import type { EasyExpansionCategory, EasyExpansionQuestion } from "../types";

const BATCH_ID = "01-history";
const PACK_ID = "built-in-history";
const RETRIEVED_AT = "2026-09-06";

type QuestionSeed = readonly [
  page: string,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const HISTORY_EASY_EXPANSION_SEEDS: readonly CategorySeed[] = [
  [
    101,
    "round-one",
    "ancient",
    "Ancient Everyday Life",
    "Antiikaja argielu",
    [
      [
        "Oil_lamp",
        "Which small vessel provided light by burning fuel through a wick?",
        "Milline väike anum andis valgust, põletades tahiga kütust?",
        "an oil lamp",
        "õlilamp",
        "The vessel held fuel that reached a flame through its wick.",
        "Anum hoidis kütust, mis jõudis tahi kaudu leegini.",
      ],
      [
        "Sundial",
        "Which timekeeper uses the Sun to cast a moving shadow?",
        "Milline ajanäitaja kasutab Päikese heidetud liikuvat varju?",
        "a sundial",
        "päikesekell",
        "Its markings show the hour as sunlight moves a shadow across the face.",
        "Selle märgistus näitab tundi, kui päikesevalgus liigutab varju üle sihverplaadi.",
      ],
      [
        "Amphora",
        "Which two-handled pottery vessel often carried wine or olive oil?",
        "Millises kahe sangaga savinõus veeti sageli veini või oliiviõli?",
        "an amphora",
        "amfora",
        "Amphorae were practical containers for storing and shipping food and drink.",
        "Amforad olid praktilised nõud toidu ja joogi hoidmiseks ning vedamiseks.",
      ],
      [
        "Ancient_Roman_bathing",
        "In Ancient Rome, which heated public facilities included pools and rooms of different temperatures?",
        "Millistes Vana-Rooma köetavates avalikes rajatistes olid basseinid ja eri temperatuuriga ruumid?",
        "Roman baths",
        "Rooma termid",
        "These complexes combined washing, exercise and social life.",
        "Need kompleksid ühendasid pesemise, liikumise ja seltsielu.",
        ["thermae"],
        ["termid"],
      ],
      [
        "Water_clock",
        "Which timekeeper measures passing hours by the controlled flow of a liquid?",
        "Milline ajanäitaja mõõdab tundide möödumist vedeliku ühtlase voolamise abil?",
        "a water clock",
        "veekell",
        "Water clocks measure time from liquid flowing into or out of a vessel.",
        "Veekell mõõdab aega anumasse voolava või sealt välja voolava vedeliku järgi.",
        ["clepsydra"],
        ["klepsüdra"],
      ],
    ],
  ],
  [
    102,
    "round-one",
    "ancient",
    "Words Before Printing",
    "Sõnad enne trükikunsti",
    [
      [
        "Roman_numerals",
        "Which number system writes values with letters such as I, V and X?",
        "Milline arvusüsteem kirjutab arve tähtedega nagu I, V ja X?",
        "Roman numerals",
        "Rooma numbrid",
        "The notation combines letter symbols whose values are added or subtracted.",
        "See arvukiri ühendab tähtsümboleid, mille väärtusi liidetakse või lahutatakse.",
        ["Roman numeral"],
        ["Rooma arvud"],
      ],
      [
        "Oral_tradition",
        "What term describes knowledge passed between generations by speaking rather than writing?",
        "Milline termin tähistab teadmiste edasiandmist põlvest põlve kõne, mitte kirja kaudu?",
        "oral tradition",
        "suuline pärimus",
        "Stories, songs and memories can be preserved through repeated telling.",
        "Lugusid, laule ja mälestusi saab säilitada neid ikka uuesti jutustades.",
      ],
      [
        "Scribe",
        "Which trained worker copied texts and kept written records?",
        "Milline väljaõppinud töötaja kopeeris tekste ja pidas kirjalikku arvestust?",
        "a scribe",
        "kirjutaja",
        "Scribes produced documents in societies where few people could write.",
        "Kirjutajad koostasid dokumente ühiskondades, kus kirjutamisoskus oli haruldane.",
        ["a copyist"],
        ["kirjatundja"],
      ],
      [
        "Wax_tablet",
        "Which reusable writing surface was scratched with a stylus and then smoothed?",
        "Millisele korduvkasutatavale kirjutuspinnale tehti krihvliga jälgi, mis hiljem maha siluti?",
        "a wax tablet",
        "vahatahvel",
        "Smoothing the surface erased old marks for reuse.",
        "Pinna silumine kustutas vanad märgid ja võimaldas tahvlit uuesti kasutada.",
      ],
      [
        "Reed_pen",
        "Which writing tool was cut from a hollow plant stem and dipped in ink?",
        "Milline kirjutusvahend lõigati õõnsast taimevarrest ja kasteti tinti?",
        "a reed pen",
        "pilliroosulg",
        "A shaped reed could carry ink and make marks on papyrus.",
        "Vormitud pilliroog hoidis tinti ning sellega sai kirjutada papüürusele.",
      ],
    ],
  ],
  [
    103,
    "round-one",
    "ancient",
    "Roads and Trade",
    "Teed ja kaubandus",
    [
      [
        "Camel_train",
        "Which desert animal carried riders and goods between distant markets?",
        "Milline kõrbeloom kandis rändureid ja kaupa kaugete turgude vahel?",
        "a camel",
        "kaamel",
        "Camel trains linked settlements across dry regions where water was scarce.",
        "Kaamelikaravanid ühendasid asulaid kuivades piirkondades, kus vett nappis.",
      ],
      [
        "Wheelbarrow",
        "Which one-wheeled handcart lets one person push a load?",
        "Milline ühe rattaga töövahend võimaldab ühel inimesel koormat lükata?",
        "a wheelbarrow",
        "käsikäru",
        "A wheelbarrow balances a load between its wheel and the person lifting its handles.",
        "Käsikäru tasakaalustab koorma ratta ja käepidemeid tõstva inimese vahel.",
        ["a one-wheeled barrow"],
        ["üherattaline käru"],
      ],
      [
        "Bullock_cart",
        "Which simple wagon was pulled by cattle and used to move heavy loads?",
        "Millist lihtsat vankrit vedasid veised ja kasutati raskete koormate veoks?",
        "an ox cart",
        "härjavanker",
        "Cattle-drawn carts carried farm produce and merchandise along land routes.",
        "Veiste veetud vankrid viisid maanteedel põllusaadusi ja kaupu.",
        ["a bullock cart", "a cattle cart"],
        ["härjakaarik", "veisekaarik"],
      ],
      [
        "Merchant_ship",
        "Which vessel carried goods for sale rather than fighting as a warship?",
        "Milline alus vedas müügiks mõeldud kaupu ega olnud sõjalaev?",
        "a merchant ship",
        "kaubalaev",
        "Merchant ships transport cargo and passengers for commercial purposes.",
        "Kaubalaevad veavad ärilisel eesmärgil lasti ja reisijaid.",
        [
          "a merchant vessel",
          "a trading vessel",
          "a merchantman",
          "a cargo ship",
        ],
        ["kaubanduslaev", "kaubaveoalus", "kaupmehelaev", "kaubaveolaev"],
      ],
      [
        "Stage_station",
        "Which station on a long road let travellers rest or exchange tired horses for fresh ones?",
        "Milline pika tee ääres asuv jaam võimaldas ränduritel puhata või väsinud hobused värskete vastu vahetada?",
        "a stage station",
        "postijaam",
        "Stage stations sped long journeys by providing rested replacement horses.",
        "Postijaamad kiirendasid pikki teekondi, pakkudes puhanud vahetushobuseid.",
        ["a relay station", "a posting station", "a staging post"],
        ["vahetusjaam", "hobupostijaam", "vahejaam"],
      ],
    ],
  ],
  [
    104,
    "round-one",
    "medieval",
    "Medieval Towns",
    "Keskaegsed linnad",
    [
      [
        "Butcher",
        "Which tradesperson cut and sold meat to town customers?",
        "Milline ametimees lõikas ja müüs linnaelanikele liha?",
        "a butcher",
        "lihunik",
        "Butchers prepared animal carcasses and sold cuts of meat.",
        "Lihunikud töötlesid loomakeresid ja müüsid lihatükke.",
      ],
      [
        "City_gate",
        "Which guarded entrance through a town wall could be closed at night?",
        "Millise linnamüüri valvatud sissepääsu sai ööseks sulgeda?",
        "a town gate",
        "linnavärav",
        "Town gates controlled movement through a fortified settlement’s walls.",
        "Linnaväravad kontrollisid liikumist läbi kindlustatud asula müüride.",
        ["a city gate"],
        ["linna värav"],
      ],
      [
        "Timber_framing",
        "Which traditional construction method leaves load-bearing wooden beams visible and fills the spaces between them?",
        "Millise traditsioonilise ehitusviisi puhul jäävad kandvad puittalad nähtavale ja nende vahed täidetakse?",
        "half-timbering",
        "vahvärk",
        "In half-timbered construction, the structural wood remains visible while other material fills the spaces.",
        "Vahvärgi puhul jääb kandev puitkarkass nähtavale ning selle vahed täidetakse muu materjaliga.",
        ["half-timbered construction"],
        ["poolpuitkonstruktsioon"],
      ],
      [
        "Pillory",
        "Which wooden punishment frame restrained an offender’s head and hands in public?",
        "Milline puust karistusvahend hoidis süüdlase pead ja käsi avalikult paigal?",
        "a pillory",
        "häbipost",
        "A pillory restrained a person by the head and hands for public punishment.",
        "Häbipost hoidis inimese pead ja käsi avaliku karistamise ajal paigal.",
      ],
      [
        "Weigh_house",
        "Which town building checked the weight of goods before they were sold?",
        "Millises linnahoones kontrolliti kaupade kaalu enne müüki?",
        "a weigh house",
        "vaekoda",
        "Public weigh houses verified goods and helped determine duties or prices.",
        "Avalikes vaekodades kontrolliti kaupu ning aidati määrata makse või hindu.",
        ["a weighing house", "a public weigh house"],
        ["kaalumaja", "kaalukoda"],
      ],
    ],
  ],
  [
    105,
    "round-one",
    "medieval",
    "Travel and Exchange",
    "Rännakud ja kaubavahetus",
    [
      [
        "Travel_literature",
        "Which personal record captures a traveller’s experiences during a journey?",
        "Milline isiklik ülestähendus talletab ränduri kogemused teekonna ajal?",
        "a travel journal",
        "rännupäevik",
        "Travellers use journals or diaries to record places, events and impressions along the way.",
        "Rändurid panevad päevikusse kirja teel nähtud paigad, sündmused ja muljed.",
        ["a travel diary", "a road journal"],
        ["reisipäevik", "teekonnapäevik"],
      ],
      [
        "Packhorse",
        "Which sure-footed horse carried goods in side bags where carts could not travel?",
        "Milline kindlajalgne hobune kandis külgkottides kaupa seal, kus vankrid liikuda ei saanud?",
        "a packhorse",
        "koormahobune",
        "Packhorses carried loads along narrow or rough routes unsuited to wheeled traffic.",
        "Koormahobused kandsid koormaid kitsastel või konarlikel teedel, kuhu vankrid ei sobinud.",
        ["a pack horse"],
        ["kandehobune"],
      ],
      [
        "Oregon_Trail",
        "What was a group of covered wagons travelling together along routes such as the Oregon Trail called?",
        "Kuidas nimetati kaetud vankrite rühma, mis liikus üheskoos sellistel teedel nagu Oregoni rada?",
        "a wagon train",
        "vankrikaravan",
        "The first migrant wagon train on the Oregon Trail was organised in 1836, and many more followed west.",
        "Esimene väljarändajate vankrikaravan Oregoni rajal moodustati 1836. aastal ning hiljem järgnes neid veel palju.",
        ["a covered-wagon train"],
        ["vankrite karavan"],
      ],
      [
        "Pilgrim_badge",
        "Which small souvenir showed that its wearer had visited a holy place?",
        "Milline väike suveniir näitas, et selle kandja oli külastanud püha paika?",
        "a pilgrim badge",
        "palveränduri märk",
        "Travellers bought badges at shrines as visible keepsakes of their journeys.",
        "Rändurid ostsid pühapaikadest märke, mis jäid nende teekonna nähtavaks mälestuseks.",
      ],
      [
        "Caravanserai",
        "Which large roadside lodging sheltered trading caravans and their animals?",
        "Milline suur teeäärne peatuspaik andis varju kaubakaravanidele ja nende loomadele?",
        "a caravanserai",
        "karavanserai",
        "Caravanserais supported long-distance trade with secure courtyards and accommodation.",
        "Karavanseraid toetasid kaugkaubandust turvalise siseõue ja öömajaga.",
        ["a caravansary", "a caravanseray", "a caravansarai"],
        [
          "karavanide öömaja",
          "karavanide võõrastemaja",
          "karavanide peatuspaik",
        ],
      ],
    ],
  ],
  [
    106,
    "round-one",
    "medieval",
    "Old Tools and Trades",
    "Vanad tööriistad ja ametid",
    [
      [
        "Windmill",
        "Which sail-powered building could grind grain without a flowing river?",
        "Milline tiibade jõul töötav hoone jahvatas vilja ka ilma voolava veeta?",
        "a windmill",
        "tuuleveski",
        "Its rotating sails transferred wind power to machinery inside.",
        "Pöörlevad tiivad kandsid tuule jõu hoone sees asuvatele masinatele.",
      ],
      [
        "Inkwell",
        "Which small desk vessel held liquid for a dipped writing tool?",
        "Milline väike laual hoitav anum sisaldas vedelikku, millesse kirjutusvahend kasteti?",
        "an inkpot",
        "tindipott",
        "The container kept a supply ready for pens that had no internal reservoir.",
        "Nõus hoiti varu sulepeade jaoks, millel puudus sisemine mahuti.",
        ["an inkwell"],
        ["tindinõu"],
      ],
      [
        "Bookbinding",
        "Which craft worker joins pages and protects them between covers?",
        "Milline käsitööline ühendab lehed ja kaitseb neid kaante vahel?",
        "a bookbinder",
        "raamatuköitja",
        "Bookbinders fasten gathered pages and add a durable outer cover.",
        "Raamatuköitjad kinnitavad kokkukogutud lehed ja lisavad vastupidavad kaaned.",
        ["a book binder"],
        ["köitja"],
      ],
      [
        "Chisel",
        "Which sharpened hand tool is pushed or tapped to cut grooves and joints in wood?",
        "Millist teritatud käsitööriista lükatakse või koputatakse soonte ja tappide lõikamiseks puitu?",
        "a chisel",
        "peitel",
        "A woodworking chisel cuts and carves timber with its sharpened edge.",
        "Puidupeitel lõikab ja uuristab puitu oma teritatud servaga.",
      ],
      [
        "Stonemasonry",
        "Which skilled worker shaped blocks for castles, churches and bridges?",
        "Milline oskustööline vormis kiviplokke kindluste, kirikute ja sildade jaoks?",
        "a stonemason",
        "kivimüürsepp",
        "Stonemasons cut and fitted stone for both structural and decorative work.",
        "Kiviraidurid lõikasid ja sobitasid kivi nii ehitiste kui ka kaunistuste jaoks.",
        ["a stonecutter"],
        ["kiviraidur"],
      ],
    ],
  ],
  [
    107,
    "round-one",
    "early-modern",
    "Navigating the Age of Sail",
    "Purjelaevade ajastul merd sõitmas",
    [
      [
        "Crow%27s_nest",
        "Which lookout platform high on a ship’s mast helped sailors spot land, hazards or other vessels?",
        "Milline kõrgel laevamastis asuv vaatlusplatvorm aitas meremeestel märgata maad, ohte või teisi aluseid?",
        "a crow’s nest",
        "mastikorv",
        "Its height gave the lookout a wider view of the sea than the deck did.",
        "Kõrgelt oli vahimehel merele avaram vaade kui laevatekilt.",
        ["a crow's nest"],
        ["vaatluskorv"],
      ],
      [
        "Conquistador",
        "What Spanish word describes the adventurers who conquered large American empires?",
        "Milline hispaania keelest pärit sõna tähistab Ameerikas suuri impeeriume vallutanud seiklejaid?",
        "a conquistador",
        "konkistadoor",
        "Conquistadors led Spanish campaigns of conquest in the Americas.",
        "Konkistadoorid juhtisid Hispaania vallutusretki Ameerikas.",
      ],
      [
        "Caravel",
        "Which small, manoeuvrable sailing ship became closely linked with Portuguese ocean voyages?",
        "Milline väike ja hea juhitavusega purjelaev seostub eriti Portugali ookeanireisidega?",
        "a caravel",
        "karavell",
        "Caravels combined a shallow draught with sails suited to ocean exploration.",
        "Karavell ühendas väikese süvise purjedega, mis sobisid ookeanireisideks.",
      ],
      [
        "Amerigo_Vespucci",
        "Whose first name inspired the name “America”?",
        "Kelle eesnimest kujunes nimi „Ameerika“?",
        "Amerigo Vespucci",
        "Amerigo Vespucci",
        "The continents were named America after published accounts associated with Vespucci.",
        "Mandrid said Vespucciga seostatud reisikirjelduste järgi nimeks Ameerika.",
        ["Vespucci"],
        ["Vespucci"],
      ],
      [
        "Maluku_Islands",
        "Which Indonesian island group drew European sailors east in search of cloves and nutmeg?",
        "Milline Indoneesia saarterühm meelitas Euroopa meresõitjaid itta nelgi ja muskaatpähkli järele?",
        "the Spice Islands",
        "Vürtsisaared",
        "The Maluku Islands were famous in Europe as a source of valuable spices.",
        "Maluku saared olid Euroopas tuntud väärtuslike vürtside allikana.",
        ["the Moluccas", "the Maluku Islands"],
        ["Molukid", "Maluku saared"],
      ],
    ],
  ],
  [
    108,
    "round-one",
    "early-modern",
    "Printing and Ideas",
    "Trükikunst ja ideed",
    [
      [
        "Paperback",
        "What kind of book has a flexible paper or card cover instead of a rigid hard cover?",
        "Millise raamatu kaaned on jäiga kõvaköite asemel painduvast paberist või kartongist?",
        "a paperback",
        "pehmekaaneline raamat",
        "A paperback uses a flexible cover and is usually lighter than a hardback.",
        "Pehmekaanelisel raamatul on painduvad kaaned ja see on tavaliselt kõvakaanelisest raamatust kergem.",
        ["a softcover", "a softback"],
        ["pehmekaaneline", "pehmeköiteline raamat"],
      ],
      [
        "Bookmark",
        "Which strip or card keeps a reader’s place between a book’s pages?",
        "Milline riba või kaart hoiab raamatu lehtede vahel lugeja järge?",
        "a bookmark",
        "järjehoidja",
        "A bookmark marks the last page reached without folding or writing on it.",
        "Järjehoidja märgib viimati loetud lehe ilma seda voltimata või sellele kirjutamata.",
        ["a book marker"],
        ["raamatu järjehoidja"],
      ],
      [
        "Table_of_contents",
        "Which list near the front of a book gives its sections and their page numbers?",
        "Milline raamatu alguses olev loend näitab peatükke ja nende leheküljenumbreid?",
        "a table of contents",
        "sisukord",
        "A table of contents helps readers find chapters or sections quickly.",
        "Sisukord aitab lugejal peatükid või osad kiiresti üles leida.",
        ["a contents page"],
        ["sisuloend"],
      ],
      [
        "Almanac",
        "Which annual booklet combined a calendar with practical information and predictions?",
        "Milline iga-aastane trükis ühendas kalendri praktilise teabe ja ennustustega?",
        "an almanac",
        "almanahh",
        "Almanacs traditionally collected calendars, astronomical data and useful reference material.",
        "Almanahhid koondasid tavaliselt kalendreid, astronoomilisi andmeid ja tarvilikku teatmematerjali.",
      ],
      [
        "Ex_libris_(bookplate)",
        "What ownership label, often decorative, is pasted inside the front cover of a volume?",
        "Milline sageli dekoratiivne omanikumärk kleebitakse köite esikaane siseküljele?",
        "a bookplate",
        "eksliibris",
        "A bookplate identifies a volume’s owner and is usually fixed to its front endpaper.",
        "Eksliibris näitab köite omanikku ja kinnitatakse tavaliselt eesmisele eeslehele.",
        ["an ex libris", "a book plate"],
        ["raamatuviit", "raamatu omanikumärk"],
      ],
    ],
  ],
  [
    109,
    "round-one",
    "early-modern",
    "Changing Kingdoms",
    "Muutuvad kuningriigid",
    [
      [
        "Regent",
        "Which temporary ruler governs when a monarch is a child, absent or unable to rule?",
        "Milline ajutine valitseja juhib riiki, kui monarh on laps, eemal või võimetu valitsema?",
        "a regent",
        "regent",
        "A regent exercises royal authority until the monarch can rule personally.",
        "Regent kasutab kuninglikku võimu seni, kuni monarh saab ise valitseda.",
        ["a royal regent"],
        ["riigihoidja"],
      ],
      [
        "Abdication",
        "What is a monarch’s formal act of giving up the throne?",
        "Kuidas nimetatakse monarhi ametlikku otsust oma valitsemine lõpetada?",
        "abdication",
        "abdikatsioon",
        "Abdication ends a monarch’s reign by formally surrendering royal authority.",
        "Abdikatsioon lõpetab monarhi valitsusaja kuninglikust võimust ametlikult loobumisega.",
        ["royal abdication"],
        ["troonist loobumine"],
      ],
      [
        "House_of_Tudor",
        "Which royal house used a red-and-white rose as its emblem?",
        "Milline kuningakoda kasutas oma sümbolina puna-valget roosi?",
        "the Tudor dynasty",
        "Tudorite dünastia",
        "The Tudor rose joined symbols associated with the houses of Lancaster and York.",
        "Tudorite roos ühendas Lancasteri ja Yorki dünastiatega seotud sümbolid.",
        ["the Tudors"],
        ["Tudorid"],
      ],
      [
        "Acts_of_Union_1707",
        "Which laws joined England and Scotland into the Kingdom of Great Britain?",
        "Millised seadused ühendasid Inglismaa ja Šotimaa Suurbritannia kuningriigiks?",
        "the Acts of Union",
        "uniooniaktid",
        "The 1707 laws united the two parliaments and created Great Britain.",
        "1707. aasta seadused ühendasid kaks parlamenti ja lõid Suurbritannia.",
        ["the Act of Union"],
        ["uniooniakt"],
      ],
      [
        "Glorious_Revolution",
        "Which largely bloodless change of monarch brought William and Mary to the English throne?",
        "Milline suuresti veretu monarhivahetus tõi Inglismaa troonile Williami ja Mary?",
        "the Glorious Revolution",
        "Kuulus revolutsioon",
        "The change removed James II and established a new constitutional settlement.",
        "See muutus kõrvaldas James II ning pani aluse uuele põhiseaduslikule korraldusele.",
      ],
    ],
  ],
  [
    110,
    "round-one",
    "political",
    "Rights and Democracy",
    "Õigused ja demokraatia",
    [
      [
        "Ballot_box",
        "Into which sealed container are completed voting papers placed?",
        "Millisesse suletud anumasse pannakse täidetud hääletussedelid?",
        "a ballot box",
        "hääletuskast",
        "The locked container keeps cast papers together until counting begins.",
        "Lukustatud anum hoiab täidetud hääletussedelid koos kuni häälte lugemise alguseni.",
      ],
      [
        "Voting_booth",
        "Which screened space lets a person mark a vote in private?",
        "Milline varjatud ruum võimaldab inimesel oma valiku salaja märkida?",
        "a polling booth",
        "hääletuskabiin",
        "Screens around the booth protect the secrecy of each voter’s choice.",
        "Kabiini seinad kaitsevad iga valija valiku salajasust.",
        ["a voting booth"],
        ["valimiskabiin"],
      ],
      [
        "Women%27s_suffrage",
        "Which movement campaigned so that women could vote in elections on the same terms as men?",
        "Milline liikumine taotles, et naised saaksid valimistel meestega võrdsetel alustel hääletada?",
        "the women’s suffrage movement",
        "naiste valimisõiguse liikumine",
        "The movement sought voting rights for women in elections.",
        "Liikumine taotles naistele valimistel hääleõigust.",
        ["the suffrage movement"],
        ["sufražistlik liikumine"],
      ],
      [
        "Voter_registration",
        "Which process puts an eligible person’s name on the official electoral roll?",
        "Millise toiminguga lisatakse hääleõigusliku inimese nimi ametlikku valijate nimekirja?",
        "voter registration",
        "valijaks registreerimine",
        "Registration establishes who may receive a ballot in systems that require an electoral roll.",
        "Registreerimine määrab valijate nimekirja kasutavates süsteemides, kellel on õigus hääletussedelile.",
      ],
      [
        "Bill_of_Rights_1689",
        "Which English statute enacted in December 1689 limited royal power and affirmed Parliament’s rights?",
        "Milline 1689. aasta detsembris vastu võetud Inglise seadus piiras kuningavõimu ja kinnitas parlamendi õigusi?",
        "the Bill of Rights",
        "õiguste deklaratsioon",
        "The 1689 settlement restricted the crown and confirmed parliamentary rights.",
        "1689. aasta kokkulepe piiras krooni võimu ja kinnitas parlamendi õigusi.",
        ["the English Bill of Rights"],
        ["Inglise õiguste deklaratsioon"],
      ],
    ],
  ],
  [
    111,
    "round-two",
    "political",
    "Peaceful Protest",
    "Rahumeelne protest",
    [
      [
        "Hunger_strike",
        "What protest involves deliberately refusing food?",
        "Millise protesti puhul keeldutakse teadlikult toidust?",
        "a hunger strike",
        "näljastreik",
        "Hunger strikers risk their health to draw attention to a demand or injustice.",
        "Näljastreikijad seavad oma tervise ohtu, et juhtida tähelepanu nõudmisele või ebaõiglusele.",
      ],
      [
        "Megaphone",
        "Which cone-shaped device can make a speaker’s voice louder at a demonstration?",
        "Milline koonusekujuline seade muudab kõneleja hääle meeleavaldusel valjemaks?",
        "a megaphone",
        "ruupor",
        "A megaphone directs and amplifies a person’s voice toward a crowd.",
        "Ruupor suunab ja võimendab inimese häält rahvahulga poole.",
        ["a bullhorn"],
        ["hääleruupor"],
      ],
      [
        "Freedom_songs",
        "Which songs, often adapted from spirituals and hymns, united marchers in the US civil-rights movement?",
        "Millised laulud, sageli spirituaalidest ja kirikulauludest kohandatud, ühendasid USA kodanikuõiguste liikumise marssijaid?",
        "freedom songs",
        "vabaduslaulud",
        "Freedom songs gave the movement a shared voice and helped sustain courage during marches and meetings.",
        "Vabaduslaulud andsid liikumisele ühise hääle ning julgustasid marssijaid ja koosolekutel osalejaid.",
        ["a freedom song"],
        ["vabaduslaul"],
      ],
      [
        "Candlelight_vigil",
        "What peaceful gathering is marked by people holding small lights after dark?",
        "Kuidas nimetatakse rahumeelset kogunemist, kus inimesed hoiavad pimedal ajal käes väikseid tulesid?",
        "a candlelight vigil",
        "küünlavigiil",
        "Participants use candlelight to express remembrance, solidarity or protest.",
        "Osalejad väljendavad küünlavalgusega mälestust, solidaarsust või protesti.",
        ["a candle vigil"],
        ["küünlavalgusvigiil"],
      ],
      [
        "Samizdat",
        "What name was given to banned writing secretly copied and circulated by dissidents in the Soviet bloc?",
        "Kuidas nimetati Nõukogude blokis keelatud tekste, mida teisitimõtlejad salaja kopeerisid ja levitasid?",
        "samizdat",
        "samizdat",
        "Samizdat bypassed censorship through clandestine copying and person-to-person distribution.",
        "Samizdati abil hiiliti tsensuurist mööda, kopeerides tekste salaja ja levitades neid käest kätte.",
        ["self-publishing"],
        ["omakirjastus"],
      ],
    ],
  ],
  [
    112,
    "round-two",
    "political",
    "International Cooperation",
    "Rahvusvaheline koostöö",
    [
      [
        "International_Criminal_Police_Organization",
        "Which international police organisation issues colour-coded notices, including Red Notices?",
        "Milline rahvusvaheline politseiorganisatsioon väljastab värvide järgi nimetatud teateid, sealhulgas punaseid teateid?",
        "INTERPOL",
        "INTERPOL",
        "INTERPOL helps police in different countries exchange notices and criminal information.",
        "INTERPOL aitab eri riikide politseil vahetada teateid ja kuritegevusega seotud teavet.",
      ],
      [
        "European_Broadcasting_Union",
        "Which organisation unites public-service television and radio networks across countries and organises the Eurovision Song Contest?",
        "Milline organisatsioon ühendab eri riikide avalik-õiguslikke tele- ja raadiojaamu ning korraldab Eurovisiooni lauluvõistlust?",
        "the European Broadcasting Union",
        "Euroopa Ringhäälingute Liit",
        "The alliance of public-service broadcasters produces Eurovision with its member organisations.",
        "Avalik-õiguslike ringhäälingute liit korraldab Eurovisiooni koos oma liikmesorganisatsioonidega.",
        ["EBU"],
        ["EBU"],
      ],
      [
        "OPEC",
        "Which group, founded in Baghdad in 1960, coordinates its members’ petroleum policies?",
        "Milline 1960. aastal Bagdadis asutatud rühm koordineerib oma liikmete naftapoliitikat?",
        "OPEC",
        "OPEC",
        "Its member countries coordinate policies affecting the supply of oil to world markets.",
        "Selle liikmesriigid koordineerivad maailmaturu naftapakkumist mõjutavat poliitikat.",
        ["the Organization of the Petroleum Exporting Countries"],
        ["Naftat Eksportivate Riikide Organisatsioon"],
      ],
      [
        "World_Anti-Doping_Agency",
        "Which body, created in 1999 with support from the Olympic movement and governments, coordinates international efforts to keep sport drug-free?",
        "Milline 1999. aastal olümpialiikumise ja valitsuste toel loodud asutus koordineerib rahvusvahelisi jõupingutusi puhta spordi nimel?",
        "the World Anti-Doping Agency",
        "Maailma Antidopingu Agentuur",
        "The agency promotes and coordinates international cooperation against doping in sport.",
        "Agentuur edendab ja koordineerib rahvusvahelist koostööd spordidopingu vastu.",
        ["WADA"],
        ["WADA"],
      ],
      [
        "Geneva_Conventions",
        "Which international conventions protect wounded soldiers, prisoners of war and civilians during armed conflict?",
        "Millised rahvusvahelised konventsioonid kaitsevad relvakonfliktis haavatud sõdureid, sõjavange ja tsiviilisikuid?",
        "the Geneva Conventions",
        "Genfi konventsioonid",
        "The agreements set humanitarian protections for people who are not taking part in fighting.",
        "Kokkulepped sätestavad humanitaarkaitse inimestele, kes lahingutegevuses ei osale.",
        ["the Geneva Convention"],
        ["Genfi konventsioon"],
      ],
    ],
  ],
  [
    113,
    "round-two",
    "social",
    "Home and Household",
    "Kodu ja majapidamine",
    [
      [
        "Fireplace",
        "Which built-in open structure holds a room fire beneath a chimney?",
        "Milline ruumi ehitatud avatud rajatis hoiab tuld korstna all?",
        "a fireplace",
        "kamin",
        "A fireplace contains a fire in a wall opening connected to a chimney.",
        "Kaminas põleb tuli seinaavas, mis on ühendatud korstnaga.",
      ],
      [
        "Hot-water_bottle",
        "Which sealed rubber or plastic container is filled from a kettle and tucked beneath bedcovers for warmth?",
        "Milline suletav kummist või plastist anum täidetakse veekeetjast ja pannakse voodiriiete alla sooja andma?",
        "a hot-water bottle",
        "soojaveekott",
        "The stored hot water releases heat slowly beneath the bedcovers.",
        "Anumas olev kuum vesi annab voodiriiete all aeglaselt soojust.",
        ["a hot water bottle"],
        ["kuumaveekott"],
      ],
      [
        "Washboard_(laundry)",
        "Which ridged board helped people scrub dirt from wet clothes?",
        "Milline sooniline laud aitas märgadest rõivastest mustust välja hõõruda?",
        "a washboard",
        "pesulaud",
        "Laundry was rubbed against the board’s corrugated surface before mechanical washing became common.",
        "Enne pesumasinate levikut hõõruti pesu vastu laua lainelist pinda.",
      ],
      [
        "Chamber_pot",
        "Which portable vessel was kept indoors for use as a toilet at night?",
        "Millist kaasaskantavat anumat hoiti toas, et seda öösel tualetina kasutada?",
        "a chamber pot",
        "ööpott",
        "Chamber pots served as indoor toilets where plumbing was absent or inconvenient.",
        "Ööpotte kasutati toas tualetina seal, kus puudus kanalisatsioon või käimlasse oli tülikas minna.",
      ],
      [
        "Icebox",
        "Which insulated cupboard kept food cool with a delivered block of frozen water?",
        "Milline isoleeritud kapp hoidis toitu jahedana kohale toodud külmunud veeploki abil?",
        "an icebox",
        "jääkast",
        "A large block inside supplied cooling before electric refrigerators.",
        "Enne elektrikülmikuid jahutas kapi sisemust suur jääplokk.",
        ["an ice box"],
        ["jääkapp"],
      ],
    ],
  ],
  [
    114,
    "round-two",
    "social",
    "Clothing and Fashion",
    "Rõivad ja mood",
    [
      [
        "Jeans",
        "Which durable trousers take their common name from Genoa and are usually made of denim?",
        "Millised vastupidavad püksid on tavaliselt tehtud teksariidest ja saanud oma levinud nime Genova järgi?",
        "blue jeans",
        "teksapüksid",
        "Jeans developed from hard-wearing work clothes and became everyday fashion worldwide.",
        "Teksapüksid arenesid vastupidavatest töörõivastest ning muutusid kogu maailmas igapäevamoeks.",
        ["jeans"],
        ["teksad"],
      ],
      [
        "Bow_tie",
        "Which neckwear forms two symmetrical loops when tied?",
        "Milline kaelarõivas moodustab sidumisel kaks sümmeetrilist aasa?",
        "a bow tie",
        "kikilips",
        "A bow tie forms a symmetrical knot with a loop on each side.",
        "Kikilips moodustab sümmeetrilise sõlme, mille mõlemal küljel on aas.",
        ["a bowtie"],
        ["lehvlips"],
      ],
      [
        "Miniskirt",
        "Which above-the-knee garment became a symbol of youthful 1960s fashion?",
        "Milline põlvest kõrgem rõivaese sai 1960. aastate noortemoe sümboliks?",
        "the miniskirt",
        "miniseelik",
        "The miniskirt became closely associated with the new youth styles of the decade.",
        "Miniseelik seostus tihedalt kümnendi uute noortestiilidega.",
        ["a mini-skirt"],
        ["mini-seelik"],
      ],
      [
        "Little_black_dress",
        "Which simple dark garment popularised by Coco Chanel became a modern fashion classic?",
        "Millisest Coco Chaneli populariseeritud lihtsast tumedast rõivast sai moodne moeklassika?",
        "the little black dress",
        "väike must kleit",
        "Coco Chanel helped popularise the little black dress in the 1920s.",
        "Coco Chanel aitas väikese musta kleidi 1920. aastatel populaarseks muuta.",
        ["an LBD"],
        ["LBD"],
      ],
      [
        "Crinoline",
        "Which cage-like frame held a nineteenth-century skirt away from the legs?",
        "Milline puuritaoline raam hoidis 19. sajandi seelikut jalgadest eemal?",
        "a crinoline",
        "krinoliin",
        "Hooped crinolines created a wide skirt shape without layers of heavy petticoats.",
        "Rõngastega krinoliin andis seelikule laia kuju ilma raskete alusseelikukihtideta.",
        ["a hoop skirt"],
        ["rõngasseelik"],
      ],
    ],
  ],
  [
    115,
    "round-two",
    "social",
    "Work and School",
    "Töö ja kool",
    [
      [
        "Pencil_sharpener",
        "Which small tool shaves wood from a pencil to restore its point?",
        "Milline väike tööriist eemaldab pliiatsilt puitu, et selle ots uuesti teravaks teha?",
        "a pencil sharpener",
        "pliiatsiteritaja",
        "Its blade removes wood and graphite until the pencil has a usable point again.",
        "Selle tera eemaldab puitu ja grafiiti, kuni pliiatsi ots on taas kirjutamiseks terav.",
        ["a sharpener", "a pencil pointer"],
        ["teritaja", "pliiatsiteriti"],
      ],
      [
        "Blackboard",
        "Which dark reusable surface did teachers cover with pale writing?",
        "Millise tumeda korduvkasutatava pinna katsid õpetajad heleda kirjaga?",
        "a blackboard",
        "klassitahvel",
        "The large surface let a whole class follow the same written lesson.",
        "Suur pind võimaldas kogu klassil sama kirjalikku õppetükki jälgida.",
        ["a chalkboard"],
        ["kriiditahvel"],
      ],
      [
        "Lunchbox",
        "Which portable container carries a meal to school or work?",
        "Millises kaasaskantavas karbis viiakse söök kooli või tööle?",
        "a lunchbox",
        "lõunakarp",
        "Lunchboxes keep a packed meal together for eating away from home.",
        "Lõunakarp hoiab kodust kaasa võetud eine koos, et seda mujal süüa.",
        ["a lunch box"],
        ["einekarp"],
      ],
      [
        "Square_academic_cap",
        "Which flat square hat with a tassel do students traditionally toss after receiving their diplomas?",
        "Millise lameda nelinurkse ülaosa ja tutiga mütsi viskavad õppurid traditsiooniliselt pärast diplomi saamist õhku?",
        "a graduation cap",
        "lõpumüts",
        "The square academic cap is part of ceremonial dress at many graduations.",
        "Nelinurkne akadeemiline müts kuulub paljudel lõpuaktustel piduliku riietuse juurde.",
        ["a mortarboard", "an academic cap", "a square academic cap"],
        ["akadeemiline nelinurkmüts", "akadeemiline müts", "nelinurkmüts"],
      ],
      [
        "Fountain_pen",
        "Which refillable writing tool feeds liquid ink to a metal nib?",
        "Milline täidetav kirjutusvahend juhib vedela tindi metallist suleotsani?",
        "a fountain pen",
        "täitesulepea",
        "A reservoir supplies ink continuously, avoiding repeated dipping.",
        "Mahuti annab tinti pidevalt, nii et sulepead ei pea korduvalt tindipotti kastma.",
      ],
    ],
  ],
  [
    116,
    "round-two",
    "social",
    "Leisure Through Time",
    "Vaba aeg läbi ajaloo",
    [
      [
        "Kite",
        "Which lightweight toy flies on a long string when the wind lifts it?",
        "Milline kerge mänguasi lendab pika nööri otsas, kui tuul selle üles tõstab?",
        "a kite",
        "tuulelohe",
        "Airflow over its surface creates lift while the string keeps it controlled.",
        "Õhuvool tekitab selle pinna kohal tõstejõu ja nöör hoiab mänguasja kontrolli all.",
        ["a toy kite"],
        ["lennulohe"],
      ],
      [
        "Kaleidoscope",
        "Which viewing tube uses mirrors and coloured pieces to make changing symmetrical patterns?",
        "Milline vaatlustoru loob peeglite ja värviliste tükkide abil muutuvaid sümmeetrilisi mustreid?",
        "a kaleidoscope",
        "kaleidoskoop",
        "Mirrors multiply the reflected pieces into a pattern that changes as the tube turns.",
        "Peeglid mitmekordistavad värviliste tükkide peegeldusi ning moodustavad mustri, mis toru pööramisel muutub.",
      ],
      [
        "Amateur_theatre",
        "What term describes stage productions created by unpaid local participants in their free time?",
        "Kuidas nimetatakse lavastusi, mida kohalikud osalejad teevad palgata ja vabal ajal?",
        "amateur theatre",
        "harrastusteater",
        "Amateur companies let local participants produce plays as a shared leisure activity.",
        "Harrastustrupid võimaldavad kohalikel inimestel ühise ajaviitena näidendeid lavastada.",
        ["amateur theater", "amateur dramatics"],
        ["amatöörteater", "harrastusnäitemäng"],
      ],
      [
        "Maypole",
        "Around which decorated pole do people traditionally dance at spring celebrations?",
        "Millise kaunistatud posti ümber tantsitakse traditsiooniliselt kevadpidustustel?",
        "a maypole",
        "maipuu",
        "Maypole dancing became a familiar feature of seasonal festivities in parts of Europe.",
        "Maipuu ümber tantsimine sai osas Euroopast tuntud kevadpidustuste osaks.",
      ],
      [
        "Magic_lantern",
        "Which early projector cast painted glass images onto a wall?",
        "Milline varajane projektor heitis maalitud klaaspildid seinale?",
        "a magic lantern",
        "võlulatern",
        "A lamp and lens enlarged transparent pictures for an audience.",
        "Lamp ja lääts suurendasid läbipaistvaid pilte, et publik neid näeks.",
        ["laterna magica"],
        ["laterna magica"],
      ],
    ],
  ],
  [
    117,
    "round-two",
    "economic",
    "Money and Marketplaces",
    "Raha ja turuplatsid",
    [
      [
        "Price_tag",
        "Which small label on an item tells a shopper how much it costs?",
        "Milline väike silt kaubal ütleb ostjale, kui palju see maksab?",
        "a price tag",
        "hinnasilt",
        "A price tag displays the amount a seller asks for an item.",
        "Hinnasilt näitab summat, mida müüja kauba eest küsib.",
        ["a price label"],
        ["hinnalipik"],
      ],
      [
        "Piggy_bank",
        "Which animal-shaped container encourages children to save small change?",
        "Milline loomakujuline anum innustab lapsi münte koguma?",
        "a piggy bank",
        "hoiupõrsas",
        "A slot lets coins enter while the container keeps savings together.",
        "Pilu laseb mündid sisse ja anum hoiab säästud koos.",
        ["a money box"],
        ["rahakassa"],
      ],
      [
        "Market_stall",
        "Which small structure lets a trader display and sell goods at a market?",
        "Milline väike rajatis võimaldab kauplejal turul kaupa välja panna ja müüa?",
        "a market stall",
        "turulet",
        "A market stall or booth houses merchandise at a street market or fair.",
        "Turulett või -putka mahutab tänavaturul või laadal müüdava kauba.",
        ["a market stand", "a market booth"],
        ["müügilett", "turuputka"],
      ],
      [
        "Barter",
        "What exchange system trades goods or services directly without currency?",
        "Millises vahetussüsteemis kaubeldakse kaupade või teenustega otse ilma rahata?",
        "barter",
        "vahetuskaubandus",
        "Barter swaps one useful thing or service for another without a monetary intermediary.",
        "Vahetuskaubanduses vahetatakse üks kasulik asi või teenus teise vastu ilma raha vahenduseta.",
      ],
      [
        "Credit_card",
        "Which payment card lets its holder carry an unpaid borrowed balance from month to month?",
        "Milline maksekaart võimaldab kasutajal laenatud summa tasumata jääki kuust kuusse edasi kanda?",
        "a credit card",
        "krediitkaart",
        "Unlike a charge card, it offers revolving credit, so an unpaid balance can remain after the monthly payment.",
        "Korduvkasutatav krediit võimaldab osa võlast pärast kuumakset alles jätta, selle asemel et kogu saldo korraga tasuda.",
      ],
    ],
  ],
  [
    118,
    "round-two",
    "economic",
    "Industrial Everyday Products",
    "Tööstusaja igapäevatooted",
    [
      [
        "Bottle_cap",
        "Which small closure is twisted or pried off the top of a bottled drink?",
        "Milline väike sulgur keeratakse või kangutatakse joogipudeli pealt ära?",
        "a bottle cap",
        "pudelikork",
        "A bottle cap seals the opening to keep the drink inside and contaminants out.",
        "Pudelikork sulgeb ava, hoides joogi pudelis ja mustuse väljas.",
        ["a bottle top"],
        ["pudelikapsel"],
      ],
      [
        "Egg_carton",
        "Which moulded package protects a dozen fragile breakfast ingredients in separate cups and usually closes with a lid?",
        "Milline vormitud pakend kaitseb tosinat habrast hommikusöögi koostisosa eraldi pesades ja sulgub tavaliselt kaanega?",
        "an egg carton",
        "munakarp",
        "Its shaped cups separate and cushion eggs during storage and transport.",
        "Selle vormitud pesad hoiavad munad lahus ja pehmendavad lööke hoidmisel ning veol.",
        ["an egg box"],
        ["munade karp"],
      ],
      [
        "Stapler",
        "Which desk tool drives a small bent metal fastener through sheets of paper?",
        "Milline lauatööriist surub väikese painutatud metallkinniti läbi paberilehtede?",
        "a stapler",
        "klammerdaja",
        "A stapler joins sheets by driving a metal staple through them and folding its ends.",
        "Klammerdaja ühendab lehed, surudes metallklambri neist läbi ja painutades selle otsad.",
        ["a paper stapler"],
        ["paberiklammerdaja"],
      ],
      [
        "Wristwatch",
        "Which personal timepiece moved from a pocket onto a strap around the arm?",
        "Milline isiklik ajanäitaja kolis taskust ümber käsivarre kinnitatud rihmale?",
        "a wristwatch",
        "käekell",
        "Mass production and military use helped make wristwatches common in the twentieth century.",
        "Masstootmine ja sõjaline kasutus aitasid käekellal 20. sajandil laialt levida.",
        ["a wrist watch"],
        ["randmekell"],
      ],
      [
        "Safety_razor",
        "Which shaving tool protects the skin by exposing only the edge of its blade?",
        "Milline raseerimisvahend kaitseb nahka, jättes nähtavale vaid tera serva?",
        "a safety razor",
        "turvahabemenuga",
        "A guard limits how much of the cutting edge can press against the skin.",
        "Kaitse piirab seda, kui palju lõikeserva saab vastu nahka suruda.",
        ["a double-edged safety razor"],
        ["ohutusraseerija"],
      ],
    ],
  ],
  [
    119,
    "round-two",
    "archaeological",
    "Historic Symbols and Records",
    "Ajaloolised sümbolid ja ülestähendused",
    [
      [
        "Sceptre",
        "Which decorated staff carried by a monarch symbolises authority?",
        "Milline monarhi käes kantav kaunistatud sau sümboliseerib valitsejavõimu?",
        "a sceptre",
        "skepter",
        "A sceptre is a ceremonial staff representing a ruler’s authority.",
        "Skepter on valitseja võimu tähistav tseremoniaalne sau.",
        ["a scepter"],
        ["valitsuskepp"],
      ],
      [
        "Liberty_Bell",
        "Which cracked bronze symbol in Philadelphia is traditionally associated with American independence?",
        "Milline mõranenud pronkssümbol Philadelphias seostub traditsiooniliselt Ameerika iseseisvusega?",
        "the Liberty Bell",
        "Vabaduskell",
        "The bell became an enduring symbol of American independence despite its famous crack.",
        "Kuulsast mõrast hoolimata sai sellest kellast Ameerika iseseisvuse püsiv sümbol.",
        ["the Philadelphia Liberty Bell"],
        ["Liberty Bell"],
      ],
      [
        "Signet_ring",
        "Which piece of jewellery was pressed into wax to leave a ruler’s personal mark on a document?",
        "Milline ehe suruti vahasse, et jätta valitseja isiklik märk dokumendile?",
        "a signet ring",
        "pitsatsõrmus",
        "A signet ring bears an engraved design that can make an identifying impression in wax.",
        "Pitsatsõrmusel on graveeritud kujund, millega saab vahasse jätta isikut tuvastava jäljendi.",
        ["a seal ring", "a signet"],
        ["signetsõrmus", "pitserisõrmus"],
      ],
      [
        "Sword_of_State",
        "What formal name is given to the bladed royal regalia carried before a monarch in processions as a sign of authority?",
        "Kuidas nimetatakse ametlikult teraga kuninglikku regaali, mida kanti rongkäigus monarhi ees võimu sümbolina?",
        "a Sword of State",
        "riigimõõk",
        "A Sword of State represents royal authority and is carried in formal processions.",
        "Riigimõõk tähistab kuninglikku võimu ja seda kantakse ametlikes rongkäikudes.",
      ],
      [
        "Domesday_Book",
        "Which vast survey ordered by William the Conqueror recorded landholding across much of England?",
        "Milline William Vallutaja tellitud ulatuslik ülevaade jäädvustas maaomandi suuremas osas Inglismaast?",
        "the Domesday Book",
        "Viimsepäevaraamat",
        "The survey compiled in 1086 recorded landholders and resources for the king’s administration.",
        "1086. aastal koostatud ülevaade jäädvustas kuninga halduse jaoks maaomanikud ja varad.",
        ["Domesday"],
        ["Domesday Book"],
      ],
    ],
  ],
  [
    120,
    "round-two",
    "cultural",
    "Ceremonies and Public Memory",
    "Tseremooniad ja avalik mälu",
    [
      [
        "Moment_of_silence",
        "What quiet observance asks a group to pause together in remembrance?",
        "Millise vaikse mälestusviisi puhul peatub rühm üheskoos?",
        "a minute of silence",
        "vaikusminut",
        "A shared silence creates a simple public act of respect or mourning.",
        "Ühine vaikus loob lihtsa avaliku austuse või leina väljenduse.",
        ["a moment of silence"],
        ["leinaseisak"],
      ],
      [
        "Commemorative_stamp",
        "Which special postal issue marks an anniversary, person or event?",
        "Milline eriline postiväljaanne tähistab tähtpäeva, inimest või sündmust?",
        "a commemorative stamp",
        "mälestusmark",
        "Its design records a chosen subject while the item still serves as postage.",
        "Selle kujundus jäädvustab valitud teema, kuid eset saab endiselt kasutada postimaksu tasumiseks.",
      ],
      [
        "Eternal_flame",
        "Which continuously burning light often symbolises lasting remembrance?",
        "Milline pidevalt põlev tuli sümboliseerib sageli kestvat mälestust?",
        "an eternal flame",
        "igavene tuli",
        "Memorial sites use an enduring flame as a sign that remembrance continues.",
        "Mälestuspaikades tähistab kestev tuli mälestuse püsimist.",
      ],
      [
        "Blue_plaque",
        "Which coloured sign on a building can mark its link with a notable person or event in Britain?",
        "Milline värviline märk hoonel võib Suurbritannias tähistada selle seost tuntud inimese või sündmusega?",
        "a blue plaque",
        "sinine mälestustahvel",
        "Blue plaques identify places connected with notable lives and events.",
        "Sinised mälestustahvlid tähistavad tuntud inimeste ja sündmustega seotud paiku.",
      ],
      [
        "Stolperstein",
        "Which small concrete cube bearing a brass plate is set into a pavement to remember a victim of Nazi persecution?",
        "Milline messingplaadiga väike betoonkuubik paigaldatakse kõnniteesse natside tagakiusamise ohvri mälestuseks?",
        "a Stolperstein",
        "komistuskivi",
        "Each Stolperstein records a person’s name and fate near a place connected with their life.",
        "Iga komistuskivi jäädvustab inimese nime ja saatuse tema eluga seotud paiga lähedal.",
        ["Stolpersteine"],
        ["Stolperstein"],
      ],
    ],
  ],
];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLocaleLowerCase("en")
    .replace(/%[0-9a-f]{2}/giu, "-")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    page,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const subjectKey = `history:${slug(page)}`;
  return {
    clueId: `built-in-history-easy-expansion-${clueNumber}`,
    key: `history-easy-expansion:${categorySetId}:${tier}`,
    factKey: `history-easy-expansion:${slug(page)}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(page).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${page}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    },
  };
}

export const HISTORY_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  HISTORY_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
