import type { EasyExpansionCategory, EasyExpansionQuestion } from "../types";

const BATCH_ID = "02-geography";
const PACK_ID = "built-in-geography";
const RETRIEVED_AT = "2026-09-06";

type QuestionSeed = readonly [
  page: string,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const GEOGRAPHY_EASY_EXPANSION_SEEDS: readonly CategorySeed[] = [
  [
    101,
    "round-one",
    "countries-capitals",
    "Countries from Their Capitals",
    "Riigid pealinnade järgi",
    [
      [
        "Qatar",
        "Doha is the capital of which small Gulf country that has hosted the FIFA World Cup?",
        "Millise jalgpalli maailmameistrivõistlusi võõrustanud Pärsia lahe väikeriigi pealinn on Doha?",
        "Qatar",
        "Katar",
        "Qatar occupies a peninsula in the Persian Gulf, and Doha is its capital and largest city.",
        "Katar asub Pärsia lahte ulatuval poolsaarel ning Doha on selle pealinn ja suurim linn.",
      ],
      [
        "Kuwait",
        "What small Gulf country north of Saudi Arabia has a capital city of the same name?",
        "Millise Saudi Araabiast põhja pool asuva väikese Pärsia lahe riigi pealinn on Al-Kuwayt?",
        "Kuwait",
        "Kuveit",
        "Kuwait lies at the head of the Persian Gulf, and Kuwait City is its capital.",
        "Kuveit asub Pärsia lahe sopis ning Al-Kuwayt on selle pealinn.",
      ],
      [
        "Costa_Rica",
        "San José is the capital of which Central American country between Nicaragua and Panama?",
        "Millise Nicaragua ja Panama vahel asuva Kesk-Ameerika riigi pealinn on San José?",
        "Costa Rica",
        "Costa Rica",
        "Costa Rica lies between Nicaragua and Panama, with San José as its capital.",
        "Costa Rica asub Nicaragua ja Panama vahel ning selle pealinn on San José.",
      ],
      [
        "Guatemala",
        "Which Central American country borders Mexico and shares its name with its capital city?",
        "Milline Kesk-Ameerika riik piirneb Mehhikoga ja kannab oma pealinnaga sama nime?",
        "Guatemala",
        "Guatemala",
        "Guatemala borders Mexico, and its capital is Guatemala City.",
        "Guatemala piirneb Mehhikoga ning riigi pealinn kannab samuti nime Guatemala.",
      ],
      [
        "North_Macedonia",
        "Skopje is the capital of which landlocked Balkan country?",
        "Millise merepiirita Balkani riigi pealinn on Skopje?",
        "North Macedonia",
        "Põhja-Makedoonia",
        "North Macedonia is a landlocked Balkan state whose capital and largest city is Skopje.",
        "Põhja-Makedoonia on merepiirita Balkani riik, mille pealinn ja suurim linn on Skopje.",
        ["the Republic of North Macedonia"],
        ["Põhja-Makedoonia Vabariik"],
      ],
    ],
  ],
  [
    102,
    "round-one",
    "cities",
    "Cities by Their Landmarks",
    "Linnad vaatamisväärsuste järgi",
    [
      [
        "Zagreb",
        "Which Croatian capital has St Mark’s Church with its colourful tiled roof?",
        "Millises Horvaatia pealinnas asub värvikireva katusekivimustriga Püha Markuse kirik?",
        "Zagreb",
        "Zagreb",
        "St Mark’s Church and its patterned roof are a familiar sight in Zagreb’s old town.",
        "Püha Markuse kirik ja selle mustriline katus on Zagrebi vanalinna tuntud vaatepilt.",
      ],
      [
        "Krak%C3%B3w",
        "Which Polish city has Wawel Castle and a vast medieval market square?",
        "Millises Poola linnas asuvad Waweli loss ja suur keskaegne turuväljak?",
        "Kraków",
        "Kraków",
        "Kraków grew around Wawel Castle and its historic Main Market Square.",
        "Kraków kujunes Waweli lossi ja ajaloolise peaturuväljaku ümber.",
        ["Krakow"],
        ["Krakow"],
      ],
      [
        "Auckland",
        "Which New Zealand city is marked by the Sky Tower and is nicknamed the City of Sails?",
        "Milline Uus-Meremaa linn on tuntud Sky Toweri poolest ja kannab hüüdnime „Purjede linn”?",
        "Auckland",
        "Auckland",
        "Auckland’s harbours support its sailing culture, while the Sky Tower dominates its skyline.",
        "Aucklandi sadamad on linna purjetamiskultuuri keskmes ning Sky Tower paistab linnasiluetis kaugele.",
      ],
      [
        "Cusco",
        "Which Peruvian city was the capital of the Inca Empire and lies near Machu Picchu?",
        "Milline Peruu linn oli inkade impeeriumi pealinn ja asub Machu Picchu lähedal?",
        "Cusco",
        "Cusco",
        "Cusco was the Inca capital, and Machu Picchu lies in the surrounding Andes.",
        "Cusco oli inkade pealinn ning Machu Picchu asub seda ümbritsevates Andides.",
        ["Cuzco"],
        ["Cuzco"],
      ],
      [
        "Varanasi",
        "Which Indian holy city is famous for long flights of riverside steps called ghats?",
        "Milline India püha linn on tuntud Gangese kaldale rajatud pikkade trepistike ehk ghat'ide poolest?",
        "Varanasi",
        "Varanasi",
        "Varanasi’s ghats line the Ganges and form the city’s best-known riverfront landscape.",
        "Varanasi ghat'id ehk jõeäärsed trepistikud ääristavad Gangese kallast ja on linna tuntumaid vaatamisväärsusi.",
        ["Benares"],
        ["Benares"],
      ],
    ],
  ],
  [
    103,
    "round-one",
    "physical-geography",
    "Landscape Features",
    "Maastiku elemendid",
    [
      [
        "Oasis",
        "In a desert, which fertile place forms around a reliable water source?",
        "Milline viljakas paik kõrbes tekib püsiva veeallika ümber?",
        "an oasis",
        "oaas",
        "An oasis supports plants and settlement because water is available in an otherwise dry region.",
        "Oaas võimaldab taimedel ja asustusel püsida, sest muidu kuivas piirkonnas leidub vett.",
      ],
      [
        "Hot_spring",
        "Geothermal energy below the ground heats which kind of natural pool or spring?",
        "Millist looduslikku veekogu või allikat soojendab maapõuest tulev geotermiline energia?",
        "a hot spring",
        "kuumaveeallikas",
        "Groundwater emerging from geothermally heated rock can form a hot spring.",
        "Geotermiliselt soojenenud kivimite vahelt väljuv põhjavesi võib moodustada kuumaveeallika.",
        ["a thermal spring"],
        ["termaalallikas"],
      ],
      [
        "Volcanic_cone",
        "Which steep-sided mound builds up around an erupting vent from ejected material?",
        "Milline järskude nõlvadega kuhjatis tekib purskava lõõri ümber väljapaisatud materjalist?",
        "a volcanic cone",
        "vulkaanikoonus",
        "Lava and loose fragments can accumulate around a vent to form a volcanic cone.",
        "Laava ja lahtised kivimiosakesed võivad kuhjuda lõõri ümber vulkaanikoonuseks.",
      ],
      [
        "Lava_field",
        "After molten rock spreads and cools, which broad rocky surface can remain?",
        "Milline lai kivine ala jääb järele, kui sulakivim maapinnal laiali voolab ja jahtub?",
        "a lava field",
        "laavaväli",
        "Repeated lava flows can cool into an extensive field of volcanic rock.",
        "Korduvad laavavoolud võivad jahtuda ulatuslikuks vulkaanilise kivimi väljaks.",
      ],
      [
        "Moraine",
        "A moving or melting glacier deposits which ridge or heap of rock debris?",
        "Millise kivimipurdest valli või kuhjatise jätab liikuv või sulav liustik?",
        "a moraine",
        "moreen",
        "Glaciers carry loose material and leave it behind as moraines when the ice retreats.",
        "Liustikud kannavad lahtist kivimimaterjali ja jätavad jää taandudes maha moreeni.",
        ["a glacial moraine"],
        ["liustikumoreen"],
      ],
    ],
  ],
  [
    104,
    "round-one",
    "rivers-lakes",
    "Rivers Around the World",
    "Jõed üle maailma",
    [
      [
        "Yellow_River",
        "Which major river of northern China gets its English colour name from sediment-rich water?",
        "Milline Põhja-Hiina suur jõgi on saanud oma ingliskeelse värvinime seteterikka vee järgi?",
        "the Yellow River",
        "Huang He",
        "Fine loess carried by the river gives its water a yellow-brown colour.",
        "Jõe kantav peen löss annab veele kollakaspruuni värvi.",
        ["the Huang He"],
        ["Kollane jõgi"],
      ],
      [
        "Dnieper",
        "Kyiv stands on which river that continues south to the Black Sea?",
        "Milline läbi Kiievi voolav jõgi suubub Musta merre?",
        "the Dnieper",
        "Dnepr",
        "The Dnieper crosses Ukraine from north to south and reaches the Black Sea.",
        "Dnepr läbib Ukrainat põhjast lõunasse ja suubub Musta merre.",
        ["the Dnipro", "the Dnepr"],
        ["Dnipro", "Dnepri jõgi"],
      ],
      [
        "Euphrates",
        "After flowing through Turkey and Syria, which river joins the Tigris in Iraq?",
        "Milline läbi Türgi ja Süüria voolav jõgi ühineb Iraagis Tigrisega?",
        "the Euphrates",
        "Eufrat",
        "The Euphrates and Tigris drain the historic region of Mesopotamia.",
        "Eufrat ja Tigris läbivad ajaloolist Mesopotaamia piirkonda.",
        ["the Euphrates River"],
        ["Eufrati jõgi"],
      ],
      [
        "Guadalquivir",
        "Seville stands on which Spanish river that reaches the Atlantic near Cádiz?",
        "Milline läbi Sevilla voolav Hispaania jõgi suubub Cádizi lähedal Atlandi ookeani?",
        "the Guadalquivir",
        "Guadalquivir",
        "The Guadalquivir crosses Andalusia and is navigable inland as far as Seville.",
        "Guadalquivir läbib Andaluusiat ja on merelt kuni Sevillani laevatatav.",
      ],
      [
        "Limpopo_River",
        "Which river forms parts of South Africa’s borders with Botswana and Zimbabwe before crossing Mozambique?",
        "Milline jõgi kulgeb osaliselt Lõuna-Aafrika Vabariigi piiril Botswana ja Zimbabwega ning läbib seejärel Mosambiigi?",
        "the Limpopo",
        "Limpopo",
        "The Limpopo crosses southern Africa and reaches the sea on Mozambique’s coast.",
        "Limpopo läbib Aafrika lõunaosa ja suubub merre Mosambiigi rannikul.",
        ["the Limpopo River"],
        ["Limpopo jõgi"],
      ],
    ],
  ],
  [
    105,
    "round-one",
    "mountains",
    "Famous Mountain Peaks",
    "Kuulsad mäetipud",
    [
      [
        "Mount_Ararat",
        "Tradition links Noah’s Ark with which mountain in eastern Turkey?",
        "Millist Ida-Türgi mäge seostatakse pärimuses Noa laevaga?",
        "Mount Ararat",
        "Ararati mägi",
        "Ararat is a snow-capped volcanic massif long associated with the story of Noah’s Ark.",
        "Ararat on lumise tipuga vulkaaniline mäemassiiv, mida on pikka aega seostatud Noa laeva looga.",
        ["Ararat"],
        ["Ararat"],
      ],
      [
        "Teide",
        "Tenerife is dominated by which volcano, Spain’s highest peak?",
        "Milline vulkaan kõrgub Tenerife kohal ja on Hispaania kõrgeim tipp?",
        "Teide",
        "Teide",
        "Teide rises from Tenerife in the Canary Islands and is the highest point in Spain.",
        "Teide kõrgub Kanaari saartel Tenerifel ja on Hispaania kõrgeim punkt.",
        ["Mount Teide"],
        ["Teide mägi"],
      ],
      [
        "Denali",
        "Name the Alaskan peak that is the highest mountain in North America.",
        "Milline Alaska tipp on Põhja-Ameerika kõrgeim mägi?",
        "Denali",
        "Denali",
        "Denali is the highest summit in North America and stands in the Alaska Range.",
        "Denali on Põhja-Ameerika kõrgeim tipp ja asub Alaska mäestikus.",
        ["Mount McKinley", "McKinley"],
        ["McKinley mägi", "McKinley"],
      ],
      [
        "Ben_Nevis",
        "The United Kingdom’s highest point is which Scottish mountain?",
        "Milline Šotimaa mägi on Ühendkuningriigi kõrgeim punkt?",
        "Ben Nevis",
        "Ben Nevis",
        "Ben Nevis rises near Fort William in the western Scottish Highlands.",
        "Ben Nevis kõrgub Fort Williami lähedal Šoti mägismaa lääneosas.",
      ],
      [
        "Mount_Kosciuszko",
        "New South Wales contains which highest point of the Australian mainland?",
        "Milline Uus-Lõuna-Walesi tipp on Austraalia mandriosa kõrgeim punkt?",
        "Mount Kosciuszko",
        "Kosciuszko mägi",
        "Mount Kosciuszko is the highest summit on mainland Australia.",
        "Kosciuszko mägi on Austraalia mandriosa kõrgeim tipp.",
        ["Kosciuszko"],
        ["Kosciuszko"],
      ],
    ],
  ],
  [
    106,
    "round-one",
    "islands",
    "European Islands",
    "Euroopa saared",
    [
      [
        "Corsica",
        "Napoleon Bonaparte was born on which French Mediterranean island?",
        "Millisel Prantsusmaale kuuluval Vahemere saarel sündis Napoleon Bonaparte?",
        "Corsica",
        "Korsika",
        "Corsica lies west of Italy, and Napoleon was born in its city of Ajaccio.",
        "Korsika asub Itaaliast läänes ning Napoleon sündis seal Ajaccio linnas.",
      ],
      [
        "Sardinia",
        "Name the large Italian island west of the mainland and north of Sicily.",
        "Milline suur Itaalia saar asub mandriosast läänes ja Sitsiiliast põhjas?",
        "Sardinia",
        "Sardiinia",
        "Sardinia is a large Mediterranean island west of mainland Italy.",
        "Sardiinia on suur Vahemere saar Itaalia mandriosast läänes.",
      ],
      [
        "Capri",
        "The Blue Grotto belongs to which Italian island in the Bay of Naples?",
        "Milline Napoli lahes asuv Itaalia saar on tuntud Sinise koopa poolest?",
        "Capri",
        "Capri",
        "Capri lies off the Sorrento Peninsula, and boats enter its famous Blue Grotto.",
        "Capri asub Sorrento poolsaare lähedal ning paadid sõidavad selle kuulsasse Sinisesse koopasse.",
      ],
      [
        "Corfu",
        "Off Albania’s coast lies which Greek island in the Ionian Sea?",
        "Milline Joonia meres asuv Kreeka saar paikneb Albaania ranniku lähedal?",
        "Corfu",
        "Korfu",
        "Corfu is the northernmost major Ionian island and faces the Albanian coast.",
        "Korfu on Joonia saarte põhjapoolseim suur saar ja paikneb Albaania ranniku vastas.",
        ["Kerkyra"],
        ["Kérkyra"],
      ],
      [
        "Menorca",
        "Which Spanish Balearic island is named as the “smaller island” compared with nearby Mallorca?",
        "Millise Hispaania Baleaari saare nimi tähendab lähedal asuva Mallorcaga võrreldes „väiksemat saart”?",
        "Menorca",
        "Menorca",
        "Menorca’s name comes from Latin for “smaller island”, contrasting it with nearby Mallorca.",
        "Menorca nimi pärineb ladinakeelsest väljendist „väiksem saar” ja vastandub lähedal asuva Mallorca nimele.",
        ["Minorca"],
        ["Minorca"],
      ],
    ],
  ],
  [
    107,
    "round-one",
    "borders",
    "At the Border",
    "Riigipiiril",
    [
      [
        "Visa_(document)",
        "Which official permission may a traveller need before entering another country?",
        "Millist ametlikku luba võib reisija vajada enne teise riiki sisenemist?",
        "a visa",
        "viisa",
        "A visa is an authorisation connected with entry to or stay in a country.",
        "Viisa on luba, mis on seotud riiki sisenemise või seal viibimisega.",
      ],
      [
        "Border_control",
        "What is the passport-checking stage at a border commonly called?",
        "Kuidas nimetatakse piiriületuse etappi, kus kontrollitakse reisija passi?",
        "passport control",
        "passikontroll",
        "Passport control verifies identity and checks whether a traveller may enter.",
        "Passikontrollis tehakse kindlaks piiriületaja isik ja kontrollitakse tema reisidokumente.",
      ],
      [
        "Border_checkpoint",
        "Which staffed facility at an official crossing checks travellers, vehicles or goods?",
        "Kuidas nimetatakse mehitatud kohta riigipiiril, kus vaadatakse üle reisijate dokumendid, sõidukid või kaubad?",
        "a border checkpoint",
        "piirikontrollipunkt",
        "A border checkpoint is an authorised place for inspecting cross-border traffic.",
        "Piirikontrollipunkt on ametlik koht piiriülese liikluse kontrollimiseks.",
        ["a border post"],
        ["piiripunkt"],
      ],
      [
        "Boundary_marker",
        "Which physical object on the ground shows where one territory ends and another begins?",
        "Milline maastikule paigutatud füüsiline tähis näitab, kus üks territoorium lõpeb ja teine algab?",
        "a boundary marker",
        "piirimärk",
        "Boundary markers make an agreed line visible at specific points on the ground.",
        "Piirimärgid teevad kokkulepitud joone maastikul kindlates punktides nähtavaks.",
        ["a border marker", "a boundary stone"],
        ["piiripost", "piirikivi"],
      ],
      [
        "Maritime_boundary",
        "What agreed line at sea separates areas under neighbouring states’ jurisdiction?",
        "Milline merel kokku lepitud joon eraldab naaberriikide võimupiirkondi?",
        "a maritime boundary",
        "merepiir",
        "Maritime boundaries divide neighbouring states’ zones of authority at sea.",
        "Merepiirid jagavad naaberriikide võimualasid merel.",
        ["a maritime border"],
        ["mereline piir"],
      ],
    ],
  ],
  [
    108,
    "round-one",
    "maps-coordinates",
    "Reading a Map",
    "Kaardi lugemine",
    [
      [
        "Britannia_Depicta",
        "A bound collection of route maps, like the historic Britannia Depicta, is which kind of book?",
        "Mis liiki raamat on ajaloolise Britannia Depicta sarnane köidetud teedekaartide kogu?",
        "a road atlas",
        "maanteeatlas",
        "Britannia Depicta was a road atlas containing hundreds of road maps of England and Wales.",
        "Britannia Depicta oli maanteeatlas, mis sisaldas sadu Inglismaa ja Walesi teedekaarte.",
        ["a road map book"],
        ["autoatlas"],
      ],
      [
        "Map_layout",
        "Which directional arrow on a map helps orient the page by showing which way it faces?",
        "Milline suunda näitav nool kaardil aitab lehte orienteerida, näidates, mispidi kaart on pööratud?",
        "a north arrow",
        "põhjanool",
        "A north arrow lets the reader orient the map to the compass directions.",
        "Põhjanool aitab lugejal kaarti ilmakaarte järgi orienteerida.",
        ["a north indicator"],
        ["põhjasuuna nool"],
      ],
      [
        "Linear_scale",
        "Which marked line shows how a distance on a map corresponds to distance on the ground?",
        "Milline jaotistega joon näitab, kui suurele vahemaale looduses vastab kaugus kaardil?",
        "a scale bar",
        "joonmõõtkava",
        "A scale bar remains a visual reference for converting map length into real distance.",
        "Joonmõõtkava aitab kaardil mõõdetud pikkuse teisendada tegelikuks vahemaaks.",
        ["a graphic scale"],
        ["graafiline mõõtkava"],
      ],
      [
        "Projected_coordinate_system",
        "What do we call a letter-and-number code that identifies a square or location on a map grid?",
        "Kuidas nimetatakse tähtedest ja numbritest koosnevat koodi, mis tähistab kaardiruudustikus ruutu või asukohta?",
        "a grid reference",
        "ruudustikuviide",
        "A grid reference directs the reader to a precise square or point on a gridded map.",
        "Ruudustikuviide juhatab lugeja ruudustikuga kaardil kindla ruudu või punktini.",
        ["a map grid reference"],
        ["kaardiruudu viide"],
      ],
      [
        "Locator_map",
        "Which small secondary map shows where the main mapped area sits within a larger region?",
        "Milline väike lisakaart näitab põhikaardil kujutatud ala paiknemist suuremas piirkonnas?",
        "a locator map",
        "asendikaart",
        "A locator map gives wider geographic context for the area shown in detail.",
        "Asukohakaart annab üksikasjalikult kujutatud alale laiema geograafilise konteksti.",
        ["a location map", "an inset map"],
        ["asukohakaart", "paiknemiskaart"],
      ],
    ],
  ],
  [
    109,
    "round-one",
    "human-geography",
    "Language Basics",
    "Keele põhimõisted",
    [
      [
        "First_language",
        "What do we call the language a person learns first in early childhood?",
        "Kuidas nimetatakse keelt, mille inimene omandab varases lapsepõlves esimesena?",
        "a mother tongue",
        "emakeel",
        "A mother tongue or first language is acquired from a person’s earliest language environment.",
        "Emakeel ehk esimene keel omandatakse inimese kõige varasemas keelekeskkonnas.",
        ["a first language", "a native language", "a native tongue"],
        ["esimene keel", "kodukeel", "L1"],
      ],
      [
        "Language_interpretation",
        "Which professional translates spoken conversation between people who use different languages?",
        "Milline spetsialist vahendab suulist vestlust eri keeli kõnelevate inimeste vahel?",
        "an interpreter",
        "suuline tõlk",
        "An interpreter conveys spoken or signed communication from one language into another.",
        "Suuline tõlk vahendab kõnet ühest keelest teise.",
        ["a language interpreter"],
        ["tõlk"],
      ],
      [
        "Language_barrier",
        "What communication obstacle can arise when two people have no language in common?",
        "Milline suhtlustakistus võib tekkida siis, kui kahel inimesel pole ühist keelt?",
        "a language barrier",
        "keelebarjäär",
        "A language barrier makes communication difficult when people do not share a language.",
        "Keelebarjäär raskendab suhtlemist, kui inimesed ei valda ühist keelt.",
      ],
      [
        "Multilingualism",
        "What term means that a person or community regularly uses two languages?",
        "Kuidas nimetatakse seda, kui inimene või kogukond kasutab korrapäraselt kaht keelt?",
        "bilingualism",
        "kakskeelsus",
        "Bilingualism is the ability or practice of using two languages.",
        "Kakskeelsus on kahe keele oskus või kasutamine.",
      ],
      [
        "Extinct_language",
        "Latin is often described by which term because it no longer has native speakers?",
        "Kuidas nimetatakse keelt, millel pole enam emakeelena kõnelejaid, nagu ladina keelel?",
        "a dead language",
        "surnud keel",
        "A dead language has no living native speakers, although people may still study or use it.",
        "Surnud keelt ei omanda enam keegi emakeelena, kuigi seda võidakse endiselt õppida või kasutada.",
        ["an extinct language"],
        ["väljasurnud keel"],
      ],
    ],
  ],
  [
    110,
    "round-one",
    "landmarks",
    "World-Famous Landmarks",
    "Maailmakuulsad vaatamisväärsused",
    [
      [
        "Leaning_Tower_of_Pisa",
        "Which Italian bell tower is famous for standing at a visible angle?",
        "Milline Itaalia kellatorn on kuulus oma silmatorkava kalde poolest?",
        "the Leaning Tower of Pisa",
        "Pisa viltune torn",
        "The freestanding bell tower began leaning as its foundations settled unevenly.",
        "Eraldiseisev kellatorn hakkas viltu vajuma, sest selle vundament vajus ebaühtlaselt.",
        ["the Leaning Tower", "the Tower of Pisa"],
        ["Pisa torn", "Pisa viltorn"],
      ],
      [
        "London_Eye",
        "Which giant observation wheel stands on the South Bank of the Thames?",
        "Milline hiiglaslik vaateratas seisab Thamesi lõunakaldal?",
        "the London Eye",
        "London Eye",
        "The London Eye carries visitors in enclosed capsules above the Thames riverfront.",
        "London Eye viib külastajad suletud kapslites kõrgele Thamesi kaldapealse kohale.",
        ["the Millennium Wheel"],
        ["Millenniumiratas"],
      ],
      [
        "Arc_de_Triomphe",
        "At the western end of the Champs-Élysées in Paris stands which monumental arch?",
        "Milline monumentaalne kaar seisab Pariisis Champs-Élysées' lääneotsas?",
        "the Arc de Triomphe",
        "Pariisi triumfikaar",
        "The Arc de Triomphe crowns the centre of Place Charles de Gaulle in Paris.",
        "Pariisi triumfikaar seisab Charles de Gaulle'i väljaku keskel.",
        ["the Arc de Triomphe de l’Étoile"],
        ["Triumfikaar"],
      ],
      [
        "Mount_Rushmore",
        "Four presidents’ faces are carved into which South Dakota monument?",
        "Millisesse Lõuna-Dakota monumenti on raiutud nelja presidendi näod?",
        "Mount Rushmore",
        "Rushmore'i mägi",
        "Mount Rushmore depicts George Washington, Thomas Jefferson, Theodore Roosevelt and Abraham Lincoln.",
        "Rushmore'i mäel on kujutatud George Washingtoni, Thomas Jeffersoni, Theodore Roosevelti ja Abraham Lincolni.",
        ["the Mount Rushmore National Memorial", "Rushmore"],
        ["Rushmore'i mäe memoriaal", "Rushmore"],
      ],
      [
        "Space_Needle",
        "Seattle’s skyline is marked by which futuristic observation tower?",
        "Milline futuristlik vaatetorn paistab silma Seattle'i linnasiluetis?",
        "the Space Needle",
        "Space Needle",
        "The Space Needle was built for Seattle’s 1962 World’s Fair and remains a symbol of the city.",
        "Space Needle ehitati Seattle'i 1962. aasta maailmanäituseks ja on endiselt linna sümbol.",
      ],
    ],
  ],
  [
    111,
    "round-two",
    "countries-capitals",
    "Capital Cities Beyond Europe",
    "Pealinnad väljaspool Euroopat",
    [
      [
        "Caracas",
        "Which Venezuelan capital lies in a mountain valley near the Caribbean coast?",
        "Milline Venezuela pealinn asub mägiorus Kariibi mere ranniku lähedal?",
        "Caracas",
        "Caracas",
        "Caracas occupies a valley in Venezuela’s northern coastal mountain range.",
        "Caracas paikneb orus Venezuela põhjaosa rannikumäestikus.",
      ],
      [
        "Kathmandu",
        "Nepal’s capital, known for Durbar Square and its Himalayan setting, is which city?",
        "Milline linn on Nepali pealinn, mis on tuntud Durbari väljaku ja Himaalaja läheduse poolest?",
        "Kathmandu",
        "Katmandu",
        "Kathmandu is Nepal’s capital and the main city of the Kathmandu Valley.",
        "Katmandu on Nepali pealinn ja Katmandu oru peamine linn.",
        ["Katmandu"],
        ["Kathmandu"],
      ],
      [
        "Amman",
        "Which capital of Jordan is home to the Citadel and a large Roman theatre?",
        "Millises Jordaania pealinnas asuvad tsitadell ja suur Rooma teater?",
        "Amman",
        "Amman",
        "Amman is Jordan’s capital, and its historic centre includes a citadel and Roman theatre.",
        "Amman on Jordaania pealinn, mille ajaloolises keskuses asuvad tsitadell ja Rooma teater.",
      ],
      [
        "Phnom_Penh",
        "Which Cambodian capital stands where the Mekong and Tonlé Sap waterways meet?",
        "Milline Kambodža pealinn asub Mekongi ja Tonlé Sapi veeteede ühinemiskohas?",
        "Phnom Penh",
        "Phnom Penh",
        "Phnom Penh grew at the meeting point of the Mekong, Tonlé Sap and Bassac rivers.",
        "Phnom Penh kasvas Mekongi, Tonlé Sapi ja Bassaci jõe ühinemiskohas.",
      ],
      [
        "Kigali",
        "Which hilly city near Rwanda’s geographic centre is the country’s capital?",
        "Milline Rwanda geograafilise keskpunkti lähedal küngastel asuv linn on riigi pealinn?",
        "Kigali",
        "Kigali",
        "Kigali is Rwanda’s capital and lies among hills near the centre of the country.",
        "Kigali on Rwanda pealinn ning asub küngaste vahel riigi keskosa lähedal.",
      ],
    ],
  ],
  [
    112,
    "round-two",
    "cities",
    "Cities and Their Countries",
    "Linnad ja nende riigid",
    [
      [
        "Valletta",
        "Which fortified city on a Mediterranean peninsula is the capital of Malta?",
        "Milline kindlustatud linn Vahemere poolsaarel on Malta pealinn?",
        "Valletta",
        "Valletta",
        "Valletta is Malta’s compact fortified capital beside the Grand Harbour.",
        "Valletta on Malta väike kindlustatud pealinn Grand Harbouri ääres.",
      ],
      [
        "Thessaloniki",
        "The White Tower stands on the waterfront of which major Greek city?",
        "Millise suure Kreeka linna rannapromenaadil seisab Valge torn?",
        "Thessaloniki",
        "Thessaloníki",
        "The White Tower is a familiar landmark on Thessaloniki’s waterfront.",
        "Valge torn on Thessaloníki rannapromenaadi tuntud maamärk.",
        ["Thessaloníki"],
        ["Thessaloniki"],
      ],
      [
        "Gravensteen",
        "Gravensteen is a medieval castle in which Belgian city?",
        "Millises Belgia linnas asub keskaegne Gravensteeni loss?",
        "Ghent",
        "Gent",
        "The Gravensteen is a medieval castle and major landmark in Ghent, East Flanders.",
        "Gravensteen on keskaegne loss ja tuntud vaatamisväärsus Ida-Flandrias Gentis.",
        ["Gent"],
        ["Ghent"],
      ],
      [
        "Coimbra",
        "Portugal’s oldest university gives which former royal capital its student character?",
        "Millisele endisele Portugali kuninglikule pealinnale annab riigi vanim ülikool tudengiliku ilme?",
        "Coimbra",
        "Coimbra",
        "Coimbra was once Portugal’s capital and is home to the country’s oldest university.",
        "Coimbra oli kunagi Portugali pealinn ja seal asub riigi vanim ülikool.",
      ],
      [
        "Cartagena,_Colombia",
        "Which Colombian Caribbean port is known for a colourful old town enclosed by defensive walls?",
        "Milline Colombia Kariibi mere sadamalinn on tuntud kaitsemüüridega ümbritsetud värvika vanalinna poolest?",
        "Cartagena",
        "Cartagena",
        "Cartagena’s historic centre preserves the walls and streets of a major Caribbean port.",
        "Cartagena ajaloolises keskuses on säilinud tähtsa Kariibi mere sadamalinna müürid ja tänavad.",
        ["Cartagena de Indias"],
        ["Cartagena de Indias"],
      ],
    ],
  ],
  [
    113,
    "round-two",
    "physical-geography",
    "Waterways and Coasts",
    "Veeteed ja rannikud",
    [
      [
        "Rapids",
        "On a river, what do we call a fast, turbulent stretch where water tumbles over shallow rocks?",
        "Kuidas nimetatakse jõel kiire voolu ja rahutu veega lõiku, kus vesi liigub üle madalate kivide?",
        "rapids",
        "kärestik",
        "Rapids form where shallow obstacles make river water flow swiftly and turbulently.",
        "Kärestik tekib seal, kus madalad takistused panevad jõevee kiiresti ja rahutult voolama.",
      ],
      [
        "Tributary",
        "Which smaller river or stream flows into a larger river rather than directly into the sea?",
        "Milline väiksem jõgi või oja suubub suuremasse jõkke, mitte otse merre?",
        "a tributary",
        "lisajõgi",
        "A tributary adds its water to a larger river at their meeting point.",
        "Lisajõgi annab oma vee suuremasse jõkke nende ühinemiskohas.",
      ],
      [
        "Seawall",
        "A seaside town builds which solid barrier directly along its shore to protect streets from waves?",
        "Millise tugeva rajatise ehitab mereäärne linn otse rannajoonele, et kaitsta tänavaid lainete eest?",
        "a seawall",
        "meremüür",
        "A seawall protects the land behind it from waves and coastal flooding.",
        "Meremüür kaitseb selle taga olevat maismaad lainete ja üleujutuste eest.",
        ["a sea wall"],
        ["rannakaitsemüür"],
      ],
      [
        "Breakwater_(structure)",
        "At a harbour entrance, boats find calmer water behind which wave-blocking barrier?",
        "Millise laineid tõkestava rajatise taga on sadamasse sisenevate paatide jaoks vesi rahulikum?",
        "a breakwater",
        "lainemurdja",
        "A breakwater shelters a harbour or anchorage from the force of incoming waves.",
        "Lainemurdja kaitseb sadamat või ankrupaika peale tulevate lainete jõu eest.",
      ],
      [
        "Shoal",
        "What long, narrow underwater ridge deposited by currents can obstruct boats near a coast or river mouth?",
        "Kuidas nimetatakse hoovuste kuhjatud pikka kitsast veealust seljandikku, mis võib ranniku või jõesuudme lähedal laevaliiklust takistada?",
        "a sandbar",
        "liivamadal",
        "A sandbar is a ridge of deposited sand that may lie below or rise above the water surface.",
        "Liivamadal on kuhjunud liivast seljandik, mis võib jääda veepinna alla või ulatuda sellest kõrgemale.",
        ["a sandbank", "a shoal"],
        ["liivamadalik", "madalik"],
      ],
    ],
  ],
  [
    114,
    "round-two",
    "rivers-lakes",
    "European Lakes",
    "Euroopa järved",
    [
      [
        "Lake_Balaton",
        "Which Hungarian freshwater lake is the largest lake in Central Europe?",
        "Milline Ungari mageveejärv on Kesk-Euroopa suurim järv?",
        "Lake Balaton",
        "Balatoni järv",
        "Lake Balaton is a freshwater lake in Hungary, the largest lake in Central Europe, and a major tourist destination.",
        "Balatoni järv on Ungaris asuv mageveejärv, Kesk-Euroopa suurim järv ja tähtis turismisihtkoht.",
        ["Balaton"],
        ["Balaton"],
      ],
      [
        "Lake_Como",
        "Villas and Alpine slopes surround which Y-shaped lake in northern Italy?",
        "Millist Y-kujulist Põhja-Itaalia järve ümbritsevad villad ja Alpide nõlvad?",
        "Lake Como",
        "Como järv",
        "Lake Como branches between steep mountains in Italy’s Lombardy region.",
        "Como järv hargneb järskude mägede vahel Itaalia Lombardia maakonnas.",
        ["Como"],
        ["Como"],
      ],
      [
        "Lake_Garda",
        "Which lake between the Alps and the Po Valley is Italy’s largest by area?",
        "Milline Alpide ja Po madaliku vahel asuv järv on pindalalt Itaalia suurim?",
        "Lake Garda",
        "Garda järv",
        "Lake Garda is Italy’s largest lake by surface area and stretches south from the Alps.",
        "Garda järv on pindalalt Itaalia suurim ning ulatub Alpidest lõuna poole.",
        ["Garda"],
        ["Garda"],
      ],
      [
        "Saimaa",
        "A rare freshwater ringed seal lives in which maze-like lake system in southeastern Finland?",
        "Millises Kagu-Soome sopilises järvistus elab haruldane magevee viigerhüljes?",
        "Lake Saimaa",
        "Saimaa järv",
        "Saimaa is a sprawling Finnish lake system and the home of the endangered Saimaa ringed seal.",
        "Saimaa on ulatuslik Soome järvistu ja ohustatud Saimaa viigerhülge kodu.",
        ["Saimaa"],
        ["Saimaa"],
      ],
      [
        "Lake_Ohrid",
        "Which ancient Balkan lake, shared by Albania and its eastern neighbour, has a UNESCO-listed natural and cultural region?",
        "Millise Albaania ja tema idanaabri vahel jagatud iidse Balkani järve loodus- ja kultuuripiirkond kuulub UNESCO nimekirja?",
        "Lake Ohrid",
        "Ohridi järv",
        "Lake Ohrid straddles an international border and is renowned for its long natural and human history.",
        "Ohridi järv ulatub üle riigipiiri ning on tuntud pika loodus- ja inimajaloo poolest.",
        ["Ohrid"],
        ["Ohrid"],
      ],
    ],
  ],
  [
    115,
    "round-two",
    "mountains",
    "Mountain Ranges Across Europe",
    "Euroopa mäestikud",
    [
      [
        "Ural_Mountains",
        "Which long Russian range traditionally marks part of the boundary between Europe and Asia?",
        "Milline pikk Venemaa mäestik tähistab tavapäraselt osa Euroopa ja Aasia piirist?",
        "the Ural Mountains",
        "Uurali mäestik",
        "The Ural Mountains run north to south and are commonly used as part of Europe’s eastern boundary.",
        "Uurali mäestik kulgeb põhjast lõunasse ja seda peetakse tavaliselt Euroopa idapiiri osaks.",
        ["the Urals"],
        ["Uuralid"],
      ],
      [
        "Apennine_Mountains",
        "Which range forms the mountainous spine of the Italian peninsula?",
        "Milline mäestik moodustab Itaalia poolsaare mägise selgroo?",
        "the Apennines",
        "Apenniinid",
        "The Apennines extend along most of mainland Italy from north to south.",
        "Apenniinid ulatuvad põhjast lõunasse läbi suurema osa Mandri-Itaaliast.",
        ["the Apennine Mountains"],
        ["Apenniini mäestik"],
      ],
      [
        "Dolomites",
        "Pale limestone towers make which range in northeastern Italy instantly recognisable?",
        "Millise Kirde-Itaalia mäestiku muudavad kergesti äratuntavaks heledad paekivitornid?",
        "the Dolomites",
        "Dolomiidid",
        "The Dolomites are a limestone mountain group in the eastern Italian Alps.",
        "Dolomiidid on paekivine mäerühm Itaalia Alpide idaosas.",
        ["the Dolomite Mountains"],
        ["Dolomiidi mäed"],
      ],
      [
        "Scandinavian_Mountains",
        "Which range runs through much of Norway and Sweden and forms a watershed between rivers flowing west and east?",
        "Milline mäestik kulgeb läbi suure osa Norrast ja Rootsist ning moodustab veelahkme läände ja itta voolavate jõgede vahel?",
        "the Scandinavian Mountains",
        "Skandinaavia mäestik",
        "The Scandinavian Mountains form a long highland system across Norway and Sweden.",
        "Skandinaavia mäestik moodustab pika kõrgustikuvööndi Norras ja Rootsis.",
        ["the Scandes"],
        ["Skandinaavia mäed"],
      ],
      [
        "Tatra_Mountains",
        "Which range on the Slovakia–Poland border rises above resorts such as Zakopane?",
        "Milline mäestik kõrgub Slovakkia ja Poola piiril selliste kuurortide kohal nagu Zakopane?",
        "the Tatra Mountains",
        "Tatrad",
        "The Tatras form the highest part of the Carpathian chain and straddle Slovakia and Poland.",
        "Tatrad moodustavad Karpaatide kõrgeima osa ning ulatuvad Slovakkiasse ja Poolasse.",
        ["the Tatras"],
        ["Tatra mäestik"],
      ],
    ],
  ],
  [
    116,
    "round-two",
    "islands",
    "Island Countries",
    "Saareriigid",
    [
      [
        "Maldives",
        "Malé is the capital of which low-lying Indian Ocean country made up of coral islands?",
        "Millise madalatest korallsaartest koosneva India ookeani riigi pealinn on Malé?",
        "the Maldives",
        "Maldiivid",
        "The Maldives is an island country of coral atolls southwest of Sri Lanka.",
        "Maldiivid on Sri Lankast edelas asuvatest korallatollidest koosnev saareriik.",
      ],
      [
        "Seychelles",
        "Victoria is the capital of which tropical archipelago northeast of Madagascar?",
        "Millise Madagaskarist kirdes asuva troopilise saarestiku pealinn on Victoria?",
        "the Seychelles",
        "Seišellid",
        "Seychelles is an Indian Ocean island country whose capital is Victoria.",
        "Seišellid on India ookeani saareriik, mille pealinn on Victoria.",
      ],
      [
        "Mauritius",
        "Which island country east of Madagascar has Port Louis as its capital?",
        "Millise Madagaskarist idas asuva saareriigi pealinn on Port Louis?",
        "Mauritius",
        "Mauritius",
        "Mauritius lies in the Indian Ocean east of Madagascar, with Port Louis as its capital.",
        "Mauritius asub India ookeanis Madagaskarist idas ning selle pealinn on Port Louis.",
      ],
      [
        "Solomon_Islands",
        "Guadalcanal belongs to which Pacific island country whose capital is Honiara?",
        "Millisesse Vaikse ookeani saareriiki, mille pealinn on Honiara, kuulub Guadalcanal?",
        "Solomon Islands",
        "Saalomoni Saared",
        "The Solomon Islands form an archipelago in Melanesia that includes Guadalcanal.",
        "Saalomoni Saared moodustavad Melaneesias saarestiku, kuhu kuulub Guadalcanal.",
        ["the Solomons"],
        ["Saalomonid"],
      ],
      [
        "Vanuatu",
        "Port Vila and the active volcano Mount Yasur belong to which Pacific island nation?",
        "Millisele Vaikse ookeani saareriigile kuuluvad Port Vila ja tegevvulkaan Yasur?",
        "Vanuatu",
        "Vanuatu",
        "Vanuatu is a Melanesian archipelago whose capital is Port Vila and whose islands include volcanic Tanna.",
        "Vanuatu on Melaneesia saarestik, mille pealinn on Port Vila ja mille vulkaaniliste saarte hulka kuulub Tanna.",
      ],
    ],
  ],
  [
    117,
    "round-two",
    "borders",
    "Travelling Between Countries",
    "Reisimine riikide vahel",
    [
      [
        "Border_guard",
        "Which uniformed official patrols a national boundary and helps control who enters?",
        "Milline vormikandjast ametnik valvab riigipiiri ja aitab kontrollida, kes riiki siseneb?",
        "a border guard",
        "piirivalvur",
        "Border guards protect national boundaries and enforce rules on entry and exit.",
        "Piirivalvurid kaitsevad riigipiiri ning tagavad riiki sisenemise ja sealt lahkumise reeglite järgimise.",
      ],
      [
        "Duty-free_shop",
        "At an international airport, which kind of shop sells eligible goods without certain local taxes?",
        "Milline rahvusvahelise lennujaama kauplus müüb reisijatele teatavaid kaupu ilma mõne kohaliku maksuta?",
        "a duty-free shop",
        "maksuvaba pood",
        "Duty-free shops sell selected goods to travellers without some taxes or duties normally included in the price.",
        "Maksuvabad poed müüvad reisijatele valitud kaupu ilma mõne hinnas tavaliselt sisalduva maksu või tollimaksuta.",
        ["a duty-free store", "duty-free"],
        ["maksuvaba kauplus", "maksuvaba"],
      ],
      [
        "Customs_declaration",
        "Which form asks an arriving traveller to list goods or cash that must be reported to the authorities?",
        "Millisel vormil peab saabuv reisija kirja panema ametiasutusele teatamist vajavad kaubad või sularaha?",
        "a customs declaration",
        "tollideklaratsioon",
        "A customs declaration tells border authorities what controlled or taxable items a traveller is carrying.",
        "Tollideklaratsioon annab piiriasutusele teada, milliseid piiratud või maksustatavaid esemeid reisija kaasas kannab.",
        ["a customs form"],
        ["tollivorm"],
      ],
      [
        "Open_border",
        "What do we call a boundary that people may cross freely without routine controls?",
        "Kuidas nimetatakse riikidevahelist joont, mida inimesed võivad ületada ilma tavapärase kontrollita?",
        "an open border",
        "avatud piir",
        "An open border allows movement across it with few or no routine restrictions.",
        "Avatud piir võimaldab seda ületada väheste tavapäraste piirangutega või täiesti piiranguteta.",
      ],
      [
        "International_Driving_Permit",
        "Which document used for driving abroad is abbreviated IDP?",
        "Millise välismaal autojuhtimiseks kasutatava dokumendi ingliskeelne lühend on IDP?",
        "an international driving permit",
        "rahvusvaheline juhiluba",
        "An international driving permit accompanies a domestic licence and presents its details in a standard multilingual form.",
        "Rahvusvahelist juhiluba kasutatakse koos kodumaise juhiloaga ning see esitab loa andmed ühtses mitmekeelses vormis.",
      ],
    ],
  ],
  [
    118,
    "round-two",
    "maps-coordinates",
    "Geography on Paper and Screen",
    "Geograafia paberil ja ekraanil",
    [
      [
        "Thomas_Guide",
        "Which kind of detailed local map, found in books such as the Thomas Guide, includes road names and an index for finding addresses?",
        "Milline üksikasjalik kohalik kaart, mida leidub näiteks Thomas Guide’i atlases, sisaldab teede nimesid ja aadresside leidmist hõlbustavat registrit?",
        "a street map",
        "tänavakaart",
        "Thomas Guides are street atlases with detailed metropolitan maps and indexes of streets and points of interest.",
        "Thomas Guide’i väljaanded on üksikasjalike linnakaartide ning tänavate ja huvipunktide registritega tänavaatlased.",
        ["a town map", "a street atlas"],
        ["linnaplaan", "tänavaatlas"],
      ],
      [
        "World_map",
        "Which kind of world map emphasises territorial boundaries and human settlements?",
        "Milline maailmakaart rõhutab territoriaalseid piire ja inimasulaid?",
        "a political map",
        "poliitiline kaart",
        "Political world maps emphasise territorial boundaries and human settlements rather than physical landforms.",
        "Poliitilised maailmakaardid rõhutavad territoriaalseid piire ja inimasulaid, mitte pinnavorme.",
      ],
      [
        "Satellite_imagery",
        "A sensor orbiting Earth produces which overhead view of clouds, land and sea?",
        "Millise ülaltvaate pilvedest, maismaast ja merest loob ümber Maa tiirlev andur?",
        "a satellite image",
        "satelliidipilt",
        "Satellite images record reflected or emitted energy from Earth’s surface and atmosphere.",
        "Satelliidipildid jäädvustavad Maa pinnalt ja atmosfäärist peegeldunud või kiirgunud energiat.",
        ["a satellite photograph"],
        ["satelliidifoto"],
      ],
      [
        "Raised-relief_map",
        "Which three-dimensional map uses a raised surface to represent mountains and valleys?",
        "Milline ruumiline kaart kujutab mägesid ja orge kõrgendatud pinnana?",
        "a raised-relief map",
        "reljeefkaart",
        "A raised-relief map is a physical three-dimensional representation of terrain.",
        "Reljeefkaart on maastiku füüsiline kolmemõõtmeline kujutis.",
        ["a relief map", "a terrain model"],
        ["reljeefne kaart", "maastikumudel"],
      ],
      [
        "Topographic_profile",
        "Hikers use which side-view graph to see the climbs and descents along a route?",
        "Millise külgvaates graafiku abil näevad matkajad teekonna tõuse ja laskumisi?",
        "an elevation profile",
        "kõrgusprofiil",
        "An elevation profile plots how ground height changes along a chosen line or route.",
        "Kõrgusprofiil näitab, kuidas maapinna kõrgus valitud joone või teekonna vältel muutub.",
        ["a topographic profile"],
        ["maastikuprofiil"],
      ],
    ],
  ],
  [
    119,
    "round-two",
    "human-geography",
    "Settlement Types",
    "Asulatüübid",
    [
      [
        "Suburb",
        "What do we call a mainly residential community on the outer part of a city?",
        "Kuidas nimetatakse peamiselt elamupiirkonnana toimivat asulat linna servas?",
        "a suburb",
        "eeslinn",
        "A suburb is a residential area or community at the edge of or just outside a larger city.",
        "Eeslinn on elamupiirkond või asula suurema linna servas või vahetus läheduses.",
        ["a suburban area"],
        ["äärelinn"],
      ],
      [
        "Ghost_town",
        "An old settlement has lost nearly all its residents but its empty buildings remain. What is it called?",
        "Vana asula on kaotanud peaaegu kõik elanikud, kuid tühjad hooned on alles. Kuidas seda nimetatakse?",
        "a ghost town",
        "kummituslinn",
        "A ghost town is an abandoned or nearly abandoned settlement with visible remains.",
        "Kummituslinn on hüljatud või peaaegu hüljatud asula, mille ehitised on veel nähtavad.",
        ["an abandoned town"],
        ["mahajäetud linn"],
      ],
      [
        "Resort_town",
        "Which type of town attracts visitors mainly for holidays, beaches, skiing or spa treatments?",
        "Kuidas nimetatakse linna, mis meelitab külastajaid eelkõige puhkuse, randade, suusatamise või spaadega?",
        "a resort town",
        "kuurortlinn",
        "A resort town is organised around tourism and recreation for visiting holidaymakers.",
        "Kuurortlinna elu ja teenused on suunatud peamiselt turistidele ning puhkajatele.",
      ],
      [
        "Megacity",
        "What term is commonly used for an urban area with at least ten million inhabitants?",
        "Kuidas nimetatakse tavaliselt linnapiirkonda, kus elab vähemalt kümme miljonit inimest?",
        "a megacity",
        "megalinn",
        "A megacity is commonly defined as an urban area with at least ten million residents.",
        "Megalinnaks nimetatakse tavaliselt linnapiirkonda, kus elab vähemalt kümme miljonit inimest.",
      ],
      [
        "Satellite_city",
        "Which term describes a smaller urban centre near a much larger city that remains a separate community but is closely linked to it?",
        "Kuidas nimetatakse suure linna lähedal asuvat väiksemat omaette linnalist keskust, mis on suurema linnaga tihedalt seotud?",
        "a satellite town",
        "satelliitlinn",
        "A satellite town is a smaller, separate settlement connected economically and socially to a nearby larger city.",
        "Satelliitlinn on suurema linna lähedal asuv väiksem omaette asula, mis on sellega majanduslikult ja ühiskondlikult tihedalt seotud.",
        ["a satellite city"],
        ["satelliitasula"],
      ],
    ],
  ],
  [
    120,
    "round-two",
    "landmarks",
    "Famous City Squares",
    "Kuulsad linnaväljakud",
    [
      [
        "St._Peter%27s_Square",
        "Which vast oval square in Vatican City is embraced by Bernini’s colonnades?",
        "Millist suurt ovaalset väljakut Vatikani linnas ümbritsevad Bernini sammaskäigud?",
        "Saint Peter’s Square",
        "Püha Peetruse väljak",
        "Bernini designed the sweeping colonnades that frame Saint Peter’s Square in Vatican City.",
        "Bernini kavandas Vatikani linnas Püha Peetruse väljakut raamivad kaarjad sammaskäigud.",
        ["St Peter's Square"],
        ["Peetruse väljak"],
      ],
      [
        "Dam_Square",
        "Amsterdam’s Royal Palace and National Monument face which central square?",
        "Millise Amsterdami keskväljaku ääres asuvad kuninglik palee ja rahvusmonument?",
        "Dam Square",
        "Dami väljak",
        "Dam Square is a central public space in Amsterdam beside the Royal Palace and National Monument.",
        "Dami väljak on Amsterdami keskne avalik ruum kuningliku palee ja rahvusmonumendi kõrval.",
      ],
      [
        "Grand-Place",
        "Ornate guildhalls and Brussels Town Hall enclose which famous Belgian square?",
        "Millist kuulsat Belgia väljakut ümbritsevad uhked gildihooned ja Brüsseli raekoda?",
        "Grand Place",
        "Grand-Place",
        "The Grand Place is Brussels’ central square, surrounded by guildhalls and its Gothic town hall.",
        "Grand-Place on Brüsseli keskväljak, mida ümbritsevad gildihooned ja gooti stiilis raekoda.",
        ["Grote Markt"],
        ["Grote Markt"],
      ],
      [
        "Plaza_Mayor,_Madrid",
        "Which arcaded square in central Madrid contains an equestrian statue of King Philip III?",
        "Millisel arkaadidega ümbritsetud Madridi keskväljakul seisab kuningas Felipe III ratsamonument?",
        "Plaza Mayor",
        "Plaza Mayor",
        "Madrid’s Plaza Mayor is a rectangular arcaded square with a statue of Philip III at its centre.",
        "Madridi Plaza Mayor on ristkülikukujuline arkaadidega väljak, mille keskel seisab Felipe III kuju.",
      ],
      [
        "Marienplatz",
        "Munich’s New Town Hall and its famous Glockenspiel overlook which central square?",
        "Millise Müncheni keskväljaku ääres asub uus raekoda koos oma kuulsa kellamänguga?",
        "Marienplatz",
        "Marienplatz",
        "Marienplatz has been Munich’s central square for centuries and is dominated by the New Town Hall.",
        "Marienplatz on olnud sajandeid Müncheni keskväljak ning selle ääres kõrgub uus raekoda.",
      ],
    ],
  ],
];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLocaleLowerCase("en")
    .replace(/%[0-9a-f]{2}/giu, "-")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    page,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const subjectKey = `geography:${slug(page)}`;
  return {
    clueId: `built-in-geography-easy-expansion-${clueNumber}`,
    key: `geography-easy-expansion:${categorySetId}:${tier}`,
    factKey: `geography-easy-expansion:${slug(page)}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(page).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${page}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    },
  };
}

export const GEOGRAPHY_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  GEOGRAPHY_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
