import type { EasyExpansionCategory, EasyExpansionQuestion } from "../types";

const BATCH_ID = "03-science-nature";
const PACK_ID = "built-in-science-nature";
const RETRIEVED_AT = "2026-09-06";

type QuestionSeed = readonly [
  page: string,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const SCIENCE_NATURE_EASY_EXPANSION_SEEDS: readonly CategorySeed[] = [
  [
    101,
    "round-one",
    "physics",
    "Electricity Around the House",
    "Elekter kodus",
    [
      [
        "Static_electricity",
        "A rubbed balloon can cling to a wall and make hair stand on end because of which electrical effect?",
        "Milline elektrinähtus võib panna hõõrutud õhupalli seina külge kleepuma ja juukseid püsti tõstma?",
        "static electricity",
        "staatiline elekter",
        "Static electricity is an imbalance of electric charge that can build up on an object's surface.",
        "Staatiline elekter tekib elektrilaengu tasakaalutusest, mis võib koguneda eseme pinnale.",
      ],
      [
        "Circuit_breaker",
        "What resettable switch in a home's electrical panel trips off during an overload?",
        "Milline kodu elektrikilbi lüliti rakendub ülekoormuse korral ja mille saab pärast uuesti sisse lülitada?",
        "a circuit breaker",
        "kaitselüliti",
        "It can be switched back on after the fault is removed.",
        "Pärast rikke kõrvaldamist saab selle uuesti sisse lülitada.",
      ],
      [
        "Short_circuit",
        "What electrical fault occurs when current finds an unintended path with very little resistance?",
        "Milline elektririke tekib siis, kui vool leiab soovimatu väga väikese takistusega tee?",
        "a short circuit",
        "lühis",
        "A short circuit creates a low-resistance path that can produce a dangerously large current.",
        "Lühis tekitab väikese takistusega tee, milles võib tekkida ohtlikult tugev vool.",
      ],
      [
        "Resistor",
        "Which small electronic component, often marked with coloured bands, limits current in a circuit?",
        "Milline sageli värviliste rõngastega märgitud väike elektroonikakomponent piirab vooluringis voolutugevust?",
        "a resistor",
        "takisti",
        "A resistor opposes electric current, and coloured bands can show its resistance value.",
        "Takisti piirab elektrivoolu ning värvilised rõngad võivad näidata selle takistuse väärtust.",
      ],
      [
        "Electromagnet",
        "A doorbell can use which switchable magnet made by sending current through a coil?",
        "Millist lülitatavat magnetit võib kasutada uksekell, kui vool juhitakse läbi mähise?",
        "an electromagnet",
        "elektromagnet",
        "Current through a coil creates a magnetic field, so an electromagnet can be switched on and off.",
        "Mähist läbiv vool tekitab magnetvälja, mistõttu elektromagnetit saab sisse ja välja lülitada.",
      ],
    ],
  ],
  [
    102,
    "round-one",
    "physics",
    "Everyday Sound",
    "Helid meie ümber",
    [
      [
        "Vocal_fold",
        "Which pair of tissue folds in the voice box vibrates when a person speaks or sings?",
        "Milline paar kõris asuvaid koevoldikesi vibreerib, kui inimene räägib või laulab?",
        "the vocal cords",
        "häälepaelad",
        "Air from the lungs makes the vocal cords vibrate and produce sound.",
        "Kopsudest tulev õhk paneb häälepaelad võnkuma ja tekitab heli.",
        ["the vocal folds"],
        ["häälekurrud"],
      ],
      [
        "Earplug",
        "Which small items placed in the ears can protect hearing from loud noise or block distracting sounds during sleep?",
        "Millised väikesed kõrva pandavad esemed võivad kaitsta kuulmist tugeva müra eest või summutada magamise ajal segavaid helisid?",
        "earplugs",
        "kõrvatropid",
        "Earplugs reduce the amount of sound reaching the ear canal.",
        "Kõrvatropid vähendavad kuulmekäiku jõudva heli hulka.",
        ["ear plugs"],
        ["kõrvakorgid"],
      ],
      [
        "Decibel",
        "Which unit, abbreviated dB, is commonly used to express sound level?",
        "Millist ühikut, mille tähis on dB, kasutatakse tavaliselt helitaseme väljendamiseks?",
        "a decibel",
        "detsibell",
        "The decibel is a logarithmic unit used for quantities including sound level.",
        "Detsibell on logaritmiline ühik, mida kasutatakse muu hulgas helitaseme väljendamiseks.",
      ],
      [
        "Tuning_fork",
        "Which two-pronged metal tool produces a steady tone when struck and helps tune musical instruments?",
        "Milline kaheharuline metallist tööriist annab löömisel kindla helikõrguse ja aitab pille häälestada?",
        "a tuning fork",
        "helihark",
        "A tuning fork vibrates at a particular pitch after it is struck.",
        "Helihark võngub pärast löömist kindlal helikõrgusel.",
      ],
      [
        "Sonar",
        "Which system sends out sound pulses and listens for returning echoes to find objects underwater?",
        "Milline süsteem saadab välja heliimpulsse ja kuulab tagasipeegelduvaid kajasid, et leida veealuseid objekte?",
        "sonar",
        "sonar",
        "Sonar measures returning sound to detect and locate objects in water.",
        "Sonar kasutab tagasipeegelduvat heli vees olevate objektide avastamiseks ja asukoha määramiseks.",
      ],
    ],
  ],
  [
    103,
    "round-one",
    "chemistry",
    "In the Science Lab",
    "Teaduslaboris",
    [
      [
        "Safety_goggles",
        "Which transparent protective eyewear should be worn when a laboratory experiment might splash chemicals?",
        "Millised läbipaistvad silmakaitsmed tuleb ette panna, kui laborikatse ajal võivad kemikaalid pritsida?",
        "safety goggles",
        "kaitseprillid",
        "Safety goggles cover the eye area and help protect it from chemical splashes.",
        "Kaitseprillid katavad silmade ümbruse ja aitavad neid kemikaalipritsmete eest kaitsta.",
      ],
      [
        "Test_tube",
        "Which narrow laboratory tube, closed at one end, holds a small sample during an experiment?",
        "Milline ühest otsast suletud kitsas laboritoru hoiab katse ajal väikest proovi?",
        "a test tube",
        "katseklaas",
        "A test tube is a small cylindrical vessel used to hold, mix or heat samples.",
        "Katseklaas on väike silindriline anum proovide hoidmiseks, segamiseks või kuumutamiseks.",
      ],
      [
        "Beaker_(laboratory_equipment)",
        "Which flat-bottomed laboratory container has straight sides and usually a small pouring lip?",
        "Millisel lameda põhja ja sirgete külgedega laborinõul on tavaliselt väike valamistila?",
        "a beaker",
        "keeduklaas",
        "A beaker is a simple laboratory vessel used for holding, mixing and heating liquids.",
        "Keeduklaas on lihtne laborinõu vedelike hoidmiseks, segamiseks ja kuumutamiseks.",
      ],
      [
        "Pipette",
        "Which slender laboratory tool transfers a small amount of liquid, often one drop at a time?",
        "Millise peenikese laborivahendiga viiakse üle väike kogus vedelikku, sageli tilkhaaval?",
        "a pipette",
        "pipett",
        "A pipette draws up and dispenses small volumes of liquid.",
        "Pipett tõmbab sisse ja väljastab väikeseid vedelikukoguseid.",
        ["a dropper", "a pipet"],
        ["tilguti", "laboripipett"],
      ],
      [
        "Bunsen_burner",
        "Which adjustable gas burner, named after a German chemist, provides a flame on a laboratory bench?",
        "Milline Saksa keemiku järgi nimetatud reguleeritav gaasipõleti annab laborilaual leegi?",
        "a Bunsen burner",
        "Bunseni põleti",
        "A Bunsen burner mixes gas with air to produce a controllable laboratory flame.",
        "Bunseni põleti segab gaasi õhuga ja tekitab reguleeritava laborileegi.",
      ],
    ],
  ],
  [
    104,
    "round-one",
    "chemistry",
    "Acids, Bases and Indicators",
    "Happed, alused ja indikaatorid",
    [
      [
        "Antacid",
        "Which type of medicine counteracts excess stomach acid to relieve heartburn?",
        "Milline ravimiliik vähendab liigse maohappe toimet ja leevendab kõrvetisi?",
        "an antacid",
        "antatsiid",
        "Antacids contain basic compounds that react with acid in the stomach.",
        "Antatsiidid sisaldavad aluselisi ühendeid, mis reageerivad maos oleva happega.",
      ],
      [
        "Litmus",
        "Which treated paper turns red in an acidic solution and blue in an alkaline one?",
        "Milline töödeldud paber muutub happelises lahuses punaseks ja aluselises lahuses siniseks?",
        "litmus paper",
        "lakmuspaber",
        "Litmus is a dye used as an indicator of whether a solution is acidic or alkaline.",
        "Lakmus on värvaine, mida kasutatakse lahuse happelisuse või aluselisuse näitamiseks.",
      ],
      [
        "Sodium_hypochlorite",
        "Which household chemical can whiten fabrics and is usually alkaline rather than acidic?",
        "Milline kodukeemia võib kangaid valgendada ja on tavaliselt pigem aluseline kui happeline?",
        "bleach",
        "valgendi",
        "Many household bleaches are alkaline solutions that remove colour through chemical reactions.",
        "Paljud majapidamises kasutatavad valgendid on aluselised lahused, mis eemaldavad värvi keemiliste reaktsioonide abil.",
        ["sodium hypochlorite", "chlorine bleach"],
        ["naatriumhüpoklorit", "kloorvalgendi"],
      ],
      [
        "Universal_indicator",
        "Which laboratory mixture uses a range of colours to show approximate pH, rather than only red or blue?",
        "Milline laborisegu näitab ligikaudset pH-d terve värviskaalaga, mitte üksnes punase või sinisega?",
        "universal indicator",
        "universaalindikaator",
        "Universal indicator changes through several colours across the pH scale.",
        "Universaalindikaator muudab pH-skaala eri osades värvi.",
      ],
      [
        "Neutralization_(chemistry)",
        "What reaction occurs when an acid and a base counteract each other, commonly producing salt and water?",
        "Milline reaktsioon toimub siis, kui hape ja alus teineteise toime kõrvaldavad ning tavaliselt tekivad sool ja vesi?",
        "neutralisation",
        "neutraliseerimine",
        "In a neutralisation reaction, an acid and a base commonly react to form a salt and water.",
        "Neutraliseerimisel reageerivad hape ja alus ning tavaliselt tekivad sool ja vesi.",
        ["neutralization"],
        ["neutralisatsioon"],
      ],
    ],
  ],
  [
    105,
    "round-one",
    "earth-science",
    "Inside Caves",
    "Koobaste sisemus",
    [
      [
        "Stalactite",
        "Which pointed mineral formation hangs down from a cave ceiling?",
        "Milline terav mineraalne moodustis ripub koopalaest alla?",
        "a stalactite",
        "stalaktiit",
        "A stalactite grows downward as mineral-rich water drips from a cave ceiling.",
        "Stalaktiit kasvab allapoole, kui mineraalirikas vesi koopalaest tilgub.",
      ],
      [
        "Stalagmite",
        "Dripping mineral-rich water can build which formation upward from a cave floor?",
        "Milline moodustis võib mineraalirikka vee tilkumisel koopapõrandalt ülespoole kasvada?",
        "a stalagmite",
        "stalagmiit",
        "A stalagmite forms on a cave floor beneath falling mineral-rich drops.",
        "Stalagmiit tekib koopapõrandale mineraalirikaste veetilkade langemiskohas.",
      ],
      [
        "Subterranean_river",
        "Water flowing through a natural channel below the ground forms what hidden kind of waterway?",
        "Milline varjatud veetee tekib siis, kui vesi voolab looduslikus sängis maapinna all?",
        "an underground river",
        "maa-alune jõgi",
        "An underground river flows beneath the surface through caves or other natural passages.",
        "Maa-alune jõgi voolab pinna all läbi koobaste või muude looduslike käikude.",
        ["a subterranean river"],
        ["maa-alune veevool"],
      ],
      [
        "Caving",
        "What do we call a person who explores caves as a sport or hobby?",
        "Kuidas nimetatakse inimest, kes uurib koopaid spordi või hobina?",
        "a caver",
        "koopauurija",
        "A caver explores cave systems recreationally, an activity also called caving or spelunking.",
        "Koopauurija avastab koopaid harrastusena, sageli koos teiste huvilistega.",
        ["a spelunker", "a cave explorer"],
        ["koopa uurija", "speleomatkaja"],
      ],
      [
        "Cave_pearl",
        "What name is given to a small rounded ball of calcite that forms around a grain in a cave pool?",
        "Kuidas nimetatakse väikest ümarat kaltsiidikuulikest, mis tekib koopalombis terakese ümber?",
        "a cave pearl",
        "koopapärl",
        "A cave pearl grows as calcite coats a loose nucleus in moving water.",
        "Koopapärl kasvab, kui liikuvast veest ladestub kaltsiit lahtise tuuma ümber.",
      ],
    ],
  ],
  [
    106,
    "round-one",
    "earth-science",
    "Prehistoric Finds",
    "Eelajaloolised leiud",
    [
      [
        "Trace_fossil",
        "Which mark in ancient sediment shows where a dinosaur once stepped?",
        "Milline jälg muistses settekihis näitab kohta, kuhu dinosaurus kunagi astus?",
        "a dinosaur footprint",
        "dinosauruse jalajälg",
        "A preserved footprint is a trace fossil recording an animal's activity rather than its body.",
        "Säilinud jalajälg on jälgfossiil, mis jäädvustab looma tegevust, mitte tema keha.",
      ],
      [
        "Dinosaur_egg",
        "Which fossilised object found in some nests once protected a developing dinosaur embryo?",
        "Milline mõnest pesast leitud kivistunud ese kaitses kunagi arenevat dinosauruse embrüot?",
        "a dinosaur egg",
        "dinosauruse muna",
        "Fossilised dinosaur eggs and nests provide evidence about dinosaur reproduction.",
        "Kivistunud dinosaurusemunad ja pesad annavad teavet dinosauruste paljunemise kohta.",
      ],
      [
        "Mammoth",
        "Which huge curved tooth from an Ice Age relative of the elephant is sometimes found in frozen ground?",
        "Milline jääajast pärit elevandi sugulase hiiglaslik kaardus hammas leitakse vahel külmunud pinnasest?",
        "a mammoth tusk",
        "mammutikihv",
        "Mammoth tusks were enlarged front teeth that could survive long after the animal died.",
        "Mammutikihvad olid suurenenud esihambad, mis võisid säilida kaua pärast looma surma.",
      ],
      [
        "Petrified_wood",
        "What do we call ancient tree material whose structure remains visible after minerals replaced its original tissue?",
        "Kuidas nimetatakse muistset puumaterjali, mille struktuur jäi nähtavaks pärast algse koe asendumist mineraalidega?",
        "petrified wood",
        "kivistunud puit",
        "Petrified wood forms when minerals replace buried plant tissue while preserving its structure.",
        "Kivistunud puit tekib siis, kui mineraalid asendavad mattunud taimekoe, säilitades selle struktuuri.",
      ],
      [
        "Trilobite",
        "Which extinct marine arthropod, whose body is divided lengthwise into three lobes, is a familiar fossil?",
        "Milline väljasurnud merelülijalgne, kelle keha jaguneb pikuti kolmeks sagaraks, on tuntud fossiil?",
        "a trilobite",
        "trilobiit",
        "Trilobites were marine arthropods with bodies divided lengthwise into three lobes, and their hard exoskeletons fossilised readily.",
        "Trilobiidid olid pikuti kolmeks sagaraks jagunenud kehaga merelülijalgsed, kelle kõva välisskelett kergesti kivistus.",
      ],
    ],
  ],
  [
    107,
    "round-one",
    "earth-science",
    "Soils Underfoot",
    "Muld meie jalge all",
    [
      [
        "Topsoil",
        "What is the upper layer of ground where most plant roots and much organic matter are found?",
        "Kuidas nimetatakse mulla pealmist osa, kus leidub enamik taimejuuri ja palju orgaanilist ainet?",
        "topsoil",
        "pealmuld",
        "Topsoil is the surface layer of soil and usually contains roots and organic matter.",
        "Pealmuld on mulla pindmine kiht, mis sisaldab tavaliselt juuri ja orgaanilist ainet.",
        ["the top layer of soil"],
        ["mulla pealmine kiht"],
      ],
      [
        "Soil_texture",
        "Which soil type feels gritty, drains quickly and contains a large share of coarse mineral particles?",
        "Milline mullatüüp tundub teraline, laseb vee kiiresti läbi ja sisaldab palju jämedaid mineraalosakesi?",
        "sandy soil",
        "liivmuld",
        "Sandy soil contains many relatively large particles, leaving spaces through which water drains readily.",
        "Liivmuld sisaldab palju suhteliselt suuri osakesi, mille vahelt vesi kergesti läbi liigub.",
      ],
      [
        "Physical_properties_of_soil",
        "Which fine-particle soil type can feel sticky when wet and hold water for a long time?",
        "Milline peente osakestega mullatüüp võib märjana tunduda kleepuv ja hoida vett kaua kinni?",
        "clay soil",
        "savimuld",
        "Clay soil has very fine particles and small pore spaces, so it retains water well.",
        "Savimullas on väga peened osakesed ja väikesed poorid, mistõttu hoiab see hästi vett.",
      ],
      [
        "Potting_soil",
        "Which ready-made growing medium sold in bags is used to fill containers for houseplants and seedlings?",
        "Millist kottides müüdavat valmis kasvusubstraati kasutatakse toalillede ja istikute pottide täitmiseks?",
        "potting soil",
        "potimuld",
        "Potting soil is a prepared growing medium used for plants raised in containers.",
        "Potimuld on anumates kasvatatavate taimede jaoks valmistatud kasvusubstraat.",
        ["potting mix"],
        ["potisegu"],
      ],
      [
        "Loam",
        "Gardeners value which crumbly soil containing a balanced mixture of sand, silt and clay?",
        "Millist sõmerat, tasakaalustatud liiva-, tolmu- ja saviosakeste seguga mulda aednikud hindavad?",
        "loam",
        "liivsavimuld",
        "Loam combines sand, silt and clay in proportions that support both drainage and water retention.",
        "Liivsavimuld ühendab liiva-, tolmu- ja saviosakesi vahekorras, mis võimaldab nii vee äravoolu kui ka niiskuse hoidmist.",
        ["loamy soil"],
        ["liivsavi"],
      ],
    ],
  ],
  [
    108,
    "round-one",
    "weather-climate",
    "Reading a Weather App",
    "Ilmaäpi lugemine",
    [
      [
        "Apparent_temperature",
        "An app combines measured air temperature with effects such as wind or humidity into which human-comfort reading?",
        "Ilmaäpp ühendab mõõdetud õhutemperatuuri tuule või õhuniiskuse mõjuga üheks inimese enesetunnet kirjeldavaks näiduks. Mis näit see on?",
        "the feels-like temperature",
        "tajutav temperatuur",
        "Apparent temperature describes how conditions feel to a person after factors such as wind or humidity are considered.",
        "Tajutav temperatuur kirjeldab ilma mõju inimesele, võttes arvesse näiteks tuult või õhuniiskust.",
        ["the apparent temperature"],
        ["näiv temperatuur"],
      ],
      [
        "Probability_of_precipitation",
        "A forecast shows a percentage for whether measurable rain, snow or sleet will occur at your location. What does it represent?",
        "Ilmaprognoos näitab protsenti selle kohta, kas sinu asukohas sajab mõõdetavalt vihma, lund või lörtsi. Mida see protsent väljendab?",
        "the probability of precipitation",
        "sademete tõenäosus",
        "A precipitation probability expresses the likelihood that measurable precipitation will occur in the forecast area.",
        "Sademete tõenäosus väljendab võimalust, et prognoosialal esineb mõõdetavaid sademeid.",
        ["precipitation probability"],
        ["saju tõenäosus"],
      ],
      [
        "Sunrise",
        "Which daily clock entry tells you when the Sun's upper edge first appears above the horizon?",
        "Milline igapäevane kellaaeg näitab, millal Päikese ülaserv esimest korda horisondi kohale ilmub?",
        "sunrise time",
        "päikesetõusu aeg",
        "Sunrise is the moment when the Sun's upper edge appears above the horizon.",
        "Päikesetõus on hetk, mil Päikese ülaserv ilmub horisondi kohale.",
        ["the time of sunrise"],
        ["päikesetõusuaeg"],
      ],
      [
        "Ultraviolet_index",
        "Which numbered scale in a forecast warns how strongly sunlight can damage unprotected skin?",
        "Milline ilmaprognoosi arvuline skaala hoiatab, kui tugevalt võib päikesekiirgus kaitsmata nahka kahjustada?",
        "the UV index",
        "UV-indeks",
        "The UV index reports the expected strength of sunburn-producing ultraviolet radiation.",
        "UV-indeks näitab päikesepõletust põhjustava ultraviolettkiirguse eeldatavat tugevust.",
        ["the ultraviolet index"],
        ["ultraviolettkiirguse indeks"],
      ],
      [
        "Weather_radar",
        "Which coloured moving map uses reflected radio waves to show nearby rain and snow?",
        "Milline liikuv värviline kaart kasutab peegelduvaid raadiolaineid, et näidata lähipiirkonna sademeid?",
        "weather radar",
        "ilmaradar",
        "Weather radar sends out radio waves and maps the signals reflected by precipitation.",
        "Ilmaradar saadab välja raadiolaineid ja kaardistab sademetelt tagasipeegelduvaid signaale.",
        ["meteorological radar"],
        ["meteoroloogiline radar"],
      ],
    ],
  ],
  [
    109,
    "round-one",
    "weather-climate",
    "Winter Weather",
    "Talveilm",
    [
      [
        "Icicle",
        "What pointed hanging shape forms when dripping water freezes along a roof edge?",
        "Milline terav rippuv moodustis tekib siis, kui tilkuv vesi räästas külmub?",
        "an icicle",
        "jääpurikas",
        "An icicle grows as water drips and freezes in successive layers.",
        "Jääpurikas kasvab, kui tilkuv vesi kiht kihi järel külmub.",
      ],
      [
        "Snowdrift",
        "Wind can pile loose white flakes into which deep bank or ridge?",
        "Millise sügava kuhja või valli võib tuul lahtistest valgetest helvestest kokku kanda?",
        "a snowdrift",
        "lumehang",
        "A snowdrift is a mound formed when wind carries and deposits snow.",
        "Lumehang tekib siis, kui tuul lund kannab ja ühte kohta kuhjab.",
      ],
      [
        "Snow_cover",
        "Which continuous white layer lying on the ground can insulate plants and soil during winter?",
        "Milline maapinnal lasuv ühtlane valge kiht võib talvel taimi ja mulda külma eest isoleerida?",
        "snow cover",
        "lumikate",
        "Snow cover is the layer of snow present on the ground and can slow heat loss from the soil.",
        "Lumikate on maapinnal püsiv lumekiht, mis võib aeglustada soojuse kadu mullast.",
      ],
      [
        "Ground_frost",
        "Which shallow overnight freeze can damage plants even when the official air temperature stays above zero?",
        "Milline maapinna lähedal tekkiv öine külm võib taimi kahjustada isegi siis, kui ametlik õhutemperatuur jääb üle nulli?",
        "ground frost",
        "öökülm",
        "Ground frost can occur near the surface when the standard air temperature remains above freezing.",
        "Öökülm võib tekkida maapinna lähedal ka siis, kui tavapäraselt mõõdetud õhutemperatuur püsib üle nulli.",
      ],
      [
        "Black_ice",
        "Which thin, nearly transparent road coating is hard to see because the dark pavement remains visible beneath it?",
        "Milline õhuke ja peaaegu läbipaistev teekate on raskesti märgatav, sest tume asfalt paistab selle alt läbi?",
        "black ice",
        "must jää",
        "Black ice is a transparent glaze on a road whose dark surface remains visible through it.",
        "Must jää on läbipaistev kiht teel, mille alt tume teepind läbi paistab.",
      ],
    ],
  ],
  [
    110,
    "round-one",
    "weather-climate",
    "Cloud Shapes",
    "Pilvekujud",
    [
      [
        "Cumulus_cloud",
        "Which familiar fair-weather cloud looks like a bright heap of cotton with a fairly flat base?",
        "Milline tuttav ilusa ilma pilv meenutab heledat puuvillakuhja ja on üsna lameda alusega?",
        "cumulus",
        "rünkpilv",
        "Cumulus clouds are separate, puffy heaps that often have flat bases.",
        "Rünkpilved on eraldiseisvad kohevad pilvekuhjad, mille alus on sageli lame.",
      ],
      [
        "Stratus_cloud",
        "A low, even grey sheet that covers much of the sky belongs to which cloud type?",
        "Millise pilveliigiga on tegu, kui madal ühtlane hall kiht katab suure osa taevast?",
        "stratus",
        "kihtpilv",
        "Stratus forms a low, featureless layer and may bring mist or light drizzle.",
        "Kihtpilv moodustab madala ühtlase kihi ning võib tuua udu või kerget uduvihma.",
      ],
      [
        "Cirrus_cloud",
        "Which high, thin cloud appears as white wisps and is made mainly of ice crystals?",
        "Milline kõrge õhuke pilv paistab valgete kiududena ja koosneb peamiselt jääkristallidest?",
        "cirrus",
        "kiudpilv",
        "Cirrus clouds form high in the atmosphere as delicate streaks of ice crystals.",
        "Kiudpilved tekivad kõrgel atmosfääris õrnade jääkristalliribadena.",
      ],
      [
        "Nimbostratus_cloud",
        "Which thick grey layer commonly brings long-lasting, steady rain or snow?",
        "Milline paks hall pilvekiht toob tavaliselt pikaajalist ühtlast vihma või lund?",
        "nimbostratus",
        "kihtsajupilv",
        "Nimbostratus is a widespread layer cloud associated with continuous precipitation.",
        "Kihtsajupilv on laialdane pilvekiht, millega kaasnevad kestvad sademed.",
      ],
      [
        "Lenticular_cloud",
        "Which smooth, lens-shaped cloud often forms near mountains and is sometimes mistaken for a flying saucer?",
        "Milline sile piklik pilv tekib sageli mägede lähedal ja seda peetakse vahel ekslikult lendavaks taldrikuks?",
        "a lenticular cloud",
        "läätspilv",
        "Lenticular clouds form in standing air waves and have a distinctive lens-like outline.",
        "Läätspilved tekivad seisulainetes ja neil on iseloomulik läätse meenutav kuju.",
        ["lenticular"],
        ["läätsepilv"],
      ],
    ],
  ],
  [
    111,
    "round-two",
    "ecology",
    "Animal Homes",
    "Loomade kodud",
    [
      [
        "Anthill",
        "Which mound of earth often marks the entrance to an underground ant colony?",
        "Milline mullakuhil märgib sageli maa-aluse sipelgakoloonia sissepääsu?",
        "an anthill",
        "sipelgapesa",
        "An anthill is the visible mound above or around an ant colony's underground nest.",
        "Sipelgapesa nähtav mullakuhil asub maa-aluse pesakäikude süsteemi kohal või ümber.",
        ["an ant hill"],
        ["sipelgakuhil"],
      ],
      [
        "Beehive",
        "Which human-made box houses a colony of honey-producing insects?",
        "Milline inimese valmistatud kast on koduks mett tootvate putukate kolooniale?",
        "a beehive",
        "mesilastaru",
        "A beehive is an enclosed structure in which honey bees live and raise their young.",
        "Mesilastaru on suletud ehitis, kus mesilased elavad ja järglasi kasvatavad.",
        ["a bee hive", "a hive", "a honey-bee hive"],
        ["taru", "mesipuu", "mesitaru"],
      ],
      [
        "Paper_wasp",
        "Which paper-like home is built from chewed wood fibres by stinging insects that live in colonies?",
        "Millise paberitaolise ehitise rajavad näritud puidukiududest kolooniana elavad nõelavad putukad?",
        "a wasp nest",
        "herilasepesa",
        "Many wasps that live in colonies build nests from wood fibres chewed into a paper-like pulp.",
        "Paljud kolooniana elavad herilased ehitavad pesa puidukiududest näritud paberitaolisest massist.",
      ],
      [
        "European_rabbit",
        "What do we call the underground tunnel and chamber where a rabbit shelters?",
        "Kuidas nimetatakse maa-alust tunnelit ja kambrit, kus küülik varju leiab?",
        "a burrow",
        "urg",
        "Rabbits dig burrows that provide shelter and places to raise their young.",
        "Küülikud kaevavad urge, mis pakuvad varju ja paika poegade kasvatamiseks.",
        ["a rabbit burrow"],
        ["küülikuurg"],
      ],
      [
        "Beaver_lodge",
        "Which dome-shaped home of branches and mud has an underwater entrance for its swimming builder?",
        "Millise okstest ja mudast kuppelja kodu veealust sissepääsu kasutab selle ujuv ehitaja?",
        "a beaver lodge",
        "kopraonn",
        "A beaver lodge is built from branches and mud and is commonly entered from below the water.",
        "Kopraonn ehitatakse okstest ja mudast ning selle sissepääs paikneb tavaliselt vee all.",
      ],
    ],
  ],
  [
    112,
    "round-two",
    "ecology",
    "Life in a Pond",
    "Elu tiigis",
    [
      [
        "Dragonfly",
        "Which large-eyed insect usually holds its two pairs of transparent wings open at rest and darts above freshwater?",
        "Milline suurte silmade ja kahe paari läbipaistvate tiibadega putukas hoiab tiibu puhkeasendis tavaliselt avatuna ja sööstab magevee kohal?",
        "a dragonfly",
        "kiil",
        "Adult dragonflies are large-eyed flying predators that usually rest with their wings spread open.",
        "Täiskasvanud kiilid on suurte silmadega lendavad kiskjad, kes hoiavad puhates tiibu tavaliselt avatuna.",
      ],
      [
        "Frogspawn",
        "What is the jelly-like mass of eggs laid in water by a frog called?",
        "Kuidas nimetatakse konna vette munetud sültjat munakogumit?",
        "frogspawn",
        "konnakudu",
        "Frogspawn consists of frog eggs surrounded by protective jelly.",
        "Konnakudu koosneb kaitsva sültja kihiga ümbritsetud konnamunadest.",
        ["frog eggs"],
        ["konnamari"],
      ],
      [
        "Duckweed",
        "Which tiny floating green plant can spread into a mat across still freshwater?",
        "Milline tilluke ujuv roheline taim võib katta seisva magevee tiheda vaibana?",
        "duckweed",
        "lemmel",
        "Duckweed consists of very small floating plants that can multiply rapidly on still water.",
        "Lemled on väga väikesed ujuvad taimed, mis võivad seisvas vees kiiresti paljuneda.",
      ],
      [
        "Typha",
        "Which tall waterside plant carries a dense brown flower spike shaped like a sausage?",
        "Millisel kõrgel veekogude ääres kasvaval taimel on tihe pruun vorstikujuline õisik?",
        "reedmace",
        "hundinui",
        "Reedmace grows in wetlands and bears a distinctive dense brown flower spike.",
        "Hundinui kasvab märgaladel ja kannab iseloomulikku tihedat pruuni õisikut.",
        ["cattail", "bulrush", "reed mace"],
        ["soetõlv", "hundinuia taim", "hundinuia perekonna taim"],
      ],
      [
        "Pond_skater",
        "Which long-legged insect glides across a pond by using surface tension?",
        "Milline pikajalgne putukas liugleb pindpinevuse abil üle tiigivee?",
        "a pond skater",
        "liuskur",
        "Pond skaters spread their weight across water-repellent legs and move on the water's surface.",
        "Liuskurid jaotavad raskuse vett hülgavatele jalgadele ja liiguvad veepinnal.",
        ["a water strider"],
        ["vesiliuskur"],
      ],
    ],
  ],
  [
    113,
    "round-two",
    "animals",
    "Animal Babies",
    "Loomalapsed",
    [
      [
        "Kitten",
        "A baby domestic cat is known by which familiar name?",
        "Millise tuttava nimega kutsutakse kodukassi poega?",
        "a kitten",
        "kassipoeg",
        "A kitten is a juvenile cat.",
        "Kassipoeg on noor kass.",
      ],
      [
        "Chick",
        "Which word names a newly hatched chicken or another young bird?",
        "Milline sõna tähistab äsja koorunud kana või mõnda muud linnupoega?",
        "a chick",
        "tibu",
        "A chick is a young bird, especially a recently hatched chicken.",
        "Tibu on noor lind, eriti äsja koorunud kana.",
      ],
      [
        "Duckling",
        "What do we call a young duck, often pictured following its mother across the water?",
        "Kuidas nimetatakse noort parti, keda kujutatakse sageli vees ema järel ujumas?",
        "a duckling",
        "pardipoeg",
        "A duckling is a young duck.",
        "Pardipoeg on noor part.",
      ],
      [
        "Foal",
        "Which name is given to a young horse during its first year?",
        "Kuidas nimetatakse hobusepoega tema esimesel eluaastal?",
        "a foal",
        "varss",
        "A foal is a horse less than one year old.",
        "Varss on alla aasta vanune hobune.",
      ],
      [
        "Fawn",
        "Which name is given to a young deer?",
        "Kuidas nimetatakse hirve poega?",
        "a fawn",
        "hirvetall",
        "A fawn is a young deer.",
        "Hirvetall on noor hirv.",
      ],
    ],
  ],
  [
    114,
    "round-two",
    "animals",
    "Animals Around the World",
    "Loomad maailma eri paigust",
    [
      [
        "Kangaroo",
        "Which Australian animal carries its young in a pouch and moves on powerful hind legs?",
        "Milline Austraalia loom kannab poega kukrus ja liigub võimsate tagajalgade abil?",
        "a kangaroo",
        "känguru",
        "Kangaroos are marsupials with large hind legs and a pouch for developing young.",
        "Kängurud on suurte tagajalgadega kukkurloomad, kelle pojad arenevad kukrus.",
      ],
      [
        "Sloth",
        "Which slow-moving mammal hangs from branches in the forests of Central and South America?",
        "Milline aeglaselt liikuv imetaja ripub Kesk- ja Lõuna-Ameerika metsades okste küljes?",
        "a sloth",
        "laiskloom",
        "Sloths spend much of their lives hanging in trees and move very slowly.",
        "Laiskloomad veedavad suure osa elust puude otsas rippudes ja liiguvad väga aeglaselt.",
      ],
      [
        "Meerkat",
        "Which small southern African mongoose often stands upright while watching for danger?",
        "Milline väike Aafrika lõunaosa mangust tõuseb ohtu valvates sageli tagajalgadele?",
        "a meerkat",
        "surikaat",
        "Meerkats live in social groups where individuals take turns watching for predators.",
        "Surikaadid elavad rühmades, kus isendid valvavad kordamööda kiskjate eest.",
      ],
      [
        "Walrus",
        "Which large Arctic marine mammal has long tusks and a bristly moustache?",
        "Millisel suurel Arktika mereimetajal on pikad kihvad ja harjaselised vurrud?",
        "a walrus",
        "morsk",
        "Walruses use their tusks and sensitive whiskers while living around Arctic seas.",
        "Morsad kasutavad Arktika meredel elades nii kihvu kui ka tundlikke vurre.",
      ],
      [
        "Wombat",
        "Which sturdy Australian marsupial has short legs, powerful digging claws and spends the daytime below ground?",
        "Milline jässakas lühikeste jalgade ja tugevate kaevamisküünistega Austraalia kukkurloom veedab päeva maa all?",
        "a wombat",
        "vombat",
        "Wombats are compact Australian marsupials that excavate extensive underground tunnel systems with strong claws.",
        "Vombatid on jässakad Austraalia kukkurloomad, kes kaevavad tugevate küünistega ulatuslikke maa-aluseid käike.",
      ],
    ],
  ],
  [
    115,
    "round-two",
    "animals",
    "Animals with Standout Looks",
    "Silmapaistva välimusega loomad",
    [
      [
        "Skunk",
        "Which black-and-white mammal defends itself by spraying a powerful-smelling liquid?",
        "Milline mustvalge imetaja kaitseb end tugeva lõhnaga vedelikku pritsides?",
        "a skunk",
        "skunk",
        "Skunks can release a strong-smelling defensive spray from glands near the tail.",
        "Skungid võivad saba lähedal asuvatest näärmetest eritada tugeva lõhnaga kaitsevedelikku.",
      ],
      [
        "Porcupine",
        "Which large rodent is covered with sharp defensive quills?",
        "Milline suur näriline on kaetud teravate kaitsvate okastega?",
        "a porcupine",
        "okassiga",
        "Porcupines are rodents whose modified hairs form stiff defensive quills.",
        "Okassead on närilised, kelle muundunud karvad moodustavad jäigad kaitseokkad.",
      ],
      [
        "European_badger",
        "Which stocky European burrowing mammal has bold black-and-white stripes along its face?",
        "Millisel jässakal Euroopas urge kaevaval imetajal on näol silmatorkavad mustvalged triibud?",
        "a badger",
        "mäger",
        "The European badger is recognised by the contrasting stripes running along its head.",
        "Euroopa mägra tunneb ära mööda pead kulgevate kontrastsete triipude järgi.",
        ["a European badger"],
        ["Euroopa mäger"],
      ],
      [
        "Ring-tailed_lemur",
        "Which Madagascan primate has a long tail marked with alternating dark and pale rings?",
        "Millisel Madagaskari primaadil on pikk vahelduvate tumedate ja heledate rõngastega saba?",
        "a ring-tailed lemur",
        "kassleemur",
        "The ring-tailed lemur is a Madagascan primate known for its boldly banded tail.",
        "Kassleemur on Madagaskari primaat, keda tuntakse silmatorkavalt vöödilise saba järgi.",
      ],
      [
        "Okapi",
        "Which forest mammal from Central Africa has dark reddish fur and zebra-like stripes on its legs?",
        "Millisel Kesk-Aafrika metsaimetajal on tume punakas karv ja sebrataolised triibud jalgadel?",
        "an okapi",
        "okaapi",
        "The okapi is a forest mammal from Central Africa with striped legs.",
        "Okaapi on Kesk-Aafrika triibuliste jalgadega metsaimetaja.",
      ],
    ],
  ],
  [
    116,
    "round-two",
    "animals",
    "Animal Record Breakers",
    "Loomariigi rekordid",
    [
      [
        "African_bush_elephant",
        "Which elephant species is the world's largest living land animal?",
        "Milline elevandiliik on maailma suurim elav maismaaloom?",
        "the African bush elephant",
        "savannielevant",
        "The African bush elephant is the largest living land animal.",
        "Savannielevant on maailma suurim elav maismaaloom.",
        ["an African elephant", "the African savanna elephant"],
        ["Aafrika elevant", "Aafrika savannielevant"],
      ],
      [
        "Giraffe",
        "Which long-necked mammal is the tallest living animal on land?",
        "Milline pika kaelaga imetaja on kõrgeim elav maismaaloom?",
        "a giraffe",
        "kaelkirjak",
        "The giraffe's long legs and neck make it the tallest living terrestrial animal.",
        "Pikad jalad ja kael teevad kaelkirjakust kõrgeima elava maismaalooma.",
      ],
      [
        "Common_ostrich",
        "Which flightless African bird is the largest living bird?",
        "Milline lennuvõimetu Aafrika lind on suurim elus lind?",
        "an ostrich",
        "jaanalind",
        "The ostrich is the largest and heaviest living bird and cannot fly.",
        "Jaanalind on suurim ja raskeim elus lind ning ta ei suuda lennata.",
      ],
      [
        "Whale_shark",
        "Which spotted, plankton-eating shark is the world's largest living fish?",
        "Milline täpiline planktonit sööv hai on maailma suurim elus kala?",
        "a whale shark",
        "vaalhai",
        "The whale shark is the largest living fish and feeds by filtering small organisms from water.",
        "Vaalhai on suurim elus kala ja filtreerib veest toiduks väikeseid organisme.",
      ],
      [
        "Peregrine_falcon",
        "Which bird of prey reaches record speeds when diving steeply after another bird?",
        "Milline röövlind saavutab saagi poole pikeerides rekordkiiruse?",
        "a peregrine falcon",
        "rabapistrik",
        "The peregrine falcon is considered the fastest animal during its high-speed hunting dive.",
        "Rabapistrikku peetakse kiireimaks loomaks tema kiire jahisööstu ajal.",
      ],
    ],
  ],
  [
    117,
    "round-two",
    "animals",
    "Birds You Can Picture",
    "Kergesti äratuntavad linnud",
    [
      [
        "Parrot",
        "Which curved-billed bird is well known for learning to imitate human speech?",
        "Milline kõvera nokaga lind on tuntud selle poolest, et õpib inimkõnet jäljendama?",
        "a parrot",
        "papagoi",
        "Some parrots can learn and reproduce human words and other sounds.",
        "Mõned papagoid suudavad õppida ja korrata inimeste sõnu ning muid helisid.",
      ],
      [
        "Flamingo",
        "Which long-legged wading bird is famous for pink plumage and often stands on one leg?",
        "Milline pikajalgne vees kahlav lind on tuntud roosa sulestiku poolest ja seisab sageli ühel jalal?",
        "a flamingo",
        "flamingo",
        "Flamingos are long-legged waterbirds whose food pigments help colour their feathers pink.",
        "Flamingod on pikajalgsed veelinnud, kelle toidus leiduvad pigmendid aitavad sulestiku roosaks värvida.",
      ],
      [
        "Pelican",
        "Which waterbird catches fish with a long bill and a large expandable throat pouch?",
        "Milline veelind püüab kala pika noka ja suure veniva kurgupaunaga?",
        "a pelican",
        "pelikan",
        "A pelican's large throat pouch helps it catch fish and drain water before swallowing.",
        "Pelikani suur kurgupaun aitab kala püüda ja enne neelamist vee välja lasta.",
      ],
      [
        "Toucan",
        "Which tropical American bird has an unusually large, brightly coloured bill?",
        "Millisel troopilise Ameerika linnul on ebatavaliselt suur ja erksavärviline nokk?",
        "a toucan",
        "tukaan",
        "Toucans are forest birds of tropical America recognised by their oversized colourful bills.",
        "Tukaanid on troopilise Ameerika metsalinnud, keda tunneb ülisuure värvika noka järgi.",
      ],
      [
        "Cassowary",
        "Which large flightless rainforest bird from New Guinea and northeastern Australia has a helmet-like crest and powerful legs?",
        "Millisel Uus-Guinea ja Kirde-Austraalia vihmametsade suurel lennuvõimetul linnul on kiivrit meenutav hari ja tugevad jalad?",
        "a cassowary",
        "kaasuar",
        "Cassowaries are powerful flightless forest birds recognised by the casque on top of the head.",
        "Kaasuarid on võimsad lennuvõimetud metsalinnud, keda tunneb pea peal oleva kiiverja harja järgi.",
      ],
    ],
  ],
  [
    118,
    "round-two",
    "plants",
    "Trees Around Us",
    "Puud meie ümber",
    [
      [
        "Aesculus_hippocastanum",
        "Which tree drops shiny brown conkers from spiny green cases in autumn?",
        "Milline puu poetab sügisel ogalistest rohelistest kupardest läikivaid pruune seemneid?",
        "a horse chestnut",
        "hobukastan",
        "Horse chestnut seeds, commonly called conkers, develop inside spiny green capsules.",
        "Hobukastani seemned arenevad ogalistes rohelistes kupardes.",
      ],
      [
        "Populus_tremula",
        "The flattened leaf stalks of which tree make its leaves tremble in even a light breeze?",
        "Millise puu lamedad leherootsud panevad lehed võbelema isegi nõrga tuulega?",
        "an aspen",
        "haab",
        "Aspen leaves flutter readily because their leaf stalks are flattened from side to side.",
        "Haavalehed võbelevad kergesti, sest nende leherootsud on külgedelt lamedad.",
      ],
      [
        "Willow",
        "Which tree often grows near water and is known for long, flexible, sometimes drooping branches?",
        "Milline puu kasvab sageli vee ääres ning on tuntud pikkade painduvate ja vahel rippuvate okste poolest?",
        "a willow",
        "paju",
        "Willows favour moist ground, and many species have flexible branches and narrow leaves.",
        "Pajud eelistavad niisket pinnast ning paljudel liikidel on painduvad oksad ja kitsad lehed.",
      ],
      [
        "Alder",
        "Which waterside tree produces hanging catkins and small woody structures that resemble cones?",
        "Milline veekogude ääres kasvav puu kannab rippuvaid urbi ja väikeseid käbisid meenutavaid puitunud vilju?",
        "an alder",
        "lepp",
        "Alders often grow on wet ground and bear woody cone-like female catkins.",
        "Lepad kasvavad sageli niiskel pinnasel ja kannavad käbitaolisi puitunud emasurbi.",
      ],
      [
        "Populus",
        "Which fast-growing tree is often planted in tall rows and releases masses of cotton-like seeds?",
        "Millist kiirekasvulist puud istutatakse sageli kõrgete ridadena ja selle seemned levivad vatitaoliste ebemetega?",
        "a poplar",
        "pappel",
        "Many poplars grow rapidly and release tiny seeds attached to cotton-like hairs.",
        "Paljud paplid kasvavad kiiresti ja levitavad vatitaoliste karvakestega seemneid.",
      ],
    ],
  ],
  [
    119,
    "round-two",
    "plants",
    "Garden Flowers",
    "Aialilled",
    [
      [
        "Pansy",
        "Which garden flower often has overlapping petals with dark markings that resemble a face?",
        "Millisel aialillel on sageli kattuvad kroonlehed ja nägu meenutavad tumedad laigud?",
        "a pansy",
        "võõrasema",
        "Garden pansies have broad overlapping petals, often with contrasting face-like markings.",
        "Võõrasemal on laiad kattuvad kroonlehed, millel on sageli kontrastsed nägu meenutavad laigud.",
        ["a garden pansy"],
        ["aedkannike"],
      ],
      [
        "Peony",
        "Which bushy perennial has deeply divided leaves and produces large, often fragrant flowers in late spring or early summer?",
        "Millisel põõsasjal püsikul on sügavalt lõhestunud lehed ja suured, sageli lõhnavad õied hiliskevadel või varasuvel?",
        "a peony",
        "pojeng",
        "Peonies are bushy perennial plants with divided leaves and large flowers that bloom from late spring into early summer.",
        "Pojengid on lõhestunud lehtede ja suurte õitega põõsjad püsikud, mis õitsevad hiliskevadest varasuveni.",
      ],
      [
        "Lily_of_the_valley",
        "Which woodland plant bears a row of small, fragrant white bells on a curved stem?",
        "Millisel metsataimel ripub kaarduvalt varrelt rida väikeseid lõhnavaid valgeid kellukesi?",
        "lily of the valley",
        "maikelluke",
        "Lily of the valley has arching stems of scented, bell-shaped white flowers.",
        "Maikellukesel on kaarduvad varred lõhnavate kellukakujuliste valgete õitega.",
        ["a lily of the valley plant"],
        ["piibeleht"],
      ],
      [
        "Galanthus",
        "Which very early spring flower has a nodding white bloom with three longer outer petals?",
        "Millisel väga varajasel kevadlillel on longus valge õis kolme pikema välimise õiekattelehega?",
        "a snowdrop",
        "lumikelluke",
        "Snowdrops flower early and have three long outer tepals around shorter inner ones.",
        "Lumikellukesed õitsevad vara ning nende kolm pikka välimist õiekattelehte ümbritsevad lühemaid sisemisi.",
      ],
      [
        "Tagetes",
        "French and African are two well-known varieties of which yellow or orange bedding flower?",
        "Millise kollase või oranži peenralille tuntud tüüpe eristatakse inglise keeles sõnadega French ja African?",
        "a marigold",
        "peiulill",
        "Tagetes is the plant genus that includes the flowers commonly called French and African marigolds.",
        "Peiulille perekonda kuuluvad muu hulgas madal ja kõrge peiulill.",
        [
          "a Tagetes marigold",
          "Tagetes",
          "a French marigold",
          "an African marigold",
        ],
        [
          "tageetes",
          "peiulille perekonna taim",
          "madal peiulill",
          "kõrge peiulill",
        ],
      ],
    ],
  ],
  [
    120,
    "round-two",
    "plants",
    "Useful Plants",
    "Kasulikud taimed",
    [
      [
        "Lawsonia_inermis",
        "Which plant provides a dye used for temporary skin designs and for colouring hair?",
        "Millisest taimest saadakse värvainet, mida kasutatakse ajutiste nahamaalingute tegemiseks ja juuste värvimiseks?",
        "henna",
        "henna",
        "Dried henna leaves are ground into a dye used on skin, hair and textiles.",
        "Kuivatatud hennalehtedest jahvatatakse värvainet, mida kasutatakse nahal, juustel ja tekstiilidel.",
      ],
      [
        "Aloe_vera",
        "Which familiar succulent has thick leaves filled with gel used in many skin-care products?",
        "Millisel tuttaval sukulendil on paksud geeliga täidetud lehed, mida kasutatakse paljudes nahahooldustoodetes?",
        "aloe vera",
        "aaloe",
        "Aloe vera is a succulent whose leaf gel is widely used in cosmetics and skin-care products.",
        "Aaloe on sukulent, mille lehegeeli kasutatakse laialdaselt kosmeetika- ja nahahooldustoodetes.",
      ],
      [
        "Sugarcane",
        "Which tall tropical grass has jointed stems that are crushed to release sweet juice?",
        "Millise kõrge troopilise kõrrelise lülilisi varsi purustatakse magusa mahla saamiseks?",
        "sugar cane",
        "suhkruroog",
        "Sugar cane's jointed stems are crushed to extract sucrose-rich juice.",
        "Suhkruroo lülilisi varsi purustatakse sahharoosirikka mahla eraldamiseks.",
        ["sugarcane"],
        ["suhkruroo taim"],
      ],
      [
        "Hevea_brasiliensis",
        "Which tropical tree is tapped for the milky latex used to make tyres and gloves?",
        "Milliselt troopiliselt puult kogutakse piimjat lateksit, millest valmistatakse rehve ja kindaid?",
        "the Brazilian rubber tree",
        "brasiilia kautšukipuu",
        "The Brazilian rubber tree is tapped for latex, the main source of natural rubber.",
        "Brasiilia kautšukipuult kogutakse lateksit, mis on loodusliku kautšuki peamine allikas.",
        ["a rubber tree", "the Pará rubber tree", "Hevea brasiliensis"],
        ["kautšukipuu", "kummipuu", "brasiilia hevea"],
      ],
      [
        "Quercus_suber",
        "Which Mediterranean tree can have its thick bark harvested for bottle stoppers without being felled?",
        "Milliselt Vahemere piirkonna puult saab paksu koort veinipudelite sulgurite valmistamiseks koguda ilma puud langetamata?",
        "a cork oak",
        "korgitamm",
        "Cork oak bark can be removed periodically while the living tree grows a new layer.",
        "Korgitamme koort saab korrapäraselt eemaldada ning elav puu kasvatab uue kihi.",
      ],
    ],
  ],
];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .toLocaleLowerCase("en")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    page,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const subjectKey = `science-nature:${slug(page)}`;
  return {
    clueId: `built-in-science-nature-easy-expansion-${clueNumber}`,
    key: `science-nature-easy-expansion:${categorySetId}:${tier}`,
    factKey: `science-nature-easy-expansion:${slug(page)}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(page).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${page}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    },
  };
}

export const SCIENCE_NATURE_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  SCIENCE_NATURE_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
