import type { EasyExpansionCategory, EasyExpansionQuestion } from "../types";

const BATCH_ID = "04-literature-language";
const PACK_ID = "built-in-literature-language";
const RETRIEVED_AT = "2026-09-06";

type QuestionSeed = readonly [
  page: string,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const LITERATURE_LANGUAGE_EASY_EXPANSION_SEEDS: readonly CategorySeed[] = [
  [
    101,
    "round-one",
    "world-literature",
    "Books and Reading",
    "Raamatud ja lugemine",
    [
      [
        "Library_card",
        "What card identifies a registered library user and lets them borrow books?",
        "Milline kaart tõendab raamatukogu kasutajaks registreerimist ja võimaldab raamatuid laenata?",
        "a library card",
        "lugejakaart",
        "A library card links a borrower to their library account and loans.",
        "Lugejakaart seob laenutaja tema raamatukogukonto ja laenutustega.",
      ],
      [
        "Audiobook",
        "What kind of book do you listen to when a narrator reads the text aloud?",
        "Millist liiki raamatut saab kuulata, kui jutustaja teksti ette loeb?",
        "an audiobook",
        "audioraamat",
        "An audiobook is a spoken recording of a book or other written work.",
        "Audioraamat on raamatu või muu kirjaliku teose etteloetud salvestis.",
        ["an audio book"],
        ["heliraamat"],
      ],
      [
        "Bookworm",
        "What friendly nickname describes someone who loves reading books?",
        "Millise sõbraliku hüüdnimega nimetatakse inimest, kes armastab raamatuid lugeda?",
        "a bookworm",
        "raamatukoi",
        "Bookworm is a familiar figurative name for an enthusiastic reader.",
        "Raamatukoi on levinud kujundlik nimetus innukale lugejale.",
      ],
      [
        "E-reader",
        "What handheld device stores digital books and displays their pages for reading?",
        "Milline käeshoitav seade talletab digiraamatuid ja kuvab nende lehekülgi lugemiseks?",
        "an e-reader",
        "e-luger",
        "An e-reader is designed mainly for storing and reading electronic books.",
        "E-luger on mõeldud peamiselt elektrooniliste raamatute talletamiseks ja lugemiseks.",
      ],
      [
        "Dust_jacket",
        "What removable printed cover wraps around the hard covers of many books?",
        "Milline eemaldatav trükitud ümbris käib paljude raamatute kõvade kaante ümber?",
        "a dust jacket",
        "ümbrispaber",
        "A dust jacket protects a hardback and usually carries its title and cover artwork.",
        "Ümbrispaber kaitseb kõvakaanelist raamatut ning kannab tavaliselt pealkirja ja kaanekujundust.",
        ["a book jacket", "dust wrapper", "dust cover"],
        ["raamatu ümbrispaber", "paberümbris", "raamatu paberümbris"],
      ],
    ],
  ],
  [
    102,
    "round-one",
    "authors",
    "Authors Behind Famous Books",
    "Kuulsate raamatute autorid",
    [
      [
        "Bram_Stoker",
        "Which Irish author wrote the vampire novel Dracula?",
        "Milline iiri kirjanik kirjutas vampiiriromaani „Dracula“?",
        "Bram Stoker",
        "Bram Stoker",
        "Bram Stoker published his famous Gothic vampire novel in 1897.",
        "Bram Stoker avaldas oma kuulsa gooti vampiiriromaani 1897. aastal.",
        ["Stoker"],
        ["Stoker"],
      ],
      [
        "Mario_Puzo",
        "Who wrote the novel The Godfather?",
        "Kes kirjutas romaani „Ristiisa“?",
        "Mario Puzo",
        "Mario Puzo",
        "Mario Puzo wrote the crime novel about the Corleone family.",
        "Mario Puzo kirjutas Corleone perekonnast rääkiva kriminaalromaani.",
        ["Puzo"],
        ["Puzo"],
      ],
      [
        "John_Grisham",
        "Who wrote the bestselling legal thriller The Firm?",
        "Kes kirjutas menuka juriidilise põneviku „Firma“?",
        "John Grisham",
        "John Grisham",
        "John Grisham became known for bestselling novels set around lawyers and courtrooms.",
        "John Grisham sai tuntuks juristide ja kohtusaalide ümber keerlevate menukate romaanidega.",
        ["Grisham"],
        ["Grisham"],
      ],
      [
        "Michael_Ende",
        "Which German author wrote The Neverending Story?",
        "Milline saksa kirjanik kirjutas „Ilma lõputa loo“?",
        "Michael Ende",
        "Michael Ende",
        "Michael Ende wrote the fantasy adventure about Bastian and the world of Fantastica.",
        "Michael Ende kirjutas fantaasiaseikluse Bastianist ja Fantaasiamaast.",
        ["Ende"],
        ["Ende"],
      ],
      [
        "Ken_Follett",
        "Who wrote The Pillars of the Earth and Eye of the Needle?",
        "Kes kirjutas romaanid „Maa sambad“ ja „Nõelasilm“?",
        "Ken Follett",
        "Ken Follett",
        "Ken Follett writes historical epics and thrillers, including both of these bestselling novels.",
        "Ken Follett kirjutab ajaloolisi suurromaane ja põnevikke, sealhulgas neid kaht menukit.",
        ["Follett"],
        ["Follett"],
      ],
    ],
  ],
  [
    103,
    "round-one",
    "novels",
    "Famous Novels in One Sentence",
    "Kuulsad romaanid ühe lausega",
    [
      [
        "The_Old_Man_and_the_Sea",
        "Which Hemingway novella has the fisherman Santiago battle a giant marlin?",
        "Millises Hemingway lühiromaanis võitleb kalur Santiago hiiglasliku marliiniga?",
        "The Old Man and the Sea",
        "„Vanamees ja meri“",
        "Santiago hooks an enormous marlin after a long run of unsuccessful fishing.",
        "Santiago püüab pärast pikka saagita perioodi hiiglasliku marliini õnge otsa.",
        ["Old Man and the Sea"],
        ["The Old Man and the Sea"],
      ],
      [
        "The_Alchemist_(novel)",
        "Which Paulo Coelho novel sends the shepherd Santiago searching for treasure near the Egyptian pyramids?",
        "Millises Paulo Coelho romaanis läheb karjus Santiago Egiptuse püramiidide lähedale aaret otsima?",
        "The Alchemist",
        "„Alkeemik“",
        "Santiago's journey toward the pyramids becomes a story about pursuing a personal dream.",
        "Santiago teekonnast püramiidide poole saab lugu isikliku unistuse järgimisest.",
        ["Alchemist"],
        ["The Alchemist"],
      ],
      [
        "The_Book_Thief",
        "Which novel narrated by Death follows Liesel Meminger in Nazi Germany?",
        "Milline Surma jutustatud romaan jälgib Liesel Memingeri elu natsi-Saksamaal?",
        "The Book Thief",
        "„Raamatuvaras“",
        "Markus Zusak's novel has Death narrate Liesel's life and her love of stolen books.",
        "Markus Zusaki romaanis jutustab Surm Lieseli elust ja tema armastusest varastatud raamatute vastu.",
        ["Book Thief"],
        ["The Book Thief"],
      ],
      [
        "The_Girl_on_the_Train_(novel)",
        "Which thriller follows Rachel after she sees something shocking from a train window during her daily journey?",
        "Milline põnevik jälgib Rachelit, kes näeb oma igapäevasel rongisõidul aknast midagi vapustavat?",
        "The Girl on the Train",
        "„Tüdruk rongis“",
        "Paula Hawkins's thriller begins when Rachel's daily view from the train draws her into a mystery.",
        "Paula Hawkinsi põnevik algab siis, kui Racheli igapäevane vaade rongiaknast tõmbab ta mõistatusse.",
        ["Girl on the Train"],
        ["The Girl on the Train"],
      ],
      [
        "Madame_Bovary",
        "Which Gustave Flaubert novel follows Emma, a doctor's wife dissatisfied with provincial life?",
        "Milline Gustave Flaubert’i romaan jälgib Emmat, provintsielus pettunud arsti abikaasat?",
        "Madame Bovary",
        "„Madame Bovary“",
        "Emma Bovary seeks excitement beyond her marriage, with disastrous consequences.",
        "Emma Bovary otsib oma abielust väljaspool põnevust ning sellel on traagilised tagajärjed.",
      ],
    ],
  ],
  [
    104,
    "round-one",
    "poetry",
    "Poetry in Many Forms",
    "Luule eri vormides",
    [
      [
        "Haiku",
        "Which short Japanese poetic form is commonly arranged in three lines when written in English?",
        "Millist lühikest jaapani luulevormi esitatakse inglise keeles sageli kolmerealisena?",
        "a haiku",
        "haiku",
        "Modern English-language haiku commonly use three lines, while Japanese haiku may appear in a single line.",
        "Tänapäeva ingliskeelne haiku on sageli kolmerealine, jaapani haiku võib aga olla kirjutatud ühe reana.",
      ],
      [
        "Nursery_rhyme",
        "What kind of simple traditional poem or song is recited to young children?",
        "Kuidas nimetatakse lihtsat pärimuslikku luuletust või laulu, mida loetakse väikestele lastele?",
        "a nursery rhyme",
        "lastesalm",
        "Nursery rhymes are short traditional verses shared with young children.",
        "Lastesalmid on lühikesed pärimuslikud värsid, mida lastele edasi antakse.",
        ["a nursery song"],
        ["lastelaul"],
      ],
      [
        "Poetry_slam",
        "What live competition has poets perform work for an audience and judges?",
        "Millises elavas võistluses esitavad luuletajad publikule ja kohtunikele luulet?",
        "a poetry slam",
        "luuleprõmm",
        "A poetry slam combines performed verse with judging by a panel or audience members.",
        "Luuleprõmm ühendab esitatud värsid žürii või publiku antud hinnetega.",
        ["poetry slam competition"],
        ["poetry slam"],
      ],
      [
        "Spoken_word",
        "What performance art presents poetry aloud and emphasises the sound of the poet's voice?",
        "Milline esituskunst kannab luulet ette ja rõhutab luuletaja hääle kõla?",
        "spoken word",
        "spoken word",
        "Spoken word poetry centres on live recitation, using voice and intonation as expressive tools.",
        "Kõneldud sõna luule keskmes on elav esitus, milles häält ja intonatsiooni kasutatakse väljendusvahendina.",
        ["spoken-word poetry", "performance poetry"],
        ["kõneldud sõna", "esitusluule"],
      ],
      [
        "Elegy",
        "What kind of reflective poem traditionally mourns someone who has died?",
        "Millist liiki mõtisklev luuletus leinab tavaliselt surnud inimest?",
        "an elegy",
        "eleegia",
        "An elegy is a poem of mourning or solemn reflection, often written for the dead.",
        "Eleegia on leina- või tõsise mõtiskluse luuletus, mis on sageli kirjutatud surnu mälestuseks.",
      ],
    ],
  ],
  [
    105,
    "round-one",
    "drama",
    "Words from the Theatre",
    "Sõnad teatrist",
    [
      [
        "Dress_rehearsal",
        "What final practice run uses costumes, lighting and other show conditions before opening night?",
        "Kuidas nimetatakse viimast proovietendust, kus enne esietendust kasutatakse kostüüme, valgustust ja muid etenduse tingimusi?",
        "a dress rehearsal",
        "peaproov",
        "A dress rehearsal runs the production much as the audience will later see it.",
        "Peaproovis mängitakse lavastus läbi peaaegu samamoodi, nagu publik seda hiljem näeb.",
      ],
      [
        "Standing_ovation",
        "What enthusiastic tribute happens when an audience rises to applaud?",
        "Kuidas nimetatakse vaimustunud austusavaldust, mille puhul publik tõuseb püsti ja aplodeerib?",
        "a standing ovation",
        "püstijalu aplaus",
        "During a standing ovation, spectators stand while showing their approval with applause.",
        "Püstijalu aplausi ajal seisavad pealtvaatajad ja avaldavad esinejatele tunnustust.",
        ["standing applause"],
        ["püsti aplodeerimine"],
      ],
      [
        "Understudy",
        "Who learns a stage role so they can replace the regular performer if needed?",
        "Kes õpib lavarolli selgeks, et vajaduse korral põhiesinejat asendada?",
        "an understudy",
        "dublant",
        "An understudy prepares to take over a particular role when the usual performer is unavailable.",
        "Dublant valmistub kindlat rolli üle võtma, kui tavapärane esitaja ei saa lavale minna.",
        ["a substitute performer"],
        ["asendusnäitleja"],
      ],
      [
        "Play_(theatre)",
        "What written instructions in a play tell performers when to enter or exit, or how to deliver a line?",
        "Kuidas nimetatakse näidendi kirjalikke juhiseid, mis ütlevad esitajatele, millal lavale tulla või lavalt lahkuda ja kuidas repliiki esitada?",
        "stage directions",
        "remargid",
        "Stage directions appear alongside dialogue and can specify entrances, exits and how lines are delivered.",
        "Remargid on tegelaste repliikidest eraldi ning võivad määrata lavale tulekut, lavalt lahkumist ja repliikide esitamise viisi.",
        ["a stage direction", "stage notes", "stage instructions"],
        ["remarg", "lavamärkused", "lavajuhised"],
      ],
      [
        "Curtain_call",
        "What end-of-show appearance lets performers return to the stage and acknowledge applause?",
        "Kuidas nimetatakse etenduse lõpuhetke, mil esitajad tulevad lavale publiku aplausi vastu võtma?",
        "a curtain call",
        "lõpukummardus",
        "During a curtain call, the cast returns to receive the audience's applause.",
        "Lõpukummarduse ajal tuleb trupp tagasi lavale publiku aplausi vastu võtma.",
        ["the cast's bow"],
        ["näitlejate kummardus"],
      ],
    ],
  ],
  [
    106,
    "round-one",
    "literary-movements",
    "How Stories Work",
    "Kuidas lood töötavad",
    [
      [
        "Happy_ending",
        "What kind of ending leaves the main characters in a favourable situation?",
        "Kuidas nimetatakse lõppu, mis jätab peategelased heasse olukorda?",
        "a happy ending",
        "õnnelik lõpp",
        "A happy ending resolves the central conflict positively for the main characters.",
        "Õnnelik lõpp lahendab keskse konflikti peategelaste jaoks positiivselt.",
      ],
      [
        "Flashback_(narrative)",
        "What storytelling device pauses the present action to show an earlier event?",
        "Milline jutustamisvõte peatab olevikus toimuva, et näidata varasemat sündmust?",
        "a flashback",
        "tagasivaade",
        "A flashback moves the narrative back in time to reveal earlier events.",
        "Tagasivaade viib jutustuse ajas tagasi, et näidata varem toimunut.",
        ["a flashback scene"],
        ["flashback"],
      ],
      [
        "Prequel",
        "What kind of later-made story takes place before an earlier work in the same series?",
        "Kuidas nimetatakse hiljem loodud lugu, mille tegevus toimub enne sama sarja varem ilmunud teose sündmusi?",
        "a prequel",
        "eellugu",
        "A prequel is released after another work but tells events that occur earlier.",
        "Eellugu ilmub teise teose järel, kuid jutustab varem toimunud sündmustest.",
        ["a prequel story"],
        ["prequel"],
      ],
      [
        "Cliffhanger",
        "What do we call an ending that stops at a tense moment and leaves the outcome unresolved?",
        "Kuidas nimetatakse lõppu, mis katkeb kõige pingelisemas kohas ja jätab tulemuse lahtiseks?",
        "a cliffhanger",
        "cliffhanger",
        "A cliffhanger delays the resolution so the audience wants to know what happens next.",
        "Cliffhanger lükkab lahenduse edasi, et publik tahaks teada, mis juhtub järgmisena.",
      ],
      [
        "Red_herring",
        "What fishy idiom means a false lead that distracts from the real solution?",
        "Kuidas nimetatakse loo võtet, mis suunab lugeja eksliku järelduse poole ja tegelikust lahendusest eemale?",
        "a red herring",
        "valejälg",
        "A red herring sends readers or viewers toward a false conclusion.",
        "Eksitav vihje suunab lugeja või vaataja vale järelduse poole.",
        ["a misleading clue"],
        ["eksitav vihje"],
      ],
    ],
  ],
  [
    107,
    "round-one",
    "fictional-characters",
    "Famous Fictional Companions",
    "Kuulsad kaaslased kirjanduses",
    [
      [
        "Obelix",
        "Which huge, super-strong friend accompanies Asterix on his adventures?",
        "Milline hiiglaslik ja ülitugev sõber saadab Asterixi tema seiklustel?",
        "Obelix",
        "Obelix",
        "Obelix delivers menhirs and joins Asterix in resisting the Romans.",
        "Obelix veab menhireid ja aitab Asterixil roomlastele vastu panna.",
      ],
      [
        "Tinker_Bell",
        "Which tiny fairy is Peter Pan's jealous but loyal companion?",
        "Milline tilluke haldjas on Peter Pani armukade, kuid ustav kaaslane?",
        "Tinker Bell",
        "Tinker Bell",
        "Tinker Bell accompanies Peter Pan and communicates through the sound of bells.",
        "Tinker Bell saadab Peter Pani ning suhtleb kellukeste heliga.",
        ["Tinkerbell"],
        ["Tinkerbell"],
      ],
      [
        "Baloo",
        "Which bear teaches Mowgli the law of the jungle?",
        "Milline karu õpetab Mowglile džungliseadust?",
        "Baloo",
        "Baloo",
        "Baloo is Mowgli's bear teacher and friend in The Jungle Book.",
        "Baloo on „Džungliraamatus“ Mowgli õpetaja ja sõber.",
      ],
      [
        "Captain_Haddock",
        "Which bearded sea captain is Tintin's hot-tempered but loyal friend?",
        "Milline habemikust merekapten on Tintini äkilise loomuga, kuid ustav sõber?",
        "Captain Haddock",
        "kapten Haddock",
        "Captain Haddock joins Tintin on many adventures and is known for colourful outbursts.",
        "Kapten Haddock saadab Tintini paljudel seiklustel ja on tuntud värvikate vihapursete poolest.",
        ["Haddock"],
        ["Haddock"],
      ],
      [
        "Snufkin",
        "Which green-hatted wanderer is Moomintroll's free-spirited friend?",
        "Milline rohelise mütsiga rändur on Muumitrolli vabadust armastav sõber?",
        "Snufkin",
        "Nuuskmõmmik",
        "Snufkin values freedom, travels south each winter and returns to Moominvalley in spring.",
        "Nuuskmõmmik hindab vabadust, rändab talveks lõunasse ja naaseb kevadel Muumiorgu.",
        ["Nuuskmõmmik"],
        ["Snufkin"],
      ],
    ],
  ],
  [
    108,
    "round-one",
    "linguistics",
    "Grammar from School",
    "Kooligrammatika",
    [
      [
        "Pronoun",
        "Which word class can stand in for a noun, as she can replace Maria?",
        "Milline sõnaliik võib asendada nimisõna, nagu „tema“ võib asendada nime Maria?",
        "a pronoun",
        "asesõna",
        "Pronouns refer to people or things without repeating their names.",
        "Asesõnad viitavad inimestele või asjadele nende nime kordamata.",
      ],
      [
        "Adverb",
        "Which word class can modify a verb by telling how, when or where something happens?",
        "Milline sõnaliik võib täpsustada tegusõna, näidates, kuidas, millal või kus midagi toimub?",
        "an adverb",
        "määrsõna",
        "Adverbs commonly add information about manner, time, place or degree.",
        "Määrsõnad lisavad tavaliselt teavet viisi, aja, koha või määra kohta.",
      ],
      [
        "Proper_noun",
        "What kind of noun names a particular person or place and normally begins with an uppercase character?",
        "Milline nimisõna liik nimetab kindlat inimest või kohta ja algab tavaliselt suure tähega?",
        "a proper noun",
        "pärisnimi",
        "Names such as Maria and Tallinn are proper nouns rather than general labels.",
        "Maria ja Tallinn on pärisnimed, mitte üldnimed.",
        ["a proper name"],
        ["prooprium"],
      ],
      [
        "Auxiliary_verb",
        "What kind of verb helps another verb express tense, mood or voice?",
        "Milline tegusõna aitab teisel tegusõnal väljendada aega, kõneviisi või tegumoodi?",
        "an auxiliary verb",
        "abitegusõna",
        "An auxiliary verb works with a main verb, as have does in have finished.",
        "Abitegusõna esineb koos põhiverbiga, näiteks „olen“ ühendis „olen lõpetanud“.",
        ["a helping verb"],
        ["abiverb"],
      ],
      [
        "Degrees_of_comparison_of_adjectives_and_adverbs",
        "Which degree of comparison appears in taller and faster?",
        "Milline võrdlusaste esineb sõnades „pikem“ ja „kiirem“?",
        "the comparative degree",
        "keskvõrre",
        "The comparative degree compares two things, often by adding -er in English.",
        "Keskvõrre võrdleb kaht asja ja selle tunnus on eesti keeles tavaliselt -m.",
        ["the comparative", "a comparative form"],
        ["komparatiiv", "keskvõrde vorm"],
      ],
    ],
  ],
  [
    109,
    "round-one",
    "etymology",
    "Names Hidden in Words",
    "Nimed sõnade sees",
    [
      [
        "Celsius",
        "On which temperature scale are water's freezing and boiling points about 0 and 100 degrees at standard atmospheric pressure?",
        "Millisel temperatuuriskaalal on vee külmumis- ja keemispunkt normaalrõhul ligikaudu 0 ja 100 kraadi?",
        "the Celsius scale",
        "Celsiuse skaala",
        "The scale is named after Swedish astronomer Anders Celsius, who proposed its first version in 1742.",
        "Skaala on nimetatud Rootsi astronoomi Anders Celsiuse järgi, kes esitas selle esimese versiooni 1742. aastal.",
        ["Celsius"],
        ["Celsius"],
      ],
      [
        "Volt",
        "Which unit of electrical potential is named after Alessandro Volta?",
        "Milline elektrilise potentsiaali ühik sai nime Alessandro Volta järgi?",
        "the volt",
        "volt",
        "The SI unit honours Alessandro Volta, an early pioneer of electrical science.",
        "SI-ühik kannab elektriuuringute teerajaja Alessandro Volta nime.",
      ],
      [
        "Richter_scale",
        "Which well-known scale traditionally measures earthquake magnitude?",
        "Milline tuntud skaala mõõdab traditsiooniliselt maavärina magnituudi?",
        "the Richter scale",
        "Richteri skaala",
        "Charles Richter helped develop the magnitude scale that became associated with his surname.",
        "Charles Richter aitas välja töötada magnituudiskaala, mida hakati seostama tema perekonnanimega.",
        ["Richter"],
        ["Richter"],
      ],
      [
        "Heimlich_maneuver",
        "Which first-aid technique uses abdominal thrusts to help a choking person?",
        "Millise esmaabivõtte puhul kasutatakse lämbuva inimese aitamiseks kõhutõukeid?",
        "the Heimlich manoeuvre",
        "Heimlichi võte",
        "The technique uses abdominal thrusts to help clear an obstructed airway.",
        "Selle võtte puhul kasutatakse hingamistee vabastamiseks kõhutõukeid.",
        ["the Heimlich maneuver"],
        ["Heimlichi manööver"],
      ],
      [
        "Beaufort_scale",
        "Which numbered scale describes wind force through observable conditions at sea or on land?",
        "Milline numbriline skaala kirjeldab tuule tugevust merel või maismaal nähtavate olude järgi?",
        "the Beaufort scale",
        "Beauforti skaala",
        "The Beaufort scale links numbered wind force to observable conditions at sea or on land.",
        "Beauforti skaala seob tuule tugevuse astmed merel või maismaal nähtavate oludega.",
        ["Beaufort"],
        ["Beaufort"],
      ],
    ],
  ],
  [
    110,
    "round-one",
    "writing-systems",
    "Marks on the Keyboard",
    "Märgid klaviatuuril",
    [
      [
        "Capitalization",
        "What kind of letter normally begins a sentence and a person's name?",
        "Milline täht alustab tavaliselt lauset ja inimese nime?",
        "a capital letter",
        "suurtäht",
        "Capital letters mark sentence beginnings and proper names in English and Estonian.",
        "Suurtähed märgivad eesti ja inglise keeles lause algust ning pärisnimesid.",
        ["an uppercase letter", "an upper-case character"],
        ["uppercase letter", "capital letter"],
      ],
      [
        "Exclamation_mark",
        "Which punctuation mark can show strong feeling and looks like a vertical stroke above a dot?",
        "Milline kirjavahemärk võib väljendada tugevat tunnet ning näeb välja nagu püstkriips punkti kohal?",
        "an exclamation mark",
        "hüüumärk",
        "An exclamation mark ends an exclamation and can add emphasis.",
        "Hüüumärk lõpetab hüüdlause ja võib lisada rõhku.",
        ["an exclamation point", "bang"],
        ["exclamation point", "exclamation mark"],
      ],
      [
        "Percent_sign",
        "Which symbol placed after a number means per hundred?",
        "Milline arvu järele kirjutatav märk tähendab „saja kohta“?",
        "a percent sign",
        "protsendimärk",
        "The percent sign shows that a number is expressed as a fraction of one hundred.",
        "Protsendimärk näitab, et arv on väljendatud osana sajast.",
      ],
      [
        "Hyphen",
        "Which short horizontal mark joins words in compounds such as well-known?",
        "Milline lühike rõhtmärk ühendab liitsõna osi, näiteks ingliskeelses sõnas well-known?",
        "a hyphen",
        "sidekriips",
        "A hyphen joins words or word parts and is shorter than a dash.",
        "Sidekriips ühendab sõnu või sõnaosi ning on mõttekriipsust lühem.",
      ],
      [
        "Underscore",
        "Which low horizontal character often replaces a space in usernames and filenames?",
        "Milline madal rõhtmärk asendab kasutajanimedes ja failinimedes sageli tühikut?",
        "an underscore",
        "alakriips",
        "An underscore is written below the usual text baseline and is common in computing.",
        "Alakriips kirjutatakse tavalisest tekstijoonest allapoole ja seda kasutatakse sageli arvutites.",
        ["low line", "low dash"],
        ["underscore", "allkriips"],
      ],
    ],
  ],
  [
    111,
    "round-two",
    "world-literature",
    "Stories from Around the World",
    "Lood maailma eri paigust",
    [
      [
        "Journey_to_the_Centre_of_the_Earth",
        "Which Jules Verne adventure sends a professor into an Icelandic volcano?",
        "Millises Jules Verne'i seiklusromaanis siseneb professor Islandi vulkaani?",
        "Journey to the Centre of the Earth",
        "„Reis maakera südamesse“",
        "The travellers descend through Snæfellsjökull and discover a vast underground world.",
        "Rändurid laskuvad Snæfellsjökulli kaudu ja avastavad tohutu maa-aluse maailma.",
        ["Journey to the Center of the Earth"],
        ["Journey to the Center of the Earth"],
      ],
      [
        "The_Prince_and_the_Pauper",
        "Which Mark Twain novel has two lookalike boys from very different backgrounds swap lives?",
        "Millises Mark Twaini romaanis vahetavad kaks eri taustaga, kuid väga sarnast poissi omavahel kohad?",
        "The Prince and the Pauper",
        "„Prints ja kerjus“",
        "Prince Edward and the poor boy Tom Canty exchange clothes and are mistaken for one another.",
        "Prints Edward ja vaene poiss Tom Canty vahetavad riided ning neid peetakse teineteiseks.",
        [],
        [],
      ],
      [
        "Doctor_Zhivago_(novel)",
        "Which Boris Pasternak novel follows a physician and poet through the Russian Revolution?",
        "Milline Boriss Pasternaki romaan jälgib arsti ja luuletajat Vene revolutsiooni keerises?",
        "Doctor Zhivago",
        "„Doktor Živago“",
        "Yuri Zhivago's personal life unfolds amid revolution and civil war in Russia.",
        "Juri Živago isiklik elu kulgeb Venemaa revolutsiooni ja kodusõja taustal.",
        ["Dr Zhivago"],
        ["Doctor Zhivago"],
      ],
      [
        "The_Kite_Runner",
        "Which Khaled Hosseini novel follows Amir and Hassan from childhood in Kabul?",
        "Milline Khaled Hosseini romaan jälgib Amiri ja Hassani lapsepõlve Kabulis?",
        "The Kite Runner",
        "„Lohejooksja“",
        "The novel links Amir and Hassan's friendship to Afghanistan's turbulent modern history.",
        "Romaan seob Amiri ja Hassani sõpruse Afganistani rahutu lähiajalooga.",
        ["Kite Runner"],
        ["The Kite Runner"],
      ],
      [
        "Sophie's_World",
        "Which Norwegian novel teaches philosophy through mysterious letters sent to a schoolgirl named Sophie?",
        "Milline norra romaan õpetab filosoofiat salapäraste kirjade kaudu, mis saadetakse koolitüdruk Sofiele?",
        "Sophie's World",
        "„Sofie maailm“",
        "Jostein Gaarder's novel combines Sophie's story with an introduction to major philosophers.",
        "Jostein Gaarderi romaan ühendab Sofie loo sissejuhatusega tuntud filosoofide mõtetesse.",
        ["Sophies World"],
        ["Sophie's World"],
      ],
    ],
  ],
  [
    112,
    "round-two",
    "authors",
    "Women Behind Famous Books",
    "Naised kuulsate raamatute taga",
    [
      [
        "J._K._Rowling",
        "Who wrote the seven main Harry Potter novels?",
        "Kes kirjutas seitse peamist Harry Potteri romaani?",
        "J. K. Rowling",
        "J. K. Rowling",
        "J. K. Rowling wrote the novel series about Harry's years at Hogwarts.",
        "J. K. Rowling kirjutas romaanisarja Harry õpinguaastatest Sigatüüka koolis.",
        ["JK Rowling", "Rowling"],
        ["JK Rowling", "Rowling"],
      ],
      [
        "Enid_Blyton",
        "Who wrote the Famous Five and Secret Seven adventure series?",
        "Kes kirjutas seikluslood neljast noorest sõbrast ja nende koerast Timmyst?",
        "Enid Blyton",
        "Enid Blyton",
        "Enid Blyton created both groups of young adventurers in long-running book series.",
        "Enid Blyton kirjutas palju noortele mõeldud seiklusraamatuid, sealhulgas lood viiest sõbrast.",
        ["Blyton"],
        ["Blyton"],
      ],
      [
        "Louisa_May_Alcott",
        "Who wrote the novel Little Women?",
        "Kes kirjutas romaani „Väikesed naised“?",
        "Louisa May Alcott",
        "Louisa May Alcott",
        "Louisa May Alcott is best known for writing Little Women and its sequels.",
        "Louisa May Alcott on tuntud eelkõige „Väikeste naiste“ ja selle järgede autorina.",
        ["Alcott"],
        ["Alcott"],
      ],
      [
        "Frances_Hodgson_Burnett",
        "Who wrote The Secret Garden and A Little Princess?",
        "Kes kirjutas „Salaaia“ ja „Väikese printsessi“?",
        "Frances Hodgson Burnett",
        "Frances Hodgson Burnett",
        "Frances Hodgson Burnett wrote both enduring children's novels.",
        "Frances Hodgson Burnett kirjutas mõlemad tänaseni armastatud lasteromaanid.",
        ["Burnett"],
        ["Burnett"],
      ],
      [
        "Elena_Ferrante",
        "Which Italian author wrote My Brilliant Friend and the other Neapolitan Novels?",
        "Milline itaalia kirjanik kirjutas „Minu geniaalse sõbranna“ ja teised Napoli-romaanid?",
        "Elena Ferrante",
        "Elena Ferrante",
        "Elena Ferrante's four-book series follows the lifelong friendship of Elena and Lila.",
        "Elena Ferrante neljaosaline sari jälgib Elena ja Lila elukestvat sõprust.",
        ["Ferrante"],
        ["Ferrante"],
      ],
    ],
  ],
  [
    113,
    "round-two",
    "novels",
    "Twentieth-Century Classics",
    "20. sajandi klassika",
    [
      [
        "All_Quiet_on_the_Western_Front",
        "Which novel follows German soldier Paul Bäumer during the First World War?",
        "Milline romaan jälgib saksa sõdurit Paul Bäumerit Esimese maailmasõja ajal?",
        "All Quiet on the Western Front",
        "„Läänerindel muutuseta“",
        "Erich Maria Remarque's novel depicts the physical and emotional strain of trench warfare.",
        "Erich Maria Remarque'i romaan kujutab kaevikusõja füüsilist ja hingelist koormat.",
        [],
        [],
      ],
      [
        "A_Clockwork_Orange_(novel)",
        "Which Anthony Burgess novel is narrated by Alex in slang called Nadsat?",
        "Millist Anthony Burgessi romaani jutustab Alex slängis nimega nadsat?",
        "A Clockwork Orange",
        "„Kellavärgiga apelsin“",
        "Alex narrates the violent dystopian story in a distinctive invented vocabulary.",
        "Alex jutustab vägivaldset düstoopialugu eripärases väljamõeldud sõnavaras.",
      ],
      [
        "Memoirs_of_a_Geisha",
        "Which novel follows Chiyo as she becomes the geisha Sayuri in Kyoto?",
        "Milline romaan jälgib Chiyot, kellest saab Kyotos geiša Sayuri?",
        "Memoirs of a Geisha",
        "„Geiša memuaarid“",
        "Arthur Golden's novel tells Sayuri's life story from childhood onward.",
        "Arthur Goldeni romaan jutustab Sayuri eluloo alates lapsepõlvest.",
        [],
        [],
      ],
      [
        "The_English_Patient",
        "Which novel has nurse Hana care for a badly burned patient in an Italian villa near the end of the Second World War?",
        "Millises romaanis hoolitseb õde Hana Teise maailmasõja lõpul Itaalia villas raskelt põlenud patsiendi eest?",
        "The English Patient",
        "„Inglise patsient“",
        "Michael Ondaatje's novel gradually uncovers the histories of four people sheltering in the villa.",
        "Michael Ondaatje romaan avab järk-järgult villas varjuva nelja inimese mineviku.",
        [],
        [],
      ],
      [
        "Flowers_for_Algernon",
        "Which novel tells of Charlie Gordon undergoing an experimental operation intended to increase his intelligence?",
        "Millises romaanis osaleb Charlie Gordon katses, mille eesmärk on suurendada tema intelligentsust?",
        "Flowers for Algernon",
        "„Lilled Algernonile“",
        "Daniel Keyes tells Charlie's story through progress reports that change as the experiment takes effect.",
        "Daniel Keyes jutustab Charlie loo arenguaruannete kaudu, mis katse mõju avaldudes muutuvad.",
        [],
        [],
      ],
    ],
  ],
  [
    114,
    "round-two",
    "poetry",
    "Poets You May Know",
    "Tuntud luuletajad",
    [
      [
        "Johann_Wolfgang_von_Goethe",
        "Which German writer and poet created the two-part drama Faust?",
        "Milline saksa kirjanik ja luuletaja lõi kaheosalise draama „Faust“?",
        "Johann Wolfgang von Goethe",
        "Johann Wolfgang von Goethe",
        "Faust is one of Goethe's best-known and most influential works.",
        "„Faust“ on Goethe üks tuntumaid ja mõjukamaid teoseid.",
        ["Goethe"],
        ["Goethe"],
      ],
      [
        "Sappho",
        "Which ancient Greek lyric poet came from the island of Lesbos?",
        "Milline Vana-Kreeka lüüriline luuletaja pärines Lesbose saarelt?",
        "Sappho",
        "Sappho",
        "Sappho was a lyric poet from Lesbos whose verse was originally accompanied by music.",
        "Sappho oli Lesboselt pärit lüüriline luuletaja, kelle värsse esitati algselt muusika saatel.",
        ["Sappho of Lesbos"],
        ["Sapfo"],
      ],
      [
        "Ovid",
        "Which Roman poet wrote Metamorphoses, a long work of mythological transformation stories?",
        "Milline Rooma luuletaja kirjutas „Metamorfoosid“, pika mütoloogiliste muundumislugude kogumiku?",
        "Ovid",
        "Ovidius",
        "Ovid's Metamorphoses is a fifteen-book mythological narrative and a major source for classical myths.",
        "Ovidiuse „Metamorfoosid“ on viieteistkümnest raamatust koosnev mütoloogiline jutustus ja tähtis antiikmüütide allikas.",
        ["Ovidius"],
        ["Ovid"],
      ],
      [
        "Emily_Dickinson",
        "Which reclusive American poet from Amherst is famous for short lines and distinctive dashes?",
        "Milline Amherstis elanud eraklik ameerika luuletaja on tuntud lühikeste ridade ja iseloomulike mõttekriipsude poolest?",
        "Emily Dickinson",
        "Emily Dickinson",
        "Dickinson wrote nearly 1,800 poems, most of which appeared after her death.",
        "Dickinson kirjutas ligi 1800 luuletust, millest enamik avaldati pärast tema surma.",
        ["Dickinson"],
        ["Dickinson"],
      ],
      [
        "Rumi",
        "Which thirteenth-century Persian-language poet and Sufi mystic is often known by one short name?",
        "Millist 13. sajandi pärsiakeelset luuletajat ja sufi müstikut tuntakse sageli ühe lühikese nimega?",
        "Rumi",
        "Rumi",
        "Rumi's lyric and narrative poetry has remained influential far beyond the Persian-speaking world.",
        "Rumi lüüriline ja jutustav luule on jäänud mõjukaks kaugel väljaspool pärsiakeelset maailma.",
        ["Jalal al-Din Rumi", "Jalāl al-Dīn Rūmī"],
        ["Džalāl ad-Dīn Rūmī", "Jalāl al-Dīn Rūmī"],
      ],
    ],
  ],
  [
    115,
    "round-two",
    "drama",
    "Musicals on Stage",
    "Muusikalid laval",
    [
      [
        "Grease_(musical)",
        "Which musical follows teenagers Danny and Sandy at Rydell High School?",
        "Milline muusikal jälgib noori Dannyt ja Sandyt Rydelli keskkoolis?",
        "Grease",
        "„Grease“",
        "Grease pairs Danny and Sandy's romance with 1950s-style songs and dancing.",
        "„Grease“ ühendab Danny ja Sandy armuloo 1950. aastate stiilis laulude ja tantsudega.",
      ],
      [
        "Starlight_Express",
        "Which Andrew Lloyd Webber musical has actors perform on roller skates as racing trains?",
        "Millises Andrew Lloyd Webberi muusikalis mängivad näitlejad rulluiskudel võidusõitu pidavaid ronge?",
        "Starlight Express",
        "„Starlight Express“",
        "The actors play trains on roller skates as the steam engine Rusty competes against modern locomotives.",
        "Näitlejad kehastavad rulluiskudel ronge, kui auruvedur Rusty võistleb moodsate veduritega.",
      ],
      [
        "Evita_(musical)",
        "Which musical about Eva Perón includes the song Don't Cry for Me Argentina?",
        "Milline Eva Perónist rääkiv muusikal sisaldab laulu „Don't Cry for Me Argentina“?",
        "Evita",
        "„Evita“",
        "Evita dramatises Eva Perón's rise to prominence in Argentina.",
        "„Evita“ kujutab Eva Peróni tõusu Argentina avaliku elu keskmesse.",
      ],
      [
        "The_Rocky_Horror_Show",
        "Which rock musical features the newly engaged Brad and Janet and the scientist Frank-N-Furter?",
        "Millises rokimuusikalis kohtuvad värskelt kihlunud Brad ja Janet teadlase Frank-N-Furteriga?",
        "The Rocky Horror Show",
        "„The Rocky Horror Show“",
        "The stage musical sends Brad and Janet into Frank-N-Furter's strange castle.",
        "Lavamuusikal viib Bradi ja Janeti Frank-N-Furteri kummalisse lossi.",
      ],
      [
        "Miss_Saigon",
        "Which musical relocates the story of Madame Butterfly to the final years of the Vietnam War?",
        "Milline muusikal paigutab „Madame Butterfly“ loo Vietnami sõja lõpuaastatesse?",
        "Miss Saigon",
        "„Miss Saigon“",
        "Miss Saigon centres on the relationship between Kim, a Vietnamese woman, and Chris, an American serviceman.",
        "„Miss Saigon“ keskendub vietnamlanna Kimi ja ameerika sõjaväelase Chrisi suhtele.",
      ],
    ],
  ],
  [
    116,
    "round-two",
    "literary-movements",
    "Story Styles and Genres",
    "Lugude laadid ja žanrid",
    [
      [
        "Biography",
        "What genre tells a real person's life story and is written by someone else?",
        "Milline žanr jutustab tegeliku inimese elust ja selle on kirjutanud keegi teine?",
        "a biography",
        "biograafia",
        "A biography is a nonfiction account of a person's life written by another author.",
        "Biograafia on kellegi elust rääkiv teos, mille on kirjutanud teine autor.",
      ],
      [
        "Detective_fiction",
        "Which genre makes the investigation and solution of a crime the centre of the story?",
        "Millises žanris on loo keskmes kuriteo uurimine ja lahendamine?",
        "detective fiction",
        "detektiivkirjandus",
        "Detective fiction follows clues and reasoning toward an explanation of a crime.",
        "Detektiivkirjandus liigub vihjete ja arutluse kaudu kuriteo seletuseni.",
        [],
        [],
      ],
      [
        "Gothic_fiction",
        "Which genre often combines old castles, dark secrets, fear and the supernatural?",
        "Milline žanr ühendab sageli vanad lossid, tumedad saladused, hirmu ja üleloomulikkuse?",
        "Gothic fiction",
        "gooti kirjandus",
        "Gothic fiction creates suspense through threatening settings, mystery and supernatural possibilities.",
        "Gooti kirjandus loob pinget ähvardavate paikade, saladuste ja üleloomulike võimalustega.",
        ["Gothic literature"],
        ["gooti romaan"],
      ],
      [
        "Melodrama",
        "Which dramatic genre uses heightened emotion, sensational conflict and clearly opposed heroes and villains?",
        "Milline draamažanr kasutab võimendatud tundeid, sensatsioonilisi konflikte ning selgelt vastandatud kangelasi ja kurikaelu?",
        "melodrama",
        "melodraama",
        "Melodrama emphasises strong emotion and sharply drawn moral conflict.",
        "Melodraama rõhutab tugevaid tundeid ja selgelt piiritletud moraalset konflikti.",
      ],
      [
        "Tragicomedy",
        "Which genre mixes serious or tragic events with comic elements?",
        "Milline žanr ühendab tõsised või traagilised sündmused koomiliste elementidega?",
        "tragicomedy",
        "tragikomöödia",
        "Tragicomedy blends features normally associated with tragedy and comedy.",
        "Tragikomöödia ühendab tavaliselt tragöödia ja komöödiaga seostatud jooni.",
      ],
    ],
  ],
  [
    117,
    "round-two",
    "fictional-characters",
    "Characters Everyone Can Picture",
    "Tegelased, keda kõik ette kujutavad",
    [
      [
        "Bambi_(character)",
        "Which young deer grows up in the forest in a novel by Felix Salten?",
        "Milline noor hirvlane kasvab Felix Salteni romaanis metsas suureks?",
        "Bambi",
        "Bambi",
        "Bambi learns about the forest and its dangers as he grows up.",
        "Bambi õpib suureks kasvades tundma metsa ja selle ohte.",
      ],
      [
        "Gandalf",
        "Which grey-robed wizard guides Bilbo and later helps the Fellowship of the Ring?",
        "Milline halli rüüd kandev võlur juhatab Bilbot ja aitab hiljem Sõrmuse Vennaskonda?",
        "Gandalf",
        "Gandalf",
        "Gandalf is a wise wizard who opposes Sauron in Tolkien's Middle-earth stories.",
        "Gandalf on tark võlur, kes astub Tolkieni Keskmaa-lugudes Sauronile vastu.",
        ["Gandalf the Grey"],
        ["Gandalf Hall"],
      ],
      [
        "Gollum",
        "Which former ring-bearer calls the One Ring his precious?",
        "Milline endine sõrmusekandja nimetab Võimusõrmust oma kallikeseks?",
        "Gollum",
        "Gollum",
        "The Ring has prolonged and twisted Gollum's life, and he is obsessed with recovering it.",
        "Sõrmus on Gollumi elu pikendanud ja teda moonutanud ning ta tahab seda kinnismõtteliselt tagasi saada.",
        ["Sméagol", "Smeagol"],
        ["Sméagol", "Smeagol"],
      ],
      [
        "Huckleberry_Finn",
        "Which Mark Twain character travels down the Mississippi River on a raft with Jim?",
        "Milline Mark Twaini tegelane sõidab koos Jimiga parvel mööda Mississippi jõge?",
        "Huckleberry Finn",
        "Huckleberry Finn",
        "Huckleberry Finn narrates an escape and river journey through the American South.",
        "Huckleberry Finn jutustab põgenemisest ja jõeretkest läbi Ameerika lõunaosa.",
        ["Huck Finn"],
        ["Huck Finn"],
      ],
      [
        "Long_John_Silver",
        "Which one-legged pirate befriends young Jim Hawkins in Treasure Island?",
        "Milline ühe jalaga piraat sõbruneb „Aarete saares“ noore Jim Hawkinsiga?",
        "Long John Silver",
        "Long John Silver",
        "Long John Silver is a charismatic ship's cook who secretly leads the pirates.",
        "Long John Silver on karismaatiline laevakokk, kes juhib salaja piraate.",
        ["Long John"],
        ["Long John"],
      ],
    ],
  ],
  [
    118,
    "round-two",
    "linguistics",
    "Everyday Word Wisdom",
    "Igapäevane sõnatarkus",
    [
      [
        "Proverb",
        "What kind of short traditional saying expresses advice or a general truth?",
        "Kuidas nimetatakse lühikest rahvapärast ütlust, mis väljendab õpetust või üldist elutõde?",
        "a proverb",
        "vanasõna",
        "A proverb passes down a compact observation or piece of practical wisdom.",
        "Vanasõna annab lühidalt edasi tähelepaneku või praktilise elutarkuse.",
      ],
      [
        "Opposite",
        "What do we call a word with the opposite meaning of another word, such as hot and cold?",
        "Kuidas nimetatakse sõna, mille tähendus on teise sõna vastand, näiteks „kuum“ ja „külm“?",
        "an antonym",
        "antonüüm",
        "Antonyms are words whose meanings contrast with one another.",
        "Antonüümid on vastandtähendusega sõnad.",
      ],
      [
        "Clich%C3%A9",
        "What do we call an expression or idea that has been used so often that it feels unoriginal?",
        "Kuidas nimetatakse väljendit või ideed, mida on kasutatud nii sageli, et see mõjub kulunult?",
        "a cliché",
        "klišee",
        "A cliché has lost much of its freshness through overuse.",
        "Klišee on liigse kasutamise tõttu kaotanud suure osa oma värskusest.",
      ],
      [
        "Homonym",
        "What do we call a word that shares its spelling or sound with another word but has a different meaning?",
        "Kuidas nimetatakse sõna, mille kirjapilt või kõla kattub teise sõnaga, kuid tähendus erineb?",
        "a homonym",
        "homonüüm",
        "Homonyms have the same form or sound but different meanings.",
        "Homonüümidel on sama kuju või kõla, kuid erinev tähendus.",
      ],
      [
        "Euphemism",
        "What term means a mild expression used instead of one considered harsh or embarrassing?",
        "Kuidas nimetatakse pehmemat väljendit, mida kasutatakse karmi või piinliku väljendi asemel?",
        "a euphemism",
        "eufemism",
        "A euphemism replaces direct wording with something considered less offensive or uncomfortable.",
        "Eufemism asendab otsese sõnastuse vähem solvava või ebamugava väljendiga.",
      ],
    ],
  ],
  [
    119,
    "round-two",
    "etymology",
    "Loanwords on the Move",
    "Rändavad laensõnad",
    [
      [
        "Kiosk",
        "Which word for a small open-fronted booth reached English through Turkish?",
        "Milline väikest avatud esiküljega müügipaviljoni tähistav sõna jõudis inglise keelde türgi keele kaudu?",
        "a kiosk",
        "kiosk",
        "Kiosk passed through Turkish and European languages before taking on its modern retail meaning.",
        "„Kiosk“ liikus türgi ja Euroopa keelte kaudu, enne kui sai tänapäevase müügipaviljoni tähenduse.",
      ],
      [
        "Pajamas",
        "Which word for loose sleeping clothes entered English through Hindustani?",
        "Milline avarat magamisriietust tähistav sõna pärineb hindustani keelest?",
        "pyjamas",
        "pidžaama",
        "The word entered English through Hindustani, from an Urdu term for leg clothing.",
        "Sõna jõudis inglise keelde hindustani keele kaudu urdu jalariietust tähistavast sõnast.",
        ["pajamas"],
        ["pidžaamad"],
      ],
      [
        "Khaki",
        "Which light tan or yellowish colour gets its name from a Hindustani word meaning soil-coloured?",
        "Milline hele kollakaspruun värv sai nime hindustani sõnast, mis tähendab mullavärvi?",
        "khaki",
        "khaki",
        "The word khaki came from Hindustani and was applied to soil-coloured military cloth.",
        "Sõna „khaki“ tuli hindustani keelest ja seda kasutati mullavärvi sõjaväekanga kohta.",
      ],
      [
        "Hammock",
        "Which hanging bed takes its English name from a Taíno word from the Caribbean?",
        "Milline rippuv magamisase sai ingliskeelse nime Kariibi piirkonna taíno keelest?",
        "a hammock",
        "võrkkiik",
        "Spanish adopted the Taíno word hamaca, which then entered English as hammock.",
        "Hispaania keel võttis taíno keelest üle sõna hamaca, millest kujunes inglise hammock.",
      ],
      [
        "Kayak",
        "Which narrow paddled boat has a name derived from the Inuktitut word qajaq?",
        "Millise kitsa aerupaadi nimi pärineb inuktituti sõnast qajaq?",
        "a kayak",
        "kajak",
        "The English word kayak comes from Inuktitut qajaq, the name of the traditional boat.",
        "Ingliskeelne sõna kayak pärineb inuktituti sõnast qajaq, mis tähistab traditsioonilist paati.",
      ],
    ],
  ],
  [
    120,
    "round-two",
    "writing-systems",
    "Letters by Hand and Screen",
    "Tähed käsitsi ja ekraanil",
    [
      [
        "Arabic_numerals",
        "Which familiar numeral system uses the ten digits from 0 to 9?",
        "Milline tuttav numbrisüsteem kasutab kümmet numbrit 0 kuni 9?",
        "Arabic numerals",
        "araabia numbrid",
        "Arabic numerals are the ten digit symbols used for everyday decimal notation.",
        "Araabia numbrid on kümme numbrimärki, mida kasutatakse igapäevases kümnendsüsteemis.",
      ],
      [
        "Comic_Sans",
        "Which informal rounded typeface was inspired by comic-book lettering and became famous on computer screens?",
        "Milline vaba ja ümar kirjastiil sai eeskuju koomiksite tekstist ning muutus arvutiekraanidel kuulsaks?",
        "Comic Sans",
        "Comic Sans",
        "Comic Sans was designed for friendly speech-bubble text and later spread widely through computer software.",
        "Comic Sans loodi sõbraliku jutumulliteksti jaoks ja levis hiljem laialt arvutitarkvaras.",
      ],
      [
        "Monogram",
        "What design combines two or more letters, often a person's initials, into one symbol?",
        "Milline kujund ühendab kaks või enam tähte, sageli inimese initsiaalid, üheks märgiks?",
        "a monogram",
        "monogramm",
        "A monogram arranges initials or other letters into a single identifying design.",
        "Monogramm seob initsiaalid või muud tähed üheks isikut tähistavaks kujundiks.",
      ],
      [
        "Cursive",
        "What style of handwriting joins many letters together in a flowing movement?",
        "Milline käekirjastiil ühendab paljud tähed sujuva liigutusega?",
        "cursive",
        "siduskiri",
        "Cursive handwriting connects letters so the pen can move smoothly across the page.",
        "Siduskirjas ühendatakse tähti, et kirjutusvahend saaks lehel sujuvalt liikuda.",
      ],
      [
        "Blackletter",
        "What dense, angular style of script is strongly associated with medieval European manuscripts?",
        "Milline tihe ja nurgeline kirjastiil seostub tugevalt keskaegsete Euroopa käsikirjadega?",
        "blackletter",
        "gooti kiri",
        "Blackletter uses tightly packed angular strokes and was widespread in medieval Europe.",
        "Gooti kiri kasutab tihedaid nurgelisi jooni ja oli keskaegses Euroopas laialt levinud.",
        ["Gothic script"],
        ["blackletter"],
      ],
    ],
  ],
];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLocaleLowerCase("en")
    .replace(/%[0-9a-f]{2}/giu, "-")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    page,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const subjectKey = `literature-language:${slug(page)}`;
  return {
    clueId: `built-in-literature-language-easy-expansion-${clueNumber}`,
    key: `literature-language-easy-expansion:${categorySetId}:${tier}`,
    factKey: `literature-language-easy-expansion:${slug(page)}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(page).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${page}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    },
  };
}

export const LITERATURE_LANGUAGE_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  LITERATURE_LANGUAGE_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
