import type { EasyExpansionCategory, EasyExpansionQuestion } from "../types";

const BATCH_ID = "05-art-architecture";
const PACK_ID = "built-in-art-architecture";
const RETRIEVED_AT = "2026-09-06";

type QuestionSeed = readonly [
  page: string,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const ART_ARCHITECTURE_EASY_EXPANSION_SEEDS: readonly CategorySeed[] = [
  [
    101,
    "round-one",
    "painting",
    "Five Ways Paint Gets Applied",
    "Viis viisi värvi pealekandmiseks",
    [
      [
        "Paint_roller",
        "A decorator needs to cover a broad, flat wall quickly and evenly. Name the tool with a rotating cylindrical cover.",
        "Maalril on vaja katta lai tasane sein kiiresti ja ühtlaselt. Nimeta pöörleva silindrilise kattega tööriist.",
        "a paint roller",
        "värvirull",
        "A paint roller spreads an even coat over a broad, flat area with its rotating cover.",
        "Värvirull kannab pöörleva katte abil laiale tasasele pinnale ühtlase värvikihi.",
      ],
      [
        "Fingerpaint",
        "No brush is needed here: paint goes straight from the fingers onto the paper. Name this painting style.",
        "Siin pole pintslit vaja: värv kantakse sõrmedega otse paberile. Nimeta see maalimisviis.",
        "finger painting",
        "sõrmedega maalimine",
        "Finger painting uses the fingers and hands to apply paint directly to a surface.",
        "Sõrmedega maalimisel kantakse värv pinnale otse sõrmede ja kätega.",
        ["fingerpainting"],
        ["sõrmevärvidega maalimine"],
      ],
      [
        "Spray_painting",
        "A pressurised tool or aerosol turns paint into airborne droplets before they land on a surface. Name the method.",
        "Survestatud tööriist või aerosoolpurk pihustab värvi õhku piiskadena, mis langevad pinnale. Nimeta see värvimisviis.",
        "spray painting",
        "pihustusvärvimine",
        "Spray painting applies paint as airborne droplets, usually from a pressurised tool or container.",
        "Pihustusvärvimisel kantakse värv pinnale õhus lenduvate piiskadena, tavaliselt survestatud tööriista või anuma abil.",
        ["spray-painting"],
        ["spreivärvimine"],
      ],
      [
        "Paint_by_number",
        "In what hobby painting system does each numbered area tell you which colour to use?",
        "Millises harrastusmaalimise süsteemis näitab iga ala number, millist värvi kasutada?",
        "paint by numbers",
        "numbrite järgi maalimine",
        "A paint-by-number picture divides an image into numbered shapes matched to numbered colours.",
        "Numbrite järgi maalitav pilt jagatakse nummerdatud aladeks, millele vastavad nummerdatud värvid.",
        ["paint by number", "paint-by-number"],
        ["numbrimaal", "numbrimaalimine"],
      ],
      [
        "Drip_painting",
        "Paint drips and pours across a canvas in this technique famously associated with Jackson Pollock. Name it.",
        "Selles Jackson Pollockiga kuulsalt seostatud tehnikas tilgub ja voolab värv lõuendile. Nimeta tehnika.",
        "drip painting",
        "tilgamaal",
        "Drip painting creates an image by dripping or pouring paint onto a surface, often laid flat.",
        "Tilgamaalis luuakse pilt värvi pinnale tilgutades või valades ning pind asetatakse sageli rõhtsalt.",
        ["drip technique", "paint dripping"],
        ["tilgutamistehnika", "värvi tilgutamine"],
      ],
    ],
  ],
  [
    102,
    "round-one",
    "painting",
    "Colours Beyond the Rainbow",
    "Värvid väljaspool vikerkaart",
    [
      [
        "Fuchsia_(color)",
        "Its flower, and then this vivid pinkish-red colour, ultimately took a name honouring botanist Leonhart Fuchs. Name the colour.",
        "Lill ja hiljem see erk roosakaspunane värv said nime botaanik Leonhart Fuchsi auks. Nimeta värv.",
        "fuchsia",
        "fuksiaroosa",
        "Fuchsia is a vivid pinkish-red colour named after the fuchsia flower, whose plant name honours Leonhart Fuchs.",
        "Fuksiaroosa on erk roosakaspunane värv, mis sai nime fuksiaõielt; taim ise nimetati Leonhart Fuchsi auks.",
        ["fuchsia pink"],
        ["fuksia"],
      ],
      [
        "Indigo_dye",
        "The classic blue of denim comes from a deep-blue dye once extracted from plants including Indigofera. Name it.",
        "Teksariide klassikaline sinine toon tuleb sügavsinisest värvainest, mida saadi kunagi muu hulgas indigopõõsa perekonna liikidest. Nimeta see.",
        "indigo",
        "indigo",
        "Indigo is a deep-blue dye historically extracted from plants, especially species of Indigofera.",
        "Indigo on sügavsinine värvaine, mida saadi ajalooliselt taimedest, eriti indigopõõsa liikidest.",
        ["indigo dye"],
        ["indigovärv"],
      ],
      [
        "Scarlet_(color)",
        "Complete the childhood illness name: ___ fever. The missing word is this bright red, sometimes slightly orange colour.",
        "Laste nakkushaiguse ingliskeelne nimi on ___ fever. Puuduv sõna tähistab erkpunast, vahel veidi oranžikat värvi. Nimeta värv.",
        "scarlet",
        "sarlakpunane",
        "Scarlet is a bright red, sometimes slightly orange colour, and the colour word appears in the illness name scarlet fever.",
        "Sarlakpunane on erk, mõnikord kergelt oranžikas punane ning sama värvisõna esineb haiguse ingliskeelses nimetuses scarlet fever.",
        ["scarlet red"],
        ["scarlet"],
      ],
      [
        "Umber",
        "An art shop sells one umber pigment in its natural, unheated form and another darker one after heating. Name the unheated colour.",
        "Kunstipood müüb üht umbripigmenti loodusliku ja kuumutamata kujul ning teist pärast kuumutamist tumedamana. Nimeta kuumutamata värv.",
        "raw umber",
        "toorumber",
        "Raw umber is the natural, unheated form of umber; heating it produces darker burnt umber.",
        "Toorumber on umbripigmendi looduslik kuumutamata vorm; kuumutamisel saadakse tumedam põletatud umber.",
        ["natural umber"],
        ["naturaalne umber"],
      ],
      [
        "Sienna",
        "Raw sienna is heated and turns warmer and reddish-brown. Name the resulting pigment.",
        "Toorest siennat kuumutatakse ning see muutub soojemaks ja punakaspruuniks. Nimeta saadud pigment.",
        "burnt sienna",
        "põletatud sienna",
        "Burnt sienna is the richer reddish-brown form produced by heating raw sienna earth pigment.",
        "Põletatud sienna on rikkalikum punakaspruun pigment, mis saadakse toore sienna kuumutamisel.",
        ["burned sienna"],
        ["põletatud sienna pigment"],
      ],
    ],
  ],
  [
    103,
    "round-one",
    "sculpture",
    "How a Sculpture Takes Shape",
    "Kuidas skulptuur kuju saab",
    [
      [
        "Stone_sculpture",
        "A sculptor chips and scrapes material away from a stone block until a figure emerges. Name this process.",
        "Skulptor raiub ja kraabib kiviplokist materjali, kuni kuju esile tuleb. Nimeta see protsess.",
        "stone carving",
        "kiviraidumine",
        "Stone carving creates a sculpture by cutting and scraping material away from a block of stone.",
        "Kiviraidumisel luuakse skulptuur kiviplokist materjali lõigates ja kraapides.",
        ["stone sculpture carving"],
        ["kivinikerdamine"],
      ],
      [
        "Woodturning",
        "A block of wood spins on a lathe while a craftsperson cuts it into a bowl or another symmetrical sculptural form. Name the craft.",
        "Puidutoorik pöörleb treipingil, samal ajal kui käsitööline lõikab sellest kausi või muu sümmeetrilise skulptuurse vormi. Nimeta see käsitöö.",
        "woodturning",
        "puidutreimine",
        "Woodturning uses a lathe and hand-held tools to cut wood into forms symmetrical around the axis of rotation.",
        "Puidutreimisel vormitakse treipingi ja käes hoitavate tööriistade abil puit pöörlemistelje suhtes sümmeetriliseks.",
        ["wood turning"],
        ["puutreimine"],
      ],
      [
        "Topiary",
        "Garden shears turn shrubs into animals or crisp geometric forms in this kind of living sculpture. Name the practice.",
        "Aiakääridega pügatakse põõsad loomade või selgepiiriliste geomeetriliste kujundite sarnaseks, luues elava skulptuuri. Nimeta see aianduskunst.",
        "topiary",
        "topiaarkunst",
        "Topiary trains perennial plants into defined geometric or fanciful shapes by clipping their foliage and twigs.",
        "Topiaarkunstis kujundatakse püsitaimed kindlateks geomeetrilisteks või fantaasiaküllasteks vormideks, kärpides nende lehti ja oksi.",
        ["topiary art"],
        ["vormpügamine"],
      ],
      [
        "Armature_(sculpture)",
        "Before adding clay or wax, a sculptor builds an internal framework to support the soft material. Name that framework.",
        "Enne savi või vaha lisamist ehitab skulptor pehme materjali toetamiseks sisemise raamistiku. Nimeta see raamistik.",
        "an armature",
        "armatuur",
        "A sculptor builds clay, wax, or another soft material around an armature for support and stability.",
        "Skulptor ehitab savi, vaha või muu pehme materjali armatuuri ümber, mis annab teosele toe ja stabiilsuse.",
        ["a sculpture armature"],
        ["skulptuuriarmatuur"],
      ],
      [
        "Lost-wax_casting",
        "A wax model melts out of the mould and molten metal takes its place. Name this casting method.",
        "Vahamudel sulatatakse vormist välja ja selle asemele valatakse sulametall. Nimeta see valumeetod.",
        "lost-wax casting",
        "vahavalu",
        "Lost-wax casting replaces a wax model with molten metal inside a heat-resistant mould.",
        "Vahavalu puhul asendatakse kuumakindlas vormis olnud vahamudel sulametalliga.",
        ["lost wax casting", "the lost-wax process"],
        ["kaduva vaha meetod", "kaduva vahaga valamine"],
      ],
    ],
  ],
  [
    104,
    "round-one",
    "sculpture",
    "People in Three Dimensions",
    "Inimesed kolmemõõtmelisena",
    [
      [
        "Garden_gnome",
        "A tiny bearded man in a pointed hat has appeared on the lawn. Name this familiar garden ornament.",
        "Murule on ilmunud terava mütsiga väike habemega mees. Nimeta see tuttav aiakaunistus.",
        "a garden gnome",
        "aiapäkapikk",
        "A garden gnome is a small humanoid lawn ornament commonly shown with a beard and pointed hat.",
        "Aiapäkapikk on väike inimesekujuline murukaunistus, mida kujutatakse tavaliselt habeme ja terava mütsiga.",
        ["a lawn gnome"],
        ["murupäkapikk"],
      ],
      [
        "Mannequin",
        "A shop window needs a human-shaped model to display its clothes. Name it.",
        "Poe vaateaknal on rõivaste esitlemiseks vaja inimesekujulist mudelit. Nimeta see.",
        "a mannequin",
        "mannekeen",
        "Shops use mannequins as human-shaped models for displaying clothing.",
        "Poed kasutavad mannekeene inimesekujuliste mudelitena rõivaste esitlemiseks.",
        ["a shop dummy", "a display mannequin"],
        ["poemanekeen", "vaateaknamannekeen"],
      ],
      [
        "Lego_minifigure",
        "Lego building sets use this small articulated plastic person as their familiar character. Name the figure.",
        "LEGO ehituskomplektides tegutseb see väike liigenditega plastist tegelane. Nimeta figuur.",
        "a Lego minifigure",
        "LEGO minifiguur",
        "A Lego minifigure is a small articulated plastic figurine designed for Lego construction sets.",
        "LEGO minifiguur on LEGO ehituskomplektide jaoks loodud väike liigenditega plastfiguur.",
        ["a minifigure", "a Lego figure", "a Lego man"],
        ["minifiguur", "LEGO figuur", "legomehike"],
      ],
      [
        "Wax_sculpture",
        "At Madame Tussauds, lifelike celebrities are modelled in wax. Name this kind of museum figure.",
        "Madame Tussaudsi muuseumis voolitakse vahast elutruid kuulsusi. Nimeta selline muuseumikuju.",
        "a wax figure",
        "vahakuju",
        "A wax figure is a lifelike wax sculpture of a person, often displayed in a wax museum.",
        "Vahakuju on inimese elutruu vahast skulptuur, mida eksponeeritakse sageli vahakujude muuseumis.",
        ["a waxwork", "a wax sculpture"],
        ["vahast kuju", "vahaskulptuur"],
      ],
      [
        "Action_figure",
        "In 1964, Hasbro wanted to market G.I. Joe to boys without calling it a doll, so it coined this toy term. Name it.",
        "1964. aastal tahtis Hasbro G.I. Joed poistele turustada ilma seda nukuks nimetamata ning lõi selle mänguasjatermini. Nimeta termin.",
        "an action figure",
        "märulifiguur",
        "Hasbro coined the term action figure in 1964 to market its poseable G.I. Joe character to boys while competitors called similar toys dolls.",
        "Hasbro lõi 1964. aastal mõiste action figure, et turustada liigutatavat G.I. Joe tegelast poistele, samal ajal kui konkurendid nimetasid sarnaseid mänguasju nukkudeks.",
        ["a poseable action figure", "an articulated action figure"],
        ["action figure", "liigendfiguur"],
      ],
    ],
  ],
  [
    105,
    "round-one",
    "sculpture",
    "Art That May Not Last",
    "Kunst, mis ei pruugi püsida",
    [
      [
        "Sand_art_and_play",
        "Damp beach sand becomes towers and other carved forms in this temporary artwork. Name it.",
        "Niiskest rannaliivast saavad selles ajutises kunstiteoses tornid ja muud raiutud vormid. Nimeta see.",
        "a sand sculpture",
        "liivaskulptuur",
        "Sand sculpture uses compacted sand and water to build forms that may be carved in detail.",
        "Liivaskulptuuris ehitatakse tihendatud liivast ja veest vorme, millesse võib nikerdada peeneid detaile.",
        ["sand art"],
        ["liivakunst"],
      ],
      [
        "Snow_sculpture",
        "At winter festivals, what kind of sculpture is carved from packed snow?",
        "Millist skulptuuri raiutakse talvefestivalidel kokkupakitud lumest?",
        "a snow sculpture",
        "lumeskulptuur",
        "Snow sculptures are shaped from compacted snow and are common features of winter festivals.",
        "Lumeskulptuure vormitakse tihendatud lumest ning neid kohtab sageli talvefestivalidel.",
        ["snow art"],
        ["lumekuju"],
      ],
      [
        "Ice_sculpture",
        "Hand tools and power tools turn a frozen block into a carved artwork. Name it.",
        "Käsi- ja elektritööriistad muudavad külmunud ploki raiutud kunstiteoseks. Nimeta see.",
        "an ice sculpture",
        "jääskulptuur",
        "Ice sculptors carve blocks of ice with hand tools, power tools, or chainsaws.",
        "Jääskulptorid raiuvad jääplokke käsitööriistade, elektritööriistade või mootorsaagidega.",
        ["ice art"],
        ["jääkuju"],
      ],
      [
        "Balloon_modelling",
        "Long inflatable balloons become dogs, hats, and other shapes after a few careful twists. Name the craft.",
        "Pikkadest õhupallidest saavad mõne hoolika keeruga koerad, kübarad ja muud kujundid. Nimeta see käsitöö.",
        "balloon modelling",
        "õhupallifiguuride tegemine",
        "Balloon modelling shapes special balloons by twisting them into figures and decorations.",
        "Õhupallifiguuride tegemisel keeratakse erilised õhupallid kujukesteks ja kaunistusteks.",
        ["balloon modeling", "balloon twisting"],
        ["õhupallimodelleerimine", "õhupallide keerutamine"],
      ],
      [
        "Butter_sculpture",
        "At some fairs, artists carve what kind of three-dimensional artwork from a chilled dairy product?",
        "Millist kolmemõõtmelist kunstiteost raiuvad kunstnikud mõnel laadal jahutatud piimatootest?",
        "a butter sculpture",
        "võiskulptuur",
        "A butter sculpture is a three-dimensional artwork made from chilled butter.",
        "Võiskulptuur on jahutatud võist valmistatud kolmemõõtmeline kunstiteos.",
        ["butter art"],
        ["võikuju"],
      ],
    ],
  ],
  [
    106,
    "round-one",
    "photography-history",
    "Photography Before Digital Files",
    "Fotograafia enne digifaile",
    [
      [
        "Photo_album",
        "Printed family photographs slide into plastic sleeves or attach to heavy pages in this book. Name it.",
        "Prinditud perefotod pistetakse selle raamatu plasttaskutesse või kinnitatakse paksudele lehtedele. Nimeta see.",
        "a photo album",
        "fotoalbum",
        "A photo album collects photographic prints in book form, often in sleeves or on heavy paper pages.",
        "Fotoalbum koondab fotoprindid raamatuks, sageli taskutesse või paksudele paberlehtedele.",
        ["a photograph album"],
        ["pildialbum"],
      ],
      [
        "Contact_print",
        "A photographer lays a whole strip of negatives directly against photographic paper, producing same-size images for choosing the best frames. Name the result.",
        "Fotograaf asetab terve negatiiviriba otse fotopaberi vastu, et saada parimate kaadrite valimiseks originaaliga sama suured kujutised. Nimeta tulemus.",
        "a contact print",
        "kontaktkoopia",
        "A contact print is made with film held directly against photographic paper; a whole strip can form a contact sheet for selecting images.",
        "Kontaktkoopia valmistamisel asetatakse film otse fotopaberi vastu; terve riba võib moodustada kaadrite valimiseks kontaktlehe.",
        ["a contact sheet"],
        ["kontaktleht"],
      ],
      [
        "Enlarger",
        "In a traditional darkroom, light passes through a negative in this projector to make a photographic print. Name the device.",
        "Traditsioonilises pimikus läbib valgus selles projektoris negatiivi, et valmistada fotoprint. Nimeta seade.",
        "a photographic enlarger",
        "fotosuurendi",
        "A photographic enlarger is a specialised projector used to produce prints from negatives or transparencies.",
        "Fotosuurendi on eriprojektor, millega valmistatakse negatiividest või diapositiividest fotoprinte.",
        ["an enlarger"],
        ["suurendi"],
      ],
      [
        "Camera_obscura",
        "Light enters a dark box or room through one small opening and projects the outside scene upside down. Name this optical device.",
        "Valgus siseneb pimedasse kasti või ruumi ühe väikese ava kaudu ja projitseerib välisvaate tagurpidi. Nimeta see optiline seade.",
        "a camera obscura",
        "camera obscura",
        "A camera obscura forms an inverted projection when light enters a dark enclosure through a small opening.",
        "Camera obscura loob ümberpööratud projektsiooni, kui valgus pääseb pimedasse ruumi väikese ava kaudu.",
        ["camera obscura"],
        ["pimekamber"],
      ],
      [
        "Tintype",
        "A dark-lacquered iron sheet carries the direct positive image in this early photographic process. Name the resulting photograph.",
        "Selles varajases fotoprotsessis kannab otsepositiivkujutist tumeda lakiga kaetud raudplaat. Nimeta saadud foto.",
        "a tintype",
        "ferrotüüp",
        "A tintype is a direct positive photograph made on a thin sheet of iron coated with dark lacquer or enamel.",
        "Ferrotüüp on otsepositiivfoto, mis tehakse tumeda laki või emailiga kaetud õhukesele raudplaadile.",
        ["a ferrotype"],
        ["ferrotüüpfoto"],
      ],
    ],
  ],
  [
    107,
    "round-one",
    "photography-history",
    "Photo Gadgets Before the Smartphone",
    "Fotovidinad enne nutitelefoni",
    [
      [
        "Photo_booth",
        "Insert a coin, pose several times, and a strip of portraits drops out. Name the machine.",
        "Sisesta münt, poseeri mitu korda ja masin väljastab portreeriba. Nimeta see masin.",
        "a photo booth",
        "fotokabiin",
        "A photo booth contains an automated camera and processor that produces portraits, often in a strip.",
        "Fotokabiinis on automaatne kaamera ja fototöötleja, mis väljastab portreed sageli ribana.",
        ["a photographic booth"],
        ["fotoautomaat"],
      ],
      [
        "Disposable_camera",
        "It arrives preloaded with film, and the whole camera goes for processing after the last shot. Name this single-use gadget.",
        "See müüakse filmiga laetuna ning pärast viimast võtet viiakse kogu aparaat ilmutusse. Nimeta see üheks kasutuskorraks mõeldud fotoseade.",
        "a disposable camera",
        "ühekordne kaamera",
        "A disposable camera is sold with film inside and is usually handed in whole for processing.",
        "Ühekordne kaamera müüakse sisseehitatud filmiga ning antakse tavaliselt tervikuna ilmutusse.",
        ["a single-use camera"],
        ["ühekorrakaamera"],
      ],
      [
        "Instant_camera",
        "Press the shutter and a physical photograph appears from the camera moments later. Name this camera type.",
        "Vajuta päästikule ja mõne hetke pärast väljub kaamerast füüsiline foto. Nimeta see kaameratüüp.",
        "an instant camera",
        "kiirpildikaamera",
        "An instant camera uses self-developing film to produce a physical photograph soon after exposure.",
        "Kiirpildikaamera kasutab kiirfilmi, et anda füüsiline foto kätte varsti pärast säritust.",
        ["an instant film camera", "a Polaroid camera"],
        ["kiirkaamera", "Polaroid-kaamera"],
      ],
      [
        "Slide_projector",
        "At a slideshow, light passes through tiny transparencies and enlarges them on the wall. Name the device.",
        "Slaidiseansil läbib valgus väikseid diapositiive ja projitseerib kujutised suurendatult seinale. Nimeta seade.",
        "a slide projector",
        "diaprojektor",
        "A slide projector shines light through a photographic slide and projects an enlarged image onto a screen.",
        "Diaprojektor suunab valguse läbi fotodiapositiivi ja kuvab suurendatud kujutise ekraanile.",
        ["a photographic slide projector"],
        ["slaidiprojektor"],
      ],
      [
        "Stereoscope",
        "Two slightly different photographs merge into one three-dimensional scene through this binocular-like viewer. Name it.",
        "Kaks veidi erinevat fotot ühinevad selle binoklit meenutava vaateseadme kaudu üheks ruumiliseks vaateks. Nimeta see.",
        "a stereoscope",
        "stereoskoop",
        "A stereoscope presents a slightly different photograph to each eye, creating an impression of depth.",
        "Stereoskoop näitab kummalegi silmale veidi erinevat fotot ja tekitab nii ruumilisuse mulje.",
        ["a stereo viewer"],
        ["stereovaataja"],
      ],
    ],
  ],
  [
    108,
    "round-one",
    "museums",
    "Words for a Museum Visit",
    "Sõnad muuseumikülastuseks",
    [
      [
        "Diorama",
        "Behind museum glass, model animals stand before a painted landscape to recreate a three-dimensional habitat. Name this display.",
        "Muuseumiklaasi taga seisavad loomamudelid maalitud maastiku ees ja loovad kolmemõõtmelise elupaiga. Nimeta selline väljapanek.",
        "a diorama",
        "dioraam",
        "A diorama is a three-dimensional replica of a scene; museum habitat dioramas often combine models with a painted background.",
        "Dioraam on stseeni kolmemõõtmeline jäljend; muuseumide elupaigadioraamid ühendavad sageli mudelid maalitud taustaga.",
        ["a museum diorama"],
        ["muuseumidioraam"],
      ],
      [
        "Travelling_exhibition",
        "The display is packed into crates, moved on, and installed at another venue. Name this kind of exhibition.",
        "Väljapanek pakitakse kastidesse, viiakse edasi ja paigaldatakse järgmises näitusepaigas. Nimeta selline näitus.",
        "a travelling exhibition",
        "rändnäitus",
        "A travelling exhibition is designed to be presented at several venues instead of staying in one place.",
        "Rändnäitus on loodud esitamiseks mitmes paigas, mitte ainult ühes kohas.",
        ["a traveling exhibition", "a touring exhibition"],
        ["ringnäitus", "rändekspositsioon"],
      ],
      [
        "Audio_tour",
        "Recorded commentary guides a visitor from one museum object to the next. Name this listening aid.",
        "Salvestatud selgitus juhatab külastaja ühe muuseumieseme juurest teiseni. Nimeta see kuulatav abivahend.",
        "an audio guide",
        "audiogiid",
        "An audio guide provides recorded spoken commentary for visitors to a museum or other attraction.",
        "Audiogiid pakub muuseumi või muu vaatamisväärsuse külastajale salvestatud suulisi selgitusi.",
        ["an audio tour"],
        ["audiotuur"],
      ],
      [
        "Exhibition_catalogue",
        "The works in a museum exhibition are listed and discussed in this accompanying book. Name it.",
        "Muuseuminäituse teosed on loetletud ja tutvustatud selles näitusega kaasnevas raamatus. Nimeta see.",
        "an exhibition catalogue",
        "näitusekataloog",
        "An exhibition catalogue records the works presented in an art exhibition and often adds descriptions or essays.",
        "Näitusekataloog talletab kunstinäitusel esitatud teosed ning lisab neile sageli kirjeldusi või esseid.",
        ["an exhibition catalog", "a museum exhibition catalogue"],
        ["muuseumi näitusekataloog", "muuseuminäituse kataloog"],
      ],
      [
        "Collection_(museum)",
        "A museum may borrow works for temporary shows, but the assets it owns belong to this collection. Name it.",
        "Muuseum võib ajutisteks näitusteks teoseid laenata, kuid tema enda varad kuuluvad sellesse kogusse. Nimeta see.",
        "a permanent collection",
        "püsikogu",
        "A museum's permanent collection consists of assets it owns, whether or not they are currently on display.",
        "Muuseumi püsikogu koosneb talle kuuluvatest varadest olenemata sellest, kas need on parajasti välja pandud.",
      ],
    ],
  ],
  [
    109,
    "round-one",
    "architecture",
    "Building Parts in Plain Sight",
    "Hoone osad meie silme ees",
    [
      [
        "Thatching",
        "Layers of straw or reeds keep a cottage dry under this traditional roof type. Name it.",
        "Õlgede või roo kihid hoiavad suvila selle traditsioonilise katuse all kuivana. Nimeta katusetüüp.",
        "a thatched roof",
        "õlg- või rookatus",
        "A thatched roof is built from layered dry vegetation, commonly straw, reeds, rushes, or similar plants.",
        "Õlg- või rookatus ehitatakse kihiti laotud kuivast taimsest materjalist, tavaliselt õlgedest, roost või kõrkjatest.",
        ["a straw roof", "a reed roof"],
        ["õlgkatus", "rookatus"],
      ],
      [
        "Stairs",
        "The staircase winds around a centre as it rises between floors. Name the form.",
        "Trepp keerdub korruste vahel tõustes ümber keskpunkti. Nimeta trepivorm.",
        "a spiral staircase",
        "keerdtrepp",
        "A spiral staircase winds around a central post or open space while gaining height.",
        "Keerdtrepp pöördub kõrgemale tõustes ümber keskposti või avatud südamiku.",
        ["spiral stairs"],
        ["spiraaltrepp"],
      ],
      [
        "Chimney",
        "An inexpensive extension raises a chimney's flue and can improve its draught. Name the piece on top.",
        "Odav pikendus tõstab korstna suitsulõõri kõrgemale ja võib parandada tõmmet. Nimeta see korstna otsas olev osa.",
        "a chimney pot",
        "korstnaotsik",
        "A chimney pot extends the flue above the chimney stack and can help improve the draught.",
        "Korstnaotsik pikendab suitsulõõri korstna kohal ja võib parandada tõmmet.",
      ],
      [
        "Balcony",
        "A railing crosses a tall window, but there is little or no platform to step onto. Name this balcony type.",
        "Kõrge akna ees on piire, kuid platvorm, millele astuda, on väga madal või puudub. Nimeta see rõdutüüp.",
        "a French balcony",
        "prantsuse rõdu",
        "A French or Juliet balcony is a balconet: a railing across a full-height opening with little or no projecting platform.",
        "Prantsuse ehk Julia rõdu on valerõdu, mille täiskõrguses ava ees on piire, kuid väljaulatuv platvorm on väga madal või puudub.",
        ["a Juliet balcony", "a balconet"],
        ["Julia rõdu", "valerõdu"],
      ],
      [
        "Curtain_wall_(architecture)",
        "A glass-and-metal skin hangs from the load-bearing frame without carrying the building. Name this outer-wall system.",
        "Klaasist ja metallist väliskiht kinnitatakse kandva karkassi külge ning see ei kanna hoonet. Nimeta see välisseinasüsteem.",
        "a curtain wall",
        "rippfassaad",
        "A curtain wall is a non-structural exterior wall attached to a building's load-bearing frame.",
        "Rippfassaad on mittekandev välissein, mis kinnitatakse hoone kandva karkassi külge.",
        ["a curtain-wall facade"],
        ["kardinfassaad"],
      ],
    ],
  ],
  [
    110,
    "round-one",
    "materials-techniques",
    "Paper Becomes Art",
    "Paberist saab kunst",
    [
      [
        "Paper_fortune_teller",
        "A folded paper toy opens and closes on your fingers to reveal hidden colours, numbers, and fortunes. Name it.",
        "Volditud paberist mänguasi avaneb ja sulgub sõrmedel ning paljastab peidetud värve, numbreid ja ennustusi. Nimeta see.",
        "a paper fortune teller",
        "paberist ennustaja",
        "A paper fortune teller is a folded paper toy operated with the fingers to reveal hidden messages.",
        "Paberist ennustaja on sõrmedega liigutatav volditud mänguasi, mis paljastab peidetud sõnumeid.",
        ["a cootie catcher", "a chatterbox"],
        ["paberennustaja", "soolatops"],
      ],
      [
        "Paper_plane",
        "Fold one sheet into a nose-heavy triangle, throw it, and this toy glides across the room. Name it.",
        "Voldi üks paberileht ninaosast raskeks kolmnurgaks, viska see õhku ja mänguasi liugleb üle toa. Nimeta see.",
        "a paper plane",
        "paberlennuk",
        "A paper plane is a toy aircraft, usually a glider, made from a single folded sheet of paper or paperboard.",
        "Paberlennuk on mängulennuk, tavaliselt liugur, mis valmistatakse ühest volditud paberi- või kartongilehest.",
        ["a paper airplane"],
        ["paberist lennuk"],
      ],
      [
        "Papier-m%C3%A2ch%C3%A9",
        "Paper pulp or pasted strips can be shaped into masks and models with this mouldable material. Name it.",
        "Peenestatud paberist või liimiga kaetud paberiribadest saab vormida maske ja mudeleid. Nimeta see materjal.",
        "papier-mâché",
        "pabermass",
        "Papier-mâché combines paper pieces or pulp with an adhesive so it can dry into a shaped object.",
        "Pabermassis ühendatakse paberitükid või -mass liimainega ning materjal kuivab vormitud esemeks.",
        ["paper mache", "paper-mâché", "papier-mâché material"],
        ["pabermašee", "papier-mâché", "papjeemašee"],
      ],
      [
        "Decoupage",
        "A plain box gains glued paper cut-outs and enough varnish to look painted. Name this decorative craft.",
        "Lihtne karp kaetakse liimitud paberist väljalõigete ja mitme lakikihiga, nii et see näeb välja maalitud. Nimeta see kaunistustehnika.",
        "decoupage",
        "dekupaaž",
        "Decoupage decorates an object with glued paper cut-outs and commonly finishes it with protective varnish.",
        "Dekupaažis kaunistatakse ese liimitud paberist väljalõigetega ja viimistletakse tavaliselt kaitsva lakiga.",
        ["découpage"],
        ["dekupaažitehnika"],
      ],
      [
        "Paper_marbling",
        "Colours swirl on a liquid bath before a sheet is laid on top and lifted away with a stone-like pattern. Name this decorative paper technique.",
        "Värvid keerlevad vedeliku pinnal, seejärel asetatakse peale paberileht, mis tõstetakse üles kivimit meenutava mustriga. Nimeta see paberi kaunistamise tehnika.",
        "paper marbling",
        "paberi marmoreerimine",
        "Paper marbling floats colours on water or another liquid surface and transfers the resulting stone-like pattern to paper.",
        "Paberi marmoreerimisel lastakse värvidel vee või muu vedeliku pinnal hõljuda ning tekkinud kivimuster kantakse paberile.",
        ["marbling"],
        ["marmoreerimine"],
      ],
    ],
  ],
  [
    111,
    "round-two",
    "museums",
    "Museums Beyond Paintings",
    "Muuseumid, kus pole ainult maale",
    [
      [
        "Children%27s_museum",
        "At this family attraction, “Please touch” can replace “Do not touch”: interactive exhibits are built around young visitors' learning. Name the institution.",
        "Selles perele mõeldud paigas võib sildi „Palun puuduta“ leida sildi „Mitte puutuda“ asemel: interaktiivsed väljapanekud toetavad noorte külastajate õppimist. Nimeta asutus.",
        "a children's museum",
        "lastemuuseum",
        "Children's museums design exhibitions and activities around children's learning and participation.",
        "Lastemuuseumid kujundavad näitused ja tegevused laste õppimist ning osalemist silmas pidades.",
      ],
      [
        "Natural_history_museum",
        "Fossils, animal specimens, plant collections and rocks share the galleries at this kind of institution. Name it.",
        "Selle asutuse väljapanekutel kohtab fossiile ning loomade, taimede ja kivimite näidiseid. Nimeta see.",
        "a natural history museum",
        "loodusmuuseum",
        "Natural history museums preserve collections covering living things, fossils, geology and other parts of nature.",
        "Loodusmuuseumid säilitavad eluslooduse, fossiilide, geoloogia ja teiste loodusvaldkondade kogusid.",
        ["a museum of natural history"],
        ["loodusajaloo muuseum"],
      ],
      [
        "Museum_ship",
        "Visitors step aboard a preserved former vessel instead of walking into galleries ashore. Name this floating attraction.",
        "Kaldal asuvate näitusesaalide asemel astuvad külastajad säilitatud endise aluse pardale. Nimeta see ujuv vaatamisväärsus.",
        "a museum ship",
        "muuseumilaev",
        "A museum ship is a preserved former vessel that has been converted into a museum open to the public.",
        "Muuseumilaev on säilitatud endine alus, mis on muudetud üldsusele avatud muuseumiks.",
      ],
      [
        "Virtual_museum",
        "No ticket desk or physical building is required: a digitally recorded collection can be explored online in this kind of institution. Name it.",
        "Piletikassat ega füüsilist hoonet pole vaja: selle asutuse digitaalselt talletatud kogu saab uurida veebis. Nimeta see.",
        "a virtual museum",
        "virtuaalmuuseum",
        "A virtual museum presents a digitally recorded collection through electronic media, commonly online.",
        "Virtuaalmuuseum esitleb digitaalselt talletatud kogu elektroonilise meedia kaudu, tavaliselt veebis.",
        ["an online museum", "a digital museum"],
        ["veebimuuseum", "digimuuseum"],
      ],
      [
        "Archaeology_museum",
        "The Ancient Agora of Athens and the Roman Forum are open-air examples of this museum type. Name it.",
        "Ateena antiikne agoraa ja Rooma foorum on selle muuseumitüübi vabaõhunäited. Nimeta muuseumitüüp.",
        "an archaeological museum",
        "arheoloogiamuuseum",
        "Archaeological museums specialise in archaeological artifacts; some, including the Ancient Agora and Roman Forum, are open-air.",
        "Arheoloogiamuuseumid keskenduvad arheoloogilistele esemetele; mõned neist, sealhulgas Ateena antiikne agoraa ja Rooma foorum, asuvad vabas õhus.",
        ["an archaeology museum"],
        ["arheoloogiline muuseum"],
      ],
    ],
  ],
  [
    112,
    "round-two",
    "architecture",
    "Inside a Building",
    "Hoone sees",
    [
      [
        "Handrail",
        "On a steep staircase, this rail is the part your palm reaches for. Name it.",
        "Järsul trepil sirutub peopesa toe saamiseks just selle piirdeosa poole. Nimeta see.",
        "a handrail",
        "käsipuu",
        "A handrail is designed to be grasped by the hand for support, especially on stairs.",
        "Käsipuu on mõeldud käega haaramiseks ja toetab inimest eelkõige trepil liikudes.",
      ],
      [
        "Revolving_door",
        "Step into one compartment, push, and the entrance turns around a central shaft while another visitor enters from the street. Name the door.",
        "Astu ühte sektsiooni ja lükka: sissepääs pöörleb ümber kesktelje, samal ajal kui järgmine külastaja tänavalt siseneb. Nimeta uks.",
        "a revolving door",
        "pöörduks",
        "A revolving door has several leaves attached to a central shaft and rotates within a round enclosure.",
        "Pöörduksel on kesktelje külge kinnitatud mitu ukselehte, mis pöörlevad ümaras korpuses.",
      ],
      [
        "Mezzanine",
        "Look up from a double-height lobby and you may see this partial intermediate floor overlooking you. Name it.",
        "Kahekorruselise kõrgusega fuajeest üles vaadates võib näha seda osalist lisatasandit. Nimeta see.",
        "a mezzanine",
        "vahekorrus",
        "A mezzanine is an intermediate floor that does not cover the entire space and may overlook the floor below.",
        "Vahekorrus on osaline korrus, mis ei kata kogu ruumi ja võib olla avatud allpool asuva ruumi poole.",
        ["a mezzanine floor"],
        ["poolkorrus"],
      ],
      [
        "Lightwell",
        "A room deep inside a large building still receives daylight and air through this open vertical space. Name the feature.",
        "Suure hoone sisemuses asuv ruum saab selle avatud püstise ruumi kaudu siiski päevavalgust ja õhku. Nimeta hooneosa.",
        "a lightwell",
        "valgusšaht",
        "A lightwell is an open vertical space designed to bring light and ventilation into interior rooms.",
        "Valgusšaht on avatud püstine ruum, mis toob siseruumidesse valgust ja õhku.",
        ["a light well"],
        ["valguskaev"],
      ],
      [
        "Dumbwaiter",
        "A restaurant sends plates between floors in this tiny goods-only lift. Name it.",
        "Restoran saadab taldrikuid korruste vahel selle väikese, ainult kaubale mõeldud liftiga. Nimeta see.",
        "a dumbwaiter",
        "toidulift",
        "A dumbwaiter is a small freight lift used to move objects rather than people between floors.",
        "Toidulift on väike kaubalift, millega liigutatakse korruste vahel esemeid, mitte inimesi.",
        ["a small service lift", "a food lift"],
        ["väikelift", "köögilift"],
      ],
    ],
  ],
  [
    113,
    "round-two",
    "architecture",
    "Homes with a Distinctive Form",
    "Eriilmelised kodud",
    [
      [
        "Igloo",
        "Blocks of suitable snow form this dome-shaped Arctic shelter traditionally used by some Inuit communities. Name it.",
        "Sobivast lumest plokid moodustavad selle kuplikujulise arktilise varjualuse, mida on traditsiooniliselt kasutanud mõned inuiti kogukonnad. Nimeta see.",
        "an igloo",
        "iglu",
        "An igloo is a shelter built from suitable snow and traditionally used in parts of the Arctic.",
        "Iglu on sobivast lumest ehitatud varjualune, mida on traditsiooniliselt kasutatud osas Arktikast.",
        ["a snow house"],
        ["lumemaja"],
      ],
      [
        "Houseboat",
        "This boat may stay moored because its main job is to be someone's regular home. Name it.",
        "See paat võib jääda kai äärde, sest selle peamine otstarve on olla kellegi alaline kodu. Nimeta see.",
        "a houseboat",
        "paatelamu",
        "A houseboat is a boat designed or modified primarily for regular dwelling.",
        "Paatelamu on paat, mis on ehitatud või ümber kohandatud eelkõige elamiseks.",
        ["a floating home"],
        ["majapaat"],
      ],
      [
        "Shipping_container_architecture",
        "A cargo box that once travelled by ship or rail gains windows, insulation and a front door. Name this kind of home.",
        "Varem laeval või rongil kaupa vedanud kast saab aknad, soojustuse ja välisukse. Nimeta selline kodu.",
        "a shipping-container home",
        "merekonteinermaja",
        "Shipping-container architecture adapts intermodal freight containers into homes and other buildings.",
        "Merekonteinerarhitektuur kohandab kaubaveokonteinereid kodudeks ja muudeks hooneteks.",
        ["a container home"],
        ["konteinermaja"],
      ],
      [
        "Yurt",
        "Nomadic families in Inner Asia can pack up this round felt-covered dwelling and move on. Name it.",
        "Sise-Aasia rändpered saavad selle ümmarguse vildiga kaetud elamu kokku pakkida ja edasi liikuda. Nimeta see.",
        "a yurt",
        "jurta",
        "A yurt is a portable round dwelling traditionally covered and insulated with felt or skins.",
        "Jurta on kaasaskantav ümmargune elamu, mida traditsiooniliselt katab ja soojustab vilt või loomanahk.",
        ["a ger"],
        ["jurt"],
      ],
      [
        "Stilt_house",
        "Posts lift this home above water or flood-prone ground. Name the house type.",
        "Postid tõstavad selle kodu vee või üleujutusohuga maapinna kohale. Nimeta majatüüp.",
        "a stilt house",
        "vaiadel maja",
        "Stilt houses are raised above land or water and are often built to reduce flood risk.",
        "Vaiadel majad on tõstetud maapinna või vee kohale ning neid ehitatakse sageli üleujutusohu vähendamiseks.",
        ["a pile dwelling"],
        ["vaiadele ehitatud maja"],
      ],
    ],
  ],
  [
    114,
    "round-two",
    "buildings",
    "Buildings with a Job",
    "Kindla otstarbega hooned",
    [
      [
        "Car_wash",
        "Soap, water, brushes and jets get to work while the vehicle waits in this purpose-built place. Name it.",
        "Seep, vesi, harjad ja veejoad asuvad tööle, kui sõiduk selles spetsiaalses paigas ootab. Nimeta koht.",
        "a car wash",
        "autopesula",
        "A car wash is a facility designed to clean the outside and sometimes the inside of motor vehicles.",
        "Autopesula on rajatis, mis on mõeldud mootorsõidukite välispinna ja vahel ka sisemuse puhastamiseks.",
      ],
      [
        "Fire_station",
        "The engines, hoses and protective gear wait here until firefighters receive the next alarm. Name the building.",
        "Päästeautod, voolikud ja kaitsevarustus ootavad siin, kuni päästjad saavad järgmise väljakutse. Nimeta hoone.",
        "a fire station",
        "tuletõrjedepoo",
        "A fire station houses firefighting vehicles, equipment and working areas for firefighters.",
        "Tuletõrjedepoos asuvad päästesõidukid, varustus ja päästjate tööruumid.",
        ["a firehouse", "a fire hall"],
        ["päästejaam", "tuletõrjejaam"],
      ],
      [
        "Hangar",
        "Aircraft roll indoors here for shelter, maintenance or repairs. Name the building.",
        "Õhusõidukid veerevad siia varju, hooldusse või remonti. Nimeta hoone.",
        "a hangar",
        "angaar",
        "A hangar is built to store and protect aircraft and to support maintenance and repair work.",
        "Angaar on ehitatud õhusõidukite hoidmiseks ja kaitsmiseks ning nende hooldus- ja remonditöödeks.",
        ["an aircraft hangar"],
        ["lennukiangaar"],
      ],
      [
        "Boathouse",
        "After a day of rowing, the boats return to this waterside shelter. Name the building.",
        "Pärast sõudepäeva viiakse paadid tagasi sellesse veeäärsesse varjualusesse. Nimeta hoone.",
        "a boathouse",
        "paadikuur",
        "A boathouse is a building beside or over water that shelters boats.",
        "Paadikuur on vee ääres või kohal asuv hoone, mis kaitseb paate.",
        ["a boat house"],
        ["paadimaja"],
      ],
      [
        "Signalling_control",
        "From this railway building, an operator can set points and control train movements with levers. Name it.",
        "Sellest raudteehoonest saab töötaja kangidega pööranguid seada ja rongide liikumist juhtida. Nimeta hoone.",
        "a signal box",
        "tsentralisatsioonipost",
        "A signal box contains equipment used to control railway points and signals.",
        "Tsentralisatsioonipostis asuvad seadmed, millega juhitakse raudtee pööranguid ja signaale.",
        ["a signal cabin", "an interlocking tower", "a switch tower"],
        ["signaalputka", "signaalikabiin", "raudtee tsentralisatsioonipost"],
      ],
    ],
  ],
  [
    115,
    "round-two",
    "movements",
    "When Art Broke the Rules",
    "Kui kunst murdis reegleid",
    [
      [
        "Pop_art",
        "Soup cans, comic panels and celebrity faces left supermarkets and magazines for gallery walls in this movement. Name it.",
        "Supipurgid, koomiksipildid ja kuulsuste näod jõudsid selle kunstivooluga supermarketitest ja ajakirjadest galeriiseintele. Nimeta kunstivool.",
        "Pop art",
        "popkunst",
        "Pop art borrowed imagery from mass culture, including advertising, comics, celebrities and everyday products.",
        "Popkunst kasutas massikultuuri kujundeid, sealhulgas reklaame, koomikseid, kuulsusi ja igapäevaseid tooteid.",
        ["the Pop art movement"],
        ["pop art"],
      ],
      [
        "Cubism",
        "Picasso and Braque fractured subjects into geometric pieces and combined several viewpoints in this movement. Name it.",
        "Picasso ja Braque jagasid kujutatava geomeetrilisteks osadeks ning ühendasid selles kunstivoolus mitu vaatenurka. Nimeta kunstivool.",
        "Cubism",
        "kubism",
        "Cubism broke subjects apart and reassembled them in abstract forms, often combining multiple viewpoints.",
        "Kubism jagas kujutatava osadeks ja pani selle abstraktselt uuesti kokku, ühendades sageli mitu vaatenurka.",
        ["Cubist art"],
        ["kubistlik kunst"],
      ],
      [
        "Futurism",
        "Cars, aeroplanes and the rush of the modern city thrilled this Italian-born movement. Name it.",
        "Autod, lennukid ja moodsa linna kiirus vaimustasid seda Itaalias sündinud kunstivoolu. Nimeta kunstivool.",
        "Futurism",
        "futurism",
        "Futurism emphasized speed, technology and modern machines such as cars and aeroplanes.",
        "Futurism rõhutas kiirust, tehnikat ja moodsaid masinaid, näiteks autosid ja lennukeid.",
        ["Italian Futurism"],
        ["itaalia futurism"],
      ],
      [
        "Kinetic_art",
        "A gallery sculpture turns in the wind; another runs on a motor. Name the movement that makes real or apparent motion part of the work.",
        "Üks galerii skulptuur pöörleb tuules, teine töötab mootoriga. Nimeta kunstisuund, mis teeb tegeliku või näilise liikumise teose osaks.",
        "kinetic art",
        "kineetiline kunst",
        "Kinetic art incorporates real or apparent movement, including works driven by motors, wind or water.",
        "Kineetiline kunst kasutab tegelikku või näilist liikumist, sealhulgas mootori, tuule või vee jõul liikuvaid teoseid.",
      ],
      [
        "Constructivism_(art)",
        "Russian artists joined geometric design and industrial materials to propaganda and social purpose in this movement. Name it.",
        "Vene kunstnikud ühendasid selles kunstivoolus geomeetrilise kujunduse ja tööstusmaterjalid propaganda ning ühiskondliku eesmärgiga. Nimeta kunstivool.",
        "Constructivism",
        "konstruktivism",
        "Constructivism began in Russia and connected abstract geometric design with modern materials and social aims.",
        "Konstruktivism sai alguse Venemaal ning ühendas abstraktse geomeetrilise kujunduse moodsate materjalide ja ühiskondlike eesmärkidega.",
        ["Constructivist art"],
        ["konstruktivistlik kunst"],
      ],
    ],
  ],
  [
    116,
    "round-two",
    "movements",
    "Art Beyond a Painted Canvas",
    "Kunst väljaspool maalilõuendit",
    [
      [
        "Land_art",
        "Rocks, soil, plants and water become the materials while the landscape itself becomes the site. Name the movement.",
        "Kivid, muld, taimed ja vesi saavad materjalideks ning maastikust endast saab teose asukoht. Nimeta kunstivool.",
        "land art",
        "maakunst",
        "Land art uses landscapes and materials found in nature, including earth, rock, plants and water.",
        "Maakunst kasutab maastikke ja loodusest leitud materjale, sealhulgas mulda, kive, taimi ja vett.",
        ["Earth art"],
        ["maastikukunst"],
      ],
      [
        "Sound_art",
        "Speakers, resonating objects and recorded noise take over the role normally given to paint or stone. Name this practice.",
        "Kõlarid, resoneerivad esemed ja salvestatud müra võtavad üle rolli, mis tavaliselt kuulub värvile või kivile. Nimeta see kunstipraktika.",
        "sound art",
        "helikunst",
        "Sound art uses sound as its primary time-based medium or material.",
        "Helikunst kasutab peamise ajalise meediumi või materjalina heli.",
      ],
      [
        "Body_art",
        "The creator's own skin and physical presence become the main medium in this practice. Name it.",
        "Looja enda nahk ja füüsiline kohalolu saavad selle praktika peamiseks meediumiks. Nimeta kunstipraktika.",
        "body art",
        "kehakunst",
        "Body art is made on, with or through the human body, which becomes part of the artwork.",
        "Kehakunst luuakse inimkehale, inimkehaga või inimkeha kaudu, nii et keha saab teose osaks.",
      ],
      [
        "Video_art",
        "A gallery monitor loops moving images without actors or a conventional plot. Name this medium-based practice.",
        "Galerii ekraanil korduvad liikuvad pildid ilma näitlejate või tavapärase süžeeta. Nimeta see meediumipõhine kunstipraktika.",
        "video art",
        "videokunst",
        "Video art uses video as a visual or audiovisual medium and often works outside conventional cinema storytelling.",
        "Videokunst kasutab videot visuaalse või audiovisuaalse meediumina ega pea järgima tavapärast filmijutustust.",
      ],
      [
        "Conceptual_art",
        "The written idea can matter more than the finished object's looks or masterful execution in this movement. Name it.",
        "Kirja pandud idee võib selles kunstivoolus olla tähtsam kui valmis teose välimus või meisterlik teostus. Nimeta kunstivool.",
        "conceptual art",
        "kontseptuaalne kunst",
        "Conceptual art gives the concept or idea equal or greater importance than traditional visual and technical concerns.",
        "Kontseptuaalses kunstis on mõte või idee vähemalt sama tähtis kui tavapärased visuaalsed ja tehnilised omadused.",
        ["conceptualism"],
        ["kontseptualism"],
      ],
    ],
  ],
  [
    117,
    "round-two",
    "materials-techniques",
    "What Drawings Are Made With",
    "Millega joonistatakse",
    [
      [
        "Colored_pencil",
        "A wooden barrel hides a pigmented core: reach for this tool when a drawing needs blue, red or green lines. Name it.",
        "Puidust ümbris peidab pigmenteeritud südamikku: siniste, punaste või roheliste joonte tegemiseks võta just see vahend. Nimeta see.",
        "a coloured pencil",
        "värvipliiats",
        "A coloured pencil has a narrow pigmented core enclosed in a wooden case.",
        "Värvipliiatsil on puidust kesta sees kitsas pigmenteeritud südamik.",
        ["a colored pencil"],
        ["värviline pliiats"],
      ],
      [
        "Crayon",
        "Childhood art boxes often contain this blunt stick of pigmented wax. Name it.",
        "Laste kunstitarvete hulgas leidub sageli seda tömpi pigmenteeritud vahast pulka. Nimeta see.",
        "a crayon",
        "vahakriit",
        "A crayon is a stick of pigmented wax used for writing or drawing.",
        "Vahakriit on pigmenteeritud vahast pulk, mida kasutatakse kirjutamiseks või joonistamiseks.",
        ["a wax crayon"],
        ["rasvakriit"],
      ],
      [
        "Gel_pen",
        "Metallic doodles show clearly even on dark paper because this tool uses thick, opaque, pigment-rich ink. Name it.",
        "Metalse läikega kritseldused paistavad isegi tumedal paberil hästi välja, sest see vahend kasutab paksu läbipaistmatut pigmenditinti. Nimeta see.",
        "a gel pen",
        "geelpliiats",
        "A gel pen suspends pigment in a water-based gel; its thick, opaque ink comes in bright, metallic and glittery colours.",
        "Geelpliiatsi pigment hõljub veepõhises geelis; selle paksu läbipaistmatut tinti leidub erksates, metalsetes ja sädelevates toonides.",
        ["a gel ink pen"],
        ["geelpastakas"],
      ],
      [
        "Mechanical_pencil",
        "Click the top and a thin replaceable lead advances from the tip; sharpening is unnecessary. Name this tool.",
        "Vajuta ülaosale ja peenike vahetatav südamik liigub otsast välja; teritada pole vaja. Nimeta vahend.",
        "a mechanical pencil",
        "mehaaniline pliiats",
        "A mechanical pencil pushes a replaceable solid marking core through its tip and does not need ordinary sharpening.",
        "Mehaaniline pliiats lükkab vahetatava kirjutussüdamiku otsast välja ega vaja tavalist teritamist.",
        ["a propelling pencil", "an automatic pencil"],
        ["täitepliiats", "automaatpliiats"],
      ],
      [
        "Oil_pastel",
        "This richly coloured drawing stick feels soft and greasy because its pigment is mixed with wax and a non-drying binder. Name the medium.",
        "See kirkavärviline joonistuspulk tundub pehme ja rasvane, sest pigment on segatud vaha ning mittekuivava sideainega. Nimeta vahend.",
        "an oil pastel",
        "õlipastell",
        "Oil pastels bind pigment with non-drying oil and wax, producing a soft, greasy drawing medium.",
        "Õlipastellis seotakse pigment mittekuivava õli ja vahaga, saades pehme ja rasvase joonistusvahendi.",
      ],
    ],
  ],
  [
    118,
    "round-two",
    "materials-techniques",
    "Yarn, Thread and Cloth",
    "Lõng, niit ja kangas",
    [
      [
        "Cross-stitch",
        "Rows of X-shaped stitches build a picture on evenly woven fabric in this needlecraft. Name it.",
        "Selles nõelatöös moodustavad X-kujuliste pistete read ühtlaselt kootud kangal pildi. Nimeta käsitöö.",
        "cross-stitch",
        "ristpiste",
        "Cross-stitch is a form of counted-thread embroidery in which X-shaped stitches form a tiled picture or pattern.",
        "Ristpiste on loendatud lõngadega tikkimisviis, milles X-kujulised pisted moodustavad ruudustikul pildi või mustri.",
        ["cross stitch"],
        ["ristpistes tikkimine"],
      ],
      [
        "Crochet",
        "One hook pulls loops of yarn through one another in this craft—no pair of knitting needles needed. Name it.",
        "Üks konks tõmbab selles käsitöös lõngasilmuseid üksteisest läbi; kudumisvarraste paari pole vaja. Nimeta käsitöö.",
        "crochet",
        "heegeldamine",
        "Crochet interlocks loops of yarn or thread with a crochet hook.",
        "Heegeldamisel ühendatakse lõnga- või niidisilmuseid heegelnõelaga.",
        ["crocheting"],
        ["heegeldus"],
      ],
      [
        "Lace",
        "Open, web-like fabric grows from looped, twisted or braided thread in this craft. Name the process.",
        "Selles käsitöös valmib silmusteks ühendatud, keeratud või põimitud niidist hõre võrgutaoline kangas. Nimeta protsess.",
        "lace making",
        "pitsitegemine",
        "Lace is an open patterned fabric made by looping, twisting or braiding threads.",
        "Pits on hõre mustriline kangas, mis valmib niite silmusteks ühendades, keerates või põimides.",
        ["lacemaking"],
        ["pitsi valmistamine"],
      ],
      [
        "Felt",
        "Loose fibres become fabric after matting, condensing and pressing rather than weaving. Name the technique.",
        "Lahtistest kiududest saab kangas vanutamise, tihendamise ja pressimise, mitte kudumise teel. Nimeta tehnika.",
        "felting",
        "viltimine",
        "Felting turns fibres into felt by matting, condensing and pressing them together.",
        "Viltimisel tehakse kiududest vilt neid vanutades, tihendades ja kokku pressides.",
        ["felt making"],
        ["vildi valmistamine"],
      ],
      [
        "Appliqu%C3%A9",
        "Small shapes cut from one fabric are sewn or stuck onto a larger piece to build a picture or pattern. Name the technique.",
        "Ühest kangast lõigatud väikesed kujundid õmmeldakse või kinnitatakse suuremale kangatükile, et moodustada pilt või muster. Nimeta tehnika.",
        "appliqué",
        "aplikatsioon",
        "Appliqué is ornamental needlework in which shaped fabric pieces are sewn or stuck onto a larger piece to form a picture or pattern.",
        "Aplikatsioon on kaunistustehnika, milles kujunditeks lõigatud kangatükid õmmeldakse või kinnitatakse suuremale tükile, et moodustada pilt või muster.",
        ["applique"],
        ["tekstiiliaplikatsioon"],
      ],
    ],
  ],
  [
    119,
    "round-two",
    "materials-techniques",
    "Building Materials Old and New",
    "Vanad ja uued ehitusmaterjalid",
    [
      [
        "Plywood",
        "Thin wooden layers are stacked and glued with their grain running in alternating directions to make this familiar board. Name it.",
        "Õhukesed puidukihid laotakse ja liimitakse vahelduva kiusuunaga tuttavaks plaatmaterjaliks. Nimeta materjal.",
        "plywood",
        "vineer",
        "Plywood is made by stacking and gluing thin wood veneers, usually with the grain of adjacent layers running at right angles.",
        "Vineer valmistatakse õhukesi puidukihte üksteise peale liimides, tavaliselt nii, et kõrvutiste kihtide kiud jooksevad täisnurga all.",
      ],
      [
        "Drywall",
        "Panels sandwich a gypsum core between heavy paper and make quick interior walls. Name this building material.",
        "Paneelides paikneb kipsisüdamik kahe tugeva paberikihi vahel ning neist saab kiiresti siseseinu ehitada. Nimeta ehitusmaterjal.",
        "drywall",
        "kipsplaat",
        "Drywall is a gypsum panel faced with heavy paper and used to construct interior walls and ceilings.",
        "Kipsplaat on tugeva paberiga kaetud kipspaneel, mida kasutatakse siseseinte ja lagede ehitamiseks.",
        ["plasterboard", "gypsum board"],
        ["kipskartong", "kipskartongplaat"],
      ],
      [
        "Plate_glass",
        "Windows, glazed doors and transparent walls all begin with broad panes manufactured in a plane form. Name this family of material.",
        "Aknad, klaasuksed ja läbipaistvad seinad saavad kõik alguse tasapinnalisena valmistatud suurtest klaaspindadest. Nimeta see materjalipere.",
        "flat glass",
        "tahvelklaas",
        "Flat glass is manufactured in a plane form and is widely used in windows, doors and glazed walls.",
        "Tahvelklaasi valmistatakse tasapinnalisena ning seda kasutatakse laialt akendes, ustes ja klaasseintes.",
        ["plate glass", "sheet glass"],
        ["lehtklaas", "plaatklaas"],
      ],
      [
        "Rammed_earth",
        "Damp soil is packed layer by layer between temporary forms until it becomes a solid wall. Name the method.",
        "Niiske pinnas tambitakse ajutiste raketiste vahel kiht kihi haaval tugevaks seinaks. Nimeta meetod.",
        "rammed earth",
        "tampsavi",
        "Rammed-earth construction compresses a damp soil mixture in layers inside formwork to create solid walls.",
        "Tampsaviehituses tihendatakse niiske savipinnas raketises kihtide kaupa tugevaks seinaks.",
        ["rammed soil", "compacted earth"],
        ["tambitud savipinnas", "tambitud pinnas"],
      ],
      [
        "Cross-laminated_timber",
        "Boards are glued in alternating right-angle layers to form strong wall and floor panels. Name this engineered timber.",
        "Lauad liimitakse vaheldumisi täisnurga all kihtideks, et saada tugevad seina- ja põrandapaneelid. Nimeta see tehispuit.",
        "cross-laminated timber",
        "ristkihtpuit",
        "Cross-laminated timber glues solid-wood boards in perpendicular layers to form strong structural panels.",
        "Ristkihtpuidus liimitakse täispuitlauad üksteise suhtes risti tugevateks kandvateks paneelideks.",
        ["CLT", "cross-laminated wood"],
        ["CLT", "ristkihtliimpuit"],
      ],
    ],
  ],
  [
    120,
    "round-two",
    "materials-techniques",
    "The Finishing Touch",
    "Viimane lihv",
    [
      [
        "Sandpaper",
        "A rough, grit-coated sheet smooths a wooden or painted surface when you rub with it. Name the tool.",
        "Karedate abrasiivteradega kaetud leht silub hõõrudes puidust või värvitud pinda. Nimeta töövahend.",
        "sandpaper",
        "liivapaber",
        "Sandpaper is paper or cloth coated with abrasive grit and is commonly used to smooth surfaces.",
        "Liivapaber on abrasiivsete teradega kaetud paber või kangas, mida kasutatakse tavaliselt pindade silumiseks.",
        ["emery paper"],
        ["smirgelpaber"],
      ],
      [
        "Polishing",
        "Repeated rubbing turns a dull surface smooth and shiny. Name the finishing process.",
        "Korduv hõõrumine muudab tuhmi pinna siledaks ja läikivaks. Nimeta viimistlusprotsess.",
        "polishing",
        "poleerimine",
        "Polishing creates a smooth, shiny surface through rubbing or chemical treatment.",
        "Poleerimine muudab pinna hõõrumise või keemilise töötlemisega siledaks ja läikivaks.",
      ],
      [
        "Gilding",
        "A picture frame gets a golden appearance from an extremely thin coating over its solid surface. Name the technique.",
        "Pildiraam saab kuldse ilme tänu äärmiselt õhukesele kihile tahkel pinnal. Nimeta tehnika.",
        "gilding",
        "kuldamine",
        "Gilding applies a thin coating of gold to surfaces such as metal, wood, porcelain or stone.",
        "Kuldamisel kantakse metallile, puidule, portselanile või kivile õhuke kullakiht.",
        ["gold leafing"],
        ["lehtkullaga katmine"],
      ],
      [
        "Shellac",
        "Flakes made from the lac insect's resin dissolve in alcohol to create this glossy brush-on wood finish. Name it.",
        "Emase kilptäi eritatud vaigust valmistatud helbed lahustatakse alkoholis, et saada see läikiv pintsliga puidule kantav viimistlus. Nimeta aine.",
        "shellac",
        "šellak",
        "Shellac is a natural resin commonly dissolved in alcohol and used as a glossy wood finish.",
        "Šellak on looduslik vaik, mis lahustatakse tavaliselt alkoholis ja mida kasutatakse puidu läikiva viimistlusena.",
      ],
      [
        "Gesso",
        "Before paint reaches canvas or a wooden panel, this white primer prepares the surface. Name it.",
        "Enne värvi kandmist lõuendile või puitpaneelile valmistab see valge krunt pinna ette. Nimeta aine.",
        "gesso",
        "gesso",
        "Gesso is a white primer mixture used to prepare canvas, wooden panels and other surfaces for paint.",
        "Gesso on valge kruntsegu, millega valmistatakse lõuend, puitpaneel või muu pind maalimiseks ette.",
      ],
    ],
  ],
];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLocaleLowerCase("en")
    .replace(/%[0-9a-f]{2}/giu, "-")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    page,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const subjectKey = `art-architecture:${slug(page)}`;
  return {
    clueId: `built-in-art-architecture-easy-expansion-${clueNumber}`,
    key: `art-architecture-easy-expansion:${categorySetId}:${tier}`,
    factKey: `art-architecture-easy-expansion:${slug(page)}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(page).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${page}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    },
  };
}

export const ART_ARCHITECTURE_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  ART_ARCHITECTURE_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
