import type { EasyExpansionCategory, EasyExpansionQuestion } from "../types";

const BATCH_ID = "06-music";
const PACK_ID = "built-in-music";
const RETRIEVED_AT = "2026-09-06";

type QuestionSeed = readonly [
  page: string,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const MUSIC_EASY_EXPANSION_SEEDS: readonly CategorySeed[] = [
  [
    101,
    "round-one",
    "classical",
    "Classical Forms and Ensembles",
    "Klassikalise muusika vormid ja koosseisud",
    [
      [
        "String_quartet",
        "Two violins, a viola and a cello make up this four-player chamber ensemble. Name it.",
        "Kaks viiulit, vioola ja tšello moodustavad selle neljaliikmelise kammeransambli. Nimeta koosseis.",
        "a string quartet",
        "keelpillikvartett",
        "A string quartet is an ensemble of two violinists, a violist and a cellist, as well as music written for that group.",
        "Keelpillikvartett on ansambel, kuhu kuuluvad kaks viiuldajat, vioolamängija ja tšellist, ning ka sellele koosseisule kirjutatud muusika.",
        ["string quartet"],
        ["kvartett"],
      ],
      [
        "Rondo",
        "A main theme keeps returning between contrasting passages in this classical form. Name the form.",
        "Selles klassikalises vormis naaseb põhiteema kontrastsete vaheosade järel ikka ja jälle. Nimeta vorm.",
        "rondo",
        "rondo",
        "A rondo is built around a principal theme that returns between contrasting musical episodes.",
        "Rondo põhineb peateemal, mis naaseb kontrastsete muusikaliste episoodide vahel.",
      ],
      [
        "Nocturne",
        "This lyrical composition evokes the night; a Polish Romantic composer wrote many famous examples for piano. Name the form.",
        "See lüüriline teos loob öise meeleolu; üks Poola romantismiaja helilooja kirjutas klaverile palju kuulsaid näiteid. Nimeta vorm.",
        "a nocturne",
        "nokturn",
        "A nocturne is a musical composition inspired by or evocative of the night, especially associated with lyrical piano music.",
        "Nokturn on ööst inspireeritud või öist meeleolu kujutav muusikateos, mida seostatakse eriti lüürilise klaverimuusikaga.",
      ],
      [
        "%C3%89tude",
        "A musician practises a piece designed to develop a particular technical skill. Name this kind of composition.",
        "Muusik harjutab pala, mis on loodud kindla mängutehnilise oskuse arendamiseks. Nimeta selline teos.",
        "an étude",
        "etüüd",
        "An étude is a composition created to practise a particular musical technique, though many are also concert works.",
        "Etüüd on kindla mängutehnika harjutamiseks loodud teos, ehkki paljud etüüdid kuuluvad ka kontserdirepertuaari.",
      ],
      [
        "Oratorio",
        "Soloists, choir and orchestra tell a large sacred story in concert, without costumes or scenery. Name the form.",
        "Solistid, koor ja orkester jutustavad kontserdil ulatusliku vaimuliku loo ilma kostüümide ja lavakujunduseta. Nimeta vorm.",
        "an oratorio",
        "oratoorium",
        "An oratorio is a large work for voices and orchestra, often on a sacred subject and normally presented without staging.",
        "Oratoorium on ulatuslik teos häältele ja orkestrile, sageli vaimulikul teemal ning tavaliselt ilma lavastuseta.",
      ],
    ],
  ],
  [
    102,
    "round-one",
    "jazz",
    "Jazz-Crossover Voices",
    "Džässiga põimunud lauljad",
    [
      [
        "Michael_Bubl%C3%A9",
        "This Canadian crooner recorded Haven't Met You Yet and a popular cover of Feeling Good. Name him.",
        "See Kanada mahedahäälne laulja salvestas lood „Haven't Met You Yet“ ja populaarse kaveri laulust „Feeling Good“. Nimeta ta.",
        "Michael Bublé",
        "Michael Bublé",
        "Michael Bublé is a Canadian singer whose recordings include Haven't Met You Yet and a cover of Feeling Good.",
        "Michael Bublé on Kanada laulja, kelle salvestiste hulka kuuluvad „Haven't Met You Yet“ ja kaver laulust „Feeling Good“.",
        ["Bublé", "Michael Buble"],
        ["Bublé", "Michael Buble"],
      ],
      [
        "Norah_Jones",
        "Come Away with Me introduced this American singer and pianist to a worldwide audience. Name her.",
        "Album „Come Away with Me“ tutvustas seda USA lauljat ja pianisti ülemaailmsele publikule. Nimeta ta.",
        "Norah Jones",
        "Norah Jones",
        "Norah Jones is an American singer and pianist whose debut album was Come Away with Me.",
        "Norah Jones on USA laulja ja pianist, kelle debüütalbum oli „Come Away with Me“.",
      ],
      [
        "Tony_Bennett",
        "I Left My Heart in San Francisco and later jazz albums with Lady Gaga point to this American singer. Name him.",
        "„I Left My Heart in San Francisco“ ja hilisemad džässialbumid Lady Gagaga viitavad sellele USA lauljale. Nimeta ta.",
        "Tony Bennett",
        "Tony Bennett",
        "American singer Tony Bennett was known for I Left My Heart in San Francisco and later recorded jazz albums with Lady Gaga.",
        "USA laulja Tony Bennett sai tuntuks looga „I Left My Heart in San Francisco“ ja salvestas hiljem Lady Gagaga džässialbumeid.",
      ],
      [
        "Sade_(singer)",
        "Smooth Operator and The Sweetest Taboo feature the restrained, jazz-influenced voice of this Nigerian-born British singer. Name her.",
        "„Smooth Operator“ ja „The Sweetest Taboo“ toovad esile selle Nigeerias sündinud Briti laulja jaheda, džässimõjulise hääle. Nimeta ta.",
        "Sade",
        "Sade",
        "British singer Sade fronts the band that bears her name and is known for songs including Smooth Operator and The Sweetest Taboo.",
        "Briti laulja Sade on enda nime kandva ansambli solist ja tuntud muu hulgas lugude „Smooth Operator“ ning „The Sweetest Taboo“ järgi.",
      ],
      [
        "Katie_Melua",
        "Nine Million Bicycles became an international hit for this Georgian-born British singer whose music blends pop, blues and jazz. Name her.",
        "„Nine Million Bicycles“ tõi sellele Gruusias sündinud Briti lauljale rahvusvahelise tuntuse; tema muusikas põimuvad popp, bluus ja džäss. Nimeta ta.",
        "Katie Melua",
        "Katie Melua",
        "Georgian-born British singer Katie Melua became internationally known through songs including Nine Million Bicycles.",
        "Gruusias sündinud Briti laulja Katie Melua sai rahvusvaheliselt tuntuks muu hulgas looga „Nine Million Bicycles“.",
      ],
    ],
  ],
  [
    103,
    "round-one",
    "folk-world",
    "Latin American Rhythms",
    "Ladina-Ameerika rütmid",
    [
      [
        "Reggaeton",
        "This style developed in Puerto Rico from Spanish reggae of Panama, then its dembow rhythm travelled worldwide with artists such as Daddy Yankee. Name it.",
        "See stiil kujunes Puerto Ricos Panama hispaaniakeelsest reggae'st ning levis hiljem Daddy Yankee suguste artistide ja dembow-rütmiga üle maailma. Nimeta stiil.",
        "reggaeton",
        "reggaeton",
        "Reggaeton developed in Puerto Rico from Spanish reggae of Panama and is strongly associated with the repeating dembow rhythm.",
        "Reggaeton kujunes Puerto Ricos Panama hispaaniakeelsest reggae'st ning seda seostatakse tugevalt korduva dembow-rütmiga.",
        ["reguetón"],
        ["reguetón"],
      ],
      [
        "Rumba",
        "This Cuban music and dance tradition shares its name with one of the ballroom dances. Name it.",
        "See Kuuba muusika- ja tantsutraditsioon kannab sama nime ühe võistlustantsuga. Nimeta see.",
        "rumba",
        "rumba",
        "Rumba refers to related Cuban music and dance traditions and also gave its name to a ballroom dance.",
        "Rumba tähistab omavahel seotud Kuuba muusika- ja tantsutraditsioone ning andis nime ka võistlustantsule.",
      ],
      [
        "Bossa_nova",
        "This relaxed samba style developed in Rio de Janeiro in the late 1950s and later entered a fruitful dialogue with jazz. Name it.",
        "See mahe sambastiil kujunes 1950. aastate lõpus Rio de Janeiros ning põimus hiljem džässiga. Nimeta stiil.",
        "bossa nova",
        "bossanoova",
        "Bossa nova developed as a relaxed samba style in Rio de Janeiro and later became closely associated with jazz musicians.",
        "Bossanoova kujunes Rio de Janeiros maheda sambastiilina ning seostus hiljem tihedalt džässmuusikutega.",
        ["bossa-nova"],
        ["bossa nova"],
      ],
      [
        "Cumbia_(Colombia)",
        "This dance music began on Colombia's Caribbean coast and later spread across Latin America. Name it.",
        "See tantsumuusika sai alguse Colombia Kariibi mere rannikul ja levis hiljem üle Ladina-Ameerika. Nimeta see.",
        "cumbia",
        "cumbia",
        "Cumbia originated on Colombia's Caribbean coast and developed into many popular forms across Latin America.",
        "Cumbia pärineb Colombia Kariibi mere rannikult ning sellest kujunes üle Ladina-Ameerika palju populaarseid vorme.",
        ["Colombian cumbia"],
        ["Kolumbia cumbia"],
      ],
      [
        "Merengue_music",
        "The Dominican Republic claims this lively music and partner dance as a national tradition. Name it.",
        "Dominikaani Vabariik peab seda hoogsat muusika- ja paaristantsustiili oma rahvuslikuks traditsiooniks. Nimeta see.",
        "merengue",
        "merengue",
        "Merengue is a lively music and partner-dance genre closely associated with the Dominican Republic.",
        "Merengue on hoogne muusika- ja paaristantsužanr, mida seostatakse tihedalt Dominikaani Vabariigiga.",
        ["merengue music"],
        ["merengue-muusika"],
      ],
    ],
  ],
  [
    104,
    "round-one",
    "composers",
    "Singer-Songwriters of the 1990s, 2000s, and 2010s",
    "1990., 2000. ja 2010. aastate lauljad-laulukirjutajad",
    [
      [
        "Thinking_Out_Loud",
        "This red-haired English songwriter co-wrote Thinking Out Loud with Amy Wadge, then recorded it himself. Name him.",
        "See punapäine Inglise laulukirjutaja kirjutas loo „Thinking Out Loud“ koos Amy Wadge'iga ja salvestas selle ise. Nimeta ta.",
        "Ed Sheeran",
        "Ed Sheeran",
        "Ed Sheeran and Amy Wadge wrote Thinking Out Loud, which Sheeran recorded for the album ×.",
        "Ed Sheeran ja Amy Wadge kirjutasid loo „Thinking Out Loud“, mille Sheeran salvestas albumile „×“.",
        ["Sheeran"],
        ["Sheeran"],
      ],
      [
        "Avril_Lavigne",
        "This Canadian singer-songwriter co-wrote Complicated and Sk8er Boi for her debut album. Name her.",
        "See Kanada laulja-laulukirjutaja oli oma debüütalbumi lugude „Complicated“ ja „Sk8er Boi“ üks autoreid. Nimeta ta.",
        "Avril Lavigne",
        "Avril Lavigne",
        "Canadian singer-songwriter Avril Lavigne co-wrote Complicated and Sk8er Boi for her debut album Let Go.",
        "Kanada laulja-laulukirjutaja Avril Lavigne oli debüütalbumi „Let Go“ lugude „Complicated“ ja „Sk8er Boi“ üks autoreid.",
        ["Lavigne"],
        ["Lavigne"],
      ],
      [
        "I%27m_Like_a_Bird",
        "This Canadian singer-songwriter wrote and recorded her breakthrough song I'm Like a Bird. Name her.",
        "See Kanada laulja-laulukirjutaja kirjutas ja salvestas oma läbimurdelaulu „I'm Like a Bird“. Nimeta ta.",
        "Nelly Furtado",
        "Nelly Furtado",
        "Nelly Furtado wrote and recorded I'm Like a Bird for her debut album Whoa, Nelly!.",
        "Nelly Furtado kirjutas ja salvestas loo „I'm Like a Bird“ oma debüütalbumile „Whoa, Nelly!“.",
        ["Furtado"],
        ["Furtado"],
      ],
      [
        "James_Blunt",
        "This former British Army officer co-wrote You're Beautiful before recording it as his worldwide hit. Name the songwriter.",
        "See endine Briti armee ohvitser oli loo „You're Beautiful“ üks autoreid ja salvestas selle hiljem ülemaailmse hitina. Nimeta laulukirjutaja.",
        "James Blunt",
        "James Blunt",
        "English singer-songwriter and former British Army officer James Blunt co-wrote and recorded You're Beautiful.",
        "Inglise laulja-laulukirjutaja ja endine Briti armee ohvitser James Blunt oli loo „You're Beautiful“ üks autoreid ning salvestas selle ise.",
      ],
      [
        "If_It_Makes_You_Happy",
        "This Missouri singer-songwriter co-wrote If It Makes You Happy with Jeff Trott, then recorded it herself. Name her.",
        "See Missourist pärit laulja-laulukirjutaja kirjutas loo „If It Makes You Happy“ koos Jeff Trottiga ja salvestas selle ise. Nimeta ta.",
        "Sheryl Crow",
        "Sheryl Crow",
        "Sheryl Crow and Jeff Trott wrote If It Makes You Happy, which Crow recorded for her self-titled album.",
        "Sheryl Crow ja Jeff Trott kirjutasid loo „If It Makes You Happy“, mille Crow salvestas oma nime kandvale albumile.",
        ["Crow"],
        ["Crow"],
      ],
    ],
  ],
  [
    105,
    "round-one",
    "instruments",
    "Instrument Parts and Playing Tools",
    "Pilliosad ja mängutarvikud",
    [
      [
        "Drum_stick",
        "A drummer grips a matched pair of these slender beaters to strike drums and cymbals. Name one.",
        "Trummar hoiab käes paari peenikesi löögivahendeid, et lüüa trumme ja taldrikuid. Nimeta üks.",
        "drumstick",
        "trummipulk",
        "A drumstick is a specialised beater used to strike drums, cymbals and other percussion instruments.",
        "Trummipulk on eriline löögivahend trummide, taldrikute ja teiste löökpillide mängimiseks.",
        ["drum stick"],
        ["trummikepp"],
      ],
      [
        "Fret",
        "A guitarist presses a string behind one of these raised strips on the neck to choose its sounding length. Name the strip.",
        "Kitarrist surub keele kaelal ühe sellise kõrgema riba taha, et määrata keele kõlava osa pikkus. Nimeta riba.",
        "fret",
        "krihv",
        "A fret is a raised strip on the neck of a stringed instrument that helps set the vibrating length of a stopped string.",
        "Krihv on keelpilli kaelal olev kõrgem riba, mis aitab määrata allavajutatud keele võnkuva osa pikkust.",
      ],
      [
        "Piano_pedals",
        "A pianist presses one of these levers with a foot to sustain or soften the instrument's sound. Name one.",
        "Pianist vajutab jalaga üht neist hoobadest, et nootide kõla pikendada või pilli kõla pehmendada. Nimeta üks.",
        "a piano pedal",
        "klaveripedaal",
        "Piano pedals are foot-operated levers that alter the instrument's sound, for example by sustaining notes or making them softer.",
        "Klaveripedaalid on jalaga juhitavad hoovad, mis näiteks pikendavad nootide kõla või muudavad pilli kõla pehmemaks.",
      ],
      [
        "Capo_(musical_device)",
        "A guitarist clamps this device across the fretboard to shorten all strings and raise their pitch while keeping familiar chord shapes. Name it.",
        "Kitarrist kinnitab selle vahendi üle sõrmlaua, et lühendada kõiki keeli, tõsta nende helikõrgust ja säilitada tuttavad akordivõtted. Nimeta vahend.",
        "a capo",
        "barreevõti",
        "A capo clamps across a fretted instrument's strings to raise their pitch while the player uses familiar chord shapes.",
        "Barreevõti kinnitatakse üle keelpilli sõrmlaua, et tõsta kõigi keelte helikõrgust ja säilitada tuttavad akordivõtted.",
        ["capo", "capotasto"],
        ["kapo", "kapodaster"],
      ],
      [
        "Rosin",
        "A string player rubs this sticky substance onto bow hair so it grips the strings. Name it.",
        "Keelpillimängija hõõrub seda kleepuvat ainet poognajõhvidele, et need haaraksid keeli paremini. Nimeta aine.",
        "rosin",
        "kampol",
        "Rosin is rubbed onto bow hair to create the friction needed to set a string vibrating.",
        "Kampolit hõõrutakse poognajõhvidele, et tekitada keele võnkuma panemiseks vajalik hõõrdumine.",
      ],
    ],
  ],
  [
    106,
    "round-one",
    "classical",
    "Famous Piano Pieces",
    "Kuulsad klaveripalad",
    [
      [
        "Piano_Sonata_No._14_(Beethoven)",
        "Beethoven's Piano Sonata No. 14 is far better known by this night-sky nickname. Name the piece.",
        "Beethoveni 14. klaverisonaati tuntakse palju paremini selle öötaevast meenutava hüüdnime järgi. Nimeta teos.",
        "the Moonlight Sonata",
        "Kuupaistesonaat",
        "Beethoven's Piano Sonata No. 14 is commonly known as the Moonlight Sonata, a nickname added after his death.",
        "Beethoveni 14. klaverisonaati tuntakse tavaliselt „Kuupaistesonaadina“; hüüdnimi lisandus pärast helilooja surma.",
        ["Moonlight Sonata", "Beethoven's Moonlight Sonata"],
        ["Beethoveni Kuupaistesonaat", "Kuuvalgussonaat"],
      ],
      [
        "Chopsticks_(waltz)",
        "Players hold their hands vertically, little fingers down, in a chopping motion for this widely known piano waltz. Name it.",
        "Selle tuntud klaverivalsi mängijad hoiavad käsi püstiselt, väikesed sõrmed all, ning teevad raiumist meenutavaid liigutusi. Nimeta pala.",
        "Chopsticks",
        "Chopsticks",
        "Chopsticks is a widely known piano waltz played with the hands vertical and the little fingers making a chopping motion.",
        "„Chopsticks“ on tuntud klaverivalss, mida mängides hoitakse käsi püstiselt ja tehakse väikeste sõrmedega raiumist meenutavaid liigutusi.",
      ],
      [
        "The_Entertainer",
        "Scott Joplin wrote this jaunty rag later made famous again by the film The Sting. Name the piece.",
        "Scott Joplin kirjutas selle hoogsa sünkopeeritud klaveripala, mille film „The Sting“ hiljem taas kuulsaks tegi. Nimeta teos.",
        "The Entertainer",
        "The Entertainer",
        "The Entertainer is a rag by Scott Joplin that gained renewed popularity through the film The Sting.",
        "„The Entertainer“ on Scott Joplini sünkopeeritud klaveripala, mis sai filmi „The Sting“ kaudu uuesti populaarseks.",
      ],
      [
        "Suite_bergamasque",
        "Its French title means moonlight: name Debussy's dreamy piano piece from Suite bergamasque.",
        "Selle prantsuskeelne pealkiri tähendab kuuvalgust. Nimeta Debussy unenäoline klaveripala süidist „Suite bergamasque“.",
        "Clair de lune",
        "Clair de lune",
        "Clair de lune, whose title means moonlight, is the third movement of Claude Debussy's Suite bergamasque.",
        "„Clair de lune“, mille pealkiri tähendab kuuvalgust, on Claude Debussy „Suite bergamasque'i“ kolmas osa.",
        ["Debussy's Clair de lune", "Clair de Lune"],
        ["Debussy Clair de lune", "Clair de Lune"],
      ],
      [
        "Heart_and_Soul_(Frank_Loesser_and_Hoagy_Carmichael_song)",
        "Tom Hanks and Robert Loggia play this song as a duet on a giant floor piano in the film Big. Name it.",
        "Tom Hanks ja Robert Loggia mängivad seda laulu filmis „Big“ hiiglaslikul põrandaklaveril duetina. Nimeta laul.",
        "Heart and Soul",
        "Heart and Soul",
        "Heart and Soul is a 1938 song by Hoagy Carmichael and Frank Loesser that is often played as a simple piano duet and appears in Big.",
        "„Heart and Soul“ on Hoagy Carmichaeli ja Frank Loesseri 1938. aasta laul, mida mängitakse sageli lihtsa klaveriduetina ja mis kõlab filmis „Big“.",
      ],
    ],
  ],
  [
    107,
    "round-one",
    "folk-world",
    "Songs Known Around the World",
    "Üle maailma tuntud laulud",
    [
      [
        "Fr%C3%A8re_Jacques",
        "A familiar French nursery round asks whether a friar is sleeping. Name the song.",
        "See tuntud prantsuse lastelaulukaanon küsib, kas munk magab. Nimeta laul.",
        "Frère Jacques",
        "Frère Jacques",
        "Frère Jacques is a traditional French round about a sleeping friar.",
        "„Frère Jacques“ on traditsiooniline prantsuse kaanon, mis räägib magavast mungast.",
        ["Are You Sleeping?"],
        ["Sepapoisid"],
      ],
      [
        "Kalinka_(1860_song)",
        "Ivan Larionov wrote this Russian song whose title refers to the guelder-rose plant. Name it.",
        "Ivan Larionov kirjutas selle vene laulu, mille pealkiri viitab lodjapuule. Nimeta laul.",
        "Kalinka",
        "Kalinka",
        "Kalinka is a Russian song written by Ivan Larionov; its title refers to the guelder-rose or snowball-tree plant.",
        "„Kalinka“ on Ivan Larionovi kirjutatud vene laul, mille pealkiri viitab lodjapuule.",
      ],
      [
        "Auld_Lang_Syne",
        "People traditionally sing this Scots-language song at midnight on New Year's Eve. Name it.",
        "Seda šotikeelset laulu lauldakse traditsiooniliselt vana-aastaõhtu südaööl. Nimeta laul.",
        "Auld Lang Syne",
        "Auld Lang Syne",
        "Auld Lang Syne is a Scots-language song traditionally sung around the world at the close of the old year.",
        "„Auld Lang Syne“ on šotikeelne laul, mida lauldakse kogu maailmas traditsiooniliselt vana aasta lõpus.",
      ],
      [
        "Guantanamera",
        "The title of this Cuban song means woman from Guantánamo. Name it.",
        "Selle Kuuba laulu pealkiri tähendab Guantánamost pärit naist. Nimeta laul.",
        "Guantanamera",
        "Guantanamera",
        "Guantanamera is a Cuban song whose Spanish title means a woman from Guantánamo.",
        "„Guantanamera“ on Kuuba laul, mille hispaaniakeelne pealkiri tähendab Guantánamost pärit naist.",
      ],
      [
        "Danny_Boy",
        "Frederic Weatherly's words turned the Irish tune Londonderry Air into this farewell song. Name it.",
        "Frederic Weatherly sõnad muutsid iiri viisi „Londonderry Air“ selleks hüvastijätulauluks. Nimeta laul.",
        "Danny Boy",
        "Danny Boy",
        "Danny Boy sets words by Frederic Weatherly to the traditional Irish melody Londonderry Air.",
        "„Danny Boy“ ühendab Frederic Weatherly sõnad traditsioonilise iiri viisiga „Londonderry Air“.",
      ],
    ],
  ],
  [
    108,
    "round-one",
    "jazz",
    "Jazz Styles and Sounds",
    "Džässistiilid ja -kõlad",
    [
      [
        "Jazz_trio",
        "Piano, double bass and drums make up the classic version of this three-player jazz ensemble. Name it.",
        "Klaver, kontrabass ja trummid moodustavad selle kolmeliikmelise džässansambli klassikalise koosseisu. Nimeta ansambel.",
        "a jazz trio",
        "džässitrio",
        "A jazz trio is a three-musician ensemble, often formed by piano, double bass and drums.",
        "Džässitrio on kolmeliikmeline ansambel, kuhu kuuluvad sageli klaver, kontrabass ja trummid.",
      ],
      [
        "Swing_music",
        "Large dance bands, a strong rhythmic groove and stars such as Benny Goodman made this jazz style the sound of the 1930s. Name it.",
        "Suured tantsuorkestrid, hoogne rütm ja Benny Goodmani sarnased tähed tegid sellest džässistiilist 1930. aastate tunnuskõla. Nimeta stiil.",
        "swing music",
        "svingmuusika",
        "Swing music became a dominant popular jazz style in the 1930s through dance-oriented big bands and bandleaders such as Benny Goodman.",
        "Svingmuusika tõusis 1930. aastatel populaarseks džässistiiliks tantsuliste bigbändide ja Benny Goodmani sarnaste orkestrijuhtide kaudu.",
      ],
      [
        "Ragtime",
        "Before jazz fully emerged, this syncopated piano style spread through sheet music and player-piano rolls. Name the style.",
        "Enne džässi täielikku väljakujunemist levis see sünkopeeritud klaveristiil noodiväljaannete ja isemängivate klaverite rullide kaudu. Nimeta stiil.",
        "ragtime",
        "ragtime",
        "Ragtime is a strongly syncopated musical style that became widely known through published piano music and player-piano rolls.",
        "Ragtime on tugevalt sünkopeeritud muusikastiil, mis sai laialt tuntuks klaverinootide ja isemängivate klaverite rullide kaudu.",
        ["ragtime music"],
        ["ragtime-muusika"],
      ],
      [
        "Bassline#Walking_bass",
        "A jazz bassist outlines the chords with a steady, stepwise bass line. Name this technique.",
        "Džässbassist järgib akorde ühtlaselt astmeliselt liikuva bassiliiniga. Nimeta tehnika.",
        "walking bass",
        "kõndiv bass",
        "Walking bass creates regular movement through a mostly stepwise or arpeggiated line that outlines the harmony.",
        "Kõndiv bass järgib harmooniat korrapäraselt liikuva, enamasti astmelise või murtud akordidel põhineva bassiliiniga.",
      ],
      [
        "Cool_jazz",
        "A restrained sound and lighter tone distinguished this postwar style from faster, fiery jazz. Name it.",
        "Vaoshoitud kõla ja kergem toon eristasid seda sõjajärgset stiili kiiremast ja tulisemast džässist. Nimeta stiil.",
        "cool jazz",
        "cool jazz",
        "Cool jazz developed after the Second World War with a comparatively relaxed and restrained approach.",
        "Cool jazz kujunes pärast Teist maailmasõda suhteliselt rahuliku ja vaoshoitud lähenemisena.",
        ["cool-jazz"],
        ["cool-džäss"],
      ],
    ],
  ],
  [
    109,
    "round-one",
    "instruments",
    "Marching-Band Instruments",
    "Marsiorkestri pillid",
    [
      [
        "Bass_drum",
        "This large drum supplies the marching band's deepest boom and often marks the main pulse. Name it.",
        "See madalahäälne löökpill annab marsiorkestrile kõige sügavama kõma ja märgib sageli põhipulssi. Nimeta pill.",
        "a bass drum",
        "suur trumm",
        "A bass drum is a large low-pitched drum used to provide a deep beat in ensembles including marching bands.",
        "Suur trumm on madala kõlaga suur löökpill, mis annab muu hulgas marsiorkestris sügava põhilöögi.",
        ["bass drum"],
        ["basstrumm"],
      ],
      [
        "Snare_drum",
        "Wires stretched beneath this drum's lower head give marching rhythms their crisp rattle. Name the drum.",
        "Selle trummi alumise naha alla pingutatud traadid annavad marsirütmile terava põrina. Nimeta pill.",
        "a snare drum",
        "väike trumm",
        "A snare drum has wires called snares stretched beneath its lower head, producing a sharp rattling sound.",
        "Väikese trummi alumise naha all on pingutatud spiraaltraadid, mis tekitavad terava põriseva heli.",
        ["snare drum", "side drum"],
        ["soolotrumm", "snare-trumm"],
      ],
      [
        "Bugle",
        "This simple brass instrument normally has no valves, so players change notes with their lips. Name it.",
        "Sellel lihtsal vaskpuhkpillil pole tavaliselt ventiile, seega muudab mängija helikõrgust huulte abil. Nimeta pill.",
        "a bugle",
        "signaalpasun",
        "A bugle is a simple brass signal instrument that normally has no valves; the player's embouchure controls its notes.",
        "Signaalpasun on lihtne vaskpuhkpill, millel tavaliselt pole ventiile ja mille helisid juhib mängija ambušüür.",
        ["bugle"],
        ["signaaltrompet"],
      ],
      [
        "Sousaphone",
        "This low brass instrument wraps around the player's body and carries a large forward-facing bell. Name it.",
        "See madal vaskpuhkpill keerdub ümber mängija keha ja selle suur lehter on suunatud ette. Nimeta pill.",
        "sousaphone",
        "sousafon",
        "A sousaphone is a tuba designed to coil around the player, making it practical for marching and outdoor performance.",
        "Sousafon on ümber mängija keha keerduv tuuba, mis sobib marsiks ja vabas õhus esinemiseks.",
        ["marching tuba"],
        ["marsituuba"],
      ],
      [
        "Euphonium",
        "In marching ensembles, a bell-forward version of this deep-sounding valved instrument is carried horizontally. Its name literally suggests a pleasant sound. Name it.",
        "Marsikoosseisudes kantakse selle madalahäälse ventiilidega pilli ettepoole suunatud lehtriga versiooni rõhtsalt. Selle nimi viitab otseselt heale või mahedale kõlale. Nimeta pill.",
        "a euphonium",
        "eufoonium",
        "The euphonium is a low-sounding valved instrument, and marching models have a horizontal, forward-facing bell.",
        "Eufoonium on madalahäälne ventiilidega pill ning marsimudelil on rõhtne ettepoole suunatud lehter.",
        ["euphonium", "marching euphonium"],
        ["euphonium", "marsiorkestri eufoonium"],
      ],
    ],
  ],
  [
    110,
    "round-one",
    "music-theory-history",
    "Reading Basic Music",
    "Noodikirja alused",
    [
      [
        "Staff_(music)",
        "In Western notation, notes are placed on five parallel horizontal lines and the spaces between them. Name this five-line system.",
        "Lääne noodikirjas paigutatakse noodid viiele paralleelsele rõhtjoonele ja nende vahedesse. Nimeta seda viiest joonest koosnevat süsteemi.",
        "a musical staff",
        "noodijoonestik",
        "A musical staff is a set of usually five horizontal lines with spaces between them, used to write notes.",
        "Noodijoonestik on tavaliselt viiest rõhtjoonest ja nendevahelistest vahedest koosnev süsteem, millele noodid kirjutatakse.",
        ["stave"],
        ["noodijoonestik"],
      ],
      [
        "Bar_(music)",
        "This vertical mark crosses the staff to separate one measure from the next. Name it.",
        "See püstine märk läbib noodijoonestikku ja eraldab ühe takti järgmisest. Nimeta märk.",
        "a bar line",
        "taktijoon",
        "A bar line is a vertical mark in notation that shows the boundary between measures.",
        "Taktijoon on noodijoonestikul olev püstjoon, mis märgib taktide piiri.",
        ["barline"],
        ["taktikriips"],
      ],
      [
        "Quarter_note",
        "A filled oval notehead with a stem usually lasts one beat in 4/4 time. Name this note value.",
        "Täidetud ovaalse noodipea ja noodivarrega noot kestab 4/4 taktimõõdus tavaliselt ühe löögi. Nimeta noodivältus.",
        "a quarter note",
        "veerandnoot",
        "A quarter note has a filled notehead and a stem and normally receives one beat in 4/4 time.",
        "Veerandnoodil on täidetud noodipea ja noodivars ning 4/4 taktimõõdus kestab see tavaliselt ühe löögi.",
        ["crotchet"],
        ["neljandiknoot"],
      ],
      [
        "Repeat_sign",
        "Two dots beside a double bar tell a performer to go back and play a section again. Name this symbol.",
        "Kaks täppi kahekordse taktijoone kõrval käsivad esitajal tagasi minna ja osa uuesti mängida. Nimeta märk.",
        "a repeat sign",
        "kordusmärk",
        "A repeat sign marks music that should be performed again, usually with dots beside paired vertical strokes.",
        "Kordusmärk tähistab uuesti esitatavat muusikalõiku ja koosneb tavaliselt kahekordse taktijoone kõrval olevatest täppidest.",
      ],
      [
        "Time_signature",
        "At the start of the staff, two stacked numbers such as 4 over 4 show how beats are grouped. Name this notation.",
        "Noodirea alguses näitavad kaks kohakuti arvu, näiteks 4 ja 4, kuidas löögid taktidesse rühmituvad. Nimeta märge.",
        "a time signature",
        "taktimõõt",
        "A time signature indicates how many beats are grouped in each measure and which note value represents a beat.",
        "Taktimõõt näitab, mitu lööki on taktis ja milline noodivältus vastab ühele löögile.",
      ],
    ],
  ],

  [
    111,
    "round-two",
    "classical",
    "Classical Music That Tells a Story",
    "Lugusid jutustav klassikaline muusika",
    [
      [
        "Peter_and_the_Wolf",
        "A narrator introduces a boy, a duck, a cat and a dangerous animal while each character is represented by an orchestra instrument. Name Prokofiev's musical tale.",
        "Jutustaja tutvustab poissi, parti, kassi ja ohtlikku looma ning iga tegelast kujutab orkestris eri pill. Nimeta Prokofjevi muusikaline muinasjutt.",
        "Peter and the Wolf",
        "Petja ja hunt",
        "Sergei Prokofiev wrote Peter and the Wolf as a narrated orchestral tale in which instruments represent the characters.",
        "Sergei Prokofjev kirjutas „Petja ja hundi“ jutustajaga orkestriteoseks, kus tegelasi kujutavad eri pillid.",
        ["Prokofiev's Peter and the Wolf"],
        ["Prokofjevi Petja ja hunt"],
      ],
      [
        "The_Carnival_of_the_Animals",
        "Lions, tortoises, an elephant and a swan parade through this Saint-Saëns suite. Name the animal-filled work.",
        "Lõvid, kilpkonnad, elevant ja luik astuvad üles selles Saint-Saënsi süidis. Nimeta loomadest tulvil teos.",
        "The Carnival of the Animals",
        "Loomade karneval",
        "Camille Saint-Saëns's suite The Carnival of the Animals portrays a playful procession of animals in separate movements.",
        "Camille Saint-Saënsi süit „Loomade karneval“ kujutab eri osades mängulist loomade rongkäiku.",
        ["Carnival of the Animals"],
        ["Saint-Saënsi Loomade karneval"],
      ],
      [
        "The_Sorcerer%27s_Apprentice_(Dukas)",
        "This 1897 orchestral scherzo by Paul Dukas became famous when Disney used it in Fantasia. Name the piece.",
        "See Paul Dukas' 1897. aasta orkestriskeertso sai kuulsaks, kui Disney kasutas seda filmis „Fantaasia“. Nimeta pala.",
        "The Sorcerer's Apprentice",
        "Nõia õpipoiss",
        "Paul Dukas composed The Sorcerer's Apprentice in 1897, and the piece became widely known through Disney's Fantasia.",
        "Paul Dukas lõi „Nõia õpipoisi“ 1897. aastal ning pala sai laialt tuntuks Disney „Fantaasia“ kaudu.",
        ["Sorcerer's Apprentice"],
        ["Dukas' Nõia õpipoiss"],
      ],
      [
        "Peer_Gynt_(Grieg)",
        "Morning Mood and In the Hall of the Mountain King come from Edvard Grieg's music for an Ibsen drama. Name that drama's wandering hero and title.",
        "„Hommikumeeleolu“ ja „Mäekuninga koopas“ pärinevad Edvard Griegi muusikast Ibseni näidendile. Nimeta näidendi rändav nimikangelane.",
        "Peer Gynt",
        "Peer Gynt",
        "Edvard Grieg composed incidental music for Henrik Ibsen's play Peer Gynt, including Morning Mood and In the Hall of the Mountain King.",
        "Edvard Grieg kirjutas Henrik Ibseni näidendile „Peer Gynt“ lavamuusika, mille hulka kuuluvad „Hommikumeeleolu“ ja „Mäekuninga koopas“.",
      ],
      [
        "William_Tell_Overture",
        "The Lone Ranger gallops to the famous finale of this Rossini overture, whose opera tells of a Swiss hero. Name the work.",
        "Telesarja „The Lone Ranger“ kangelane kappab selle Rossini avamängu kuulsa finaali saatel; ooper jutustab Šveitsi kangelasest. Nimeta teos.",
        "William Tell Overture",
        "Wilhelm Telli avamäng",
        "Rossini's William Tell Overture opens the opera about the Swiss hero, and its galloping finale became famous as the theme for The Lone Ranger.",
        "Rossini „Wilhelm Telli avamäng“ alustab Šveitsi kangelasest jutustavat ooperit ning selle kappav finaal sai tuntuks telesarja „The Lone Ranger“ tunnusmuusikana.",
        ["the William Tell Overture"],
        ["William Telli avamäng"],
      ],
    ],
  ],
  [
    112,
    "round-two",
    "folk-world",
    "Vocal Styles and Traditions",
    "Vokaalstiilid ja -traditsioonid",
    [
      [
        "Yodeling",
        "This Alpine-associated singing technique rapidly switches between a low chest voice and a high head voice. Name it.",
        "See Alpidega seostatud laulutehnika vaheldab kiiresti madalamat rinnahäält ja kõrget peahäält. Nimeta tehnika.",
        "yodeling",
        "joodeldamine",
        "Yodeling features rapid repeated changes between the lower chest register and the higher head register.",
        "Joodeldamisele on iseloomulik kiire korduv vaheldumine madalama rinna- ja kõrgema pearegistri vahel.",
        ["yodelling"],
        ["joodlemine"],
      ],
      [
        "Sea_shanty",
        "Sailors once sang this work song together to coordinate hauling ropes or raising an anchor. Name the song type.",
        "Meremehed laulsid seda töölaulu koos, et köite tõmbamist või ankru hiivamist rütmis teha. Nimeta laululiik.",
        "sea shanty",
        "meremeeste töölaul",
        "A sea shanty is a rhythmic work song formerly sung aboard large sailing vessels to coordinate labour.",
        "Meremeeste töölaul on rütmiline laul, mida lauldi purjelaevadel ühise töö koordineerimiseks.",
        ["shanty"],
        ["madruste töölaul"],
      ],
      [
        "Doo-wop",
        "Close harmony, simple beats and playful nonsense syllables mark this 1950s vocal-group style. Name it.",
        "Lähiharmoonia, lihtne rütm ja mängulised tähenduseta silbid iseloomustavad seda 1950. aastate vokaalansamblistiili. Nimeta stiil.",
        "doo-wop",
        "doo-wop",
        "Doo-wop is a rhythm-and-blues vocal style known for close harmony and repeated nonsense syllables.",
        "Doo-wop on rütmibluusi vokaalstiil, mida iseloomustavad lähiharmoonia ja korduvad tähenduseta silbid.",
      ],
      [
        "Barbershop_music",
        "Four unaccompanied voices sing close harmony as lead, tenor, baritone and bass in this style. Name it.",
        "Neli saateta häält laulavad selles stiilis lähiharmoonias juht-, tenori-, baritoni- ja bassipartiid. Nimeta stiil.",
        "barbershop music",
        "barbershop-muusika",
        "Barbershop music uses close four-part unaccompanied vocal harmony, traditionally labelled lead, tenor, baritone and bass.",
        "Barbershop-muusikas kõlab saateta neljahäälne lähiharmoonia, mille partiid on juht, tenor, bariton ja bass.",
        ["barbershop"],
        ["barbershop"],
      ],
      [
        "Whistle_register",
        "Singers use this name for the human voice's highest register, which can produce flute-like notes. Name it.",
        "Selle nimega tähistatakse inimhääle kõrgeimat registrit, milles saab tekitada flööditaolisi helisid. Nimeta register.",
        "the whistle register",
        "vileregister",
        "The whistle register is the highest register of the human voice and produces very high, flute-like tones.",
        "Vileregister on inimhääle kõrgeim register ja selles tekivad väga kõrged flööditaolised helid.",
      ],
    ],
  ],
  [
    113,
    "round-two",
    "composers",
    "Singer-Songwriters Who Broke Through Before 1990",
    "Enne 1990. aastaid läbi löönud lauljad-laulukirjutajad",
    [
      [
        "Bruce_Springsteen",
        "This New Jersey songwriter wrote and recorded Born in the U.S.A. and became known as The Boss. Name him.",
        "See New Jerseyst pärit laulukirjutaja kirjutas ja salvestas loo „Born in the U.S.A.“ ning sai tuntuks hüüdnimega The Boss. Nimeta ta.",
        "Bruce Springsteen",
        "Bruce Springsteen",
        "New Jersey singer-songwriter Bruce Springsteen wrote and recorded Born in the U.S.A. and is widely nicknamed The Boss.",
        "New Jerseyst pärit laulja-laulukirjutaja Bruce Springsteen kirjutas ja salvestas loo „Born in the U.S.A.“ ning teda tuntakse hüüdnimega The Boss.",
        ["Springsteen"],
        ["Springsteen"],
      ],
      [
        "Billy_Joel",
        "This New York songwriter wrote Piano Man from his experience playing in a Los Angeles piano bar. Name him.",
        "See New Yorgist pärit laulukirjutaja kirjutas „Piano Mani“ oma Los Angelese klaveribaaris mängimise kogemusest. Nimeta ta.",
        "Billy Joel",
        "Billy Joel",
        "American singer-songwriter Billy Joel wrote Piano Man after working as a lounge pianist in Los Angeles.",
        "Ameerika laulja-laulukirjutaja Billy Joel kirjutas „Piano Mani“ pärast seda, kui oli töötanud Los Angeleses salongipianistina.",
      ],
      [
        "Tracy_Chapman",
        "This American singer-songwriter wrote both Fast Car and Talkin' 'bout a Revolution for her debut album. Name her.",
        "See USA laulja-laulukirjutaja kirjutas oma debüütalbumile nii loo „Fast Car“ kui ka „Talkin' 'bout a Revolution“. Nimeta ta.",
        "Tracy Chapman",
        "Tracy Chapman",
        "American singer-songwriter Tracy Chapman wrote Fast Car and Talkin' 'bout a Revolution for her self-titled debut album.",
        "USA laulja-laulukirjutaja Tracy Chapman kirjutas oma nime kandvale debüütalbumile lood „Fast Car“ ja „Talkin' 'bout a Revolution“.",
      ],
      [
        "James_Taylor",
        "This American singer-songwriter wrote Fire and Rain about personal loss and recorded it for Sweet Baby James. Name him.",
        "See USA laulja-laulukirjutaja kirjutas isiklikust kaotusest loo „Fire and Rain“ ja salvestas selle albumile „Sweet Baby James“. Nimeta ta.",
        "James Taylor",
        "James Taylor",
        "American singer-songwriter James Taylor wrote and recorded Fire and Rain for his album Sweet Baby James.",
        "USA laulja-laulukirjutaja James Taylor kirjutas ja salvestas albumile „Sweet Baby James“ loo „Fire and Rain“.",
      ],
      [
        "Carole_King",
        "She co-wrote Will You Love Me Tomorrow for another group before writing and recording songs for her own album Tapestry. Name her.",
        "Ta oli ansamblile The Shirelles loodud laulu „Will You Love Me Tomorrow“ üks autoreid ning kirjutas ja salvestas hiljem laule oma albumile „Tapestry“. Nimeta ta.",
        "Carole King",
        "Carole King",
        "Carole King co-wrote Will You Love Me Tomorrow before becoming a recording artist and songwriter behind the album Tapestry.",
        "Carole King oli loo „Will You Love Me Tomorrow“ üks autoreid ning sai hiljem albumi „Tapestry“ esitaja ja laulukirjutajana tuntuks.",
      ],
    ],
  ],
  [
    114,
    "round-two",
    "instruments",
    "Electronic Music Tools",
    "Elektroonilise muusika tööriistad",
    [
      [
        "Electronic_drum",
        "A player strikes rubber or mesh pads, and a sound module turns the hits into percussion sounds. Name this digital drum setup.",
        "Mängija lööb kummist või võrkkattega patju ning helimoodul muudab löögid löökpillihelideks. Nimeta see digitaalne trummikomplekt.",
        "electronic drums",
        "elektrontrummid",
        "Electronic drums use playable pads and an electronic sound module to produce percussion sounds.",
        "Elektrontrummides tekitavad mängitavad padjad ja elektrooniline helimoodul löökpillihelisid.",
        ["electronic drum kit", "electronic drum set"],
        ["elektroonilised trummid", "elektrontrummikomplekt"],
      ],
      [
        "MIDI_keyboard",
        "Its piano-style keys usually send performance instructions to software or another sound module rather than making acoustic sound themselves. Name this controller.",
        "Selle klaverilaadsed klahvid saadavad tavaliselt mängukäske tarkvarale või helimoodulile, mitte ei tekita ise akustilist heli. Nimeta see kontroller.",
        "MIDI keyboard",
        "MIDI-klaviatuur",
        "A MIDI keyboard is a piano-style controller that sends MIDI performance data to another device or software instrument.",
        "MIDI-klaviatuur on klaverilaadne kontroller, mis saadab MIDI-mänguandmeid teisele seadmele või tarkvarapillile.",
        ["MIDI controller keyboard"],
        ["MIDI-kontrollerklaviatuur"],
      ],
      [
        "Live_looping",
        "A solo musician records a phrase during a performance, starts it repeating and plays the next part over it. Name this device.",
        "Soolomuusik salvestab esinemise ajal fraasi, laseb selle korduses käima ja mängib järgmise partii peale. Nimeta seade.",
        "a loop station",
        "luuper",
        "A loop station records short passages and repeats them so a performer can build layered music live.",
        "Luuper salvestab lühikesi lõike ja kordab neid, et esitaja saaks reaalajas kihilist muusikat luua.",
        ["loop pedal"],
        ["looper-pedaal"],
      ],
      [
        "Digital_audio_workstation",
        "A producer records, edits and mixes tracks on a computer inside this kind of music software. Name it.",
        "Produtsent salvestab, töötleb ja miksib arvutis heliradu seda liiki muusikatarkvaras. Nimeta see.",
        "a digital audio workstation",
        "digitaalne helitööjaam",
        "DAW software is used to record, edit, arrange and mix digital audio.",
        "DAW-tarkvara kasutatakse digitaalse heli salvestamiseks, töötlemiseks, seadmiseks ja miksimiseks.",
        ["DAW"],
        ["DAW"],
      ],
      [
        "Music_sequencer",
        "This hardware or software arranges recorded or programmed musical events along a timeline for later playback. Name it.",
        "See riistvara või tarkvara paigutab salvestatud või programmeeritud muusikasündmused ajajoonele, et neid hiljem esitada. Nimeta see.",
        "music sequencer",
        "sekventser",
        "A music sequencer records, edits and plays back musical performance information in an ordered sequence.",
        "Sekventser salvestab, muudab ja esitab muusikalist esitusinfot järjestatud jadana.",
        ["sequencer"],
        ["muusikasekventser"],
      ],
    ],
  ],
  [
    115,
    "round-two",
    "folk-world",
    "Latin Styles and Crossovers",
    "Ladina stiilid ja žanriühendused",
    [
      [
        "Latin_pop",
        "Pop music performed mainly in Spanish or Portuguese is grouped under this two-word genre name. Name it.",
        "Peamiselt hispaania või portugali keeles esitatud popmuusikat koondatakse selle kahe sõnaga žanrinimetuse alla. Nimeta žanr.",
        "Latin pop",
        "ladinapopp",
        "Latin pop is a broad label for popular music from Spanish- and Portuguese-speaking areas and performers.",
        "Ladinapopp on hispaania- ja portugalikeelsete piirkondade ning esitajate popmuusika lai koondnimetus.",
        ["Latin-pop"],
        ["ladina popp"],
      ],
      [
        "Mambo_(music)",
        "This Cuban dance-music genre was popularised in big-band form by Pérez Prado and became a 1940s–1950s dance craze. Name it.",
        "Selle Kuuba tantsumuusikažanri tegi bigbändiseades tuntuks Pérez Prado ning 1940.–1950. aastatel sai sellest tantsuhullus. Nimeta žanr.",
        "mambo",
        "mambo",
        "Mambo is a Cuban dance-music genre that Pérez Prado popularised internationally in a big-band form.",
        "Mambo on Kuuba tantsumuusikažanr, mille Pérez Prado tegi bigbändiseades rahvusvaheliselt tuntuks.",
      ],
      [
        "Latin_jazz",
        "This jazz genre uses Latin American rhythms; its main branches include Afro-Cuban and Afro-Brazilian jazz. Name it.",
        "Selles džässižanris kasutatakse Ladina-Ameerika rütme; selle peamiste harude hulka kuuluvad afrokuuba ja afrobrasiilia džäss. Nimeta žanr.",
        "Latin jazz",
        "ladina džäss",
        "Latin jazz combines jazz with Latin American rhythms, especially through Afro-Cuban and Afro-Brazilian branches.",
        "Ladina džäss ühendab džässi Ladina-Ameerika rütmidega, eriti afrokuuba ja afrobrasiilia harude kaudu.",
        ["Latin jazz music"],
        ["ladina jazz"],
      ],
      [
        "Rock_en_espa%C3%B1ol",
        "This Spanish phrase names rock music whose vocals are sung in Spanish. Give the phrase.",
        "Selle hispaaniakeelse väljendiga nimetatakse hispaaniakeelsete vokaalidega rokkmuusikat. Nimeta väljend.",
        "rock en español",
        "rock en español",
        "Rock en español is the Spanish-language term for rock music performed with Spanish vocals.",
        "Rock en español on hispaaniakeelne nimetus hispaaniakeelsete vokaalidega rokkmuusikale.",
        ["Spanish-language rock"],
        ["hispaaniakeelne rokk"],
      ],
      [
        "Son_cubano",
        "This eastern Cuban music-and-dance tradition blends Spanish-derived song and guitar with African-rooted clave, call-and-response and percussion. Name it.",
        "See Ida-Kuubast pärit muusika- ja tantsutraditsioon ühendab Hispaania päritolu laulustiili ja kitarri Aafrika juurtega clave-rütmi, eeslaulja ja koori vaheldumise ning löökpillidega. Nimeta see.",
        "son cubano",
        "son cubano",
        "Son cubano developed in eastern Cuba by combining Spanish-derived song and guitar with African-rooted rhythms, vocal exchange and percussion.",
        "Son cubano kujunes Ida-Kuubas, ühendades Hispaania päritolu laulustiili ja kitarri Aafrika juurtega rütmide, vokaalse vaheldumise ning löökpillidega.",
        ["Cuban son"],
        ["Kuuba son"],
      ],
    ],
  ],
  [
    116,
    "round-two",
    "classical",
    "Great Classical Soloists",
    "Klassikalise muusika suured solistid",
    [
      [
        "Andrea_Bocelli",
        "Time to Say Goodbye and duets that bridge opera and pop point to this blind Italian tenor. Name him.",
        "„Time to Say Goodbye“ ning ooperit ja poppi ühendavad duetid viitavad sellele pimedale Itaalia tenorile. Nimeta ta.",
        "Andrea Bocelli",
        "Andrea Bocelli",
        "Blind Italian tenor Andrea Bocelli became internationally known through recordings that cross between classical and popular music, including Time to Say Goodbye.",
        "Pime Itaalia tenor Andrea Bocelli sai rahvusvaheliselt tuntuks klassikalist ja levimuusikat ühendavate salvestistega, sealhulgas looga „Time to Say Goodbye“.",
        ["Bocelli"],
        ["Bocelli"],
      ],
      [
        "Andr%C3%A9_Rieu",
        "This Dutch violinist leads the Johann Strauss Orchestra in festive concerts filled with waltzes. Name him.",
        "See Hollandi viiuldaja juhatab pidulikel valsikontsertidel Johann Straussi orkestrit. Nimeta ta.",
        "André Rieu",
        "André Rieu",
        "Dutch violinist André Rieu founded and leads the Johann Strauss Orchestra, known for popular performances of waltzes.",
        "Hollandi viiuldaja André Rieu asutas Johann Straussi orkestri ja juhib seda populaarsetel valsikontsertidel.",
        ["Andre Rieu", "Rieu"],
        ["Andre Rieu", "Rieu"],
      ],
      [
        "Yo-Yo_Ma",
        "This Paris-born cellist's work ranges from Bach recordings to projects with the Silk Road Ensemble. Name him.",
        "Selle Pariisis sündinud tšellisti tegevus ulatub Bachi teoste salvestamisest Silk Road Ensemble'i projektideni. Nimeta ta.",
        "Yo-Yo Ma",
        "Yo-Yo Ma",
        "Cellist Yo-Yo Ma has recorded Bach and founded the Silk Road Ensemble alongside his classical career.",
        "Tšellist Yo-Yo Ma on salvestanud Bachi teoseid ning asutas klassikalise karjääri kõrval Silk Road Ensemble'i.",
        ["Yo Yo Ma"],
        ["Yo Yo Ma"],
      ],
      [
        "Maria_Callas",
        "This Greek-American soprano, nicknamed La Divina, became one of the twentieth century's most celebrated opera singers. Name her.",
        "See kreeka-ameerika sopran hüüdnimega La Divina sai üheks 20. sajandi kuulsaimaks ooperilauljaks. Nimeta ta.",
        "Maria Callas",
        "Maria Callas",
        "Greek-American soprano Maria Callas was one of the twentieth century's most renowned opera singers and was nicknamed La Divina.",
        "Kreeka-Ameerika sopran Maria Callas oli üks 20. sajandi hinnatumaid ooperilauljaid ning kandis hüüdnime La Divina.",
        ["Callas"],
        ["Callas"],
      ],
      [
        "Lang_Lang",
        "This Chinese concert pianist's name repeats the same spelling in the Latin alphabet, and he performed at the 2008 Beijing Olympics opening ceremony. Name him.",
        "Selle Hiina kontsertpianisti nimi kordab ladina kirjas sama kirjapilti ning ta esines 2008. aasta Pekingi olümpiamängude avatseremoonial. Nimeta ta.",
        "Lang Lang",
        "Lang Lang",
        "Chinese concert pianist Lang Lang, whose two names have the same Latin-alphabet spelling but different tones, performed at the 2008 Beijing Olympic Games opening ceremony.",
        "Hiina kontsertpianist Lang Lang, kelle kahe nime kirjapilt on ladina kirjas sama, kuid toon erineb, esines 2008. aasta Pekingi olümpiamängude avatseremoonial.",
        ["Láng Lǎng"],
        ["Láng Lǎng"],
      ],
    ],
  ],
  [
    117,
    "round-two",
    "jazz",
    "Jazz-Age Dances",
    "Džässiajastu tantsud",
    [
      [
        "Tap_dance",
        "Metal plates on a dancer's shoes turn footwork into audible percussion in this style. Name it.",
        "Tantsija kingade metallplaadid muudavad sammud selles stiilis kuuldavaks löökpillipartiiks. Nimeta stiil.",
        "tap dance",
        "stepp",
        "Tap dance uses shoes fitted with metal taps to create rhythmic percussion through footwork.",
        "Stepp kasutab metallplaatidega kingi, et luua sammudega rütmilist löökpillikõla.",
        ["tap dancing"],
        ["stepptants"],
      ],
      [
        "Charleston_(dance)",
        "Bent knees, swinging arms and fast kicks made this 1920s dance named after a South Carolina city instantly recognisable. Name it.",
        "Kõverdatud põlved, hoogsed käeliigutused ja kiired jalalöögid tegid selle Lõuna-Carolina linna järgi nimetatud 1920. aastate tantsu kergesti äratuntavaks. Nimeta see.",
        "Charleston",
        "tšarleston",
        "The Charleston is an energetic dance named for Charleston, South Carolina, and closely associated with the 1920s.",
        "Tšarleston on energiline Lõuna-Carolina Charlestoni järgi nimetatud tants, mida seostatakse tihedalt 1920. aastatega.",
        ["Charleston dance"],
        ["Charlestoni tants"],
      ],
      [
        "Foxtrot",
        "Long, smooth travelling steps give this partner dance its characteristic slow-slow-quick-quick rhythm. Name it.",
        "Pikad sujuvad sammud annavad sellele paaristantsule iseloomuliku „aeglane–aeglane–kiire–kiire“ rütmi. Nimeta see.",
        "foxtrot",
        "fokstrott",
        "The foxtrot is a smooth progressive partner dance commonly taught with a slow-slow-quick-quick rhythm.",
        "Fokstrott on sujuvalt edasi liikuv paaristants, mida õpetatakse sageli rütmiga „aeglane–aeglane–kiire–kiire“.",
        ["fox trot"],
        ["foxtrot"],
      ],
      [
        "Cakewalk",
        "High-stepping couples once competed for a cake as the prize in this dance, whose name later came to mean an easy task. Name it.",
        "Kõrgete sammudega paarid võistlesid selles tantsus kunagi auhinnaks olnud koogi nimel; tantsu ingliskeelne nimi hakkas hiljem tähendama lihtsat ülesannet. Nimeta tants.",
        "cakewalk",
        "cakewalk",
        "The cakewalk developed as a competitive dance whose prize was often a cake, and its name later became a term for something easily accomplished.",
        "Cakewalk kujunes võistlustantsuna, mille auhind oli sageli kook, ning selle nimi hakkas hiljem tähendama kergesti tehtavat asja.",
      ],
      [
        "Shimmy",
        "Keeping the torso mostly still while the shoulders shake rapidly creates this Jazz Age dance. Name it.",
        "Selles džässiajastu tantsus püsib kere suuresti paigal, kuid õlad värisevad kiiresti. Nimeta tants.",
        "shimmy",
        "shimmy",
        "The shimmy is a dance in which the body is held fairly still while the shoulders move rapidly back and forth.",
        "Shimmy on tants, milles keha püsib üsna paigal ja õlad liiguvad kiiresti edasi-tagasi.",
        ["shimmy dance"],
        ["shimmy-tants"],
      ],
    ],
  ],
  [
    118,
    "round-two",
    "folk-world",
    "Regional Popular Music Traditions",
    "Piirkondlikud levimuusikatraditsioonid",
    [
      [
        "K-pop",
        "BTS and BLACKPINK helped take this South Korean popular-music style to a worldwide audience. Name the style.",
        "BTS ja BLACKPINK aitasid selle Lõuna-Korea popmuusikastiili ülemaailmse publikuni viia. Nimeta stiil.",
        "K-pop",
        "K-pop",
        "K-pop is South Korean popular music that gained a large international audience through acts including BTS and BLACKPINK.",
        "K-pop on Lõuna-Korea popmuusika, mis jõudis muu hulgas BTS-i ja BLACKPINKi kaudu suure rahvusvahelise publikuni.",
        ["Korean pop"],
        ["Korea pop"],
      ],
      [
        "J-pop",
        "This short label means Japanese popular music and became common for Japan's modern mainstream sound. Name it.",
        "See lühinimetus tähendab Jaapani popmuusikat ja kinnistus Jaapani moodsa peavoolumuusika kohta. Nimeta see.",
        "J-pop",
        "J-pop",
        "J-pop is the common abbreviated name for modern Japanese popular music.",
        "J-pop on Jaapani moodsa popmuusika levinud lühinimetus.",
        ["Japanese pop"],
        ["Jaapani pop"],
      ],
      [
        "Hindi_film_music",
        "Songs written for India's Hindi-language cinema form this tradition, often known internationally through Bollywood. Name it.",
        "India hindikeelsele kinole kirjutatud laulud moodustavad selle muusikatraditsiooni, mida tuntakse rahvusvaheliselt sageli Bollywoodi kaudu. Nimeta see.",
        "Hindi film music",
        "Hindi filmimuusika",
        "Hindi film music consists of songs written and performed for Hindi-language cinema and is widely associated with Bollywood.",
        "Hindi filmimuusika koosneb hindikeelsele kinole kirjutatud ja esitatud lauludest ning seda seostatakse laialt Bollywoodiga.",
        ["Bollywood film music", "Bollywood music"],
        ["Bollywoodi filmimuusika", "Bollywoodi muusika"],
      ],
      [
        "Afrobeats",
        "Burna Boy and Wizkid helped take this contemporary West African pop umbrella, centred especially in Nigeria and Ghana, around the world. Name it.",
        "Burna Boy ja Wizkid aitasid selle eriti Nigeeria ja Ghanaga seotud nüüdisaegse Lääne-Aafrika popmuusika koondnimetuse üle maailma viia. Nimeta see.",
        "Afrobeats",
        "Afrobeats",
        "Afrobeats is an umbrella term for contemporary West African popular music, distinct from the older genre called Afrobeat.",
        "Afrobeats on nüüdisaegse Lääne-Aafrika popmuusika koondnimetus ning erineb vanemast žanrist Afrobeat.",
      ],
      [
        "Cantopop",
        "Hong Kong popular songs performed mainly in Cantonese carry this blended name. Name the style.",
        "Peamiselt kantoni keeles esitatud Hongkongi poplaulud kannavad seda liitsõnalist nimetust. Nimeta stiil.",
        "Cantopop",
        "Cantopop",
        "Cantopop is a form of popular music associated with Hong Kong and sung chiefly in Cantonese.",
        "Cantopop on Hongkongiga seostatud popmuusika, mida lauldakse peamiselt kantoni keeles.",
        ["Cantonese pop"],
        ["kantonikeelne pop"],
      ],
    ],
  ],
  [
    119,
    "round-two",
    "composers",
    "Great Classical Composers",
    "Klassikalise muusika suured heliloojad",
    [
      [
        "Fr%C3%A9d%C3%A9ric_Chopin",
        "This Polish-born Romantic composer became inseparable from the piano through his nocturnes, études and mazurkas. Name him.",
        "See Poolas sündinud romantismiaja helilooja sai oma nokturnide, etüüdide ja masurkade kaudu klaveriga lahutamatult seotuks. Nimeta ta.",
        "Frédéric Chopin",
        "Frédéric Chopin",
        "Frédéric Chopin was a Polish-born Romantic composer and pianist celebrated for works including nocturnes, études and mazurkas.",
        "Frédéric Chopin oli Poolas sündinud romantismiaja helilooja ja pianist, kes on tuntud muu hulgas nokturnide, etüüdide ja masurkade poolest.",
        ["Chopin", "Frederic Chopin"],
        ["Chopin", "Frederic Chopin"],
      ],
      [
        "Franz_Liszt",
        "Hungarian Rhapsodies and dazzling piano showpieces point to this Hungarian Romantic composer and virtuoso. Name him.",
        "„Ungari rapsoodiad“ ja säravad klaveripalad viitavad sellele Ungari romantismiaja heliloojale ja virtuoosile. Nimeta ta.",
        "Franz Liszt",
        "Franz Liszt",
        "Hungarian Romantic composer and pianist Franz Liszt wrote the Hungarian Rhapsodies and many virtuoso piano works.",
        "Ungari romantismiaja helilooja ja pianist Franz Liszt kirjutas „Ungari rapsoodiad“ ja palju virtuoosseid klaveriteoseid.",
        ["Liszt"],
        ["Liszt"],
      ],
      [
        "Franz_Schubert",
        "This Viennese composer wrote the song Erlkönig and left a famous symphony Unfinished. Name him.",
        "See Viini helilooja kirjutas laulu „Metshaldjas“ ning jättis ühe kuulsa sümfoonia lõpetamata. Nimeta ta.",
        "Franz Schubert",
        "Franz Schubert",
        "Viennese composer Franz Schubert wrote the art song Erlkönig and the work known as the Unfinished Symphony.",
        "Viini helilooja Franz Schubert kirjutas kunstlaulu „Metshaldjas“ ja teose, mida tuntakse „Lõpetamata sümfooniana“.",
        ["Schubert"],
        ["Schubert"],
      ],
      [
        "Johannes_Brahms",
        "Four symphonies and the lively Hungarian Dances point to this German Romantic composer. Name him.",
        "Neli sümfooniat ja särtsakad „Ungari tantsud“ viitavad sellele Saksa romantismiaja heliloojale. Nimeta ta.",
        "Johannes Brahms",
        "Johannes Brahms",
        "German Romantic composer Johannes Brahms wrote four symphonies and the collection of Hungarian Dances.",
        "Saksa romantismiaja helilooja Johannes Brahms kirjutas neli sümfooniat ja kogumiku „Ungari tantsud“.",
        ["Brahms"],
        ["Brahms"],
      ],
      [
        "Felix_Mendelssohn",
        "The Wedding March heard at many ceremonies comes from this German Romantic composer's music for A Midsummer Night's Dream. Name him.",
        "Paljudel pulmatseremooniatel kõlav „Pulmamarss“ pärineb selle Saksa romantismiaja helilooja muusikast näidendile „Suveöö unenägu“. Nimeta ta.",
        "Felix Mendelssohn",
        "Felix Mendelssohn",
        "German Romantic composer Felix Mendelssohn wrote the Wedding March as part of his music for A Midsummer Night's Dream.",
        "Saksa romantismiaja helilooja Felix Mendelssohn kirjutas „Pulmamarsi“ osana oma muusikast näidendile „Suveöö unenägu“.",
        ["Mendelssohn"],
        ["Mendelssohn"],
      ],
    ],
  ],
  [
    120,
    "round-two",
    "rock",
    "Rock Bands of the 1990s and 2000s",
    "1990. ja 2000. aastate rokkbändid",
    [
      [
        "Rammstein",
        "Du hast and spectacular pyrotechnic concerts point to this German industrial-metal band. Name it.",
        "„Du hast“ ja suurejoonelised pürotehnilised kontserdid viitavad sellele Saksa industrial metal'i ansamblile. Nimeta see.",
        "Rammstein",
        "Rammstein",
        "Rammstein is a German industrial-metal band known for Du hast and concert performances featuring extensive pyrotechnics.",
        "Rammstein on Saksa industrial metal'i ansambel, mida tuntakse loo „Du hast“ ja rohke pürotehnikaga kontsertide järgi.",
      ],
      [
        "The_Cardigans",
        "Lovefool and My Favourite Game came from this Swedish rock band fronted by Nina Persson. Name it.",
        "„Lovefool“ ja „My Favourite Game“ pärinevad sellelt Nina Perssoni juhitud Rootsi rokkansamblilt. Nimeta see.",
        "The Cardigans",
        "The Cardigans",
        "The Cardigans are a Swedish rock band fronted by Nina Persson and known for songs including Lovefool and My Favourite Game.",
        "The Cardigans on Nina Perssoni juhitud Rootsi rokkansambel, mida tuntakse muu hulgas lugude „Lovefool“ ja „My Favourite Game“ järgi.",
        ["Cardigans"],
        ["Cardigans"],
      ],
      [
        "Foo_Fighters",
        "Former Nirvana drummer Dave Grohl founded this American rock band. Name it.",
        "Nirvana endine trummar Dave Grohl asutas selle Ameerika rokkansambli. Nimeta see.",
        "Foo Fighters",
        "Foo Fighters",
        "Dave Grohl founded the American rock band Foo Fighters after his time as Nirvana's drummer.",
        "Dave Grohl asutas Ameerika rokkansambli Foo Fighters pärast Nirvana trummarina tegutsemist.",
        ["The Foo Fighters"],
        ["The Foo Fighters"],
      ],
      [
        "Nickelback",
        "How You Remind Me became an international hit for this Canadian rock band fronted by Chad Kroeger. Name the band.",
        "„How You Remind Me“ sai selle Chad Kroegeri juhitud Kanada rokkansambli rahvusvaheliseks hitiks. Nimeta ansambel.",
        "Nickelback",
        "Nickelback",
        "Nickelback are a Canadian rock band fronted by Chad Kroeger whose breakthrough international hit was How You Remind Me.",
        "Nickelback on Chad Kroegeri juhitud Kanada rokkansambel, mille rahvusvaheliseks läbimurdehitiks sai „How You Remind Me“.",
      ],
      [
        "Muse_(band)",
        "Matt Bellamy fronts this British rock trio behind Supermassive Black Hole and Uprising. Name the band.",
        "Matt Bellamy juhib seda Briti rokitriot, mille tuntud lugude hulka kuuluvad „Supermassive Black Hole“ ja „Uprising“. Nimeta ansambel.",
        "Muse",
        "Muse",
        "Muse are a British rock trio fronted by Matt Bellamy and known for songs including Supermassive Black Hole and Uprising.",
        "Muse on Matt Bellamy juhitud Briti rokitrio, mida tuntakse muu hulgas lugude „Supermassive Black Hole“ ja „Uprising“ järgi.",
      ],
    ],
  ],
];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLocaleLowerCase("en")
    .replace(/%[0-9a-f]{2}/giu, "-")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    page,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const subjectKey = `music:${slug(page)}`;
  return {
    clueId: `built-in-music-easy-expansion-${clueNumber}`,
    key: `music-easy-expansion:${categorySetId}:${tier}`,
    factKey: `music-easy-expansion:${slug(page)}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(page).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${page}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    },
  };
}

export const MUSIC_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  MUSIC_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
