import type { EasyExpansionCategory, EasyExpansionQuestion } from "../types";

const BATCH_ID = "07-film-television";
const PACK_ID = "built-in-film-television";
const RETRIEVED_AT = "2026-09-07";

type QuestionSeed = readonly [
  page: string,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const FILM_TELEVISION_EASY_EXPANSION_SEEDS: readonly CategorySeed[] = [
  [
    101,
    "round-one",
    "actors",
    "Comedy Stars on Screen",
    "Ekraanikomöödia tähed",
    [
      [
        "Robin_Williams",
        "This comedian gave the Genie his voice and played the title role in Mrs. Doubtfire. Name the actor.",
        "See koomik andis Džinnile hääle ning mängis peaosa filmis „Meie issi, proua Doubtfire“. Nimeta näitleja.",
        "Robin Williams",
        "Robin Williams",
        "Robin Williams voiced the Genie and starred as Mrs. Doubtfire, two of his familiar family-film roles.",
        "Robin Williams andis Džinnile hääle ning kehastas proua Doubtfire'i; mõlemad on tema tuntud perefilmirollid.",
        [],
        [],
      ],
      [
        "Ben_Stiller",
        "The comedies Zoolander and Night at the Museum both feature this actor in the lead. Name him.",
        "See näitleja mängib peaosa nii komöödias „Zoolander“ kui ka filmis „Öö muuseumis“. Nimeta ta.",
        "Ben Stiller",
        "Ben Stiller",
        "Ben Stiller starred in Zoolander and led the Night at the Museum films.",
        "Ben Stiller mängis peaosa filmis „Zoolander“ ning filmisarjas „Öö muuseumis“.",
        ["Stiller"],
        ["Stiller"],
      ],
      [
        "Steve_Martin",
        "This comedian played Inspector Clouseau in The Pink Panther and the anxious dad in Father of the Bride. Name him.",
        "See koomik kehastas inspektor Clouseau'd filmis „Roosa panter“ ja murelikku isa filmis „Pruudi isa“. Nimeta ta.",
        "Steve Martin",
        "Steve Martin",
        "Steve Martin played Inspector Clouseau in The Pink Panther and the father in the Father of the Bride films.",
        "Steve Martin kehastas inspektor Clouseau'd filmis „Roosa panter“ ning isa filmides „Pruudi isa“.",
        [],
        [],
      ],
      [
        "Melissa_McCarthy",
        "Bridesmaids and the action comedy Spy showcase this American actress's comic talents. Name her.",
        "Komöödia „Pruutneitsid“ ja märulikomöödia „Spioon“ toovad esile selle Ameerika näitlejanna koomikuande. Nimeta ta.",
        "Melissa McCarthy",
        "Melissa McCarthy",
        "Melissa McCarthy appeared in Bridesmaids and starred in the comedy Spy.",
        "Melissa McCarthy mängis komöödias „Pruutneitsid“ ning peaosa filmis „Spioon“.",
        [],
        [],
      ],
      [
        "Will_Ferrell",
        "The Christmas comedy Elf and the newsroom comedy Anchorman have this leading actor in common. Name him.",
        "Jõulukomöödial „Päkapikk“ ja teleuudistest rääkival komöödial „Uudisteankur: Legend Ron Burgundyst“ on sama peaosatäitja. Nimeta ta.",
        "Will Ferrell",
        "Will Ferrell",
        "Will Ferrell starred in both Elf and Anchorman, comedies set around Christmas and television news respectively.",
        "Will Ferrell mängis peaosa nii jõulukomöödias „Päkapikk“ kui ka teleuudistest rääkivas komöödias „Uudisteankur: Legend Ron Burgundyst“.",
        ["Ferrell"],
        ["Ferrell"],
      ],
    ],
  ],
  [
    102,
    "round-one",
    "actors",
    "Action Stars Around the World",
    "Märulitähed kogu maailmast",
    [
      [
        "Jackie_Chan",
        "This Hong Kong star mixes martial arts with slapstick comedy and is famous for performing his own daring stunts. Name him.",
        "See Hongkongi staar ühendab võitluskunstid füüsilise komöödiaga ning on kuulus selle poolest, et teeb oma julged kaskadööritrikid ise. Nimeta ta.",
        "Jackie Chan",
        "Jackie Chan",
        "Jackie Chan is known for acrobatic fighting, comic timing and inventive stunts that he typically performs himself.",
        "Jackie Chan on tuntud akrobaatiliste võitlusstseenide, täpse koomilise ajastuse ja leidlike trikkide poolest, mida ta tavaliselt ise teeb.",
        [],
        [],
      ],
      [
        "Bruce_Willis",
        "This actor became an action-film favourite as John McClane, the hero of Die Hard. Name him.",
        "See näitleja sai märulifilmide lemmikuks, kehastades „Visa hinge“ kangelast John McClane'i. Nimeta ta.",
        "Bruce Willis",
        "Bruce Willis",
        "Bruce Willis played John McClane throughout the Die Hard film series.",
        "Bruce Willis kehastas John McClane'i filmisarjas „Visa hing“.",
        [],
        [],
      ],
      [
        "Sylvester_Stallone",
        "Boxer Rocky Balboa and soldier John Rambo are two signature roles of this action star. Name him.",
        "Poksija Rocky Balboa ja sõdur John Rambo on selle märulistaari kaks kuulsat rolli. Nimeta ta.",
        "Sylvester Stallone",
        "Sylvester Stallone",
        "Sylvester Stallone portrayed the boxer Rocky Balboa and the soldier John Rambo in two successful film series.",
        "Sylvester Stallone kehastas kahes menukas filmisarjas poksija Rocky Balboad ja sõdur John Rambot.",
        ["Stallone"],
        ["Stallone"],
      ],
      [
        "Keanu_Reeves",
        "This actor played both Neo and the title character in the John Wick action films. Name him.",
        "See näitleja kehastas nii Neot kui ka nimitegelast „John Wicki“ märulifilmides. Nimeta ta.",
        "Keanu Reeves",
        "Keanu Reeves",
        "Keanu Reeves is known for playing Neo and for his starring role as John Wick.",
        "Keanu Reeves on tuntud Neo rolli ja John Wicki kehastamise poolest.",
        ["Reeves"],
        ["Reeves"],
      ],
      [
        "Michelle_Yeoh",
        "This Malaysian actress starred in Crouching Tiger, Hidden Dragon and later Everything Everywhere All at Once. Name her.",
        "See Malaisia näitlejanna mängis filmides „Tiiger ja draakon“ ning hiljem „Kõik kõikjal ja korraga“. Nimeta ta.",
        "Michelle Yeoh",
        "Michelle Yeoh",
        "Michelle Yeoh starred in the martial-arts film Crouching Tiger, Hidden Dragon and in Everything Everywhere All at Once.",
        "Michelle Yeoh mängis võitluskunstifilmis „Tiiger ja draakon“ ning filmis „Kõik kõikjal ja korraga“.",
        ["Yeoh"],
        ["Yeoh"],
      ],
    ],
  ],
  [
    103,
    "round-one",
    "animation",
    "Animated Television Friends",
    "Animeeritud telesõbrad",
    [
      [
        "Peppa_Pig",
        "A little pig enjoys everyday adventures with her parents and younger brother George in this preschool cartoon. Name the series.",
        "Väike põrsas seikleb koos vanemate ja noorema venna George'iga selles eelkooliealistele mõeldud multifilmisarjas. Nimeta sari.",
        "Peppa Pig",
        "Põrsas Peppa",
        "Peppa Pig follows a young pig and her family, including her younger brother George.",
        "„Põrsas Peppa“ jälgib väikese põrsa ja tema pere elu; perre kuulub ka noorem vend George.",
        [],
        [],
      ],
      [
        "Masha_and_the_Bear",
        "An energetic little girl repeatedly disrupts the quiet life of her patient bear friend in this animated series. Name it.",
        "Energiline väike tüdruk pöörab selles animasarjas ikka ja jälle kannatliku karu rahuliku elu pea peale. Nimeta sari.",
        "Masha and the Bear",
        "Maša ja karu",
        "Masha and the Bear centres on a lively young girl and the caring bear who looks after her.",
        "„Maša ja karu“ keskmes on elav väike tüdruk ning hoolitsev karu, kes tal silma peal hoiab.",
        ["Masha & the Bear"],
        ["Masha ja karu"],
      ],
      [
        "Paw_Patrol",
        "A boy named Ryder leads a team of rescue pups on missions to help their community in this cartoon. Name the series.",
        "Poiss nimega Ryder juhib selles multifilmisarjas päästekutsikate meeskonda, kes aitab kohalikke elanikke. Nimeta sari.",
        "PAW Patrol",
        "Käpapatrull",
        "PAW Patrol follows Ryder and his team of search-and-rescue dogs as they protect their community.",
        "„Käpapatrull“ jälgib Ryderit ja tema päästekoerte meeskonda, kes kaitseb kohalikke elanikke.",
        [],
        [],
      ],
      [
        "Dora_the_Explorer_(TV_series)",
        "A young explorer and her monkey friend Boots invite viewers to help them on their adventures in this animated series. Name it.",
        "Noor avastaja ja tema ahvist sõber Boots kutsuvad selles animasarjas vaatajaid oma seiklustel appi. Nimeta sari.",
        "Dora the Explorer",
        "Avastaja Dora",
        "Dora the Explorer follows a girl and her monkey friend Boots, with questions that invite the audience to take part.",
        "„Avastaja Dora“ jälgib tüdruku ja tema ahvist sõbra Bootsi seiklusi ning kutsub küsimustega vaatajaid osalema.",
        [],
        [],
      ],
      [
        "Bluey_(TV_series)",
        "An Australian Blue Heeler puppy invents games with her little sister Bingo and their parents in this animated series. Name it.",
        "Austraalia sinine karjakoerakutsikas mõtleb selles animasarjas välja mänge koos oma väikese õe Bingo ja vanematega. Nimeta sari.",
        "Bluey",
        "Bluey",
        "Bluey follows an Australian Blue Heeler puppy and her family, including younger sister Bingo, through imaginative play.",
        "„Bluey“ jälgib Austraalia karjakoerakutsika ja tema pere, sealhulgas noorema õe Bingo fantaasiarikkaid mänge.",
        [],
        [],
      ],
    ],
  ],
  [
    104,
    "round-one",
    "animation",
    "Family Animation After 2000",
    "Pereanimatsioon pärast 2000. aastat",
    [
      [
        "Despicable_Me_(film)",
        "Gru and his yellow Minions plot a spectacular theft, but three orphan girls change his life in this animated film. Name it.",
        "Gru ja tema kollased käsilased plaanivad selles animafilmis suurt vargust, kuid kolm orvuks jäänud tüdrukut muudavad ta elu. Nimeta film.",
        "Despicable Me",
        "Mina, supervaras",
        "Despicable Me follows supervillain Gru, his Minions and the three orphan girls he adopts.",
        "„Mina, supervaras“ jälgib superkurikaela Gru, tema käsilaste ja kolme tüdruku lugu, kelle ta lapsendab.",
        [],
        [],
      ],
      [
        "Kung_Fu_Panda_(film)",
        "Clumsy Po is chosen as the Dragon Warrior and must train in martial arts in this animated film. Name it.",
        "Kohmakas Po valitakse selles animafilmis Draakonisõdalaseks ning ta peab asuma võitluskunste õppima. Nimeta film.",
        "Kung Fu Panda",
        "Kung Fu Panda",
        "Kung Fu Panda follows Po, an unlikely Dragon Warrior who trains to defend his home.",
        "„Kung Fu Panda“ jälgib ootamatult Draakonisõdalaseks valitud Pod, kes treenib oma kodu kaitsmiseks.",
        [],
        [],
      ],
      [
        "Hotel_Transylvania_(film)",
        "Dracula runs a holiday retreat where monsters can relax away from humans in this animated comedy. Name the film.",
        "Dracula peab selles animakomöödias hotelli, kus koletised saavad inimestest eemal puhata. Nimeta film.",
        "Hotel Transylvania",
        "Hotell Transilvaania",
        "Hotel Transylvania centres on Dracula's hotel, intended as a safe retreat for monsters away from humans.",
        "„Hotell Transilvaania“ keskmes on Dracula hotell, mis pakub koletistele turvalist puhkepaika inimestest eemal.",
        [],
        [],
      ],
      [
        "The_Boss_Baby",
        "A boy's new baby brother wears a suit and tie and talks like an adult when their parents are away in this animated comedy. Name it.",
        "Poisi uus pisivend kannab selles animakomöödias ülikonda ja lipsu ning räägib vanemate äraolekul nagu täiskasvanu. Nimeta film.",
        "The Boss Baby",
        "Boss beebi",
        "The Boss Baby introduces a suit-wearing infant who behaves like an adult when his parents are not watching.",
        "„Boss beebi“ tutvustab ülikonda kandvat imikut, kes käitub täiskasvanuna, kui vanemad ei näe.",
        ["Boss Baby"],
        ["The Boss Baby"],
      ],
      [
        "The_Croods",
        "A prehistoric family must leave the safety of its cave and explore an unfamiliar world in this animated adventure. Name the film.",
        "Ürgaja pere peab selles animaseikluses lahkuma oma turvalisest koopast ja avastama tundmatut maailma. Nimeta film.",
        "The Croods",
        "Kruudid",
        "The Croods follows a prehistoric cave-dwelling family forced to travel through a changing world.",
        "„Kruudid“ jälgib koopas elavat ürgaja perekonda, kes on sunnitud asuma teele läbi muutuva maailma.",
        ["Croods"],
        ["The Croods"],
      ],
    ],
  ],
  [
    105,
    "round-one",
    "awards",
    "Oscar-Winning Films Since 1990",
    "Pärast 1990. aastat Oscari võitnud filmid",
    [
      [
        "Oppenheimer_(film)",
        "Cillian Murphy plays the physicist who led the atomic bomb laboratory in this Oscar-winning drama. Name the film.",
        "Cillian Murphy kehastab selles Oscari võitnud draamas füüsikut, kes juhtis aatomipommi loonud laborit. Nimeta film.",
        "Oppenheimer",
        "Oppenheimer",
        "Oppenheimer stars Cillian Murphy as the physicist who led the Los Alamos laboratory; the film won several Oscars.",
        "„Oppenheimeris“ kehastab Cillian Murphy Los Alamose laborit juhtinud füüsikut; film võitis mitu Oscarit.",
        [],
        [],
      ],
      [
        "The_Incredibles",
        "A family hiding its superpowers returns to superhero action in this Oscar-winning animated film. Name it.",
        "Oma supervõimeid varjanud perekond asub selles Oscari võitnud animafilmis taas superkangelastena tegutsema. Nimeta film.",
        "The Incredibles",
        "Imelised",
        "The Incredibles follows a superhero family drawn back into action and won Oscars for animated feature and sound editing.",
        "„Imelised“ räägib taas tegutsema asuvast superkangelaste perest ning võitis animafilmi ja helimontaaži Oscari.",
        ["Incredibles"],
        ["The Incredibles"],
      ],
      [
        "Zootopia",
        "A rabbit police officer teams up with a fox to investigate missing animals in this Oscar-winning animated film. Name it.",
        "Jänesest politseinik ühendab selles Oscari võitnud animafilmis jõud rebasega, et uurida loomade kadumist. Nimeta film.",
        "Zootopia",
        "Zootropolis",
        "Zootopia pairs rabbit officer Judy Hopps with fox Nick Wilde in a missing-animals investigation and won the animated-feature Oscar.",
        "„Zootropolises“ uurivad jänesest politseinik Judy Hopps ja rebane Nick Wilde loomade kadumist; film võitis animafilmi Oscari.",
        ["Zootropolis"],
        ["Zootopia"],
      ],
      [
        "12_Years_a_Slave_(film)",
        "Free-born Solomon Northup is kidnapped and forced into slavery in this Oscar-winning historical drama. Name the film.",
        "Vabana sündinud Solomon Northup röövitakse ja orjastatakse selles Oscari võitnud ajaloolises draamas. Nimeta film.",
        "12 Years a Slave",
        "12 aastat orjana",
        "12 Years a Slave depicts Solomon Northup's kidnapping and enslavement and won the Oscar for best picture.",
        "„12 aastat orjana“ kujutab Solomon Northupi röövimist ja orjapõlve ning võitis parima filmi Oscari.",
        ["Twelve Years a Slave"],
        ["Kaksteist aastat orjana"],
      ],
      [
        "Encanto",
        "The Madrigal family's magical gifts begin to fade, and Mirabel tries to save them in this Oscar-winning animated film. Name it.",
        "Madrigali pere võluvõimed hakkavad kaduma ning Mirabel püüab neid päästa selles Oscari võitnud animafilmis. Nimeta film.",
        "Encanto",
        "Encanto",
        "Encanto follows Mirabel's efforts to save the Madrigal family's magic and won the Oscar for best animated feature.",
        "„Encanto“ jälgib Mirabeli püüdlusi päästa Madrigali pere maagia ning võitis parima animafilmi Oscari.",
        [],
        [],
      ],
    ],
  ],
  [
    106,
    "round-one",
    "directors",
    "Popular Films Directed by Women",
    "Naiste lavastatud tuntud filmid",
    [
      [
        "Captain_Marvel_(film)",
        "Anna Boden co-directed this film in which Carol Danvers discovers her past and becomes a cosmic superhero. Name the film.",
        "Anna Boden on selle filmi kaaslavastaja; loos avastab Carol Danvers oma mineviku ja saab kosmiliseks superkangelaseks. Nimeta film.",
        "Captain Marvel",
        "Kapten Marvel",
        "Captain Marvel was co-directed by Anna Boden and Ryan Fleck and follows Carol Danvers's path to becoming a superhero.",
        "„Kapten Marveli“ lavastasid koos Anna Boden ja Ryan Fleck ning film jälgib Carol Danversi kujunemist superkangelaseks.",
        [],
        [],
      ],
      [
        "What_Women_Want",
        "Nancy Meyers directed this comedy about a man who suddenly gains the ability to hear women's thoughts. Name it.",
        "Nancy Meyers lavastas selle komöödia mehest, kes saab ootamatult võime kuulda naiste mõtteid. Nimeta film.",
        "What Women Want",
        "Mida naised tahavad",
        "Nancy Meyers directed What Women Want, in which a man discovers that he can hear what women are thinking.",
        "Nancy Meyers lavastas filmi „Mida naised tahavad“, milles mees avastab, et kuuleb naiste mõtteid.",
        [],
        [],
      ],
      [
        "Sleepless_in_Seattle",
        "Nora Ephron directed this romance in which a boy's radio call about his widowed father catches a woman's attention far away. Name the film.",
        "Nora Ephron lavastas selle armastusfilmi, kus poiss räägib raadiosaates telefonitsi oma lesestunud isast ning köidab kaugel elava naise tähelepanu. Nimeta film.",
        "Sleepless in Seattle",
        "Unetus Seattle'is",
        "Nora Ephron's Sleepless in Seattle brings two strangers together after a boy calls a radio show seeking a new wife for his father.",
        "Nora Ephroni lavastatud „Unetus Seattle'is“ viib kokku kaks võõrast pärast seda, kui poiss otsib raadio kaudu oma isale uut naist.",
        [],
        [],
      ],
      [
        "Point_Break",
        "Kathryn Bigelow directed this action film in which an FBI agent joins a surfing community while investigating bank robbers. Name it.",
        "Kathryn Bigelow lavastas selle märulifilmi, kus FBI agent sulandub pangaröövleid otsides surfajate seltskonda. Nimeta film.",
        "Point Break",
        "Murdepunkt",
        "Kathryn Bigelow directed Point Break, whose undercover FBI agent investigates suspected bank robbers among surfers.",
        "Kathryn Bigelow lavastas „Murdepunkti“, kus varjatult tegutsev FBI agent otsib surfajate seast kahtlustatavaid pangaröövleid.",
        [],
        [],
      ],
      [
        "A_League_of_Their_Own",
        "Penny Marshall directed this film about women playing in a new professional baseball league while the men are away at war. Name it.",
        "Penny Marshall lavastas selle filmi naistest, kes mängivad meeste sõjas viibimise ajal uues profipesapalliliigas. Nimeta film.",
        "A League of Their Own",
        "Naised palliplatsil",
        "Penny Marshall directed A League of Their Own, a story set in the women's professional baseball league formed during the war.",
        "Penny Marshall lavastas filmi „Naised palliplatsil“, mille tegevus toimub sõja ajal loodud naiste profipesapalliliigas.",
        [],
        [],
      ],
    ],
  ],
  [
    107,
    "round-one",
    "directors",
    "Stars Who Also Direct",
    "Staarid, kes ka lavastavad",
    [
      [
        "Clint_Eastwood",
        "The star of Dirty Harry also directed the Western Unforgiven. Name this actor and filmmaker.",
        "Filmi „Räpane Harry“ peaosatäitja lavastas ka vesterni „Armutu“. Nimeta näitleja ja filmilavastaja.",
        "Clint Eastwood",
        "Clint Eastwood",
        "Clint Eastwood starred as Dirty Harry and directed the Western Unforgiven.",
        "Clint Eastwood mängis peaosa filmis „Räpane Harry“ ning lavastas vesterni „Armutu“.",
        ["Eastwood"],
        ["Eastwood"],
      ],
      [
        "Angelina_Jolie",
        "This actress played Lara Croft and later directed the wartime survival drama Unbroken. Name her.",
        "See näitlejanna kehastas Lara Crofti ning lavastas hiljem sõjaaegsest ellujäämisest rääkiva draama „Murdumatu“. Nimeta ta.",
        "Angelina Jolie",
        "Angelina Jolie",
        "Angelina Jolie starred as Lara Croft and directed the war drama Unbroken.",
        "Angelina Jolie kehastas Lara Crofti ning lavastas sõjadraama „Murdumatu“.",
        ["Jolie"],
        ["Jolie"],
      ],
      [
        "Ben_Affleck",
        "This Batman actor also directed and starred in the thriller Argo. Name him.",
        "See Batmani kehastanud näitleja lavastas põneviku „Argo“ ja mängis selles peaosa. Nimeta ta.",
        "Ben Affleck",
        "Ben Affleck",
        "Ben Affleck played Batman and both directed and starred in Argo.",
        "Ben Affleck kehastas Batmani ning oli nii „Argo“ lavastaja kui ka peaosatäitja.",
        ["Affleck"],
        ["Affleck"],
      ],
      [
        "George_Clooney",
        "This Ocean's Eleven star also directed the newsroom drama Good Night, and Good Luck. Name him.",
        "Filmi „Oceani 11 – kõrged panused“ staar lavastas ka teleajakirjandusest rääkiva draama „Head õhtut ja õnn kaasa“. Nimeta ta.",
        "George Clooney",
        "George Clooney",
        "George Clooney starred in Ocean's Eleven and directed Good Night, and Good Luck.",
        "George Clooney mängis filmis „Oceani 11 – kõrged panused“ ning lavastas filmi „Head õhtut ja õnn kaasa“.",
        ["Clooney"],
        ["Clooney"],
      ],
      [
        "Robert_Redford",
        "One of the stars of The Sting went on to direct the family drama Ordinary People. Name this actor and director.",
        "Üks filmi „Tüssamine“ staare lavastas hiljem peredraama „Tavalised inimesed“. Nimeta näitleja ja lavastaja.",
        "Robert Redford",
        "Robert Redford",
        "Robert Redford starred in The Sting and made his directing debut with the family drama Ordinary People.",
        "Robert Redford mängis filmis „Tüssamine“ ning tegi lavastajadebüüdi peredraamaga „Tavalised inimesed“.",
        ["Redford"],
        ["Redford"],
      ],
    ],
  ],
  [
    108,
    "round-one",
    "genres",
    "Movie Musicals",
    "Filmimuusikalid",
    [
      [
        "My_Fair_Lady_(film)",
        "Flower seller Eliza Doolittle learns to speak like a society lady in this film musical. Name it.",
        "Lillemüüja Eliza Doolittle õpib selles filmimuusikalis kõnelema nagu kõrgseltskonna daam. Nimeta film.",
        "My Fair Lady",
        "Minu veetlev leedi",
        "My Fair Lady follows Eliza Doolittle as a professor teaches her the speech needed to pass as a society lady.",
        "„Minu veetlev leedi“ jälgib Eliza Doolittle'it, kellele professor õpetab kõrgseltskonna daamina esinemiseks vajalikku kõneviisi.",
        [],
        [],
      ],
      [
        "Singin%27_in_the_Rain",
        "Hollywood performers struggle with the move from silent films to sound in this musical starring Gene Kelly. Name the film.",
        "Hollywoodi esinejad peavad selles Gene Kellyga muusikalis kohanema üleminekuga tummfilmilt helifilmile. Nimeta film.",
        "Singin' in the Rain",
        "Lauldes vihmas",
        "Singin' in the Rain stars Gene Kelly in a story about Hollywood's transition from silent films to sound.",
        "Gene Kelly mängib filmis „Lauldes vihmas“, mille lugu kujutab Hollywoodi üleminekut tummfilmilt helifilmile.",
        ["Singing in the Rain"],
        ["Singin' in the Rain"],
      ],
      [
        "The_Muppets_(2011_film)",
        "Kermit reunites his old puppet troupe to save their theatre from an oil magnate in this musical comedy. Name the film.",
        "Selles muusikakomöödias kutsub Kermit oma vana nukutrupi taas kokku, et päästa nende teater naftamagnaadi käest. Nimeta film.",
        "The Muppets",
        "Muppetid",
        "The Muppets is a musical comedy in which Kermit reunites his old puppet troupe to save their theatre from an oil magnate.",
        "„Muppetid“ on muusikakomöödia, kus Kermit kutsub oma vana nukutrupi taas kokku, et päästa nende teater naftamagnaadi käest.",
        [],
        [],
      ],
      [
        "Footloose",
        "A teenager moves to a town that has banned dancing and helps the local young people challenge the rule in this film. Name it.",
        "Teismeline kolib selles filmis linna, kus tantsimine on keelatud, ja aitab kohalikel noortel keelu vastu astuda. Nimeta film.",
        "Footloose",
        "Footloose",
        "Footloose follows a teenage newcomer who challenges a small town's ban on dancing.",
        "„Footloose“ jälgib väikelinna kolinud teismelist, kes astub kohaliku tantsukeelu vastu.",
        [],
        [],
      ],
      [
        "Pitch_Perfect",
        "A university's all-female singing group competes using only their voices, without instruments, in this musical comedy. Name it.",
        "Ülikooli naistest koosnev laulurühm võistleb selles muusikakomöödias ainult oma hääli kasutades, ilma pillisaateta. Nimeta film.",
        "Pitch Perfect",
        "Lauluässad",
        "Pitch Perfect follows an all-female university a cappella group competing against other student singing groups.",
        "„Lauluässad“ jälgib ülikooli naiste a cappella rühma, kes võistleb teiste tudengite laulurühmadega.",
        [],
        [],
      ],
    ],
  ],
  [
    109,
    "round-one",
    "genres",
    "Big-Screen Adventures",
    "Seiklusfilmid suurel ekraanil",
    [
      [
        "King_Kong_(1933_film)",
        "A giant ape is captured on Skull Island and brought to New York in this classic adventure film. Name it.",
        "Hiiglaslik inimahv püütakse selles klassikalises seiklusfilmis kinni Pealuusaarel ja tuuakse New Yorki. Nimeta film.",
        "King Kong",
        "King Kong",
        "King Kong tells of a giant ape taken from an isolated island to New York, where his captors put him on display.",
        "„King Kong“ räägib hiiglaslikust inimahvist, kes viiakse üksikult saarelt New Yorki, kus vangistajad teda rahvale näitavad.",
        [],
        [],
      ],
      [
        "The_Mask_of_Zorro",
        "An ageing masked swordsman trains a younger successor to fight injustice in California in this swashbuckling film. Name it.",
        "Vananev maskiga mõõgavõitleja õpetab selles seiklusfilmis nooremat järeltulijat Californias ebaõigluse vastu võitlema. Nimeta film.",
        "The Mask of Zorro",
        "Zorro mask",
        "The Mask of Zorro follows an older masked hero training his successor to oppose a corrupt ruler in California.",
        "„Zorro mask“ jälgib vanemat maskiga kangelast, kes õpetab oma järeltulijat California korrumpeerunud valitsejale vastu astuma.",
        ["Mask of Zorro"],
        ["The Mask of Zorro"],
      ],
      [
        "The_Adventures_of_Tintin_(film)",
        "A model of a ship called the Unicorn starts a search for lost treasure in this animated film. Name it.",
        "Ükssarvik-nimelise laeva mudel käivitab selles animafilmis kadunud aarde otsingu. Nimeta film.",
        "The Adventures of Tintin",
        "Tintini seiklused",
        "The Adventures of Tintin begins with the reporter buying a model ship, which leads him and Snowy into a hunt for lost treasure.",
        "„Tintini seiklustes“ ostab reporter laevamudeli, mis viib ta koos koer Milouga kadunud aarde otsinguile.",
        ["Adventures of Tintin"],
        ["The Adventures of Tintin"],
      ],
      [
        "Crocodile_Dundee",
        "An Australian bushman visits New York and finds city life very different from the outback in this comedy adventure. Name the film.",
        "Austraalia looduses karastunud mees külastab selles seikluskomöödias New Yorki ning avastab, et linnaelu erineb kõvasti kodusest elust. Nimeta film.",
        "Crocodile Dundee",
        "Krokodill Dundee",
        "Crocodile Dundee brings an Australian bushman to New York, where he has to navigate unfamiliar urban customs.",
        "„Krokodill Dundee“ toob Austraalia looduses kasvanud mehe New Yorki, kus ta peab harjuma võõraste linnakommetega.",
        [],
        [],
      ],
      [
        "George_of_the_Jungle_(film)",
        "A man raised by apes leaves the jungle for San Francisco, where his vine-swinging skills come in handy in this comedy. Name the film.",
        "Ahvide kasvatatud mees lahkub selles komöödias džunglist San Franciscosse, kus tema liaanidel kiikumise oskus kulub marjaks ära. Nimeta film.",
        "George of the Jungle",
        "Džungli George",
        "George of the Jungle follows an ape-raised man to San Francisco, where he uses his swinging skills to rescue a man whose paraglider is caught on the Bay Bridge.",
        "„Džungli George“ viib ahvide kasvatatud mehe San Franciscosse, kus ta kasutab oma kiikumisoskust, et päästa mees, kelle paraglaider on Bay Bridge’i trossidesse takerdunud.",
        [],
        [],
      ],
    ],
  ],
  [
    110,
    "round-one",
    "genres",
    "Disaster and Survival Films",
    "Katastroofi- ja ellujäämisfilmid",
    [
      [
        "I_Am_Legend_(film)",
        "In this film, Will Smith plays a man immune to a deadly virus who survives in an almost empty New York. Name it.",
        "Selles filmis kehastab Will Smith surmava viiruse suhtes immuunset meest, kes elab peaaegu inimtühjas New Yorgis. Nimeta film.",
        "I Am Legend",
        "Ma olen legend",
        "I Am Legend stars Will Smith as a virus-immune survivor trying to find a cure in a devastated New York.",
        "Filmis „Ma olen legend“ kehastab Will Smith viiruse suhtes immuunset ellujäänut, kes otsib laastatud New Yorgis ravi.",
        [],
        [],
      ],
      [
        "World_War_Z_(film)",
        "A former investigator played by Brad Pitt races around the world seeking a way to stop a zombie pandemic in this film. Name it.",
        "Brad Pitti kehastatud endine uurija ruttab selles filmis mööda maailma, otsides võimalust peatada zombipandeemia. Nimeta film.",
        "World War Z",
        "Z maailmasõda",
        "World War Z follows Brad Pitt's former investigator as he travels in search of a solution to a zombie pandemic.",
        "„Z maailmasõda“ jälgib Brad Pitti kehastatud endist uurijat, kes reisib zombipandeemiale lahendust otsides.",
        [],
        [],
      ],
      [
        "Deepwater_Horizon_(film)",
        "Workers fight to escape a burning offshore oil rig in this disaster film starring Mark Wahlberg. Name it.",
        "Töölised püüavad selles Mark Wahlbergiga katastroofifilmis pääseda põlevalt merel asuvalt naftaplatvormilt. Nimeta film.",
        "Deepwater Horizon",
        "Deepwater Horizoni katastroof",
        "Deepwater Horizon dramatises an offshore oil-rig explosion and the workers' struggle to escape the fire.",
        "„Deepwater Horizoni katastroof“ kujutab merel asuva naftaplatvormi plahvatust ja tööliste püüdlusi põlengust pääseda.",
        [],
        [],
      ],
      [
        "Don%27t_Look_Up",
        "Two astronomers struggle to make people take seriously a comet heading straight for Earth in this satirical disaster film. Name it.",
        "Kaks astronoomi püüavad selles satiirilises katastroofifilmis panna inimesi tõsiselt võtma otse Maa poole liikuvat komeeti. Nimeta film.",
        "Don't Look Up",
        "Ära vaata üles",
        "Don't Look Up follows two astronomers whose warnings about a civilisation-destroying comet meet public indifference.",
        "„Ära vaata üles“ jälgib kaht astronoomi, kelle hoiatused tsivilisatsiooni hävitava komeedi eest põrkuvad avalikkuse ükskõiksusega.",
        [],
        [],
      ],
      [
        "A_Quiet_Place",
        "A family must live in silence because the creatures hunting them locate prey by sound in this survival thriller. Name the film.",
        "Perekond peab selles ellujäämispõnevikus elama vaikuses, sest neid jahtivad olendid leiavad saagi heli järgi. Nimeta film.",
        "A Quiet Place",
        "Kena vaikne kohake",
        "A Quiet Place follows a family trying to survive creatures that hunt by sound, forcing them to stay quiet.",
        "„Kena vaikne kohake“ jälgib perekonda, kes püüab ellu jääda heli järgi jahtivate olendite keskel ning peab seetõttu vaikima.",
        [],
        [],
      ],
    ],
  ],
  [
    111,
    "round-two",
    "production-craft",
    "Ways the Screen Image Changes",
    "Kuidas ekraanipilt muutub",
    [
      [
        "Slow_motion",
        "A leap that took a moment stretches out on screen, letting viewers follow every movement. Name this effect that shows action more slowly than it happened.",
        "Hetkega tehtud hüpe venib ekraanil pikemaks, nii et vaataja jõuab jälgida iga liigutust. Nimeta võte, mis näitab tegevust tegelikust aeglasemalt.",
        "slow motion",
        "aegluup",
        "Slow motion makes recorded action appear slower than it occurred in real time.",
        "Aegluup näitab salvestatud tegevust aeglasemalt, kui see tegelikult toimus.",
        ["slow-mo", "slo-mo"],
        ["slow motion", "aeglustatud võte"],
      ],
      [
        "Credits",
        "The story is over, but the screen lists the actors and the people who made the film. Name these end-of-film acknowledgements.",
        "Lugu on lõppenud, kuid ekraanile ilmuvad näitlejate ja teiste filmitegijate nimed. Kuidas neid filmi lõpus näidatavaid nimesid nimetatakse?",
        "closing credits",
        "lõputiitrid",
        "Closing credits appear at the end of a film or programme and acknowledge its cast and crew.",
        "Lõputiitrid ilmuvad filmi või saate lõpus ning nimetavad selles osalenud näitlejaid ja teisi tegijaid.",
        ["end credits"],
        ["closing credits"],
      ],
      [
        "Freeze-frame_shot",
        "The action suddenly stops on one image, held on screen like a photograph. Name this film effect.",
        "Tegevus peatub äkki ühel pildil, mis jääb ekraanile nagu foto. Nimeta see filmivõte.",
        "freeze-frame",
        "stoppkaader",
        "A freeze-frame repeats a single frame so that the moving image becomes a still picture.",
        "Stoppkaadri puhul korratakse üht kaadrit, nii et liikuv pilt muutub liikumatuks.",
        ["freeze-frame shot"],
        ["freeze-frame"],
      ],
      [
        "Time-lapse_photography",
        "A plant seems to grow in seconds because photographs taken far apart in time are played in quick succession. Name this filming technique.",
        "Taim näib kasvavat mõne sekundiga, sest pikkade ajavahedega tehtud fotod esitatakse kiiresti üksteise järel. Nimeta see võttetehnika.",
        "time-lapse",
        "intervallvõte",
        "Time-lapse photography records images at intervals and plays them faster, making slow changes such as plant growth visible in a short sequence.",
        "Intervallvõttega salvestatakse pilte ajavahemike järel ja esitatakse neid kiiremini, nii et aeglane muutus, näiteks taime kasvamine, mahub lühikesse lõiku.",
        ["time-lapse photography"],
        ["time-lapse"],
      ],
      [
        "Split_screen_effect",
        "Two scenes appear at once, each occupying a separate part of the same picture. Name this way of dividing the screen.",
        "Kaks stseeni on korraga nähtaval, kumbki sama pildi eri osas. Kuidas sellist ekraani jaotamist nimetatakse?",
        "split screen",
        "jagatud ekraan",
        "Split screen divides the picture into separate areas so that more than one image can be shown simultaneously.",
        "Jagatud ekraani puhul on pilt jaotatud eraldi aladeks, et näidata mitut kujutist korraga.",
      ],
    ],
  ],
  [
    112,
    "round-two",
    "production-craft",
    "Words, Voices and Plans for the Screen",
    "Sõnad, hääled ja ekraaniplaanid",
    [
      [
        "Dubbing",
        "A foreign film's original dialogue is replaced with newly recorded speech in the audience's language. Name this process.",
        "Võõrkeelse filmi algne dialoog asendatakse vaatajate keeles salvestatud kõnega. Kuidas seda protsessi nimetatakse?",
        "dubbing",
        "dubleerimine",
        "Dubbing can replace a film's original dialogue with a recorded translation spoken in another language.",
        "Dubleerimisel saab filmi algse dialoogi asendada teises keeles sisse loetud tõlkega.",
      ],
      [
        "Voice_acting",
        "An animated character speaks and laughs thanks to a performer heard on the soundtrack but not seen on camera. Name this performer's profession.",
        "Animategelane räägib ja naerab tänu esitajale, keda on kuulda, kuid keda kaamera ees ei näe. Nimeta selle esitaja amet.",
        "a voice actor",
        "häälnäitleja",
        "A voice actor performs characters using the voice, including animated characters whose performer does not appear on screen.",
        "Häälnäitleja kehastab tegelasi hääle abil, sealhulgas animategelasi, kelle esitaja ise ekraanile ei ilmu.",
        ["voice actor", "voice actress"],
        ["voice actor", "häälnäitlejanna"],
      ],
      [
        "Teleprompter",
        "A television presenter reads a prepared script while seeming to look straight into the camera. Name the device that displays the words near the lens.",
        "Telesaatejuht loeb ettevalmistatud teksti, vaadates näiliselt otse kaamerasse. Nimeta seade, mis kuvab sõnu objektiivi juures.",
        "a teleprompter",
        "teleprompter",
        "A teleprompter displays a script at the camera lens so a presenter can read while looking toward the audience.",
        "Teleprompter kuvab teksti kaamera objektiivi juures, nii et saatejuht saab lugeda vaatajate poole vaadates.",
        ["teleprompter", "autocue"],
        ["autocue", "prompter"],
      ],
      [
        "Audio_description",
        "An extra narrator explains the action and other visual details so blind viewers can follow a film. Name this accessibility service.",
        "Lisajutustaja selgitab tegevust ja muid pildil nähtavaid üksikasju, et pimedad vaatajad saaksid filmi jälgida. Nimeta see ligipääsetavust toetav teenus.",
        "audio description",
        "kirjeldustõlge",
        "Audio description adds spoken information about important visual elements for blind and visually impaired viewers.",
        "Kirjeldustõlge lisab pimedatele ja vaegnägijatele suulist teavet oluliste visuaalsete elementide kohta.",
      ],
      [
        "Storyboard",
        "Before filming, a sequence of drawings shows how the planned shots will tell the story. Name this illustrated plan.",
        "Enne filmimist näitab joonistuste jada, kuidas kavandatud kaadrid loo edasi annavad. Nimeta see pildiline plaan.",
        "a storyboard",
        "piltstsenaarium",
        "A storyboard arranges illustrations in sequence to visualise a film or other screen work before it is made.",
        "Piltstsenaarium seab joonistused järjestusse, et kujutada filmi või muud ekraaniteost enne selle valmimist.",
        ["storyboard"],
        ["storyboard"],
      ],
    ],
  ],
  [
    113,
    "round-two",
    "screen-adaptations",
    "Video Games on the Big Screen",
    "Videomängud suurel ekraanil",
    [
      [
        "Gran_Turismo_(film)",
        "A teenage racing-game player wins a competition that puts him behind the wheel of a real Nissan race car. Name this film based on a driving simulator.",
        "Teismeline võidusõidumängu mängija võidab võistluse, mis viib ta päris Nissani võidusõiduauto rooli. Nimeta see sõidusimulaatoril põhinev film.",
        "Gran Turismo",
        "Gran Turismo",
        "Gran Turismo dramatises Jann Mardenborough's route from playing a racing simulator to winning a place as a real racing driver through Nissan's competition.",
        "„Gran Turismo“ jutustab dramatiseeritud loo sellest, kuidas Jann Mardenborough sai sõidusimulaatori mängijast Nissani võistluse kaudu päris võidusõitjaks.",
      ],
      [
        "Detective_Pikachu_(film)",
        "A talking yellow Pokémon teams up with Tim Goodman to investigate his father's disappearance. Name this live-action film adapted from a detective video game.",
        "Rääkiv kollane Pokémon asub koos Tim Goodmaniga uurima tema isa kadumist. Nimeta see detektiivivideomängu põhjal valminud mängufilm.",
        "Detective Pikachu",
        "Pokémon: detektiiv Pikachu",
        "Detective Pikachu adapts the video game and follows Pikachu and Tim Goodman as they investigate the disappearance of Tim's father.",
        "Videomängul põhinevas filmis „Pokémon: detektiiv Pikachu“ uurivad Pikachu ja Tim Goodman Timi isa kadumist.",
        ["Pokémon Detective Pikachu"],
        ["detektiiv Pikachu"],
      ],
      [
        "Resident_Evil_(2002_film)",
        "A virus escapes inside an underground laboratory, and Alice faces zombies while a team tries to contain the outbreak. Name this video-game adaptation.",
        "Maa-aluses laboris pääseb valla viirus ning Alice seisab silmitsi zombidega, samal ajal kui eriüksus püüab puhangut peatada. Nimeta see videomängu ekraniseering.",
        "Resident Evil",
        "Resident Evil",
        "Resident Evil is based on the game series and follows Alice and commandos confronting a virus outbreak and zombies in an underground research facility.",
        "Mängusarjal põhinevas filmis „Resident Evil“ seisavad Alice ja eriüksus maa-aluses uurimiskeskuses silmitsi viirusepuhangu ja zombidega.",
      ],
      [
        "Prince_of_Persia:_The_Sands_of_Time_(film)",
        "Dastan and Tamina try to protect a dagger that can turn time back. Name this fantasy adventure adapted from a video game.",
        "Dastan ja Tamina püüavad kaitsta pistoda, mis suudab aega tagasi pöörata. Nimeta see videomängul põhinev fantaasiaseiklus.",
        "Prince of Persia: The Sands of Time",
        "Pärsia prints: ajaliivad",
        "Prince of Persia: The Sands of Time adapts the game and centres on Dastan, Tamina and a magical dagger capable of reversing time.",
        "Videomängu ekraniseeringu „Pärsia prints: ajaliivad“ keskmes on Dastan, Tamina ja maagiline pistoda, mis suudab aega tagasi pöörata.",
        ["Prince of Persia"],
        ["Pärsia prints"],
      ],
      [
        "Five_Nights_at_Freddy%27s_(film)",
        "A new night guard at an abandoned pizza restaurant discovers that its mechanical animal mascots are a deadly threat. Name this horror film based on a video-game series.",
        "Mahajäetud pitsarestorani uus öövalvur avastab, et sealsed mehaanilised loomamaskotid kujutavad endast surmaohtu. Nimeta see videomängusarjal põhinev õudusfilm.",
        "Five Nights at Freddy's",
        "Viis ööd Freddy baaris",
        "Five Nights at Freddy's adapts the game series into a film about a security guard and possessed mechanical mascots at an abandoned pizzeria.",
        "„Viis ööd Freddy baaris“ on videomängusarja ekraniseering, mis räägib turvamehest ja mahajäetud pitsarestorani vaimude vallatud mehaanilistest maskottidest.",
        ["FNAF"],
        ["Five Nights at Freddy's"],
      ],
    ],
  ],
  [
    114,
    "round-two",
    "screen-adaptations",
    "Books That Became Familiar Films",
    "Raamatud, millest said tuntud filmid",
    [
      [
        "Fight_Club",
        "An office worker with insomnia meets soap salesman Tyler Durden, and the two organise secret bare-knuckle bouts. Name this film adapted from Chuck Palahniuk's novel.",
        "Unetuse all kannatav kontoritöötaja kohtub seebimüüja Tyler Durdeniga ning nad hakkavad korraldama salajasi paljakäsi võitlusi. Nimeta see Chuck Palahniuki romaani ekraniseering.",
        "Fight Club",
        "Kaklusklubi",
        "Fight Club adapts Chuck Palahniuk's novel about an insomniac narrator who starts an underground fighting group with Tyler Durden.",
        "„Kaklusklubi“ ekraniseerib Chuck Palahniuki romaani unetust jutustajast, kes loob koos Tyler Durdeniga salajase võitlusgrupi.",
      ],
      [
        "The_Green_Mile_(film)",
        "A prison guard meets John Coffey, a gentle inmate with an extraordinary healing gift. Name this film adapted from a Stephen King novel.",
        "Vangivalvur kohtub John Coffeyga, leebe vangiga, kellel on erakordne tervendamisvõime. Nimeta see Stephen Kingi romaani ekraniseering.",
        "The Green Mile",
        "Roheline miil",
        "The Green Mile is based on Stephen King's novel and follows prison guard Paul Edgecomb as he discovers John Coffey's healing powers.",
        "Stephen Kingi romaanil põhinev „Roheline miil“ jälgib vangivalvur Paul Edgecombi, kes avastab John Coffey tervendamisvõime.",
      ],
      [
        "The_Da_Vinci_Code_(film)",
        "Robert Langdon and Sophie Neveu follow clues hidden in famous works of art after a mystery begins at the Louvre. Name this film adapted from Dan Brown's novel.",
        "Pärast Louvre'is toimunud mõrva asuvad Robert Langdon ja Sophie Neveu järgima kuulsatesse kunstiteostesse peidetud vihjeid. Nimeta see Dan Browni romaani ekraniseering.",
        "The Da Vinci Code",
        "Da Vinci kood",
        "The Da Vinci Code adapts Dan Brown's novel, with Langdon and Neveu following an art-linked mystery that begins at the Louvre.",
        "Dan Browni romaani ekraniseeringus „Da Vinci kood“ lahendavad Langdon ja Neveu kunstiga seotud mõistatust, mis saab alguse Louvre'is.",
      ],
      [
        "One_Flew_Over_the_Cuckoo%27s_Nest_(film)",
        "In a psychiatric hospital, the rebellious McMurphy challenges the strict control of Nurse Ratched. Name this film based on Ken Kesey's novel.",
        "Psühhiaatriahaiglas astub mässumeelne McMurphy vastu õde Ratchedi rangele võimule. Nimeta see Ken Kesey romaanil põhinev film.",
        "One Flew Over the Cuckoo's Nest",
        "Lendas üle käopesa",
        "One Flew Over the Cuckoo's Nest adapts Ken Kesey's novel and centres on McMurphy's conflict with Nurse Ratched in a psychiatric hospital.",
        "Ken Kesey romaani ekraniseeringu „Lendas üle käopesa“ keskmes on McMurphy konflikt õde Ratchediga psühhiaatriahaiglas.",
      ],
      [
        "The_Curious_Case_of_Benjamin_Button_(film)",
        "A man is born with the body of an old person and grows physically younger as the years pass. Name this film adapted from an F. Scott Fitzgerald story.",
        "Mees sünnib vana inimese kehaga ja muutub aastate möödudes kehaliselt nooremaks. Nimeta see F. Scott Fitzgeraldi jutustuse põhjal valminud film.",
        "The Curious Case of Benjamin Button",
        "Benjamin Buttoni uskumatu elu",
        "The Curious Case of Benjamin Button is adapted from Fitzgerald's short story and follows a man who ages in reverse.",
        "Fitzgeraldi lühijutul põhinev „Benjamin Buttoni uskumatu elu“ jälgib meest, kes vananeb tagurpidi.",
        ["Benjamin Button"],
        ["Benjamin Button"],
      ],
    ],
  ],
  [
    115,
    "round-two",
    "series",
    "Streaming-Era Series",
    "Voogedastusajastu sarjad",
    [
      [
        "Squid_Game",
        "People in deep debt enter a secret contest for a huge cash prize, but losing its children's games means death. Name this South Korean series.",
        "Suurtes võlgades inimesed osalevad salajasel võistlusel hiiglasliku rahalise auhinna nimel, kuid sealsetes lastemängudes kaotamine tähendab surma. Nimeta see Lõuna-Korea sari.",
        "Squid Game",
        "Kalmaarimäng",
        "Squid Game follows financially desperate contestants playing deadly versions of children's games for a large cash prize.",
        "„Kalmaarimäng“ jälgib rahahädas võistlejaid, kes mängivad suure rahalise auhinna nimel lastemängude surmavaid versioone.",
      ],
      [
        "The_Queen%27s_Gambit_(miniseries)",
        "Orphan Beth Harmon discovers a talent for chess and rises toward the top of the competitive game. Name this miniseries.",
        "Orvuks jäänud Beth Harmon avastab oma maleande ja tõuseb võistlusmale tippu. Nimeta see minisari.",
        "The Queen's Gambit",
        "Lipugambiit",
        "The Queen's Gambit follows Beth Harmon from her childhood in an orphanage to her rise as a chess prodigy.",
        "„Lipugambiit“ jälgib Beth Harmoni teekonda lastekodulapsest erakordselt andekaks maletajaks.",
      ],
      [
        "The_Mandalorian",
        "An armoured bounty hunter travels through the galaxy protecting the small, green child Grogu. Name this streaming series.",
        "Soomusrüüs pearahakütt rändab mööda galaktikat, kaitstes väikest rohelist last Grogut. Nimeta see voogedastussari.",
        "The Mandalorian",
        "Mandaloorlane",
        "The Mandalorian follows a bounty hunter who becomes the protector of the child Grogu.",
        "„Mandaloorlane“ jälgib pearahakütti, kellest saab lapse Grogu kaitsja.",
      ],
      [
        "Ted_Lasso",
        "An optimistic American football coach is hired to lead an English football club despite having no experience in that sport. Name this comedy series.",
        "Optimistlik ameerika jalgpalli treener palgatakse juhtima Inglise jalgpalliklubi, kuigi ta pole varem jalgpallitreenerina töötanud. Nimeta see komöödiasari.",
        "Ted Lasso",
        "Ted Lasso",
        "Ted Lasso follows an American college football coach who takes charge of the English club AFC Richmond despite his lack of experience with football as played there.",
        "„Ted Lasso“ jälgib ameerika jalgpalli ülikoolimeeskonna treenerit, kes asub juhtima Inglise klubi AFC Richmond, ehkki tal puudub jalgpallitreeneri kogemus.",
      ],
      [
        "Narcos",
        "Drug cartels rise and fall in Colombia while agents pursue their leaders, beginning with Pablo Escobar. Name this crime series.",
        "Colombias tõusevad ja langevad narkokartellid, samal ajal kui agendid jälitavad nende juhte, alustades Pablo Escobarist. Nimeta see krimisari.",
        "Narcos",
        "Narcos",
        "Narcos depicts the Colombian drug trade, first focusing on Pablo Escobar and later on the Cali Cartel and the agents pursuing them.",
        "„Narcos“ kujutab Colombia narkokaubandust, keskendudes esmalt Pablo Escobarile ning hiljem Cali kartellile ja neid jälitavatele agentidele.",
      ],
    ],
  ],
  [
    116,
    "round-two",
    "series",
    "Television Characters Across Genres",
    "Teletegelased eri žanritest",
    [
      [
        "Chandler_Bing",
        "In Friends, this sarcastic member of the group shares a flat with Joey and later marries Monica. Name the character.",
        "Sarjas „Sõbrad“ jagab see sarkastiline seltskonnaliige Joeyga korterit ja abiellub hiljem Monicaga. Nimeta tegelane.",
        "Chandler Bing",
        "Chandler Bing",
        "Chandler Bing is the sarcastic Friends character who is Joey's roommate and later Monica's husband.",
        "Chandler Bing on sarja „Sõbrad“ sarkastiline tegelane, kes on Joey korterikaaslane ja hiljem Monica abikaasa.",
        ["Chandler"],
        ["Chandler"],
      ],
      [
        "Michael_Scott_(The_Office)",
        "In the American version of The Office, this awkward boss manages the Scranton branch of paper company Dunder Mifflin. Name him.",
        "„Kontori“ Ameerika versioonis juhib see piinlikke olukordi tekitav ülemus paberifirma Dunder Mifflini Scrantoni haru. Nimeta ta.",
        "Michael Scott",
        "Michael Scott",
        "Michael Scott is the often unprofessional regional manager of Dunder Mifflin's Scranton branch in The Office.",
        "Michael Scott on sarjas „Kontor“ Dunder Mifflini Scrantoni haru juht, kes käitub sageli ebaprofessionaalselt.",
      ],
      [
        "Tyrion_Lannister",
        "In Game of Thrones, this sharp-witted younger brother of Cersei and Jaime often relies on words to survive court politics. Name him.",
        "„Troonide mängus“ toetub see teravmeelne Cersei ja Jaime noorem vend õukonnaintriigides ellujäämiseks sageli sõnaosavusele. Nimeta ta.",
        "Tyrion Lannister",
        "Tyrion Lannister",
        "Tyrion Lannister is Cersei and Jaime's younger brother, known for his intelligence and wit in Game of Thrones.",
        "Tyrion Lannister on Cersei ja Jaime noorem vend, kes on „Troonide mängus“ tuntud oma arukuse ja teravmeelsuse poolest.",
        ["Tyrion"],
        ["Tyrion"],
      ],
      [
        "Fox_Mulder",
        "Dana Scully's FBI partner in The X-Files believes that aliens and other paranormal forces can explain their unusual cases. Name him.",
        "Dana Scully FBI-partner sarjas „Salatoimikud“ usub, et nende ebatavalisi juhtumeid võivad selgitada tulnukad ja muud paranormaalsed jõud. Nimeta ta.",
        "Fox Mulder",
        "Fox Mulder",
        "Fox Mulder investigates unusual FBI cases with Dana Scully and is the partner who believes in extraterrestrial and paranormal explanations.",
        "Fox Mulder uurib koos Dana Scullyga ebatavalisi FBI juhtumeid ning usub maavälistesse ja paranormaalsetesse seletustesse.",
        ["Mulder"],
        ["Mulder"],
      ],
      [
        "Bender_(Futurama)",
        "Fry’s cigar-smoking robot roommate in Futurama is notorious for rude jokes and misbehaviour. Name him.",
        "Sarjas „Futurama“ on Fry robotist toakaaslane tuntud sigarisuitsetamise, ebaviisakate naljade ja pahanduste poolest. Nimeta ta.",
        "Bender",
        "Bender",
        "Bender is Futurama's metal-bending robot and a frequently badly behaved comic character.",
        "Bender on „Futurama“ metalli painutav robot ja sageli halvasti käituv koomiline tegelane.",
      ],
    ],
  ],
  [
    117,
    "round-two",
    "television-history",
    "Children's Television Through the Years",
    "Lastetelevisioon läbi aastakümnete",
    [
      [
        "Teletubbies",
        "Tinky Winky, Dipsy, Laa-Laa and Po have antennas on their heads and television screens on their bellies. Name their children's programme.",
        "Tinky Winky, Dipsy, Laa-Laa ja Po peas on antennid ning kõhul teleekraanid. Nimeta nende lastesaade.",
        "Teletubbies",
        "Teletupsud",
        "Teletubbies features four colourful characters named Tinky Winky, Dipsy, Laa-Laa and Po, with television screens on their bellies.",
        "„Teletupsudes“ tegutsevad neli värvilist tegelast Tinky Winky, Dipsy, Laa-Laa ja Po, kelle kõhul on teleekraanid.",
      ],
      [
        "Pingu",
        "A little clay penguin and his family communicate in an invented language full of honks and babble. Name this animated children's series.",
        "Väike plastiliinist pingviin ja tema pere suhtlevad väljamõeldud keeles, milles kostab prääksatusi ja pudistamist. Nimeta see animeeritud lastesari.",
        "Pingu",
        "Pingu",
        "Pingu is a stop-motion series about a penguin family whose dialogue uses an invented penguin language.",
        "„Pingu“ on nukuanimatsioonisari pingviiniperest, kelle dialoog kõlab väljamõeldud pingviinikeeles.",
      ],
      [
        "Thomas_%26_Friends",
        "On the island of Sodor, a little blue engine and other talking railway vehicles have adventures together. Name this children's series.",
        "Sodori saarel seiklevad väike sinine vedur ja teised rääkivad raudteesõidukid. Nimeta see lastesari.",
        "Thomas & Friends",
        "Thomas ja sõbrad",
        "Thomas & Friends follows a blue tank engine and other living railway vehicles on the fictional island of Sodor.",
        "„Thomas ja sõbrad“ jälgib sinist vedurit ja teisi elavaid raudteesõidukeid väljamõeldud Sodori saarel.",
        ["Thomas and Friends", "Thomas the Tank Engine"],
        ["Thomas & Friends", "Thomas the Tank Engine"],
      ],
      [
        "Bob_the_Builder",
        "A cheerful builder and his team of talking construction machines work together on repairs and building projects. Name this animated children's series.",
        "Rõõmsameelne ehitaja ja tema rääkivate ehitusmasinate meeskond teevad koos remondi- ja ehitustöid. Nimeta see animeeritud lastesari.",
        "Bob the Builder",
        "Ehitaja Bob",
        "Bob the Builder follows a builder whose team of living construction vehicles helps him complete building work.",
        "„Ehitaja Bob“ jälgib ehitajat, keda aitavad ehitustöödel elavad ehitusmasinad.",
      ],
      [
        "Postman_Pat",
        "A friendly postman delivers letters around Greendale with his black-and-white cat Jess. Name this children's television series.",
        "Sõbralik postiljon toimetab Greendale'is kirju kohale koos oma mustvalge kassi Jessiga. Nimeta see laste telesari.",
        "Postman Pat",
        "Postimees Pat",
        "Postman Pat follows a village postman and his cat Jess as they deliver mail and help people in Greendale.",
        "„Postimees Pat“ jälgib külapostiljoni ja tema kassi Jessi, kes toimetavad Greendale'is posti kohale ning aitavad inimesi.",
      ],
    ],
  ],
  [
    118,
    "round-two",
    "television-history",
    "Prime-Time Classics of the 1980s and 1990s",
    "1980. ja 1990. aastate teleklassika",
    [
      [
        "Baywatch",
        "Lifeguards rescue swimmers and face personal dramas while patrolling the beaches of California. Name this television series.",
        "Vetelpäästjad päästavad ujujaid ja lahendavad isiklikke muresid, patrullides California randades. Nimeta see telesari.",
        "Baywatch",
        "Rannavalve",
        "Baywatch follows lifeguards on California beaches and combines rescues with stories about their personal lives.",
        "„Rannavalve“ jälgib California randade vetelpäästjaid ning ühendab päästetööd lugudega nende eraelust.",
      ],
      [
        "Dallas_(TV_series)",
        "The wealthy Ewing family battles over oil, money and relationships in this Texas-set soap opera. Name the series.",
        "Jõukas Ewingite perekond heitleb nafta, raha ja suhete pärast selles Texases toimuvas seebiooperis. Nimeta sari.",
        "Dallas",
        "Dallas",
        "Dallas centres on the feuding Ewing family, who own an oil company and the Southfork ranch in Texas.",
        "„Dallase“ keskmes on omavahel tülitsev Ewingite pere, kellele kuuluvad naftafirma ja Southforki rantšo Texases.",
      ],
      [
        "MacGyver_(1985_TV_series)",
        "An ingenious secret agent turns ordinary objects into tools that get him out of danger. Name this adventure series whose title is also its hero's surname.",
        "Leidlik salaagent muudab tavalised esemed tööriistadeks, mis aitavad tal ohust pääseda. Nimeta see seiklussari, mille pealkiri on ka peategelase perekonnanimi.",
        "MacGyver",
        "MacGyver",
        "MacGyver follows a resourceful secret agent who solves problems using scientific knowledge and materials at hand.",
        "„MacGyver“ jälgib leidlikku salaagenti, kes lahendab probleeme teaduslike teadmiste ja käepäraste vahendite abil.",
      ],
      [
        "The_Bold_and_the_Beautiful",
        "The Forrester family's fashion business and tangled relationships drive this long-running Los Angeles soap opera. Name it.",
        "Forresterite pere moeäri ja keerulised suhted kannavad seda pika ajalooga Los Angeleses toimuvat seebiooperit. Nimeta sari.",
        "The Bold and the Beautiful",
        "Vaprad ja ilusad",
        "The Bold and the Beautiful is set in Los Angeles and centres on the Forrester family and their fashion business.",
        "„Vaprad ja ilusad“ toimub Los Angeleses ning keskendub Forresterite perekonnale ja nende moeärile.",
      ],
      [
        "Beverly_Hills,_90210",
        "Twins Brandon and Brenda Walsh move from Minnesota and adjust to life at a wealthy California high school. Name this teen drama.",
        "Kaksikud Brandon ja Brenda Walsh kolivad Minnesotast Californiasse ning harjuvad eluga jõuka piirkonna keskkoolis. Nimeta see noortesari.",
        "Beverly Hills, 90210",
        "Beverly Hills, 90210",
        "Beverly Hills, 90210 begins with Brandon and Brenda Walsh adjusting to a new life in an affluent California community after moving from Minnesota.",
        "„Beverly Hills, 90210“ algab sellega, et Brandon ja Brenda Walsh kolivad Minnesotast jõukasse California kogukonda, ning jälgib nende kohanemist uue eluga.",
        ["90210"],
        ["90210"],
      ],
    ],
  ],
  [
    119,
    "round-two",
    "world-cinema",
    "1980s Cinema Favorites",
    "1980. aastate filmilemmikud",
    [
      [
        "Top_Gun",
        "Elite naval aviators compete at a California flight school, where a daring pilot nicknamed Maverick tests his skills. Name this film.",
        "Mereväe eliitpiloodid võistlevad California lennukoolis, kus hüüdnime Maverick kandev uljas lendur paneb oma oskused proovile. Nimeta film.",
        "Top Gun",
        "Top Gun",
        "Top Gun follows the naval pilot Maverick as he trains and competes at an elite fighter-pilot school in California.",
        "„Top Gun“ jälgib mereväelendur Mavericki, kes treenib ja võistleb California eliitses hävitajapilootide koolis.",
      ],
      [
        "Beverly_Hills_Cop",
        "Detroit detective Axel Foley follows his friend's murder case to a wealthy Californian city, clashing with the local police. Name this action comedy.",
        "Detroidi detektiiv Axel Foley sõidab sõbra mõrva uurides jõukasse California linna ja satub seal kohaliku politseiga vastuollu. Nimeta see märulikomöödia.",
        "Beverly Hills Cop",
        "Beverly Hillsi võmm",
        "Beverly Hills Cop follows Detroit detective Axel Foley to California as he investigates the murder of his friend.",
        "„Beverly Hillsi võmm“ jälgib Detroidi detektiivi Axel Foleyt, kes läheb Californiasse uurima oma sõbra mõrva.",
      ],
      [
        "Rain_Man",
        "After their father's death, Charlie discovers he has an autistic older brother, Raymond, and the two travel across the United States by car. Name this film.",
        "Pärast isa surma saab Charlie teada, et tal on autistlik vanem vend Raymond, ning nad sõidavad koos autoga läbi Ameerika Ühendriikide. Nimeta film.",
        "Rain Man",
        "Vihmamees",
        "Rain Man follows Charlie Babbitt and his newly discovered brother Raymond on a cross-country road trip after their father's death.",
        "„Vihmamees“ jälgib Charlie Babbitti ja tema seni tundmatut venda Raymondi ühisel autoreisil läbi riigi pärast nende isa surma.",
      ],
      [
        "Who_Framed_Roger_Rabbit",
        "In a world shared by humans and cartoons, private detective Eddie Valiant investigates a murder blamed on cartoon star Roger Rabbit. Name this film.",
        "Inimeste ja multifilmitegelaste ühises maailmas uurib eradetektiiv Eddie Valiant mõrva, milles süüdistatakse multifilmitähte Roger Rabbitit. Nimeta film.",
        "Who Framed Roger Rabbit",
        "Kes süüdistas Roger Rabbitit?",
        "Who Framed Roger Rabbit combines live action and animation as Eddie Valiant helps clear Roger Rabbit of a murder accusation.",
        "„Kes süüdistas Roger Rabbitit?“ ühendab mängufilmi ja animatsiooni loos, kus Eddie Valiant aitab Roger Rabbitil mõrvasüüdistusest vabaneda.",
      ],
      [
        "Scarface_(1983_film)",
        "Cuban immigrant Tony Montana rises through Miami's criminal underworld and builds a drug empire. Name this crime film.",
        "Kuuba immigrant Tony Montana tõuseb Miami kuritegelikus maailmas ja rajab narkoimpeeriumi. Nimeta see krimifilm.",
        "Scarface",
        "Arminägu",
        "Scarface follows Tony Montana's rise from Cuban immigrant to a powerful drug lord in Miami.",
        "„Arminägu“ jälgib Tony Montana tõusu Kuuba immigrandist mõjukaks Miami narkoparuniks.",
      ],
    ],
  ],
  [
    120,
    "round-two",
    "world-cinema",
    "1990s Cinema Favorites",
    "1990. aastate filmilemmikud",
    [
      [
        "The_Silence_of_the_Lambs_(film)",
        "FBI trainee Clarice Starling interviews imprisoned psychiatrist Hannibal Lecter for help with a criminal investigation. Name this thriller.",
        "FBI väljaõppel olev Clarice Starling küsitleb vangistatud psühhiaatrit Hannibal Lecterit, et saada abi kuriteo uurimisel. Nimeta see põnevik.",
        "The Silence of the Lambs",
        "Voonakeste vaikimine",
        "The Silence of the Lambs follows Clarice Starling as she seeks Hannibal Lecter's help in an FBI investigation.",
        "„Voonakeste vaikimine“ jälgib Clarice Starlingut, kes otsib FBI uurimise käigus abi Hannibal Lecterilt.",
      ],
      [
        "Good_Will_Hunting",
        "A young Boston janitor reveals an extraordinary gift for mathematics and begins therapy that changes his life. Name this drama.",
        "Noorel Bostoni koristajal ilmneb erakordne matemaatikaanne ning ta alustab teraapiat, mis muudab tema elu. Nimeta see draamafilm.",
        "Good Will Hunting",
        "Hea Will Hunting",
        "Good Will Hunting follows a gifted young janitor in Boston whose mathematical talent is discovered and who works with a therapist.",
        "„Hea Will Hunting“ jälgib andekat noort Bostoni koristajat, kelle matemaatikaanne avastatakse ja kes hakkab käima terapeudi juures.",
      ],
      [
        "Basic_Instinct",
        "A San Francisco detective investigates crime novelist Catherine Tramell after a killing resembles a scene from her book. Name this thriller.",
        "San Francisco detektiiv uurib krimikirjanik Catherine Tramelli seotust tapmisega, mis meenutab stseeni tema raamatust. Nimeta see põnevik.",
        "Basic Instinct",
        "Ürginstinkt",
        "Basic Instinct centres on a detective's investigation of Catherine Tramell, whose crime novel resembles the case he is solving.",
        "„Ürginstinkti“ keskmes on detektiiv, kes uurib Catherine Tramelli seost mõrvaga, mille asjaolud sarnanevad naise kriminaalromaani sündmustega.",
      ],
      [
        "Apollo_13_(film)",
        "An oxygen-tank explosion ends a crew's planned Moon landing, turning their mission into a struggle to return safely to Earth. Name this space drama.",
        "Hapnikupaagi plahvatus nurjab meeskonna kavandatud Kuule maandumise ning missioonist saab võitlus turvaliselt Maale naasmise nimel. Nimeta see kosmosedraama.",
        "Apollo 13",
        "Apollo 13",
        "Apollo 13 dramatises the damaged spacecraft's mission, in which an oxygen-tank explosion forces the crew to abandon the Moon landing and work to get home.",
        "„Apollo 13“ dramatiseerib kahjustatud kosmoselaeva missiooni, kus hapnikupaagi plahvatus sunnib meeskonda loobuma Kuule maandumisest ja keskenduma kojujõudmisele.",
        ["Apollo Thirteen"],
        ["Apollo kolmteist"],
      ],
      [
        "The_Full_Monty",
        "Unemployed steelworkers in Sheffield decide to earn money by creating an all-male striptease act. Name this British comedy.",
        "Tööta jäänud Sheffieldi terasetöölised otsustavad teenida raha meeste striptiisietendusega. Nimeta see Briti komöödia.",
        "The Full Monty",
        "Püksid maha!",
        "The Full Monty follows unemployed men in Sheffield, including former steelworkers, who put together a striptease show to earn money.",
        "„Püksid maha!“ jälgib Sheffieldi töötuid mehi, sealhulgas endisi terasetöölisi, kes panevad raha teenimiseks kokku striptiisietenduse.",
      ],
    ],
  ],
];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLocaleLowerCase("en")
    .replace(/%[0-9a-f]{2}/giu, "-")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    page,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const subjectKey = `film-television:${slug(page)}`;
  return {
    clueId: `built-in-film-television-easy-expansion-${clueNumber}`,
    key: `film-television-easy-expansion:${categorySetId}:${tier}`,
    factKey: `film-television-easy-expansion:${slug(page)}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(page).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${page}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    },
  };
}

export const FILM_TELEVISION_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  FILM_TELEVISION_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
