import type {
  EasyExpansionCategory,
  EasyExpansionQuestion,
  EasyExpansionSource,
} from "../types";

const BATCH_ID = "08-sports-games";
const PACK_ID = "built-in-sports-games";
const RETRIEVED_AT = "2026-09-07";

type DirectSourceSeed = Readonly<{
  key: string;
  sourceId: string;
  title: string;
  url: string;
  license: string;
}>;

type SourceSeed = string | DirectSourceSeed;

type QuestionSeed = readonly [
  source: SourceSeed,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const SPORTS_GAMES_EASY_EXPANSION_SEEDS: readonly CategorySeed[] = [
  [
    101,
    "round-one",
    "athletics",
    "Running Events by Their Shape",
    "Jooksualad tunnuse järgi",
    [
      [
        "100_metres",
        "The shortest stadium sprint on the Olympic athletics programme covers this distance. Name it.",
        "Olümpia kergejõustikukava lühim staadionisprint läbitakse sellel distantsil. Nimeta distants.",
        "100 metres",
        "100 meetri jooks",
        "The 100 metres is the shortest standard outdoor sprint and is run on one straight section of the track.",
        "100 meetri jooks on lühim tavapärane staadionisprint ja see joostakse raja ühel sirgel.",
        ["100-metre race"],
        ["100 meetrit"],
      ],
      [
        "200_metres",
        "Half a lap of a standard outdoor track, including one bend, makes up this Olympic sprint. Name the distance.",
        "Pool tavapärasest staadioniringist koos ühe kurviga moodustab selle olümpiasprindi. Nimeta distants.",
        "200 metres",
        "200 meetri jooks",
        "The 200 metres covers half of a standard outdoor lap, combining a bend with the home straight.",
        "200 meetri jooks katab poole tavapärasest staadioniringist ning ühendab kurvi finišisirgega.",
        ["200-metre race"],
        ["200 meetrit"],
      ],
      [
        "800_metres",
        "Two laps of a standard outdoor track make up this middle-distance race. Name the distance.",
        "Kaks tavapärase välisraja ringi moodustavad selle keskmaajooksu. Nimeta distants.",
        "800 metres",
        "800 meetri jooks",
        "The 800 metres is a middle-distance race equal to two laps of a standard outdoor track.",
        "800 meetri jooks on keskmaadistants, mis võrdub tavapärasel välisrajal kahe ringiga.",
        ["800-metre race"],
        ["800 meetrit"],
      ],
      [
        "1500_metres",
        "Often called the metric mile, this middle-distance race covers three and three-quarter standard laps. Name the distance.",
        "Seda keskmaajooksu kutsutakse sageli meetermiiliks ning see katab tavarajal kolm ja kolmveerand ringi. Nimeta distants.",
        "1500 metres",
        "1500 meetri jooks",
        "The 1500 metres is known as the metric mile and covers three and three-quarter laps of a standard track.",
        "1500 meetri jooksu tuntakse meetermiilina ning see katab tavarajal kolm ja kolmveerand ringi.",
        ["1500-metre race"],
        ["1500 meetrit"],
      ],
      [
        "3000_metres_steeplechase",
        "Barriers and a water jump distinguish this Olympic track race run over several laps. Name the event.",
        "Seda mitmeringilist olümpia staadionijooksu eristavad tõkked ja veetakistus. Nimeta ala.",
        "3000 metres steeplechase",
        "3000 meetri takistusjooks",
        "The 3000 metres steeplechase is a track race with barriers and a water jump on each full lap.",
        "3000 meetri takistusjooksus ületatakse igal täisringil tõkkeid ja veetakistust.",
        [],
        [],
      ],
    ],
  ],
  [
    102,
    "round-one",
    "athletics",
    "Field Events and Their Equipment",
    "Väljakualad ja nende varustus",
    [
      [
        "Discus_throw",
        "Athletes spin inside a circle before launching a heavy disc in this field event. Name it.",
        "Sellel väljakualal pöörlevad sportlased heiteringis enne raske ketta lennutamist. Nimeta ala.",
        "discus throw",
        "kettaheide",
        "In the discus throw, an athlete turns inside a throwing circle to build speed before releasing a heavy disc.",
        "Kettaheites kogub sportlane heiteringis pööreldes kiirust ja laseb seejärel raske ketta lendu.",
        [],
        [],
      ],
      [
        "Hammer_throw",
        "A heavy metal ball attached by wire to a handle is used in this field event. Name it.",
        "Sellel väljakualal kasutatakse käepideme külge traadiga kinnitatud rasket metallkuuli. Nimeta ala.",
        "hammer throw",
        "vasaraheide",
        "The hammer throw uses a metal ball connected by steel wire to a grip, which the athlete spins and releases.",
        "Vasaraheites keerutab sportlane metallkuuli, mis on terastraadiga käepideme külge kinnitatud, ja laseb selle siis lendu.",
        [],
        [],
      ],
      [
        "Javelin_throw",
        "Athletes throw a long spear-shaped implement as far as possible in this field event. Name it.",
        "Sellel väljakualal viskavad sportlased pika odakujulise vahendi võimalikult kaugele. Nimeta ala.",
        "javelin throw",
        "odavise",
        "The javelin throw is a field event in which competitors throw a long, spear-like implement for distance.",
        "Odavise on väljakuala, kus võistlejad viskavad pika odakujulise vahendi kauguse peale.",
        [],
        [],
      ],
      [
        "Triple_jump",
        "A run-up is followed by three phases traditionally called the hop, step and jump in this field event. Name it.",
        "Sellel hüppealal järgnevad hoojooksule kolm osa, mida nimetatakse hüppeks, sammuks ja lõpphüppeks. Nimeta ala.",
        "triple jump",
        "kolmikhüpe",
        "The triple jump combines a hop, a step and a final jump into the sand pit.",
        "Kolmikhüpe ühendab hüppe, sammu ja viimase hüppe liivakasti.",
        [],
        [],
      ],
      [
        "Pole_vault",
        "A long flexible pole helps an athlete clear a high bar in this field event. Name it.",
        "Sellel väljakualal aitab pikk painduv teivas sportlasel ületada kõrgel asuvat latti. Nimeta ala.",
        "pole vault",
        "teivashüpe",
        "In the pole vault, an athlete plants a flexible pole and uses it to rise over a crossbar.",
        "Teivashüppes asetab sportlane painduva teiba tugikasti ja kasutab seda lati kohale tõusmiseks.",
        [],
        [],
      ],
    ],
  ],
  [
    103,
    "round-one",
    "athletics",
    "Iconic Track-and-Field Stars",
    "Ikoonilised kergejõustikutähed",
    [
      [
        "Jesse_Owens",
        "At the 1936 Berlin Olympics, this American sprinter and long jumper won four gold medals. Name him.",
        "See USA sprinter ja kaugushüppaja võitis 1936. aasta Berliini olümpiamängudel neli kuldmedalit. Nimeta ta.",
        "Jesse Owens",
        "Jesse Owens",
        "Jesse Owens took four gold medals across sprinting, long jump and relay events in Berlin.",
        "Jesse Owens võitis Berliinis sprindi-, kaugushüppe- ja teatejooksualadel kokku neli kuldmedalit.",
        ["Owens"],
        ["Owens"],
      ],
      [
        "Carl_Lewis",
        "This American sprinter and long jumper won nine Olympic gold medals, including four at Los Angeles 1984. Name him.",
        "See USA sprinter ja kaugushüppaja võitis üheksa olümpiakulda, neist neli 1984. aastal Los Angeleses. Nimeta ta.",
        "Carl Lewis",
        "Carl Lewis",
        "Carl Lewis won nine Olympic gold medals during a career in which he dominated sprinting and the long jump.",
        "Carl Lewis võitis sprindi- ja kaugushüppekarjääri jooksul üheksa olümpiakulda.",
        [],
        [],
      ],
      [
        "Florence_Griffith_Joyner",
        "This American sprint star stood out in 1988 with bold one-legged racing suits and long decorated nails. Name her.",
        "See USA sprinditäht paistis 1988. aastal silma erksate ühe säärega võistluskostüümide ja pikkade kaunistatud küüntega. Nimeta ta.",
        "Florence Griffith Joyner",
        "Florence Griffith Joyner",
        "Florence Griffith Joyner, widely known as Flo-Jo, won three gold medals at Seoul 1988 and became famous for her distinctive style.",
        "Florence Griffith Joyner, keda tunti Flo-Jo nime all, võitis 1988. aasta Souli olümpial kolm kuldmedalit ja sai kuulsaks oma erilise stiiliga.",
        ["Griffith Joyner", "Flo-Jo"],
        ["Griffith Joyner", "Flo-Jo"],
      ],
      [
        "Sergey_Bubka",
        "This Ukrainian athletics legend was the first person to use a pole to clear both six metres and 6.10 metres. Name him.",
        "See Ukraina kergejõustikulegend oli esimene, kes ületas teiba abil nii kuus meetrit kui ka 6,10 meetrit. Nimeta ta.",
        "Sergey Bubka",
        "Sergei Bubka",
        "Sergey Bubka became the first athlete in his event to clear 6.00 metres and later 6.10 metres.",
        "Sergei Bubka sai oma ala esimeseks sportlaseks, kes ületas 6,00 meetrit ja hiljem ka 6,10 meetrit.",
        ["Bubka", "Sergei Bubka"],
        ["Bubka", "Sergey Bubka"],
      ],
      [
        "Haile_Gebrselassie",
        "This Ethiopian distance-running great won Olympic gold in the 10,000 metres in both 1996 and 2000. Name him.",
        "See Etioopia pikamaajooksulegend võitis nii 1996. kui ka 2000. aastal olümpiakulla 10 000 meetri jooksus. Nimeta ta.",
        "Haile Gebrselassie",
        "Haile Gebrselassie",
        "Haile Gebrselassie won the Olympic 10,000-metre title in Atlanta in 1996 and defended it in Sydney in 2000.",
        "Haile Gebrselassie võitis 1996. aastal Atlantas 10 000 meetri jooksu olümpiakulla ja kaitses tiitlit 2000. aastal Sydneys.",
        ["Gebrselassie"],
        ["Gebrselassie"],
      ],
    ],
  ],
  [
    104,
    "round-one",
    "athletics",
    "City Marathons",
    "Linnamaratonid",
    [
      [
        "New_York_City_Marathon",
        "This major road race crosses all five boroughs before finishing in Central Park. Name the event.",
        "See suur maanteejooks läbib kõik viis linnaosa ja lõpeb Central Parkis. Nimeta võistlus.",
        "New York City Marathon",
        "New Yorgi maraton",
        "The New York City Marathon runs through all five boroughs and finishes in Manhattan's Central Park.",
        "New Yorgi maraton läbib kõik viis linnaosa ja lõpeb Manhattanil Central Parkis.",
        ["NYC Marathon"],
        ["New York City Marathon"],
      ],
      [
        "Berlin_Marathon",
        "This major city race passes through the Brandenburg Gate shortly before its finish. Name the event.",
        "See suur linnajooks möödub veidi enne finišit Brandenburgi väravast. Nimeta võistlus.",
        "Berlin Marathon",
        "Berliini maraton",
        "The Berlin Marathon follows a course through the German capital and passes the Brandenburg Gate near the finish.",
        "Berliini maratoni rada kulgeb läbi Saksamaa pealinna ja möödub finiši eel Brandenburgi väravast.",
        ["BMW Berlin Marathon"],
        ["Berlin Marathon"],
      ],
      [
        "Chicago_Marathon",
        "This major US city race starts and finishes in Grant Park and loops through neighbourhoods beside Lake Michigan. Name the event.",
        "See USA suurlinna jooks algab ja lõpeb Grant Parkis ning läbib Michigani järve äärseid linnaosi. Nimeta võistlus.",
        "Chicago Marathon",
        "Chicago maraton",
        "The Chicago Marathon is a loop course through the city that begins and ends in Grant Park.",
        "Chicago maraton kulgeb ringrajana läbi linna ning algab ja lõpeb Grant Parkis.",
        ["Bank of America Chicago Marathon"],
        ["Chicago Marathon"],
      ],
      [
        "Tokyo_Marathon",
        "This annual World Marathon Major is run through Japan's capital. Name the event.",
        "See iga-aastane maailma suurmaraton joostakse läbi Jaapani pealinna. Nimeta võistlus.",
        "Tokyo Marathon",
        "Tokyo maraton",
        "The Tokyo Marathon is an annual road race through Japan's capital and one of the World Marathon Majors.",
        "Tokyo maraton on iga-aastane maanteejooks läbi Jaapani pealinna ning kuulub maailma suurmaratonide hulka.",
        [],
        [],
      ],
      [
        "Paris_Marathon",
        "This major spring road race starts on the Champs-Élysées in the French capital. Name the event.",
        "See suur kevadine maanteejooks algab Prantsusmaa pealinnas Champs-Élysées'l. Nimeta võistlus.",
        "Paris Marathon",
        "Pariisi maraton",
        "The Paris Marathon starts on the Champs-Élysées and carries runners through the French capital.",
        "Pariisi maraton algab Champs-Élysées'l ja viib jooksjad läbi Prantsusmaa pealinna.",
        ["Marathon de Paris"],
        ["Paris Marathon"],
      ],
    ],
  ],
  [
    105,
    "round-one",
    "basketball",
    "Basketball Beyond the NBA",
    "Korvpall väljaspool NBA-d",
    [
      [
        "FIBA",
        "This four-letter body governs international basketball and organizes its men's World Cup. Name it.",
        "See neljatäheline organisatsioon juhib rahvusvahelist korvpalli ja korraldab meeste maailmameistrivõistlusi. Nimeta organisatsioon.",
        "FIBA",
        "FIBA",
        "FIBA is basketball's international governing body and organizes the Basketball World Cup.",
        "FIBA on korvpalli rahvusvaheline juhtorgan ja korraldab korvpalli maailmameistrivõistlusi.",
        ["International Basketball Federation"],
        ["Rahvusvaheline Korvpalliliit"],
      ],
      [
        "Women%27s_National_Basketball_Association",
        "This US professional league is the women's counterpart to the NBA. Name it.",
        "See USA profiliiga on naiste vaste NBA-le. Nimeta liiga.",
        "WNBA",
        "WNBA",
        "The WNBA is a professional women's basketball league in the United States.",
        "WNBA on Ameerika Ühendriikide naiste profikorvpalliliiga.",
        ["Women's National Basketball Association"],
        ["Women's National Basketball Association"],
      ],
      [
        "1992_United_States_men%27s_Olympic_basketball_team",
        "The 1992 US men's Olympic basketball squad packed with active NBA stars received this nickname. Give it.",
        "USA 1992. aasta meeste olümpiakorvpallimeeskond, kuhu kuulusid NBA tegevmängijad, sai selle hüüdnime. Nimeta see.",
        "Dream Team",
        "Dream Team",
        "The 1992 United States men's Olympic basketball team was nicknamed the Dream Team and was the first US Olympic squad to feature active NBA players.",
        "USA 1992. aasta meeste olümpiakorvpallimeeskond sai hüüdnime Dream Team ja oli riigi esimene tegevate NBA mängijatega olümpiakoondis.",
        ["U.S. Dream Team", "1992 U.S. Olympic basketball team"],
        ["USA unistuste meeskond", "1992. aasta USA olümpiakorvpallikoondis"],
      ],
      [
        "Harlem_Globetrotters",
        "This travelling basketball team is famous for mixing dazzling skill with comedy and showmanship. Name it.",
        "See rändav näidismeeskond on kuulus korvpallioskuste, komöödia ja vaatemängu ühendamise poolest. Nimeta meeskond.",
        "Harlem Globetrotters",
        "Harlem Globetrotters",
        "The Harlem Globetrotters are an exhibition team whose performances combine basketball, entertainment and comedy.",
        "Harlem Globetrotters on näidismeeskond, kelle etteasted ühendavad korvpalli, meelelahutuse ja komöödia.",
        [],
        [],
      ],
      [
        "3x3_basketball",
        "One basket, a half court and teams of three players define this Olympic form of basketball. Name it.",
        "Üks korv, pool väljakut ja kolmeliikmelised võistkonnad iseloomustavad seda olümpiakorvpalli vormi. Nimeta see.",
        "3x3 basketball",
        "3x3 korvpall",
        "3x3 basketball is played by two teams of three on a half court with one basket.",
        "3x3 korvpallis mängivad kaks kolmeliikmelist võistkonda poolel väljakul ühe korvi all.",
        ["3-on-3 basketball", "three-on-three basketball"],
        ["3 × 3 korvpall", "kolm kolme vastu korvpall"],
      ],
    ],
  ],
  [
    106,
    "round-one",
    "basketball",
    "Basketball Moves",
    "Korvpallivõtted",
    [
      [
        "Layup",
        "This close-range basketball shot is usually taken after one or two steps and often placed off the backboard. Name it.",
        "See korvilähedane korvpallivise tehakse tavaliselt ühe või kahe sammu järel ja sageli lauda kasutades. Nimeta vise.",
        "layup",
        "sammudelt vise",
        "A layup is a close-range shot made near the basket, often after stepping toward the hoop and using the backboard.",
        "Sammudelt vise sooritatakse korvi lähedalt, liikudes sammudega korvi poole ja kasutades sageli korvilauda.",
        ["lay-up"],
        ["sammudelt vise korvile"],
      ],
      [
        {
          key: "jr-nba-bounce-pass",
          sourceId: "source:sports-games:jr-nba-bounce-pass",
          title: "Bounce Pass - NBA.com: Jr. NBA",
          url: "https://jr.nba.com/bounce-pass/",
          license: "All rights reserved",
        },
        "This pass reaches a teammate after the ball is deliberately thrown down to the floor. Name it.",
        "See sööt jõuab kaaslaseni pärast seda, kui pall lükatakse meelega vastu põrandat. Nimeta sööt.",
        "bounce pass",
        "põrkesööt",
        "A bounce pass is directed into the floor so that the ball rebounds up to a teammate.",
        "Põrkesöödu puhul suunatakse pall vastu põrandat, kust see põrkab kaaslasele.",
        [],
        [],
      ],
      [
        "Jump_shot_(basketball)",
        "This basketball shot is released while the shooter is airborne. Name it.",
        "See korvpallivise lastakse käest ajal, mil viskaja on õhus. Nimeta vise.",
        "jump shot",
        "hüppevise",
        "A jump shot is released near the top of the shooter's jump, helping create space above a defender.",
        "Hüppevise lastakse käest hüppe kõrgeimas osas, mis aitab kaitsjast kõrgemalt visata.",
        ["jumpshot"],
        ["jump shot"],
      ],
      [
        "Alley-oop",
        "In this basketball play, one player catches a pass near the basket in mid-air and scores before landing. Name the play.",
        "Selles korvpallikombinatsioonis püüab mängija korvi lähedal õhus söödu ja skoorib enne maandumist. Nimeta kombinatsioon.",
        "alley-oop",
        "alley-oop",
        "In an alley-oop, one player throws a pass near the rim for a teammate to catch and score in one airborne motion.",
        "Alley-oop'i puhul viskab üks mängija palli korvi lähedale, et kaaslane saaks selle õhus püüda ja ühe liigutusega skoorida.",
        [],
        [],
      ],
      [
        "Hook_shot",
        "In this one-handed basketball shot, the shooting arm sweeps in an arc while the shooter's body shields the ball. Name it.",
        "Selle ühekäeviske puhul liigub viskekäsi kaarega ning viskaja keha jääb palli ja kaitsja vahele. Nimeta vise.",
        "hook shot",
        "haakvise",
        "A hook shot uses a sideways body position and a sweeping one-handed motion that helps protect the ball from a defender.",
        "Haakviskes on keha külgsuunas ning ühe käe kaarjas liigutus aitab palli kaitsja eest varjata.",
        ["hookshot"],
        ["hook shot"],
      ],
    ],
  ],
  [
    107,
    "round-one",
    "basketball",
    "Global Basketball Stars",
    "Maailma korvpallitähed",
    [
      [
        "LeBron_James",
        "Nicknamed King James, this basketball superstar has played for Cleveland, Miami and Los Angeles. Name him.",
        "See hüüdnime King James kandev korvpallistaar on mänginud Clevelandis, Miamis ja Los Angeleses. Nimeta ta.",
        "LeBron James",
        "LeBron James",
        "LeBron James, widely called King James, has starred for NBA teams in Cleveland, Miami and Los Angeles.",
        "LeBron James, keda tuntakse hüüdnime King James all, on olnud NBA staar Clevelandis, Miamis ja Los Angeleses.",
        ["LeBron"],
        ["LeBron"],
      ],
      [
        "Shaquille_O%27Neal",
        "This giant centre starred beside Kobe Bryant for Los Angeles and later became a television analyst. Name him.",
        "See hiiglaslik tsenter mängis Los Angeleses Kobe Bryanti kõrval ja sai hiljem teleanalüütikuks. Nimeta ta.",
        "Shaquille O'Neal",
        "Shaquille O'Neal",
        "Shaquille O'Neal, often called Shaq, was a dominant NBA centre and won three consecutive championships in Los Angeles.",
        "Shaquille O'Neal, keda kutsutakse sageli Shaqiks, oli NBA võimas tsenter ja võitis Los Angeleses kolm meistritiitlit järjest.",
        ["Shaq", "O'Neal"],
        ["Shaq", "O'Neal"],
      ],
      [
        "Kevin_Durant",
        "Nicknamed KD, this American scoring star won two NBA championships with Golden State. Name him.",
        "See hüüdnime KD kandev USA korvikütt võitis Golden State'iga kaks NBA meistritiitlit. Nimeta ta.",
        "Kevin Durant",
        "Kevin Durant",
        "Kevin Durant won consecutive NBA championships and Finals MVP awards with Golden State in 2017 and 2018.",
        "Kevin Durant võitis Golden State'iga 2017. ja 2018. aastal järjest NBA meistritiitli ning finaalseeria väärtuslikema mängija auhinna.",
        ["Durant"],
        ["Durant"],
      ],
      [
        "Giannis_Antetokounmpo",
        "The Milwaukee Bucks star nicknamed the Greek Freak is this Greek player. Name him.",
        "Milwaukee Bucksi hüüdnime Greek Freak kandev täht on see Kreeka mängija. Nimeta ta.",
        "Giannis Antetokounmpo",
        "Giannis Antetokounmpo",
        "Giannis Antetokounmpo is the Greek Milwaukee star widely known by the nickname Greek Freak.",
        "Giannis Antetokounmpo on Milwaukee Kreeka päritolu täht, keda tuntakse laialt hüüdnime Greek Freak all.",
        ["Giannis", "Antetokounmpo"],
        ["Giannis", "Antetokounmpo"],
      ],
      [
        "Dirk_Nowitzki",
        "This German basketball star led his only NBA club to its first championship in 2011 and was named Finals MVP. Name him.",
        "See Saksamaa korvpallistaar viis oma ainsa NBA klubi 2011. aastal esimest korda meistriks ja valiti finaalseeria väärtuslikemaks mängijaks. Nimeta ta.",
        "Dirk Nowitzki",
        "Dirk Nowitzki",
        "Dirk Nowitzki spent his entire NBA career with one club and led it to its first championship in 2011.",
        "Dirk Nowitzki veetis kogu NBA karjääri ühes klubis ja viis selle 2011. aastal esimese meistritiitlini.",
        ["Nowitzki"],
        ["Nowitzki"],
      ],
    ],
  ],
  [
    108,
    "round-one",
    "basketball",
    "Basketball Teams by Their Identity",
    "Korvpallimeeskonnad tunnuse järgi",
    [
      [
        "Toronto_Raptors",
        "Canada's NBA team won its first championship in 2019 and uses a dinosaur in its identity. Name the team.",
        "Kanada NBA meeskond võitis 2019. aastal oma esimese meistritiitli ja kasutab identiteedis dinosaurust. Nimeta meeskond.",
        "Toronto Raptors",
        "Toronto Raptors",
        "The Toronto Raptors are based in Canada, and their name and logo draw on the popular image of a raptor dinosaur.",
        "Toronto Raptors tegutseb Kanadas ning meeskonna nimi ja logo viitavad röövtoidulisele dinosaurusele.",
        ["Raptors"],
        ["Raptors"],
      ],
      [
        "Dallas_Mavericks",
        "This Texas NBA team is often shortened to the Mavs and won its first championship in 2011. Name it.",
        "Seda Texase NBA meeskonda kutsutakse sageli Mavsiks ning 2011. aastal võitis klubi oma esimese meistritiitli. Nimeta meeskond.",
        "Dallas Mavericks",
        "Dallas Mavericks",
        "The Mavericks, commonly called the Mavs, won the franchise's first NBA championship in 2011.",
        "Mavericks, mida kutsutakse sageli Mavsiks, võitis 2011. aastal klubi esimese NBA meistritiitli.",
        ["Mavericks"],
        ["Mavericks"],
      ],
      [
        "New_York_Knicks",
        "This NBA team plays its home games at Madison Square Garden. Name it.",
        "See NBA meeskond peab oma kodumänge Madison Square Gardenis. Nimeta meeskond.",
        "New York Knicks",
        "New York Knicks",
        "The New York Knicks play their home games at Madison Square Garden in Manhattan.",
        "New York Knicks peab kodumänge Manhattanil Madison Square Gardenis.",
        ["Knicks"],
        ["Knicks"],
      ],
      [
        "San_Antonio_Spurs",
        "This Texas NBA team won five championships under coach Gregg Popovich, with Tim Duncan as its cornerstone. Name it.",
        "See Texase NBA meeskond võitis treener Gregg Popovichi käe all viis meistritiitlit ja toetus Tim Duncanile. Nimeta meeskond.",
        "San Antonio Spurs",
        "San Antonio Spurs",
        "The San Antonio Spurs won five NBA championships under Gregg Popovich, with Tim Duncan on every title team.",
        "San Antonio Spurs võitis Gregg Popovichi juhendamisel viis NBA meistritiitlit ning Tim Duncan kuulus igasse tiitlivõistkonda.",
        ["Spurs"],
        ["Spurs"],
      ],
      [
        "Houston_Rockets",
        "This NBA team from Houston has a space-themed name matching the city's role in human spaceflight. Name it.",
        "Sellel Houstoni NBA meeskonnal on linna kosmoselendudega seotud rollile sobiv kosmoseteemaline nimi. Nimeta meeskond.",
        "Houston Rockets",
        "Houston Rockets",
        "The Houston Rockets use a space-themed name that suits Houston's close association with crewed spaceflight.",
        "Houston Rockets kasutab kosmoseteemalist nime, mis sobib Houstoni tiheda seosega mehitatud kosmoselendudega.",
        ["Rockets"],
        ["Rockets"],
      ],
    ],
  ],
  [
    109,
    "round-one",
    "olympics",
    "Olympic Symbols and Traditions",
    "Olümpiasümbolid ja -traditsioonid",
    [
      [
        "Olympic_symbols",
        "Five interlocking coloured circles form this best-known Olympic symbol. Name it.",
        "Viis omavahel põimunud värvilist ringi moodustavad selle tuntuima olümpiasümboli. Nimeta see.",
        "Olympic rings",
        "olümpiarõngad",
        "The Olympic rings are five interlocking rings used as the best-known visual symbol of the Olympic movement.",
        "Olümpiarõngad on viis omavahel põimunud ringi ja olümpialiikumise tuntuim visuaalne sümbol.",
        [],
        [],
      ],
      [
        "Olympic_Oath",
        "A spoken promise to respect the rules and fair play is made on behalf of athletes and officials under this name. Give it.",
        "Sportlaste ja kohtunike nimel antakse selle nime all suuline lubadus austada reegleid ning ausat mängu. Nimeta see.",
        "Olympic oath",
        "olümpiavanne",
        "The Olympic oath is a ceremonial promise made by representatives of athletes, judges and coaches.",
        "Olümpiavanne on pidulik lubadus, mille annavad sportlaste, kohtunike ja treenerite esindajad.",
        [],
        [],
      ],
      [
        "List_of_Olympic_torch_relays",
        "A chain of runners carries the flame from Olympia to the host city in this pre-Games tradition. Name it.",
        "Selles mängude-eelses traditsioonis viib jooksjate ahel leegi Olümpiast korraldajalinna. Nimeta traditsioon.",
        "torch relay",
        "olümpiatule teatejooks",
        "The torch relay transports the Olympic flame from Olympia through a chain of runners to the host city.",
        "Olümpiatule teatejooks viib leegi Olümpiast jooksjate ahela kaudu korraldajalinna.",
        [],
        [],
      ],
      [
        "Olympic_Games_ceremony",
        "The top three competitors step onto a podium and receive gold, silver and bronze awards during this part of an Olympic event. Name it.",
        "Olümpiavõistluse selles osas astuvad kolm parimat poodiumile ning saavad kuldse, hõbedase ja pronksise autasu. Nimeta see.",
        "medal ceremony",
        "autasustamistseremoonia",
        "A medal ceremony brings the top three competitors to the podium to receive gold, silver and bronze medals.",
        "Autasustamistseremoonial astuvad kolm parimat poodiumile ning saavad kuld-, hõbe- ja pronksmedali.",
        ["medal presentation ceremony"],
        ["medalitseremoonia"],
      ],
      [
        "Olympic_Games",
        "'Faster, Higher, Stronger – Together' is this official Olympic phrase. Name it.",
        "„Kiiremini, kõrgemale, tugevamini – üheskoos“ on see ametlik olümpiafraas. Nimeta see.",
        "Olympic motto",
        "olümpiadeviis",
        "The Olympic motto is 'Faster, Higher, Stronger – Together', traditionally expressed in Latin.",
        "Olümpiadeviis tähendab „Kiiremini, kõrgemale, tugevamini – üheskoos“ ja seda väljendatakse traditsiooniliselt ladina keeles.",
        [],
        [],
      ],
    ],
  ],
  [
    110,
    "round-one",
    "olympics",
    "Summer Olympic Sports",
    "Suveolümpiaalad",
    [
      [
        "Artistic_gymnastics",
        "The balance beam, uneven bars, rings and pommel horse are apparatus in this Olympic discipline. Name it.",
        "Poom, eri kõrgusega rööbaspuud, rõngad ja sangadega hobune on selle olümpiaala vahendid. Nimeta ala.",
        "artistic gymnastics",
        "sportvõimlemine",
        "Artistic gymnastics consists of routines on apparatus, including the beam and uneven bars for women and rings and pommel horse for men.",
        "Sportvõimlemine koosneb vahendikavadest, sealhulgas naiste poomi- ja eri kõrgusega rööbaspuude ning meeste rõngaste ja sangadega hobuse kavast.",
        [],
        [],
      ],
      [
        "Triathlon_at_the_Summer_Olympics",
        "Swimming, cycling and running, completed in that order, make up this endurance sport. Name it.",
        "Ujumine, rattasõit ja jooks moodustavad selles järjekorras läbitava vastupidavusala. Nimeta ala.",
        "triathlon",
        "triatlon",
        "A triathlon is a continuous race made up of swimming, cycling and running sections.",
        "Triatlon on järjest läbitav võistlus, mis koosneb ujumisest, rattasõidust ja jooksust.",
        [],
        [],
      ],
      [
        "Sport_climbing_at_the_Summer_Olympics",
        "Speed, bouldering and lead are disciplines within this Olympic sport on artificial walls. Name it.",
        "Kiirusronimine, rahnuronimine ja raskusronimine on selle tehisronimisseinal peetava olümpiaala võistlusviisid. Nimeta ala.",
        "sport climbing",
        "sportronimine",
        "Sport climbing at the Olympics uses artificial walls for speed, bouldering and lead competition.",
        "Sportronimise olümpiavõistlused peetakse tehisronimisseinal kiirus-, rahnu- ja raskusronimises.",
        [],
        [],
      ],
      [
        "Canoeing_at_the_Summer_Olympics",
        "Boats race head-to-head in marked lanes on calm, straight water in this Olympic canoeing discipline. Name it.",
        "Sellel aerutamise olümpiaalal võisteldakse paatidega rahulikul sirgel veel kõrvuti tähistatud radadel. Nimeta ala.",
        "canoe sprint",
        "rajaaerutamine",
        "Canoe sprint holds straight-course races in lanes for canoes and kayaks on calm water.",
        "Rajaaerutamises võistlevad kanuud ja süstad rahulikul veel sirgel tähistatud rajal.",
        [],
        [],
      ],
      [
        "Modern_pentathlon",
        "Fencing and swimming join several other disciplines in this five-part Olympic contest. Name it.",
        "Vehklemine ja ujumine ühinevad mitme teise alaga selles viieosalises olümpiavõistluses. Nimeta ala.",
        "modern pentathlon",
        "moodne viievõistlus",
        "Modern pentathlon is an Olympic multisport contest built from five different disciplines rather than one race or match.",
        "Moodne viievõistlus on olümpia mitmevõistlus, mis koosneb ühe võistluse või mängu asemel viiest eri alast.",
        [],
        [],
      ],
    ],
  ],

  [
    111,
    "round-two",
    "olympics",
    "Olympic Legends",
    "Olümpialegendid",
    [
      [
        "Olga_Korbut",
        "This Soviet gymnast, nicknamed the “Sparrow from Minsk”, became a sensation at the 1972 Munich Olympics with daring acrobatics, including a backflip on the uneven bars. Name her.",
        "See „Minski varblaseks“ kutsutud Nõukogude võimleja tõusis 1972. aasta Müncheni olümpial sensatsiooniks julge akrobaatikaga, sealhulgas tagurpidi saltoga eri kõrgusega rööbaspuudel. Nimeta ta.",
        "Olga Korbut",
        "Olga Korbut",
        "Olga Korbut won three gold medals at Munich 1972, and her acrobatic routines helped make gymnastics far more popular.",
        "Olga Korbut võitis 1972. aastal Münchenis kolm kuldmedalit ning tema akrobaatilised kavad aitasid võimlemist palju populaarsemaks muuta.",
        ["Korbut"],
        ["Korbut"],
      ],
      [
        "Greg_Louganis",
        "At Seoul 1988, this American diver struck his head on the springboard, returned to the competition and still won two gold medals. Name him.",
        "See USA vettehüppaja lõi 1988. aasta Souli olümpial pea vastu hüppelauda, naasis võistlusele ja võitis siiski kaks kuldmedalit. Nimeta ta.",
        "Greg Louganis",
        "Greg Louganis",
        "Greg Louganis continued after the springboard accident and won both the springboard and platform events at Seoul 1988.",
        "Greg Louganis jätkas pärast hüppelaual juhtunud õnnetust võistlemist ning võitis 1988. aastal Soulis nii hoolaua- kui ka tornihüpped.",
        ["Louganis"],
        ["Louganis"],
      ],
      [
        "Ian_Thorpe",
        "This Australian freestyle swimmer was the most successful athlete at the Sydney 2000 Olympics, winning three gold and two silver medals. Name him.",
        "See Austraalia vabaujuja oli 2000. aasta Sydney olümpia edukaim sportlane, võites kolm kuld- ja kaks hõbemedalit. Nimeta ta.",
        "Ian Thorpe",
        "Ian Thorpe",
        "Ian Thorpe won three gold and two silver medals in Sydney and earned the nickname “Thorpedo” for his speed in the pool.",
        "Ian Thorpe võitis Sydneys kolm kuld- ja kaks hõbemedalit ning sai oma kiiruse tõttu hüüdnime „Thorpedo“.",
        ["Thorpe"],
        ["Thorpe"],
      ],
      [
        "Katie_Ledecky",
        "At age 15, this American swimmer unexpectedly won the 800-metre freestyle at the 2012 Olympics. Name her.",
        "See USA ujuja võitis 15-aastaselt üllatuslikult 2012. aasta olümpial 800 meetri vabaujumise. Nimeta ta.",
        "Katie Ledecky",
        "Katie Ledecky",
        "Katie Ledecky won the Olympic 800-metre freestyle title on her international debut at the 2012 Games.",
        "Katie Ledecky võitis 2012. aasta mängudel oma rahvusvahelisel debüüdil 800 meetri vabaujumise olümpiakulla.",
        ["Ledecky"],
        ["Ledecky"],
      ],
      [
        "Eddie_the_Eagle",
        "This British ski jumper finished last in both events at Calgary 1988, and a 2016 film later told his story. Name him.",
        "See Briti suusahüppaja jäi 1988. aastal Calgarys mõlemas võistluses viimaseks ning 2016. aastal valmis tema loost film. Nimeta ta.",
        "Eddie the Eagle",
        "Kotkas Eddie",
        "Eddie the Eagle was Great Britain’s first Olympic ski-jumping representative and finished last in both Calgary events.",
        "Eddie the Eagle oli Suurbritannia esimene olümpiamängude suusahüppaja ning jäi Calgary mõlemas võistluses viimaseks.",
        ["Eddie 'the Eagle' Edwards", "Eddie Edwards", "Michael Edwards"],
        ["Eddie the Eagle", "Eddie Edwards", "Michael Edwards"],
      ],
    ],
  ],
  [
    112,
    "round-two",
    "olympics",
    "Memorable Summer Games",
    "Meeldejäänud suveolümpiamängud",
    [
      [
        "2012_Summer_Olympics",
        "At which Summer Olympics did Rowan Atkinson appear as Mr Bean during the opening ceremony?",
        "Millistel suveolümpiamängudel astus avatseremoonial Mr Beanina üles Rowan Atkinson?",
        "London 2012",
        "London 2012",
        "The London 2012 opening ceremony included Rowan Atkinson performing in character as Mr Bean.",
        "London 2012 avatseremoonial astus Rowan Atkinson üles Mr Beani rollis.",
        ["2012 London Olympics"],
        ["Londoni 2012. aasta olümpiamängud"],
      ],
      [
        "2008_Summer_Olympics",
        "The opening ceremony of these Summer Games filled the Bird’s Nest stadium in China’s capital. Name the Games.",
        "Nende suveolümpiamängude avatseremoonia täitis Hiina pealinnas asuva Linnupesa staadioni. Nimeta need mängud.",
        "Beijing 2008",
        "2008. aasta Pekingi olümpiamängud",
        "Beijing 2008 held its opening ceremony at Beijing National Stadium, widely known as the Bird’s Nest.",
        "2008. aasta Pekingi olümpiamängude avatseremoonia toimus Pekingi rahvusstaadionil, mida tuntakse Linnupesa nime all.",
        ["the Beijing 2008 Games"],
        ["Peking 2008"],
      ],
      [
        "2020_Summer_Olympics",
        "These Summer Games kept their 2020 name even though the pandemic postponed them until 2021. Name the Games.",
        "Need suveolümpiamängud säilitasid 2020. aasta nime, kuigi pandeemia lükkas nende toimumise 2021. aastasse. Nimeta need mängud.",
        "Tokyo 2020",
        "Tokyo 2020",
        "Tokyo 2020 was postponed because of the COVID-19 pandemic and held in 2021 under its original name.",
        "Tokyo 2020 lükati COVID-19 pandeemia tõttu edasi ja peeti 2021. aastal algse nime all.",
        ["2020 Tokyo Olympics"],
        ["Tokyo 2020. aasta olümpiamängud"],
      ],
      [
        "2004_Summer_Olympics",
        "Which 2004 Summer Games returned the Olympics to Greece, the birthplace of the ancient Games and host of the first modern Games?",
        "Millised 2004. aasta suveolümpiamängud tõid olümpia tagasi Kreekasse, antiikmängude sünnimaale ja esimeste nüüdisaegsete mängude võõrustajariiki?",
        "Athens 2004",
        "Ateena 2004",
        "Athens 2004 brought the Summer Olympics back to Greece, where the ancient Games began and the first modern Games were held.",
        "Ateena 2004 tõi suveolümpiamängud tagasi Kreekasse, kus said alguse antiikmängud ja peeti esimesed nüüdisaegsed olümpiamängud.",
        ["2004 Athens Olympics"],
        ["Ateena 2004. aasta olümpiamängud"],
      ],
      [
        "1992_Summer_Olympics",
        "The 1992 Summer Games took place in a Spanish city famous for the Sagrada Família. Name the Games.",
        "1992. aasta suveolümpiamängud toimusid Hispaania linnas, mis on kuulus Sagrada Família poolest. Nimeta need mängud.",
        "Barcelona 1992",
        "Barcelona 1992",
        "Barcelona 1992 was hosted by the Spanish city whose landmarks include the Sagrada Família.",
        "Barcelona 1992 toimus Hispaania linnas, mille kuulsate vaatamisväärsuste hulka kuulub Sagrada Família.",
        ["1992 Barcelona Olympics"],
        ["Barcelona 1992. aasta olümpiamängud"],
      ],
    ],
  ],
  [
    113,
    "round-two",
    "racket-sports",
    "On a Tennis Court",
    "Tenniseväljakul",
    [
      [
        "Tennis_court",
        "On a tennis court, what line runs parallel to the net and marks the far end of each service box?",
        "Milline tenniseväljaku joon kulgeb võrguga rööbiti ja märgib kummagi servikasti tagumist piiri?",
        "service line",
        "servijoon",
        "The service line runs parallel to the net and marks the far boundary of the service boxes on a tennis court.",
        "Servijoon kulgeb tenniseväljakul võrguga rööbiti ja märgib servikastide tagumist piiri.",
        [],
        [],
      ],
      [
        "Racket_(sports_equipment)",
        "In tennis, what piece of equipment has a handle and an oval frame filled with strings for hitting the ball?",
        "Millisel tennise mänguvahendil on käepide ja nööridega täidetud ovaalne raam, millega palli lüüakse?",
        "tennis racket",
        "tennisereket",
        "A tennis racket has a handled frame strung with a network of cords used to strike the ball.",
        "Tennisereket on käepidemega ja nööridega kaetud raam, millega lüüakse palli.",
        [],
        [],
      ],
      [
        "Tennis",
        "This barrier stretches across the middle of a tennis court, and the ball must pass over it during play. Name it.",
        "Mis on tõmmatud üle tenniseväljaku keskjoone ning millest peab pall mängu ajal üle lendama?",
        "tennis net",
        "tennisevõrk",
        "The tennis net divides the court, and players strike the ball over it to the opponent’s side.",
        "Tennisevõrk jagab väljaku kaheks ning mängijad löövad palli üle selle vastase poolele.",
        [],
        [],
      ],
      [
        "Official_(tennis)",
        "Which tennis official sits in a raised seat beside the court and announces the score?",
        "Milline tennisekohtunik istub väljaku kõrval kõrgel istmel ja teatab seisu?",
        "chair umpire",
        "pukikohtunik",
        "The chair umpire oversees a tennis match from a raised chair and announces the score.",
        "Pukikohtunik juhib tennisemängu kõrgel istmelt ja teatab seisu.",
        [],
        [],
      ],
      [
        "Ball_boy",
        "Who retrieves loose tennis balls and supplies them to players between points?",
        "Kes korjab punktide vahel tenniseväljakult pallid kokku ja annab need mängijatele?",
        "ball kid",
        "pallilaps",
        "A ball kid retrieves balls that are out of play and provides them to tennis players when needed.",
        "Pallilaps korjab mängust väljas olevad pallid kokku ja annab need vajaduse korral tennisistidele.",
        [],
        [],
      ],
    ],
  ],
  [
    114,
    "round-two",
    "racket-sports",
    "Tennis Champions Across Generations",
    "Eri põlvkondade tennisemeistrid",
    [
      [
        "Novak_Djokovic",
        "This Serbian star is part of men’s tennis’s Big Three alongside Roger Federer and Rafael Nadal. Name him.",
        "See Serbia tennisetäht kuulub koos Roger Federeri ja Rafael Nadaliga meeste tennise suurde kolmikusse. Nimeta ta.",
        "Novak Djokovic",
        "Novak Djokovic",
        "Novak Djokovic is the Serbian member of the group of leading men’s players known as the Big Three.",
        "Novak Djokovic on Serbia tennisist, kes kuulub meeste tennise juhtmängijate rühma, mida tuntakse suure kolmiku nime all.",
        ["Novak Đoković", "Djokovic", "Đoković"],
        ["Novak Đoković", "Djokovic", "Đoković"],
      ],
      [
        "Venus_Williams",
        "This American athlete earned four Olympic gold medals: one individually and three in partnership with her younger sibling. Name her.",
        "See USA sportlane võitis neli olümpiakulda: ühe individuaalselt ja kolm koos oma noorema õega. Nimeta ta.",
        "Venus Williams",
        "Venus Williams",
        "Venus Williams won one Olympic singles gold and three doubles gold medals with her younger sister Serena.",
        "Venus Williams võitis ühe olümpiakulla üksikmängus ja kolm paarismängus koos noorema õe Serenaga.",
        [],
        [],
      ],
      [
        "Maria_Sharapova",
        "This Russian tennis champion won each of the four major singles tournaments during her career, completing a career Grand Slam. Name her.",
        "See Venemaa tennisemeister võitis karjääri jooksul kõik neli suure slämmi üksikmänguturniiri. Nimeta ta.",
        "Maria Sharapova",
        "Maria Šarapova",
        "Maria Sharapova completed a career Grand Slam by winning all four major singles titles.",
        "Maria Šarapova võitis karjääri jooksul kõigi nelja suure slämmi turniiri üksikmängu tiitli.",
        ["Maria Šarapova", "Šarapova", "Sharapova"],
        ["Maria Sharapova", "Šarapova", "Sharapova"],
      ],
      [
        "Martina_Navratilova",
        "This Czech-born tennis champion became an American citizen and is especially famous for her success at Wimbledon. Name her.",
        "See Tšehhoslovakkias sündinud tennisemeister sai USA kodanikuks ja on eriti kuulus oma edu poolest Wimbledonis. Nimeta ta.",
        "Martina Navratilova",
        "Martina Navratilova",
        "Martina Navratilova was born in Czechoslovakia, later became a US citizen and enjoyed exceptional success at Wimbledon.",
        "Martina Navratilova sündis Tšehhoslovakkias, sai hiljem USA kodanikuks ja saavutas Wimbledonis erakordset edu.",
        ["Navratilova"],
        ["Navratilova"],
      ],
      [
        "Andre_Agassi",
        "Which American tennis champion is married to fellow tennis great Steffi Graf?",
        "Milline USA tennisemeister on abielus teise tennisekuulsuse Steffi Grafiga?",
        "Andre Agassi",
        "Andre Agassi",
        "Andre Agassi is an American tennis champion married to fellow former world number one Steffi Graf.",
        "Andre Agassi on USA tennisemeister, kes on abielus endise maailma esireketi Steffi Grafiga.",
        ["Agassi"],
        ["Agassi"],
      ],
    ],
  ],
  [
    115,
    "round-two",
    "racket-sports",
    "Tennis Shots",
    "Tenniselöögid",
    [
      [
        "Volley_(tennis)",
        "In tennis, what shot is struck before the ball bounces on the court?",
        "Kuidas nimetatakse tennises lööki, millega pall saadetakse tagasi enne selle väljakule põrkamist?",
        "volley",
        "lendpall",
        "A volley is a tennis shot in which the ball is struck before it bounces.",
        "Lendpall on tenniselöök, mis tehakse enne palli põrkamist.",
        ["volley shot"],
        ["lendpalli löök"],
      ],
      [
        "Lob_(tennis)",
        "In tennis, what high, arching shot sends the ball over an opponent who has moved close to the net?",
        "Kuidas nimetatakse tennises kõrget kaarega lööki, millega pall saadetakse võrgu lähedale liikunud vastasest üle?",
        "lob",
        "küünalpall",
        "A lob sends the tennis ball in a high arc over an opponent, often when that player is near the net.",
        "Küünalpall saadab tennisepalli kõrge kaarega üle vastase, sageli siis, kui vastane on võrgu lähedal.",
        ["lob shot"],
        ["lob"],
      ],
      [
        "Drop_shot",
        "In tennis, what soft shot is intended to land just over the net, too short for a distant opponent to reach?",
        "Kuidas nimetatakse tennises pehmet lööki, mis peaks maanduma napilt üle võrgu ja jääma tagapool olevale vastasele kättesaamatuks?",
        "drop shot",
        "tilkpall",
        "A drop shot is played softly so the tennis ball lands close to the net on the opponent’s side.",
        "Tilkpall lüüakse pehmelt, et tennisepall maanduks vastase väljakupoolel võrgu lähedal.",
        ["dropshot"],
        ["stopplöök"],
      ],
      [
        "Forehand",
        "In tennis, what stroke is played on the same side of the body as the hand holding the racket?",
        "Kuidas nimetatakse tennises lööki, mis tehakse reketit hoidva käe poolsel kehaküljel?",
        "forehand",
        "eeskäelöök",
        "A forehand is played with the racket on the player’s dominant-hand side of the body.",
        "Eeskäelöök tehakse reketikäe poolsel kehaküljel.",
        [],
        [],
      ],
      [
        "Backhand",
        "In tennis, what stroke travels across the body with the back of the racket hand leading toward the opponent?",
        "Kuidas nimetatakse tennises lööki, mille ajal liigub reket üle keha ja käeselg on vastase poole?",
        "backhand",
        "tagakäelöök",
        "A backhand is played across the body with the back of the hand leading in the direction of the stroke.",
        "Tagakäelöök sooritatakse üle keha nii, et käeselg liigub löögi suunas.",
        [],
        [],
      ],
    ],
  ],
  [
    116,
    "round-two",
    "racket-sports",
    "Racket Sports Beyond Tennis",
    "Reketialad väljaspool tennist",
    [
      [
        "Badminton",
        "Which racket sport sends a feathered or plastic shuttlecock back and forth over a net?",
        "Millises reketimängus lüüakse üle võrgu edasi-tagasi sulgedega või plastist süstikut?",
        "badminton",
        "sulgpall",
        "Badminton is played with rackets and a shuttlecock hit across a net.",
        "Sulgpalli mängitakse reketitega, lüües süstikut üle võrgu.",
        [],
        [],
      ],
      [
        "Squash_(sport)",
        "Which racket sport is played on a small enclosed court where players hit a rubber ball against the front wall?",
        "Millist reketimängu mängitakse väikesel kinnisel väljakul, kus mängijad löövad kummipalli vastu esiseina?",
        "squash",
        "squash",
        "Squash is played on an enclosed court by striking a small rubber ball against the walls, especially the front wall.",
        "Squash'i mängitakse kinnisel väljakul, lüües väikest kummipalli vastu seinu, eelkõige esiseina.",
        ["squash rackets"],
        ["seinatennis"],
      ],
      [
        "Padel",
        "Which racket sport is usually played as doubles on an enclosed court where the surrounding walls remain part of play?",
        "Millist reketiala mängitakse tavaliselt paarismänguna kinnisel väljakul, mille seinad jäävad mängu osaks?",
        "padel",
        "padel",
        "Padel is normally played in doubles on an enclosed court, and balls may be played from the surrounding walls.",
        "Padelit mängitakse tavaliselt paarismänguna kinnisel väljakul ning palli võib mängida ka väljakut ümbritsevatelt seintelt.",
        [],
        [],
      ],
      [
        "Pickleball",
        "Which paddle sport uses a perforated plastic ball on a court with a low net?",
        "Millises reketimängus kasutatakse aukudega plastpalli ja madala võrguga väljakut?",
        "pickleball",
        "pickleball",
        "Pickleball is played with paddles and a hollow perforated plastic ball across a net.",
        "Pickleball'i mängitakse lapikute reketite ja õõnsa aukudega plastpalliga üle võrgu.",
        [],
        [],
      ],
      [
        "Beach_tennis",
        "Which racket sport combines features of tennis and beach volleyball and is played on sand?",
        "Millist tennise ja rannavõrkpalli elemente ühendavat reketiala mängitakse liival?",
        "beach tennis",
        "rannatennis",
        "Beach tennis is a racket sport played on sand that combines elements of tennis and beach volleyball.",
        "Rannatennis on liival mängitav reketiala, mis ühendab tennise ja rannavõrkpalli elemente.",
        [],
        [],
      ],
    ],
  ],
  [
    117,
    "round-two",
    "winter-sports",
    "Ice-Hockey Stars",
    "Jäähokitähed",
    [
      [
        "Wayne_Gretzky",
        "This Canadian ice-hockey star is nicknamed the Great One. Name him.",
        "Seda Kanada jäähokitähte kutsutakse hüüdnimega The Great One ehk Suur. Nimeta ta.",
        "Wayne Gretzky",
        "Wayne Gretzky",
        "Wayne Gretzky is a Canadian ice-hockey legend widely known by the nickname the Great One.",
        "Wayne Gretzky on Kanada jäähokilegend, keda tuntakse laialdaselt hüüdnime The Great One all.",
        ["Gretzky"],
        ["Gretzky"],
      ],
      [
        "Jarom%C3%ADr_J%C3%A1gr",
        "This Czech ice-hockey star won Stanley Cups with Pittsburgh and Olympic gold for his country. Name him.",
        "See Tšehhi jäähokitäht võitis Pittsburghiga Stanley karikaid ja oma riigi koondisega olümpiakulla. Nimeta ta.",
        "Jaromír Jágr",
        "Jaromír Jágr",
        "Jaromír Jágr won two Stanley Cups with the Pittsburgh Penguins and Olympic gold with the Czech Republic.",
        "Jaromír Jágr võitis Pittsburgh Penguinsiga kaks Stanley karikat ja Tšehhi koondisega olümpiakulla.",
        ["Jagr", "Jágr"],
        ["Jagr", "Jágr"],
      ],
      [
        "Alexander_Ovechkin",
        "Which Russian ice-hockey star is famous for scoring goals for the Washington Capitals?",
        "Milline Venemaa jäähokitäht on kuulus Washington Capitalsi eest löödud väravate poolest?",
        "Alexander Ovechkin",
        "Aleksandr Ovetškin",
        "Alexander Ovechkin is a Russian goal scorer closely associated with the Washington Capitals.",
        "Aleksandr Ovetškin on Venemaa väravakütt, kes on tihedalt seotud Washington Capitalsiga.",
        ["Ovetškin", "Ovechkin"],
        ["Ovetškin", "Ovechkin"],
      ],
      [
        "Mario_Lemieux",
        "This Pittsburgh Penguins legend shares the nickname Super Mario with Nintendo’s moustached plumber. Name him.",
        "Sellel Pittsburgh Penguinsi legendil on Nintendo vuntsidega torumehega sama hüüdnimi Super Mario. Nimeta ta.",
        "Mario Lemieux",
        "Mario Lemieux",
        "Mario Lemieux is a Pittsburgh Penguins legend known by the nickname Super Mario.",
        "Mario Lemieux on Pittsburgh Penguinsi legend, keda tuntakse hüüdnime Super Mario all.",
        ["Lemieux"],
        ["Lemieux"],
      ],
      [
        "Teemu_Sel%C3%A4nne",
        "This Finnish ice-hockey star is nicknamed the Finnish Flash. Name him.",
        "Seda Soome jäähokitähte tuntakse hüüdnimega Finnish Flash ehk Soome välk. Nimeta ta.",
        "Teemu Selänne",
        "Teemu Selänne",
        "Teemu Selänne is a Finnish ice-hockey star widely known as the Finnish Flash.",
        "Teemu Selänne on Soome jäähokitäht, keda tuntakse laialdaselt hüüdnime Finnish Flash all.",
        ["Selanne", "Selänne"],
        ["Selanne", "Selänne"],
      ],
    ],
  ],
  [
    118,
    "round-two",
    "winter-sports",
    "Ski-Lift and Slope Basics",
    "Suusatõstuki ja -nõlva põhitõed",
    [
      [
        "Chairlift",
        "At a ski resort, what lift carries people uphill on a moving cable in rows of hanging seats?",
        "Milline suusatõstuk viib inimesed liikuva trossi küljes rippuvatel istmetel mäest üles?",
        "chairlift",
        "tooltõstuk",
        "A chairlift carries passengers uphill on chairs suspended from a continuously moving cable.",
        "Tooltõstuk viib reisijad mäest üles pidevalt liikuva trossi küljes rippuvatel istmetel.",
        [],
        [],
      ],
      [
        "Ski_pole",
        "What hand-held piece of skiing equipment helps with balance and pushing along the snow?",
        "Milline käes hoitav suusavarustuse osa aitab tasakaalu hoida ja lumel edasi tõugata?",
        "ski pole",
        "suusakepp",
        "A ski pole is held in the hand to aid balance, timing and propulsion while skiing.",
        "Suusakeppi hoitakse käes ning see aitab hoida tasakaalu ja rütmi ning liikuda edasi.",
        [],
        [],
      ],
      [
        "Ski_boot",
        "What stiff item of footwear clips into a binding to connect a skier to a ski?",
        "Milline jäik jalats kinnitub sidemesse ja ühendab suusataja suusaga?",
        "ski boot",
        "suusasaabas",
        "A ski boot is designed to attach securely to a ski binding and transfer the skier’s movements to the ski.",
        "Suusasaabas kinnitub kindlalt suusasidemesse ja kannab suusataja liigutused suusale üle.",
        [],
        [],
      ],
      [
        "Goggles",
        "What close-fitting eyewear protects a skier’s eyes from snow, wind and bright glare?",
        "Millised tihedalt näo ümber istuvad prillid kaitsevad suusataja silmi lume, tuule ja ereda peegelduse eest?",
        "ski goggles",
        "suusaprillid",
        "Ski goggles protect the eyes from wind, snow and glare while skiing.",
        "Suusaprillid kaitsevad suusatamisel silmi tuule, lume ja ereda peegelduse eest.",
        [],
        [],
      ],
      [
        "Lift_ticket",
        "What ticket gives a skier access to a resort’s lifts for a set period?",
        "Milline pilet annab suusatajale kindlaks ajaks juurdepääsu suusakeskuse tõstukitele?",
        "ski pass",
        "mäepilet",
        "A ski pass, also called a lift ticket, grants access to a ski area’s lifts for a specified period.",
        "Mäepilet ehk suusapass annab kindlaks ajaks juurdepääsu suusakeskuse tõstukitele.",
        ["lift pass"],
        ["suusapass"],
      ],
    ],
  ],
  [
    119,
    "round-two",
    "winter-sports",
    "Winter-Sport Stars",
    "Talisportlased",
    [
      [
        "Lindsey_Vonn",
        "This American alpine skier became the first US woman to win Olympic downhill gold, at Vancouver 2010. Name her.",
        "See USA mäesuusataja sai 2010. aasta Vancouveri olümpial esimeseks ameeriklannaks, kes võitis kiirlaskumises kulla. Nimeta ta.",
        "Lindsey Vonn",
        "Lindsey Vonn",
        "Lindsey Vonn won the Vancouver 2010 downhill, the first Olympic gold in that event for an American woman.",
        "Lindsey Vonn võitis 2010. aastal Vancouveris kiirlaskumise ning tõi sel alal USA naistele esimese olümpiakulla.",
        ["Vonn"],
        ["Vonn"],
      ],
      [
        "Ole_Einar_Bj%C3%B8rndalen",
        "Known as the “King of Biathlon”, this Norwegian won every men’s biathlon event at the Salt Lake City 2002 Olympics. Name him.",
        "See „laskesuusakuningaks“ kutsutud norralane võitis 2002. aasta Salt Lake City olümpial kõik meeste laskesuusatamise võistlused. Nimeta ta.",
        "Ole Einar Bjørndalen",
        "Ole Einar Bjørndalen",
        "Ole Einar Bjørndalen won the sprint, pursuit, individual race and relay, taking four gold medals in Salt Lake City.",
        "Ole Einar Bjørndalen võitis Salt Lake Citys sprindi, jälitussõidu, tavadistantsi ja teatesõidu ning teenis neli kuldmedalit.",
        ["Bjørndalen", "Bjorndalen"],
        ["Bjørndalen", "Bjorndalen"],
      ],
      [
        "Marit_Bj%C3%B8rgen",
        "This Norwegian cross-country skier won five medals, including three golds, at the Vancouver 2010 Winter Olympics. Name her.",
        "See Norra murdmaasuusataja võitis 2010. aasta Vancouveri taliolümpial viis medalit, sealhulgas kolm kuldmedalit. Nimeta ta.",
        "Marit Bjørgen",
        "Marit Bjørgen",
        "Marit Bjørgen topped the Vancouver 2010 medal table with five medals, including three golds.",
        "Marit Bjørgen oli 2010. aasta Vancouveri olümpia edukaim sportlane: ta võitis viis medalit, sealhulgas kolm kulda.",
        ["Bjørgen", "Bjorgen"],
        ["Bjørgen", "Bjorgen"],
      ],
      [
        "Alberto_Tomba",
        "This charismatic Italian alpine skier won both slalom and giant-slalom gold at the Calgary 1988 Olympics. Name him.",
        "See karismaatiline Itaalia mäesuusataja võitis 1988. aasta Calgary olümpial kulla nii slaalomis kui ka suurslaalomis. Nimeta ta.",
        "Alberto Tomba",
        "Alberto Tomba",
        "Alberto Tomba won both technical alpine-skiing events in Calgary and was popularly nicknamed “Tomba the Bomb”.",
        "Alberto Tomba võitis Calgarys mõlemad mäesuusatamise tehnikaalad ning sai populaarse hüüdnime „Tomba la Bomba“.",
        [],
        [],
      ],
      [
        "Yuzuru_Hanyu",
        "This Japanese figure skater won men’s singles gold at both Sochi 2014 and Pyeongchang 2018, becoming the first man in 66 years to retain the Olympic title. Name him.",
        "See Jaapani iluuisutaja võitis meeste üksiksõidu kulla nii 2014. aastal Sotšis kui ka 2018. aastal Pyeongchangis ning sai esimeseks meheks 66 aasta jooksul, kes kaitses olümpiavõitu. Nimeta ta.",
        "Yuzuru Hanyu",
        "Yuzuru Hanyu",
        "Yuzuru Hanyu won back-to-back Olympic men’s singles titles in 2014 and 2018, a feat no man had achieved for 66 years.",
        "Yuzuru Hanyu võitis 2014. ja 2018. aastal järjest meeste üksiksõidu olümpiakulla; ükski mees polnud seda 66 aastat suutnud.",
        ["Hanyu"],
        ["Hanyu"],
      ],
    ],
  ],
  [
    120,
    "round-two",
    "winter-sports",
    "Hockey-Rink Basics",
    "Jäähokiväljaku põhitõed",
    [
      [
        "Hockey_stick",
        "In ice hockey, what long piece of equipment does a player use to control and shoot the puck?",
        "Millise pika mänguvahendiga juhib ja lööb jäähokimängija litrit?",
        "hockey stick",
        "hokikepp",
        "A hockey stick is the long piece of equipment players use to handle, pass and shoot the puck.",
        "Hokikepp on pikk mänguvahend, millega mängijad juhivad, söödavad ja löövad litrit.",
        [],
        [],
      ],
      [
        "Penalty_box",
        "What rink-side area must an ice-hockey player wait in while serving certain penalties?",
        "Millises väljakuäärses alas peab jäähokimängija teatava karistuse kandmise ajal ootama?",
        "penalty box",
        "karistuspink",
        "The penalty box is the area beside an ice-hockey rink where a penalized player serves time away from play.",
        "Karistuspink on jäähokiväljaku kõrval asuv ala, kus karistatud mängija viibib ajutiselt mängust eemal.",
        [],
        [],
      ],
      [
        "Ice_resurfacer",
        "What machine drives over an ice rink to clean, smooth and renew its frozen surface?",
        "Milline masin sõidab jäähokiväljakul, et puhastada, siluda ja uuendada jääpinda?",
        "ice resurfacer",
        "jääpuhastusmasin",
        "An ice resurfacer cleans and smooths the ice by renewing the rink’s surface between uses.",
        "Jääpuhastusmasin puhastab ja silub jääd, uuendades väljaku pinda kasutuskordade vahel.",
        ["Zamboni"],
        ["Zamboni"],
      ],
      [
        "Ice_hockey_rink",
        "In ice hockey, what is either of the two matching rink markings that divide the ice into defensive, neutral and attacking zones?",
        "Kuidas nimetatakse kumbagi kahest ühesugusest jäähokiväljaku joonest, mis jagavad jää kaitse-, kesk- ja ründetsooniks?",
        "blue line",
        "sinijoon",
        "The two blue lines divide an ice-hockey rink into defensive, neutral and attacking zones.",
        "Kaks sinijoont jagavad jäähokiväljaku kaitse-, kesk- ja ründetsooniks.",
        [],
        [],
      ],
      [
        "Checking_(ice_hockey)",
        "This ice-hockey defensive move uses the shoulder or torso to separate a puck carrier from the puck. Name the move.",
        "See jäähoki kaitsevõte kasutab õlga või keha, et litrit valdav mängija litrist eraldada. Nimeta võte.",
        "body check",
        "jõuvõte",
        "A body check uses a player’s shoulder or body against a puck carrier in an attempt to separate that opponent from the puck.",
        "Jõuvõtte puhul kasutatakse õlga või keha, et eraldada litrit valdav vastane litrist.",
        ["bodychecking"],
        ["kehamäng"],
      ],
    ],
  ],
];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLocaleLowerCase("en")
    .replace(/%[0-9a-f]{2}/giu, "-")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function sourceKey(seed: SourceSeed): string {
  return typeof seed === "string" ? slug(seed) : seed.key;
}

function source(seed: SourceSeed, subjectKey: string): EasyExpansionSource {
  if (typeof seed === "string") {
    return {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(seed).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${seed}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    };
  }
  return {
    sourceId: seed.sourceId,
    title: seed.title,
    url: seed.url,
    license: seed.license,
    retrievedAt: RETRIEVED_AT,
  };
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    sourceSeed,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const identity = sourceKey(sourceSeed);
  const subjectKey = `sports-games:${identity}`;
  return {
    clueId: `built-in-sports-games-easy-expansion-${clueNumber}`,
    key: `sports-games-easy-expansion:${categorySetId}:${tier}`,
    factKey: `sports-games-easy-expansion:${identity}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: source(sourceSeed, subjectKey),
  };
}

export const SPORTS_GAMES_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  SPORTS_GAMES_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
