import type {
  EasyExpansionCategory,
  EasyExpansionQuestion,
  EasyExpansionSource,
} from "../types";

const BATCH_ID = "09-food-drink";
const PACK_ID = "built-in-food-drink";
const RETRIEVED_AT = "2026-09-07";

type DirectSourceSeed = Readonly<{
  key: string;
  sourceId: string;
  title: string;
  url: string;
  license: string;
}>;

type SourceSeed = string | DirectSourceSeed;

type QuestionSeed = readonly [
  source: SourceSeed,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const FOOD_DRINK_EASY_EXPANSION_SEEDS: readonly CategorySeed[] = [
  [
    101,
    "round-one",
    "world-cuisines",
    "Everyday Dining",
    "Igapäevane väljas söömine",
    [
      [
        "Table_reservation",
        "Before arriving, diners make this booking so a restaurant will hold a table for them. Name it.",
        "Enne kohalejõudmist teevad sööjad selle broneeringu, et restoran neile laua hoiaks. Nimeta see.",
        "table reservation",
        "laua broneerimine",
        "A table reservation is a booking made before arrival so a restaurant keeps a table available for the diners.",
        "Laua broneerimine tähendab, et enne saabumist pannakse restoranis sööjate jaoks laud kinni.",
        ["restaurant reservation"],
        ["lauabroneering"],
      ],
      [
        "Drive-through",
        "This service lets customers order and collect food without leaving their car. Name it.",
        "See teenus võimaldab klientidel toitu tellida ja kätte saada autost väljumata. Nimeta see.",
        "drive-through",
        "drive-through",
        "A drive-through serves customers while they remain in their vehicle for ordering and collection.",
        "Drive-through võimaldab klientidel nii tellida kui ka toidu kätte saada autost lahkumata.",
        ["drive-thru"],
        ["autoga läbisõiduteenus"],
      ],
      [
        "Buffet",
        "At this kind of meal, diners choose from several shared dishes and serve themselves. Name it.",
        "Seda tüüpi einel valivad sööjad mitme ühise roa seast ja tõstavad endale ise toitu. Nimeta see.",
        "buffet",
        "Rootsi laud",
        "A buffet offers several shared dishes from which diners serve themselves.",
        "Rootsi lauas on mitu ühist rooga, mille seast sööjad endale ise toitu tõstavad.",
        ["self-service buffet"],
        ["buffet"],
      ],
      [
        "Cafeteria",
        "This simple self-service dining place is commonly found at a school or workplace. Name it.",
        "See lihtne iseteeninduslik söögikoht asub sageli koolis või töökohal. Nimeta see.",
        "canteen",
        "söökla",
        "A canteen is a simple place at a school or workplace where people usually select and collect their own food.",
        "Söökla on kooli või töökoha lihtne söögikoht, kus inimesed valivad ja võtavad oma toidu tavaliselt ise.",
        ["cafeteria"],
        ["iseteenindussöökla"],
      ],
      [
        {
          key: "govuk-restaurant-service-charges",
          sourceId: "source:food-drink:govuk-restaurant-service-charges",
          title: "GOV.UK: Restaurant service charges",
          url: "https://www.gov.uk/hmrc-internal-manuals/national-insurance-manual/nim02915",
          license: "OGL-3.0",
        },
        "A restaurant may add this fee to the bill for the service provided. Name it.",
        "Restoran võib lisada arvele selle tasu osutatud teeninduse eest. Nimeta see.",
        "service charge",
        "teenindustasu",
        "A service charge is a fee added to a restaurant bill for providing service.",
        "Teenindustasu on restoranis teeninduse eest arvele lisatav tasu.",
        [],
        [],
      ],
    ],
  ],
  [
    102,
    "round-one",
    "world-cuisines",
    "Familiar Food Brands",
    "Tuttavad toidubrändid",
    [
      [
        "KFC",
        "Buckets and a recipe described as eleven herbs and spices point to this three-letter fast-food chain. Name it.",
        "Ämbrid ning üheteistkümne ürdi ja vürtsi retsept viitavad sellele kolmetähelisele kiirtoiduketile. Nimeta see.",
        "KFC",
        "KFC",
        "KFC is a fast-food chain known for bucket meals and a recipe described as a blend of eleven herbs and spices.",
        "KFC on kiirtoidukett, mida tuntakse ämbris pakutavate einete ning üheteistkümne ürdi ja vürtsi seguna kirjeldatud retsepti järgi.",
        ["Kentucky Fried Chicken"],
        ["Kentucky Fried Chicken"],
      ],
      [
        "Oreo",
        "This black-and-white filled biscuit is often twisted apart before it is eaten. Name the brand.",
        "Seda mustvalget täidisega küpsist keeratakse enne söömist sageli kaheks. Nimeta bränd.",
        "Oreo",
        "Oreo",
        "An Oreo has two dark biscuit pieces around a pale sweet filling and is often eaten by twisting the halves apart.",
        "Oreo koosneb kahest tumedast küpsisepoolest ja nende vahel olevast heledast magusast täidisest ning pooled keeratakse sageli lahku.",
        [],
        [],
      ],
      [
        "Heinz",
        "The slogan “57 varieties” is closely associated with ketchup from this brand. Name it.",
        "Loosungit „57 sorti“ seostatakse tihedalt selle brändi ketšupiga. Nimeta bränd.",
        "Heinz",
        "Heinz",
        "Heinz is a food brand whose ketchup has long been associated with the “57 varieties” slogan.",
        "Heinz on toidubränd, mille ketšupit seostatakse juba ammu loosungiga „57 sorti“.",
        ["H. J. Heinz"],
        ["H. J. Heinz"],
      ],
      [
        "Nescaf%C3%A9",
        "This Nestlé instant-coffee brand joins the company name with the French word for coffee. Name it.",
        "Selle Nestlé lahustuva kohvi brändi nimi ühendab ettevõtte nime prantsuskeelse kohvisõnaga. Nimeta bränd.",
        "Nescafé",
        "Nescafé",
        "Nescafé is Nestlé's instant-coffee brand, and its name combines Nestlé with the French word café.",
        "Nescafé on Nestlé lahustuva kohvi bränd, mille nimi ühendab Nestlé nime prantsuskeelse sõnaga café.",
        ["Nescafe"],
        ["Nescafe"],
      ],
      [
        "Kellogg%27s",
        "Frosties and Coco Pops boxes carry the name of this breakfast-cereal company. Name it.",
        "Frostiesi ja Coco Popsi pakenditel on selle hommikuhelbefirma nimi. Nimeta ettevõte.",
        "Kellogg's",
        "Kellogg's",
        "Kellogg's is the breakfast-cereal company behind brands including Frosties and Coco Pops.",
        "Kellogg's on hommikuhelbefirma, mille brändide hulka kuuluvad Frosties ja Coco Pops.",
        [],
        [],
      ],
    ],
  ],
  [
    103,
    "round-one",
    "world-cuisines",
    "Takeaway Favourites",
    "Kaasavõetavad lemmikud",
    [
      [
        "Fish_and_chips",
        "A battered fish fillet beside thick fried potato pieces makes this famous British takeaway. Name it.",
        "Tainas praetud kalafilee koos paksude praetud kartulitükkidega moodustab selle kuulsa Briti kaasavõetava roa. Nimeta roog.",
        "fish and chips",
        "kala friikartulitega",
        "Fish and chips pairs battered fried fish with thick-cut fried potatoes and is a well-known British takeaway meal.",
        "Kala friikartulitega ühendab tainas praetud kala ja paksud praetud kartulid ning on tuntud Briti kaasavõetav roog.",
        [],
        [],
      ],
      [
        "Chicken_nugget",
        "Small breaded poultry pieces sold in fast-food boxes go by this name. Give it.",
        "Väikesi paneeritud kanalihatükke müüakse kiirtoidukarpides selle nime all. Nimeta need.",
        "chicken nuggets",
        "kananagitsad",
        "Chicken nuggets are small pieces of poultry meat that are breaded and cooked as bite-size fast food.",
        "Kananagitsad on väikesed paneeritud kanalihatükid, mida pakutakse suupärase kiirtoiduna.",
        ["chicken nugget"],
        ["kananagits"],
      ],
      [
        "Fried_chicken",
        "Crisp-coated wings or drumsticks cooked in hot oil make this takeaway favourite. Name it.",
        "Krõbeda kattega tiibadest või koibadest, mida küpsetatakse kuumas õlis, valmib see kaasavõetav lemmikroog. Nimeta roog.",
        "fried chicken",
        "krõbekana",
        "Fried chicken consists of poultry pieces such as wings or drumsticks coated and cooked in hot oil until crisp.",
        "Krõbekana koosneb kattega kanalihatükkidest, näiteks tiibadest või koibadest, mis praetakse kuumas õlis krõbedaks.",
        [],
        [],
      ],
      [
        "Onion_ring",
        "Round slices cut from a layered bulb vegetable are coated in batter and fried for this side dish. Name it.",
        "Kihilise mugulköögivilja ümmargused viilud kaetakse tainaga ja praetakse selle lisandi valmistamiseks. Nimeta lisand.",
        "onion rings",
        "sibularõngad",
        "Onion rings are round slices of onion coated in batter or crumbs and fried.",
        "Sibularõngad on ümmargused sibulaviilud, mis kaetakse taina või paneeringuga ja praetakse.",
        ["onion ring"],
        ["sibularõngas"],
      ],
      [
        "Doner_kebab",
        "Seasoned meat shaved from a vertical rotisserie and placed in flatbread makes this Turkish takeaway. Name it.",
        "Püstvardalt lõigatud maitsestatud liha pannakse lapiku saia sisse selles Türgi kaasavõetavas roas. Nimeta roog.",
        "doner kebab",
        "döner kebab",
        "Doner kebab is a Turkish dish of seasoned meat cooked on a vertical rotisserie, sliced off and commonly served in flatbread.",
        "Döner kebab on Türgi roog, mille maitsestatud liha küpsetatakse püstvardal, lõigatakse sealt õhukeselt maha ja pannakse sageli lapiku saia sisse.",
        ["doner"],
        ["döner"],
      ],
    ],
  ],
  [
    104,
    "round-one",
    "world-cuisines",
    "Familiar Asian Menu",
    "Tuttav Aasia menüü",
    [
      [
        "Wasabi",
        "This sharp green Japanese paste tastes similar to hot mustard or horseradish. Name it.",
        "See terav roheline Jaapani pasta maitseb sarnaselt kange sinepi või mädarõikaga. Nimeta see.",
        "wasabi",
        "vasabi",
        "Wasabi is a pungent green Japanese paste with a flavour often compared with hot mustard or horseradish.",
        "Vasabi on terav roheline Jaapani pasta, mille maitset võrreldakse sageli kange sinepi või mädarõikaga.",
        ["Japanese horseradish"],
        ["wasabi"],
      ],
      [
        "Dim_sum",
        "Small Cantonese dishes shared around the table and traditionally eaten with tea have this collective name. Give it.",
        "Väikesi Kantoni roogi, mida lauas jagatakse ja traditsiooniliselt tee kõrvale süüakse, nimetatakse selle koondnimega. Nimeta see.",
        "dim sum",
        "dim sum",
        "Dim sum is a Cantonese meal of small dishes traditionally shared at the table with tea.",
        "Dim sum on Kantoni eine väikestest roogadest, mida traditsiooniliselt lauas jagatakse ja tee kõrvale süüakse.",
        [],
        [],
      ],
      [
        "Teriyaki",
        "A glossy, sweet soy-based glaze defines this Japanese cooking style. Name it.",
        "Läikiv magus sojapõhine glasuur iseloomustab seda Jaapani valmistusviisi. Nimeta see.",
        "teriyaki",
        "teriyaki",
        "Teriyaki is a Japanese cooking style in which food is given a glossy glaze based on soy sauce and sugar.",
        "Teriyaki on Jaapani valmistusviis, mille puhul toit saab läikiva sojakastmel ja suhkrul põhineva glasuuri.",
        [],
        [],
      ],
      [
        "Udon",
        "These thick, pale Japanese wheat noodles are often served in a hot broth. Name them.",
        "Neid pakse heledaid Jaapani nisunuudleid serveeritakse sageli kuumas puljongis. Nimeta need.",
        "udon",
        "udon",
        "Udon is a thick Japanese noodle made from wheat flour and commonly served in broth.",
        "Udon on paks nisujahust valmistatud Jaapani nuudel, mida serveeritakse sageli puljongis.",
        [],
        [],
      ],
      [
        "Wonton",
        "Small filled dough parcels floating in Chinese broth make this familiar menu dish. Name it.",
        "Väikestest täidisega tainataskutest Hiina puljongis koosneb see tuttav menüüroog. Nimeta roog.",
        "wonton soup",
        "wontonisupp",
        "Wonton soup is a Chinese broth containing small dough parcels wrapped around a filling.",
        "Wontonisupp on Hiina puljong, milles on väikesed täidise ümber keeratud tainataskud.",
        ["won ton soup"],
        ["wontoni supp"],
      ],
    ],
  ],
  [
    105,
    "round-one",
    "dishes",
    "Quick Food",
    "Kiirelt valmiv toit",
    [
      [
        "Instant_noodles",
        "Dried noodle strands in a packet or cup need only hot water and a few minutes. Name this quick food.",
        "Pakis või topsis olevad kuivatatud nuudlid vajavad vaid kuuma vett ja mõnda minutit. Nimeta see kiire toit.",
        "instant noodles",
        "kiirnuudlid",
        "Instant noodles are dried noodles sold with seasoning in a packet or cup and prepared in minutes with hot water.",
        "Kiirnuudlid on maitseainega pakis või topsis müüdavad kuivatatud nuudlid, mis valmivad kuuma veega mõne minutiga.",
        [],
        [],
      ],
      [
        "Frozen_pizza",
        "This topped flat round is stored below zero until it goes into the oven. Name it.",
        "Seda kattega lamedat ümmargust toitu hoitakse miinuskraadidel, kuni see läheb ahju. Nimeta toit.",
        "frozen pizza",
        "külmutatud pitsa",
        "This prepared topped round is stored below zero and baked before eating.",
        "Külmutatud pitsa valmistatakse koos kattega, hoitakse sügavkülmas ja küpsetatakse enne söömist.",
        [],
        [],
      ],
      [
        {
          key: "wiktionary-ready-meal",
          sourceId: "source:food-drink:wiktionary-ready-meal",
          title: "Wiktionary: ready meal",
          url: "https://en.wiktionary.org/wiki/ready_meal",
          license: "CC-BY-SA-4.0",
        },
        "This complete prepackaged dish needs no preparation beyond heating and may be warmed in its own tray. Name it.",
        "See terviklik pakendatud roog ei vaja peale soojendamise muud valmistamist ja seda võib kuumutada oma alusel. Nimeta roog.",
        "ready meal",
        "valmistoit",
        "A ready meal is a fresh or frozen prepackaged dish that only needs heating, sometimes in its own packaging.",
        "Valmistoit on värske või külmutatud pakendatud roog, mida on vaja ainult soojendada, mõnikord samas pakendis.",
        [],
        [],
      ],
      [
        "Energy_bar",
        "This compact packaged snack bar takes its first word from the quantity that food labels measure in calories or kilojoules. Name it.",
        "Selle väikese pakendatud batooni nime esimene pool viitab näitajale, mida toidupakendil väljendatakse kalorites või kilodžaulides. Nimeta batoon.",
        "energy bar",
        "energiabatoon",
        "An energy bar is a compact packaged snack designed to provide food energy conveniently.",
        "Energiabatoon on väike pakendatud suupiste, mis on mõeldud mugavaks energia saamiseks.",
        [],
        [],
      ],
      [
        "Microwave_popcorn",
        "Kernels sold in a folded paper bag expand along with the bag as they heat. Name this snack.",
        "Volditud paberkotis müüdavad terad paisuvad kuumutamisel koos kotiga. Nimeta see suupiste.",
        "microwave popcorn",
        "mikrolainepopkorn",
        "Microwave popcorn comes as kernels in a folded paper bag that expands while the kernels pop during heating.",
        "Mikrolainepopkorni terad on volditud paberkotis, mis terade kuumutamisel ja paisumisel suuremaks muutub.",
        ["microwave popcorn bag"],
        ["mikrolaineahju popkorn"],
      ],
    ],
  ],
  [
    106,
    "round-one",
    "dishes",
    "Comfort-Food Favourites",
    "Kodused lemmiktoidud",
    [
      [
        "Cabbage_roll",
        "Leaves from the vegetable also used for sauerkraut are cooked and wrapped around a savoury meat-and-grain filling. Name these parcels.",
        "Hapukapsa valmistamiseks kasutatava köögivilja lehed keedetakse ning keeratakse soolase liha- ja teraviljatäidise ümber. Nimeta need pakikesed.",
        "cabbage rolls",
        "kapsarullid",
        "Cabbage rolls are cooked cabbage leaves wrapped around a savoury filling that often combines meat and grain.",
        "Kapsarullid on keedetud kapsalehed, mis keeratakse sageli lihast ja teraviljast koosneva soolase täidise ümber.",
        ["cabbage roll"],
        ["kapsarull"],
      ],
      [
        "Macaroni_and_cheese",
        "Short pasta covered in a creamy cheese sauce makes this comfort-food favourite. Name it.",
        "Lühikesed makaronid kreemises juustukastmes moodustavad selle koduse lemmikroa. Nimeta roog.",
        "mac and cheese",
        "makaronid juustuga",
        "Mac and cheese combines cooked macaroni with a creamy cheese sauce.",
        "Makaronid juustuga on roog, milles keedetud makaronid kaetakse kreemja juustukastmega.",
        ["macaroni and cheese"],
        ["juustumakaronid"],
      ],
      [
        "Chicken_soup",
        "This warm poultry broth is often served to someone who has a cold. Name the dish.",
        "Seda sooja linnulihapuljongit pakutakse sageli külmetunud inimesele. Nimeta roog.",
        "chicken soup",
        "kanasupp",
        "Chicken soup is a warm broth made with poultry and is commonly eaten as comfort food during a cold.",
        "Kanasupp on soe linnulihast valmistatud puljong, mida süüakse külmetuse ajal sageli lohutustoiduna.",
        [],
        [],
      ],
      [
        "Meatloaf",
        "Seasoned minced meat is shaped like a loaf of bread and baked for this dish. Name it.",
        "Selle roa valmistamiseks vormitakse maitsestatud hakkliha leivapätsi kujuliseks ja küpsetatakse. Nimeta roog.",
        "meatloaf",
        "pikkpoiss",
        "Meatloaf is made by shaping seasoned minced meat into a loaf and baking it.",
        "Pikkpoiss valmistatakse maitsestatud hakkliha pätsiks vormides ja küpsetades.",
        ["meat loaf"],
        ["hakklihapäts"],
      ],
      [
        "Grilled_cheese",
        "Bread slices are browned around a layer of melted cheese in this hot sandwich. Name it.",
        "Selle kuuma võileiva valmistamisel röstitakse saiaviilud, mille vahel on kiht sulanud juustu. Nimeta võileib.",
        "grilled cheese sandwich",
        "juusturöstsai",
        "A grilled cheese sandwich is made by browning bread around a filling dominated by melted cheese.",
        "Juusturöstsai valmistatakse saiaviile pruunistades nii, et nendevaheline täidis koosneb peamiselt sulanud juustust.",
        ["grilled cheese"],
        ["grillitud juustuvõileib"],
      ],
    ],
  ],
  [
    107,
    "round-one",
    "dishes",
    "Snacks and Sides",
    "Suupisted ja lisandid",
    [
      [
        "Potato_chips",
        "Thin crisp potato slices are sold salted in a snack bag under this name. Give it.",
        "Õhukesi krõbedaid kartuliviile müüakse soolasena suupistepakis selle nime all. Nimeta need.",
        "potato chips",
        "kartulikrõpsud",
        "Potato chips are thin slices of potato cooked until crisp and commonly sold salted in bags.",
        "Kartulikrõpsud on õhukesed krõbedaks küpsetatud kartuliviilud, mida müüakse sageli soolasena pakis.",
        ["potato crisps"],
        ["kartulikrõps"],
      ],
      [
        "Potato_wedges",
        "Thick skin-on potato pieces are cut lengthwise and baked or fried until crisp outside. Name this side.",
        "Paksud koorega kartulitükid lõigatakse pikuti ja küpsetatakse või praetakse väljast krõbedaks. Nimeta lisand.",
        "potato wedges",
        "kartulilohud",
        "Potato wedges are thick lengthwise pieces of potato, often left with the skin on, then baked or fried.",
        "Kartulilohud on paksud pikuti lõigatud kartulitükid, millele jäetakse sageli koor ning mis seejärel küpsetatakse või praetakse.",
        ["potato wedge"],
        ["kartulilohk"],
      ],
      [
        "Gummy_bear",
        "Colourful chewy sweets shaped like tiny bears have this familiar name. Give it.",
        "Värvilistel nätsketel maiustustel, mis on väikeste karude kujulised, on see tuttav nimi. Nimeta need.",
        "gummy bears",
        "kummikommikarud",
        "Gummy bears are small, chewy, colourful sweets moulded into the shape of bears.",
        "Kummikommikarud on väikesed nätsked värvilised maiustused, mis vormitakse karude kujuliseks.",
        ["gummy bear"],
        ["kummikommikaru"],
      ],
      [
        "Mozzarella_sticks",
        "Elongated cheese pieces are coated in batter or breadcrumbs and usually served as an appetiser. Name them.",
        "Pikad juustutükid kaetakse taina või riivsaiaga ja serveeritakse tavaliselt eelroana. Nimeta need.",
        "mozzarella sticks",
        "mozzarellapulgad",
        "Mozzarella sticks are elongated pieces of mozzarella coated in batter or breadcrumbs and usually served as an appetiser.",
        "Mozzarellapulgad on pikad mozzarella tükid, mis kaetakse taina või riivsaiaga ja mida serveeritakse tavaliselt eelroana.",
        ["mozzarella stick"],
        ["mozzarellapulk"],
      ],
      [
        "Cheese_puffs",
        "Light airy corn snacks coated in cheese-flavoured powder go by this name. Give it.",
        "Kergeid õhulisi maisisuupisteid, mis on kaetud juustumaitselise pulbriga, nimetatakse selle nimega. Nimeta need.",
        "cheese puffs",
        "juustupallid",
        "Cheese puffs are airy puffed-corn snacks covered with cheese-flavoured powder.",
        "Juustupallid on õhulised paisutatud maisist suupisted, mis kaetakse juustumaitselise pulbriga.",
        ["cheese puff"],
        ["juustupall"],
      ],
    ],
  ],
  [
    108,
    "round-one",
    "world-cuisines",
    "Food Characters on Screen",
    "Toidutegelased ekraanil",
    [
      [
        "Popeye",
        "This cartoon sailor becomes strong after opening a can of leafy greens. Name him.",
        "See multifilmimeremees muutub tugevaks pärast roheliste lehtede konservi avamist. Nimeta ta.",
        "Popeye",
        "Popeye",
        "Popeye is a cartoon sailor whose strength increases after he eats canned leafy greens.",
        "Popeye on multifilmimeremees, kelle jõud kasvab pärast roheliste lehtede konservi söömist.",
        ["Popeye the Sailor"],
        ["meremees Popeye"],
      ],
      [
        "Ronald_McDonald",
        "This clown character is the primary mascot of a global burger chain. Name him.",
        "See klounitegelane on üleilmse burgeriketi peamine maskott. Nimeta ta.",
        "Ronald McDonald",
        "Ronald McDonald",
        "Ronald McDonald is the clown character used as the primary mascot of a global fast-food chain.",
        "Ronald McDonald on klounitegelane, keda üleilmne kiirtoidukett kasutab oma peamise maskotina.",
        [],
        [],
      ],
      [
        "Cookie_Monster",
        "This furry blue Sesame Street puppet is famous for eagerly devouring baked treats. Name him.",
        "See karvane sinine Seesamitänava nukk on tuntud küpsetatud maiuste innuka söömise poolest. Nimeta ta.",
        "Cookie Monster",
        "Küpsisekoletis",
        "Cookie Monster is the furry blue Sesame Street puppet known for his enthusiastic appetite for baked treats.",
        "Küpsisekoletis on karvane sinine Seesamitänava nukk, keda tuntakse tema tohutu küpsetatud maiuste isu poolest.",
        ["Sesame Street's Cookie Monster"],
        ["Küpsisekoll"],
      ],
      [
        "Joey_Tribbiani",
        "Matt LeBlanc plays this food-loving sitcom character whose emphatic rule is that he does not share food. Name him.",
        "Matt LeBlanc kehastab seda sööki armastavat komöödiategelast, kelle kindel reegel on, et ta ei jaga toitu. Nimeta ta.",
        "Joey Tribbiani",
        "Joey Tribbiani",
        "Joey Tribbiani is Matt LeBlanc's food-loving sitcom character, remembered for insisting that he does not share food.",
        "Joey Tribbiani on Matt LeBlanci kehastatud sööki armastav komöödiategelane, kelle tuntud reegel on, et ta ei jaga toitu.",
        [],
        [],
      ],
      [
        "Mr._Krabs",
        "This money-loving red crab owns an underwater fast-food restaurant. Name him.",
        "Sellele rahahimulisele punasele krabile kuulub veealune kiirtoidurestoran. Nimeta ta.",
        "Mr. Krabs",
        "härra Krabs",
        "Mr. Krabs is a money-loving red crab who owns an underwater fast-food restaurant.",
        "Härra Krabs on rahahimuline punane krabi, kellele kuulub veealune kiirtoidurestoran.",
        ["Mister Krabs"],
        ["hr Krabs"],
      ],
    ],
  ],
  [
    109,
    "round-one",
    "ingredients",
    "The Baking Cupboard",
    "Küpsetusained kapis",
    [
      [
        {
          key: "wiktionary-cake-mix",
          sourceId: "source:food-drink:wiktionary-cake-mix",
          title: "Wiktionary: cake mix",
          url: "https://en.wiktionary.org/wiki/cake_mix",
          license: "CC-BY-SA-4.0",
        },
        "This powdered blend combines the dry ingredients needed to make a cake. Name it.",
        "See pulbriline segu ühendab koogi valmistamiseks vajalikud kuivained. Nimeta see.",
        "cake mix",
        "koogisegu",
        "A cake mix is a powdered blend of dry ingredients prepared for making a cake.",
        "Koogisegu on koogi valmistamiseks mõeldud kuivainete pulbriline segu.",
        ["dry cake mix"],
        ["koogipulber"],
      ],
      [
        "Chocolate_chip",
        "Small drops of chocolate are folded into batter before baking. Name these cupboard ingredients.",
        "Need väikesed vormitud šokolaadipalad segatakse enne küpsetamist tainasse. Nimeta need.",
        "chocolate chips",
        "šokolaaditükid",
        "Chocolate chips are small shaped pieces of chocolate made to be mixed into dough or batter for baking.",
        "Šokolaaditükid on väikesed vormitud šokolaadipalad, mis segatakse küpsetamisel tainasse.",
        ["chocolate chip", "chocolate morsels"],
        ["šokolaaditükk", "šokolaaditilgad"],
      ],
      [
        "Cocoa_powder",
        "This unsweetened brown baking ingredient comes from cacao beans and flavours chocolate cakes. Name it.",
        "See kakaoubadest saadud magustamata pruun küpsetusaine annab šokolaadikookidele maitse. Nimeta see.",
        "cocoa powder",
        "kakaopulber",
        "Cocoa powder is an unsweetened brown product of cacao beans used to give baked goods a chocolate flavour.",
        "Kakaopulber on kakaoubadest saadud magustamata pruun toode, millega antakse küpsetistele šokolaadimaitse.",
        [],
        [],
      ],
      [
        "Corn_starch",
        "This fine white maize product is stirred into sauces to make them thicker. Name it.",
        "Seda peent valget maisitoodet segatakse kastmetesse, et neid paksendada. Nimeta aine.",
        "cornstarch",
        "maisitärklis",
        "Cornstarch is a fine white starch made from maize and commonly used to thicken sauces.",
        "Maisitärklis on maisist saadud peen valge tärklis, mida kasutatakse sageli kastmete paksendamiseks.",
        [],
        [],
      ],
      [
        "Vanilla_extract",
        "This fragrant baking liquid is traditionally made by soaking aromatic pods. Name it.",
        "Seda lõhnavat küpsetusvedelikku valmistatakse traditsiooniliselt aromaatseid kaunu leotades. Nimeta see.",
        "vanilla extract",
        "vanilliekstrakt",
        "Vanilla extract is a flavouring liquid made by soaking or macerating vanilla pods in alcohol and water.",
        "Vanilliekstrakt on maitsevedelik, mida valmistatakse vanillikaunu alkoholi ja vee lahuses leotades.",
        [],
        [],
      ],
    ],
  ],
  [
    110,
    "round-one",
    "ingredients",
    "The Dairy Aisle",
    "Piimatoodete lett",
    [
      [
        "Lactose-free_milk",
        "This familiar dairy drink is treated so that its natural sugar is removed or broken down. Name it.",
        "Seda tuttavat piimajooki töödeldakse nii, et selle looduslik suhkur eemaldatakse või lagundatakse. Nimeta jook.",
        "lactose-free milk",
        "laktoosivaba piim",
        "Lactose-free milk is treated by removing its lactose or breaking that sugar down with an enzyme.",
        "Laktoosivaba piima valmistamisel eemaldatakse sellest laktoos või lagundatakse see suhkur ensüümi abil.",
        [],
        [],
      ],
      [
        "Cottage_cheese",
        "This mild fresh dairy product has visible small curds and is commonly sold in tubs. Name it.",
        "See mahe värske piimatoode on nähtavalt teraline ja seda müüakse sageli topsis. Nimeta see.",
        "cottage cheese",
        "kodujuust",
        "Cottage cheese is a mild fresh cheese made of small, visible curds and often packaged in a tub.",
        "Kodujuust on mahe värske piimatoode, mis koosneb väikestest nähtavatest teradest ja mida müüakse sageli topsis.",
        [],
        [],
      ],
      [
        "Milk",
        "This standard white dairy drink keeps its usual fat content instead of having cream removed. Name it.",
        "Selle tavalise valge piimajoogi rasvasisaldust ei vähendata koore eemaldamisega. Nimeta jook.",
        "whole milk",
        "täispiim",
        "Whole milk retains its normal milk-fat level rather than having fat reduced through the removal of cream.",
        "Täispiimas säilib tavapärane piimarasvasisaldus, sest seda ei vähendata koore eemaldamisega.",
        ["full-fat milk"],
        ["täisrasvane piim"],
      ],
      [
        "Smoked_cheese",
        "Exposure to smoke gives this cheese a distinctive flavour and a brownish rind. Name it.",
        "Suitsuga kokkupuutel saab see juust erilise maitse ja pruunika kooriku. Nimeta juust.",
        "smoked cheese",
        "suitsujuust",
        "Smoked cheese is exposed to smoke, which gives it a characteristic flavour and often a brownish outer colour.",
        "Suitsujuust puutub kokku suitsuga, mis annab sellele iseloomuliku maitse ja sageli pruunika välispinna.",
        [],
        [],
      ],
      [
        "Quark_(dairy_product)",
        "Souring milk and straining the curds produces this soft white unaged dairy product. Name it.",
        "Piima hapendamisel ja kalgendi nõrutamisel saadakse see pehme valge laagerdamata piimatoode. Nimeta see.",
        "quark",
        "kohupiim",
        "Quark is a soft white unaged dairy product made by souring milk and straining the resulting curds.",
        "Kohupiim on pehme valge laagerdamata piimatoode, mis valmistatakse piima hapendades ja tekkinud kalgendit nõrutades.",
        ["curd cheese"],
        ["vaarapiim"],
      ],
    ],
  ],

  [
    111,
    "round-two",
    "non-alcoholic-drinks",
    "Everyday Drink Types",
    "Igapäevased joogiliigid",
    [
      [
        "Tap_water",
        "This everyday drinking supply comes straight from an indoor household faucet. Name it.",
        "See igapäevane joogivesi tuleb kodus otse siseruumis asuvast segistist. Nimeta see.",
        "tap water",
        "kraanivesi",
        "Tap water is drinking water supplied through indoor plumbing to a faucet.",
        "Kraanivesi on joogivesi, mis jõuab siseruumis asuva kraanini torustiku kaudu.",
        [],
        [],
      ],
      [
        "Enhanced_water",
        "A still bottled drink has fruit or another flavour added and may also contain sweeteners or vitamins. Name the drink type.",
        "Sellele gaseerimata pudelijoogile lisatakse puuvilja- või muud maitset ning vahel ka magustajaid või vitamiine. Nimeta joogiliik.",
        "flavoured water",
        "maitsestatud vesi",
        "Flavoured water is non-carbonated water with added flavouring and may also include sweeteners or vitamins.",
        "Maitsestatud vesi on gaseerimata vesi, millele on lisatud maitset ning vahel ka magustajaid või vitamiine.",
        ["flavored water"],
        ["maitsevesi"],
      ],
      [
        "Energy_drink",
        "Marketed as a pick-me-up for alertness and often containing caffeine, this beverage has what generic name?",
        "Seda jooki müüakse erksuse suurendajana ning see sisaldab sageli kofeiini. Mis on selle joogiliigi üldnimetus?",
        "energy drink",
        "energiajook",
        "Energy drinks are marketed to increase alertness and commonly contain caffeine.",
        "Energiajooke müüakse erksuse suurendajatena ning need sisaldavad sageli kofeiini.",
        [],
        [],
      ],
      [
        "Vegetable_juice",
        "Carrots or tomatoes are pressed or blended into this savoury drink. Name it.",
        "Porganditest või tomatitest pressitakse või püreestatakse see soolakas jook. Nimeta see.",
        "vegetable juice",
        "köögiviljamahl",
        "Vegetable juice is made by blending vegetables or extracting their liquid; carrots and tomatoes are common ingredients.",
        "Köögiviljamahla saadakse köögiviljade püreestamisel või neist vedeliku pressimisel; sageli kasutatakse porgandeid või tomateid.",
        [],
        [],
      ],
      [
        "Coconut_water",
        "The clear liquid naturally found inside a young green tropical fruit is sold as this drink. Name it.",
        "Noore rohelise troopilise vilja sees leiduvat läbipaistvat vedelikku müüakse selle joogina. Nimeta see.",
        "coconut water",
        "kookosvesi",
        "Coconut water is the clear liquid naturally found inside young green coconuts.",
        "Kookosvesi on läbipaistev vedelik, mida leidub looduslikult noorte roheliste kookospähklite sees.",
        [],
        [],
      ],
    ],
  ],
  [
    112,
    "round-two",
    "cooking-techniques",
    "Prep and Finish",
    "Ettevalmistus ja viimistlus",
    [
      [
        {
          key: "wiktionary-peeling",
          sourceId: "source:food-drink:wiktionary-peeling",
          title: "Wiktionary: peeling",
          url: "https://en.wiktionary.org/wiki/peeling",
          license: "CC-BY-SA-4.0",
        },
        "Removing the outer skin from an apple, potato or carrot before eating or cooking is called this. Name the action.",
        "Kuidas nimetatakse õuna, kartuli või porgandi väliskihi eemaldamist enne söömist või toiduvalmistamist?",
        "peeling",
        "koorimine",
        "Peeling is the action of removing an outer skin or layer from food.",
        "Koorimine tähendab toidu väliskihi või koore eemaldamist.",
        [],
        [],
      ],
      [
        {
          key: "wiktionary-grate",
          sourceId: "source:food-drink:wiktionary-grate",
          title: "Wiktionary: grate",
          url: "https://en.wiktionary.org/wiki/grate",
          license: "CC-BY-SA-4.0",
        },
        "Rubbing a carrot across a surface of sharp holes to make small shreds is this kitchen action. Name it.",
        "Porgandi hõõrumine vastu teravate aukudega pinda, et saada väikesed ribad, on see köögitoiming. Nimeta see.",
        "grating",
        "riivimine",
        "Grating reduces food to small shreds by rubbing it against a surface with sharp projections or holes.",
        "Riivimisel hõõrutakse toitu vastu teravate sakkide või aukudega pinda, et saada väikesed ribad.",
        [],
        [],
      ],
      [
        {
          key: "wiktionary-sieving",
          sourceId: "source:food-drink:wiktionary-sieving",
          title: "Wiktionary: sieving",
          url: "https://en.wiktionary.org/wiki/sieving",
          license: "CC-BY-SA-4.0",
        },
        "Passing a dry ingredient through fine mesh to remove lumps is this preparation action. Name it.",
        "Kuivaine laskmine läbi peene võrgu, et eemaldada tükid, on see ettevalmistustoiming. Nimeta see.",
        "sieving",
        "sõelumine",
        "Sieving passes an ingredient through a mesh so that lumps or larger particles are left behind.",
        "Sõelumisel lastakse kuivaine läbi võrgu, nii et tükid või suuremad osakesed jäävad järele.",
        ["sifting"],
        ["sõelast läbilaskmine"],
      ],
      [
        "Meat_tenderness",
        "Pounding a steak before cooking so it becomes less tough is this preparation step. Name it.",
        "Steigi tampimine enne küpsetamist, et see muutuks vähem sitkeks, on see ettevalmistusvõte. Nimeta see.",
        "meat tenderising",
        "liha pehmendamine",
        "Meat tenderising can be done mechanically by pounding a piece so it becomes less tough.",
        "Liha pehmendamiseks võib tükki tampida, et see muutuks vähem sitkeks.",
        ["meat tenderizing"],
        ["liha pehmeks tegemine"],
      ],
      [
        "Garnish_(cooking)",
        "Adding a final edible decoration to a plated dish just before serving is this finishing action. Name it.",
        "Viimase söödava kaunistuse lisamine taldrikul olevale roale vahetult enne serveerimist on see viimistlustoiming. Nimeta see.",
        "garnishing",
        "garneerimine",
        "Garnishing means adding a decorative edible element to food before it is served.",
        "Garneerimine tähendab toidule enne serveerimist kaunistava söödava elemendi lisamist.",
        ["garnish"],
        ["toidu kaunistamine"],
      ],
    ],
  ],
  [
    113,
    "round-two",
    "cooking-techniques",
    "Food Storage Basics",
    "Toidu säilitamise põhitõed",
    [
      [
        {
          key: "wiktionary-freezer",
          sourceId: "source:food-drink:wiktionary-freezer",
          title: "Wiktionary: freezer",
          url: "https://en.wiktionary.org/wiki/freezer",
          license: "CC-BY-SA-4.0",
        },
        "This extra-cold appliance compartment keeps stored food below its freezing point. Name it.",
        "See seadmeosa hoiab säilitatavat toitu külmumispunktist madalamal temperatuuril. Nimeta see.",
        "freezer",
        "sügavkülmik",
        "A freezer is an appliance or compartment that keeps food frozen at very low temperatures.",
        "Sügavkülmik on seade või seadmeosa, mis hoiab toitu väga madalal temperatuuril külmununa.",
        [],
        [],
      ],
      [
        "Plastic_wrap",
        "Stretch this thin transparent plastic sheet over a bowl of leftovers to cover it. Name it.",
        "See õhuke läbipaistev plastleht tõmmatakse toidujääkidega kausi peale. Nimeta see.",
        "cling film",
        "toidukile",
        "Cling film is a thin transparent plastic sheet used to cover food and seal containers.",
        "Toidukile on õhuke läbipaistev plastleht, mida kasutatakse toidu katmiseks ja anumate sulgemiseks.",
        ["plastic wrap"],
        ["värskuskile"],
      ],
      [
        "Zipper_storage_bag",
        "Press two interlocking tracks together to close this flexible plastic food pouch. Name it.",
        "Selle painduva plastpakendi sulgemiseks surutakse kaks haakuvat riba kokku. Nimeta pakend.",
        "zipper storage bag",
        "sulguriga säilituskott",
        "A zipper storage bag is a flexible plastic pouch closed by pressing together two interlocking tracks.",
        "Sulguriga säilituskott on painduv plastpakend, mis suletakse kahe haakuva riba kokkusurumisel.",
        ["zipper bag", "ziplock bag", "resealable bag"],
        ["sulgurkott", "grip-kott", "Minigrip-kott"],
      ],
      [
        "Jar",
        "Preserves often keep in this rigid transparent container with a wide mouth and screw lid. Name it.",
        "Hoidiseid hoitakse sageli selles jäigas läbipaistvas laia suu ja keeratava kaanega anumas. Nimeta anum.",
        "glass jar",
        "klaaspurk",
        "A glass jar is a rigid wide-mouthed container with a lid, commonly used for preserves.",
        "Klaaspurk on jäik laia suuga kaanega anum, mida kasutatakse sageli hoidiste jaoks.",
        [],
        [],
      ],
      [
        "Pantry",
        "Dry groceries and kitchen supplies are kept in this small room or cupboard. Name it.",
        "Kuivaineid ja köögitarbeid hoitakse selles väikeses ruumis või kapis. Nimeta see.",
        "pantry",
        "sahver",
        "A pantry is a small room or cupboard used to store food, groceries and kitchen supplies.",
        "Sahver on väike ruum või kapp toidu, kuivainete ja köögitarvete hoidmiseks.",
        [],
        [],
      ],
    ],
  ],
  [
    114,
    "round-two",
    "ingredients",
    "Read the Pack",
    "Loe pakendit",
    [
      [
        {
          key: "european-commission-mandatory-food-information",
          sourceId:
            "source:food-drink:european-commission-mandatory-food-information",
          title: "European Commission: Mandatory food information",
          url: "https://food.ec.europa.eu/food-safety/labelling-and-nutrition/food-information-consumers-legislation/mandatory-food-information_en",
          license: "CC-BY-4.0",
        },
        "Look for this package panel to see everything used to make the product. Name it.",
        "Sellest pakendi osast näeb kõiki toote valmistamiseks kasutatud aineid. Nimeta see.",
        "ingredients list",
        "koostisosade loetelu",
        "An ingredients list tells consumers which substances were used to make a packaged food.",
        "Koostisosade loetelu näitab tarbijale, milliseid aineid pakendatud toidu valmistamiseks kasutati.",
        ["ingredient list"],
        ["koostisainete loetelu"],
      ],
      [
        {
          key: "european-commission-nutrition-labelling",
          sourceId: "source:food-drink:european-commission-nutrition-labelling",
          title: "European Commission: Nutrition labelling",
          url: "https://food.ec.europa.eu/food-safety/labelling-and-nutrition/food-information-consumers-legislation/nutrition-labelling_en",
          license: "CC-BY-4.0",
        },
        "Energy, fat, carbohydrate and protein amounts appear together in this package table. Name it.",
        "Energia, rasva, süsivesikute ja valgu kogused on koos selles pakenditabelis. Nimeta see.",
        "nutrition label",
        "toitumisalane teave",
        "A nutrition label reports a food's energy value and amounts of nutrients such as fat, carbohydrate and protein.",
        "Toitumisalane teave näitab toidu energiasisaldust ning toitainete, näiteks rasva, süsivesikute ja valgu koguseid.",
        ["nutrition declaration"],
        ["toitumisinfo"],
      ],
      [
        {
          key: "european-commission-allergies",
          sourceId: "source:food-drink:european-commission-allergies",
          title: "European Commission: Allergies",
          url: "https://food.ec.europa.eu/food-safety/campaign-2026/allergies_en",
          license: "CC-BY-4.0",
        },
        "This highlighted package text tells shoppers about substances that could trigger a serious reaction. Name it.",
        "See pakendil esile tõstetud tekst teavitab ostjat ainetest, mis võivad põhjustada tõsise reaktsiooni. Nimeta see.",
        "allergen warning",
        "allergeenihoiatus",
        "An allergen warning highlights substances in a food that may cause allergic reactions.",
        "Allergeenihoiatus tõstab esile toidus olevad ained, mis võivad põhjustada allergilisi reaktsioone.",
        ["allergen information"],
        ["allergeenide hoiatus"],
      ],
      [
        {
          key: "eur-lex-regulation-1169-2011",
          sourceId: "source:food-drink:eur-lex-regulation-1169-2011",
          title: "EUR-Lex: Regulation (EU) No 1169/2011",
          url: "https://eur-lex.europa.eu/eli/reg/2011/1169/oj/eng",
          license: "EU-reuse-policy",
        },
        "Besides figures per 100 grams, a package may optionally give values for this suggested amount eaten at one time. Name it.",
        "Lisaks saja grammi väärtustele võib pakend vabatahtlikult näidata andmeid selle soovitusliku korraga söödava koguse kohta. Nimeta see.",
        "serving size",
        "portsjoni suurus",
        "EU rules allow nutrition values per serving or consumption unit in addition to the standard values per 100 grams or millilitres.",
        "ELi reeglid lubavad näidata toitumisväärtusi portsjoni või tarbimisühiku kohta lisaks tavapärastele saja grammi või milliliitri väärtustele.",
        ["portion size"],
        ["portsjonisuurus"],
      ],
      [
        {
          key: "govuk-best-before-use-by",
          sourceId: "source:food-drink:govuk-best-before-use-by",
          title: "GOV.UK: Best before and use-by dates",
          url: "https://www.gov.uk/understanding-food-labelling/best-before-and-use-by-dates",
          license: "OGL-3.0",
        },
        "This package date is about food quality, unlike the safety deadline used for highly perishable products. Name the label.",
        "See pakendikuupäev näitab toidu kvaliteeti, mitte kiiresti rikneva toidu ohutustähtaega. Nimeta märge.",
        "best-before date",
        "„parim enne“ märge",
        "A best-before date concerns food quality, while a use-by date concerns safety for highly perishable food.",
        "„Parim enne“ märge puudutab toidu kvaliteeti, kuid „kõlblik kuni“ kuupäev kiiresti rikneva toidu ohutust.",
        ["best-before label"],
        ["parim enne"],
      ],
    ],
  ],
  [
    115,
    "round-two",
    "baking",
    "Bake Sale",
    "Küpsetiste laat",
    [
      [
        "Swiss_roll",
        "A thin sponge is spread with a sweet filling, rolled up, then sliced to reveal a spiral. Name the bake.",
        "Õhuke biskviit kaetakse magusa täidisega, keeratakse rulli ja lõigatakse spiraalse mustriga viiludeks. Nimeta küpsetis.",
        "Swiss roll",
        "rullbiskviit",
        "A Swiss roll is a thin filled sponge cake rolled into a cylinder and sliced to show a spiral.",
        "Rullbiskviit on õhuke täidisega biskviit, mis keeratakse silindriks ja lõigatakse spiraalse mustriga viiludeks.",
        ["jelly roll"],
        ["rullkook"],
      ],
      [
        "Cupcake",
        "This small cake for one person is baked in a paper case and often finished with icing. Name it.",
        "See väike ühele sööjale mõeldud kook küpsetatakse pabervormis ja kaetakse sageli glasuuriga. Nimeta see.",
        "cupcake",
        "tassikook",
        "A cupcake is a small cake designed for one person and is often topped with icing or decorations.",
        "Tassikook on ühele sööjale mõeldud väike kook, mille peal on sageli glasuur või kaunistused.",
        ["cup cake"],
        ["cupcake"],
      ],
      [
        "Doughnut",
        "Name the sweet fried ring with a hole through its middle.",
        "Nimeta magus praetud rõngas, mille keskel on auk.",
        "doughnut",
        "sõõrik",
        "A doughnut is a sweet fried pastry that is often shaped like a ring with a central hole.",
        "Sõõrik on magus praetud küpsetis, mis on sageli rõngakujuline ja mille keskel on auk.",
        ["donut"],
        ["donut"],
      ],
      [
        "Marble_cake",
        "Light and chocolate batters are gently swirled so each slice has a streaked pattern in this bake. Name it.",
        "Heledat tainast ja šokolaaditainast segatakse kergelt, nii et selle küpsetise igas viilus on kirju muster. Nimeta see.",
        "marble cake",
        "marmorikook",
        "Marble cake gets its streaked appearance by lightly mixing pale and chocolate batters.",
        "Marmorikoogi kirju muster saadakse heleda ja šokolaadise taina kergest segamisest.",
        ["marbled cake"],
        ["marmorkeeks"],
      ],
      [
        "Banana_bread",
        "Mashed ripe yellow fruit gives this moist loaf-shaped bake its name. Name it.",
        "Püreestatud küps kollane vili annab sellele niiskele pätsikujulisele küpsetisele nime. Nimeta see.",
        "banana bread",
        "banaanileib",
        "Banana bread is a moist loaf-shaped bake made with mashed ripe bananas.",
        "Banaanileib on niiske pätsikujuline küpsetis, mida tehakse püreestatud küpsetest banaanidest.",
        ["banana loaf"],
        ["banaanikeeks"],
      ],
    ],
  ],
  [
    116,
    "round-two",
    "baking",
    "Cake Finishing Touches",
    "Koogi viimane lihv",
    [
      [
        "Birthday_cake",
        "After making a wish, people blow out these small wax sticks placed on a celebration cake. Name them.",
        "Pärast soovi lausumist puhutakse ära need väikesed vahapulgad, mis asetatakse pidupäevakoogile. Nimeta need.",
        "birthday candles",
        "sünnipäevaküünlad",
        "Birthday candles are placed on a cake and traditionally blown out after the celebrant makes a wish.",
        "Sünnipäevaküünlad asetatakse koogile ning puhutakse tavaliselt ära pärast seda, kui sünnipäevalaps on soovi lausunud.",
        ["birthday candle"],
        ["sünnipäevaküünal"],
      ],
      [
        "Maraschino_cherry",
        "This bright red preserved sweet fruit is placed on top of cakes or ice cream. Name it.",
        "See erkpunane säilitatud magus vili pannakse kookide või jäätise peale. Nimeta see.",
        "cocktail cherry",
        "kokteilikirss",
        "A cocktail cherry, also called a maraschino cherry, is a preserved sweet cherry placed as decoration on cakes, ice cream and drinks.",
        "Kokteilikirss on säilitatud magus kirss, mida kasutatakse kookide, jäätise ja jookide kaunistamiseks.",
        ["maraschino cherry"],
        ["maraschino kirss"],
      ],
      [
        "Edible_flower",
        "These colourful blossoms can decorate a cake and are safe for guests to eat. Name the decoration.",
        "Need värvilised õied võivad kooki kaunistada ja külalised võivad neid ohutult süüa. Nimeta need.",
        "edible flowers",
        "söödavad lilled",
        "Edible flowers are blossoms that can safely be eaten and used to add colour and decoration to food.",
        "Söödavad lilled on õied, mida võib ohutult süüa ning kasutada toidule värvi ja kaunistuse lisamiseks.",
        ["edible flower"],
        ["söödav lill"],
      ],
      [
        "Fondant_icing",
        "This smooth sweet paste is rolled into a sheet and draped over a cake. Name it.",
        "See sile magus pasta rullitakse leheks ja asetatakse koogi peale. Nimeta see.",
        "fondant",
        "suhkrumass",
        "Fondant is a smooth sweet paste that can be rolled flat and used to cover or decorate cakes.",
        "Suhkrumass on sile magus pasta, mida saab lapikuks rullida ning kasutada kookide katmiseks või kaunistamiseks.",
        ["rolled fondant"],
        ["fondant"],
      ],
      [
        "Royal_icing",
        "Softly beaten egg whites and powdered sugar make this hard white cake decoration. Name it.",
        "Kergelt vahustatud munavalgest ja tuhksuhkrust tehakse see kõva valge koogikaunistus. Nimeta see.",
        "royal icing",
        "kuninglik glasuur",
        "Royal icing is a hard white icing made from softly beaten egg whites and powdered sugar.",
        "Kuninglik glasuur on kõva valge glasuur, mida tehakse kergelt vahustatud munavalgest ja tuhksuhkrust.",
        [],
        [],
      ],
    ],
  ],
  [
    117,
    "round-two",
    "baking",
    "Ready to Bake",
    "Küpsetamiseks valmis",
    [
      [
        "Apron",
        "Tie this garment over your clothes before mixing to catch splashes and powdery spills. Name it.",
        "Seo see rõivaese enne segamist riiete peale, et püüda kinni pritsmed ja pulbrised plekid. Nimeta see.",
        "kitchen apron",
        "köögipõll",
        "A kitchen apron is tied over clothing to protect it from splashes, spills and other messes.",
        "Köögipõll seotakse riiete peale, et kaitsta neid pritsmete, plekkide ja muu määrdumise eest.",
        ["apron"],
        ["põll"],
      ],
      [
        "Oven_glove",
        "Pull this thick heat-resistant hand covering on before lifting a hot baking dish. Name it.",
        "Pane see paks kuumakindel käekate kätte enne kuuma küpsetusnõu tõstmist. Nimeta see.",
        "oven mitt",
        "pajakinnas",
        "An oven mitt is an insulated hand covering used to handle hot cookware safely.",
        "Pajakinnas on kuumust isoleeriv käekate, millega saab kuumi küpsetusnõusid ohutult käsitseda.",
        ["oven glove"],
        ["ahjukinnas"],
      ],
      [
        "Muffin_tin",
        "Several round cups in one metal baking pan produce individual small cakes. Name the pan.",
        "Selles metallist küpsetusvormis on mitu ümmargust pesa väikeste kookide ühekaupa valmistamiseks. Nimeta vorm.",
        "muffin tin",
        "muffinivorm",
        "A muffin tin is a metal baking pan with several round cups for baking individual small cakes.",
        "Muffinivorm on metallist küpsetusvorm, mille mitmes ümmarguses pesas küpsetatakse väikseid kooke ühekaupa.",
        ["muffin tray"],
        ["muffinipann"],
      ],
      [
        "Weighing_scale",
        "Place recipe ingredients on this countertop device to measure their weight in grams. Name it.",
        "Aseta retsepti koostisosad sellele tööpinnal seisvale seadmele, et saada teada nende mass grammides. Nimeta seade.",
        "kitchen scales",
        "köögikaal",
        "Kitchen scales are used to weigh recipe ingredients, commonly in grams.",
        "Köögikaaluga mõõdetakse retsepti koostisosade massi, tavaliselt grammides.",
        ["kitchen scale"],
        ["köögikaalud"],
      ],
      [
        "Pastry_brush",
        "Use this small bristled kitchen tool to paint egg wash over dough before baking. Name it.",
        "Millise väikese harjastega köögiriistaga määritakse tainale enne küpsetamist munamääret?",
        "pastry brush",
        "tainapintsel",
        "A pastry brush is a small kitchen brush used to spread egg wash, butter or glaze over food.",
        "Tainapintsel on väike köögipintsel, millega määritakse toidule munamääret, võid või glasuuri.",
        ["basting brush"],
        ["küpsetuspintsel"],
      ],
    ],
  ],
  [
    118,
    "round-two",
    "non-alcoholic-drinks",
    "Familiar Drink Brands",
    "Tuttavad joogibrändid",
    [
      [
        "Pepsi",
        "The red-white-blue circular symbol called the Globe belongs to this cola brand. Name it.",
        "Gloobuseks nimetatud puna-valge-sinine ümmargune sümbol kuulub sellele koolabrändile. Nimeta see.",
        "Pepsi",
        "Pepsi",
        "Pepsi uses a red, white and blue circular logo known as the Pepsi Globe.",
        "Pepsi kasutab puna-valge-sinist ümmargust logo, mida tuntakse Pepsi gloobusena.",
        [],
        [],
      ],
      [
        {
          key: "coca-cola-company-fanta",
          sourceId: "source:food-drink:coca-cola-company-fanta",
          title: "The Coca-Cola Company: Fanta",
          url: "https://www.coca-colacompany.com/brands/sparkling-soft-drinks/fanta",
          license: "All rights reserved",
        },
        "This five-letter fruit-flavoured fizzy brand starts with F and is sold in an orange version. Name it.",
        "See viietäheline F-iga algav puuviljamaitseline gaseeritud joogibränd on müügil ka apelsiniversioonina. Nimeta see.",
        "Fanta",
        "Fanta",
        "Fanta is a five-letter fruit-flavoured fizzy-drink brand that includes an orange product.",
        "Fanta on viietäheline puuviljamaitseline gaseeritud jookide bränd, mille valikus on apelsiniversioon.",
        [],
        [],
      ],
      [
        "Sprite_(drink)",
        "This clear lemon-lime soft-drink brand has a six-letter name beginning with S and ending in “ite”. Name it.",
        "Selle läbipaistva sidruni-laimi karastusjoogibrändi kuuest tähest koosnev nimi algab S-iga ja lõpeb tähtedega „ite“. Nimeta see.",
        "Sprite",
        "Sprite",
        "Sprite is a clear lemon-lime soft drink with a six-letter brand name beginning with S and ending in “ite”.",
        "Sprite on läbipaistev sidruni-laimi karastusjook, mille kuuest tähest koosnev brändinimi algab S-iga ja lõpeb tähtedega „ite“.",
        [],
        [],
      ],
      [
        "Schweppes",
        "Jacob Schweppe founded this long-running fizzy-drink brand. Name it.",
        "Jacob Schweppe asutas selle pika ajalooga gaseeritud jookide brändi. Nimeta see.",
        "Schweppes",
        "Schweppes",
        "Schweppes is a long-running carbonated-drink brand founded by Jacob Schweppe.",
        "Schweppes on pika ajalooga gaseeritud jookide bränd, mille asutas Jacob Schweppe.",
        [],
        [],
      ],
      [
        "7_Up",
        "The cartoon character Fido Dido once advertised this lemon-lime drink brand. Name it.",
        "Multifilmitegelane Fido Dido reklaamis kunagi seda sidruni-laimi maitsega joogibrändi. Nimeta see.",
        "7 Up",
        "7 Up",
        "7 Up is a lemon-lime soft-drink brand that was advertised using the character Fido Dido.",
        "7 Up on sidruni-laimi maitsega karastusjoogibränd, mida reklaamiti Fido Dido tegelaskujuga.",
        ["Seven Up"],
        ["Seven Up"],
      ],
    ],
  ],
  [
    119,
    "round-two",
    "ingredients",
    "Everyday Sweeteners",
    "Igapäevased magustajad",
    [
      [
        "Maple_syrup",
        "Boiled tree sap becomes this amber pancake topping. Name it.",
        "Keedetud puumahlast saab see merevaigukarva pannkoogikate. Nimeta see.",
        "maple syrup",
        "vahtrasiirup",
        "Maple syrup is made by concentrating sap collected from maple trees.",
        "Vahtrasiirupit tehakse vahtrapuudest kogutud mahla kontsentreerides.",
        [],
        [],
      ],
      [
        "Stevia",
        "Extracts from the leaves of this plant are used as very intense sweeteners. Name the plant.",
        "Selle taime leheekstrakte kasutatakse väga magusate magustajatena. Nimeta taim.",
        "stevia",
        "steevia",
        "Stevia plants provide leaf extracts that are used as high-intensity sweeteners.",
        "Steeviataime lehtedest saadud ekstrakte kasutatakse väga magusate magustajatena.",
        ["stevia plant"],
        ["stevia"],
      ],
      [
        "Sugar_cube",
        "This pressed white sweetener has six square faces and is often dropped into tea or coffee. Name it.",
        "Sellel pressitud valgel magustajal on kuus ruudukujulist tahku ning seda pannakse sageli tee või kohvi sisse. Nimeta see.",
        "sugar cube",
        "suhkrutükk",
        "A sugar cube is made by pressing white sugar granules into a small cube, commonly used to sweeten tea or coffee.",
        "Suhkrutükk valmistatakse valge suhkru terade pressimisel väikeseks kuubikuks ning seda kasutatakse sageli tee või kohvi magustamiseks.",
        ["sugar lump"],
        ["tükksuhkur"],
      ],
      [
        "Vanilla_sugar",
        "White granules are infused with aromatic pods or mixed with their extract to make this European baking ingredient. Name it.",
        "Valgeid terakesi maitsestatakse aromaatsete kaunadega või segatakse nende ekstraktiga, et saada see Euroopas levinud küpsetusaine. Nimeta see.",
        "vanilla sugar",
        "vanillisuhkur",
        "Vanilla sugar is made by infusing sugar with vanilla beans or by mixing the grains with liquid flavouring from the same plant, and it is common in European desserts.",
        "Vanillisuhkrut valmistatakse suhkru maitsestamisel vanillikaunadega või segades terad sama taime vedela maitseainega ning see on Euroopa magustoitudes levinud.",
        [],
        [],
      ],
      [
        "Gelling_sugar",
        "This special dry ingredient already contains a gelling agent, helping homemade fruit preserves set. Name it.",
        "See eriline kuivaine sisaldab juba tarretavat ainet, mis aitab kodusel puuviljahoidisel tarretuda. Nimeta see.",
        "jam sugar",
        "moosisuhkur",
        "Jam sugar combines sugar with a gelling agent for making preserves, helping cooked fruit mixtures reach the desired consistency.",
        "Moosisuhkrus on suhkur ühendatud tarretava ainega, mis aitab keedetud puuviljahoidisel saavutada soovitud paksuse.",
        [],
        [],
      ],
    ],
  ],
  [
    120,
    "round-two",
    "non-alcoholic-drinks",
    "Café and Party Drinks",
    "Kohviku- ja peojoogid",
    [
      [
        "Lemonade",
        "Mix yellow citrus juice, water and something sweet to make this refreshing drink. Name it.",
        "Sega kollase tsitruse mahl, vesi ja midagi magusat, et saada see värskendav jook. Nimeta see.",
        "lemonade",
        "limonaad",
        "Lemonade is commonly made by mixing lemon juice with water and a sweetener.",
        "Limonaadi tehakse tavaliselt sidrunimahla, vee ja magustaja segamisel.",
        [],
        [],
      ],
      [
        "Smoothie",
        "Blending puréed fruit with liquid creates this thick cold drink. Name it.",
        "Püreestatud puuvilja ja vedeliku segamisel valmib see paks külm jook. Nimeta see.",
        "smoothie",
        "smuuti",
        "A smoothie is a thick cold drink made by blending puréed fruit with a liquid.",
        "Smuuti on paks külm jook, mis valmistatakse püreestatud puuvilja ja vedeliku segamisel.",
        [],
        [],
      ],
      [
        "Iced_coffee",
        "A brewed bean drink is chilled and commonly poured over ice for this café order. Name it.",
        "Röstitud ubadest pruulitud jook jahutatakse ja valatakse selle kohvikutellimuse jaoks sageli jää peale. Nimeta jook.",
        "iced coffee",
        "jääkohv",
        "Iced coffee is brewed coffee served cold and commonly poured over ice.",
        "Jääkohv on valmistatud kohv, mida serveeritakse külmalt ja sageli jääga.",
        ["ice coffee"],
        ["kohv jääga"],
      ],
      [
        "Hot_chocolate",
        "Cocoa or melted chocolate is turned into this warm café drink. Name it.",
        "Kakaost või sulatatud šokolaadist valmistatakse see soe kohvikujook. Nimeta see.",
        "hot chocolate",
        "kuum šokolaad",
        "Hot chocolate is a heated drink made with cocoa or melted chocolate.",
        "Kuum šokolaad on kuumutatud jook, mida tehakse kakaost või sulatatud šokolaadist.",
        ["drinking chocolate"],
        ["kakaojook"],
      ],
      [
        {
          key: "wiktionary-fruit-punch",
          sourceId: "source:food-drink:wiktionary-fruit-punch",
          title: "Wiktionary: fruit punch",
          url: "https://en.wiktionary.org/wiki/fruit_punch",
          license: "CC-BY-SA-4.0",
        },
        "This alcohol-free party drink mixes several juices and is served from a large communal bowl. Name it.",
        "See alkoholivaba peojook segatakse mitmest mahlast ja serveeritakse suurest ühisest kausist. Nimeta see.",
        "fruit punch",
        "puuviljapunšš",
        "Fruit punch is a usually non-alcoholic mixture of fruit juices served as punch, often from a communal bowl.",
        "Puuviljapunšš on tavaliselt alkoholivaba puuviljamahlade segu, mida serveeritakse sageli ühisest kausist.",
        ["non-alcoholic fruit punch"],
        ["alkoholivaba puuviljapunšš"],
      ],
    ],
  ],
];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLocaleLowerCase("en")
    .replace(/%[0-9a-f]{2}/giu, "-")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function sourceKey(seed: SourceSeed): string {
  return typeof seed === "string" ? slug(seed) : seed.key;
}

function source(seed: SourceSeed, subjectKey: string): EasyExpansionSource {
  if (typeof seed === "string") {
    return {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(seed).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${seed}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    };
  }
  return {
    sourceId: seed.sourceId,
    title: seed.title,
    url: seed.url,
    license: seed.license,
    retrievedAt: RETRIEVED_AT,
  };
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    sourceSeed,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const identity = sourceKey(sourceSeed);
  const subjectKey = `food-drink:${identity}`;
  return {
    clueId: `built-in-food-drink-easy-expansion-${clueNumber}`,
    key: `food-drink-easy-expansion:${categorySetId}:${tier}`,
    factKey: `food-drink-easy-expansion:${identity}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: source(sourceSeed, subjectKey),
  };
}

export const FOOD_DRINK_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  FOOD_DRINK_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
