import type {
  EasyExpansionCategory,
  EasyExpansionQuestion,
  EasyExpansionSource,
} from "../types";

const BATCH_ID = "10-technology-inventions";
const PACK_ID = "built-in-technology-inventions";
const RETRIEVED_AT = "2026-09-08";

type DirectSourceSeed = Readonly<{
  key: string;
  sourceId: string;
  title: string;
  url: string;
  license: string;
}>;

type SourceSeed = string | DirectSourceSeed;

type QuestionSeed = readonly [
  source: SourceSeed,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const TECHNOLOGY_INVENTIONS_EASY_EXPANSION_SEEDS: readonly CategorySeed[] = [
  [
    101,
    "round-one",
    "computing-history",
    "Familiar Keyboard Keys",
    "Klaviatuuri tuttavad klahvid",
    [
      [
        "Backspace",
        "A typing mistake just before the cursor disappears when you press this typing control. Name it.",
        "Selle klahvi vajutamine kustutab kirjutades märgi, mis asub kursorist vahetult vasakul. Nimeta klahv.",
        "Backspace key",
        "Backspace-klahv",
        "Pressing it removes the character immediately to the left of the cursor.",
        "Selle vajutamisel eemaldatakse kursorist vahetult vasakul olev märk.",
        ["Backspace"],
        ["tagasilükkeklahv"],
      ],
      [
        "Function_key",
        "Numbered F1, F2 and so on can each be assigned a special action by a program. Name this kind of control.",
        "Klaviatuuri nummerdatud F-rea klahvidele saavad programmid määrata eritoiminguid. Mis tüüpi klahv see on?",
        "function key",
        "F-klahv",
        "Its purpose depends on the program, and it belongs to the numbered F row.",
        "See kuulub klaviatuuri nummerdatud F-ritta ning selle otstarve sõltub programmist.",
        ["F-key"],
        ["funktsiooniklahv"],
      ],
      [
        "Tab_key",
        "In a form, pressing this control jumps the focus to the next box instead of typing a character. Name it.",
        "Veebivormil viib selle klahvi vajutamine fookuse järgmisele väljale, mitte ei sisesta märki. Nimeta klahv.",
        "Tab key",
        "Tab-klahv",
        "It moves focus forward between form fields and can also indent text.",
        "See viib fookuse vormiväljade vahel edasi ja võib teha tekstis taande.",
        ["Tab"],
        ["tabeldusklahv"],
      ],
      [
        "Arrow_keys",
        "A little cluster marked ←, ↑, ↓ and → moves a cursor or a game character. Name these controls.",
        "Väike rühm tähistega ←, ↑, ↓ ja → liigutab kursorit või mängutegelast. Nimeta need juhtnupud.",
        "arrow keys",
        "nooleklahvid",
        "The four controls provide movement in horizontal and vertical directions.",
        "Neli juhtnuppu võimaldavad liikuda neljas eri suunas.",
        ["arrow key"],
        ["nooleklahv"],
      ],
      [
        "Numeric_keypad",
        "Like a pocket calculator, this panel on the right of many full-size keyboards groups digits and arithmetic symbols. Name it.",
        "Numbrid ja tehtemärgid paiknevad sellel paljude täissuuruses klaviatuuride parempoolsel paneelil nagu kalkulaatoril. Nimeta see.",
        "numeric keypad",
        "numbriklahvistik",
        "It provides a calculator-style arrangement for entering numbers quickly.",
        "Selle kalkulaatorilaadne paigutus aitab numbreid kiiresti sisestada.",
        ["numpad"],
        ["numbriplokk"],
      ],
    ],
  ],
  [
    102,
    "round-one",
    "computing-history",
    "On a Computer Screen",
    "Arvutiekraanil",
    [
      [
        "Taskbar",
        "Windows usually places this long strip along one side of the display, with the Start control and symbols for open apps. Name it.",
        "Windows paigutab selle pika riba tavaliselt ekraani ühele küljele; seal on Start-nupp ja avatud rakenduste tähised. Nimeta see.",
        "taskbar",
        "tegumiriba",
        "It provides quick access to launching programs and switching among them.",
        "Selle kaudu saab programme kiiresti käivitada ja nende vahel liikuda.",
        ["task bar"],
        ["Windowsi tegumiriba"],
      ],
      [
        "Scrollbar",
        "A narrow track beside a long page has a draggable box that moves the view up or down. Name this on-screen control.",
        "Pika lehe kõrval oleva kitsa raja lohistatav liugur liigutab vaadet üles või alla. Nimeta ekraanil olev juhik.",
        "scroll bar",
        "kerimisriba",
        "Dragging its thumb changes which part of a document is visible.",
        "Selle liuguri lohistamine muudab, milline dokumendi osa on nähtav.",
        ["scrollbar"],
        ["scrollimisriba"],
      ],
      [
        "Trash_(computing)",
        "Deleted Windows files wait behind this desktop icon until you restore them or remove them permanently. Name it.",
        "Kustutatud Windowsi failid ootavad selle töölauaikooni taga, kuni need taastatakse või lõplikult eemaldatakse. Nimeta see.",
        "Recycle Bin",
        "prügikast",
        "It temporarily stores deleted items, allowing recovery before permanent removal.",
        "Seal hoitakse kustutatud üksusi ajutiselt, nii et neid saab enne lõplikku eemaldamist taastada.",
        ["Windows Recycle Bin"],
        ["Windowsi prügikast"],
      ],
      [
        "Screenshot",
        "This still image records exactly what a device is displaying at one moment. Name it.",
        "Selle pildiga jäädvustad täpselt selle, mida seade parajasti kuvab. Nimeta pilt.",
        "screenshot",
        "ekraanipilt",
        "It records the visible display at one moment as an image.",
        "See salvestab seadme nähtava kuva ühe hetke pildina.",
        ["screen capture", "screen grab"],
        ["kuvatõmmis", "ekraanitõmmis"],
      ],
      [
        "Button_(computing)#Windows_shell",
        "Click the small dash in a window's title bar to hide the window without closing it. Name that control.",
        "Klõpsa akna tiitliriba väikest kriipsu, et aken sulgemata peita. Nimeta see nupp.",
        "minimize button",
        "minimeerimisnupp",
        "It removes an open window from view while leaving the program running.",
        "See eemaldab avatud akna vaatest, kuid jätab programmi tööle.",
        ["minimise button"],
        ["akna minimeerimise nupp"],
      ],
    ],
  ],
  [
    103,
    "round-one",
    "communications",
    "Phone Calls",
    "Telefonikõned",
    [
      [
        {
          key: "google-phone-manage-call-history",
          sourceId:
            "source:technology-inventions:google-phone-manage-call-history",
          title: "Google Phone Help: Manage call history",
          url: "https://support.google.com/phoneapp/answer/2811854?hl=en",
          license: "All rights reserved",
        },
        "A phone that sounded but went unanswered leaves this entry among its recent activity. Name it.",
        "Telefon helises, kuid keegi ei vastanud, ja hiljutiste tegevuste loendisse jäi selle kohta kirje. Nimeta see.",
        "missed call",
        "vastamata kõne",
        "It records an incoming attempt that the recipient did not pick up.",
        "See märgib sissetulevat helistamist, millele saaja ei vastanud.",
        ["unanswered call"],
        ["vastamata telefonikõne"],
      ],
      [
        "Voicemail",
        "When nobody picks up, a caller can leave this recorded spoken message for later. Name it.",
        "Keegi ei vasta, kuid helistaja saab jätta selle salvestatud suulise sõnumi hilisemaks kuulamiseks. Nimeta see.",
        "voicemail",
        "kõnepost",
        "It stores speech from a caller so the recipient can listen afterward.",
        "See talletab helistaja jutu, et saaja saaks seda hiljem kuulata.",
        ["voice mail"],
        ["voicemail"],
      ],
      [
        "Caller_ID",
        "Before you answer, this phone feature can show the incoming number or a saved name. Name it.",
        "Enne vastamist võib see telefoni funktsioon näidata sissetulevat numbrit või salvestatud nime. Nimeta see.",
        "caller ID",
        "helistaja ID",
        "It tells the recipient who is ringing by displaying a number or stored name.",
        "See annab saaja ekraanil numbri või nime järgi teada, kes parajasti helistab.",
        ["caller identification"],
        ["helistaja tuvastus"],
      ],
      [
        {
          key: "apple-iphone-call-history",
          sourceId: "source:technology-inventions:apple-iphone-call-history",
          title: "Apple Support: View and delete your call history on iPhone",
          url: "https://support.apple.com/en-gb/guide/iphone/iph21d1e1f56/ios",
          license: "All rights reserved",
        },
        "Open this phone-app list to see recent phone entries in time order. Name it.",
        "Selles telefonirakenduse loendis näed hiljutisi helistamisi ajalises järjekorras. Nimeta loend.",
        "call history",
        "kõnelogi",
        "It keeps recent phone activity arranged by when each entry occurred.",
        "See hoiab hiljutised helistamised nende toimumisaja järgi järjestatuna.",
        ["call log"],
        ["kõneajalugu"],
      ],
      [
        "Conference_call",
        "Three colleagues speak together by phone in this shared conversation. Name it.",
        "Kolm kolleegi räägivad telefonitsi korraga selles ühises vestluses. Nimeta see.",
        "conference call",
        "konverentskõne",
        "It links at least three participants into one simultaneous phone conversation.",
        "See ühendab vähemalt kolm osalejat ühte samaaegsesse telefonivestlusse.",
        ["group call"],
        ["rühmakõne"],
      ],
    ],
  ],
  [
    104,
    "round-one",
    "communications",
    "Getting Online at Home",
    "Kodune internet",
    [
      [
        {
          key: "microsoft-windows-connect-wifi",
          sourceId:
            "source:technology-inventions:microsoft-windows-connect-wifi",
          title: "Microsoft Support: Connect to a Wi-Fi network in Windows",
          url: "https://support.microsoft.com/en-us/windows/experience/connectivity-networking/connect-to-a-wi-fi-network-in-windows",
          license: "All rights reserved",
        },
        "Before a new device joins a protected wireless network, it asks for this secret string. Name it.",
        "Enne uue seadme ühendamist küsib kaitstud juhtmeta ühendus seda salajast märgijada. Nimeta see.",
        "Wi-Fi password",
        "Wi-Fi parool",
        "Entering the correct secret lets the device join the protected network.",
        "Õige salajase märgijada sisestamine lubab seadme kaitstud võrku.",
        ["wireless password"],
        ["võrguparool"],
      ],
      [
        "Ethernet_over_twisted_pair",
        "A lead with plastic connectors at both ends links a computer directly to a wired network. Name it.",
        "Läbipaistva plastotsaga juhe ühendab arvuti otse juhtmega võrku. Nimeta juhe.",
        "Ethernet cable",
        "Etherneti kaabel",
        "It provides a physical wired connection for carrying network data.",
        "See loob võrguandmete edastamiseks füüsilise juhtmega ühenduse.",
        ["network cable"],
        ["võrgukaabel"],
      ],
      [
        "Wireless_repeater",
        "A weak wireless signal in the far room improves when this small device repeats it over a wider area. Name it.",
        "Kaugemas toas muutub nõrk juhtmeta signaal tugevamaks, kui see väike seade signaali laiemale alale edasi saadab. Nimeta seade.",
        "Wi-Fi extender",
        "Wi-Fi-võimendi",
        "It receives an existing wireless signal and broadcasts it again to increase coverage.",
        "See võtab olemasoleva juhtmeta signaali vastu ja edastab selle uuesti, et leviala suurendada.",
        ["wireless repeater", "range extender"],
        ["Wi-Fi-repiiter", "leviala laiendaja"],
      ],
      [
        "Internet_service_provider",
        "This company sells your household access to the global network. Name its role.",
        "See ettevõte müüb majapidamisele juurdepääsu ülemaailmsele võrgule. Nimeta tema roll.",
        "internet service provider",
        "internetiteenuse pakkuja",
        "It supplies customers with access to the global network.",
        "See võimaldab klientidele juurdepääsu ülemaailmsele võrgule.",
        ["ISP", "internet provider"],
        ["ISP", "internetipakkuja"],
      ],
      [
        "Fiber_to_the_x",
        "This fast home connection uses optical fibre for all or part of the local link to the customer. Name it.",
        "See kiire koduühendus kasutab kliendini jõudmiseks täielikult või osaliselt optilist kiudu. Nimeta ühendus.",
        "fibre-optic broadband",
        "valguskaabliühendus",
        "It is a broadband architecture that uses optical fibre for all or part of the local loop.",
        "See on lairibavõrgu lahendus, milles kohalik ühendus kasutab täielikult või osaliselt optilist kiudu.",
        ["fiber-optic broadband", "fibre broadband"],
        ["fiiberoptiline ühendus", "fiiberinternet"],
      ],
    ],
  ],
  [
    105,
    "round-one",
    "transportation",
    "Behind the Wheel",
    "Autoroolis",
    [
      [
        "Rearview_mirror",
        "Mounted inside near the top of the windscreen, this reflective panel shows the driver the road through the car's rear window. Name it.",
        "Salongis esiklaasi ülaossa kinnitatud peegeldav pind näitab juhile teed läbi auto tagaakna. Nimeta see.",
        "rear-view mirror",
        "tahavaatepeegel",
        "It is usually fixed near the top of the windscreen so the driver can see rearward through the rear window.",
        "See kinnitatakse tavaliselt esiklaasi ülaossa, et juht näeks läbi tagaakna enda taha.",
        ["rearview mirror"],
        ["tagasivaatepeegel"],
      ],
      [
        "Sun_visor",
        "Lower this hinged flap above the windscreen to shade the driver's eyes from bright sunlight. Name it.",
        "Langeta see esiklaasi kohal olev liigendiga klapp, et ere päikesevalgus juhti ei pimestaks. Nimeta see.",
        "sun visor",
        "päikesesirm",
        "The adjustable interior flap can be lowered or swung aside to block sunlight.",
        "Reguleeritava salongiklapi saab päikesevalguse varjamiseks alla lasta või küljele pöörata.",
        ["sunshade"],
        ["autopäikesesirm"],
      ],
      [
        "Car_controls",
        "To slow or stop the car, the driver's foot pushes this control. Name it.",
        "Auto aeglustamiseks või peatamiseks vajutab juht jalaga seda juhtseadist. Nimeta see.",
        "brake pedal",
        "piduripedaal",
        "It converts foot pressure into the action that reduces the vehicle's speed.",
        "See muudab jalasurve sõiduki kiirust vähendavaks toimeks.",
        ["foot brake"],
        ["jalgpidur"],
      ],
      [
        "Gear_stick",
        "Backward motion, neutral and the driving ratios are selected with this hand control. Name it.",
        "Tagurpidikäik, vabakäik ja sõidukäigud valitakse selle käsitsi liigutatava juhtseadisega. Nimeta see.",
        "gear lever",
        "käigukang",
        "Its positions let the driver choose backward motion, neutral or a forward ratio.",
        "Selle asenditega valib juht tagurpidikäigu, vabakäigu või edasisõidu ülekande.",
        ["gear stick"],
        ["käiguvahetuskang"],
      ],
      [
        "Parking_brake",
        "After stopping on a slope, set this separate control so the unattended car will not roll. Name it.",
        "Kallakul peatudes rakenda seda eraldi juhtseadist, et järelevalveta auto ei veereks. Nimeta see.",
        "parking brake",
        "käsipidur",
        "It holds a stationary vehicle in place after the driver leaves.",
        "See hoiab seisva sõiduki paigal ka pärast juhi lahkumist.",
        ["handbrake"],
        ["seisupidur"],
      ],
    ],
  ],
  [
    106,
    "round-one",
    "transportation",
    "Bicycle Bits",
    "Jalgratta osad ja tarvikud",
    [
      [
        "Bicycle_lighting",
        "This small cycle-mounted lamp helps the rider see and be seen at night. Name it.",
        "See rattale kinnitatud väike lamp aitab sõitjal pimedas näha ja nähtav olla. Nimeta see.",
        "bicycle light",
        "jalgrattatuli",
        "It illuminates the way ahead or makes the cycle visible to others.",
        "See valgustab teed või muudab ratta teistele liiklejatele nähtavaks.",
        ["bike light"],
        ["rattatuli"],
      ],
      [
        "Bicycle_bell",
        "Press its thumb lever and this handlebar-mounted device rings to warn pedestrians. Name it.",
        "Vajuta pöidlaga selle juhtrauale kinnitatud seadme hooba ning see heliseb jalakäijate hoiatamiseks. Nimeta see.",
        "bicycle bell",
        "rattakell",
        "The thumb-operated signalling device warns pedestrians and other cyclists.",
        "Pöidlaga kasutatav märguandeseade hoiatab jalakäijaid ja teisi rattureid.",
        ["bike bell"],
        ["jalgrattakell"],
      ],
      [
        "Bicycle_pump",
        "Connect this hand-operated cylinder to a tyre valve and push its handle to add air. Name it.",
        "Ühenda see käsitsi kasutatav silinder rehviventiiliga ja suru õhu lisamiseks käepidet. Nimeta see.",
        "bicycle pump",
        "rattapump",
        "Repeated handle strokes force air through the valve into the tyre.",
        "Käepideme korduv liigutamine surub õhu läbi ventiili rehvi.",
        ["bike pump"],
        ["jalgrattapump"],
      ],
      [
        "Bicycle_fender",
        "A curved cover above the wheel saves the rider's back from dirty road spray. Name it.",
        "Ratta kohal olev kaarjas kate hoiab teelt pritsiva porivee sõitja seljast eemal. Nimeta kate.",
        "bicycle mudguard",
        "jalgratta porilaud",
        "It intercepts water and dirt thrown upward by the rotating tyre.",
        "See peatab pöörleva rehvi paisatud vee ja mustuse.",
        ["bike mudguard", "bicycle fender"],
        ["porilaud", "rattaporilaud"],
      ],
      [
        "Inner_tube",
        "On many cycles, this inflatable tube sits hidden between the rim and tyre. Name it.",
        "Paljudel jalgratastel asub see täispuhutav rõngas velje ja rehvi vahel peidus. Nimeta see.",
        "inner tube",
        "sisekumm",
        "Air inside it supports the tyre and cushions the ride.",
        "Selles olev õhk toetab rehvi ja pehmendab sõitu.",
        ["bicycle tube"],
        ["jalgratta sisekumm"],
      ],
    ],
  ],
  [
    107,
    "round-one",
    "engineering",
    "Building Site Essentials",
    "Ehitusplatsi vahendid",
    [
      [
        "Hard_hat",
        "Falling tools and debris are why workers wear this rigid head protection on a building site. Name it.",
        "Kukkuvate tööriistade ja prahi tõttu kannavad töötajad ehitusplatsil seda jäika peakaitset. Nimeta see.",
        "hard hat",
        "kaitsekiiver",
        "Its hard shell is designed to reduce head injury from impacts and falling objects.",
        "Selle kõva kest vähendab löökidest ja kukkuvatest esemetest tingitud peavigastuste ohtu.",
        ["safety helmet"],
        ["ehituskiiver"],
      ],
      [
        "Toolbox",
        "A handle and divided compartments make this portable container handy for carrying hand tools. Name it.",
        "Sangaga kaasaskantava anuma lahtrites saab käsitööriistu korrastatult kaasa võtta. Nimeta anum.",
        "toolbox",
        "tööriistakast",
        "It keeps a set of implements organised and transportable between jobs.",
        "See hoiab töövahendid korrastatuna ja teeb nende viimise ühelt töökohalt teisele lihtsaks.",
        ["tool box"],
        ["tööriistakohver"],
      ],
      [
        "Spirit_level",
        "A bubble in a liquid-filled vial shows whether a beam is horizontal or a wall is vertical. Name this building tool.",
        "Vedelikuga ampullis olev mull näitab, kas pruss on rõhtne või sein püstloodis. Nimeta see ehitustööriist.",
        "spirit level",
        "vesilood",
        "The bubble settles between marked lines when a surface is level or plumb.",
        "Mull jääb tähistusjoonte vahele, kui pind on rõht- või püstloodis.",
        [],
        [],
      ],
      [
        "Tool_belt",
        "Pockets and loops around the waist place a worker's hand tools within reach. Name this wearable holder.",
        "Vöökoha ümber olevad taskud ja aasad hoiavad töötaja käsitööriistad käeulatuses. Nimeta see kantav hoidik.",
        "tool belt",
        "tööriistavöö",
        "Worn around the waist, it carries commonly used implements without occupying the hands.",
        "Seda kantakse vöökohal, nii et töövahendid on kaasas ja käed jäävad vabaks.",
        [],
        [],
      ],
      [
        "Jackhammer",
        "This heavy powered tool pounds rapidly into concrete or road surface until it breaks apart. Name it.",
        "See raske mootoriga tööriist lööb kiiresti vastu betooni või teekatet, kuni materjal puruneb. Nimeta tööriist.",
        "jackhammer",
        "piikvasar",
        "Its bit delivers repeated impacts that fracture hard concrete.",
        "Selle otsik annab korduvaid lööke, mis purustavad kõva betooni.",
        ["pneumatic drill"],
        ["suruõhuvasar"],
      ],
    ],
  ],
  [
    108,
    "round-one",
    "engineering",
    "Familiar Fasteners",
    "Tuttavad kinnitusvahendid",
    [
      [
        "Carabiner",
        "This strong metal loop has a spring-loaded gate and quickly clips gear to a rope or belt. Name it.",
        "Selle tugeva metallaasa vedruga värav võimaldab varustuse kiiresti köie või vöö külge kinnitada. Nimeta see.",
        "carabiner",
        "karabiin",
        "Its gate opens to admit an item and springs shut to hold it in the loop.",
        "Selle värav avaneb eseme lisamiseks ja sulgub vedru jõul, et eset aasas hoida.",
        ["karabiner"],
        ["karabiinhaak"],
      ],
      [
        "Buckle",
        "A metal frame and pin close a belt or adjust the length of a strap. Name this fitting.",
        "Metallraam ja keel sulgevad vöö või reguleerivad rihma pikkust. Nimeta kinnitus.",
        "buckle",
        "pannal",
        "The pin passes through a hole while the frame holds the strap in place.",
        "Keel läheb läbi augu ning raam hoiab rihma paigal.",
        ["belt buckle"],
        ["vööpannal"],
      ],
      [
        "Cable_tie",
        "Pull this narrow toothed plastic strip through its one-way head and it locks tightly around a bundle. Name it.",
        "Tõmba see kitsas hambuline plastriba läbi ühesuunalise pea ja see lukustub tihedaks aasaks. Nimeta see.",
        "cable tie",
        "kaabliside",
        "Its teeth prevent the strip from sliding back after it has been tightened.",
        "Hambad takistavad riba tagasilibisemist pärast aasa pingutamist.",
        ["zip tie", "tie wrap"],
        ["kaablivits", "nipukas"],
      ],
      [
        {
          key: "getty-aat-screw-clamps",
          sourceId: "source:technology-inventions:getty-aat-screw-clamps",
          title: "Getty Art & Architecture Thesaurus — screw clamps",
          url: "https://www.getty.edu/vow/AATFullDisplay?find=&logic=&note=&subjectid=300024135",
          license: "All rights reserved",
        },
        "Turn the threaded handle and two parallel jaws squeeze a woodworking piece firmly. Name this holding tool.",
        "Keera keermestatud käepidet ning kaks paralleelset lõuga suruvad puidutüki kindlalt paigale. Nimeta see hoidmisvahend.",
        "screw clamp",
        "pitskruvi",
        "A threaded mechanism moves one jaw toward the other to grip the workpiece.",
        "Keermemehhanism liigutab ühe lõua teise poole, et töödeldav detail kinni hoida.",
        ["screw cramp"],
        ["kruvipits"],
      ],
      [
        "Snap_fastener",
        "Press the two small round parts on a garment together and they close with a click. Name this fitting.",
        "Suru kaks väikest ümarat rõivaosa kokku ja need kinnituvad klõpsuga. Nimeta see kinnitus.",
        "snap fastener",
        "trukk",
        "One part fits into the other, so the garment can be opened and closed repeatedly.",
        "Üks osa sobitub teise sisse, nii et rõivast saab korduvalt avada ja sulgeda.",
        ["press stud"],
        ["trukknööp"],
      ],
    ],
  ],
  [
    109,
    "round-one",
    "materials",
    "Materials Around Us",
    "Materjalid meie ümber",
    [
      [
        "Aluminium_foil",
        "This very thin, shiny metal sheet wraps leftovers and covers a baking dish before heating. Name it.",
        "See väga õhuke läikiv metallleht sobib toidu pakkimiseks ja ahjuvormi katmiseks. Nimeta see.",
        "aluminium foil",
        "alumiiniumfoolium",
        "Rolled into flexible sheets, the metal forms a common kitchen wrapping.",
        "Metall valtsitakse painduvateks lehtedeks, mida köögis pakendamiseks kasutatakse.",
        ["aluminum foil", "tin foil"],
        ["hõbepaber", "foolium"],
      ],
      [
        "Memory_foam",
        "A dent from your head slowly disappears from this pillow material after you get up. Name it.",
        "Pea jäetud lohk kaob sellest padjamaterjalist pärast tõusmist aeglaselt. Nimeta materjal.",
        "memory foam",
        "mäluvaht",
        "After pressure is removed, it gradually recovers its former shape.",
        "Pärast surve eemaldamist taastab see järk-järgult oma endise kuju.",
        ["viscoelastic foam"],
        ["viskoelastne vaht"],
      ],
      [
        "Laminate_flooring",
        "Layered planks with a printed grain pattern often click together to create this floor covering. Name it.",
        "Selle põrandakatte moodustavad puiduilmelised kihilised lauad, mis ühendatakse sageli klõpsuga. Nimeta kate.",
        "laminate flooring",
        "laminaatparkett",
        "Its planks combine several layers beneath a printed surface that copies a grain pattern.",
        "Selle laudadel on mitu kihti ja puitu jäljendav pealispind.",
        ["laminate floor"],
        ["laminaatpõrand"],
      ],
      [
        "Silicone_rubber",
        "Flexible baking moulds, spatulas and heat-resistant seals are commonly made from this material. Name it.",
        "Painduvad küpsetusvormid, pannilabidad ja kuumakindlad tihendid valmistatakse sageli sellest materjalist. Nimeta see.",
        "silicone rubber",
        "silikoonkumm",
        "It stays flexible while withstanding temperatures found in cooking and sealing uses.",
        "See püsib painduvana ning talub toiduvalmistamisel ja tihendamisel esinevat kuumust.",
        ["silicone elastomer"],
        ["silikoonelastomeer"],
      ],
      [
        "Carbon_fibers",
        "A black woven pattern on a racing car often reveals this strong material with very little weight. Name it.",
        "Võidusõiduauto must kootud muster paljastab sageli selle tugeva ja väga väikese kaaluga materjali. Nimeta see.",
        "carbon fibre",
        "süsinikkiud",
        "Its fine filaments form strong reinforcement with little weight and a distinctive black weave.",
        "Peentest kiududest saab väikese kaaluga tugeva materjali, millel on iseloomulik tume koekiri.",
        ["carbon fiber"],
        ["süsinikfiiber"],
      ],
    ],
  ],
  [
    110,
    "round-one",
    "energy",
    "Power at Home",
    "Kodune elekter",
    [
      [
        "Extension_cord",
        "When an appliance's cable cannot reach the wall outlet, this flexible lead carries mains power farther. Name it.",
        "Kui seadme kaabel ei ulatu seinakontaktini, viib see painduv juhe võrguelektri kaugemale. Nimeta see.",
        "extension cord",
        "pikendusjuhe",
        "It adds length between an electrical appliance and a mains outlet.",
        "See pikendab elektriseadme ja seinakontakti vahelist ühendust.",
        ["extension lead"],
        ["pikenduskaabel"],
      ],
      [
        "AA_battery",
        "This familiar cylindrical size is marked with two identical letters and powers many small household gadgets. Name it.",
        "Kahe ühesuguse tähega märgitud tuttavat silindrilist vooluallikat kasutatakse paljudes väikestes koduseadmetes. Nimeta suurus.",
        "AA battery",
        "AA-patarei",
        "It is a standard cylindrical size commonly used in small household electronics.",
        "See on standardne silindriline mõõt, mida kasutatakse väikestes koduelektroonikaseadmetes.",
        ["AA cell"],
        ["AA-element"],
      ],
      [
        "Battery_charger",
        "Rechargeable cells go into this device to receive electricity before being used again. Name it.",
        "Taaslaetavad elemendid pannakse sellesse seadmesse, et need saaksid uueks kasutuskorraks elektrit. Nimeta seade.",
        "battery charger",
        "akulaadija",
        "It supplies electrical energy to restore charge in reusable cells.",
        "See annab korduskasutatavatele elementidele nende laengu taastamiseks elektrienergiat.",
        ["rechargeable-battery charger"],
        ["patareilaadija"],
      ],
      [
        "Surge_protector",
        "Plug electronics into this protective device so brief voltage spikes are limited before causing damage. Name it.",
        "Ühenda elektroonikaseadmed selle kaitseseadmega, et lühikesed pingetipud ei tekitaks kahju. Nimeta see.",
        "surge protector",
        "liigpingekaitse",
        "It limits excess voltage before it can damage connected equipment.",
        "See piirab liigset pinget enne, kui see saab ühendatud seadmeid kahjustada.",
        ["surge suppressor"],
        ["ülepingekaitse"],
      ],
      [
        "Electricity_meter",
        "This device records a home's electrical energy use for the utility company. Name it.",
        "See seade mõõdab kodus kasutatud elektrienergiat, et müüja saaks tarbimise eest tasu arvutada. Nimeta seade.",
        "electricity meter",
        "elektriarvesti",
        "It measures cumulative consumption so the supplier can calculate a charge.",
        "See liidab tarbimise kokku, et elektrimüüja saaks arve koostada.",
        ["electric meter"],
        ["elektrienergia arvesti"],
      ],
    ],
  ],
  [
    111,
    "round-two",
    "communications",
    "Online Communication",
    "Suhtlus internetis",
    [
      [
        "Videotelephony",
        "Live sound and picture bring distant participants together in this online conversation. Name it.",
        "Reaalajas heli ja pilt toovad selles veebivestluses kokku eemal viibivad osalejad. Nimeta see.",
        "video call",
        "videokõne",
        "A video call transmits moving images and sound in real time so participants can see and hear one another.",
        "Videokõne edastab reaalajas liikuvat pilti ja heli, nii et osalejad saavad üksteist näha ja kuulda.",
        ["video chat"],
        ["videovestlus"],
      ],
      [
        "Private_message",
        "A note sent inside an online platform is visible only to the particular user you chose. Name this kind of message.",
        "Veebiplatvormil saadetud teadet näeb ainult konkreetne kasutaja, kelle valisid. Nimeta selline sõnum.",
        "direct message",
        "otsesõnum",
        "A direct message is delivered privately to a selected account instead of appearing in a public conversation.",
        "Otsesõnum saadetakse privaatselt valitud kontole, mitte avalikku vestlusse.",
        ["DM", "private message"],
        ["privaatsõnum", "erasõnum"],
      ],
      [
        "Desktop_sharing",
        "During an online meeting, this feature lets everyone else watch what appears on one participant's computer display. Name it.",
        "Veebikoosolekul laseb see funktsioon kõigil teistel näha ühe osaleja arvutikuva. Nimeta see.",
        "screen sharing",
        "ekraani jagamine",
        "Screen sharing sends the contents of one user's display to other participants over a network.",
        "Ekraani jagamine edastab ühe kasutaja arvutikuva sisu võrgu kaudu teistele osalejatele.",
        ["desktop sharing"],
        ["ekraanijagamine"],
      ],
      [
        "Online_chat",
        "Several members type into one shared online conversation, and each can read the others' messages. Name this format.",
        "Mitu liiget kirjutavad ühte ühisesse veebivestlusse ja igaüks saab teiste sõnumeid lugeda. Nimeta selline suhtlusvorm.",
        "group chat",
        "grupivestlus",
        "A group chat gives several members one shared online conversation in which they can exchange messages.",
        "Grupivestlus annab mitmele liikmele ühise veebivestluse, kus nad saavad sõnumeid vahetada.",
        ["chat group"],
        ["rühmavestlus"],
      ],
      [
        {
          key: "cambridge-dictionary-voice-note",
          sourceId:
            "source:technology-inventions:cambridge-dictionary-voice-note",
          title: "Cambridge Dictionary: voice note",
          url: "https://dictionary.cambridge.org/us/dictionary/english/voice-note",
          license: "All rights reserved",
        },
        "Instead of typing in a messaging app, speak briefly and send the resulting recording. Name it.",
        "Sõnumirakenduses trükkimise asemel räägi lühidalt ja saada tekkinud salvestis teele. Nimeta see.",
        "voice note",
        "häälsõnum",
        "A voice note is a short recording of speech sent electronically as a message.",
        "Häälsõnum on lühike kõnesalvestis, mis saadetakse elektrooniliselt sõnumina.",
        ["voice message", "audio message"],
        ["helisõnum", "audiosõnum"],
      ],
    ],
  ],
  [
    112,
    "round-two",
    "transportation",
    "At the Station and Along the Line",
    "Jaamas ja raudteel",
    [
      [
        "Ticket_machine",
        "At a station, this self-service device lets a traveller choose a journey, pay, and receive proof of travel. Name it.",
        "Jaamas laseb see iseteenindusseade reisijal valida sõidu, maksta ja saada sõiduõigust tõendava dokumendi. Nimeta seade.",
        "ticket machine",
        "piletiautomaat",
        "A ticket machine lets a traveller select and pay for a journey without help from a clerk.",
        "Piletiautomaat võimaldab reisijal valida sõidu ja selle eest maksta ilma teenindaja abita.",
        ["ticket vending machine"],
        ["piletimasin"],
      ],
      [
        "Passenger_information_system",
        "Times, destinations, platform numbers and delays fill this large station display. Name it.",
        "Rongide kellaajad, sihtkohad, perrooninumbrid ja hilinemised täidavad selle suure jaamaekraani. Nimeta see.",
        "departure board",
        "väljumistabloo",
        "A departure board gathers leaving times, destinations, platforms and service updates on one station display.",
        "Väljumistabloo koondab ühele jaamaekraanile väljumisajad, sihtkohad, perroonid ja liiklusteated.",
        ["departures board"],
        ["väljumiste tabloo"],
      ],
      [
        "Paid_area",
        "Present a valid fare card or travel document and this station gate opens to the platform area. Name it.",
        "Näita kehtivat sõidukaarti või -dokumenti ning see jaamavärav avaneb perroonialale. Nimeta see.",
        "ticket barrier",
        "piletivärav",
        "A ticket barrier checks proof of payment before allowing a passenger into a station's paid area.",
        "Piletivärav kontrollib sõiduõigust, enne kui reisija pääseb jaama tasulisele alale.",
        ["fare gate"],
        ["pääsuvärav"],
      ],
      [
        "Level_crossing",
        "A road cuts across railway tracks at the same height here, with no bridge or tunnel. Name the place.",
        "Maantee läheb siin rongirööbastest üle samal tasapinnal, ilma silla või tunnelita. Nimeta koht.",
        "level crossing",
        "raudteeülesõit",
        "A level crossing is an at-grade meeting of a road and railway rather than a bridge or tunnel crossing.",
        "Raudteeülesõit on maantee ja raudtee ristumine samal tasapinnal, mitte silla või tunneli kaudu.",
        ["railroad crossing"],
        ["raudteeülesõidukoht"],
      ],
      [
        "Overhead_line",
        "Wires suspended above the rails feed electricity to an electric train. Name this railway supply.",
        "Rööbaste kohal rippuvad juhtmed annavad elektrirongile voolu. Nimeta see raudtee toitesüsteem.",
        "overhead line",
        "kontaktliin",
        "An overhead line carries electrical energy above the track for a train to collect while moving.",
        "Kontaktliin kannab elektrienergiat rööbaste kohal, et rong saaks seda sõidu ajal kasutada.",
        ["overhead wire"],
        ["kontaktvõrk"],
      ],
    ],
  ],
  [
    113,
    "round-two",
    "energy",
    "At the Filling Station",
    "Tanklas",
    [
      [
        "Gasoline_pump",
        "Pull its nozzle from the filling-station machine, place it in the vehicle, and the hose delivers a measured amount of liquid fuel. Name the machine.",
        "Võta tankla masina küljest püstol, aseta see sõidukisse ja voolik annab mõõdetud koguse vedelkütust. Nimeta masin.",
        "petrol pump",
        "tankur",
        "A petrol pump measures liquid fuel and transfers it from storage into a vehicle through a hose and nozzle.",
        "Tankur mõõdab vedelkütust ning juhib selle mahutist vooliku ja püstoli kaudu sõidukisse.",
        ["fuel dispenser", "gasoline pump", "gas pump"],
        ["kütusetankur", "bensiinipump", "tankimispump"],
      ],
      [
        "Gasoline",
        "This road fuel is sold without the lead additive used in its older counterpart. Name it.",
        "Seda autokütust müüakse ilma vanemates segudes kasutatud pliilisandita. Nimeta kütus.",
        "unleaded petrol",
        "pliivaba bensiin",
        "Unleaded petrol is motor fuel sold without the lead compounds formerly added to gasoline.",
        "Pliivaba bensiin on mootorikütus, millele pole lisatud varem bensiinis kasutatud pliiühendeid.",
        ["unleaded gasoline", "unleaded"],
        ["pliivaba mootoribensiin", "pliivaba"],
      ],
      [
        "Charging_station",
        "At this fixed point, a cable supplies electrical power to an electric car. Name the facility.",
        "Selles püsipunktis annab kaabel elektriautole laadimiseks elektrit. Nimeta rajatis.",
        "EV charging station",
        "elektriauto laadimisjaam",
        "An EV charging station supplies electrical energy through a cable so an electric vehicle can recharge.",
        "Elektriauto laadimisjaam annab kaabli kaudu elektrienergiat, et elektrisõiduk saaks akut laadida.",
        [
          "electric vehicle charging station",
          "charging station",
          "charge point",
          "EV charger",
        ],
        [
          "elektrisõiduki laadimisjaam",
          "laadimisjaam",
          "laadimispunkt",
          "elektriauto laadija",
        ],
      ],
      [
        "Octane_rating",
        "Numbers such as 95 and 98 at a filling station express how well fuel resists unwanted knocking in an engine. Name this measure.",
        "Tankla arvud 95 ja 98 näitavad, kui hästi peab kütus mootoris soovimatule detonatsioonile vastu. Nimeta see näit.",
        "octane rating",
        "oktaaniarv",
        "An octane rating measures a fuel's resistance to engine knock; 95 and 98 are familiar examples of the measure.",
        "Oktaaniarv mõõdab kütuse vastupidavust mootori detonatsioonile; 95 ja 98 on selle näidu tuttavad näited.",
        ["octane number", "octane"],
        ["oktaanarv", "oktaan"],
      ],
      [
        "Diesel_exhaust_fluid",
        "This six-letter trademark beginning with A labels the separate fluid a diesel vehicle uses to cut nitrogen-oxide emissions. Name it.",
        "See A-ga algav kuuetäheline kaubamärk tähistab eraldi vedelikku, mida diiselsõiduk kasutab lämmastikoksiidide heite vähendamiseks. Nimeta see.",
        "AdBlue",
        "AdBlue",
        "AdBlue is a trade name for diesel exhaust fluid used in selective catalytic reduction to reduce nitrogen-oxide emissions.",
        "AdBlue on diisli heitgaasivedeliku kaubamärk; vedelikku kasutatakse selektiivkatalüütilises reduktsioonis lämmastikoksiidide heite vähendamiseks.",
        [],
        [],
      ],
    ],
  ],
  [
    114,
    "round-two",
    "space-technology",
    "At a Rocket Launch",
    "Raketi stardil",
    [
      [
        "Launch_pad",
        "A rocket waits on this prepared platform before lifting off from it. Name the place.",
        "Rakett ootab enne õhkutõusu sellel ettevalmistatud platvormil. Nimeta koht.",
        "launch pad",
        "stardiplatvorm",
        "A launch pad is the prepared platform from which a rocket lifts off.",
        "Stardiplatvorm on ettevalmistatud alus, millelt rakett õhku tõuseb.",
        ["rocket launch pad"],
        ["raketi stardiplats"],
      ],
      [
        "Rocket_engine",
        "Hot gas blasts out at high speed, creating the thrust that drives a rocket. Name the machine producing it.",
        "Kuum gaas paiskub suure kiirusega välja ja tekitab raketti liigutava tõukejõu. Nimeta masin, mis seda teeb.",
        "rocket engine",
        "raketimootor",
        "A rocket engine produces thrust by expelling exhaust gas at high speed.",
        "Raketimootor tekitab tõukejõu, paisates heitgaasi suure kiirusega välja.",
        ["rocket motor"],
        ["raketi mootor"],
      ],
      [
        "Mission_control_center",
        "Back on Earth, teams in this room monitor the spacecraft and direct the flight. Name the nerve centre.",
        "Maal jälgivad selles ruumis töötavad meeskonnad kosmosesõidukit ja juhivad lendu. Nimeta see koht.",
        "mission control",
        "missioonijuhtimiskeskus",
        "Mission control is the ground facility where teams monitor and direct a spaceflight.",
        "Missioonijuhtimiskeskus on maapealne rajatis, kus meeskonnad jälgivad ja juhivad kosmoselendu.",
        ["mission control centre"],
        ["missiooni juhtimiskeskus"],
      ],
      [
        "Space_capsule",
        "Crew members ride in this compact craft, built to survive the trip back through Earth's atmosphere. Name it.",
        "Meeskond reisib selles kompaktses aluses, mis on ehitatud taluma naasmist läbi Maa atmosfääri. Nimeta alus.",
        "space capsule",
        "kosmosekapsel",
        "A space capsule is a compact crew-carrying craft designed to return through Earth's atmosphere.",
        "Kosmosekapsel on kompaktne meeskonda kandev alus, mis on mõeldud Maa atmosfääri naasmiseks.",
        ["spacecraft capsule"],
        ["kosmoselaeva kapsel"],
      ],
      [
        "Heat_shield",
        "During atmospheric re-entry, this protective layer keeps a returning craft from burning up. Name it.",
        "Atmosfääri naasmisel hoiab see kaitsekiht ära aluse läbipõlemise. Nimeta see.",
        "heat shield",
        "kuumakilp",
        "A heat shield protects a returning craft from the extreme heating of atmospheric entry.",
        "Kuumakilp kaitseb naasvat alust atmosfääri sisenemisel tekkiva äärmise kuumenemise eest.",
        ["thermal shield"],
        ["soojuskilp"],
      ],
    ],
  ],
  [
    115,
    "round-two",
    "everyday-devices",
    "Home Security Devices",
    "Kodu turvaseadmed",
    [
      [
        "Intercom",
        "A visitor at an apartment entrance presses a button, and this two-way system lets someone inside speak before opening up. Name it.",
        "Kortermaja sissepääsu juures vajutab külaline nuppu ning seesolija saab selle kahesuunalise süsteemi kaudu enne avamist rääkida. Nimeta seade.",
        "door intercom",
        "fonolukk",
        "A door intercom carries two-way speech between an entrance and someone inside before access is granted.",
        "Fonolukk võimaldab sissepääsu juures oleva külalisega enne ukse avamist kahesuunalist kõnesidet pidada.",
        ["entryphone"],
        ["uksetelefon"],
      ],
      [
        "Door_chain",
        "This short run of metal links lets an entrance open only a narrow gap while still restraining it. Name it.",
        "See metallist lülidest koosnev lühike tõke laseb välisuksel avaneda vaid kitsa vahe võrra, kuid hoiab seda endiselt kinni. Nimeta see.",
        "door chain",
        "uksekett",
        "A door chain restrains an entrance so it can open only far enough for limited viewing or conversation.",
        "Uksekett piirab välisukse liikumist, nii et see avaneb ainult vaatamiseks või rääkimiseks piisava vahe võrra.",
        ["security chain"],
        ["turvakett"],
      ],
      [
        {
          key: "ring-install-contact-sensor-gen2",
          sourceId:
            "source:technology-inventions:ring-install-contact-sensor-gen2",
          title: "Ring Support: Tips for Installing Contact Sensor (2nd Gen)",
          url: "https://ring.com/support/articles/y44jn/Installing-Your-Contact-Sensor-Gen2",
          license: "All rights reserved",
        },
        "One magnetic piece sits on the frame and its partner on the door; the security system detects when they separate. Name the device.",
        "Üks magnetiline osa paikneb uksepiidal ja teine ukse küljes; turvasüsteem tuvastab nende eraldumise. Nimeta seade.",
        "door sensor",
        "ukseandur",
        "A door sensor uses two aligned magnetic parts; opening the door separates them and changes the reported state.",
        "Ukseandur kasutab kaht kohakuti magnetilist osa; ukse avamine eraldab need ja muudab süsteemile edastatud olekut.",
        ["contact sensor"],
        ["kontaktandur"],
      ],
      [
        "Closed-circuit_television",
        "Mounted in a fixed position, this video device watches and records a protected home or property. Name it.",
        "See kindlasse kohta kinnitatud videoseade jälgib ja salvestab kaitstavat kodu või muud vara. Nimeta see.",
        "security camera",
        "turvakaamera",
        "A security camera supplies video surveillance and recording for a protected property.",
        "Turvakaamera võimaldab kaitstavat vara video abil jälgida ja salvestada.",
        ["surveillance camera"],
        ["valvekaamera"],
      ],
      [
        "Smart_lock",
        "A phone, entry code or wireless credential can release this electronic piece of entrance hardware. Name it.",
        "Telefon, pääsukood või juhtmeta pääsuvahend avab selle elektroonilise ukseluku. Nimeta see.",
        "smart lock",
        "nutilukk",
        "A smart lock uses electronic authentication such as a phone, code or wireless credential to control entry.",
        "Nutilukk kasutab sissepääsu juhtimiseks elektroonilist tuvastust, näiteks telefoni, koodi või juhtmeta pääsuvahendit.",
        ["electronic smart lock"],
        ["nutikas lukk"],
      ],
    ],
  ],
  [
    116,
    "round-two",
    "standards-units",
    "Everyday Tech Units",
    "Ühikud tehnikamaailmas",
    [
      [
        "Gigabyte",
        "One billion bytes make one of these familiar units on a phone or computer storage label. Name it.",
        "Miljard baiti moodustab ühe sellise tuttava ühiku telefoni või arvuti salvestusmahu kirjelduses. Nimeta ühik.",
        "gigabyte",
        "gigabait",
        "A gigabyte is a digital-information unit equal to one billion bytes in the decimal convention used on storage labels.",
        "Gigabait on digitaalse info ühik, mis võrdub salvestusmahu märgistusel kasutatava kümnendsüsteemi järgi miljardi baidiga.",
        ["GB"],
        ["GB"],
      ],
      [
        "Frame_rate",
        "This unit phrase tells how many separate pictures a game or video displays during one second. Give it.",
        "See näit ütleb, mitu eraldi pilti mäng või video ühe sekundi jooksul kuvab. Nimeta see.",
        "frames per second",
        "kaadrit sekundis",
        "Frames per second expresses a frame rate as the number of individual images displayed each second.",
        "Väljend „kaadrit sekundis“ annab kaadrisageduse ühe sekundi jooksul kuvatavate üksikpiltide arvuna.",
        ["FPS"],
        ["FPS"],
      ],
      [
        "Horsepower",
        "A familiar working animal lends its name to this unit for an engine's power. Name the unit.",
        "Tuttav tööloom annab nime sellele mootori võimsusühikule. Nimeta ühik.",
        "horsepower",
        "hobujõud",
        "Horsepower is a unit of power historically framed by comparison with the work of horses.",
        "Hobujõud on võimsusühik, mille ajalooline nimetus võrdleb masina võimsust hobuse tööga.",
        ["hp"],
        ["hj"],
      ],
      [
        "Lumen_(unit)",
        "On a light-bulb box, a higher number in this unit means the lamp produces more visible light. Name the unit.",
        "Lambipakil tähendab suurem arv selles ühikus, et lamp annab rohkem nähtavat valgust. Nimeta ühik.",
        "lumen",
        "luumen",
        "A lumen measures luminous flux, the amount of visible light emitted by a source.",
        "Luumen mõõdab valgusvoogu ehk valgusallika tekitatud nähtava valguse hulka.",
        ["lm"],
        ["lm"],
      ],
      [
        "Kilowatt-hour",
        "Household electricity bills total consumed energy in this unit rather than simply listing power. Name it.",
        "Kodune elektriarve arvestab tarbitud energiat selles ühikus, mitte üksnes võimsust. Nimeta ühik.",
        "kilowatt-hour",
        "kilovatt-tund",
        "A kilowatt-hour is an energy unit equal to using one kilowatt of power for one hour and is common on electricity bills.",
        "Kilovatt-tund on energiaühik, mis vastab ühe kilovati võimsuse kasutamisele ühe tunni jooksul ja mida kasutatakse elektriarvetel.",
        ["kWh"],
        ["kWh"],
      ],
    ],
  ],
  [
    117,
    "round-two",
    "everyday-devices",
    "Electricals in the Bathroom",
    "Elektriseadmed vannitoas",
    [
      [
        "Electric_toothbrush",
        "A rechargeable brush cleans teeth with a head that vibrates or rotates. Name the device.",
        "Selle laetava harja pea vibreerib või pöörleb, et hambaid puhastada. Nimeta seade.",
        "electric toothbrush",
        "elektrihambahari",
        "An electric toothbrush moves its bristles automatically, commonly by vibrating or rotating the brush head.",
        "Elektrihambahari liigutab harjaseid automaatselt, tavaliselt harjapead vibreerides või pöörates.",
        ["powered toothbrush"],
        ["elektriline hambahari"],
      ],
      [
        "Electric_shaver",
        "Guarded moving blades trim facial hair in this powered handheld grooming device. Name it.",
        "Selle käes hoitava elektrilise hooldusseadme kaitstud liikuvad terad lõikavad näokarvu. Nimeta seade.",
        "electric shaver",
        "elektripardel",
        "An electric shaver uses powered moving blades behind a guard to cut facial hair.",
        "Elektripardel lõikab näokarvu elektri jõul liikuvate teradega, mida katab kaitse.",
        ["electric razor"],
        ["pardel"],
      ],
      [
        "Hair_iron",
        "Clamp a section of hair between this hinged tool's two heated flat plates to smooth it. Name the tool.",
        "See liigendiga tööriist silub juuksesalku kahe kuuma lameda plaadi vahel. Nimeta tööriist.",
        "hair straightener",
        "juuksesirgendaja",
        "A hair straightener presses hair between two heated flat plates to make it smoother and straighter.",
        "Juuksesirgendaja surub juuksed kahe kuuma lameda plaadi vahele, et need siledamaks ja sirgemaks muuta.",
        ["straightening iron"],
        ["sirgendaja"],
      ],
      [
        {
          key: "wiktionary-curling-iron",
          sourceId: "source:technology-inventions:wiktionary-curling-iron",
          title: "Wiktionary: curling iron",
          url: "https://en.wiktionary.org/wiki/curling_iron",
          license: "CC-BY-SA-4.0",
        },
        "This heated cylindrical styling device is used to make hair curly. Name it.",
        "Seda kuumutatavat silindrilist soenguvahendit kasutatakse juuste lokkimiseks. Nimeta vahend.",
        "curling iron",
        "lokitangid",
        "A curling iron is a heated cylindrical device used to make hair curly.",
        "Lokitangid on kuumutatav silindriline vahend, mida kasutatakse juuste lokkimiseks.",
        ["curling tongs"],
        ["juuksekoolutaja"],
      ],
      [
        "Hair_clipper",
        "Comb-like moving blades on this powered handheld cutter trim hair short. Name the tool.",
        "Selle käes hoitava elektrilise tööriista kammitaolised liikuvad terad lõikavad juuksed lühikeseks. Nimeta see.",
        "hair clippers",
        "juukselõikusmasin",
        "Powered hair clippers use motor-driven comb-like blades to cut hair to a short, even length.",
        "Elektrilised juukselõikusmasinad kasutavad juuste lühikeseks ja ühtlaseks lõikamiseks mootoriga liikuvaid kammitaolisi terasid.",
        ["hair clipper"],
        ["juukselõikur"],
      ],
    ],
  ],
  [
    118,
    "round-two",
    "everyday-devices",
    "Laundry Day Helpers",
    "Pesupäeva vahendid",
    [
      [
        "Washing_machine",
        "Water, detergent and a turning drum clean clothes inside this household appliance. Name it.",
        "Vesi, pesuvahend ja pöörlev trummel puhastavad selles kodumasinas riideid. Nimeta seade.",
        "washing machine",
        "pesumasin",
        "A washing machine cleans clothes with water and detergent inside a rotating drum.",
        "Pesumasin puhastab riideid vee ja pesuvahendiga pöörlevas trumlis.",
        [],
        [],
      ],
      [
        "Laundry_basket",
        "Toss dirty clothes into this open container, then carry them to the wash. Name it.",
        "Viska mustad riided sellesse lahtisesse anumasse ja vii need siis pesema. Nimeta anum.",
        "laundry basket",
        "pesukorv",
        "A laundry basket is an open container for collecting and carrying clothes before or after washing.",
        "Pesukorv on lahtine anum riiete kogumiseks ja kandmiseks enne või pärast pesemist.",
        ["clothes basket"],
        ["mustapesukorv"],
      ],
      [
        "Clothes_horse",
        "Unfold this barred frame and drape wet clothes over it so they can dry in the air. Name it.",
        "Klapi see varbadega raam lahti ja laota märjad riided sellele õhu käes kuivama. Nimeta vahend.",
        "drying rack",
        "pesurest",
        "A drying rack is a folding frame with bars that support wet clothes while they air-dry.",
        "Pesurest on kokkupandav varbadega raam, millel märjad riided õhu käes kuivavad.",
        ["clothes horse", "clothes airer"],
        ["kuivatusrest", "pesukuivatusrest"],
      ],
      [
        "Clothes_dryer",
        "Freshly washed laundry turns in this appliance's heated drum until it is dry. Name the appliance.",
        "Värskelt pestud pesu pöörleb selle seadme soojas trumlis, kuni see on kuiv. Nimeta seade.",
        "tumble dryer",
        "pesukuivati",
        "A tumble dryer dries washed laundry by rotating it in a drum through which heated air passes.",
        "Pesukuivati kuivatab pestud pesu, keerutades seda trumlis, millest liigub läbi soe õhk.",
        ["clothes dryer"],
        ["kuivati"],
      ],
      [
        "Lint_remover",
        "This handled roll of sticky sheets lifts fluff and pet hair from a jacket. Name it.",
        "See käepidemega kleepuvate lehtede rull eemaldab jakilt ebemed ja loomakarvad. Nimeta vahend.",
        "lint roller",
        "riiderull",
        "A lint roller uses a handled roll of adhesive sheets to lift fluff and hair from clothing.",
        "Riiderull eemaldab rõivastelt ebemeid ja karvu käepidemega kleepuvate lehtede rulli abil.",
        ["clothes roller"],
        ["ebemerull"],
      ],
    ],
  ],
  [
    119,
    "round-two",
    "everyday-devices",
    "Keeping a Room Comfortable",
    "Mugav sisekliima",
    [
      [
        "Thermostat",
        "Set a desired room temperature, and this control switches heating or cooling to maintain it. Name the control.",
        "Vali soovitud toatemperatuur ning see juhtseade lülitab selle hoidmiseks kütte või jahutuse sisse ja välja. Nimeta seade.",
        "thermostat",
        "termostaat",
        "A thermostat controls heating or cooling to keep a space near a selected temperature.",
        "Termostaat juhib kütet või jahutust, et hoida ruum valitud temperatuuri lähedal.",
        ["temperature controller"],
        ["temperatuuriregulaator"],
      ],
      [
        "Air_conditioning",
        "Hot indoor air becomes cooler after passing through this appliance. Name it.",
        "Kuum siseõhk muutub seda seadet läbides jahedamaks. Nimeta seade.",
        "air conditioner",
        "konditsioneer",
        "An air conditioner removes heat from indoor air to cool an enclosed space.",
        "Konditsioneer eemaldab siseõhust soojust, et kinnist ruumi jahutada.",
        ["air-conditioning unit"],
        ["kliimaseade"],
      ],
      [
        "Air_purifier",
        "Dust, smoke and other particles are trapped by filters as room air passes through this device. Name it.",
        "Tolm, suits ja muud osakesed jäävad filtritesse, kui toaõhk seda seadet läbib. Nimeta seade.",
        "air purifier",
        "õhupuhasti",
        "An air purifier passes room air through filters that remove contaminants such as dust and smoke particles.",
        "Õhupuhasti juhib toaõhu läbi filtrite, mis eemaldavad saasteaineid, näiteks tolmu- ja suitsuosakesi.",
        ["air cleaner"],
        ["õhupuhastaja"],
      ],
      [
        "Humidifier",
        "When indoor air feels too dry, this device adds moisture to it. Name it.",
        "Kui toaõhk on liiga kuiv, lisab see seade sellesse niiskust. Nimeta seade.",
        "humidifier",
        "õhuniisuti",
        "A humidifier raises humidity by adding moisture to dry indoor air.",
        "Õhuniisuti suurendab õhuniiskust, lisades kuivale siseõhule niiskust.",
        ["air humidifier"],
        ["niisuti"],
      ],
      [
        "Dehumidifier",
        "A damp room loses excess moisture as air passes through this device. Name it.",
        "See seade eemaldab niiskest toast liigse niiskuse, kui õhk sellest läbi liigub. Nimeta seade.",
        "dehumidifier",
        "õhukuivati",
        "This device removes water from humid indoor air and collects or drains it away.",
        "See seade eemaldab niiskest siseõhust vett ning kogub selle anumasse või juhib ära.",
        ["air dehumidifier"],
        ["niiskuseemaldi"],
      ],
    ],
  ],
  [
    120,
    "round-two",
    "everyday-devices",
    "On an Office Desk",
    "Kontorilaual",
    [
      [
        "Hole_punch",
        "Press its lever and neat round openings appear along a sheet's edge, ready for a binder. Name the desk tool.",
        "Vajuta hooba ning lehe serva ilmuvad korralikud ümmargused avad, et leht kausta panna. Nimeta lauavahend.",
        "hole punch",
        "auguraud",
        "A hole punch uses a lever-driven cutter to make round openings in paper for filing in a binder.",
        "Auguraud teeb hoovaga liigutatava lõikuri abil paberisse ümmargused avad, et lehti saaks kausta panna.",
        ["paper punch"],
        ["paberiaugustaja"],
      ],
      [
        "Rubber_stamp",
        "Press this handled object onto an ink pad and then onto a document to leave the same mark again and again. Name it.",
        "Vajuta see käepidemega ese tindipadjale ja seejärel dokumendile, et jätta ikka sama märk. Nimeta ese.",
        "rubber stamp",
        "kummitempel",
        "A rubber stamp transfers ink from a shaped surface to paper, allowing the same mark to be repeated.",
        "Kummitempel kannab tindi kujundiga pinnalt paberile, nii et sama märki saab korduvalt jätta.",
        ["ink stamp"],
        ["tinditempel"],
      ],
      [
        "Paper_shredder",
        "Feed a private document into this electric office device and it emerges as thin strips or small pieces. Name it.",
        "Sisesta privaatne dokument sellesse elektrilisse kontoriseadmesse ning see väljub peente ribade või väikeste tükkidena. Nimeta seade.",
        "paper shredder",
        "paberipurustaja",
        "A paper shredder cuts documents into strips or particles so their contents are harder to recover.",
        "Paberipurustaja lõikab dokumendid ribadeks või osakesteks, et nende sisu oleks raskem taastada.",
        ["document shredder"],
        ["dokumendipurustaja"],
      ],
      [
        "Label_printer",
        "This compact device puts text or barcodes onto self-adhesive material. Name it.",
        "See kompaktne seade kannab teksti või vöötkoodi isekleepuvale materjalile. Nimeta seade.",
        "label printer",
        "etiketiprinter",
        "A label printer prints text or barcodes onto self-adhesive label material.",
        "Etiketiprinter prindib teksti või vöötkoodi isekleepuvale etiketimaterjalile.",
        [],
        [],
      ],
      [
        "USB_hub",
        "Several peripherals can share one computer's USB port through this small desk device. Name it.",
        "Mitu välisseadet saavad selle väikese lauaseadme kaudu kasutada arvuti üht USB-pesa. Nimeta seade.",
        "USB hub",
        "USB-jaotur",
        "A USB hub expands one computer connection into several ports for multiple peripheral devices.",
        "USB-jaotur jagab arvuti ühe ühenduse mitmeks pesaks, et ühendada mitu välisseadet.",
        ["USB port hub"],
        ["USB-hub"],
      ],
    ],
  ],
];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLocaleLowerCase("en")
    .replace(/%[0-9a-f]{2}/giu, "-")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function sourceKey(seed: SourceSeed): string {
  return typeof seed === "string" ? slug(seed) : seed.key;
}

function source(seed: SourceSeed, subjectKey: string): EasyExpansionSource {
  if (typeof seed === "string") {
    return {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(seed).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${seed}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    };
  }
  return {
    sourceId: seed.sourceId,
    title: seed.title,
    url: seed.url,
    license: seed.license,
    retrievedAt: RETRIEVED_AT,
  };
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    sourceSeed,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const identity = sourceKey(sourceSeed);
  const subjectKey = `technology-inventions:${identity}`;
  return {
    clueId: `built-in-technology-inventions-easy-expansion-${clueNumber}`,
    key: `technology-inventions-easy-expansion:${categorySetId}:${tier}`,
    factKey: `technology-inventions-easy-expansion:${identity}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: source(sourceSeed, subjectKey),
  };
}

export const TECHNOLOGY_INVENTIONS_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  TECHNOLOGY_INVENTIONS_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
