import type {
  EasyExpansionCategory,
  EasyExpansionQuestion,
  EasyExpansionSource,
} from "../types";

const BATCH_ID = "11-politics-economics-society";
const PACK_ID = "built-in-politics-economics-society";
const RETRIEVED_AT = "2026-09-08";

type DirectSourceSeed = Readonly<{
  key: string;
  sourceId: string;
  title: string;
  url: string;
  license: string;
}>;

type SourceSeed = string | DirectSourceSeed;

type QuestionSeed = readonly [
  source: SourceSeed,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const POLITICS_ECONOMICS_SOCIETY_EASY_EXPANSION_SEEDS: readonly CategorySeed[] =
  [
    [
      101,
      "round-one",
      "political-systems",
      "Election Day Details",
      "Valimispäeva detailid",
      [
        [
          "Postal_voting",
          "A voter receives ballot papers at home and returns them by mail before election day. Name this method.",
          "Valija saab hääletussedelid koju ja tagastab need enne valimispäeva postiga. Nimeta see viis.",
          "postal voting",
          "posti teel hääletamine",
          "The ballot papers are delivered to the voter and are usually returned through the mail.",
          "Hääletussedelid saadetakse valijale ning tavaliselt tagastatakse need posti kaudu.",
          ["postal vote"],
          ["postihääletus"],
        ],
        [
          "Election_monitoring",
          "This independent person watches election procedures and reports whether they were fair. Name the role.",
          "See sõltumatu inimene jälgib valimiste käiku ja annab hinnangu nende aususele. Nimeta amet.",
          "election observer",
          "valimisvaatleja",
          "The role involves observing voting procedures independently and assessing how the election was conducted.",
          "Selle ameti ülesanne on jälgida hääletamist sõltumatult ja hinnata valimiste korraldust.",
          ["election monitor"],
          ["valimiste vaatleja"],
        ],
        [
          "Vote_counting",
          "After polls close, officials read marked ballots and total the choices to produce a result. Name this process.",
          "Pärast jaoskondade sulgemist loevad ametnikud märgistatud sedeleid ja liidavad valikud tulemuse saamiseks kokku. Nimeta protsess.",
          "vote counting",
          "häälte lugemine",
          "This process turns the marked ballots into numerical election results.",
          "Selles protsessis teisendatakse märgistatud sedelid valimiste arvuliseks tulemuseks.",
          ["ballot counting"],
          ["häältelugemine"],
        ],
        [
          "Voter_turnout",
          "A results chart says that 63 percent of eligible people cast a ballot. What participation measure is this?",
          "Tulemuste graafik näitab, et hääletas 63 protsenti valimisõiguslikest inimestest. Mis osalusnäitaja see on?",
          "voter turnout",
          "valimisaktiivsus",
          "It is the share of eligible people who actually cast a ballot.",
          "See on hääle andnud valimisõiguslike inimeste osakaal.",
          ["turnout"],
          ["hääletamisaktiivsus"],
        ],
        [
          "Spoilt_vote",
          "Officials reject a marked voting paper because the intended choice is unclear or the marking rules were broken. Name it.",
          "Ametnikud jätavad märgistatud hääletuspaberi arvestamata, sest valik pole üheselt mõistetav või märkimisreegleid on rikutud. Nimeta see.",
          "invalid ballot",
          "kehtetu sedel",
          "A voting paper that cannot be accepted under the rules is left out of the result.",
          "Reeglite järgi vastuvõetamatu hääletuspaber jäetakse tulemusest välja.",
          ["spoilt ballot", "spoiled ballot"],
          ["rikutud sedel", "kehtetu hääletussedel"],
        ],
      ],
    ],
    [
      102,
      "round-one",
      "constitutions",
      "Everyday Rights",
      "Igapäevased õigused",
      [
        [
          "Right_to_privacy",
          "Which right protects a patient's medical records and other personal-life information from unwarranted exposure?",
          "Milline õigus kaitseb patsiendi terviseandmeid ja muud eraelu puudutavat teavet põhjendamatu avalikustamise eest?",
          "right to privacy",
          "õigus eraelu puutumatusele",
          "It protects information about a person's private life against unjustified intrusion or disclosure.",
          "See kaitseb inimese eraelu puudutavat teavet põhjendamatu sekkumise või avalikustamise eest.",
          [],
          [],
        ],
        [
          "Freedom_of_movement",
          "Which right lets a person travel within their country and choose whether to live in Tallinn, Tartu, or elsewhere?",
          "Milline õigus lubab inimesel riigis ringi liikuda ja valida elukohaks Tallinna, Tartu või muu paiga?",
          "freedom of movement",
          "liikumisvabadus",
          "It covers travelling within a country and choosing one's place of residence.",
          "See hõlmab riigis liikumist ja oma elukoha valimist.",
          ["right to free movement"],
          ["vabalt liikumise õigus"],
        ],
        [
          "Discrimination",
          "A qualified applicant must not be rejected only because of age, origin, sex, religion, or disability. Name this principle.",
          "Sobivat kandidaati ei tohi kõrvale jätta üksnes vanuse, päritolu, soo, usundi või puude tõttu. Nimeta see põhimõte.",
          "non-discrimination",
          "diskrimineerimiskeeld",
          "The principle forbids unfair treatment based only on protected personal characteristics.",
          "See põhimõte keelab ebaõiglase kohtlemise üksnes kaitstud isikutunnuste tõttu.",
          ["equal treatment"],
          ["võrdne kohtlemine"],
        ],
        [
          "Right_to_a_fair_trial",
          "In a criminal case, which right promises the accused an independent public hearing and a chance to answer the case?",
          "Milline õigus tagab kriminaalasjas süüdistatavale sõltumatu avaliku menetluse ja võimaluse väidetele vastata?",
          "right to a fair trial",
          "õigus õiglasele kohtumenetlusele",
          "It requires an independent hearing in which the accused can present a defence.",
          "See nõuab sõltumatut menetlust, kus süüdistatav saab end kaitsta.",
          [],
          [],
        ],
        [
          "Freedom_of_association",
          "Workers use this right when they form a trade union, and neighbours use it when they voluntarily start a club. Name it.",
          "Töötajad kasutavad seda õigust ametiühingu loomisel ja naabrid vabatahtlikult klubi asutamisel. Nimeta see.",
          "freedom of association",
          "ühinemisvabadus",
          "It protects people's ability to form and join groups voluntarily.",
          "See kaitseb inimeste võimalust vabatahtlikult rühmi luua ja nendega ühineda.",
          ["right of association"],
          ["ühinemisõigus"],
        ],
      ],
    ],
    [
      103,
      "round-one",
      "international-institutions",
      "Organisations in the News",
      "Organisatsioonid uudistes",
      [
        [
          "World_Economic_Forum",
          "Which forum brings political and business leaders together for its annual gathering in Davos?",
          "Milline foorum toob poliitika- ja ärijuhid kokku iga-aastasele kohtumisele Davosis?",
          "World Economic Forum",
          "Maailma Majandusfoorum",
          "The World Economic Forum is known for its annual Davos meeting of political and business leaders.",
          "Maailma Majandusfoorum on tuntud poliitika- ja ärijuhtide iga-aastase kohtumise poolest Davosis.",
          ["WEF", "Davos Forum"],
          ["WEF", "Davosi foorum"],
        ],
        [
          "Europol",
          "Name the EU agency that helps national police forces cooperate against cross-border crime.",
          "Nimeta ELi amet, mis aitab riikide politseil teha koostööd piiriülese kuritegevuse vastu.",
          "Europol",
          "Europol",
          "This agency supports cooperation and information sharing among European law-enforcement authorities.",
          "See amet toetab Euroopa õiguskaitseasutuste koostööd ja infovahetust.",
          [],
          [],
        ],
        [
          "G7",
          "News photos show the leaders of seven wealthy democracies meeting at this group's annual summit. Name the group.",
          "Uudisfotodel kohtuvad selle rühma iga-aastasel tippkohtumisel seitsme jõuka demokraatliku riigi juhid. Nimeta rühm.",
          "G7",
          "G7",
          "It is an informal group of seven major advanced democracies whose leaders meet annually.",
          "See on seitsme suure arenenud demokraatia mitteametlik rühm, mille juhid kohtuvad igal aastal.",
          [],
          [],
        ],
        [
          "European_Council",
          "EU heads of state or government meet in this body to set the union's overall political direction. Name it.",
          "ELi riigi- ja valitsusjuhid kohtuvad selles kogus, et määrata liidu üldine poliitiline suund. Nimeta see.",
          "European Council",
          "Euroopa Ülemkogu",
          "It brings together national leaders and defines the European Union's broad priorities.",
          "See toob kokku riikide juhid ja määrab Euroopa Liidu üldised prioriteedid.",
          [],
          [],
        ],
        [
          "Frontex",
          "Which EU agency coordinates support for countries controlling the union's external borders?",
          "Milline ELi amet koordineerib abi liidu välispiiri kontrollivatele riikidele?",
          "Frontex",
          "Frontex",
          "The agency coordinates European cooperation in managing external borders.",
          "See amet koordineerib Euroopa koostööd välispiiride haldamisel.",
          [],
          [],
        ],
      ],
    ],
    [
      104,
      "round-one",
      "international-institutions",
      "The Diplomatic Toolkit",
      "Diplomaatia tööriistad",
      [
        [
          "Ambassador",
          "At an embassy reception, this is the highest-ranking official representing their home country. Name the role.",
          "Saatkonna vastuvõtul on see oma koduriiki esindav kõrgeim ametnik. Nimeta amet.",
          "ambassador",
          "suursaadik",
          "This official is a country's highest-ranking diplomatic representative abroad.",
          "See ametnik on riigi kõrgeim diplomaatiline esindaja välismaal.",
          [],
          [],
        ],
        [
          "Diplomatic_immunity",
          "News reports use this term for legal protection that limits a host country's ability to prosecute an accredited foreign envoy. Name it.",
          "Uudistes kasutatakse seda terminit õigusliku kaitse kohta, mis piirab vastuvõtva riigi võimalust akrediteeritud välisesindajat vastutusele võtta. Nimeta see.",
          "diplomatic immunity",
          "diplomaatiline puutumatus",
          "It gives accredited envoys defined protections from the host state's legal jurisdiction.",
          "See annab akrediteeritud välisesindajatele kindlaksmääratud kaitse vastuvõtva riigi õigusvõimu eest.",
          ["diplomat's immunity"],
          ["diplomaadi puutumatus"],
        ],
        [
          "Diplomatic_bag",
          "A sealed official package travels between an embassy and its government without ordinary airport inspection. Name it.",
          "Suletud ametlik saadetis liigub saatkonna ja selle valitsuse vahel ilma tavapärase lennujaamakontrollita. Nimeta see.",
          "diplomatic bag",
          "diplomaatiline post",
          "This protected package carries official communications between a mission and its government.",
          "Selles kaitstud saadetises liiguvad ametlikud dokumendid esinduse ja valitsuse vahel.",
          ["diplomatic pouch"],
          ["diplomaadikott"],
        ],
        [
          "State_visit",
          "A head of state makes this formal trip to another country at its head of state's invitation and receives the highest level of ceremonial welcome. Name it.",
          "Riigipea teeb selle ametliku reisi teise riigipea kutsel ning teda tervitatakse kõrgeima taseme tseremooniatega. Nimeta see.",
          "state visit",
          "riigivisiit",
          "A state visit is a formal visit by one head of state to another country at that country's head-of-state invitation, with the highest level of ceremonial welcome.",
          "Riigivisiit on ühe riigipea ametlik külaskäik teise riiki selle riigi riigipea kutsel ning seda saadab kõrgeima taseme tseremoniaalne vastuvõtt.",
          ["official state visit"],
          ["riiklik visiit"],
        ],
        [
          "Bilateral_treaty",
          "Representatives of exactly two countries negotiate and sign this written deal. Name it.",
          "Täpselt kahe riigi esindajad räägivad läbi ja allkirjastavad selle kirjaliku kokkuleppe. Nimeta see.",
          "bilateral agreement",
          "kahepoolne kokkulepe",
          "It is a formal deal made between two countries or other parties.",
          "See on ametlik lepe kahe riigi või muu osapoole vahel.",
          ["bilateral treaty"],
          ["kahepoolne leping"],
        ],
      ],
    ],
    [
      105,
      "round-one",
      "economics",
      "Earnings and Deductions",
      "Teenistus ja mahaarvamised",
      [
        [
          {
            key: "govuk-payslips-employee-rights",
            sourceId:
              "source:politics-economics-society:govuk-payslips-employee-rights",
            title: "GOV.UK: Payslips: employee rights",
            url: "https://www.gov.uk/payslips",
            license: "OGL-3.0",
          },
          "An employer gives a worker this document showing earnings before and after deductions such as tax. Name it.",
          "Tööandja annab töötajale selle dokumendi, mis näitab teenistust enne ja pärast selliseid mahaarvamisi nagu maksud. Nimeta dokument.",
          "payslip",
          "palgaleht",
          "The document itemises a worker's earnings and deductions for a payment date.",
          "Dokumendis tuuakse maksepäeva kohta eraldi välja töötaja teenistus ja mahaarvamised.",
          ["pay slip", "wage slip"],
          ["palgateatis", "töötasu teatis"],
        ],
        [
          {
            key: "govuk-running-payroll-payslips",
            sourceId:
              "source:politics-economics-society:govuk-running-payroll-payslips",
            title: "GOV.UK: Running payroll — Payslips",
            url: "https://www.gov.uk/running-payroll/payslips",
            license: "OGL-3.0",
          },
          "Which line on a wage statement shows the worker's total earnings before tax and other deductions?",
          "Milline töötasu dokumendi rida näitab töötaja kogutasu enne makse ja muid mahaarvamisi?",
          "gross pay",
          "brutopalk",
          "This is the worker's total amount before deductions are removed.",
          "See on töötaja kogusumma enne mahaarvamiste tegemist.",
          ["gross earnings"],
          ["brutosissetulek"],
        ],
        [
          {
            key: "govuk-check-payslip-tax",
            sourceId:
              "source:politics-economics-society:govuk-check-payslip-tax",
            title: "GOV.UK: Check if the tax on your payslip is correct",
            url: "https://www.gov.uk/guidance/check-if-the-tax-on-your-payslip-is-correct",
            license: "OGL-3.0",
          },
          "What amount from a wage statement reaches the worker after tax and other deductions have been taken away?",
          "Milline töötasu summa jõuab töötajani pärast maksude ja muude mahaarvamiste tegemist?",
          "net pay",
          "netopalk",
          "This is the amount the worker actually receives after deductions.",
          "See on summa, mille töötaja pärast mahaarvamisi tegelikult kätte saab.",
          ["take-home pay"],
          ["kätte saadav palk"],
        ],
        [
          "Payroll",
          "Name the company activity that calculates employees' wages and sends the payments on payday.",
          "Nimeta ettevõtte tegevus, mille käigus arvutatakse töötajate tasu ja tehakse palgapäeval väljamaksed.",
          "payroll",
          "palgaarvestus",
          "It is the process used to calculate and pay employee wages.",
          "See on töötajate tasu arvutamise ja väljamaksmise protsess.",
          ["payroll processing"],
          ["töötasuarvestus"],
        ],
        [
          {
            key: "govuk-gender-pay-gap-preparing-data",
            sourceId:
              "source:politics-economics-society:govuk-gender-pay-gap-preparing-data",
            title: "GOV.UK: Preparing your data",
            url: "https://www.gov.uk/government/publications/gender-pay-gap-reporting-guidance-for-employers/preparing-your-data",
            license: "OGL-3.0",
          },
          "A worker may be paid for a week, two weeks, or a month at a time. Name this covered timeframe.",
          "Töötajale võidakse maksta korraga nädala, kahe nädala või kuu eest. Nimeta see ajavahemik.",
          "pay period",
          "palgaperiood",
          "It is the span of time covered by one wage payment.",
          "See on ühe palgamaksega hõlmatud ajavahemik.",
          ["payroll period"],
          ["palgaarvestusperiood"],
        ],
      ],
    ],
    [
      106,
      "round-one",
      "economics",
      "Everyday Price Talk",
      "Igapäevane hinnajutt",
      [
        [
          "Discounts_and_allowances",
          "A shop cuts 20 euros from an item's normal cost for a weekend sale. Name this reduction.",
          "Pood vähendab nädalavahetuse kampaania ajaks kauba tavahinda 20 euro võrra. Nimeta see hinnavähendus.",
          "discount",
          "allahindlus",
          "It is a reduction from the normal amount charged for a product or service.",
          "See on toote või teenuse tavalisest hinnast tehtav vähendus.",
          [],
          [],
        ],
        [
          "Comparison_shopping_website",
          "On this kind of site, a shopper searches for one product and sees offers from several sellers side by side. Name it.",
          "Sellisel saidil otsib ostja üht toodet ja näeb kõrvuti mitme müüja pakkumisi. Nimeta sait.",
          "price comparison website",
          "hinnavõrdlussait",
          "The site gathers offers so shoppers can compare prices across different sellers.",
          "Sait koondab pakkumised, et ostja saaks eri müüjate hindu võrrelda.",
          ["comparison shopping website", "price comparison site"],
          ["hinnavõrdlusportaal", "hinnavõrdluse veebisait"],
        ],
        [
          "Unit_price",
          "A supermarket shelf shows a cost per kilogram or litre so shoppers can compare differently sized packs. Name this figure.",
          "Supermarketi riiulil näidatakse maksumust kilogrammi või liitri kohta, et ostja saaks võrrelda eri suurusega pakendeid. Nimeta see näitaja.",
          "unit price",
          "ühikuhind",
          "It expresses a product's cost for one standard quantity, such as a kilogram or litre.",
          "See väljendab toote maksumust ühe standardkoguse, näiteks kilogrammi või liitri kohta.",
          [],
          [],
        ],
        [
          "Interest_rate",
          "What percentage is used to calculate either the cost of borrowing money or the return earned on savings?",
          "Millise protsendi järgi arvutatakse kas raha laenamise kulu või säästudelt teenitav tulu?",
          "interest rate",
          "intressimäär",
          "This percentage determines interest charged on a loan or paid on savings.",
          "Selle protsendi järgi määratakse laenult võetav või säästudelt makstav intress.",
          [],
          [],
        ],
        [
          "Consumer_price_index",
          "Which official measure tracks average changes in the cost of a standard basket of goods and services?",
          "Milline ametlik näitaja jälgib tüüpilise kaupade ja teenuste ostukorvi keskmist hinnamuutust?",
          "consumer price index",
          "tarbijahinnaindeks",
          "It follows how the prices paid for a representative shopping basket change over time.",
          "See jälgib, kuidas tüüpilise ostukorvi eest makstavad hinnad aja jooksul muutuvad.",
          ["CPI"],
          ["THI"],
        ],
      ],
    ],
    [
      107,
      "round-one",
      "economics",
      "Starting a New Job",
      "Uuele tööle asumine",
      [
        [
          "Job_interview",
          "At this meeting, an employer asks a candidate about experience and suitability for a role. Name it.",
          "Sellel kohtumisel küsib tööandja kandidaadilt tema kogemuse ja ametikohale sobivuse kohta. Nimeta kohtumine.",
          "job interview",
          "töövestlus",
          "It lets an employer assess a candidate and lets the candidate learn about the role.",
          "See võimaldab tööandjal kandidaati hinnata ning kandidaadil ametikoha kohta teavet saada.",
          ["employment interview"],
          ["tööintervjuu"],
        ],
        [
          "Employment_contract",
          "An employee and employer use this agreement to set their rights and responsibilities, including the work and pay. Name it.",
          "Töötaja ja tööandja määravad selles kokkuleppes oma õigused ning kohustused, sealhulgas töö ja tasu. Nimeta dokument.",
          "employment contract",
          "tööleping",
          "The agreement establishes the terms under which a person works for an employer.",
          "Selles kokkuleppes määratakse tingimused, mille alusel inimene tööandja juures töötab.",
          [],
          [],
        ],
        [
          "Timesheet",
          "Employees complete this table to record how long they worked on individual tasks. Name it.",
          "Töötajad märgivad sellesse tabelisse, kui kaua nad eri ülesannetega tegelesid. Nimeta dokument.",
          "timesheet",
          "tööajatabel",
          "It records the duration an employee spent on each task.",
          "Selles dokumendis peetakse arvestust töötaja eri ülesannetele kulunud aja üle.",
          ["time sheet"],
          ["tööaja arvestusleht"],
        ],
        [
          {
            key: "acas-probation-periods",
            sourceId:
              "source:politics-economics-society:acas-probation-periods",
            title: "Acas: What probation is — Probation periods",
            url: "https://www.acas.org.uk/probation-periods",
            license: "OGL-3.0",
          },
          "At the start of employment, the employer assesses the new worker's suitability while the worker checks whether the role fits. Name this time.",
          "Töösuhte alguses hindab tööandja uue töötaja sobivust ning töötaja omakorda, kas amet talle sobib. Nimeta see aeg.",
          "probationary period",
          "katseaeg",
          "This initial employment interval allows both employer and employee to assess whether the arrangement works.",
          "See töösuhte algusaeg võimaldab nii tööandjal kui ka töötajal hinnata, kas koostöö sobib.",
          ["probation period"],
          ["prooviperiood"],
        ],
        [
          "Notice_period",
          "Name the interval between announcing that employment will end and the employee's last working day.",
          "Nimeta ajavahemik töösuhte lõppemisest teatamise ja töötaja viimase tööpäeva vahel.",
          "notice period",
          "etteteatamisaeg",
          "It is the time that runs from notification of termination until the final day of work.",
          "See on aeg töösuhte lõpetamisest teatamisest kuni viimase tööpäevani.",
          ["period of notice"],
          ["töösuhte lõpetamisest etteteatamise aeg"],
        ],
      ],
    ],
    [
      108,
      "round-one",
      "currencies",
      "Details on Coins and Notes",
      "Detailid müntidel ja rahatähtedel",
      [
        [
          "Currency_symbol",
          "The dollar mark and euro mark are examples of this short sign written beside a money amount. Name it.",
          "Dollari- ja euromärk on näited sellisest lühikesest tähisest, mis kirjutatakse rahasumma kõrvale. Nimeta see.",
          "currency symbol",
          "valuutasümbol",
          "It is a compact sign used to show which money unit an amount uses.",
          "See on lühike märk, mis näitab, millises rahaühikus summa on esitatud.",
          ["currency sign"],
          ["rahaühiku sümbol"],
        ],
        [
          {
            key: "bank-of-england-plates-and-dies",
            sourceId:
              "source:politics-economics-society:bank-of-england-plates-and-dies",
            title: "Bank of England Museum: Plates and dies",
            url: "https://www.bankofengland.co.uk/museum/online-collections/banknotes/plates-and-dies",
            license: "All rights reserved",
          },
          "On a Bank of England note, this unique printed combination of letters and numbers identifies the individual note. Name it.",
          "Inglise Panga rahatähel eristab see ainulaadne tähtede ja numbrite kombinatsioon üht rahatähte teisest. Nimeta see tunnus.",
          "banknote serial number",
          "rahatähe seerianumber",
          "Bank of England notes use this letter-and-number combination as a unique identifier for each individual note.",
          "Inglise Panga rahatähtedel on see tähtede ja numbrite kombinatsioon iga üksiku rahatähe ainulaadne tunnus.",
          ["serial number"],
          ["seerianumber"],
        ],
        [
          "Watermark",
          "A faint image becomes visible when you hold paper money up to the light. Name this security feature.",
          "Paberraha valguse poole hoides muutub nähtavaks nõrk kujutis. Nimeta see turvaelement.",
          "banknote watermark",
          "rahatähe vesimärk",
          "The image is formed within the paper and can be checked against transmitted light.",
          "Kujutis moodustatakse paberi sisse ning seda saab kontrollida läbivas valguses.",
          ["watermark"],
          ["vesimärk"],
        ],
        [
          {
            key: "eesti-pank-2-euro-commemorative-coin-design-competition",
            sourceId:
              "source:politics-economics-society:eesti-pank-2-euro-commemorative-coin-design-competition",
            title: "Eesti Pank: 2-eurose mündi kujunduskonkurss",
            url: "https://www.eestipank.ee/press/2-eurose-mundi-kujunduskonkursile-saab-kavandeid-esitada-20-maini-10052011",
            license: "All rights reserved",
          },
          "A euro-area country issues this special-design two-euro coin to mark an important national or European event. Name it.",
          "Euroala riik annab selle erikujundusega kahe-eurose mündi välja tähtsa riikliku või Euroopa sündmuse tähistamiseks. Nimeta see.",
          "commemorative coin",
          "mälestusmünt",
          "Eesti Pank distinguishes circulating two-euro commemorative coins with special designs marking important national or European events from collector coins.",
          "Eesti Pank eristab ringlusse mõeldud erikujundusega kahe-euroseid mälestusmünte, millega tähistatakse olulisi riiklikke või Euroopa sündmusi, meenemüntidest.",
          ["2 euro commemorative coin"],
          ["2-eurone mälestusmünt"],
        ],
        [
          "Security_thread",
          "This narrow strip is embedded through a paper note to make counterfeiting harder. Name the feature.",
          "See kitsas riba paigutatakse paberraha sisse, et võltsimist raskendada. Nimeta turvaelement.",
          "security thread",
          "turvaniit",
          "The embedded strip is one of the features used to authenticate paper money.",
          "Paberi sisse paigutatud riba on üks paberraha ehtsuse kontrollimise tunnuseid.",
          ["security strip"],
          ["turvariba"],
        ],
      ],
    ],
    [
      109,
      "round-one",
      "currencies",
      "Money Around Europe",
      "Euroopa rahad",
      [
        [
          "Swiss_franc",
          "What official money is used in Switzerland and Liechtenstein?",
          "Millist ametlikku raha kasutatakse Šveitsis ja Liechtensteinis?",
          "Swiss franc",
          "Šveitsi frank",
          "This is the official money of both Switzerland and Liechtenstein.",
          "See on nii Šveitsi kui ka Liechtensteini ametlik raha.",
          ["Swiss francs"],
          ["Šveitsi frangid"],
        ],
        [
          "Swedish_krona",
          "Name the official money used in Sweden.",
          "Nimeta Rootsis kasutatav ametlik raha.",
          "Swedish krona",
          "Rootsi kroon",
          "Sweden uses this national money instead of the euro.",
          "Rootsi kasutab euro asemel seda oma riigi raha.",
          ["Swedish crowns"],
          ["Rootsi kroonid"],
        ],
        [
          "Danish_krone",
          "Name the official money used in Denmark.",
          "Nimeta Taanis kasutatav ametlik raha.",
          "Danish krone",
          "Taani kroon",
          "Denmark uses this national money instead of the euro.",
          "Taani kasutab euro asemel seda oma riigi raha.",
          ["Danish crowns"],
          ["Taani kroonid"],
        ],
        [
          "Polish_z%C5%82oty",
          "Which official money of Poland has a name derived from a word meaning golden?",
          "Millise Poola ametliku raha nimi pärineb kuldset tähendavast sõnast?",
          "Polish złoty",
          "Poola zlott",
          "Its name is connected to the Polish adjective for golden.",
          "Selle nimi on seotud poolakeelse omadussõnaga, mis tähendab kuldset.",
          ["Polish zloty"],
          ["zlott"],
        ],
        [
          "Hungarian_forint",
          "Name the official money used in Hungary.",
          "Nimeta Ungaris kasutatav ametlik raha.",
          "Hungarian forint",
          "Ungari forint",
          "Hungary uses this national money instead of the euro.",
          "Ungari kasutab euro asemel seda oma riigi raha.",
          ["Hungarian forints"],
          ["Ungari forintid"],
        ],
      ],
    ],
    [
      110,
      "round-one",
      "law-courts",
      "Inside a Courtroom",
      "Kohtusaalis",
      [
        [
          "Courtroom",
          "In courtroom dramas, a person giving evidence goes to this designated place before answering questions. Name it.",
          "Kohtudraamades läheb ütlusi andev inimene enne küsimustele vastamist sellele kindlale kohale. Nimeta see.",
          "witness stand",
          "tunnistajapink",
          "It is the designated place in a courtroom from which a witness gives testimony.",
          "See on kohtusaalis kindel koht, kust tunnistaja annab ütlusi.",
          ["witness box"],
          ["tunnistajakast"],
        ],
        [
          {
            key: "utah-courts-court-interpreter-faq",
            sourceId:
              "source:politics-economics-society:utah-courts-court-interpreter-faq",
            title: "Utah State Courts: How to Become a Court Interpreter",
            url: "https://www.utcourts.gov/en/court-records-publications/resources/court-interpreters/faq.html",
            license: "All rights reserved",
          },
          "This person orally renders speech from one language into another during a hearing. Name the role.",
          "See inimene tõlgib istungil kõnet suuliselt ühest keelest teise. Nimeta amet.",
          "court interpreter",
          "kohtutõlk",
          "The role allows participants who use different languages to understand spoken proceedings.",
          "See amet võimaldab eri keeli kasutavatel osalejatel suulisest menetlusest aru saada.",
          ["courtroom interpreter"],
          ["kohtusaali tõlk"],
        ],
        [
          "Plaintiff",
          "In a civil lawsuit, what do you call the person or organisation that brought the case against the other side?",
          "Kuidas nimetatakse tsiviilkohtuasjas inimest või organisatsiooni, kes esitas teise poole vastu hagi?",
          "plaintiff",
          "hageja",
          "This is the party that initiates a civil case against another party.",
          "See on pool, kes algatab teise poole vastu tsiviilasja.",
          ["claimant"],
          ["hagi esitaja"],
        ],
        [
          "Court_clerk",
          "Which hearing official keeps the case documents, records, and schedule in order?",
          "Milline istungil töötav ametnik hoiab korras kohtuasja dokumendid, kirjed ja ajakava?",
          "court clerk",
          "kohtusekretär",
          "This official handles administrative records and documents for the judicial process.",
          "See ametnik korraldab kohtumenetluse haldusdokumente ja kirjeid.",
          ["clerk of court"],
          ["kohtuistungi sekretär"],
        ],
        [
          "Courtroom_sketch",
          "When cameras are restricted during a hearing, this person's drawings may appear in the news. Name the role.",
          "Kui kaamerate kasutamine istungil on piiratud, võidakse uudistes näidata selle inimese joonistusi. Nimeta amet.",
          "courtroom sketch artist",
          "kohtusaali kunstnik",
          "This person draws scenes from proceedings that cannot be freely photographed or filmed.",
          "See inimene joonistab stseene menetlusest, mida ei saa vabalt pildistada ega filmida.",
          ["court artist", "sketch artist"],
          ["kohtukunstnik", "kohtusaali joonistaja"],
        ],
      ],
    ],
    [
      111,
      "round-two",
      "law-courts",
      "Legal Paperwork",
      "Õigusdokumendid",
      [
        [
          "Arrest_warrant",
          "Police may arrest and detain a specified person once a court issues this document. Name it.",
          "Politsei võib kindlaksmääratud inimese vahistada ja kinni pidada, kui kohus annab välja selle dokumendi. Nimeta see.",
          "arrest warrant",
          "vahistamismäärus",
          "An arrest warrant is a court-issued document authorising the arrest and detention of a specified person.",
          "Vahistamismäärus on kohtu välja antud dokument, mis lubab kindlaksmääratud inimese vahistada ja kinni pidada.",
          ["arrest order"],
          ["vahistamise määrus"],
        ],
        [
          "Search_warrant",
          "This court document authorises police to look through a specified home or other place for evidence of a crime. Name it.",
          "See kohtu dokument annab politseile loa otsida kindlaksmääratud kodust või muust paigast kuriteo tõendeid. Nimeta see.",
          "search warrant",
          "läbiotsimismäärus",
          "A search warrant authorises police to search a specified place for evidence of a crime.",
          "Läbiotsimismäärus annab politseile loa otsida kindlaksmääratud paigast kuriteo tõendeid.",
          ["search order"],
          ["läbiotsimisluba"],
        ],
        [
          {
            key: "riigi-teataja-civil-procedure-case-file",
            sourceId:
              "source:politics-economics-society:riigi-teataja-civil-procedure-case-file",
            title: "Estonian Code of Civil Procedure: Chapter 9, Case File",
            url: "https://www.riigiteataja.ee/public-api/api/v1/en/akt/510042025001/blob-html#para56lg1",
            license: "public-domain-government",
          },
          "A court keeps this collection of procedural documents and other relevant information for one civil case. Name it.",
          "Kohus hoiab selles kogumis ühe tsiviilasja menetlusdokumente ja muid asjaga seotud andmeid. Nimeta see.",
          "case file",
          "kohtutoimik",
          "A case file is the collection of procedural documents and other relevant information kept for one court case.",
          "Kohtutoimik on ühe kohtuasja kohta hoitavate menetlusdokumentide ja muude asjakohaste andmete kogum.",
        ],
        [
          "Power_of_attorney",
          "You sign this document so another person can handle banking or legal matters on your behalf. Name it.",
          "Sa allkirjastad selle dokumendi, et teine inimene saaks sinu nimel panga- või õigustoiminguid teha. Nimeta see.",
          "power of attorney",
          "volikiri",
          "A power of attorney lets one person act on another person's behalf in specified matters.",
          "Volikiri lubab ühel inimesel kindlaksmääratud küsimustes teise nimel tegutseda.",
        ],
        [
          "Restraining_order",
          "A court issues this to require one person to keep away from and not contact another. Name it.",
          "Kohus annab selle välja, et kohustada üht inimest teisest eemale hoidma ja temaga mitte ühendust võtma. Nimeta see.",
          "restraining order",
          "lähenemiskeeld",
          "A restraining order directs a person to keep away from and avoid contacting another person.",
          "Lähenemiskeeld kohustab inimest teisest eemale hoidma ja temaga ühenduse võtmist vältima.",
        ],
      ],
    ],
    [
      112,
      "round-two",
      "law-courts",
      "Rules of the Road",
      "Liiklusreeglid",
      [
        [
          "Speed_limit",
          "On a road sign, this is the highest number above which drivers may not travel on that stretch. Name it.",
          "Liiklusmärgil on see suurim arv, millest kiiremini sellel teelõigul sõita ei tohi. Nimeta see.",
          "speed limit",
          "kiiruspiirang",
          "A speed limit sets the highest legal driving speed for a stretch of road.",
          "Kiiruspiirang määrab teelõigul suurima lubatud sõidukiiruse.",
        ],
        [
          "Traffic_enforcement_camera",
          "This roadside device photographs vehicles travelling faster than the legal maximum. Name it.",
          "See teeäärne seade pildistab lubatust kiiremini liikuvaid sõidukeid. Nimeta see.",
          "speed camera",
          "kiiruskaamera",
          "A speed camera records vehicles that exceed the legal maximum speed.",
          "Kiiruskaamera salvestab sõidukeid, mis ületavad suurimat lubatud sõidukiirust.",
          ["speed enforcement camera"],
          ["automaatne kiiruskaamera"],
        ],
        [
          "Breathalyzer",
          "A driver blows into this device so alcohol can be estimated from the exhaled air. Name it.",
          "Juht puhub sellesse seadmesse, et väljahingatava õhu järgi alkoholi kogust hinnata. Nimeta see.",
          "breathalyser",
          "alkomeeter",
          "A breathalyser estimates alcohol in a person's body by analysing a breath sample.",
          "Alkomeeter hindab inimese organismis oleva alkoholi kogust väljahingatava õhu proovi abil.",
          ["breathalyzer"],
          ["alkoholitester"],
        ],
        [
          "Parking_violation",
          "A driver may receive this penalty notice after leaving a car where or when it is forbidden. Name it.",
          "Juht võib saada selle karistusteate, kui jätab auto lubamatusse kohta või lubamatul ajal. Nimeta see.",
          "parking ticket",
          "parkimistrahv",
          "A parking ticket is a penalty notice issued for leaving a vehicle where or when it is not allowed.",
          "Parkimistrahv on karistus auto lubamatusse kohta või lubamatul ajal jätmise eest.",
          ["parking fine"],
          ["parkimise trahv"],
        ],
        [
          "Vehicle_inspection",
          "A car periodically undergoes this official check to confirm that it is safe and fit for public roads. Name it.",
          "Auto läbib korrapäraselt selle ametliku kontrolli, et kinnitada selle ohutust ja sobivust avalikel teedel sõitmiseks. Nimeta see.",
          "vehicle inspection",
          "tehnoülevaatus",
          "A vehicle inspection is a periodic official check of a vehicle's roadworthiness.",
          "Tehnoülevaatus on sõiduki liikluskõlblikkuse korrapärane ametlik kontroll.",
        ],
      ],
    ],
    [
      113,
      "round-two",
      "sociology",
      "Neighbours Helping Neighbours",
      "Naabrid aitavad naabreid",
      [
        [
          "Food_bank",
          "This charity collects donated groceries and distributes them to people who need help. Name it.",
          "See heategevusorganisatsioon kogub annetatud söögikraami ja jagab seda abi vajavatele inimestele. Nimeta see.",
          "food bank",
          "toidupank",
          "A food bank collects and distributes donated groceries to people in need.",
          "Toidupank kogub annetatud söögikraami ja jagab seda abi vajavatele inimestele.",
        ],
        [
          "Neighborhood_watch",
          "In this scheme, local residents cooperate and report suspicious activity to help prevent crime. Name it.",
          "Selles süsteemis teevad piirkonna elanikud koostööd ja teatavad kuritegevuse vältimiseks kahtlasest tegevusest. Nimeta see.",
          "neighbourhood watch",
          "naabrivalve",
          "Neighbourhood watch involves residents cooperating and reporting suspicious local activity to help prevent crime.",
          "Naabrivalve tähendab, et elanikud teevad koostööd ja teatavad kuritegevuse vältimiseks piirkonnas toimuvast kahtlasest tegevusest.",
          ["neighborhood watch"],
          ["naabruskonna valve"],
        ],
        [
          "Blood_donation",
          "At a donor centre, a volunteer gives some of their blood so it can be used to treat patients. Name this act.",
          "Doonorikeskuses loovutab vabatahtlik osa oma verest, et seda saaks kasutada patsientide raviks. Nimeta see tegevus.",
          "blood donation",
          "veredoonorlus",
          "Blood donation is the voluntary giving of blood for use in treating patients.",
          "Veredoonorlus on vabatahtlik vere loovutamine patsientide raviks.",
          ["donating blood"],
          ["vere loovutamine"],
        ],
        [
          "Community_gardening",
          "Local residents grow flowers, herbs, or vegetables together on this shared plot. Name it.",
          "Piirkonna elanikud kasvatavad sellel ühisel maatükil koos lilli, maitsetaimi või köögivilju. Nimeta see.",
          "community garden",
          "kogukonnaaed",
          "A community garden is a shared plot cultivated by local residents.",
          "Kogukonnaaed on ühine maatükk, mida piirkonna elanikud koos harivad.",
          ["shared garden"],
          ["ühisaed"],
        ],
        [
          "Charity_shop",
          "This store sells donated goods to raise money for a cause. Name it.",
          "See kauplus müüb annetatud esemeid, et koguda raha mõne eesmärgi heaks. Nimeta see.",
          "charity shop",
          "heategevuspood",
          "A charity shop sells donated goods and uses the proceeds to support a cause.",
          "Heategevuspood müüb annetatud esemeid ja kasutab saadud tulu mõne eesmärgi toetamiseks.",
          ["charity store"],
          ["annetuspood"],
        ],
      ],
    ],
    [
      114,
      "round-two",
      "sociology",
      "How Society Shapes Us",
      "Kuidas ühiskond meid mõjutab",
      [
        [
          "First_impression_(psychology)",
          "This opinion forms in the first moments of meeting someone, before you know them well. Name it.",
          "See arvamus kujuneb kellegagi kohtumise esimestel hetkedel, enne kui sa teda hästi tunned. Nimeta see.",
          "first impression",
          "esmamulje",
          "A first impression is an initial opinion formed when one person first encounters another.",
          "Esmamulje on esialgne arvamus, mis kujuneb inimesega esimest korda kohtudes.",
        ],
        [
          "Social_norm",
          "Members of a group generally expect people to follow this unwritten rule of behaviour. Name it.",
          "Rühma liikmed ootavad üldiselt, et inimesed järgiksid seda kirjutamata käitumisreeglit. Nimeta see.",
          "social norm",
          "sotsiaalne norm",
          "A social norm is an unwritten rule describing behaviour that a group generally expects.",
          "Sotsiaalne norm on kirjutamata reegel, mis kirjeldab rühmas üldiselt oodatavat käitumist.",
          ["societal norm"],
          ["ühiskondlik norm"],
        ],
        [
          "Culture_shock",
          "A person may feel this confusion or discomfort after entering a place with an unfamiliar way of life. Name it.",
          "Inimene võib tunda seda segadust või ebamugavust talle võõra eluviisiga paika sattudes. Nimeta see.",
          "culture shock",
          "kultuurišokk",
          "Culture shock is confusion or discomfort caused by entering an unfamiliar culture or way of life.",
          "Kultuurišokk on võõrasse kultuuri või eluviisi sattumisest põhjustatud segadus või ebamugavus.",
        ],
        [
          "Generation_gap",
          "This expression describes differences in attitudes and habits between younger and older people. Name it.",
          "See väljend kirjeldab nooremate ja vanemate inimeste hoiakute ning harjumuste erinevust. Nimeta see.",
          "generation gap",
          "põlvkondade lõhe",
          "A generation gap is a difference in attitudes or habits between younger and older generations.",
          "Põlvkondade lõhe on nooremate ja vanemate põlvkondade hoiakute või harjumuste erinevus.",
          ["generational gap"],
          ["põlvkondadevaheline lõhe"],
        ],
        [
          "Bystander_effect",
          "In an emergency, a person may be less likely to help when several other witnesses are present. Name this effect.",
          "Hädaolukorras võib inimene aidata väiksema tõenäosusega, kui kohal on veel mitu pealtnägijat. Nimeta see mõju.",
          "bystander effect",
          "kõrvalseisja efekt",
          "The bystander effect makes an individual less likely to help in an emergency when other people are present.",
          "Kõrvalseisja efekti korral aitab inimene hädaolukorras väiksema tõenäosusega, kui kohal on teised inimesed.",
          ["bystander apathy"],
          ["kõrvalseisja apaatia"],
        ],
      ],
    ],
    [
      115,
      "round-two",
      "sociology",
      "Making Your Voice Heard",
      "Oma hääle kuuldavaks tegemine",
      [
        [
          {
            key: "university-delaware-campaign-events",
            sourceId:
              "source:politics-economics-society:university-delaware-campaign-events",
            title:
              "University of Delaware Library: Campaign events — Trail to the Voting Booth",
            url: "https://exhibitions.lib.udel.edu/trail-to-the-voting-booth/on-the-trail/campaign-events/",
            license: "All rights reserved",
          },
          "During an election campaign, a candidate speaks at this public gathering while supporters come together. Name it.",
          "Valimiskampaania ajal kõneleb kandidaat sellel avalikul kogunemisel ja toetajad tulevad kokku. Nimeta see.",
          "campaign rally",
          "valimiskoosolek",
          "A campaign rally is a public election event where a candidate speaks to a gathering of supporters.",
          "Valimiskoosolek on avalik valimisüritus, kus kandidaat kõneleb kokkutulnud toetajatele.",
          ["election rally"],
          ["valimismiiting"],
        ],
        [
          "Opinion_poll",
          "This survey asks a selected group what they think about an issue or candidate. Name it.",
          "Selles uuringus küsitakse valitud inimrühmalt, mida nad mõnest küsimusest või kandidaadist arvavad. Nimeta see.",
          "opinion poll",
          "arvamusküsitlus",
          "An opinion poll surveys a selected group to measure what people think about a subject.",
          "Arvamusküsitlus uurib valitud inimrühma kaudu, mida inimesed mingil teemal arvavad.",
          ["public opinion poll"],
          ["arvamusuuring"],
        ],
        [
          "Letter_to_the_editor",
          "A newspaper reader sends this message for publication on the paper's comment page. Name it.",
          "Ajalehe lugeja saadab selle sõnumi avaldamiseks väljaande arvamusküljele. Nimeta see.",
          "letter to the editor",
          "lugejakiri",
          "A letter to the editor is a reader's message submitted to a publication for its comment section.",
          "Lugejakiri on lugeja sõnum, mis saadetakse väljaandele arvamusküljel avaldamiseks.",
        ],
        [
          {
            key: "resource-centre-letter-writing-campaign",
            sourceId:
              "source:politics-economics-society:resource-centre-letter-writing-campaign",
            title: "Resource Centre: Organising a letter-writing campaign",
            url: "https://www.resourcecentre.org.uk/information/organising-a-letter-writing-campaign/",
            license: "All rights reserved",
          },
          "In this organised effort, many people write to a decision-maker asking for the same change. Name it.",
          "Selles korraldatud ettevõtmises kirjutavad paljud inimesed otsustajale ja paluvad sama muudatust. Nimeta see.",
          "letter-writing campaign",
          "kirjakampaania",
          "A letter-writing campaign organises many people to write to a decision-maker in support of the same change.",
          "Kirjakampaania käigus kirjutavad paljud inimesed otsustajale sama muudatuse toetuseks.",
          ["letter campaign"],
          ["kirjade kirjutamise kampaania"],
        ],
        [
          "Public_consultation",
          "Before making a decision, an authority uses this process to invite comments from residents and organisations. Name it.",
          "Enne otsuse tegemist kasutab ametiasutus seda protsessi, et paluda elanikel ja organisatsioonidel arvamust avaldada. Nimeta see.",
          "public consultation",
          "avalik konsultatsioon",
          "A public consultation invites residents and organisations to comment before an authority makes a decision.",
          "Avalik konsultatsioon kutsub elanikke ja organisatsioone enne ametiasutuse otsust arvamust avaldama.",
          ["public comment process"],
          ["avalik arutelu"],
        ],
      ],
    ],
    [
      116,
      "round-two",
      "education",
      "A School Day",
      "Koolipäev",
      [
        [
          "School_bell",
          "This ringing signal marks the start or end of a lesson. Name it.",
          "See helisev märguanne tähistab õppetunni algust või lõppu. Nimeta see.",
          "school bell",
          "koolikell",
          "A school bell signals when a lesson or another part of the school day begins or ends.",
          "Koolikell annab märku õppetunni või koolipäeva muu osa algusest ja lõpust.",
        ],
        [
          "School_meal",
          "Pupils eat this midday meal during their study day. Name it.",
          "Õpilased söövad seda keskpäevast einet oma õppepäeva jooksul. Nimeta see.",
          "school lunch",
          "koolilõuna",
          "A school lunch is a midday meal served to pupils during the school day.",
          "Koolilõuna on keskpäevane eine, mida õpilastele koolipäeva jooksul pakutakse.",
        ],
        [
          "School_uniform",
          "Pupils at one educational institution are required to wear this matching clothing. Name it.",
          "Ühe õppeasutuse õpilased peavad kandma seda ühesugust rõivastust. Nimeta see.",
          "school uniform",
          "koolivorm",
          "A school uniform is matching clothing that pupils at an institution are required to wear.",
          "Koolivorm on ühesugune rõivastus, mida ühe õppeasutuse õpilased peavad kandma.",
        ],
        [
          "Pencil_case",
          "This small box or pouch keeps a pupil's pens, pencils and eraser together. Name it.",
          "Selles väikeses karbis või kotikeses hoiab õpilane pastakaid, pliiatseid ja kustukummi. Nimeta see.",
          "pencil case",
          "pinal",
          "It is a small container for writing tools such as pens and pencils.",
          "See on väike karp või kotike kirjutusvahendite, näiteks pastakate ja pliiatsite jaoks.",
          ["pencil box", "pencil pouch"],
          ["pliiatsikarp", "pliiatsikott"],
        ],
        [
          "Field_trip",
          "On this organised visit, pupils learn somewhere away from their usual classroom. Name it.",
          "Sellel korraldatud väljasõidul õpivad õpilased väljaspool oma tavapärast klassiruumi. Nimeta see.",
          "class trip",
          "klassiekskursioon",
          "A class trip takes pupils away from their usual classroom for an organised educational visit.",
          "Klassiekskursioon viib õpilased korraldatud õppekäigule väljapoole nende tavapärast klassiruumi.",
          ["field trip"],
          ["õppekäik"],
        ],
      ],
    ],
    [
      117,
      "round-two",
      "education",
      "Around Campus",
      "Ülikoolilinnakus",
      [
        [
          "Lecture_hall",
          "At a university, many students sit in rows in this large room to listen to a talk. Name it.",
          "Ülikoolis istuvad paljud tudengid selles suures ridadega ruumis, et ettekannet kuulata. Nimeta see.",
          "lecture hall",
          "loengusaal",
          "A lecture hall is a large room with rows of seats for talks at a university.",
          "Loengusaal on suur istmeridadega ruum ülikoolis peetavate ettekannete jaoks.",
          ["lecture theatre", "lecture room"],
          ["loenguruum", "auditoorium"],
        ],
        [
          "Campus_card",
          "This card proves enrolment at a college or university and gives its holder access to campus services and resources. Name it.",
          "See kaart tõendab kõrgkoolis õppimist ning annab selle omanikule juurdepääsu õppeasutuse teenustele ja vahenditele. Nimeta see.",
          "student ID card",
          "üliõpilaspilet",
          "A student ID card proves enrolment and can provide access to services and resources on campus.",
          "Üliõpilaspilet tõendab kõrgkoolis õppimist ning võib anda juurdepääsu õppeasutuse teenustele ja vahenditele.",
          ["student ID", "student card"],
          ["üliõpilaskaart", "tudengikaart"],
        ],
        [
          "Students%27_union",
          "This organisation represents learners at a college or university and often provides services for them. Name it.",
          "See organisatsioon esindab kõrgkoolis õppijaid ja pakub neile sageli teenuseid. Nimeta see.",
          "student union",
          "üliõpilasesindus",
          "A student union represents students at a college or university and often provides services for them.",
          "Üliõpilasesindus esindab kõrgkooli õppureid ja pakub neile sageli teenuseid.",
          ["students' union"],
          ["üliõpilasliit"],
        ],
        [
          "Academic_library",
          "This campus place and service offers books, journals, and databases for study and research. Name it.",
          "See õppeasutuse koht ja teenus pakub õppimiseks ning uurimistööks raamatuid, ajakirju ja andmebaase. Nimeta see.",
          "university library",
          "ülikooli raamatukogu",
          "A university library provides books, journals, databases, and other resources for higher education and research.",
          "Ülikooli raamatukogu pakub kõrghariduse ja uurimistöö jaoks raamatuid, ajakirju, andmebaase ning muid vahendeid.",
        ],
        [
          "Thesis",
          "At this formal session, a learner presents final research and answers examiners' questions about it. Name the session.",
          "Sellel ametlikul arutelul esitleb üliõpilane oma uurimistööd ja vastab hindajate küsimustele. Nimeta arutelu.",
          "thesis defence",
          "lõputöö kaitsmine",
          "A thesis defence is a formal session in which a student presents research and answers examiners' questions.",
          "Lõputöö kaitsmine on ametlik arutelu, kus üliõpilane esitleb oma uurimistööd ja vastab hindajate küsimustele.",
          ["thesis defense", "oral defence", "oral defense"],
          ["lõputöö kaitse", "uurimistöö kaitsmine", "uurimistöö kaitse"],
        ],
      ],
    ],
    [
      118,
      "round-two",
      "education",
      "Learning for a Career",
      "Ametiks õppimine",
      [
        [
          {
            key: "epale-online-learning-concepts",
            sourceId:
              "source:politics-economics-society:epale-online-learning-concepts",
            title: "EPALE: Õpime internetis — aga kas mõisted on selged?",
            url: "https://epale.ec.europa.eu/et/blog/opime-internetis-aga-kas-moisted-selged",
            license: "CC-BY-NC-SA-4.0",
          },
          "This organised series of lessons is completed through the internet instead of in a physical classroom. Name it.",
          "See korraldatud õppetundide sari läbitakse füüsilise klassiruumi asemel interneti kaudu. Nimeta see.",
          "online course",
          "veebikursus",
          "An online course is an organised series of lessons delivered and completed through the internet.",
          "Veebikursus on korraldatud õppetundide sari, mida pakutakse ja läbitakse interneti kaudu.",
          ["online class"],
          ["e-kursus"],
        ],
        [
          "Bachelor%27s_degree",
          "This first common university qualification is usually earned after several years of undergraduate study. Name it.",
          "See esimene tavapärane ülikoolikvalifikatsioon saadakse üldjuhul mitme aasta pikkuse kõrgharidusõppe järel. Nimeta see.",
          "bachelor's degree",
          "bakalaureusekraad",
          "A bachelor's degree is a common first university qualification earned through undergraduate study.",
          "Bakalaureusekraad on tavapärane esimene ülikoolikvalifikatsioon, mis saadakse kõrgharidusõppe läbimisel.",
        ],
        [
          "Master%27s_degree",
          "This advanced university qualification is usually taken after completing an initial degree. Name it.",
          "See kõrgem ülikoolikvalifikatsioon omandatakse tavaliselt pärast esimese kõrgharidusastme lõpetamist. Nimeta see.",
          "master's degree",
          "magistrikraad",
          "A master's degree is an advanced university qualification usually completed after an initial degree.",
          "Magistrikraad on kõrgem ülikoolikvalifikatsioon, mis omandatakse tavaliselt pärast esimese kõrgharidusastme lõpetamist.",
        ],
        [
          "Adult_education",
          "An adult returns to organised learning later in life to finish school, learn basic literacy, or gain a new skill. Name this kind of education.",
          "Täiskasvanu naaseb hilisemas eas organiseeritud õppesse, et kool lõpetada, omandada põhiline kirjaoskus või õppida uus oskus. Nimeta selline haridus.",
          "adult education",
          "täiskasvanuharidus",
          "Adult education is education and organised learning for adults, including finishing school, basic literacy, and learning new skills.",
          "Täiskasvanuharidus on täiskasvanutele mõeldud haridus ja organiseeritud õpe, sealhulgas kooli lõpetamine, põhilise kirjaoskuse omandamine ja uute oskuste õppimine.",
          ["adult learning"],
          ["täiskasvanute haridus"],
        ],
        [
          {
            key: "govuk-become-an-apprentice",
            sourceId:
              "source:politics-economics-society:govuk-become-an-apprentice",
            title: "GOV.UK: Become an apprentice — How apprenticeships work",
            url: "https://www.gov.uk/become-apprentice",
            license: "OGL-3.0",
          },
          "This training route combines practical learning in a workplace with organised lessons. Name it.",
          "See õppevorm ühendab töökohal saadava praktilise kogemuse korraldatud õppetööga. Nimeta see.",
          "apprenticeship",
          "õpipoisiõpe",
          "An apprenticeship combines practical workplace training with organised study.",
          "Õpipoisiõpe ühendab praktilise töökohal õppimise korraldatud õppetööga.",
          ["apprenticeship training"],
          ["töökohapõhine õpe"],
        ],
      ],
    ],
    [
      119,
      "round-two",
      "demographics",
      "Reading Population Charts",
      "Rahvastikugraafikute lugemine",
      [
        [
          "Life_expectancy",
          "On a population chart, this figure gives the average years a newborn would live if the measured pattern of deaths by age stayed the same. Name it.",
          "Rahvastikugraafikul näitab see keskmist aastate arvu, mille vastsündinu elaks, kui mõõdetud vanusepõhine suremus püsiks samasugune. Nimeta see.",
          "life expectancy",
          "oodatav eluiga",
          "Life expectancy estimates the average number of years a newborn would live if the measured age-specific mortality pattern stayed the same.",
          "Oodatav eluiga näitab keskmist aastate arvu, mille vastsündinu elaks, kui mõõdetud vanusepõhine suremus püsiks samasugune.",
          ["expected lifespan"],
          ["keskmine eeldatav eluiga"],
        ],
        [
          "Mortality_rate",
          "A population table may show this figure as ten deaths per thousand residents in one year. Name it.",
          "Rahvastikutabel võib näidata seda näitajat näiteks kümne surmana tuhande elaniku kohta aastas. Nimeta see.",
          "death rate",
          "suremusmäär",
          "A death rate records the number of deaths in a population during a specified period, often relative to population size.",
          "Suremusmäär näitab surmade arvu rahvastikus kindla ajavahemiku jooksul, sageli elanike arvuga võrrelduna.",
          ["mortality rate"],
          ["suremuskordaja"],
        ],
        [
          {
            key: "eurostat-population-metadata",
            sourceId:
              "source:politics-economics-society:eurostat-population-metadata",
            title: "Eurostat: Population metadata",
            url: "https://webgate.ec.europa.eu/eurostat/cache/metadata/en/demo_pop_esms.htm",
            license: "CC-BY-4.0",
          },
          "This age divides a population chart so that half the people are younger and half are older. Name it.",
          "See vanus jagab rahvastikugraafiku nii, et pool elanikkonda on noorem ja pool vanem. Nimeta see.",
          "median age",
          "mediaanvanus",
          "The median age divides a population into two equal-sized groups, one younger and one older.",
          "Mediaanvanus jagab elanikkonna kaheks võrdseks rühmaks, millest üks on noorem ja teine vanem.",
          ["population median age"],
          ["rahvastiku mediaanvanus"],
        ],
        [
          "Population_pyramid",
          "On this two-sided chart, age groups run upward while male and female bars appear on opposite sides. Name it.",
          "Sellel kahepoolsel graafikul paiknevad vanuserühmad alt üles ning meeste ja naiste tulbad vastaskülgedel. Nimeta see.",
          "population pyramid",
          "rahvastikupüramiid",
          "A population pyramid uses opposing bars to show the age and sex distribution of a population.",
          "Rahvastikupüramiid näitab vastassuunaliste tulpade abil rahvastiku vanuselist ja soolist jaotust.",
          ["age-sex pyramid"],
          ["vanusepüramiid"],
        ],
        [
          "Human_sex_ratio",
          "This population comparison may be written as the number of males for every 100 females. Name it.",
          "Seda rahvastiku võrdlust võib väljendada meeste arvuna iga saja naise kohta. Nimeta see.",
          "sex ratio",
          "sugude suhe",
          "The sex ratio compares the number of males with the number of females in a population.",
          "Sugude suhe võrdleb meeste ja naiste arvu rahvastikus.",
          ["male-to-female ratio"],
          ["meeste ja naiste arvuline suhe"],
        ],
      ],
    ],
    [
      120,
      "round-two",
      "demographics",
      "When Populations Change",
      "Kui rahvastik muutub",
      [
        [
          "Baby_boom",
          "A births chart shows this sharp temporary spike, famously seen in many countries after the Second World War. Name it.",
          "Sündide graafik näitab seda järsku ajutist hüpet, mida täheldati paljudes riikides pärast Teist maailmasõda. Nimeta see.",
          "baby boom",
          "beebibuum",
          "A baby boom is a temporary period with a sharp rise in the number of births.",
          "Beebibuum on ajutine periood, mil sündide arv järsult suureneb.",
          ["post-war baby boom"],
          ["sündimusbuum"],
        ],
        [
          "Population_ageing",
          "News uses this phrase when the share of residents aged 65 and over keeps growing. Name it.",
          "Uudistes kasutatakse seda väljendit olukorra kohta, kus vähemalt 65-aastaste elanike osakaal aina suureneb. Nimeta see.",
          "ageing population",
          "vananev rahvastik",
          "An ageing population has a growing proportion of older people.",
          "Vananevas rahvastikus suureneb vanemate inimeste osakaal.",
          ["aging population"],
          ["rahvastiku vananemine"],
        ],
        [
          "Population_decline",
          "A downward line on a chart shows that the total number of residents is falling over time. Name this change.",
          "Allapoole liikuv joon graafikul näitab, et elanike koguarv aja jooksul langeb. Nimeta see muutus.",
          "population decline",
          "rahvaarvu vähenemine",
          "Population decline means that the total number of residents falls over time.",
          "Rahvaarvu vähenemine tähendab, et elanike koguarv aja jooksul langeb.",
          ["demographic decline"],
          ["rahvastiku kahanemine"],
        ],
        [
          "Return_migration",
          "People move back to Estonia or another country of origin after living abroad. Name this movement.",
          "Inimesed kolivad pärast välismaal elamist tagasi Eestisse või muusse päritoluriiki. Nimeta see liikumine.",
          "return migration",
          "tagasiränne",
          "Return migration is the movement of people back to their country of origin after they have lived abroad.",
          "Tagasiränne on inimeste liikumine tagasi päritoluriiki pärast välismaal elamist.",
          [],
          [],
        ],
        [
          "Human_capital_flight",
          "Headlines use this term when many highly trained doctors, engineers, or other specialists leave to work abroad. Name it.",
          "Uudiste pealkirjades kasutatakse seda väljendit, kui paljud väljaõppinud arstid, insenerid või teised spetsialistid lahkuvad välismaale tööle. Nimeta see.",
          "brain drain",
          "ajude äravool",
          "Brain drain is the departure of highly trained or qualified people to work or settle elsewhere.",
          "Ajude äravool on kõrgelt koolitatud või kvalifitseeritud inimeste lahkumine mujale tööle või elama.",
          ["human capital flight"],
          ["oskustööjõu väljaränne"],
        ],
      ],
    ],
  ];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLocaleLowerCase("en")
    .replace(/%[0-9a-f]{2}/giu, "-")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function sourceKey(seed: SourceSeed): string {
  return typeof seed === "string" ? slug(seed) : seed.key;
}

function source(seed: SourceSeed, subjectKey: string): EasyExpansionSource {
  if (typeof seed === "string") {
    return {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(seed).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${seed}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    };
  }
  return {
    sourceId: seed.sourceId,
    title: seed.title,
    url: seed.url,
    license: seed.license,
    retrievedAt: RETRIEVED_AT,
  };
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    sourceSeed,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const identity = sourceKey(sourceSeed);
  const subjectKey = `politics-economics-society:${identity}`;
  return {
    clueId: `built-in-politics-economics-society-easy-expansion-${clueNumber}`,
    key: `politics-economics-society-easy-expansion:${categorySetId}:${tier}`,
    factKey: `politics-economics-society-easy-expansion:${identity}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: source(sourceSeed, subjectKey),
  };
}

export const POLITICS_ECONOMICS_SOCIETY_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  POLITICS_ECONOMICS_SOCIETY_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
