import type {
  EasyExpansionCategory,
  EasyExpansionQuestion,
  EasyExpansionSource,
} from "../types";

const BATCH_ID = "12-mythology-religion-philosophy";
const PACK_ID = "built-in-mythology-religion-philosophy";
const RETRIEVED_AT = "2026-09-08";

type DirectSourceSeed = Readonly<{
  key: string;
  sourceId: string;
  title: string;
  url: string;
  license: string;
}>;

type SourceSeed = string | DirectSourceSeed;

type QuestionSeed = readonly [
  source: SourceSeed,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  explanationEn: string,
  explanationEt: string,
  variantsEn?: readonly string[],
  variantsEt?: readonly string[],
];

type CategorySeed = readonly [
  suffix: number,
  round: EasyExpansionCategory["round"],
  macroTopic: string,
  nameEn: string,
  nameEt: string,
  questions: readonly QuestionSeed[],
];

const MYTHOLOGY_RELIGION_PHILOSOPHY_EASY_EXPANSION_SEEDS: readonly CategorySeed[] =
  [
    [
      101,
      "round-one",
      "greek-roman",
      "Roman Gods Through Familiar Associations",
      "Rooma jumalad tuntud seoste järgi",
      [
        [
          "Dionysus",
          "At a Roman feast, which god would be recognised by a wine cup and a grapevine?",
          "Millise jumala tunneks Rooma pidusöögil ära veinikarika ja viinapuu järgi?",
          "Bacchus",
          "Bacchus",
          "This Roman god is associated with wine, grapevines, celebration, and theatre.",
          "Seda Rooma jumalat seostatakse veini, viinapuude, pidustuste ja teatriga.",
          ["Roman Dionysus"],
          ["Rooma Dionysos"],
        ],
        [
          "Minerva_McGonagall",
          "Which Roman wisdom goddess shares her first name with Professor McGonagall and corresponds to Greek Athena?",
          "Milline Rooma tarkusejumalanna jagab eesnime professor McGonagalliga ja vastab Kreeka Athenale?",
          "Minerva",
          "Minerva",
          "Professor McGonagall shares her first name with this Roman goddess, known as Athena in Greek mythology.",
          "Professor McGonagall jagab eesnime selle Rooma jumalannaga, keda Kreeka mütoloogias tuntakse Athena nime all.",
          [],
          [],
        ],
        [
          "Vulcan_(mythology)",
          "Think of the similar-looking word 'volcano': which Roman fire-and-forge god is pictured with a blacksmith's hammer?",
          "Mõtle sarnase kirjapildiga sõnale „vulkaan”: millist Rooma tule- ja sepajumalat kujutatakse sepahaamriga?",
          "Vulcan",
          "Vulcanus",
          "This Roman god rules fire and the forge and is traditionally shown with a smith's tools.",
          "See Rooma jumal valitseb tule ja sepikoja üle ning teda kujutatakse traditsiooniliselt sepatööriistadega.",
          ["Vulcanus", "Volcanus"],
          ["Vulcan", "Volcanus"],
        ],
        [
          "Ceres_(mythology)",
          "Which Roman goddess of agriculture and grain gave us the word-family link remembered through 'cereal'?",
          "Millist Rooma põllundus- ja viljajumalannat aitab meenutada sõna „cereal” ehk hommikuhelbed?",
          "Ceres",
          "Ceres",
          "Her name is the root of the English word for grain-based breakfast food.",
          "Tema nimest pärineb ingliskeelne sõna teraviljast hommikusöögi kohta.",
          [],
          [],
        ],
        [
          "Vesta_(mythology)",
          "Which Roman goddess of home and hearth was served by priestesses who guarded a sacred state fire?",
          "Millist Rooma kodu- ja koldejumalannat teenisid riigi püha tuld valvanud preestrinnad?",
          "Vesta",
          "Vesta",
          "Her priestesses kept the sacred state hearth burning in Rome.",
          "Tema preestrinnad hoidsid Roomas riigi püha koldetuld põlemas.",
          ["Roman goddess of the hearth", "Roman hearth goddess"],
          ["Rooma koldejumalanna", "Rooma kodukoldejumalanna"],
        ],
      ],
    ],
    [
      102,
      "round-one",
      "norse",
      "Norse Myth Through Familiar Symbols",
      "Põhjala müüdid tuntud sümbolite järgi",
      [
        [
          "Asgard",
          "Name the fortified realm where the best-known Norse gods live.",
          "Nimeta kindlustatud maailm, kus elavad tuntumad Põhjala jumalad.",
          "Asgard",
          "Asgard",
          "The best-known Norse gods, the Æsir, live in this fortified realm.",
          "Selles kindlustatud maailmas elavad tuntuimad Põhjala jumalad ehk aasid.",
          ["Ásgarðr"],
          ["Ásgarðr"],
        ],
        [
          "Yggdrasil",
          "What enormous tree connects the nine worlds in Norse myth?",
          "Milline hiiglaslik puu ühendab Põhjala mütoloogias üheksat maailma?",
          "Yggdrasil",
          "Yggdrasil",
          "The immense sacred tree stands at the centre of the Norse cosmos and connects its worlds.",
          "Hiiglaslik püha puu seisab Põhjala maailmapildi keskmes ja ühendab selle maailmu.",
          ["world tree"],
          ["maailmapuu"],
        ],
        [
          "Bifr%C3%B6st",
          "Name the burning rainbow route that links the human realm with the realm of the Norse gods.",
          "Nimeta põlev vikerkaaretee, mis ühendab inimeste maailma Põhjala jumalate maailmaga.",
          "Bifröst",
          "Bifröst",
          "This bridge is described as a burning rainbow between the human and divine realms.",
          "Seda silda kirjeldatakse põleva vikerkaarena inimeste ja jumalate maailma vahel.",
          ["Bifrost", "rainbow bridge"],
          ["Bifrost", "vikerkaaresild"],
        ],
        [
          "Huginn_and_Muninn",
          "Odin sends a pair of which black birds around the world to bring him news?",
          "Millised kaks musta lindu saadab Odin üle maailma endale uudiseid tooma?",
          "Odin's ravens",
          "Odini rongad",
          "The pair bring reports from across the world to the one-eyed chief god.",
          "Linnupaar toob ühesilmsele peajumalale teateid kogu maailmast.",
          ["ravens of Odin", "Huginn and Muninn", "Hugin and Munin", "ravens"],
          ["Odini kaarnad", "Huginn ja Muninn", "Hugin ja Munin", "rongad"],
        ],
        [
          "Heimdall",
          "Which Norse guardian is played by Idris Elba in Marvel films?",
          "Millist Põhjala valvurit kehastab Marveli filmides Idris Elba?",
          "Heimdall",
          "Heimdall",
          "The Norse guardian appears in Marvel's films, where Idris Elba portrays him.",
          "Põhjala valvur esineb Marveli filmides, kus teda kehastab Idris Elba.",
          ["Heimdallr"],
          ["Heimdallr"],
        ],
      ],
    ],
    [
      103,
      "round-one",
      "american",
      "Stories and Legends of the Americas",
      "Ameerika lood ja legendid",
      [
        [
          "Bigfoot",
          "Which legendary North American forest creature is described as huge, hairy, and humanlike, with oversized footprints?",
          "Millist Põhja-Ameerika legendiolendit kirjeldatakse hiiglasliku, karvase ja inimesesarnasena ning suurte jalajälgedega?",
          "Bigfoot",
          "Bigfoot",
          "Reports describe a large hairy humanlike figure associated with forests and oversized tracks.",
          "Lugudes kirjeldatakse suurt karvast inimesesarnast kuju, keda seostatakse metsade ja hiiglaslike jälgedega.",
          ["Sasquatch"],
          ["Sasquatch"],
        ],
        [
          "Chupacabra",
          "Which creature from Puerto Rican and wider Latin American folklore is blamed for attacking livestock and draining their blood?",
          "Millist Puerto Rico ja muu Ladina-Ameerika folklooriolendit süüdistatakse kariloomade ründamises ja nende vere imemises?",
          "chupacabra",
          "chupacabra",
          "The legendary creature is said to attack livestock, especially goats, and drink their blood.",
          "Legendi järgi ründab olend kariloomi, eriti kitsi, ja joob nende verd.",
          ["goat-sucker"],
          ["kitseimeja"],
        ],
        [
          "La_Llorona",
          "Which ghostly mother in Latin American folklore has a Spanish title that refers to her crying and wanders near water mourning her lost children?",
          "Milline Ladina-Ameerika folkloori kummituslik ema kannab nutmisele viitavat hispaaniakeelset nime ning uitab vee ääres kaotatud lapsi leinates?",
          "La Llorona",
          "La Llorona",
          "The legend tells of a ghostly woman whose cries are heard as she searches for or mourns her children.",
          "Legend räägib kummituslikust naisest, kelle nuttu kuuldakse, kui ta oma lapsi otsib või leinab.",
          ["the Weeping Woman"],
          ["nuttev naine"],
        ],
        [
          "Pocahontas",
          "Which historical Powhatan woman gave her name to a famous 1995 Disney animated film?",
          "Milline ajalooline powhatani naine andis oma nime kuulsale 1995. aasta Disney animafilmile?",
          "Pocahontas",
          "Pocahontas",
          "She was a Powhatan woman whose life inspired many later, often heavily fictionalised, stories and screen versions.",
          "Ta oli powhatani naine, kelle elu inspireeris paljusid hilisemaid ja sageli tugevalt väljamõeldud lugusid ning ekraniseeringuid.",
          ["Matoaka"],
          ["Matoaka"],
        ],
        [
          "Thunderbird_(mythology)",
          "In some Indigenous North American traditions, this great bird makes the sky rumble with its wingbeats and sends flashes from its eyes. Name it.",
          "Mõnes Põhja-Ameerika põlisrahva pärimuses paneb see hiidlind tiivalöökidega taeva mürisema ja tema silmist sähvivad välgud. Nimeta lind.",
          "Thunderbird",
          "kõuelind",
          "In these traditions, the bird's wingbeats make the sky rumble and flashes come from its eyes.",
          "Nendes pärimustes panevad linnu tiivalöögid taeva mürisema ja tema silmist sähvivad välgud.",
          ["Thunder Bird"],
          ["Thunderbird"],
        ],
      ],
    ],
    [
      104,
      "round-one",
      "american",
      "Folklore Creatures from Around the World",
      "Folklooriolendid kogu maailmast",
      [
        [
          "Loch_Ness_Monster",
          "Name the reported animal with an elongated neck said to inhabit a body of water in the Scottish Highlands.",
          "Nimeta Šoti mägismaa veekogus elavat väidetavat pika kaelaga looma.",
          "Loch Ness Monster",
          "Loch Nessi koletis",
          "Reports describe an animal with an elongated neck in a Scottish Highland body of water.",
          "Teadetes kirjeldatakse Šoti mägismaa veekogus elavat pika kaelaga looma.",
          ["Nessie"],
          ["Nessie"],
        ],
        [
          "Yeti",
          "Name the large shaggy humanlike figure said to inhabit Asia's high mountains and linked to oversized footprints.",
          "Nimeta Aasia kõrgmäestikus elavat väidetavat suurt karvast inimesesarnast kuju, keda seostatakse hiiglaslike jalajälgedega.",
          "yeti",
          "jeti",
          "The reported shaggy humanlike figure is associated with high mountains and oversized footprints.",
          "Seda väidetavat karvast inimesesarnast kuju seostatakse kõrgmäestiku ja hiiglaslike jalajälgedega.",
          ["Abominable Snowman"],
          ["jäle lumemees"],
        ],
        [
          "Leprechaun",
          "Which small Irish fairy is popularly shown in green and guarding a pot of gold?",
          "Millist väikest Iiri haldjat kujutatakse sageli rohelises rõivas kullapada valvamas?",
          "leprechaun",
          "iiri härjapõlvlane",
          "Popular culture presents this solitary Irish fairy as a small green-clad guardian of hidden gold.",
          "Populaarkultuur kujutab seda üksildast Iiri haldjat väikese rohelises rõivas peidetud kulla valvurina.",
          ["Irish leprechaun"],
          ["leprechaun"],
        ],
        [
          "Golem",
          "In Jewish folklore, what human-shaped figure can be formed from clay and brought to life?",
          "Millise inimesekujulise olendi võib juudi folklooris savist vormida ja ellu äratada?",
          "golem",
          "golem",
          "The folklore figure is an artificial humanlike being, traditionally made from clay and animated.",
          "See folklooriolend on kunstlik inimesesarnane olevus, mis valmistatakse tavaliselt savist ja äratatakse ellu.",
          ["clay golem"],
          ["savist golem"],
        ],
        [
          "Poltergeist",
          "What type of haunting is blamed when unseen forces make loud noises and throw or move objects?",
          "Millist liiki kummitust süüdistatakse selles, kui nähtamatud jõud teevad valju müra ning loobivad või liigutavad esemeid?",
          "poltergeist",
          "poltergeist",
          "This supposed haunting is associated with unexplained noises and moving objects.",
          "Seda väidetavat kummitust seostatakse seletamatu müra ja liikuvate esemetega.",
          ["noisy ghost"],
          ["lärmakas kummitus"],
        ],
      ],
    ],
    [
      105,
      "round-one",
      "american",
      "Signs and Objects of Good Luck",
      "Õnnemärgid ja -esemed",
      [
        [
          "Meteor",
          "What familiar name is given to a brief glowing streak made by a meteor crossing the night sky?",
          "Millise tuttava nimega kutsutakse üle öötaeva liikuvat lühikest helendavat meteoorijälge?",
          "shooting star",
          "langev täht",
          "The familiar streak is a meteor glowing as it passes through the atmosphere.",
          "Tuttav valgusjälg on atmosfääris helendav meteoor.",
          ["falling star"],
          ["lendtäht"],
        ],
        [
          "Nazar_(amulet)",
          "Name the eye-shaped bead worn or displayed as protection from a harmful gaze.",
          "Nimeta silmakujuline helmes, mida kantakse või hoitakse kaitseks kurja pilgu eest.",
          "nazar amulet",
          "kurja silma amulett",
          "The eye-shaped bead is intended to protect against a harmful gaze.",
          "Silmakujuline helmes on mõeldud kaitsma kurja pilgu eest.",
          ["nazar", "eye bead", "evil-eye amulet"],
          ["nazar", "nazari amulett", "silmaamulett"],
        ],
        [
          "Dreamcatcher",
          "Name the hoop woven with a web-like net and hung near a sleeping place to filter dreams.",
          "Nimeta võrgutaolise mustriga punutud rõngas, mis riputatakse magamiskoha lähedale unenägusid filtreerima.",
          "dreamcatcher",
          "unenäopüüdja",
          "The handmade hoop comes from Indigenous North American traditions and is associated with protecting sleepers from bad dreams.",
          "Käsitööna valminud rõngas pärineb Põhja-Ameerika põlisrahvaste pärimusest ja seda seostatakse magaja kaitsmisega halbade unenägude eest.",
          ["dream catcher"],
          ["unepüüdja"],
        ],
        [
          "Dracaena_sanderiana",
          "Which houseplant with bundled green stems is sold under a name promising good fortune, although it is not true bamboo?",
          "Millist kokku seotud roheliste vartega toataime müüakse head õnne tõotava nime all, kuigi see pole päris bambus?",
          "lucky bamboo",
          "õnnebambus",
          "This popular houseplant is a dracaena marketed as a symbol of good fortune.",
          "See populaarne toataim on draakonipuu, mida turustatakse hea õnne sümbolina.",
          ["Dracaena sanderiana"],
          ["Sanderi draakonipuu"],
        ],
        [
          "Horseshoe",
          "Which U-shaped object once fitted to a horse's hoof is often hung above a doorway as a sign of good luck?",
          "Milline hobuse kabja alla kinnitatav U-kujuline ese riputatakse sageli ukse kohale õnne märgiks?",
          "lucky horseshoe",
          "õnnehobuseraud",
          "This familiar iron object has long been used as a protective and lucky symbol.",
          "Seda tuttavat raudeset on ammu kasutatud kaitsva õnnesümbolina.",
          ["good-luck horseshoe"],
          ["õnne toov hobuseraud"],
        ],
      ],
    ],
    [
      106,
      "round-one",
      "world-religions",
      "Furnishings in a Church",
      "Kiriku sisustus",
      [
        [
          "Pew",
          "What is one of the long benches where a congregation sits during a church service?",
          "Kuidas nimetatakse üht pikkadest pinkidest, millel kogudus jumalateenistuse ajal istub?",
          "pew",
          "kirikupink",
          "These long benches provide seating for the congregation in a church.",
          "Need pikad pingid annavad kirikus kogudusele istekoha.",
          ["church bench"],
          ["kogudusepink"],
        ],
        [
          "Hymnal",
          "Which bound collection lets a congregation follow and sing the songs used in worship?",
          "Millisest köidetud kogumikust saab kogudus jumalateenistuse laule jälgida ja kaasa laulda?",
          "hymnbook",
          "lauluraamat",
          "The book collects hymns for communal worship and singing.",
          "Raamat koondab kogukondlikul jumalateenistusel lauldavaid kirikulaule.",
          ["hymnal"],
          ["koraaliraamat"],
        ],
        [
          "Pulpit",
          "What raised platform does a preacher commonly use to deliver a sermon in a church?",
          "Millist kõrgendatud kohta kasutab vaimulik kirikus tavaliselt jutluse pidamiseks?",
          "pulpit",
          "kantsel",
          "The raised furnishing makes the preacher visible and audible while delivering a sermon.",
          "Kõrgendatud kirikusisustus teeb jutlust pidava vaimuliku nähtavaks ja kuuldavaks.",
          ["preaching platform"],
          ["jutlusepult"],
        ],
        [
          "Kneeler",
          "Name the low padded bench that supports a worshipper's knees during prayers.",
          "Nimeta madal polsterdatud pink, millele palvetamisel põlved toetatakse.",
          "kneeler",
          "põlvituspink",
          "The low bench supports the knees during prayers.",
          "Madal pink toetab palvetamise ajal põlvi.",
          ["prayer bench"],
          ["palvepink"],
        ],
        [
          "Baptismal_font",
          "What stone or metal vessel in a church holds the water used during christening?",
          "Milline kivist või metallist anum hoiab kirikus vett, mida kasutatakse ristimisel?",
          "baptismal font",
          "ristimisnõu",
          "The church vessel contains water for the Christian rite of baptism.",
          "See kirikuanum sisaldab kristliku ristimistalituse vett.",
          ["font", "baptismal basin"],
          ["ristimisvaagen", "ristimisallikas"],
        ],
      ],
    ],
    [
      107,
      "round-one",
      "greek-roman",
      "Groups in Greek Myth",
      "Rühmad Kreeka mütoloogias",
      [
        [
          "Muses",
          "Which nine Greek goddesses were believed to inspire poetry, music, history, and the other arts?",
          "Millised üheksa Kreeka jumalannat pidid innustama luulet, muusikat, ajalugu ja teisi kunste?",
          "the Muses",
          "muusad",
          "This group of nine goddesses personified inspiration for the arts and learning.",
          "See üheksast jumalannast koosnev rühm kehastas kunstide ja teadmiste inspiratsiooni.",
          ["nine Muses"],
          ["üheksa muusat"],
        ],
        [
          "Nymph",
          "What female nature spirits in Greek myth inhabit places such as springs, trees, and mountains?",
          "Millised naissoost loodusvaimud elavad Kreeka mütoloogias allikates, puudes ja mägedes?",
          "nymphs",
          "nümfid",
          "These female spirits personify natural places and features.",
          "Need naissoost vaimud kehastavad looduspaiku ja -nähtusi.",
          ["nature nymphs"],
          ["loodusnümfid"],
        ],
        [
          "Satyr",
          "Which wild woodland spirits in Greek myth are commonly shown with a man's upper body and goat-like features?",
          "Milliseid Kreeka mütoloogia metsikuid loodusvaime kujutatakse tavaliselt inimese ülakeha ja kitsetunnustega?",
          "satyrs",
          "saatürid",
          "These lively male nature spirits are associated with forests, music, dancing, and animal features.",
          "Neid elavaid meessoost loodusvaime seostatakse metsade, muusika, tantsu ja loomsete tunnustega.",
          ["satyr"],
          ["saatür"],
        ],
        [
          "Amazons",
          "What nation of women warriors appears in Greek legends and battles heroes such as Heracles?",
          "Milline sõdalasnaiste rahvas esineb Kreeka legendides ja võitleb selliste kangelastega nagu Herakles?",
          "the Amazons",
          "amatsoonid",
          "Greek stories describe this legendary people as a society of women warriors.",
          "Kreeka lood kirjeldavad seda legendaarset rahvast sõdalasnaiste ühiskonnana.",
          ["Amazon warriors"],
          ["amatsoonsõdalased"],
        ],
        [
          "Erinyes",
          "Which avenging goddesses have a familiar English name that sounds like 'fury' and punish grave family crimes?",
          "Milliste kättemaksujumalannade rahvusvaheline nimi meenutab inglise sõna fury ehk „raev”?",
          "the Furies",
          "fuuriad",
          "Greek tradition calls these avenging goddesses the Erinyes; English commonly calls them the Furies.",
          "Kreeka pärimuses tuntakse neid kättemaksujumalannasid erinnüstena; rahvusvaheliselt tuntakse neid ka fuuriatena.",
          ["Erinyes", "Eumenides"],
          ["erinnüsed", "eumeniidid"],
        ],
      ],
    ],
    [
      108,
      "round-one",
      "egyptian",
      "Bible Stories in One Scene",
      "Piiblilood ühe stseeni järgi",
      [
        [
          "Adam_and_Eve",
          "Name the first human couple in Eden.",
          "Nimeta Eedeni esimene inimpaar.",
          "Adam and Eve",
          "Aadam ja Eeva",
          "The story places the first human couple in Eden.",
          "Loo järgi paigutati esimene inimpaar Eedenisse.",
          ["Eve and Adam"],
          ["Eeva ja Aadam"],
        ],
        [
          "Feeding_the_multitude",
          "Which Bible miracle feeds a huge crowd from just five loaves and two fish?",
          "Millises piibliimes toidetakse tohutu rahvahulk vaid viie leiva ja kahe kalaga?",
          "feeding of the five thousand",
          "viie tuhande toitmine",
          "The Gospel scene describes a small amount of food becoming enough for thousands of people.",
          "Evangeeliumilugu kirjeldab, kuidas vähesest toidust piisab tuhandetele inimestele.",
          ["feeding the five thousand", "miracle of the loaves and fishes"],
          ["viie tuhande inimese toitmine", "leibade ja kalade ime"],
        ],
        [
          "Judgement_of_Solomon",
          "Which Bible story has two women claim one baby until a king proposes dividing the child to reveal the true mother?",
          "Millises piibliloos väidavad kaks naist kumbki, et sama laps on tema oma, kuni kuningas pakub tõelise ema leidmiseks lapse jagamist?",
          "Judgement of Solomon",
          "Saalomoni kohtuotsus",
          "The real mother gives up her claim to save the child, revealing the king's wisdom.",
          "Tõeline ema loobub lapse päästmiseks oma nõudest ning paljastab nii kuninga tarkuse.",
          ["Judgment of Solomon", "Solomon's judgement"],
          ["Saalomoni otsus", "kuningas Saalomoni kohtuotsus"],
        ],
        [
          "Daniel_in_the_lions%27_den",
          "Which Bible story puts a faithful man among lions overnight, where he survives unharmed?",
          "Millises piibliloos satub usklik mees ööseks lõvide sekka ja jääb vigastamata ellu?",
          "Daniel in the lions' den",
          "Taaniel lõvide augus",
          "The condemned man survives because the animals do not harm him.",
          "Hukkamõistetud mees jääb ellu, sest loomad ei tee talle viga.",
          ["Daniel in the lion's den"],
          ["Taaniel lõviaugus"],
        ],
        [
          "Parting_of_the_Red_Sea",
          "Name the biblical miracle in which waters divide so Moses can lead escaping people through on dry ground.",
          "Nimeta piibellik ime, kus veed lahknevad ja Mooses juhib põgeneva rahva kuiva maad mööda läbi.",
          "parting of the Red Sea",
          "Punase mere lahknemine",
          "The escape story describes the sea opening and a path appearing between the waters.",
          "Põgenemisloos avaneb meri ja vete vahele ilmub läbipääs.",
          ["Moses parts the Red Sea"],
          ["Mooses lahutab Punase mere"],
        ],
      ],
    ],
    [
      109,
      "round-one",
      "world-religions",
      "The Christian Calendar",
      "Kristlik kalender",
      [
        [
          "Advent",
          "In most Western churches, what four-Sunday season of waiting and candle-lighting leads up to Christmas?",
          "Milline nelja pühapäevaga ootuse ja küünalde süütamise aeg eelneb enamikus läänekirikutes jõuludele?",
          "Advent",
          "advent",
          "In most Western calendars, this Christian season prepares for Christmas across the four preceding Sundays.",
          "Enamikus lääne kalendrites valmistab see kristlik aeg nelja eelneva pühapäeva jooksul jõuludeks.",
          ["Advent season"],
          ["advendiaeg"],
        ],
        [
          "All_Saints%27_Day",
          "In the Roman Catholic calendar, name the feast honouring all saints.",
          "Nimeta roomakatoliku kalendri püha, millega austatakse kõiki pühakuid.",
          "All Saints' Day",
          "kõigi pühakute päev",
          "This observance honours the entire company of saints in that calendar.",
          "Selles kalendris austatakse selle pühaga kõiki pühakuid.",
          ["All Hallows' Day"],
          ["pühakutepäev"],
        ],
        [
          "Palm_Sunday",
          "Which Christian Sunday recalls Jesus entering Jerusalem while crowds welcomed him with branches?",
          "Milline kristlik pühapäev meenutab Jeesuse saabumist Jeruusalemma, kui rahvahulk tervitas teda okstega?",
          "Palm Sunday",
          "palmipuudepüha",
          "The feast remembers the entry into Jerusalem and the crowd's greeting with palm branches.",
          "Püha meenutab Jeruusalemma sisenemist ja rahvahulga tervitust palmiokstega.",
          ["Passion Sunday"],
          ["palmipühapäev"],
        ],
        [
          "Feast_of_the_Ascension",
          "Name the Christian feast commemorating the risen saviour's ascent into heaven.",
          "Nimeta kristlik püha, millega meenutatakse ülestõusnud päästja taevasse tõusmist.",
          "Ascension Day",
          "taevaminemispüha",
          "The feast commemorates the risen saviour's ascent into heaven.",
          "Püha meenutab ülestõusnud päästja taevasse tõusmist.",
          ["Feast of the Ascension"],
          ["Kristuse taevaminemispüha"],
        ],
        [
          "Pentecost",
          "On the fiftieth day of the Easter season, which Christian feast recalls the Holy Spirit appearing over the disciples as tongues of fire?",
          "Milline lihavõtteaja viiekümnendal päeval peetav kristlik püha meenutab Püha Vaimu ilmumist tulekeeltena jüngrite kohal?",
          "Pentecost",
          "nelipüha",
          "The feast falls on the fiftieth day of the Easter season; Acts describes tongues like fire and speech in other tongues, whose exact nature is interpreted differently.",
          "Püha peetakse lihavõtteaja viiekümnendal päeval; Apostlite teod kirjeldavad tulekeeli ja teistes keeltes kõnelemist, mille täpset olemust tõlgendatakse erinevalt.",
          [
            "Whitsun",
            "Whitsunday",
            "Whit Sunday",
            "Pentecost Sunday",
            "Feast of the Holy Spirit",
          ],
          [
            "suvistepüha",
            "suvistepühad",
            "suvisted",
            "nelipühad",
            "Püha Vaimu püha",
          ],
        ],
      ],
    ],
    [
      110,
      "round-one",
      "world-religions",
      "Objects Used in Worship",
      "Jumalateenistustel kasutatavad esemed",
      [
        [
          "Holy_water",
          "What liquid has been blessed for uses such as making the sign of the cross or sprinkling a congregation?",
          "Milline vedelik on õnnistatud näiteks ristimärgi tegemiseks või koguduse piserdamiseks?",
          "holy water",
          "pühitsetud vesi",
          "Religious traditions bless this water for ritual protection, purification, or blessing.",
          "Usutraditsioonides õnnistatakse seda vett rituaalseks kaitseks, puhastamiseks või õnnistamiseks.",
          ["blessed water"],
          ["õnnistatud vesi"],
        ],
        [
          "Rosary",
          "What loop of beads helps Catholics count repeated prayers?",
          "Milline helmestest palvevahend aitab katoliiklastel korduvaid palveid loendada?",
          "rosary",
          "roosipärg",
          "The beads guide a sequence of repeated Catholic prayers and meditations.",
          "Helmed juhivad katoliiklikku korduvate palvete ja mõtiskluste jada.",
          ["rosary beads", "prayer beads"],
          ["palvehelmed", "roosikrants"],
        ],
        [
          "Prayer_rug",
          "What small mat provides a clean place for a Muslim worshipper to kneel and bow?",
          "Milline väike vaip annab moslemile puhta koha põlvitamiseks ja kummardamiseks?",
          "prayer rug",
          "palvevaip",
          "The mat marks a clean surface for the movements of Islamic worship.",
          "Vaip tähistab puhta pinna islami palvuse liigutuste jaoks.",
          ["prayer mat"],
          ["palvematt"],
        ],
        [
          "Prayer_wheel",
          "What Buddhist cylinder bearing a mantra is turned by hand as a devotional act?",
          "Millist mantraga budistlikku silindrit pööratakse käega usulise toiminguna?",
          "prayer wheel",
          "palveratas",
          "Turning the mantra-bearing cylinder is a devotional practice in Tibetan Buddhism.",
          "Mantraga silindri pööramine on Tiibeti budismi usuline tava.",
          ["Mani wheel"],
          ["maniratas"],
        ],
        [
          "Mezuzah",
          "Name the small sacred parchment kept in a case on a Jewish doorpost.",
          "Nimeta väike püha pärgamendirull, mida hoitakse juudi kodu uksepiidale kinnitatud ümbrises.",
          "mezuzah",
          "mezuza",
          "The case contains a parchment bearing sacred text.",
          "Ümbris sisaldab püha tekstiga pärgamendirulli.",
          ["Jewish doorpost scroll", "doorpost parchment"],
          ["juudi uksepiida pärgamendirull", "uksepiida pärgamendirull"],
        ],
      ],
    ],
    [
      111,
      "round-two",
      "world-religions",
      "Festivals Around the World",
      "Pühad kogu maailmas",
      [
        [
          "Saint_Patrick%27s_Day",
          "Which Irish-linked celebration fills streets with green clothes and shamrocks on 17 March?",
          "Milline Iirimaaga seotud püha täidab 17. märtsil tänavad roheliste riiete ja ristikulehtedega?",
          "St Patrick's Day",
          "püha Patricku päev",
          "The annual celebration honours Ireland's patron saint and is widely marked with green and shamrocks.",
          "Iga-aastane pidupäev austab Iirimaa kaitsepühakut ning seda tähistatakse laialdaselt rohelise värvi ja ristikulehtedega.",
          ["Saint Patrick's Day"],
          ["Patrickupäev"],
        ],
        [
          "Passover",
          "Which Jewish festival retells the Exodus from slavery in Egypt?",
          "Milline juudi püha meenutab Egiptuse orjusest lahkumist?",
          "Passover",
          "paasapüha",
          "The festival commemorates the Israelites' departure from slavery in Egypt.",
          "Püha meenutab iisraellaste lahkumist Egiptuse orjusest.",
          ["Pesach", "Pesah"],
          ["pesah", "juudi paasapüha"],
        ],
        [
          "Mardi_Gras",
          "Which colourful carnival climax immediately before Lent is especially famous in New Orleans?",
          "Milline värvikas paastueelne karneval on eriti kuulus New Orleansis?",
          "Mardi Gras",
          "Mardi Gras",
          "The celebration reaches its climax on the final day before the Christian fasting season begins.",
          "Pidustus jõuab haripunkti viimasel päeval enne kristliku paastuaja algust.",
          ["Fat Tuesday", "Shrove Tuesday carnival"],
          ["rasvane teisipäev", "vastlakarneval"],
        ],
        [
          "Eid_al-Adha",
          "Name the major Islamic festival marked by animal sacrifice and distribution of meat.",
          "Nimeta suur islami püha, mille tähistamise juurde kuuluvad looma ohverdamine ja liha jagamine.",
          "Eid al-Adha",
          "Eid al-Adha",
          "Its celebration includes sacrificing an animal and sharing the meat.",
          "Selle tähistamise juurde kuuluvad looma ohverdamine ja liha jagamine.",
          ["Feast of Sacrifice", "Eid ul-Adha"],
          ["ohvripüha", "Eid ul-Adha"],
        ],
        [
          "Chinese_New_Year",
          "Which new-year celebration is famous for red envelopes and colourful dragon or lion dances?",
          "Milline uusaastapidu on tuntud punaste ümbrike ning värvikate draakoni- või lõvitantsude poolest?",
          "Chinese New Year",
          "Hiina uusaasta",
          "The festival begins a new year in the traditional Chinese calendar and is celebrated with many red decorations.",
          "Püha alustab Hiina traditsioonilise kalendri uut aastat ning seda tähistatakse rohkete punaste kaunistustega.",
          ["Chinese Lunar New Year"],
          ["Hiina kuu-uusaasta"],
        ],
      ],
    ],
    [
      112,
      "round-two",
      "world-religions",
      "Faith at the Table",
      "Usk söögilauas",
      [
        [
          "Halal",
          "Which Arabic word on a menu says that food is permitted under Islamic rules?",
          "Milline araabiakeelne sõna menüüs näitab, et toit on islami reeglite järgi lubatud?",
          "halal",
          "halal",
          "The term means permitted and is commonly used for food that meets Islamic requirements.",
          "Sõna tähendab lubatut ja seda kasutatakse tavaliselt islami nõuetele vastava toidu kohta.",
          ["halaal", "permitted food"],
          ["halaal", "lubatud toit"],
        ],
        [
          "Sacramental_bread",
          "At services in many Western churches, worshippers receive this thin, round edible piece. Name it.",
          "Paljude läänekirikute jumalateenistusel saavad usklikud õhukese ümara söödava pala. Nimeta see.",
          "communion wafer",
          "armulaua oblaat",
          "Many Western traditions use a thin round edible piece in this rite.",
          "Paljudes lääne traditsioonides kasutatakse selles talituses õhukest ümarat söödavat tükki.",
          ["communion bread", "sacramental bread"],
          ["armulaualeib", "oblaat"],
        ],
        [
          "Iftar",
          "What evening meal begins after sunset and ends each daily Ramadan fast?",
          "Milline õhtune eine algab pärast päikeseloojangut ja lõpetab ramadaani iga paastupäeva?",
          "iftar",
          "iftar",
          "Muslims share this meal after sunset during the fasting month.",
          "Moslemid söövad seda einet paastukuu ajal pärast päikeseloojangut.",
          ["fast-breaking meal"],
          ["paastu lõpetav eine"],
        ],
        [
          "Matzah",
          "Name the flat bread eaten during the Jewish festival recalling the Exodus; its dough is not allowed to rise.",
          "Nimeta Egiptusest lahkumist meenutaval juudi pühal söödav lame leib, mille tainal ei lasta kerkida.",
          "matzo",
          "matsa",
          "Keeping its dough from rising produces this flat festival bread.",
          "Tainal ei lasta kerkida ning nii valmib lame pühadeleib.",
          [
            "matzah",
            "matza",
            "unleavened Passover bread",
            "Passover flatbread",
            "unleavened bread",
            "unleavened flatbread",
          ],
          [
            "matzah",
            "matzo",
            "paasapüha hapnemata leib",
            "hapnemata paasaleib",
            "hapnemata leib",
            "hapnemata küpsetis",
          ],
        ],
        [
          "Passover_Seder",
          "What is the name of the ordered Jewish ritual dinner with symbolic foods during the festival that remembers the Exodus?",
          "Kuidas nimetatakse kindla korraga juudi rituaalset söömaaega, kus Egiptusest lahkumist meenutaval pühal kasutatakse sümboolseid toite?",
          "seder",
          "seder",
          "The festival dinner follows a set order, retells the Exodus and uses symbolic foods.",
          "Pühade söömaaeg järgib kindlat korda, meenutab Egiptusest lahkumist ja kasutab sümboolseid toite.",
          ["Passover seder", "Passover ritual meal", "Passover meal"],
          [
            "paasapüha rituaalne söömaaeg",
            "paasasöömaaeg",
            "paasaõhtu söömaaeg",
          ],
        ],
      ],
    ],
    [
      113,
      "round-two",
      "world-religions",
      "Heavenly and Fallen Beings",
      "Taevased ja langenud olendid",
      [
        [
          "Satan",
          "Who is the chief supernatural adversary in familiar Christian tradition?",
          "Kes on tuttavas kristlikus pärimuses peamine üleloomulik vastane?",
          "Satan",
          "Saatan",
          "This figure is portrayed as the principal opponent of God and tempter of humanity.",
          "Seda kuju kujutatakse Jumala peamise vastase ja inimeste kiusajana.",
          ["the biblical Devil"],
          ["piibli kurat"],
        ],
        [
          "Guardian_angel",
          "What heavenly protector is traditionally believed to watch over one particular person?",
          "Millist taevast kaitsjat usutakse traditsiooniliselt valvavat üht kindlat inimest?",
          "guardian angel",
          "kaitseingel",
          "Tradition assigns this protective heavenly being to guide and guard an individual.",
          "Pärimuse järgi juhib ja valvab see kaitsev taevane olend üht inimest.",
          ["protecting angel"],
          ["kaitsevaim"],
        ],
        [
          "Fallen_angel",
          "What kind of heavenly being has rebelled and been cast out of heaven?",
          "Kuidas nimetatakse taevast olendit, kes on mässanud ja taevast välja heidetud?",
          "fallen angel",
          "langenud ingel",
          "The term describes an angel expelled from heaven after rebellion or disobedience.",
          "Nimetus kirjeldab inglit, kes saadeti mässu või sõnakuulmatuse järel taevast välja.",
          ["cast-out angel"],
          ["taevast välja heidetud ingel"],
        ],
        [
          "Cherub",
          "Which biblical heavenly being is usually winged in art and is often popularly pictured as a chubby child?",
          "Millist piibellikku taevast olendit kujutatakse kunstis tavaliselt tiivulisena ja rahvapäraselt sageli pontsaka lapsena?",
          "cherub",
          "keerub",
          "Western art often gives this biblical being wings and, in popular imagery, a childlike form.",
          "Lääne kunst annab sellele piibellikule olendile sageli tiivad ja populaarses kujutluses lapseliku kuju.",
          ["cherubim"],
          ["keerubid"],
        ],
        [
          "Azrael",
          "In Islamic tradition, Azrael takes the souls of the deceased away from the body. What familiar heavenly role or title does this describe?",
          "Islami pärimuses viib Azrael lahkunu hinge kehast ära. Millise tuttava taevase rolli või nimetusega on tegu?",
          "angel of death",
          "surmaingel",
          "Islamic tradition describes Azrael as the heavenly figure responsible for taking the souls of the deceased.",
          "Islami pärimus kirjeldab Azraeli taevase kujuna, kelle ülesanne on võtta lahkunute hinged.",
          ["death angel"],
          ["surma ingel"],
        ],
      ],
    ],
    [
      114,
      "round-two",
      "greek-roman",
      "Greek Myths and Beliefs",
      "Kreeka müüdid ja uskumused",
      [
        [
          "Styx",
          "Which river of the Greek underworld is crossed by the ferryman Charon?",
          "Millist Kreeka allilma jõge ületab paadimees Charon?",
          "River Styx",
          "Styx",
          "In Greek myth, this river forms a boundary between the worlds of the living and the dead.",
          "Kreeka mütoloogias moodustab see jõgi piiri elavate ja surnute maailma vahel.",
          ["Styx"],
          ["Styx jõgi"],
        ],
        [
          "Ambrosia",
          "In Greek myth, what divine sustenance paired with nectar was often associated with immortality?",
          "Millist nektariga sageli koos nimetatud jumalikku toitu või jooki seostati Kreeka mütoloogias surematusega?",
          "ambrosia",
          "ambroosia",
          "Greek sources treat it as divine food or drink, often paired with nectar and linked with longevity or immortality.",
          "Kreeka allikates on see jumalik toit või jook, mida seostatakse sageli nektari ning pikaealisuse või surematusega.",
          ["food of the gods"],
          ["jumalate toit"],
        ],
        [
          "Delphi",
          "At which ancient Greek sanctuary did Apollo's famous oracle answer visitors' questions?",
          "Millises Vana-Kreeka pühamus vastas Apolloni kuulus oraakel külastajate küsimustele?",
          "Delphi",
          "Delfi",
          "The sanctuary was regarded as a major religious centre and the seat of Apollo's Pythia.",
          "Pühamut peeti oluliseks usukeskuseks ja seal tegutses Apolloni püütia.",
          ["Delphi oracle"],
          ["Delfi oraakel"],
        ],
        [
          "Libation",
          "In ancient Greek worship, what was a drink poured onto the ground as a gift to a deity called?",
          "Kuidas nimetati vanakreeka usukombes jooki, mis valati maapinnale anniks jumalusele?",
          "libation",
          "jookohver",
          "The ritual gives a drink to a deity by pouring it out.",
          "Rituaalis antakse jumalusele vedelik seda välja valades.",
          ["drink offering", "liquid offering"],
          ["joogiohvri toomine", "libatsioon"],
        ],
        [
          "Andromeda_(mythology)",
          "Which daughter of Cassiopeia was chained up as prey for a sea monster, rescued, and later gave her name to a galaxy?",
          "Milline Kassiopeia tütar aheldati merekoletise saagiks, päästeti ning andis hiljem nime galaktikale?",
          "Andromeda",
          "Andromeeda",
          "The rescued princess became a figure in the night sky, and the nearby galaxy carries the same name.",
          "Päästetud printsessist sai tähistaeva kuju ning lähedal asuv galaktika kannab sama nime.",
          ["Princess Andromeda"],
          ["printsess Andromeeda"],
        ],
      ],
    ],
    [
      115,
      "round-two",
      "early-modern-philosophy",
      "Ideas and Thinkers",
      "Ideed ja mõtlejad",
      [
        [
          "Free_market",
          "In which economic model do buyers' and sellers' bids and offers shape prices rather than government-set prices?",
          "Millises majandusmudelis kujunevad hinnad ostjate ja müüjate pakkumiste kaudu, mitte riigi korraldusel?",
          "free market",
          "vabaturg",
          "In the model, supply and demand through voluntary exchange shape prices without state price-setting.",
          "Selles mudelis kujundavad hindu vabatahtliku vahetuse kaudu pakkumine ja nõudlus, mitte riiklik hinnamääramine.",
          ["free-market economy"],
          ["vaba turumajandus"],
        ],
        [
          "Renaissance_humanism",
          "Name the European educational movement that revived the study of Greco-Roman texts through the humanities.",
          "Nimeta Euroopa haridus- ja mõttevool, mis elavdas humanitaarainete kaudu Kreeka-Rooma tekstide uurimist.",
          "Renaissance humanism",
          "renessansihumanism",
          "The movement sought to revive classical literature, culture, and moral philosophy through the humanities.",
          "Mõttevool püüdis humanitaarainete kaudu elustada antiikkirjandust, -kultuuri ja moraalifilosoofiat.",
          ["humanism"],
          ["humanism"],
        ],
        [
          "Causality",
          "What familiar relationship links why something happens to the result that follows?",
          "Milline tuttav seos ühendab millegi juhtumise põhjuse sellele järgneva tulemusega?",
          "cause and effect",
          "põhjus ja tagajärg",
          "One event or condition brings about a later result.",
          "Üks sündmus või tingimus kutsub esile hilisema tulemuse.",
          ["causality", "cause-and-effect relationship"],
          ["põhjuslikkus", "põhjuse ja tagajärje seos"],
        ],
        [
          {
            key: "list-of-calvin-and-hobbes-characters-hobbes",
            sourceId:
              "source:mythology-religion-philosophy:list-of-calvin-and-hobbes-characters-hobbes",
            title: "List of Calvin and Hobbes characters — Wikipedia",
            url: "https://en.wikipedia.org/wiki/List_of_Calvin_and_Hobbes_characters#Hobbes",
            license: "CC-BY-SA-4.0",
          },
          "Calvin's stuffed tiger was named after which 17th-century philosopher?",
          "Millise 17. sajandi filosoofi järgi sai nime Calvini mängutiiger?",
          "Thomas Hobbes",
          "Thomas Hobbes",
          "The comic-strip character Hobbes was named after the 17th-century philosopher Thomas Hobbes.",
          "Koomiksitegelane Hobbes sai nime 17. sajandi filosoofi Thomas Hobbesi järgi.",
          ["philosopher Hobbes"],
          ["filosoof Hobbes"],
        ],
        [
          "Francis_Bacon",
          "Which English thinker and statesman—sharing a surname with a breakfast food—championed learning from repeated observations and moving from examples to general conclusions?",
          "Milline inglise mõtleja ja riigimees, kelle perekonnanimi tähendab inglise keeles peekonit, rõhutas korduvatest vaatlustest õppimist ja üksikjuhtumitest üldiste järelduste tegemist?",
          "Francis Bacon",
          "Francis Bacon",
          "He promoted a method that builds broader conclusions from systematic observation and evidence.",
          "Ta propageeris meetodit, mis ehitab süstemaatiliste vaatluste ja tõendite põhjal üldisemaid järeldusi.",
          [],
          [],
        ],
      ],
    ],
    [
      116,
      "round-two",
      "american",
      "Name the Magical Tale",
      "Nimeta muinasjutt",
      [
        [
          "The_Frog_Prince",
          "Which fairy tale features a talking frog, a princess and her golden ball, with the frog later restored as a prince?",
          "Millises muinasjutus on rääkiv konn, printsess ja tema kuldne pall ning konn saab hiljem taas printsiks?",
          "The Frog Prince",
          "Konnaprints",
          "Versions differ on how the spell ends, but the talking frog is ultimately restored to princely human form.",
          "Versioonid erinevad nõiduse lõppemise poolest, kuid rääkiv konn saab lõpuks tagasi printsi inimkuju.",
          ["The Frog King"],
          ["Konnakuningas"],
        ],
        [
          "The_Ugly_Duckling",
          "Which Andersen tale follows a mocked young bird that grows up to discover it is a swan?",
          "Milline Anderseni muinasjutt räägib pilgatud linnupojast, kes kasvades avastab, et on luik?",
          "The Ugly Duckling",
          "Inetu pardipoeg",
          "The rejected young bird matures into a beautiful swan.",
          "Tõrjutud linnupoeg kasvab kauniks luigeks.",
          [],
          [],
        ],
        [
          "Beauty_and_the_Beast",
          "Which fairy tale has a young woman learn to love an enchanted monster, breaking his curse?",
          "Millises muinasjutus õpib noor naine armastama nõiutud koletist ja murrab tema needuse?",
          "Beauty and the Beast",
          "Kaunitar ja koletis",
          "Her love sees beyond the frightening appearance and ends the enchantment.",
          "Tema armastus näeb hirmutavast välimusest kaugemale ja lõpetab nõiduse.",
          [],
          [],
        ],
        [
          "The_Emperor%27s_New_Clothes",
          "Which Andersen tale ends when a child points out that a vain ruler is wearing nothing at all?",
          "Milline Anderseni muinasjutt kulmineerub sellega, et laps ütleb edevale valitsejale, et tal pole midagi seljas?",
          "The Emperor's New Clothes",
          "Keisri uued rõivad",
          "Swindlers fool the ruler and his court until a child says what everyone can see.",
          "Petturid narrivad valitsejat ja tema õukonda, kuni laps ütleb välja selle, mida kõik näevad.",
          ["The Emperor Has No Clothes"],
          ["Keisri uued riided"],
        ],
        [
          "The_Princess_and_the_Pea",
          "Which fairy tale tests a royal guest by hiding one tiny vegetable beneath a tall pile of mattresses?",
          "Millises muinasjutus pannakse kuninglik külaline proovile, peites kõrge madratsikuhja alla ühe tillukese köögivilja?",
          "The Princess and the Pea",
          "Printsess herneteral",
          "The guest's sensitivity to the hidden pea is treated as proof of her royal identity.",
          "Külalise tundlikkust peidetud herne suhtes peetakse tema kuningliku päritolu tõendiks.",
          [],
          [],
        ],
      ],
    ],
    [
      117,
      "round-two",
      "modern-philosophy",
      "Bad Arguments in Conversation",
      "Halvad argumendid vestluses",
      [
        [
          "Double_standard",
          "A manager excuses a friend's lateness but punishes a rival for the same delay. What unfair use of two different rules is this?",
          "Juht vabandab sõbra hilinemise, kuid karistab rivaali täpselt sama hilinemise eest. Kuidas nimetatakse kahe eri mõõdupuu ebaõiglast kasutamist?",
          "double standard",
          "topeltstandard",
          "The same behaviour is judged by different rules depending on who does it.",
          "Sama käitumist hinnatakse eri reeglite järgi sõltuvalt sellest, kes nii käitub.",
          ["double standards"],
          ["kahekordne mõõdupuu"],
        ],
        [
          "Argumentum_ad_populum",
          "Someone says a claim must be true because millions of people believe it. Name this bad argument.",
          "Keegi väidab, et miski peab olema tõsi, sest miljonid inimesed usuvad seda. Nimeta see vigane argument.",
          "appeal to popularity",
          "enamusele apelleerimine",
          "Widespread belief is presented as proof even though popularity does not establish truth.",
          "Laialdast uskumist esitatakse tõendina, kuigi populaarsus ei näita väite tõesust.",
          [
            "bandwagon fallacy",
            "argumentum ad populum",
            "popularity argument",
            "appeal to the majority",
          ],
          [
            "karjaargument",
            "populaarsusele apelleerimine",
            "populaarsusargument",
            "enamuse argument",
          ],
        ],
        [
          "Circular_reasoning",
          "A speaker says, 'This rule is correct because it is the right rule.' What faulty reasoning simply repeats its own claim?",
          "Kõneleja ütleb: „See reegel on õige, sest see on õige reegel.” Milline vigane põhjendus kordab lihtsalt oma väidet?",
          "circular reasoning",
          "ringtõestus",
          "The conclusion is used as its own support instead of receiving independent evidence.",
          "Järeldust kasutatakse iseenda toetusena, selle asemel et tuua sõltumatuid tõendeid.",
          ["circular argument", "begging the question"],
          ["ringargument", "suletud ringiga põhjendus"],
        ],
        [
          "Cherry_picking",
          "Someone selects only evidence supporting one side and ignores contrary cases. Name this practice.",
          "Keegi valib ainult üht poolt toetavad tõendid ja eirab vastupidiseid juhtumeid. Nimeta selline võte.",
          "cherry picking",
          "tõendite valikuline esitamine",
          "Only supportive cases are presented, while contrary evidence is left out.",
          "Esitatakse ainult toetavaid juhtumeid ja vastupidised tõendid jäetakse välja.",
          ["selective use of evidence"],
          ["sobivate tõendite valimine"],
        ],
        [
          "Argument_from_analogy",
          "Someone argues that apples and oranges must taste the same because both are fruit. What bad argument relies on this weak likeness?",
          "Keegi väidab, et õunad ja apelsinid peavad maitsema ühtemoodi, sest mõlemad on puuviljad. Milline vigane argument toetub sellisele nõrgale sarnasusele?",
          "false analogy",
          "valeanaloogia",
          "The comparison ignores relevant differences and draws a conclusion from a superficial similarity.",
          "Võrdlus eirab olulisi erinevusi ja teeb pealiskaudse sarnasuse põhjal järelduse.",
          ["faulty analogy", "weak analogy", "false comparison"],
          ["vigane analoogia", "ekslik võrdlus", "vale samastamine"],
        ],
      ],
    ],
    [
      118,
      "round-two",
      "modern-philosophy",
      "Everyday Ethical Choices",
      "Igapäevased eetilised valikud",
      [
        [
          "Ethical_dilemma",
          "You must choose between two actions, but either choice violates an important value. What kind of difficult choice is this?",
          "Pead valima kahe teo vahel, kuid kumbki valik rikub mõnd olulist väärtust. Milline raske valikuolukord see on?",
          "moral dilemma",
          "moraalne dilemma",
          "The situation creates competing moral duties, so every available choice has an ethical cost.",
          "Olukorras põrkuvad moraalsed kohustused, mistõttu on igal võimalikul valikul eetiline hind.",
          ["ethical dilemma"],
          ["eetiline dilemma"],
        ],
        [
          "Conflict_of_interest",
          "A city official must choose a contractor, but one bidder belongs to their family. What ethical problem should be declared?",
          "Linnaametnik peab valima töövõtja, kuid üks pakkuja kuulub tema pereliikmele. Millisest eetilisest probleemist tuleks teatada?",
          "conflict of interest",
          "huvide konflikt",
          "A personal relationship or benefit could improperly influence an official decision.",
          "Isiklik suhe või kasu võib ametiotsust sobimatult mõjutada.",
          ["competing interests"],
          ["huvide vastuolu"],
        ],
        [
          "Moral_compass",
          "What metaphorical inner guide helps a person judge right from wrong?",
          "Milline kujundlik sisemine teejuht aitab inimesel eristada õiget valest?",
          "moral compass",
          "moraalne kompass",
          "The metaphor compares ethical judgment with an instrument that points a direction.",
          "Kujund võrdleb eetilist otsustusvõimet suunda näitava instrumendiga.",
          ["ethical compass"],
          ["eetiline kompass"],
        ],
        [
          "Common_good",
          "A town chooses a clean public park that benefits everyone rather than a private perk for a few. What shared aim is it serving?",
          "Linn valib kõigile kasuliku puhta avaliku pargi, mitte vähestele mõeldud eraeelise. Millist ühist eesmärki see teenib?",
          "common good",
          "ühine hüve",
          "The decision seeks a benefit shared by the community as a whole.",
          "Otsus taotleb kasu, mida jagab kogukond tervikuna.",
          ["common welfare"],
          ["üldine hüve"],
        ],
        [
          "Lesser_of_two_evils_principle",
          "Neither available option is good, so you choose the one expected to cause less harm. What familiar principle is this?",
          "Kumbki võimalik valik pole hea, seega valid selle, mis põhjustab eeldatavasti vähem kahju. Milline tuttav põhimõte see on?",
          "lesser evil",
          "väiksem kurjus",
          "The principle favours the less harmful choice when all available options are bad.",
          "Põhimõte eelistab vähem kahjulikku valikut, kui kõik võimalused on halvad.",
          ["lesser of two evils"],
          ["kahest halvast väiksem"],
        ],
      ],
    ],
    [
      119,
      "round-two",
      "early-modern-philosophy",
      "Latin Phrases in Everyday Use",
      "Ladinakeelsed väljendid igapäevaelus",
      [
        [
          "Carpe_diem",
          "Which famous Latin phrase urges you to make full use of the present moment instead of waiting for tomorrow?",
          "Milline kuulus ladinakeelne väljend soovitab tänast võimalust kohe kasutada, mitte homset ootama jääda?",
          "carpe diem",
          "carpe diem",
          "The phrase encourages making use of the present instead of relying on an uncertain future.",
          "Väljend kutsub praegust hetke kasutama, selle asemel et loota ebakindlale tulevikule.",
          ["seize the day"],
          ["haara päevast"],
        ],
        [
          "Tabula_rasa",
          "Which Latin phrase describes a fresh start with no previous marks or assumptions, as if a writing surface had been wiped clean?",
          "Milline ladinakeelne väljend tähendab „puhast lehte” ehk uut algust ilma varasemate jälgede või eeldusteta?",
          "tabula rasa",
          "tabula rasa",
          "Literally a scraped-clean tablet, the expression now describes an unmarked starting point.",
          "Sõna-sõnalt puhtaks kraabitud tahvel tähistab nüüd varasemate märkideta alguspunkti.",
          ["blank slate"],
          ["puhas leht"],
        ],
        [
          "Status_quo",
          "Which Latin phrase used in everyday speech means that conditions remain unchanged?",
          "Milline igapäevases kõnes kasutatav ladinakeelne väljend tähendab, et olukord jääb samaks?",
          "status quo",
          "status quo",
          "The expression refers to conditions as they currently are, especially before a proposed change.",
          "Väljend tähistab praegust olukorda, eriti enne kavandatavat muutust.",
          ["existing state of affairs"],
          ["olemasolev olukord"],
        ],
        [
          "Et_cetera",
          "Which two-word Latin phrase is shortened to a familiar three-letter abbreviation after examples when a list continues in the same way?",
          "Milline kahesõnaline ladinakeelne väljend lühendatakse kolme tähega, kui loetelu jätkub samal viisil?",
          "et cetera",
          "et cetera",
          "Writers use the phrase or its abbreviation to show that a list continues in the same way.",
          "Kirjutajad kasutavad väljendit või selle lühendit, et näidata loetelu samal viisil jätkumist.",
          ["the abbreviation etc."],
          ["lühend etc."],
        ],
        [
          "Good_faith",
          "Which Latin phrase used in English can label something authentic or an action done honestly rather than deceptively?",
          "Milline rahvusvahelises kasutuses olev ladinakeelne väljend võib tähistada ehtsat asja või ausalt tehtud tegu?",
          "bona fide",
          "bona fide",
          "The phrase can describe something authentic or an action performed honestly and sincerely.",
          "Väljend võib kirjeldada ehtsat asja või ausalt ja siiralt tehtud tegu.",
          ["in good faith"],
          ["heas usus"],
        ],
      ],
    ],
    [
      120,
      "round-two",
      "modern-philosophy",
      "Big Ideas in Famous Sayings",
      "Suured mõtted tuntud ütlustes",
      [
        [
          "Knowledge_is_power",
          "Name the familiar maxim linking what a person knows with the capacity to act or influence events.",
          "Nimeta tuntud mõttetera, mis seostab inimese teadmised tegutsemis- või mõjutamisvõimega.",
          "knowledge is power",
          "teadmine on jõud",
          "The saying links what someone knows to their ability to act.",
          "Ütlus seostab inimese teadmised tema tegutsemisvõimega.",
          ["information is power", "knowledge gives power"],
          ["info on jõud", "teadmised annavad jõu"],
        ],
        [
          "Know_thyself",
          "Name the ancient maxim associated with a shrine inscription that urges a person to understand their own character.",
          "Nimeta vana mõttetera, mida seostatakse muistsele pühamule raiutud kirjaga ja mis kutsub inimest oma iseloomu mõistma.",
          "know thyself",
          "tunne iseennast",
          "The maxim is associated with an ancient shrine inscription.",
          "Mõttetera seostatakse muistsele pühamule raiutud kirjaga.",
          ["know yourself"],
          ["tunne ennast"],
        ],
        [
          "The_pen_is_mightier_than_the_sword",
          "Which familiar saying claims that writing and ideas can achieve more than violence?",
          "Milline tuntud ütlus väidab, et kirjutamine ja ideed võivad saavutada rohkem kui vägivald?",
          "the pen is mightier than the sword",
          "sulg on võimsam kui mõõk",
          "The saying contrasts the influence of written ideas with the use of armed force.",
          "Ütlus vastandab kirjalike mõtete mõju relvastatud jõu kasutamisele.",
          ["the word is mightier than the sword"],
          ["sõna on võimsam kui mõõk"],
        ],
        [
          "All_that_glitters_is_not_gold",
          "Which familiar saying warns that an attractive appearance does not guarantee real value?",
          "Milline tuntud ütlus hoiatab, et ahvatlev välimus ei taga tegelikku väärtust?",
          "all that glitters is not gold",
          "kõik, mis hiilgab, pole kuld",
          "The saying notes that something shiny or attractive may still be worthless or deceptive.",
          "Ütlus märgib, et särav või ahvatlev asi võib siiski olla väärtusetu või petlik.",
          ["not all that glitters is gold", "all that glistens is not gold"],
          ["mitte kõik hiilgav pole kuld", "kõik, mis särab, pole kuld"],
        ],
        [
          "The_road_to_hell_is_paved_with_good_intentions",
          "Which familiar saying warns that meaning well is not enough if actions lead to harmful results?",
          "Milline tuntud ütlus hoiatab, et heast tahtest ei piisa, kui teod viivad kahjulike tulemusteni?",
          "hell is paved with good intentions",
          "head kavatsused sillutavad põrguteed",
          "Good intentions can still lead to harmful actions or consequences.",
          "Head kavatsused võivad siiski viia kahjulike tegude või tagajärgedeni.",
          ["the road to hell is paved with good intentions"],
          ["tee põrgusse on sillutatud heade kavatsustega"],
        ],
      ],
    ],
  ];

function slug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLocaleLowerCase("en")
    .replace(/%[0-9a-f]{2}/giu, "-")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function hash(value: string): string {
  let result = 0x811c9dc5;
  for (const character of value) {
    result = Math.imul(result ^ (character.codePointAt(0) ?? 0), 0x01000193);
  }
  return (result >>> 0).toString(36);
}

function sourceKey(seed: SourceSeed): string {
  return typeof seed === "string" ? slug(seed) : seed.key;
}

function source(seed: SourceSeed, subjectKey: string): EasyExpansionSource {
  if (typeof seed === "string") {
    return {
      sourceId: `source:${subjectKey}`,
      title: `${decodeURIComponent(seed).replace(/_/gu, " ")} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${seed}`,
      license: "CC-BY-SA-4.0",
      retrievedAt: RETRIEVED_AT,
    };
  }
  return {
    sourceId: seed.sourceId,
    title: seed.title,
    url: seed.url,
    license: seed.license,
    retrievedAt: RETRIEVED_AT,
  };
}

function question(
  categorySetId: string,
  categoryIndex: number,
  seed: QuestionSeed,
  questionIndex: number,
): EasyExpansionQuestion {
  const [
    sourceSeed,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    explanationEn,
    explanationEt,
    variantsEn = [],
    variantsEt = [],
  ] = seed;
  const tier = (questionIndex + 1) as 1 | 2 | 3 | 4 | 5;
  const clueNumber = (categoryIndex * 5 + tier).toString().padStart(3, "0");
  const identity = sourceKey(sourceSeed);
  const subjectKey = `mythology-religion-philosophy:${identity}`;
  return {
    clueId: `built-in-mythology-religion-philosophy-easy-expansion-${clueNumber}`,
    key: `mythology-religion-philosophy-easy-expansion:${categorySetId}:${tier}`,
    factKey: `mythology-religion-philosophy-easy-expansion:${identity}:${hash(`${clueEn}\0${responseEn}`)}`,
    tier,
    subjectKey,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variantsEn, et: variantsEt },
    explanation: { en: explanationEn, et: explanationEt },
    source: source(sourceSeed, subjectKey),
  };
}

export const MYTHOLOGY_RELIGION_PHILOSOPHY_EASY_EXPANSION_CATEGORIES: readonly EasyExpansionCategory[] =
  MYTHOLOGY_RELIGION_PHILOSOPHY_EASY_EXPANSION_SEEDS.map(
    ([suffix, round, macroTopic, nameEn, nameEt, questions], categoryIndex) => {
      const categorySetId = `${PACK_ID}-set-${suffix}`;
      return {
        categorySetId,
        batchId: BATCH_ID,
        packId: PACK_ID,
        difficulty: "easy",
        round,
        macroTopic,
        name: { en: nameEn, et: nameEt },
        questions: questions.map((seed, questionIndex) =>
          question(categorySetId, categoryIndex, seed, questionIndex),
        ),
      };
    },
  );
