import type { AccessibleCategory, AccessibleQuestion } from '../types';

type TextPair = readonly [en: string, et: string];
type VariantPair = readonly [en: readonly string[], et: readonly string[]];
type QuestionSeed = readonly [
  slug: string,
  clue: TextPair,
  response: TextPair,
  variants: VariantPair,
  explanation: TextPair,
  sourcePage: string,
];

const PREFIX = 'retained-easy-01-04:';

function source(slug: string, page: string): AccessibleQuestion['source'] {
  const title = decodeURIComponent(page).replaceAll('_', ' ');
  return {
    sourceId: `${PREFIX}source:${slug}`,
    title: `${title} — Wikipedia`,
    url: `https://en.wikipedia.org/wiki/${page}`,
    license: 'CC-BY-SA-4.0',
    retrievedAt: '2026-08-31',
  };
}

function category(
  categorySetId: string,
  batchId: string,
  name: TextPair,
  seeds: readonly QuestionSeed[],
): AccessibleCategory {
  return {
    categorySetId,
    batchId,
    name: { en: name[0], et: name[1] },
    questions: seeds.map((seed, index) => {
      const [slug, clue, response, variants, explanation, sourcePage] = seed;
      return {
        key: `${PREFIX}fact:${slug}`,
        tier: (index + 1) as AccessibleQuestion['tier'],
        subjectKey: `${PREFIX}subject:${slug}`,
        clue: { en: clue[0], et: clue[1] },
        response: { en: response[0], et: response[1] },
        acceptedVariants: { en: variants[0], et: variants[1] },
        explanation: { en: explanation[0], et: explanation[1] },
        source: source(slug, sourcePage),
      };
    }),
  };
}

export const RETAINED_EASY_01_HISTORY_CATEGORIES: readonly AccessibleCategory[] = [
  category('built-in-history-set-000', '01-history',
    ["History's Greatest Plot Twists", 'Ajaloo suurimad pöörded'], [
      ['h000-great-fire-london',
        ['What disaster began near Pudding Lane and burned through much of old London?', 'Milline katastroof sai alguse Pudding Lane’i lähedalt ja hävitas suure osa vanast Londonist?'],
        ['The Great Fire of London', 'Londoni suur tulekahju'], [['Great Fire', 'Great Fire of London'], ['Londoni suurpõleng', 'Suur Londoni tulekahju']],
        ['The Great Fire swept through central London for several days and destroyed thousands of buildings.', 'Londoni suur tulekahju möllas kesklinnas mitu päeva ja hävitas tuhandeid hooneid.'], 'Great_Fire_of_London'],
      ['h000-black-death',
        ['What name is given to the plague pandemic that devastated medieval Europe?', 'Kuidas nimetatakse katkuepideemiat, mis laastas keskaegset Euroopat?'],
        ['The Black Death', 'Must surm'], [['Black Death', 'Great Mortality'], ['Must katk']],
        ['The Black Death was a vast plague pandemic that killed millions across Europe.', 'Must surm oli ulatuslik katkuepideemia, mis tappis Euroopas miljoneid inimesi.'], 'Black_Death'],
      ['h000-magna-carta',
        ['Which charter did rebellious barons force King John of England to seal?', 'Millise üriku sundisid mässulised parunid Inglismaa kuningat Johni kinnitama?'],
        ['Magna Carta', 'Magna Carta'], [['The Great Charter'], ['Suur vabaduskiri']],
        ['Magna Carta limited royal power and became an enduring symbol of the rule of law.', 'Magna Carta piiras kuningavõimu ja sellest sai püsiv õigusriigi sümbol.'], 'Magna_Carta'],
      ['h000-bastille',
        ['Which Paris fortress-prison was stormed at the start of the French Revolution?', 'Milline Pariisi kindlusvangla vallutati Prantsuse revolutsiooni alguses?'],
        ['The Bastille', 'Bastille'], [['Bastille'], ['Bastille’ kindlus']],
        ['The storming of the Bastille became a defining symbol of the French Revolution.', 'Bastille’ vallutamisest sai Prantsuse revolutsiooni üks põhisümboleid.'], 'Storming_of_the_Bastille'],
      ['h000-hms-bounty',
        ['Which British ship became famous for a mutiny in the South Pacific?', 'Milline Briti laev sai kuulsaks Vaikse ookeani lõunaosas toimunud mässu tõttu?'],
        ['HMS Bounty', 'HMS Bounty'], [['The Bounty', 'Bounty'], ['Bounty']],
        ['Mutineers seized HMS Bounty from Lieutenant William Bligh in 1789.', 'Mässajad hõivasid 1789. aastal leitnant William Bligh’lt laeva HMS Bounty.'], 'Mutiny_on_the_Bounty'],
    ]),

  category('built-in-history-set-003', '01-history',
    ["A Time Traveller's Packing List", 'Ajaränduri pakkimisnimekiri'], [
      ['h003-toga',
        ['What draped woollen garment would help a citizen blend into public life in ancient Rome?', 'Milline üle keha seatav villane rõivas aitaks kodanikul Vana-Rooma avalikus elus sulanduda?'],
        ['A toga', 'Tooga'], [['Toga'], ['Tooga']],
        ['The toga was a distinctive outer garment of Roman citizens.', 'Tooga oli Rooma kodanike iseloomulik pealisrõivas.'], 'Toga'],
      ['h003-quill',
        ['What writing tool made from a large bird feather belonged on many medieval desks?', 'Milline suure linnu sulest valmistatud kirjutusvahend kuulus paljudele keskaegsetele kirjutuslaudadele?'],
        ['A quill pen', 'Sulg'], [['Quill', 'Feather pen'], ['Kirjutussulg', 'Linnusulg']],
        ['Quills were the main writing instruments in Europe for many centuries.', 'Kirjutussuled olid Euroopas sajandeid peamised kirjutusvahendid.'], 'Quill'],
      ['h003-abacus',
        ['What bead-frame tool would help a trader calculate before electronic calculators?', 'Milline helmestega raam aitaks kaupmehel arvutada enne elektroonilisi kalkulaatoreid?'],
        ['An abacus', 'Arvelaud'], [['Abacus', 'Counting frame'], ['Abakus', 'Arvutuslaud']],
        ['An abacus represents numbers with movable beads arranged on rods or wires.', 'Arvelaual kujutatakse arve varrastel või traatidel liikuvate helmestega.'], 'Abacus'],
      ['h003-astrolabe',
        ['What handheld instrument let historical navigators estimate position from the Sun or stars?', 'Milline käeshoitav instrument aitas kunagistel meresõitjatel Päikese või tähtede järgi asukohta hinnata?'],
        ['An astrolabe', 'Astrolaab'], [['Astrolabe'], ['Astrolaab']],
        ['Mariners used astrolabes to measure the altitude of celestial objects above the horizon.', 'Meresõitjad kasutasid astrolaabi taevakehade kõrguse mõõtmiseks horisondi kohal.'], "Mariner's_astrolabe"],
      ['h003-cuneiform-tablet',
        ['What clay object covered in wedge-shaped marks could carry a message in ancient Mesopotamia?', 'Milline kiilukujuliste märkidega kaetud saviese võis kanda sõnumit muistses Mesopotaamias?'],
        ['A cuneiform tablet', 'Kiilkirjatahvel'], [['Clay tablet', 'Cuneiform clay tablet'], ['Savitahvel', 'Kiilkirjaga savitahvel']],
        ['Scribes pressed cuneiform signs into wet clay and then dried or fired the tablets.', 'Kirjutajad vajutasid kiilkirjamärgid märga savisse ning kuivatasid või põletasid tahvlid.'], 'Clay_tablet'],
    ]),

  category('built-in-history-set-011', '01-history',
    ['Famous Firsts, No Dates', 'Kuulsad esimesed ilma aastaarvudeta'], [
      ['h011-barack-obama',
        ['Which politician became the first Black person elected to lead the United States?', 'Millisest poliitikust sai esimene mustanahaline inimene, kes valiti Ameerika Ühendriike juhtima?'],
        ['Barack Obama', 'Barack Obama'], [['Obama', 'Barack Hussein Obama'], ['Obama']],
        ['Barack Obama became the first African American elected to lead the United States.', 'Barack Obamast sai esimene afroameeriklane, kes valiti Ameerika Ühendriike juhtima.'], 'Barack_Obama'],
      ['h011-dolly-sheep',
        ['What sheep became the first mammal cloned from an adult body cell?', 'Millisest lambast sai esimene täiskasvanud keharakust kloonitud imetaja?'],
        ['Dolly the sheep', 'Lammas Dolly'], [['Dolly', 'Dolly the Sheep'], ['Dolly']],
        ['Dolly was cloned from the nucleus of an adult mammary-gland cell.', 'Dolly klooniti täiskasvanud lamba piimanäärmeraku tuumast.'], 'Dolly_(sheep)'],
      ['h011-roald-amundsen',
        ['Which Norwegian explorer led the first expedition to reach the South Pole?', 'Milline Norra maadeavastaja juhtis esimest lõunapoolusele jõudnud ekspeditsiooni?'],
        ['Roald Amundsen', 'Roald Amundsen'], [['Amundsen'], ['Amundsen']],
        ['Roald Amundsen and four companions reached the South Pole before Robert Falcon Scott.', 'Roald Amundsen ja neli kaaslast jõudsid lõunapoolusele enne Robert Falcon Scotti.'], 'Roald_Amundsen'],
      ['h011-kathryn-bigelow',
        ['Which filmmaker became the first woman to win the Academy Award for Best Director?', 'Millisest filmitegijast sai esimene naine, kes võitis parima režissööri Oscari?'],
        ['Kathryn Bigelow', 'Kathryn Bigelow'], [['Bigelow'], ['Bigelow']],
        ['Kathryn Bigelow won Best Director for The Hurt Locker.', 'Kathryn Bigelow võitis parima režissööri Oscari filmi „Piinakamber” eest.'], 'Kathryn_Bigelow'],
      ['h011-roger-bannister',
        ['Which British runner became the first person recorded as completing a mile in under four minutes?', 'Milline Briti jooksja läbis esimesena miili ametlikult alla nelja minuti?'],
        ['Roger Bannister', 'Roger Bannister'], [['Bannister'], ['Bannister']],
        ['Roger Bannister broke the four-minute mile barrier at Oxford.', 'Roger Bannister alistas Oxfordis nelja minuti miili piiri.'], 'Roger_Bannister'],
    ]),

  category('built-in-history-set-013', '01-history',
    ["People You'd Meet in a Time Machine", 'Inimesed, keda kohtaksid ajamasinas'], [
      ['h013-cleopatra',
        ['Which queen ruled ancient Egypt and allied herself with Julius Caesar and Mark Antony?', 'Milline kuninganna valitses Vana-Egiptust ning oli liidus Julius Caesari ja Marcus Antoniusega?'],
        ['Cleopatra', 'Kleopatra'], [['Cleopatra VII'], ['Kleopatra VII', 'Cleopatra']],
        ['Cleopatra VII was the last active ruler of Ptolemaic Egypt.', 'Kleopatra VII oli Ptolemaioste Egiptuse viimane aktiivne valitseja.'], 'Cleopatra'],
      ['h013-marco-polo',
        ['Which Venetian traveller became famous in Europe for accounts of journeys across Asia?', 'Milline Veneetsia rändur sai Euroopas kuulsaks oma Aasia-reiside kirjeldustega?'],
        ['Marco Polo', 'Marco Polo'], [['Polo'], ['Polo']],
        ['Marco Polo’s travels were recorded in a book describing lands across Asia.', 'Marco Polo reisid jäädvustati raamatus, mis kirjeldab maid üle kogu Aasia.'], 'Marco_Polo'],
      ['h013-joan-of-arc',
        ['Which French heroine led troops during the Hundred Years’ War and was later made a saint?', 'Milline Prantsuse kangelanna juhtis saja-aastases sõjas vägesid ja kuulutati hiljem pühakuks?'],
        ['Joan of Arc', 'Jeanne d’Arc'], [['Jeanne d’Arc', 'The Maid of Orléans'], ['Orléansi neitsi', 'Jeanne d’Arc']],
        ['Joan of Arc helped French forces during the siege of Orléans and was later canonised.', 'Jeanne d’Arc aitas Prantsuse vägesid Orléansi piiramisel ja kuulutati hiljem pühakuks.'], 'Joan_of_Arc'],
      ['h013-alexander-fleming',
        ['Which scientist noticed that mould in a laboratory dish killed nearby bacteria, leading to penicillin?', 'Milline teadlane märkas, et laborinõus olev hallitus tappis lähedal baktereid, sillutades teed penitsilliinile?'],
        ['Alexander Fleming', 'Alexander Fleming'], [['Fleming'], ['Fleming']],
        ['Alexander Fleming observed the antibacterial effect of Penicillium mould.', 'Alexander Fleming märkas Penicillium’i hallituse antibakteriaalset toimet.'], 'Alexander_Fleming'],
      ['h013-ada-lovelace',
        ['Which mathematician wrote an algorithm for Charles Babbage’s planned Analytical Engine?', 'Milline matemaatik kirjutas algoritmi Charles Babbage’i kavandatud analüütilisele masinale?'],
        ['Ada Lovelace', 'Ada Lovelace'], [['Augusta Ada King', 'Lovelace'], ['Augusta Ada King', 'Lovelace']],
        ['Ada Lovelace’s notes contain an algorithm intended for Babbage’s mechanical computer.', 'Ada Lovelace’i märkmetes leidub Babbage’i mehaanilisele arvutile mõeldud algoritm.'], 'Ada_Lovelace'],
    ]),

  category('built-in-history-set-017', '01-history',
    ['Objects That Tell a Story', 'Esemed, mis jutustavad loo'], [
      ['h017-enigma-machine',
        ['What cipher device did Nazi Germany use for many secret military messages?', 'Millist šifreerimisseadet kasutas Natsi-Saksamaa paljude salajaste sõjaväesõnumite jaoks?'],
        ['The Enigma machine', 'Enigma masin'], [['Enigma', 'Enigma cipher machine'], ['Enigma', 'Enigma šifrimasin']],
        ['Allied cryptanalysts worked to read messages encrypted by Enigma machines.', 'Liitlasriikide krüptoanalüütikud töötasid Enigma masinatega krüpteeritud sõnumite lugemise nimel.'], 'Enigma_machine'],
      ['h017-gutenberg-bible',
        ['Which famous book was among the earliest major works printed in Europe with movable metal type?', 'Milline kuulus raamat oli üks esimesi suuremaid Euroopas liikuvate metalltähtedega trükitud teoseid?'],
        ['The Gutenberg Bible', 'Gutenbergi piibel'], [['Gutenberg Bible', 'The 42-line Bible'], ['Gutenbergi 42-realine piibel']],
        ['The Gutenberg Bible demonstrated the scale and quality possible with movable-type printing.', 'Gutenbergi piibel näitas liikuva kirjaga trükkimise võimalikku mahtu ja kvaliteeti.'], 'Gutenberg_Bible'],
      ['h017-hammurabi-code',
        ['Which ancient law collection was carved on a tall stone monument for a Babylonian king?', 'Milline muistne seadustekogu raiuti Babüloonia kuninga jaoks kõrgele kivisambale?'],
        ['The Code of Hammurabi', 'Hammurapi seadused'], [['Hammurabi’s Code', 'Code of Hammurabi'], ['Hammurapi koodeks', 'Hammurapi seadustekogu']],
        ['The Code of Hammurabi survives on a stone stele bearing laws in cuneiform script.', 'Hammurapi seadused on säilinud kiilkirjas seadusi kandval kivisteelil.'], 'Code_of_Hammurabi'],
      ['h017-bayeux-tapestry',
        ['Which embroidered medieval artwork tells the story of the Norman conquest of England?', 'Milline tikitud keskaegne kunstiteos jutustab normannide Inglismaa-vallutuse loo?'],
        ['The Bayeux Tapestry', 'Bayeux’ vaip'], [['Bayeux Tapestry', 'The Bayeux embroidery'], ['Bayeux’ seinavaip', 'Bayeux’ tikand']],
        ['The Bayeux Tapestry depicts events surrounding the conquest and the Battle of Hastings.', 'Bayeux’ vaip kujutab vallutusega seotud sündmusi ja Hastingsi lahingut.'], 'Bayeux_Tapestry'],
      ['h017-antikythera-mechanism',
        ['What ancient Greek geared device is often described as an early analogue computer?', 'Millist Vana-Kreeka hammasratastega seadet kirjeldatakse sageli varase analoogarvutina?'],
        ['The Antikythera mechanism', 'Antikythera mehhanism'], [['Antikythera Mechanism'], ['Antikythera mehhanism']],
        ['The Antikythera mechanism modelled astronomical cycles using bronze gears.', 'Antikythera mehhanism kujutas pronkshammasrataste abil astronoomilisi tsükleid.'], 'Antikythera_mechanism'],
    ]),

  category('built-in-history-set-019', '01-history',
    ['Voyages That Changed the Story', 'Reisid, mis muutsid lugu'], [
      ['h019-apollo-11',
        ['Which space mission carried the first people to walk on the Moon?', 'Milline kosmosemissioon viis esimesed inimesed Kuu pinnale?'],
        ['Apollo 11', 'Apollo 11'], [['Apollo Eleven'], ['Apollo üksteist']],
        ['Apollo 11 landed Neil Armstrong and Buzz Aldrin on the lunar surface.', 'Apollo 11 viis Neil Armstrongi ja Buzz Aldrini Kuu pinnale.'], 'Apollo_11'],
      ['h019-mayflower',
        ['Which ship carried the Pilgrims from England to North America?', 'Milline laev viis palverändurid Inglismaalt Põhja-Ameerikasse?'],
        ['The Mayflower', 'Mayflower'], [['Mayflower'], ['Mayfloweri laev']],
        ['The Mayflower carried English families who founded Plymouth Colony.', 'Mayflower viis üle ookeani Inglise pered, kes rajasid Plymouthi koloonia.'], 'Mayflower'],
      ['h019-hms-beagle',
        ['Which survey ship carried Charles Darwin on the journey that shaped his ideas about evolution?', 'Milline uurimislaev viis Charles Darwini reisile, mis kujundas tema evolutsiooniideid?'],
        ['HMS Beagle', 'HMS Beagle'], [['The Beagle', 'Beagle'], ['Beagle']],
        ['Darwin sailed around the world aboard HMS Beagle and collected evidence from many regions.', 'Darwin purjetas laeval HMS Beagle ümber maailma ja kogus tõendeid paljudest piirkondadest.'], 'HMS_Beagle'],
      ['h019-kon-tiki',
        ['What raft did Thor Heyerdahl sail across the Pacific to test a theory about ancient migration?', 'Millise parvega purjetas Thor Heyerdahl üle Vaikse ookeani, et katsetada muistse rände teooriat?'],
        ['Kon-Tiki', 'Kon-Tiki'], [['The Kon-Tiki'], ['Kon-Tiki parv']],
        ['Kon-Tiki was a balsa-wood raft inspired by pre-Columbian South American craft.', 'Kon-Tiki oli Kolumbuse-eelsetest Lõuna-Ameerika alustest inspireeritud balsapuust parv.'], 'Kon-Tiki_expedition'],
      ['h019-endurance',
        ["Which ship was crushed by Antarctic ice during Ernest Shackleton's Imperial Trans-Antarctic Expedition?", 'Millise laeva purustas Antarktika jää Ernest Shackletoni keiserlikul Antarktika-ekspeditsioonil?'],
        ['Endurance', 'Endurance'], [['The Endurance'], ['Endurance’i laev']],
        ["Although Endurance sank, Shackleton's entire stranded party survived.", 'Kuigi Endurance uppus, jäi kogu Shackletoni merehätta sattunud meeskond ellu.'], 'Endurance_(1912_ship)'],
    ]),

  category('built-in-history-set-024', '01-history',
    ['History Hiding in Plain Sight', 'Ajalugu otse meie silme all'], [
      ['h024-earl-of-sandwich',
        ['Which British nobleman is traditionally credited with lending his title to a meal between two slices of bread?', 'Millise Briti aadlimehe tiitlist pärineb pärimuse järgi kahe leivaviilu vahele pandud eine nimetus?'],
        ['The Earl of Sandwich', 'Sandwichi krahv'], [['John Montagu', 'Fourth Earl of Sandwich'], ['John Montagu', 'Sandwichi neljas krahv']],
        ['The sandwich is traditionally associated with John Montagu, the fourth Earl of Sandwich.', 'Võileiva ingliskeelne nimetus seostub pärimuse järgi Sandwichi neljanda krahvi John Montaguga.'], 'John_Montagu,_4th_Earl_of_Sandwich'],
      ['h024-theodore-roosevelt-teddy',
        ['Which American leader lent his nickname to the teddy bear?', 'Millise Ameerika riigijuhi hüüdnimest sai kaisukaru ingliskeelne nimi „teddy bear”?'],
        ['Theodore Roosevelt', 'Theodore Roosevelt'], [['Teddy Roosevelt', 'Roosevelt'], ['Teddy Roosevelt', 'Roosevelt']],
        ['The teddy bear was named after Theodore “Teddy” Roosevelt following a famous hunting story.', 'Kaisukaru ingliskeelne nimi tekkis Theodore „Teddy” Rooseveltiga seotud kuulsa jahiloo järel.'], 'Teddy_bear'],
      ['h024-boycott',
        ['Which word for deliberately refusing to buy something originated with an ostracised Irish land agent?', 'Milline teadliku ostmisest keeldumise sõna sai alguse Iirimaal tõrjutud maavalitseja loost?'],
        ['A boycott', 'Boikott'], [['Boycotting'], ['Boikoteerimine']],
        ['Charles Boycott’s name became a verb and noun after his community organised a campaign of social and economic isolation against him.', 'Charles Boycotti nimest sai tegusõna ja nimisõna pärast seda, kui kogukond korraldas tema vastu sotsiaalse ja majandusliku tõrjumise kampaania.'], 'Boycott'],
      ['h024-harald-bluetooth',
        ['Which medieval Danish king inspired the name of a modern short-range wireless standard?', 'Milline keskaegne Taani kuningas andis nime tänapäevasele lähiraadioside standardile?'],
        ['Harald Bluetooth', 'Harald Sinihammas'], [['Harald I', 'Harald Gormsson'], ['Harald Bluetooth', 'Harald I', 'Harald Gormsson']],
        ['The wireless standard was named for Harald Bluetooth, who united parts of Denmark and Norway.', 'Raadiosidestandard nimetati Harald Sinihamba järgi, kes ühendas osa Taanist ja Norrast.'], 'Harald_Bluetooth'],
      ['h024-earl-of-cardigan',
        ['Which Crimean War commander gave his title to a buttoned knitted garment?', 'Milline Krimmi sõja väejuht andis oma tiitli nööbitavale kootud rõivaesemele?'],
        ['The Earl of Cardigan', 'Cardigani krahv'], [['James Brudenell', 'Seventh Earl of Cardigan'], ['James Brudenell', 'Cardigani seitsmes krahv']],
        ['The cardigan was named after James Brudenell, the seventh Earl of Cardigan.', 'Kardigan sai nime Cardigani seitsmenda krahvi James Brudenelli järgi.'], 'James_Brudenell,_7th_Earl_of_Cardigan'],
    ]),

  category('built-in-history-set-026', '01-history',
    ['History by Its Symbols', 'Ajalugu sümbolite kaudu'], [
      ['h026-v-sign',
        ['Which two-finger hand gesture did Winston Churchill use as a wartime sign of victory?', 'Millist kahe sõrmega käemärki kasutas Winston Churchill sõja ajal võidu tähisena?'],
        ['The V sign', 'V-märk'], [['Victory sign', 'V for victory'], ['Võidumärk', 'V võidu tähisena']],
        ['Churchill’s use of the V sign helped make it one of the best-known images of Allied victory during the Second World War.', 'Churchilli kasutatud V-märgist sai Teise maailmasõja ajal üks tuntumaid liitlaste võidu kujutisi.'], 'V_sign'],
      ['h026-hammer-and-sickle',
        ['Which emblem paired a farm tool with a metalworking tool to represent peasants and industrial workers?', 'Milline embleem ühendas talutööriista metallitööriistaga, et kujutada talupoegi ja tööstustöölisi?'],
        ['The hammer and sickle', 'Sirp ja vasar'], [['Hammer and sickle'], ['Vasar ja sirp']],
        ['The hammer and sickle became the best-known emblem of Soviet communism.', 'Sirbist ja vasarast sai Nõukogude kommunismi tuntuim embleem.'], 'Hammer_and_sickle'],
      ['h026-jolly-roger',
        ['What name is given to the skull-and-crossbones flag associated with pirates?', 'Kuidas nimetatakse piraatidega seostatud pealuu ja ristatud kontidega lippu?'],
        ['The Jolly Roger', 'Jolly Roger'], [['Jolly Roger', 'Pirate flag'], ['Piraadilipp', 'Piraatide lipp']],
        ['Jolly Roger is the familiar name for flags flown by some pirates to identify or intimidate.', 'Jolly Roger on mõne piraadi kasutatud lippude tuntud nimetus, mis pidi neid tuvastama või vastaseid hirmutama.'], 'Jolly_Roger'],
      ['h026-laurel-wreath',
        ['What ring of bay leaves was used to honour victors in the ancient Greek and Roman worlds?', 'Millise loorberilehtedest pärjaga austati Vana-Kreekas ja Vana-Roomas võitjaid?'],
        ['A laurel wreath', 'Loorberipärg'], [['Laurel crown', 'Bay wreath'], ['Loorberikroon']],
        ['Laurel wreaths crowned athletic, poetic, and military victors and became lasting symbols of triumph.', 'Loorberipärjad kroonisid spordi-, luule- ja sõjalisi võitjaid ning neist said püsivad triumfi sümbolid.'], 'Laurel_wreath'],
      ['h026-fleur-de-lis',
        ['What stylised lily was long associated with French royalty?', 'Milline stiliseeritud liilia oli kaua seotud Prantsuse kuningavõimuga?'],
        ['The fleur-de-lis', 'Fleur-de-lis'], [['Fleur-de-lys', 'Fleur de lis', 'Fleur de lys'], ['Prantsuse liilia', 'Liiliaembleem']],
        ['The fleur-de-lis appeared throughout the heraldry of the French monarchy.', 'Fleur-de-lis esines laialt Prantsuse monarhia heraldikas.'], 'Fleur-de-lis'],
    ]),
];
