import type { AccessibleCategory, AccessibleQuestion } from '../types';

type Fact = readonly [
  factKey: string,
  subjectKey: string,
  clueEn: string,
  clueEt: string,
  responseEn: string,
  responseEt: string,
  variantsEn: string,
  variantsEt: string,
  explanationEn: string,
  explanationEt: string,
  sourceTitle: string,
  sourcePath: string,
];

function variants(value: string): readonly string[] {
  return value.split('|').map((item) => item.trim()).filter(Boolean);
}

function buildQuestion(
  categorySetId: string,
  fact: Fact,
  tierIndex: number,
): AccessibleQuestion {
  const [
    factKey,
    subjectKey,
    clueEn,
    clueEt,
    responseEn,
    responseEt,
    variantsEn,
    variantsEt,
    explanationEn,
    explanationEt,
    sourceTitle,
    sourcePath,
  ] = fact;
  return {
    key: `retained-easy-09-12:${categorySetId}:${factKey}`,
    tier: (tierIndex + 1) as 1 | 2 | 3 | 4 | 5,
    subjectKey: `retained-easy-09-12:${subjectKey}`,
    clue: { en: clueEn, et: clueEt },
    response: { en: responseEn, et: responseEt },
    acceptedVariants: { en: variants(variantsEn), et: variants(variantsEt) },
    explanation: { en: explanationEn, et: explanationEt },
    source: {
      sourceId: `retained-easy-09-12:source:${sourcePath.toLocaleLowerCase('en')}`,
      title: sourceTitle,
      url: `https://en.wikipedia.org/wiki/${sourcePath}`,
      license: 'CC-BY-SA-4.0',
      retrievedAt: '2026-08-31',
    },
  };
}

function category(
  categorySetId: string,
  batchId: string,
  nameEn: string,
  nameEt: string,
  facts: readonly Fact[],
): AccessibleCategory {
  if (facts.length !== 5) throw new Error(`${categorySetId} must contain five facts`);
  return {
    categorySetId,
    batchId,
    name: { en: nameEn, et: nameEt },
    questions: facts.map((fact, index) => buildQuestion(categorySetId, fact, index)),
  };
}

export const RETAINED_EASY_09_TO_12_CATEGORIES = [
  category(
    'built-in-food-drink-set-001',
    '09-food-drink',
    'A Better Start to the Day',
    'Maitsev algus päevale',
    [
      ['toaster-browns-bread', 'appliance:toaster', 'Which countertop appliance browns slices of bread with radiant heat?', 'Milline köögikapil seisev seade pruunistab saiaviile kiirgussoojusega?', 'Toaster', 'röster', 'bread toaster', 'saiaröster|röstsaiamasin', 'A toaster exposes bread slices to radiant heat until their surfaces brown.', 'Röster kuumutab saiaviile kiirgussoojusega, kuni nende pind pruunistub.', 'Toaster', 'Toaster'],
      ['scrambled-eggs-stirred', 'food:scrambled-eggs', 'Which egg dish is made by stirring beaten eggs gently as they cook in a pan?', 'Milline munaroog valmib lahtiklopitud mune pannil küpsemise ajal segades?', 'Scrambled eggs', 'munapuder', 'scrambled egg', 'puderjas munaroog', 'Scrambled eggs form soft curds when beaten eggs are stirred during cooking.', 'Munapuder muutub pehmeks teraliseks roaks, kui lahtiklopitud mune küpsemise ajal segada.', 'Scrambled eggs', 'Scrambled_eggs'],
      ['granola-baked-clusters', 'food:granola', 'Which crunchy breakfast mix is baked into clusters, often with oats, nuts, and honey?', 'Milline krõbe hommikusöögisegu küpsetatakse tavaliselt kaerahelvestest, pähklitest ja meest kobarateks?', 'Granola', 'granola', 'baked granola', 'krõbe granola', 'Granola is baked until its grains, nuts, and sweetener form crisp clusters.', 'Granolat küpsetatakse, kuni teraviljast, pähklitest ja magustajast tekivad krõbedad kobarad.', 'Granola', 'Granola'],
      ['shakshuka-eggs-tomato', 'food:shakshuka', 'Which North African and Middle Eastern breakfast cooks eggs directly in a spiced tomato sauce?', 'Millises Põhja-Aafrika ja Lähis-Ida hommikusöögiroas küpsetatakse munad otse vürtsikas tomatikastmes?', 'Shakshuka', 'šakšuka', 'shakshouka', 'shakshuka', 'Shakshuka poaches eggs in a sauce of tomatoes, peppers, onions, and spices.', 'Šakšukas pošeeritakse munad tomati-, paprika-, sibula- ja vürtsikastmes.', 'Shakshouka', 'Shakshouka'],
      ['congee-rice-breakfast', 'food:congee', 'Which Asian breakfast dish cooks rice in abundant water until it becomes soft and spoonable?', 'Milline Aasia hommikusöök valmib riisi rohkes vees keetes, kuni see muutub pehmeks ja lusikaga söödavaks?', 'Congee', 'congee', 'rice congee', 'kondži|Aasia riisipuder', 'Congee is made by cooking rice in abundant water until the grains soften into porridge.', 'Congee valmistamiseks keedetakse riisi rohkes vees, kuni terad muutuvad pehmeks pudruks.', 'Congee', 'Congee'],
    ],
  ),
  category(
    'built-in-food-drink-set-002',
    '09-food-drink',
    'Kitchen Curiosities',
    'Köögiüllatused',
    [
      ['popcorn-kernel-bursts', 'food:popcorn', 'Which cinema snack appears when heated maize kernels burst and turn inside out?', 'Milline kinosaali suupiste tekib siis, kui kuumutatud maisiterad lõhkevad ja end pahupidi pööravad?', 'Popcorn', 'popkorn', 'popped corn', 'plaksumais', 'Steam pressure bursts a popcorn kernel and rapidly expands its cooked starch.', 'Aururõhk lõhestab popkornitera ning paisutab selle küpsenud tärklise kiiresti.', 'Popcorn', 'Popcorn'],
      ['lemon-juice-slows-browning', 'ingredient:lemon-juice', 'A squeeze of which tart juice can slow the browning of a cut apple?', 'Millise hapu mahla lisamine võib aeglustada lahtilõigatud õuna pruunistumist?', 'Lemon juice', 'sidrunimahl', 'juice of a lemon', 'sidruni mahl', 'Lemon juice is acidic and contains antioxidants that slow enzymatic browning.', 'Sidrunimahl on happeline ja sisaldab antioksüdante, mis aeglustavad ensümaatilist pruunistumist.', 'Fruit browning', 'Fruit_browning'],
      ['mayonnaise-oil-water-emulsion', 'food:mayonnaise', 'Which creamy sauce keeps droplets of oil mixed with water and egg yolk instead of separating?', 'Millises kreemjas kastmes püsivad õlitilgad vee ja munakollasega segunenuna, mitte ei eraldu?', 'Mayonnaise', 'majonees', 'mayo', 'majoneesikaste', 'Egg-yolk emulsifiers help mayonnaise hold oil and water together.', 'Munakollases olevad emulgaatorid aitavad majoneesis õli ja vett koos hoida.', 'Mayonnaise', 'Mayonnaise'],
      ['pressure-cooker-higher-boiling-point', 'appliance:pressure-cooker', 'Which sealed pot cooks food faster by raising the pressure and boiling point of water?', 'Milline suletud pott küpsetab toitu kiiremini, tõstes rõhku ja vee keemistemperatuuri?', 'Pressure cooker', 'kiirkeedupott', 'pressure pot', 'rõhupott', 'A pressure cooker traps steam, allowing water and food to reach a higher temperature.', 'Kiirkeedupott hoiab auru kinni, nii et vesi ja toit saavutavad kõrgema temperatuuri.', 'Pressure cooking', 'Pressure_cooking'],
      ['aquafaba-whips-like-egg-white', 'ingredient:aquafaba', 'What chickpea-cooking liquid can be whipped into a foam much like egg white?', 'Millist kikerherneste keeduvedelikku saab vahustada peaaegu nagu munavalget?', 'Aquafaba', 'aquafaba', 'chickpea water|chickpea liquid', 'kikerhernevedelik|kikerherne keeduvesi', 'Aquafaba contains dissolved starches and proteins that let it trap air as a foam.', 'Aquafaba sisaldab lahustunud tärklisi ja valke, mis aitavad vahul õhku kinni hoida.', 'Aquafaba', 'Aquafaba'],
    ],
  ),
  category(
    'built-in-food-drink-set-003',
    '09-food-drink',
    'Home Baking Tools and Tricks',
    'Koduse küpsetamise vahendid ja võtted',
    [
      ['oven-enclosed-heating', 'appliance:oven', 'Which enclosed kitchen appliance bakes food with controlled heat?', 'Milline suletud köögiseade küpsetab toitu reguleeritud kuumusega?', 'Oven', 'ahi', 'baking oven', 'küpsetusahi|praeahi', 'An oven surrounds food with controlled heat for baking and roasting.', 'Ahi ümbritseb toitu reguleeritud kuumusega, et seda küpsetada või röstida.', 'Oven', 'Oven'],
      ['rolling-pin-flattens-dough', 'tool:rolling-pin', 'Which cylindrical tool is rolled over dough to flatten it?', 'Millist silindrikujulist tööriista veeretatakse taina peal, et seda õhemaks rullida?', 'Rolling pin', 'tainarull', 'pastry roller', 'taignarull', 'A rolling pin spreads dough into a thinner, even sheet.', 'Tainarull muudab taina õhemaks ja ühtlasemaks kihiks.', 'Rolling pin', 'Rolling_pin'],
      ['parchment-prevents-sticking', 'material:baking-paper', 'Which heat-resistant paper lines a baking tray so biscuits are less likely to stick?', 'Millise kuumakindla paberiga kaetakse küpsetusplaat, et küpsised selle külge kinni ei jääks?', 'Baking paper', 'küpsetuspaber', 'parchment paper|baking parchment', 'pärgamentpaber', 'Baking parchment provides a heat-resistant, non-stick surface on a tray.', 'Küpsetuspaber moodustab plaadile kuumakindla pinna, mille külge toit kergesti ei nakku.', 'Parchment paper', 'Parchment_paper'],
      ['piping-bag-decorates', 'tool:piping-bag', 'Which cone-shaped bag lets a baker pipe neat lines or rosettes of icing?', 'Millise koonilise koti abil saab pagar pritsida glasuurist korralikke jooni või rosette?', 'Piping bag', 'pritskott', 'pastry bag|icing bag', 'kondiitrikott|tordiprits', 'A piping bag pushes soft icing or dough through a shaped nozzle.', 'Pritskott surub pehme glasuuri või taina läbi kujuga otsaku.', 'Pastry bag', 'Pastry_bag'],
      ['bain-marie-gentle-heat', 'technique:bain-marie', 'Which gentle heating method places a bowl of custard or chocolate over or inside hot water?', 'Millise õrna kuumutusviisi puhul asetatakse vanillikreemi või šokolaadiga anum kuuma vee kohale või sisse?', 'Bain-marie', 'vesivann', 'water bath|double boiler', 'kuumaveevann|veevannis kuumutamine', 'A bain-marie surrounds a container with hot water to moderate the heat.', 'Vesivann ümbritseb anuma kuuma veega ja muudab kuumutamise ühtlasemaks.', 'Bain-marie', 'Bain-marie'],
    ],
  ),
  category(
    'built-in-food-drink-set-004',
    '09-food-drink',
    'Fruit with a Surprising Side',
    'Puuviljade üllatav külg',
    [
      ['watermelon-water-rich', 'fruit:watermelon', 'Which huge summer fruit has a green rind and juicy red flesh dotted with dark seeds?', 'Millisel suurel suveviljal on roheline koor ja mahlane punane viljaliha, milles leidub tumedaid seemneid?', 'Watermelon', 'arbuus', 'water melon', 'vesimelon', 'A watermelon is a large melon with a hard rind and water-rich flesh.', 'Arbuus on kõva koore ja väga veerikka viljalihaga suur melon.', 'Watermelon', 'Watermelon'],
      ['kiwifruit-fuzzy-green', 'fruit:kiwifruit', 'Which small brown fuzzy fruit is bright green inside and shares its nickname with a New Zealand bird?', 'Milline väike pruun karvane vili on seest erkroheline ning jagab nime Uus-Meremaa linnuga?', 'Kiwifruit', 'kiivi', 'kiwi fruit|kiwi', 'kiivivili', 'Kiwifruit was given its commercial name after New Zealand’s kiwi bird.', 'Kiivivili sai oma kaubandusliku nime Uus-Meremaa kiivilinnu järgi.', 'Kiwifruit', 'Kiwifruit'],
      ['strawberry-seeds-outside', 'fruit:strawberry', 'Which red fruit appears to carry its tiny seeds on the outside?', 'Millise punase vilja pinnal paistavad olevat väikesed seemned?', 'Strawberry', 'maasikas', 'strawberries', 'aedmaasikas|maasikad', 'The visible specks on a strawberry are small fruits called achenes.', 'Maasika pinnal nähtavad täpikesed on väikesed viljad, mida nimetatakse pähklikesteks.', 'Strawberry', 'Strawberry'],
      ['avocado-single-stone', 'fruit:avocado', 'Which creamy green fruit has one large stone and is the base of guacamole?', 'Millisel kreemja rohelise viljal on üks suur luuseeme ning sellest valmistatakse guacamole’t?', 'Avocado', 'avokaado', 'avocado pear', 'avokaadovili', 'Avocado flesh surrounds one large seed and is mashed for guacamole.', 'Avokaado viljaliha ümbritseb üht suurt seemet ning seda tambitakse guacamole valmistamiseks.', 'Avocado', 'Avocado'],
      ['fig-flowers-inside', 'fruit:fig', 'Which soft fruit hides many tiny flowers inside the structure that later becomes the part we eat?', 'Millise pehme vilja paljud pisikesed õied peituvad selle osa sees, mida hiljem sööme?', 'Fig', 'viigimari', 'common fig', 'viigivili|viigipuu vili', 'A fig’s enclosed flower structure develops into the fleshy multiple fruit we eat.', 'Viigimarja suletud õisik areneb lihakaks koguviljaks, mida sööme.', 'Fig', 'Fig'],
    ],
  ),
  category(
    'built-in-food-drink-set-005',
    '09-food-drink',
    'Pantry Staples on the Plate',
    'Sahvrivarud taldrikul',
    [
      ['rice-steamed-grain', 'food:rice', 'Which grain is commonly steamed or boiled and serves as a staple for billions of people?', 'Millist teravilja tavaliselt aurutatakse või keedetakse ning mida söövad põhitoiduna miljardid inimesed?', 'Rice', 'riis', 'cooked rice', 'keedetud riis', 'Rice is a cereal grain cooked as a staple food across much of the world.', 'Riis on teravili, mida süüakse suurel osal maailmast keedetud põhitoiduna.', 'Rice', 'Rice'],
      ['pasta-durum-wheat', 'food:pasta', 'Which family of foods includes spaghetti and penne and is often made from durum wheat?', 'Millisesse toiduperesse kuuluvad spagetid ja penne ning mida valmistatakse sageli kõvanisust?', 'Pasta', 'pasta', 'Italian pasta', 'pastatooted|makaronitooted', 'Many dried pasta shapes are made from durum-wheat semolina and water.', 'Paljud kuivatatud pastavormid valmistatakse kõvanisu mannast ja veest.', 'Pasta', 'Pasta'],
      ['lentils-pulse', 'food:lentils', 'Which small lens-shaped pulses may be green, brown, red, or black?', 'Millised väikesed läätsekujulised kaunviljad võivad olla rohelised, pruunid, punased või mustad?', 'Lentils', 'läätsed', 'lentil', 'lääts', 'Lentils are edible pulse seeds that come in several colours and cook without soaking.', 'Läätsed on eri värvi söödavad kaunviljaseemned, mida saab keeta ilma eelneva leotamiseta.', 'Lentil', 'Lentil'],
      ['couscous-semolina-granules', 'food:couscous', 'Which North African staple consists of tiny steamed granules traditionally made from semolina?', 'Milline Põhja-Aafrika põhitoit koosneb väikestest aurutatud terakestest, mida tehakse traditsiooniliselt mannast?', 'Couscous', 'kuskuss', 'cous cous', 'kuskus', 'Couscous is made by rolling moistened semolina into small granules and steaming them.', 'Kuskussi valmistamiseks veeretatakse niisutatud manna väikesteks teradeks ja aurutatakse.', 'Couscous', 'Couscous'],
      ['bulgur-parboiled-wheat', 'food:bulgur', 'Which quick-cooking grain consists of cracked wheat that has already been parboiled and dried?', 'Milline kiiresti valmiv teravili koosneb eelkeedetud, kuivatatud ja purustatud nisuteradest?', 'Bulgur', 'bulgur', 'bulgur wheat|burghul', 'bulgurnisu|purustatud eelküpsetatud nisu', 'Bulgur is made from wheat groats that are parboiled, dried, and cracked.', 'Bulgur valmistatakse nisuteradest, mis eelkeedetakse, kuivatatakse ja purustatakse.', 'Bulgur', 'Bulgur'],
    ],
  ),
  category(
    'built-in-food-drink-set-006',
    '09-food-drink',
    'Small Ingredients, Big Flavour',
    'Väikesed lisandid, suur maitse',
    [
      ['lemon-zest-aromatic-peel', 'ingredient:lemon-zest', 'What brightly coloured part of a lemon is grated to add citrus aroma without much juice?', 'Millist sidruni erksavärvilist osa riivitakse, et lisada toidule tsitruselõhna ilma rohke mahlata?', 'Lemon zest', 'sidrunikoor', 'lemon peel|zest', 'riivitud sidrunikoor|sidruni koor', 'Lemon zest is the aromatic outer layer of the peel.', 'Sidrunikoorena kasutatav zest on koore aromaatne välimine kiht.', 'Zest (ingredient)', 'Zest_(ingredient)'],
      ['soy-sauce-umami', 'ingredient:soy-sauce', 'Which dark fermented seasoning adds salty umami flavour to stir-fries and sushi?', 'Milline tume kääritatud maitseaine lisab vokiroogadele ja sushile soolast umami maitset?', 'Soy sauce', 'sojakaste', 'shoyu', 'soja kaste', 'Soy sauce is a fermented liquid seasoning made chiefly from soybeans and wheat.', 'Sojakaste on peamiselt sojaubadest ja nisust valmistatud kääritatud vedel maitseaine.', 'Soy sauce', 'Soy_sauce'],
      ['sesame-oil-toasted-aroma', 'ingredient:toasted-sesame-oil', 'Which fragrant oil made from toasted seeds is often drizzled over an Asian dish near the end of cooking?', 'Millist röstitud seemnetest valmistatud lõhnavat õli niristatakse Aasia roale sageli küpsetamise lõpus?', 'Sesame oil', 'seesamiõli', 'toasted sesame oil', 'röstitud seesamiõli|seesami õli', 'Toasted sesame oil has a strong nutty aroma and is commonly used as a finishing flavour.', 'Röstitud seesamiõlil on tugev pähkline lõhn ning seda kasutatakse sageli roa viimistlemiseks.', 'Sesame oil', 'Sesame_oil'],
      ['capers-pickled-flower-buds', 'ingredient:capers', 'Which small pickled flower buds add a sharp salty bite to dishes such as puttanesca?', 'Millised väikesed marineeritud õienupud annavad näiteks puttanesca-kastmele teravalt soolaka maitse?', 'Capers', 'kapparid', 'caper buds', 'kapparinupud', 'Capers are unopened flower buds preserved in salt or brine.', 'Kapparid on avanemata õienupud, mida säilitatakse soolas või soolvees.', 'Caper', 'Caper'],
      ['harissa-chilli-paste', 'ingredient:harissa', 'Which North African red chilli paste adds heat with peppers, garlic, and aromatic spices?', 'Milline Põhja-Aafrika punane tšillipasta lisab teravust paprika, küüslaugu ja aromaatsete vürtsidega?', 'Harissa', 'harissa', 'harissa paste', 'harissapasta', 'Harissa is a North African chilli paste seasoned with garlic and spices.', 'Harissa on Põhja-Aafrika tšillipasta, mida maitsestatakse küüslaugu ja vürtsidega.', 'Harissa', 'Harissa'],
    ],
  ),
  category(
    'built-in-food-drink-set-007',
    '09-food-drink',
    'Kitchen Rescue Missions',
    'Köögi päästeoperatsioonid',
    [
      ['lid-smothers-pan-fire', 'object:pan-lid', 'What simple cover can smother a small pan fire by cutting off its oxygen?', 'Milline lihtne kate võib väikese pannipõlengu lämmatada, katkestades hapniku juurdepääsu?', 'Lid', 'kaas', 'pan lid|metal lid', 'pannikaan|metallkaas', 'A fitted lid can exclude oxygen from a small contained cooking fire.', 'Sobiv kaas võib katkestada väikese piiratud toidupõlengu hapnikuvarustuse.', 'Fire safety', 'Fire_safety'],
      ['timer-remembers-the-oven', 'tool:kitchen-timer', 'Which small alarm remembers when the biscuits should come out of the oven?', 'Milline väike alarm tuletab meelde, millal tuleb küpsised ahjust välja võtta?', 'Kitchen timer', 'köögitaimer', 'timer|cooking timer', 'taimer|munakell', 'A kitchen timer sounds after a chosen interval so a cook need not watch the clock.', 'Köögitaimer annab valitud aja möödudes märku, nii et kokk ei pea kella jälgima.', 'Timer', 'Timer'],
      ['ice-bath-stops-cooking', 'technique:ice-bath', 'What bowl of very cold water quickly stops green vegetables cooking after blanching?', 'Milline väga külma vee kauss peatab roheliste köögiviljade küpsemise kohe pärast blanšeerimist?', 'Ice bath', 'jäävann', 'iced-water bath|ice water', 'jäävesi|külm veevann', 'An ice bath cools blanched food rapidly and limits further cooking.', 'Jäävann jahutab blanšeeritud toidu kiiresti ning peatab edasise küpsemise.', 'Ice bath', 'Ice_bath'],
      ['slurry-thickens-sauce', 'technique:starch-slurry', 'What smooth mixture of starch and cold liquid can rescue a sauce that is too thin?', 'Milline tärklise ja külma vedeliku ühtlane segu aitab päästa liiga vedela kastme?', 'Slurry', 'tärklisesegu', 'cornstarch slurry|starch slurry', 'tärkliselört|maisitärklise segu', 'Starch dispersed in cold liquid can thicken a hot sauce without forming dry lumps.', 'Külmas vedelikus hajutatud tärklis paksendab kuuma kastet kuivade klompideta.', 'Starch gelatinization', 'Starch_gelatinization'],
      ['deglazing-lifts-browned-bits', 'technique:deglazing', 'What technique adds liquid to a hot pan and loosens its flavourful browned bits into a sauce?', 'Millise võtte puhul lisatakse kuumale pannile vedelikku ning lahustatakse pruunistunud maitsekad osakesed kastmesse?', 'Deglazing', 'deglaseerimine', 'deglaze|pan deglazing', 'panni deglaseerimine|pannijääkide lahustamine', 'Deglazing dissolves browned pan residue so it can flavour a sauce.', 'Deglaseerimine lahustab pannile pruunistunud jäägid, et need annaksid kastmele maitset.', 'Deglazing (cooking)', 'Deglazing_(cooking)'],
    ],
  ),
  category(
    'built-in-food-drink-set-008',
    '09-food-drink',
    'Desserts from Oven, Fridge, and Fryer',
    'Magustoidud ahjust, külmikust ja fritüürist',
    [
      ['brownie-chocolate-square', 'dessert:brownie', 'Which dense chocolate bake is commonly cut into small squares?', 'Milline tihke šokolaadiküpsetis lõigatakse tavaliselt väikesteks ruutudeks?', 'Brownie', 'brownie', 'chocolate brownie', 'šokolaadibrownie|brownie-kook', 'A brownie is a dense chocolate bake usually served as a square or bar.', 'Brownie on tihke šokolaadiküpsetis, mida serveeritakse tavaliselt ruudu või batoonina.', 'Chocolate brownie', 'Chocolate_brownie'],
      ['meringue-whipped-egg-whites', 'dessert:meringue', 'Which light sweet is made by whipping egg whites with sugar before drying or baking it?', 'Milline kerge maius valmib munavalgeid suhkruga vahustades ning seejärel kuivatades või küpsetades?', 'Meringue', 'besee', 'meringue shell', 'beseeküpsis', 'Meringue is a sweet foam made by whipping egg whites and sugar.', 'Besee on munavalgete ja suhkru vahustamisel saadud magus vaht.', 'Meringue', 'Meringue'],
      ['churros-fried-dough', 'dessert:churros', 'Which ridged sticks of fried dough are often rolled in cinnamon sugar and served with chocolate?', 'Milliseid soonilisi praetud tainapulki veeretatakse sageli kaneelisuhkrus ja serveeritakse šokolaadiga?', 'Churros', 'tšurrod', 'churro', 'churro|tšurro', 'Churros are piped lengths of dough fried until crisp and commonly dusted with sugar.', 'Tšurrod on pritsitud tainaribad, mis praetakse krõbedaks ja kaetakse sageli suhkruga.', 'Churro', 'Churros'],
      ['panna-cotta-set-cream', 'dessert:panna-cotta', 'Which Italian dessert sets sweetened cream with gelatine and is served chilled?', 'Milline Itaalia magustoit valmistatakse želatiiniga tardunud magusast koorest ja serveeritakse külmalt?', 'Panna cotta', 'panna cotta', 'pannacotta', 'pannacotta|kooretarretis', 'Panna cotta is sweetened cream set with gelatine in a mould or serving glass.', 'Panna cotta on vormis või serveerimisklaasis želatiiniga tardunud magus koor.', 'Panna cotta', 'Panna_cotta'],
      ['profiterole-cream-puff', 'dessert:profiterole', 'Which small choux-pastry ball is filled with cream and often covered with chocolate sauce?', 'Milline väike keedutainapall täidetakse koorekreemiga ja kaetakse sageli šokolaadikastmega?', 'Profiterole', 'profitrool', 'cream puff|profiteroles', 'profitroolid|täidetud tuuletasku', 'A profiterole is a filled choux-pastry ball, commonly served with chocolate sauce.', 'Profitrool on täidetud keedutainapall, mida serveeritakse sageli šokolaadikastmega.', 'Profiterole', 'Profiterole'],
    ],
  ),
  category(
    'built-in-technology-inventions-set-001',
    '10-technology-inventions',
    'Quirky Firsts of the Digital Age',
    'Digiajastu kummalised esimesed sammud',
    [
      ['first-sms-merry-christmas', 'message:first-sms-greeting', 'Which two-word festive greeting appeared in the first SMS sent to a mobile phone?', 'Milline ingliskeelne kahesõnaline jõulutervitus oli esimeses mobiiltelefonile saadetud SMS-is?', 'Merry Christmas', 'Merry Christmas', 'Merry Xmas', 'Häid jõule|Merry Xmas', 'Engineer Neil Papworth sent the message “Merry Christmas” from a computer to a mobile phone.', 'Insener Neil Papworth saatis arvutist mobiiltelefonile sõnumi „Merry Christmas“.', 'Text messaging', 'Text_messaging'],
      ['first-youtube-me-at-zoo', 'work:first-youtube-video', 'What is the title of the first video uploaded to YouTube, filmed beside elephants?', 'Mis on YouTube’i esimese, elevantide juures filmitud video pealkiri?', 'Me at the zoo', 'Me at the zoo', 'Me at the Zoo', 'Mina loomaaias|Me at the Zoo', 'YouTube co-founder Jawed Karim appeared in the short upload “Me at the zoo”.', 'YouTube’i kaasasutaja Jawed Karim astus üles lühivideos „Me at the zoo“.', 'Me at the zoo', 'Me_at_the_zoo'],
      ['first-mouse-wooden-shell', 'material:first-computer-mouse-shell', 'Douglas Engelbart’s early computer mouse had its outer case made from which familiar material?', 'Millisest tuttavast materjalist oli valmistatud Douglas Engelbarti varase arvutihiire väliskest?', 'Wood', 'puit', 'wooden case|wooden shell', 'puidust kest|puukest', 'Engelbart’s prototype mouse used a small wooden case around its wheels and electronics.', 'Engelbarti hiire prototüübil oli rataste ja elektroonika ümber väike puidust kest.', 'Douglas Engelbart', 'Douglas_Engelbart'],
      ['first-webcam-coffee-pot', 'object:trojan-room-coffee-pot', 'The first famous webcam watched which shared office object at the University of Cambridge?', 'Millist ühist kontorieset jälgis Cambridge’i ülikooli kuulus esimene veebikaamera?', 'A coffee pot', 'kohvikann', 'coffee pot|coffee machine', 'kohvimasin|kohvikann', 'The Trojan Room camera let researchers check whether their communal coffee pot was empty.', 'Trojan Roomi kaamera võimaldas teadlastel kontrollida, kas ühine kohvikann oli tühi.', 'Trojan Room coffee pot', 'Trojan_Room_coffee_pot'],
      ['first-com-domain-symbolics', 'website:first-dot-com-domain', 'Which name followed by “.com” became the first registered domain with that ending?', 'Milline nimi koos lõpuga „.com“ sai esimeseks registreeritud selle lõpuga domeeniks?', 'Symbolics.com', 'Symbolics.com', 'Symbolics', 'Symbolics', 'Computer maker Symbolics registered Symbolics.com as the first dot-com domain.', 'Arvutitootja Symbolics registreeris esimese .com-domeenina aadressi Symbolics.com.', 'Symbolics', 'Symbolics'],
    ],
  ),
  category(
    'built-in-technology-inventions-set-002',
    '10-technology-inventions',
    'Tech Names with Backstories',
    'Tehnikanimede tagamaad',
    [
      ['google-name-googol', 'brand:google-name', 'Which search company took a name resembling “googol”, the mathematical word for an enormous number?', 'Milline otsingufirma sai nime, mis meenutab tohutut arvu tähistavat matemaatikasõna „googol“?', 'Google', 'Google', 'Google Search', 'Google’i otsing', 'Google’s name is a play on “googol”, reflecting the ambition to organise a vast amount of information.', 'Google’i nimi mängib sõnaga „googol“ ja viitab soovile korrastada tohutut infohulka.', 'Google', 'Google'],
      ['python-name-monty-python', 'language:python-name', 'Which programming language did Guido van Rossum name after a British comedy group rather than a snake?', 'Millise programmeerimiskeele nimetas Guido van Rossum Briti komöödiarühma, mitte mao järgi?', 'Python', 'Python', 'Python programming language', 'Pythoni programmeerimiskeel', 'Creator Guido van Rossum chose Python’s name while reading scripts from Monty Python’s Flying Circus.', 'Looja Guido van Rossum valis Pythoni nime, lugedes sarja „Monty Python’s Flying Circus“ käsikirju.', 'Python (programming language)', 'Python_(programming_language)'],
      ['java-name-coffee', 'language:java-name', 'Which programming language has both the name and a steaming-cup logo associated with coffee?', 'Millise programmeerimiskeele nimi ja aurava tassi logo seostuvad kohviga?', 'Java', 'Java', 'Java programming language', 'Java programmeerimiskeel', 'Java was named after coffee, and a steaming cup became its familiar logo.', 'Java sai nime kohvi järgi ning selle tuntud logoks kujunes aurav tass.', 'Java (programming language)', 'Java_(programming_language)'],
      ['macintosh-name-apple-cultivar', 'computer:macintosh-name', 'Which Apple computer family was named after the McIntosh variety of apple?', 'Milline Apple’i arvutipere sai nime McIntoshi õunasordi järgi?', 'Macintosh', 'Macintosh', 'Apple Macintosh|Mac', 'Apple Macintosh|Mac', 'Apple employee Jef Raskin named the Macintosh project after his favourite apple cultivar.', 'Apple’i töötaja Jef Raskin nimetas Macintoshi projekti oma lemmikõunasordi järgi.', 'Macintosh', 'Macintosh'],
      ['adobe-name-creek', 'brand:adobe-name', 'Which software company was named after a creek running behind co-founder John Warnock’s home?', 'Milline tarkvarafirma sai nime kaasasutaja John Warnocki kodu taga voolanud oja järgi?', 'Adobe', 'Adobe', 'Adobe Inc.|Adobe Systems', 'Adobe Inc.|Adobe Systems', 'Adobe took its name from Adobe Creek in California.', 'Adobe sai nime Californias asuva Adobe Creeki järgi.', 'Adobe Inc.', 'Adobe_Inc.'],
    ],
  ),
  category(
    'built-in-technology-inventions-set-003',
    '10-technology-inventions',
    'Moving Words and Pictures Between Paper and Screen',
    'Sõnade ja piltide liikumine paberi ning ekraani vahel',
    [
      ['printer-puts-ink-paper', 'device:printer', 'Which device produces a paper copy of a digital document?', 'Milline seade valmistab digitaalsest dokumendist paberkoopia?', 'Printer', 'printer', 'computer printer', 'arvutiprinter', 'A printer transfers text or images from digital data onto paper or another medium.', 'Printer kannab digitaalsed tekstid või pildid paberile või muule kandjale.', 'Printer (computing)', 'Printer_(computing)'],
      ['stylus-writes-on-screen', 'device:stylus', 'Which pen-shaped tool lets you write or draw directly on a tablet screen?', 'Millise pliiatsikujulise vahendiga saab tahvelarvuti ekraanile otse kirjutada või joonistada?', 'Stylus', 'puutepliiats', 'digital pen|tablet pen', 'digipliiats|tahvlipliiats', 'A stylus gives a touchscreen a precise pen-like input point.', 'Puutepliiats annab puuteekraanil täpse pliiatsitaolise sisestuspunkti.', 'Stylus (computing)', 'Stylus_(computing)'],
      ['photocopier-duplicates-page', 'device:photocopier', 'Which office machine makes another paper copy of an existing page without needing its digital file?', 'Milline kontorimasin teeb olemasolevast paberlehest uue koopia ilma digifaili vajamata?', 'Photocopier', 'koopiamasin', 'copy machine|copier', 'paljundusmasin|kopeerimismasin', 'A photocopier photographs a document and reproduces its image on another sheet.', 'Koopiamasin loeb dokumendi kujutise ning kannab selle teisele paberilehele.', 'Photocopier', 'Photocopier'],
      ['document-camera-projects-page', 'device:document-camera', 'Which overhead camera shows a book page or small object live on a classroom screen?', 'Milline ülalt suunatud kaamera näitab raamatu lehte või väikest eset klassiruumi ekraanil otseülekandena?', 'Document camera', 'dokumendikaamera', 'visual presenter|visualiser', 'esitluskaamera|dokumendiesitleja', 'A document camera sends a live image of material placed beneath its lens to a display.', 'Dokumendikaamera edastab objektiivi alla asetatud materjali otsepildi ekraanile.', 'Document camera', 'Document_camera'],
      ['electronic-paper-holds-image', 'technology:electronic-paper', 'Which display technology imitates ink on paper and can keep an image while using almost no power?', 'Milline ekraanitehnoloogia jäljendab tinti paberil ning suudab pilti hoida peaaegu elektrit kulutamata?', 'Electronic paper', 'elektrooniline paber', 'e-paper|electronic ink', 'e-paber|elektrooniline tint', 'Electronic paper reflects ambient light and many versions need power mainly when the image changes.', 'Elektrooniline paber peegeldab ümbritsevat valgust ning paljud lahendused vajavad energiat peamiselt pildi muutmisel.', 'Electronic paper', 'Electronic_paper'],
    ],
  ),
  category(
    'built-in-technology-inventions-set-004',
    '10-technology-inventions',
    'Small Inventions, Everyday Convenience',
    'Väikesed leiutised, igapäevane mugavus',
    [
      ['zipper-interlocking-teeth', 'invention:zipper', 'Which fastener closes clothing or a bag by joining two rows of small teeth?', 'Milline kinnis sulgeb rõiva või koti, ühendades kaks rida väikeseid hambaid?', 'Zipper', 'tõmblukk', 'zip fastener', 'lukk|tõmbelukk', 'A zipper slider brings two rows of interlocking teeth together or separates them.', 'Tõmbluku kelk ühendab kaks hambarida või tõmbab need lahku.', 'Zipper', 'Zipper'],
      ['clothespin-grips-laundry', 'invention:clothespin', 'Which spring-loaded clip grips wet laundry to a clothesline?', 'Milline vedruga klamber hoiab märga pesu pesunööril?', 'Clothespin', 'pesulõks', 'clothes peg|clothes pin', 'pesuklamber|pesupulk', 'A clothespin clamps fabric to a line so wind does not carry it away.', 'Pesulõks kinnitab kanga nöörile, et tuul seda minema ei viiks.', 'Clothespin', 'Clothespin'],
      ['safety-pin-covered-point', 'invention:safety-pin', 'Which fastening pin hides its sharp point inside a clasp when closed?', 'Millise kinnitusnõela terav ots peitub sulgemisel kaitsvasse lukku?', 'Safety pin', 'haaknõel', 'safety-pin', 'kaitsenõel', 'A safety pin bends into a spring and locks its point beneath a protective clasp.', 'Haaknõel toimib vedruna ning lukustab terava otsa kaitsva kinnise alla.', 'Safety pin', 'Safety_pin'],
      ['vacuum-flask-insulates-drink', 'invention:vacuum-flask', 'Which double-walled bottle keeps a drink hot or cold by placing a near-vacuum between its walls?', 'Milline kahekordse seinaga pudel hoiab joogi kuuma või külmana, sest seinte vahel on peaaegu vaakum?', 'Vacuum flask', 'termospudel', 'thermos|insulated flask', 'termos|vaakumpudel', 'A vacuum flask reduces heat transfer through the evacuated space between its walls.', 'Termospudel vähendab soojusülekannet seinte vahel oleva hõrendatud ruumi abil.', 'Vacuum flask', 'Vacuum_flask'],
      ['barcode-optical-data', 'invention:barcode', 'Which machine-readable pattern of bars and spaces identifies products at a checkout?', 'Milline masinloetav vöötide ja vahede muster tuvastab toote kassas?', 'Barcode', 'vöötkood', 'bar code|linear barcode', 'ribakood|joonvöötkood', 'A barcode encodes an identifier in widths and gaps that an optical reader can scan.', 'Vöötkood kodeerib tunnuse vöötide laiustesse ja vahedesse, mida optiline lugeja skannib.', 'Barcode', 'Barcode'],
    ],
  ),
  category(
    'built-in-technology-inventions-set-005',
    '10-technology-inventions',
    'How Gadgets Capture Sound and Pictures',
    'Kuidas seadmed heli ja pilti jäädvustavad',
    [
      ['microphone-sound-to-signal', 'device:microphone', 'Which device does the reverse of a speaker by turning sound into an electrical signal?', 'Milline seade teeb kõlariga võrreldes vastupidist tööd ning muudab heli elektrisignaaliks?', 'Microphone', 'mikrofon', 'mic', 'mikk', 'A microphone converts sound-wave motion into an electrical or digital signal.', 'Mikrofon muudab helilaine liikumise elektriliseks või digitaalseks signaaliks.', 'Microphone', 'Microphone'],
      ['viewfinder-frames-picture', 'device:camera-viewfinder', 'Which small window lets a photographer frame the scene before pressing the shutter?', 'Milline väike aken aitab fotograafil enne päästikule vajutamist kaadrit paika seada?', 'Viewfinder', 'pildiotsija', 'camera viewfinder', 'kaamera pildiotsija|kaadriotsija', 'A viewfinder shows the photographer the scene and boundaries that the camera will record.', 'Pildiotsija näitab fotograafile stseeni ja kaadri piire, mille kaamera salvestab.', 'Viewfinder', 'Viewfinder'],
      ['pop-filter-softens-plosives', 'device:microphone-pop-filter', 'Which mesh screen between a singer and microphone softens bursts from sounds such as P and B?', 'Milline laulja ja mikrofoni vahele asetatud võrkketas pehmendab P- ja B-häälikute õhupahvakuid?', 'Pop filter', 'popfilter', 'pop shield|microphone pop filter', 'mikrofoni popfilter|pop-filter', 'A pop filter disperses fast-moving breath before it strikes the microphone diaphragm.', 'Popfilter hajutab kiire õhuvoolu enne selle jõudmist mikrofoni membraanini.', 'Pop filter', 'Pop_filter'],
      ['image-stabilisation-counters-shake', 'technology:image-stabilisation', 'Which camera feature moves a lens element or sensor to counter small hand movements?', 'Milline kaamerafunktsioon liigutab läätseosa või sensorit, et tasakaalustada käe väikest värinat?', 'Image stabilisation', 'pildistabilisaator', 'image stabilization|optical stabilisation', 'pildistabiliseerimine|optiline stabilisaator', 'Image stabilisation compensates for camera movement during exposure.', 'Pildistabilisaator kompenseerib kaamera liikumist särituse ajal.', 'Image stabilization', 'Image_stabilization'],
      ['binaural-recording-two-ears', 'technology:binaural-recording', 'Which recording method places two microphones like human ears to create a three-dimensional headphone effect?', 'Milline salvestusviis paigutab kaks mikrofoni inimese kõrvade sarnaselt, et luua kõrvaklappides ruumiline efekt?', 'Binaural recording', 'binauraalne salvestus', 'binaural audio|dummy-head recording', 'binauraalheli|kunstpea salvestus', 'Binaural recording captures the timing and level differences that reach two ears.', 'Binauraalne salvestus jäädvustab kahe kõrvani jõudva heli aja- ja tugevuserinevused.', 'Binaural recording', 'Binaural_recording'],
    ],
  ),
  category(
    'built-in-technology-inventions-set-006',
    '10-technology-inventions',
    'Accidents That Became Inventions',
    'Leiutisteks saanud juhused',
    [
      ['play-doh-wallpaper-cleaner', 'product:play-doh-origin', 'Which colourful modelling compound began as a cleaner for soot-stained wallpaper?', 'Milline värviline voolimismass alustas tahmase tapeedi puhastusvahendina?', 'Play-Doh', 'Play-Doh', 'Play-Doh modelling compound', 'Play-Doh’ voolimismass', 'The soft compound later sold as Play-Doh was first marketed for cleaning wallpaper.', 'Hiljem Play-Doh’ nime all müüdud pehmet massi turustati algul tapeedi puhastamiseks.', 'Play-Doh', 'Play-Doh'],
      ['bubble-wrap-wallpaper', 'product:bubble-wrap-origin', 'Which poppable packing material was first imagined as textured wallpaper?', 'Millist plõksuvat pakkematerjali kavandati algul reljeefse tapeedina?', 'Bubble wrap', 'mullikile', 'bubble-wrap|air bubble wrap', 'õhumullikile|mullplast', 'Its inventors sealed air bubbles between plastic sheets while experimenting with wallpaper.', 'Leiutajad sulgesid tapeediga katsetades õhumullid plastkilekihtide vahele.', 'Bubble wrap', 'Bubble_wrap'],
      ['slinky-fallen-spring', 'toy:slinky-origin', 'Which walking spring toy was inspired when a naval engineer dropped a tension spring?', 'Milline trepist alla kõndiv vedrumänguasi sai idee mereväeinseneri maha kukkunud pingutusvedrust?', 'Slinky', 'Slinky', 'Slinky toy', 'Slinky vedru|vedrumänguasi Slinky', 'Richard James noticed that a dropped spring stepped through a series of arcs instead of simply falling.', 'Richard James märkas, et maha kukkunud vedru liikus kaarte kaupa edasi, mitte ei langenud lihtsalt maha.', 'Slinky', 'Slinky'],
      ['ice-pop-frozen-drink', 'food:ice-pop-origin', 'Which frozen treat was inspired when a child left a flavoured drink and stirring stick outdoors overnight?', 'Milline külmutatud maius sai alguse sellest, et laps jättis maitsestatud joogi koos segamispulgaga ööseks õue?', 'Ice pop', 'pulgajää', 'ice lolly|Popsicle', 'jääpulk|Popsicle', 'Frank Epperson later developed his accidentally frozen drink into the ice pop sold as the Popsicle.', 'Frank Epperson arendas juhuslikult külmunud joogist hiljem pulgajää, mida müüdi Popsicle’i nime all.', 'Popsicle', 'Popsicle'],
      ['super-glue-too-sticky', 'invention:super-glue-origin', 'Which powerful adhesive was initially rejected during research because it stuck to nearly everything?', 'Milline tugev liim jäeti uurimistöös algul kõrvale, sest see kleepus peaaegu kõige külge?', 'Super Glue', 'superliim', 'superglue|cyanoacrylate glue', 'kiirliim|tsüanoakrülaatliim', 'Cyanoacrylate was encountered during materials research and later marketed as Super Glue.', 'Tsüanoakrülaati märgati materjaliuuringutes ning hiljem hakati seda müüma superliimina.', 'Cyanoacrylate', 'Cyanoacrylate'],
    ],
  ),
  category(
    'built-in-technology-inventions-set-007',
    '10-technology-inventions',
    'Landmark Inventions at Work',
    'Murrangulised leiutised tegutsemas',
    [
      ['umbrella-folding-canopy', 'invention:umbrella', 'Which folding canopy carried on a handle protects a person from rain or strong sun?', 'Milline varre otsas kantav kokkupandav kuppel kaitseb inimest vihma või tugeva päikese eest?', 'Umbrella', 'vihmavari', 'rain umbrella|parasol', 'päikesevari|vihmakate', 'An umbrella spreads a fabric canopy over folding ribs to shelter its user.', 'Vihmavari pingutab riidest kupli kokkupandavate ribide peale ning pakub kasutajale varju.', 'Umbrella', 'Umbrella'],
      ['eyeglasses-correct-vision', 'invention:eyeglasses', 'Which wearable invention places corrective lenses in front of the eyes?', 'Milline kantav leiutis asetab nägemist korrigeerivad läätsed silmade ette?', 'Eyeglasses', 'prillid', 'glasses|spectacles', 'nägemisprillid|silmaprillid', 'Eyeglasses hold lenses that correct or protect a wearer’s vision.', 'Prillid hoiavad silmade ees nägemist korrigeerivaid või kaitsvaid läätsi.', 'Glasses', 'Glasses'],
      ['sewing-machine-mechanises-stitches', 'invention:sewing-machine', 'Which machine joins fabric by forming stitches much faster than sewing by hand?', 'Milline masin ühendab kanga pisteid tehes palju kiiremini kui käsitsi õmmeldes?', 'Sewing machine', 'õmblusmasin', 'sewing-machine', 'õmblusmasin', 'A sewing machine mechanically interlocks thread to make repeated stitches in fabric.', 'Õmblusmasin seob niidi mehaaniliselt korduvateks pisteteks kangas.', 'Sewing machine', 'Sewing_machine'],
      ['anaesthesia-blocks-surgical-pain', 'invention:anaesthesia', 'Which medical advance lets surgery take place without the patient feeling the operation?', 'Milline meditsiiniline edusamm võimaldab teha operatsiooni nii, et patsient seda ei tunne?', 'Anaesthesia', 'anesteesia', 'anesthesia|general anaesthesia', 'narkoos|tuimastus', 'Anaesthesia uses medicines to prevent sensation, awareness, or both during a procedure.', 'Anesteesia kasutab ravimeid, et vältida protseduuri ajal aistinguid, teadvuselolekut või mõlemat.', 'History of general anesthesia', 'History_of_general_anesthesia'],
      ['volvo-three-point-seat-belt', 'organization:volvo-seat-belt', 'Which Swedish car company introduced the modern three-point seat belt and allowed other manufacturers to use the design?', 'Milline Rootsi autofirma võttis kasutusele tänapäevase kolmepunktiturvavöö ning lubas ka teistel tootjatel seda lahendust kasutada?', 'Volvo', 'Volvo', 'Volvo Cars', 'Volvo Cars|Volvo autotehas', 'Volvo engineer Nils Bohlin developed the three-point belt, and the company made the patent available for wider safety use.', 'Volvo insener Nils Bohlin töötas välja kolmepunktiturvavöö ning ettevõte lubas patenti liiklusohutuse huvides laialt kasutada.', 'Seat belt', 'Seat_belt'],
    ],
  ),
  category(
    'built-in-technology-inventions-set-008',
    '10-technology-inventions',
    'Safer Habits in Digital Life',
    'Turvalisemad harjumused digielus',
    [
      ['screen-lock-blocks-access', 'security:screen-lock', 'Which phone feature asks for a code, pattern, or biometric before showing your apps?', 'Milline telefonifunktsioon küsib enne rakenduste näitamist koodi, mustrit või biomeetrilist tunnust?', 'Screen lock', 'ekraanilukk', 'device lock|lock screen', 'seadmelukk|lukustuskuva', 'A screen lock blocks ordinary access until the user proves their identity.', 'Ekraanilukk takistab tavakasutust, kuni kasutaja oma isiku tõendab.', 'Lock screen', 'Lock_screen'],
      ['app-permissions-limit-access', 'security:app-permissions', 'What settings decide whether an app may use your camera, microphone, or location?', 'Millised seaded määravad, kas rakendus tohib kasutada kaamerat, mikrofoni või asukohta?', 'App permissions', 'rakenduse õigused', 'application permissions|permissions', 'rakenduse load|juurdepääsuõigused', 'App permissions limit which protected device features and data an application can access.', 'Rakenduse õigused piiravad, millistele kaitstud seadmefunktsioonidele ja andmetele rakendus ligi pääseb.', 'Application permissions', 'Application_permissions'],
      ['passkey-passwordless-login', 'security:passkey', 'Which newer login credential uses your device to sign in without sending a reusable password?', 'Milline uuem sisselogimistunnus kasutab seadet ning ei saada teenusele korduvalt kasutatavat parooli?', 'Passkey', 'pääsuvõti', 'pass key', 'digitaalne pääsuvõti|paroolivaba pääsuvõti', 'A passkey uses public-key cryptography and keeps the private credential on a user-controlled device.', 'Pääsuvõti kasutab avaliku võtme krüptograafiat ning hoiab salajase tunnuse kasutaja seadmes.', 'Passkey (authentication)', 'Passkey_(authentication)'],
      ['hardware-security-key-physical', 'security:hardware-security-key', 'Which small physical key can prove your identity to a website when inserted or tapped?', 'Milline väike füüsiline võti saab veebisaidile kasutaja isikut tõendada, kui see ühendada või vastu seadet puudutada?', 'Hardware security key', 'riistvaraline turvavõti', 'security key|authentication key', 'turvavõti|autentimisvõti', 'A hardware security key stores a cryptographic credential in a separate physical device.', 'Riistvaraline turvavõti hoiab krüptograafilist tunnust eraldi füüsilises seadmes.', 'Security token', 'Security_token'],
      ['end-to-end-encryption', 'security:end-to-end-encryption', 'Which protection lets only the communicating users, not the message service, read the content?', 'Milline kaitse võimaldab sõnumi sisu lugeda ainult suhtlejatel, mitte sõnumiteenusel?', 'End-to-end encryption', 'otspunktkrüpteerimine', 'E2EE|end to end encryption', 'läbivkrüpteerimine|E2EE', 'End-to-end encryption keeps plaintext available only at the communicating endpoints.', 'Otspunktkrüpteerimine jätab loetava teksti kättesaadavaks ainult suhtluse otspunktides.', 'End-to-end encryption', 'End-to-end_encryption'],
    ],
  ),
  category(
    'built-in-politics-economics-society-set-001',
    '11-politics-economics-society',
    'People Who Opened Doors',
    'Inimesed, kes avasid uksi',
    [
      ['braille-raised-dots', 'person:louis-braille', 'Which French teenager gave his name to the raised-dot reading system used by blind people?', 'Milline prantsuse teismeline andis nime pimedate kasutatavale reljeefsete punktidega kirjasüsteemile?', 'Louis Braille', 'Louis Braille', 'Braille', 'Braille|Louis Braille', 'Louis Braille developed the six-dot tactile writing system while still a teenager.', 'Louis Braille töötas kuuepunktilise kombitava kirjasüsteemi välja juba teismelisena.', 'Louis Braille', 'Louis_Braille'],
      ['lamarr-frequency-hopping', 'person:hedy-lamarr', 'Which Hollywood star also co-invented a frequency-hopping radio system during the Second World War?', 'Milline Hollywoodi täht oli Teise maailmasõja ajal ka sagedushüpetega raadiosüsteemi kaasleiutaja?', 'Hedy Lamarr', 'Hedy Lamarr', 'Lamarr|Hedwig Kiesler', 'Lamarr|Hedwig Kiesler', 'Hedy Lamarr and George Antheil patented a frequency-hopping communication system.', 'Hedy Lamarr ja George Antheil patenteerisid sagedushüpetega sidesüsteemi.', 'Hedy Lamarr', 'Hedy_Lamarr'],
      ['johnson-nasa-trajectories', 'person:katherine-johnson', 'Which mathematician calculated flight paths for NASA and was portrayed in Hidden Figures?', 'Milline matemaatik arvutas NASA lennutrajektoore ning keda kujutati filmis Varjatud arvud?', 'Katherine Johnson', 'Katherine Johnson', 'Johnson|Katherine Goble Johnson', 'Johnson|Katherine Goble Johnson', 'Katherine Johnson calculated trajectories for crewed US space missions.', 'Katherine Johnson arvutas USA mehitatud kosmosemissioonide trajektoore.', 'Katherine Johnson', 'Katherine_Johnson'],
      ['yunus-microcredit', 'person:muhammad-yunus', 'Which Bangladeshi Nobel laureate founded Grameen Bank and popularised tiny loans for people without conventional collateral?', 'Milline Bangladeshi Nobeli laureaat rajas Grameen Banki ning muutis tuntuks väikelaenud inimestele, kellel puudub tavapärane tagatis?', 'Muhammad Yunus', 'Muhammad Yunus', 'Yunus', 'Yunus|Muhammed Yunus', 'Muhammad Yunus and Grameen Bank received the Nobel Peace Prize for advancing microcredit.', 'Muhammad Yunus ja Grameen Bank said mikrokrediidi edendamise eest Nobeli rahupreemia.', 'Muhammad Yunus', 'Muhammad_Yunus'],
      ['maathai-green-belt', 'person:wangari-maathai', 'Which Kenyan Nobel laureate founded the Green Belt Movement, linking women’s community work with tree planting?', 'Milline Kenya Nobeli laureaat rajas Rohelise Vöö Liikumise, ühendades naiste kogukonnatöö puude istutamisega?', 'Wangari Maathai', 'Wangari Maathai', 'Maathai|Wangari Muta Maathai', 'Maathai|Wangari Muta Maathai', 'Wangari Maathai founded a movement that organised Kenyan women to plant trees and protect livelihoods.', 'Wangari Maathai rajas liikumise, mis koondas Kenya naisi puid istutama ja elatusvõimalusi kaitsma.', 'Wangari Maathai', 'Wangari_Maathai'],
    ],
  ),
  category(
    'built-in-politics-economics-society-set-002',
    '11-politics-economics-society',
    'Fortunes in Pop Culture',
    'Varandused popkultuuris',
    [
      ['monopoly-board-game-property', 'work:monopoly-game', 'In which board game do players buy streets, build hotels, and try not to go bankrupt?', 'Millises lauamängus ostavad mängijad tänavaid, ehitavad hotelle ja püüavad pankrotti vältida?', 'Monopoly', 'Monopol', 'Monopoly game', 'Monopoli lauamäng|Monopoly', 'Monopoly centres on buying property, charging rent, and driving opponents into bankruptcy.', 'Monopol keskendub kinnisvara ostmisele, rendi kogumisele ja vastaste pankrotti ajamisele.', 'Monopoly (game)', 'Monopoly_(game)'],
      ['abba-money-money-money', 'work:money-money-money-song', 'Which ABBA song imagines how much easier life might be “in a rich man’s world”?', 'Milline ABBA laul kujutleb, kui palju lihtsam võiks elu olla „rikka mehe maailmas“?', 'Money Money Money', 'Money Money Money', 'Money, Money, Money', 'Money, Money, Money', 'ABBA released “Money, Money, Money” in 1976 on the album Arrival.', 'ABBA avaldas laulu „Money, Money, Money“ 1976. aastal albumil Arrival.', 'Money, Money, Money', 'Money,_Money,_Money'],
      ['scrooge-mcduck-money-bin', 'character:scrooge-mcduck', 'Which Disney duck is famous for diving into the coins in his enormous money bin?', 'Milline Disney part on kuulus selle poolest, et sukeldub oma hiiglasliku rahahoidla müntidesse?', 'Scrooge McDuck', 'Onu Robert', 'Uncle Scrooge', 'Scrooge McDuck|Onu Robert McPart', 'Scrooge McDuck is portrayed as an exceptionally rich businessman with a giant money bin.', 'Onu Robertit kujutatakse äärmiselt rikka ärimehena, kellel on hiiglaslik rahahoidla.', 'Scrooge McDuck', 'Scrooge_McDuck'],
      ['wolf-wall-street-belfort', 'work:wolf-of-wall-street', 'Which film starring Leonardo DiCaprio follows the rise and fall of stockbroker Jordan Belfort?', 'Milline Leonardo DiCaprio film jälgib börsimaakler Jordan Belforti tõusu ja langust?', 'The Wolf of Wall Street', 'Wall Streeti hunt', 'Wolf of Wall Street', 'The Wolf of Wall Street|Wall Streeti hunt', 'The Wolf of Wall Street dramatises Jordan Belfort’s career and financial crimes.', 'Wall Streeti hunt dramatiseerib Jordan Belforti karjääri ja finantskuritegusid.', 'The Wolf of Wall Street (2013 film)', 'The_Wolf_of_Wall_Street_(2013_film)'],
      ['deal-no-deal-briefcases', 'work:deal-or-no-deal', 'Which game show asks a contestant to open numbered briefcases while a banker makes offers?', 'Millises telemängus avab võistleja nummerdatud kohvreid, samal ajal kui pankur teeb pakkumisi?', 'Deal or No Deal', 'Võta või jäta', 'Deal or No Deal game show', 'Deal or No Deal|Võta või jäta', 'Deal or No Deal balances unknown briefcase values against offers from a fictional banker.', 'Võta või jäta vastandab kohvrite tundmatud väärtused väljamõeldud pankuri pakkumistele.', 'Deal or No Deal', 'Deal_or_No_Deal'],
    ],
  ),
  category(
    'built-in-politics-economics-society-set-003',
    '11-politics-economics-society',
    'Places Hiding in Everyday Words',
    'Kohad igapäevasõnade taga',
    [
      ['hamburger-name-hamburg', 'place:hamburg-name-hamburger', 'Which German port city gave its name to the hamburger?', 'Milline Saksamaa sadamalinn andis nime hamburgerile?', 'Hamburg', 'Hamburg', 'Hamburg, Germany', 'Hamburg Saksamaal', 'The hamburger’s name traces through Hamburg steak to the city of Hamburg.', 'Hamburgeri nimi pärineb Hamburgi biifsteegi kaudu Hamburgi linnast.', 'Hamburger', 'Hamburger'],
      ['cologne-fragrance-city', 'place:cologne-fragrance-name', 'Which German city lent its name to a light fragrance whose French name literally means “water of this city”?', 'Milline Saksamaa linn andis nime kergele lõhnaveele, mille prantsuskeelne nimi tähendab sõna-sõnalt „selle linna vett“?', 'Cologne', 'Köln', 'Cologne, Germany', 'Kölni linn|Cologne', 'Eau de Cologne means “water of Cologne” and was created in the city.', 'Eau de Cologne tähendab „Kölni vett“ ning see loodi selles linnas.', 'Eau de Cologne', 'Eau_de_Cologne'],
      ['tuxedo-name-new-york-place', 'place:tuxedo-park-clothing-name', 'Which New York community lent its name to the formal dinner jacket called a tuxedo?', 'Milline New Yorgi osariigi asula andis nime pidulikule õhtupintsakule ehk smokingule?', 'Tuxedo Park', 'Tuxedo Park', 'Tuxedo, New York', 'Tuxedo|Tuxedo Park New Yorgis', 'The dinner jacket became associated with New York’s Tuxedo Club and the surrounding community.', 'Õhtupintsakut hakati seostama New Yorgi Tuxedo Clubi ja seda ümbritseva asulaga.', 'Tuxedo Park, New York', 'Tuxedo_Park,_New_York'],
      ['bikini-name-atoll', 'place:bikini-atoll-name', 'Which Pacific atoll gave its name to the two-piece swimsuit launched soon after nuclear tests there?', 'Milline Vaikse ookeani atoll andis nime kaheosalisele ujumisriidele, mis tuli müügile peagi pärast sealseid tuumakatsetusi?', 'Bikini Atoll', 'Bikini atoll', 'Bikini', 'Bikini|Bikini saared', 'Designer Louis Réard named the swimsuit after Bikini Atoll, expecting a similarly explosive reaction.', 'Disainer Louis Réard nimetas ujumisriide Bikini atolli järgi, oodates sama plahvatuslikku vastukaja.', 'Bikini', 'Bikini'],
      ['denim-name-nimes', 'place:nimes-denim-name', 'Which southern French city hides in the traditional origin story of the word “denim”?', 'Milline Lõuna-Prantsusmaa linn peitub sõna „denim“ traditsioonilises päritoluloos?', 'Nîmes', 'Nîmes', 'Nimes', 'Nimes|Nîmes’i linn', 'The traditional etymology derives denim from “serge de Nîmes”, a fabric associated with Nîmes.', 'Traditsioonilise seletuse järgi pärineb denim väljendist „serge de Nîmes“, mis seostas kanga Nîmes’i linnaga.', 'Denim', 'Denim'],
    ],
  ),
  category(
    'built-in-politics-economics-society-set-004',
    '11-politics-economics-society',
    'Day Jobs of Famous Characters',
    'Kuulsate tegelaste päevatööd',
    [
      ['mario-luigi-plumber-brothers', 'characters:mario-and-luigi-plumbers', 'Which Nintendo brothers are traditionally portrayed as Italian plumbers?', 'Milliseid Nintendo vendi kujutatakse traditsiooniliselt Itaalia päritolu torulukkseppadena?', 'Mario and Luigi', 'Mario ja Luigi', 'the Mario Brothers|Mario Bros.', 'vennad Mario ja Luigi|Mario Bros.', 'Mario and Luigi are the title brothers of Mario Bros. and share the plumbing trade.', 'Mario ja Luigi on „Mario Brosi“ nimitegelastest vennad ning mõlemad on torulukksepad.', 'Mario Bros.', 'Mario_Bros.'],
      ['spongebob-fry-cook', 'occupation:spongebob-fry-cook', 'What is SpongeBob SquarePants’s job at the Krusty Krab?', 'Mis ametit peab Käsna-Kalle restoranis Krusty Krab?', 'Fry cook', 'praekokk', 'cook|short-order cook', 'kokk|restoranikokk', 'SpongeBob works as the Krusty Krab’s enthusiastic fry cook.', 'Käsna-Kalle töötab Krusty Krabis innuka praekokana.', 'SpongeBob SquarePants (character)', 'SpongeBob_SquarePants_(character)'],
      ['indiana-jones-archaeology-professor', 'occupation:indiana-jones-archaeology-professor', 'What university job does Indiana Jones return to between his adventures?', 'Millise ülikoolitöö juurde naaseb Indiana Jones oma seikluste vahel?', 'Archaeology professor', 'arheoloogiaprofessor', 'professor of archaeology|archaeology teacher', 'arheoloogia õppejõud|arheoloogiaprofessor', 'Indiana Jones teaches archaeology at university when he is not pursuing ancient artefacts.', 'Indiana Jones õpetab ülikoolis arheoloogiat, kui ta parajasti muistiseid ei otsi.', 'Indiana Jones', 'Indiana_Jones'],
      ['homer-simpson-safety-inspector', 'occupation:homer-simpson-safety-inspector', 'What safety-related job does Homer Simpson hold at the Springfield Nuclear Power Plant?', 'Millist ohutusega seotud ametit peab Homer Simpson Springfieldi tuumaelektrijaamas?', 'Nuclear safety inspector', 'tuumaohutuse inspektor', 'safety inspector', 'ohutusinspektor|tuumajaama ohutusinspektor', 'Homer is employed as a safety inspector despite his famously careless behaviour.', 'Homer töötab ohutusinspektorina hoolimata oma kurikuulsalt hooletust käitumisest.', 'Homer Simpson', 'Homer_Simpson'],
      ['ross-geller-palaeontologist', 'occupation:ross-geller-palaeontologist', 'What scientific profession does Ross Geller practise in Friends?', 'Millist teadusametit peab Ross Geller sarjas „Sõbrad“?', 'Palaeontologist', 'paleontoloog', 'paleontologist', 'muinasloomade uurija', 'Ross works as a palaeontologist at a museum and later teaches at a university.', 'Ross töötab paleontoloogina muuseumis ning õpetab hiljem ülikoolis.', 'Ross Geller', 'Ross_Geller'],
    ],
  ),
  category(
    'built-in-politics-economics-society-set-005',
    '11-politics-economics-society',
    'Symbols with a Public Message',
    'Avaliku sõnumiga sümbolid',
    [
      ['recycling-symbol-three-arrows', 'symbol:recycling-mobius-loop', 'Which environmental symbol forms a triangular loop from three chasing arrows?', 'Milline keskkonnasümbol moodustab kolmest üksteist jälitavast noolest kolmnurkse ringi?', 'Recycling symbol', 'taaskasutussümbol', 'recycle symbol|Möbius loop', 'ümbertöötlemise sümbol|Möbiuse silmus', 'Gary Anderson designed the three-arrow recycling symbol for a student competition.', 'Gary Anderson kujundas kolme noolega taaskasutussümboli üliõpilasvõistlusele.', 'Recycling symbol', 'Recycling_symbol'],
      ['white-flag-surrender', 'symbol:white-flag', 'Which plain flag is internationally understood as a request to stop fighting and negotiate?', 'Millist ühevärvilist lippu mõistetakse rahvusvaheliselt palvena võitlus peatada ja läbirääkimisi alustada?', 'White flag', 'valge lipp', 'flag of truce|truce flag', 'vaherahulipp|alistumislipp', 'A white flag signals truce, surrender, or a wish to communicate with an opponent.', 'Valge lipp annab märku vaherahust, alistumisest või soovist vastasega suhelda.', 'White flag', 'White_flag'],
      ['skull-crossbones-warning', 'symbol:skull-and-crossbones', 'Which symbol of a human skull above crossed bones warns of poison and also appears on pirate flags?', 'Milline inimkolju ja ristatud sääreluudega sümbol hoiatab mürgi eest ning ilmub ka piraadilippudel?', 'Skull and crossbones', 'pealuu ja ristatud kondid', 'skull-and-crossbones|Jolly Roger symbol', 'kolp ja ristatud sääreluud|piraadimärk', 'The skull and crossbones has served both as a toxicity warning and a pirate emblem.', 'Pealuud ja ristatud konte on kasutatud nii mürgihoiatusena kui ka piraadiembleemina.', 'Skull and crossbones', 'Skull_and_crossbones'],
      ['smiley-harvey-ball', 'symbol:harvey-ball-smiley', 'Which simple yellow face did designer Harvey Ball create to lift employee morale?', 'Millise lihtsa kollase näo lõi disainer Harvey Ball töötajate meeleolu tõstmiseks?', 'Smiley face', 'naerunägu', 'smiley|yellow smiley', 'smail|kollane naerunägu', 'Harvey Ball drew the round yellow smiley for an insurance company’s morale campaign.', 'Harvey Ball joonistas ümara kollase naerunäo kindlustusfirma töötajate moraalikampaania jaoks.', 'Smiley', 'Smiley'],
      ['guy-fawkes-mask-protest', 'symbol:guy-fawkes-mask', 'Which moustached mask from V for Vendetta later appeared at Anonymous and other protests?', 'Milline vuntsidega mask teosest V nagu veritasu ilmus hiljem Anonymous’e ja teiste protestide juures?', 'Guy Fawkes mask', 'Guy Fawkesi mask', 'V for Vendetta mask|Anonymous mask', 'V nagu veritasu mask|Anonymous’e mask', 'The stylised Guy Fawkes mask became a modern protest symbol after V for Vendetta.', 'Stiliseeritud Guy Fawkesi maskist sai pärast teost V nagu veritasu tänapäevane protestisümbol.', 'Guy Fawkes mask', 'Guy_Fawkes_mask'],
    ],
  ),
  category(
    'built-in-politics-economics-society-set-006',
    '11-politics-economics-society',
    'Accessibility in Everyday Culture',
    'Ligipääsetavus igapäevaelus ja kultuuris',
    [
      ['closed-captions-cc-button', 'accessibility:closed-captions-symbol', 'What do the letters CC on a television or video-player button switch on?', 'Mille lülitavad sisse tähed CC teleri või videopleieri nupul?', 'Closed captions', 'vaegkuuljate subtiitrid', 'closed captioning|captions', 'CC-subtiitrid|kinnised subtiitrid', 'Closed captions display dialogue and relevant sounds as text that viewers can turn on or off.', 'Vaegkuuljate subtiitrid kuvavad dialoogi ja olulised helid tekstina, mida vaataja saab sisse või välja lülitada.', 'Closed captioning', 'Closed_captioning'],
      ['guide-dog-intelligent-disobedience', 'accessibility:guide-dog-safety', 'Which assistance animal is trained to refuse a command when obeying would lead its handler into danger?', 'Milline abiloom on õpetatud käsku eirama, kui selle täitmine viiks kasutaja ohtu?', 'Guide dog', 'juhtkoer', 'seeing-eye dog|guide animal', 'pimedate juhtkoer|juhtkoer', 'Guide dogs practise intelligent disobedience when a handler’s command would be unsafe.', 'Juhtkoerad kasutavad teadlikku allumatust, kui kasutaja käsk oleks ohtlik.', 'Guide dog', 'Guide_dog'],
      ['curb-cut-helps-wheels', 'accessibility:curb-cut', 'Which lowered section of pavement, designed for wheelchairs, also helps prams, bicycles, and wheeled luggage?', 'Milline ratastoolidele loodud madaldatud kõnniteeserv aitab ka lapsevankreid, jalgrattaid ja ratastega kohvreid?', 'Curb cut', 'äärekivimadaldus', 'dropped kerb|kerb cut', 'madaldatud äärekivi|äärekivi kaldtee', 'A curb cut creates a smooth transition between pavement and street for many kinds of wheels.', 'Äärekivimadaldus loob kõnnitee ja sõidutee vahele sujuva ülemineku paljudele ratastega liikujatele.', 'Curb cut', 'Curb_cut'],
      ['coda-best-picture-deaf-family', 'work:coda-film-accessibility', 'Which Best Picture winner follows Ruby, the only hearing member of a Deaf fishing family?', 'Milline parima filmi Oscari võitja jälgib Rubyt, kes on kurtide kaluriperes ainus kuulja?', 'CODA', 'CODA', 'CODA film', 'film CODA', 'CODA centres Deaf performers and American Sign Language in a family coming-of-age story.', '„CODA“ toob täiskasvanuks saamise loos keskmesse kurdid näitlejad ja Ameerika viipekeele.', 'CODA (2021 film)', 'CODA_(2021_film)'],
      ['paralympic-symbol-agitos', 'symbol:paralympic-agitos', 'What name is given to the three curved shapes in the Paralympic symbol?', 'Kuidas nimetatakse kolme kaardus kujundit paraolümpiamängude sümbolil?', 'Agitos', 'agitos', 'the Agitos', 'agito-kujundid|Agitos', 'The Paralympic symbol uses three Agitos, a Latin-derived name suggesting movement.', 'Paraolümpiasümbol koosneb kolmest agito-kujundist, mille ladina päritolu nimi viitab liikumisele.', 'Paralympic symbols', 'Paralympic_symbols'],
    ],
  ),
  category(
    'built-in-politics-economics-society-set-007',
    '11-politics-economics-society',
    'Trash to Treasure, On Screen and Off',
    'Prügist aardeks ekraanil ja päriselus',
    [
      ['wall-e-trash-compactor', 'character:wall-e-recycling-robot', 'Which Pixar robot spends his days compacting the rubbish left behind on Earth?', 'Milline Pixari robot veedab oma päevi Maale jäänud prügi kokku pressides?', 'WALL-E', 'WALL-E', 'Walle|WALL·E', 'Walle|WALL·E', 'WALL-E is a waste-compacting robot who continues cleaning an abandoned Earth.', 'WALL-E on jäätmeid kokku pressiv robot, kes jätkab mahajäetud Maa koristamist.', 'WALL-E (character)', 'WALL-E_(character)'],
      ['macklemore-thrift-shop', 'artist:macklemore-thrift-shop', 'Which rapper turned bargain hunting for second-hand clothes into the hit song “Thrift Shop”?', 'Milline räppar tegi kasutatud riiete soodsast jahist hittloo „Thrift Shop“?', 'Macklemore', 'Macklemore', 'Ben Haggerty', 'Ben Haggerty', 'Macklemore and Ryan Lewis released “Thrift Shop”, celebrating flamboyant second-hand finds.', 'Macklemore ja Ryan Lewis avaldasid loo „Thrift Shop“, mis ülistab silmatorkavaid teise ringi leide.', 'Thrift Shop', 'Thrift_Shop'],
      ['forky-made-from-spork', 'character:forky-reused-spork', 'Which Toy Story 4 character is handmade from a spork, pipe cleaners, and modelling clay?', 'Milline „Lelulugu 4“ tegelane on tehtud plastikust söömisriistast, karvastest traadijuppidest ja voolimismassist?', 'Forky', 'Kahvel', 'Forky from Toy Story', 'Forky|tegelane Kahvel', 'Bonnie creates Forky from discarded craft materials, and he comes to life as a toy.', 'Bonnie meisterdab Kahvli äravisatud käsitöömaterjalidest ning ta ärkab mänguasjana ellu.', 'Forky', 'Forky'],
      ['kintsugi-golden-repair', 'craft:kintsugi-repair', 'Which Japanese craft highlights cracks in broken pottery with lacquer and powdered gold?', 'Milline Jaapani käsitöövõte toob katkise keraamika praod laki ja kullapulbriga esile?', 'Kintsugi', 'kintsugi', 'kintsukuroi|golden repair', 'kintsukuroi|kuldparandus', 'Kintsugi treats repaired cracks as part of an object’s history rather than hiding them.', 'Kintsugi käsitleb parandatud pragusid eseme ajaloo osana, mitte ei peida neid.', 'Kintsugi', 'Kintsugi'],
      ['earthship-reused-material-home', 'architecture:earthship-reused-materials', 'What kind of off-grid home often builds thick walls from earth-packed discarded tyres?', 'Millist võrguvälist majatüüpi ehitatakse sageli mullaga täidetud kasutatud rehvidest paksude seintega?', 'Earthship', 'earthship-maja', 'Earthship house', 'Earthship|maalaev', 'Earthships combine passive-solar design with reused materials such as tyres, cans, and bottles.', 'Earthship-majad ühendavad passiivse päikeseenergia kasutatud materjalidega, näiteks rehvide, purkide ja pudelitega.', 'Earthship', 'Earthship'],
    ],
  ),
  category(
    'built-in-politics-economics-society-set-008',
    '11-politics-economics-society',
    'A Newsroom Around the Clock',
    'Uudistetoimetuse ööpäev',
    [
      ['newspaper-front-page', 'media:newspaper', 'What printed publication puts its biggest stories on a front page and appears daily or weekly?', 'Milline trükiväljaanne paigutab suurimad lood esiküljele ning ilmub iga päev või kord nädalas?', 'Newspaper', 'ajaleht', 'daily paper', 'päevaleht|ajaleheväljaanne', 'A newspaper publishes news reporting in regularly issued printed or digital editions.', 'Ajaleht avaldab päevakajalisi uudiseid korrapäraselt ilmuvates trüki- või digiväljaannetes.', 'Newspaper', 'Newspaper'],
      ['radio-news-audio-bulletin', 'media:radio-news', 'Which news format can update drivers and listeners without requiring them to look at a screen?', 'Milline uudisevorming saab autojuhte ja teisi kuulajaid teavitada, ilma et nad peaksid ekraani vaatama?', 'Radio news', 'raadiouudised', 'radio bulletin|news on the radio', 'raadio uudistesaade|uudised raadios', 'Radio news delivers reports as spoken audio, often in scheduled bulletins.', 'Raadiouudised edastavad teated kõnena, sageli kindlal ajal algavate uudistesaadetena.', 'News broadcasting', 'News_broadcasting'],
      ['podcast-subscribed-episodes', 'media:podcast', 'Which downloadable audio programme reaches subscribers as a series of episodes?', 'Milline allalaaditav helisaade jõuab tellijateni episoodide sarjana?', 'Podcast', 'taskuhääling', 'audio podcast|podcast show', 'podcast|netisaade', 'A podcast is an episodic digital audio programme distributed over the internet.', 'Taskuhääling on internetis levitatav episoodiline digitaalne helisaade.', 'Podcast', 'Podcast'],
      ['foreign-correspondent-reports-abroad', 'media:foreign-correspondent', 'Which reporter is based in another country to cover events there for an audience back home?', 'Milline reporter elab teises riigis ning kajastab sealseid sündmusi kodupublikule?', 'Foreign correspondent', 'väliskorrespondent', 'overseas correspondent|foreign reporter', 'korrespondent välismaal|välisreporter', 'A foreign correspondent gathers and explains news from a country outside the outlet’s home base.', 'Väliskorrespondent kogub ja selgitab uudiseid riigist, mis asub väljaande kodubaasist eemal.', 'Correspondent', 'Correspondent'],
      ['news-agency-supplies-outlets', 'media:news-agency', 'What organisation gathers reports and supplies them to many newspapers, broadcasters, and websites?', 'Milline organisatsioon kogub uudiseid ning edastab neid paljudele ajalehtedele, ringhäälingutele ja veebisaitidele?', 'News agency', 'uudisteagentuur', 'wire service|press agency', 'infoagentuur|pressiagentuur', 'A news agency distributes reporting for other media outlets to publish or broadcast.', 'Uudisteagentuur levitab kajastusi, mida teised meediaväljaanded saavad avaldada või eetrisse anda.', 'News agency', 'News_agency'],
    ],
  ),
] as const satisfies readonly AccessibleCategory[];
