import { RETAINED_EASY_01_HISTORY_CATEGORIES } from './retainedEasy01History';
import { RETAINED_EASY_02_GEOGRAPHY_CATEGORIES } from './retainedEasy02Geography';
import { RETAINED_EASY_03_SCIENCE_NATURE_CATEGORIES } from './retainedEasy03ScienceNature';
import { RETAINED_EASY_04_LITERATURE_LANGUAGE_CATEGORIES } from './retainedEasy04LiteratureLanguage';
import { RETAINED_EASY_05_TO_08_CATEGORIES } from './retainedEasy05To08';
import { RETAINED_EASY_09_TO_12_CATEGORIES } from './retainedEasy09To12';

export const REAUTHORED_RETAINED_EASY_CATEGORIES = [
  ...RETAINED_EASY_01_HISTORY_CATEGORIES,
  ...RETAINED_EASY_02_GEOGRAPHY_CATEGORIES,
  ...RETAINED_EASY_03_SCIENCE_NATURE_CATEGORIES,
  ...RETAINED_EASY_04_LITERATURE_LANGUAGE_CATEGORIES,
  ...RETAINED_EASY_05_TO_08_CATEGORIES,
  ...RETAINED_EASY_09_TO_12_CATEGORIES,
] as const;
