import type { CategoryTitle } from './types';

export const ACCESSIBLE_CATEGORY_TITLES = [
  { categorySetId: "built-in-history-set-000", batchId: "01-history", name: { en: "History: Landmark Years in Modern History", et: "Ajalugu: Uusaja ajaloo pöördelised aastad" } },
  { categorySetId: "built-in-history-set-001", batchId: "01-history", name: { en: "History: Daily Life in Ancient Egypt", et: "Ajalugu: Igapäevaelu Vana-Egiptuses" } },
  { categorySetId: "built-in-history-set-003", batchId: "01-history", name: { en: "History: Dates That Changed the World", et: "Ajalugu: Maailma muutnud kuupäevad" } },
  { categorySetId: "built-in-history-set-010", batchId: "01-history", name: { en: "History: Classical Greece", et: "Ajalugu: Klassikaline Kreeka" } },
  { categorySetId: "built-in-history-set-011", batchId: "01-history", name: { en: "History: Leaders Who Shaped Nations", et: "Ajalugu: Rahvaid kujundanud juhid" } },
  { categorySetId: "built-in-history-set-012", batchId: "01-history", name: { en: "History: The Roman Empire", et: "Ajalugu: Rooma impeerium" } },
  { categorySetId: "built-in-history-set-013", batchId: "01-history", name: { en: "History: Reformers, Monarchs, and Wartime Leaders", et: "Ajalugu: Uuendajad, monarhid ja sõjaaegsed juhid" } },
  { categorySetId: "built-in-history-set-014", batchId: "01-history", name: { en: "History: The Viking Age", et: "Ajalugu: Viikingiaeg" } },
  { categorySetId: "built-in-history-set-017", batchId: "01-history", name: { en: "History: Ancient Sites and Monuments", et: "Ajalugu: Muistsed paigad ja mälestised" } },
  { categorySetId: "built-in-history-set-018", batchId: "01-history", name: { en: "History: Medieval Castles", et: "Ajalugu: Keskaegsed lossid" } },
  { categorySetId: "built-in-history-set-019", batchId: "01-history", name: { en: "History: Places That Witnessed History", et: "Ajalugu: Ajaloo tunnistajaks olnud paigad" } },
  { categorySetId: "built-in-history-set-023", batchId: "01-history", name: { en: "History: The Age of Exploration", et: "Ajalugu: Maadeavastuste ajastu" } },
  { categorySetId: "built-in-history-set-024", batchId: "01-history", name: { en: "History: Early Empires and Peoples", et: "Ajalugu: Varased impeeriumid ja rahvad" } },
  { categorySetId: "built-in-history-set-025", batchId: "01-history", name: { en: "History: The American Revolution", et: "Ajalugu: Ameerika revolutsioon" } },
  { categorySetId: "built-in-history-set-026", batchId: "01-history", name: { en: "History: Civilizations, Empires, and States", et: "Ajalugu: Tsivilisatsioonid, impeeriumid ja riigid" } },
  { categorySetId: "built-in-history-set-029", batchId: "01-history", name: { en: "History: The French Revolution", et: "Ajalugu: Prantsuse revolutsioon" } },
  { categorySetId: "built-in-history-set-030", batchId: "01-history", name: { en: "History: The Industrial Revolution", et: "Ajalugu: Tööstusrevolutsioon" } },
  { categorySetId: "built-in-history-set-031", batchId: "01-history", name: { en: "History: The First World War", et: "Ajalugu: Esimene maailmasõda" } },
  { categorySetId: "built-in-history-set-033", batchId: "01-history", name: { en: "History: The Second World War", et: "Ajalugu: Teine maailmasõda" } },
  { categorySetId: "built-in-history-set-034", batchId: "01-history", name: { en: "History: The Cold War", et: "Ajalugu: Külm sõda" } },
  { categorySetId: "built-in-history-set-035", batchId: "01-history", name: { en: "History: The Space Race", et: "Ajalugu: Kosmosevõidujooks" } },
  { categorySetId: "built-in-history-set-039", batchId: "01-history", name: { en: "History: The Civil Rights Movement", et: "Ajalugu: Kodanikuõiguste liikumine" } },
  { categorySetId: "built-in-history-set-043", batchId: "01-history", name: { en: "History: Women's Suffrage", et: "Ajalugu: Naiste valimisõigus" } },
  { categorySetId: "built-in-history-set-049", batchId: "01-history", name: { en: "History: Famous Archaeological Finds", et: "Ajalugu: Kuulsad arheoloogilised leiud" } },
  { categorySetId: "built-in-history-set-050", batchId: "01-history", name: { en: "History: Historic Trade Routes", et: "Ajalugu: Ajaloolised kaubateed" } },
  { categorySetId: "built-in-history-set-051", batchId: "01-history", name: { en: "History: Royal Houses of Europe", et: "Ajalugu: Euroopa kuningakojad" } },
  { categorySetId: "built-in-history-set-052", batchId: "01-history", name: { en: "History: Independence Movements", et: "Ajalugu: Iseseisvusliikumised" } },
  { categorySetId: "built-in-history-set-053", batchId: "01-history", name: { en: "History: The History of Writing", et: "Ajalugu: Kirjutamise ajalugu" } },
  { categorySetId: "built-in-history-set-055", batchId: "01-history", name: { en: "History: The History of Medicine", et: "Ajalugu: Meditsiini ajalugu" } },
  { categorySetId: "built-in-history-set-060", batchId: "01-history", name: { en: "History: Famous Peace Treaties", et: "Ajalugu: Kuulsad rahulepingud" } },
  { categorySetId: "built-in-history-set-070", batchId: "01-history", name: { en: "History: Cities Through Time", et: "Ajalugu: Linnad läbi aegade" } },
  { categorySetId: "built-in-history-set-072", batchId: "01-history", name: { en: "History: Everyday Life in the 1990s", et: "Ajalugu: Igapäevaelu 1990. aastatel" } },
  { categorySetId: "built-in-history-set-074", batchId: "01-history", name: { en: "History: Baltic Independence", et: "Ajalugu: Balti riikide iseseisvus" } },
  { categorySetId: "built-in-history-set-092", batchId: "01-history", name: { en: "History: Inventions That Changed Society", et: "Ajalugu: Ühiskonda muutnud leiutised" } },
  { categorySetId: "built-in-geography-set-001", batchId: "02-geography", name: { en: "Geography: Nordic and Baltic Capitals", et: "Geograafia: Põhjala ja Baltimaade pealinnad" } },
  { categorySetId: "built-in-geography-set-002", batchId: "02-geography", name: { en: "Geography: Capitals of Europe", et: "Geograafia: Euroopa pealinnad" } },
  { categorySetId: "built-in-geography-set-003", batchId: "02-geography", name: { en: "Geography: Famous World Capitals", et: "Geograafia: Tuntud maailma pealinnad" } },
  { categorySetId: "built-in-geography-set-004", batchId: "02-geography", name: { en: "Geography: Capitals of Asia", et: "Geograafia: Aasia pealinnad" } },
  { categorySetId: "built-in-geography-set-010", batchId: "02-geography", name: { en: "Geography: Landmarks from Paris to Rio", et: "Geograafia: Vaatamisväärsused Pariisist Rioni" } },
  { categorySetId: "built-in-geography-set-011", batchId: "02-geography", name: { en: "Geography: Landmarks from Pisa to Easter Island", et: "Geograafia: Vaatamisväärsused Pisast Lihavõttesaareni" } },
  { categorySetId: "built-in-geography-set-012", batchId: "02-geography", name: { en: "Geography: Capitals of Africa", et: "Geograafia: Aafrika pealinnad" } },
  { categorySetId: "built-in-geography-set-013", batchId: "02-geography", name: { en: "Geography: Seas, Oceans, and Great Rivers", et: "Geograafia: Mered, ookeanid ja suured jõed" } },
  { categorySetId: "built-in-geography-set-015", batchId: "02-geography", name: { en: "Geography: Capitals of the Americas", et: "Geograafia: Ameerikate pealinnad" } },
  { categorySetId: "built-in-geography-set-018", batchId: "02-geography", name: { en: "Geography: Rivers, Lakes, and Waterfalls", et: "Geograafia: Jõed, järved ja joad" } },
  { categorySetId: "built-in-geography-set-024", batchId: "02-geography", name: { en: "Geography: Flags of the World", et: "Geograafia: Maailma lipud" } },
  { categorySetId: "built-in-geography-set-027", batchId: "02-geography", name: { en: "Geography: Countries by Their Shapes", et: "Geograafia: Riigid kuju järgi" } },
  { categorySetId: "built-in-geography-set-029", batchId: "02-geography", name: { en: "Geography: Rivers of Europe", et: "Geograafia: Euroopa jõed" } },
  { categorySetId: "built-in-geography-set-030", batchId: "02-geography", name: { en: "Geography: Earth's Great Features", et: "Geograafia: Maa suured pinnavormid" } },
  { categorySetId: "built-in-geography-set-032", batchId: "02-geography", name: { en: "Geography: Mountains of the World", et: "Geograafia: Maailma mäed" } },
  { categorySetId: "built-in-geography-set-033", batchId: "02-geography", name: { en: "Geography: From Poles to Islands", et: "Geograafia: Poolustelt saartele" } },
  { categorySetId: "built-in-geography-set-037", batchId: "02-geography", name: { en: "Geography: Great Deserts", et: "Geograafia: Suured kõrbed" } },
  { categorySetId: "built-in-geography-set-047", batchId: "02-geography", name: { en: "Geography: Famous Islands", et: "Geograafia: Kuulsad saared" } },
  { categorySetId: "built-in-geography-set-055", batchId: "02-geography", name: { en: "Geography: Volcanoes", et: "Geograafia: Vulkaanid" } },
  { categorySetId: "built-in-geography-set-057", batchId: "02-geography", name: { en: "Geography: National Parks", et: "Geograafia: Rahvuspargid" } },
  { categorySetId: "built-in-geography-set-058", batchId: "02-geography", name: { en: "Geography: World Time Zones", et: "Geograafia: Maailma ajavööndid" } },
  { categorySetId: "built-in-geography-set-062", batchId: "02-geography", name: { en: "Geography: Neighbouring Countries", et: "Geograafia: Naaberriigid" } },
  { categorySetId: "built-in-geography-set-064", batchId: "02-geography", name: { en: "Geography: The Baltic Region", et: "Geograafia: Läänemere piirkond" } },
  { categorySetId: "built-in-geography-set-065", batchId: "02-geography", name: { en: "Geography: The Nordic Countries", et: "Geograafia: Põhjamaad" } },
  { categorySetId: "built-in-geography-set-066", batchId: "02-geography", name: { en: "Geography: The Mediterranean Region", et: "Geograafia: Vahemere piirkond" } },
  { categorySetId: "built-in-geography-set-072", batchId: "02-geography", name: { en: "Geography: The Caribbean", et: "Geograafia: Kariibi mere piirkond" } },
  { categorySetId: "built-in-geography-set-073", batchId: "02-geography", name: { en: "Geography: Southeast Asia", et: "Geograafia: Kagu-Aasia" } },
  { categorySetId: "built-in-geography-set-074", batchId: "02-geography", name: { en: "Geography: South America", et: "Geograafia: Lõuna-Ameerika" } },
  { categorySetId: "built-in-geography-set-077", batchId: "02-geography", name: { en: "Geography: Landmarks of Africa", et: "Geograafia: Aafrika vaatamisväärsused" } },
  { categorySetId: "built-in-geography-set-080", batchId: "02-geography", name: { en: "Geography: Landmarks of Asia", et: "Geograafia: Aasia vaatamisväärsused" } },
  { categorySetId: "built-in-geography-set-082", batchId: "02-geography", name: { en: "Geography: Landmarks of Europe", et: "Geograafia: Euroopa vaatamisväärsused" } },
  { categorySetId: "built-in-geography-set-085", batchId: "02-geography", name: { en: "Geography: Oceans and Currents", et: "Geograafia: Ookeanid ja hoovused" } },
  { categorySetId: "built-in-geography-set-088", batchId: "02-geography", name: { en: "Geography: Natural Wonders", et: "Geograafia: Loodusimed" } },
  { categorySetId: "built-in-geography-set-094", batchId: "02-geography", name: { en: "Geography: Languages and Their Countries", et: "Geograafia: Keeled ja nende riigid" } },
  { categorySetId: "built-in-science-nature-set-000", batchId: "03-science-nature", name: { en: "Science & Nature: Our Nearest Space Neighbours", et: "Teadus ja loodus: Meie lähimad kosmosenaabrid" } },
  { categorySetId: "built-in-science-nature-set-001", batchId: "03-science-nature", name: { en: "Science & Nature: Objects Across the Solar System and Beyond", et: "Teadus ja loodus: Päikesesüsteemi ja kaugema kosmose objektid" } },
  { categorySetId: "built-in-science-nature-set-002", batchId: "03-science-nature", name: { en: "Science & Nature: Major Parts of the Human Body", et: "Teadus ja loodus: Inimkeha peamised osad" } },
  { categorySetId: "built-in-science-nature-set-003", batchId: "03-science-nature", name: { en: "Science & Nature: Cells, Organs, and Human Biology", et: "Teadus ja loodus: Rakud, elundid ja inimbioloogia" } },
  { categorySetId: "built-in-science-nature-set-004", batchId: "03-science-nature", name: { en: "Science & Nature: Everyday Science Essentials", et: "Teadus ja loodus: Igapäevase teaduse alused" } },
  { categorySetId: "built-in-science-nature-set-007", batchId: "03-science-nature", name: { en: "Science & Nature: Matter, Forces, and Visible Phenomena", et: "Teadus ja loodus: Aine, jõud ja nähtavad nähtused" } },
  { categorySetId: "built-in-science-nature-set-010", batchId: "03-science-nature", name: { en: "Science & Nature: Remarkable Animals from Ocean to Ice", et: "Teadus ja loodus: Tähelepanuväärsed loomad ookeanist jääväljadeni" } },
  { categorySetId: "built-in-science-nature-set-011", batchId: "03-science-nature", name: { en: "Science & Nature: Animals Around the World", et: "Teadus ja loodus: Loomad kõikjalt maailmast" } },
  { categorySetId: "built-in-science-nature-set-013", batchId: "03-science-nature", name: { en: "Science & Nature: The Inner Planets", et: "Teadus ja loodus: Siseplaneedid" } },
  { categorySetId: "built-in-science-nature-set-014", batchId: "03-science-nature", name: { en: "Science & Nature: The Outer Planets", et: "Teadus ja loodus: Välisplaneedid" } },
  { categorySetId: "built-in-science-nature-set-015", batchId: "03-science-nature", name: { en: "Science & Nature: Moons of the Solar System", et: "Teadus ja loodus: Päikesesüsteemi kuud" } },
  { categorySetId: "built-in-science-nature-set-016", batchId: "03-science-nature", name: { en: "Science & Nature: Constellations in the Night Sky", et: "Teadus ja loodus: Tähtkujud öötaevas" } },
  { categorySetId: "built-in-science-nature-set-017", batchId: "03-science-nature", name: { en: "Science & Nature: Weather Basics", et: "Teadus ja loodus: Ilma põhitõed" } },
  { categorySetId: "built-in-science-nature-set-018", batchId: "03-science-nature", name: { en: "Science & Nature: Climate Zones", et: "Teadus ja loodus: Kliimavöötmed" } },
  { categorySetId: "built-in-science-nature-set-019", batchId: "03-science-nature", name: { en: "Science & Nature: Rocks and Minerals", et: "Teadus ja loodus: Kivimid ja mineraalid" } },
  { categorySetId: "built-in-science-nature-set-021", batchId: "03-science-nature", name: { en: "Science & Nature: Volcanoes and Earthquakes", et: "Teadus ja loodus: Vulkaanid ja maavärinad" } },
  { categorySetId: "built-in-science-nature-set-022", batchId: "03-science-nature", name: { en: "Science & Nature: Life in the Ocean", et: "Teadus ja loodus: Elu ookeanis" } },
  { categorySetId: "built-in-science-nature-set-023", batchId: "03-science-nature", name: { en: "Science & Nature: Forests of the World", et: "Teadus ja loodus: Maailma metsad" } },
  { categorySetId: "built-in-science-nature-set-026", batchId: "03-science-nature", name: { en: "Science & Nature: How Plants Grow", et: "Teadus ja loodus: Kuidas taimed kasvavad" } },
  { categorySetId: "built-in-science-nature-set-027", batchId: "03-science-nature", name: { en: "Science & Nature: Insects", et: "Teadus ja loodus: Putukad" } },
  { categorySetId: "built-in-science-nature-set-028", batchId: "03-science-nature", name: { en: "Science & Nature: Birds", et: "Teadus ja loodus: Linnud" } },
  { categorySetId: "built-in-science-nature-set-029", batchId: "03-science-nature", name: { en: "Science & Nature: Mammals", et: "Teadus ja loodus: Imetajad" } },
  { categorySetId: "built-in-science-nature-set-030", batchId: "03-science-nature", name: { en: "Science & Nature: Reptiles and Amphibians", et: "Teadus ja loodus: Roomajad ja kahepaiksed" } },
  { categorySetId: "built-in-science-nature-set-032", batchId: "03-science-nature", name: { en: "Science & Nature: Dinosaurs", et: "Teadus ja loodus: Dinosaurused" } },
  { categorySetId: "built-in-science-nature-set-034", batchId: "03-science-nature", name: { en: "Science & Nature: The Human Senses", et: "Teadus ja loodus: Inimese meeled" } },
  { categorySetId: "built-in-science-nature-set-039", batchId: "03-science-nature", name: { en: "Science & Nature: Bones and Muscles", et: "Teadus ja loodus: Luud ja lihased" } },
  { categorySetId: "built-in-science-nature-set-040", batchId: "03-science-nature", name: { en: "Science & Nature: Digestion", et: "Teadus ja loodus: Seedimine" } },
  { categorySetId: "built-in-science-nature-set-051", batchId: "03-science-nature", name: { en: "Science & Nature: Electricity", et: "Teadus ja loodus: Elekter" } },
  { categorySetId: "built-in-science-nature-set-081", batchId: "03-science-nature", name: { en: "Science & Nature: Light and Colour", et: "Teadus ja loodus: Valgus ja värvus" } },
  { categorySetId: "built-in-science-nature-set-084", batchId: "03-science-nature", name: { en: "Science & Nature: Simple Machines", et: "Teadus ja loodus: Lihtsad masinad" } },
  { categorySetId: "built-in-science-nature-set-085", batchId: "03-science-nature", name: { en: "Science & Nature: States of Matter", et: "Teadus ja loodus: Aine olekud" } },
  { categorySetId: "built-in-science-nature-set-090", batchId: "03-science-nature", name: { en: "Science & Nature: Familiar Chemical Elements", et: "Teadus ja loodus: Tuntud keemilised elemendid" } },
  { categorySetId: "built-in-science-nature-set-094", batchId: "03-science-nature", name: { en: "Science & Nature: Scientists Everyone Knows", et: "Teadus ja loodus: Teadlased, keda kõik teavad" } },
  { categorySetId: "built-in-science-nature-set-097", batchId: "03-science-nature", name: { en: "Science & Nature: Chemistry in Daily Life", et: "Teadus ja loodus: Keemia igapäevaelus" } },
  { categorySetId: "built-in-literature-language-set-001", batchId: "04-literature-language", name: { en: "Literature & Language: Authors of Beloved Classics", et: "Kirjandus ja keel: Armastatud klassikute autorid" } },
  { categorySetId: "built-in-literature-language-set-002", batchId: "04-literature-language", name: { en: "Literature & Language: Writers from Britain to Estonia", et: "Kirjandus ja keel: Kirjanikud Britanniast Eestini" } },
  { categorySetId: "built-in-literature-language-set-003", batchId: "04-literature-language", name: { en: "Literature & Language: Classic Books and Their Connections", et: "Kirjandus ja keel: Klassikalised raamatud ja nende seosed" } },
  { categorySetId: "built-in-literature-language-set-004", batchId: "04-literature-language", name: { en: "Literature & Language: Literary Figures, Places, and Creators", et: "Kirjandus ja keel: Kirjandustegelased, paigad ja loojad" } },
  { categorySetId: "built-in-literature-language-set-005", batchId: "04-literature-language", name: { en: "Literature & Language: Languages of Western and Northern Europe", et: "Kirjandus ja keel: Lääne- ja Põhja-Euroopa keeled" } },
  { categorySetId: "built-in-literature-language-set-006", batchId: "04-literature-language", name: { en: "Literature & Language: Languages of Europe and Beyond", et: "Kirjandus ja keel: Euroopa ja kaugemate maade keeled" } },
  { categorySetId: "built-in-literature-language-set-011", batchId: "04-literature-language", name: { en: "Literature & Language: Fairy Tales of the World", et: "Kirjandus ja keel: Maailma muinasjutud" } },
  { categorySetId: "built-in-literature-language-set-014", batchId: "04-literature-language", name: { en: "Literature & Language: Myths in Literature", et: "Kirjandus ja keel: Müüdid kirjanduses" } },
  { categorySetId: "built-in-literature-language-set-016", batchId: "04-literature-language", name: { en: "Literature & Language: Shakespeare's Characters", et: "Kirjandus ja keel: Shakespeare'i tegelased" } },
  { categorySetId: "built-in-literature-language-set-021", batchId: "04-literature-language", name: { en: "Literature & Language: Classic Children's Books", et: "Kirjandus ja keel: Klassikalised lasteraamatud" } },
  { categorySetId: "built-in-literature-language-set-022", batchId: "04-literature-language", name: { en: "Literature & Language: Words About Words", et: "Kirjandus ja keel: Sõnad sõnade kohta" } },
  { categorySetId: "built-in-literature-language-set-023", batchId: "04-literature-language", name: { en: "Literature & Language: Famous Detectives", et: "Kirjandus ja keel: Kuulsad detektiivid" } },
  { categorySetId: "built-in-literature-language-set-024", batchId: "04-literature-language", name: { en: "Literature & Language: Fantasy Worlds", et: "Kirjandus ja keel: Fantaasiamaailmad" } },
  { categorySetId: "built-in-literature-language-set-026", batchId: "04-literature-language", name: { en: "Literature & Language: Science Fiction Classics", et: "Kirjandus ja keel: Teadusulme klassika" } },
  { categorySetId: "built-in-literature-language-set-028", batchId: "04-literature-language", name: { en: "Literature & Language: Adventure Novels", et: "Kirjandus ja keel: Seiklusromaanid" } },
  { categorySetId: "built-in-literature-language-set-030", batchId: "04-literature-language", name: { en: "Literature & Language: Poetry Basics", et: "Kirjandus ja keel: Luule põhitõed" } },
  { categorySetId: "built-in-literature-language-set-032", batchId: "04-literature-language", name: { en: "Literature & Language: Forms and Figures of Writing", et: "Kirjandus ja keel: Kirjutamise vormid ja kujundid" } },
  { categorySetId: "built-in-literature-language-set-035", batchId: "04-literature-language", name: { en: "Literature & Language: Literary Devices", et: "Kirjandus ja keel: Kirjanduslikud võtted" } },
  { categorySetId: "built-in-literature-language-set-036", batchId: "04-literature-language", name: { en: "Literature & Language: Famous First Lines", et: "Kirjandus ja keel: Kuulsad avalaused" } },
  { categorySetId: "built-in-literature-language-set-054", batchId: "04-literature-language", name: { en: "Literature & Language: Authors and Their Countries", et: "Kirjandus ja keel: Autorid ja nende riigid" } },
  { categorySetId: "built-in-literature-language-set-069", batchId: "04-literature-language", name: { en: "Literature & Language: Writers' Pen Names", et: "Kirjandus ja keel: Kirjanike pseudonüümid" } },
  { categorySetId: "built-in-literature-language-set-072", batchId: "04-literature-language", name: { en: "Literature & Language: Settings in Famous Books", et: "Kirjandus ja keel: Kuulsate raamatute tegevuspaigad" } },
  { categorySetId: "built-in-literature-language-set-077", batchId: "04-literature-language", name: { en: "Literature & Language: Talking Animals in Stories", et: "Kirjandus ja keel: Kõnelevad loomad lugudes" } },
  { categorySetId: "built-in-literature-language-set-080", batchId: "04-literature-language", name: { en: "Literature & Language: Literary Villains", et: "Kirjandus ja keel: Kirjanduslikud kurikaelad" } },
  { categorySetId: "built-in-literature-language-set-081", batchId: "04-literature-language", name: { en: "Literature & Language: Literary Heroes", et: "Kirjandus ja keel: Kirjanduskangelased" } },
  { categorySetId: "built-in-literature-language-set-082", batchId: "04-literature-language", name: { en: "Literature & Language: Classic Love Stories", et: "Kirjandus ja keel: Klassikalised armastuslood" } },
  { categorySetId: "built-in-literature-language-set-090", batchId: "04-literature-language", name: { en: "Literature & Language: Nordic Children's Stories", et: "Kirjandus ja keel: Põhjamaade lastelood" } },
  { categorySetId: "built-in-literature-language-set-091", batchId: "04-literature-language", name: { en: "Literature & Language: Writers of the Baltic Region", et: "Kirjandus ja keel: Baltimaade kirjanikud" } },
  { categorySetId: "built-in-literature-language-set-092", batchId: "04-literature-language", name: { en: "Literature & Language: Estonian Literary Classics", et: "Kirjandus ja keel: Eesti kirjandusklassika" } },
  { categorySetId: "built-in-literature-language-set-093", batchId: "04-literature-language", name: { en: "Literature & Language: Language Families", et: "Kirjandus ja keel: Keelekonnad" } },
  { categorySetId: "built-in-literature-language-set-094", batchId: "04-literature-language", name: { en: "Literature & Language: Borrowed Words", et: "Kirjandus ja keel: Laensõnad" } },
  { categorySetId: "built-in-literature-language-set-096", batchId: "04-literature-language", name: { en: "Literature & Language: Idioms and Sayings", et: "Kirjandus ja keel: Idioomid ja kõnekäänud" } },
  { categorySetId: "built-in-literature-language-set-098", batchId: "04-literature-language", name: { en: "Literature & Language: Punctuation Marks", et: "Kirjandus ja keel: Kirjavahemärgid" } },
  { categorySetId: "built-in-literature-language-set-100", batchId: "04-literature-language", name: { en: "Literature & Language: Alphabets of the World", et: "Kirjandus ja keel: Maailma tähestikud" } },
  { categorySetId: "built-in-art-architecture-set-001", batchId: "05-art-architecture", name: { en: "Art & Architecture: Primary and Secondary Colours", et: "Kunst ja arhitektuur: Põhi- ja sekundaarvärvid" } },
  { categorySetId: "built-in-art-architecture-set-002", batchId: "05-art-architecture", name: { en: "Art & Architecture: Tools of the Painter", et: "Kunst ja arhitektuur: Maalikunstniku töövahendid" } },
  { categorySetId: "built-in-art-architecture-set-003", batchId: "05-art-architecture", name: { en: "Art & Architecture: Materials of Sculpture", et: "Kunst ja arhitektuur: Skulptuuri materjalid" } },
  { categorySetId: "built-in-art-architecture-set-004", batchId: "05-art-architecture", name: { en: "Art & Architecture: Great Art Museums", et: "Kunst ja arhitektuur: Suured kunstimuuseumid" } },
  { categorySetId: "built-in-art-architecture-set-005", batchId: "05-art-architecture", name: { en: "Art & Architecture: Masters of the Renaissance", et: "Kunst ja arhitektuur: Renessansimeistrid" } },
  { categorySetId: "built-in-art-architecture-set-006", batchId: "05-art-architecture", name: { en: "Art & Architecture: Impressionist Painting", et: "Kunst ja arhitektuur: Impressionistlik maalikunst" } },
  { categorySetId: "built-in-art-architecture-set-007", batchId: "05-art-architecture", name: { en: "Art & Architecture: Famous Paintings at a Glance", et: "Kunst ja arhitektuur: Kuulsad maalid ühe pilguga" } },
  { categorySetId: "built-in-art-architecture-set-008", batchId: "05-art-architecture", name: { en: "Art & Architecture: Modern Artists and Their Signature Looks", et: "Kunst ja arhitektuur: Moodsa kunsti meistrite tunnusstiilid" } },
  { categorySetId: "built-in-art-architecture-set-009", batchId: "05-art-architecture", name: { en: "Art & Architecture: Nature in Art", et: "Kunst ja arhitektuur: Loodus kunstis" } },
  { categorySetId: "built-in-art-architecture-set-010", batchId: "05-art-architecture", name: { en: "Art & Architecture: Art across the Ages", et: "Kunst ja arhitektuur: Kunst läbi aegade" } },
  { categorySetId: "built-in-art-architecture-set-011", batchId: "05-art-architecture", name: { en: "Art & Architecture: Famous Portraits", et: "Kunst ja arhitektuur: Kuulsad portreed" } },
  { categorySetId: "built-in-art-architecture-set-012", batchId: "05-art-architecture", name: { en: "Art & Architecture: Landscape Painting", et: "Kunst ja arhitektuur: Maastikumaal" } },
  { categorySetId: "built-in-art-architecture-set-013", batchId: "05-art-architecture", name: { en: "Art & Architecture: Street Art", et: "Kunst ja arhitektuur: Tänavakunst" } },
  { categorySetId: "built-in-art-architecture-set-014", batchId: "05-art-architecture", name: { en: "Art & Architecture: Photography Basics", et: "Kunst ja arhitektuur: Fotograafia põhitõed" } },
  { categorySetId: "built-in-art-architecture-set-015", batchId: "05-art-architecture", name: { en: "Art & Architecture: Shapes in Architecture", et: "Kunst ja arhitektuur: Kujundid arhitektuuris" } },
  { categorySetId: "built-in-art-architecture-set-016", batchId: "05-art-architecture", name: { en: "Art & Architecture: Columns and Arches", et: "Kunst ja arhitektuur: Sambad ja kaared" } },
  { categorySetId: "built-in-art-architecture-set-017", batchId: "05-art-architecture", name: { en: "Art & Architecture: Castles of Europe", et: "Kunst ja arhitektuur: Euroopa lossid" } },
  { categorySetId: "built-in-art-architecture-set-018", batchId: "05-art-architecture", name: { en: "Art & Architecture: Great Cathedrals", et: "Kunst ja arhitektuur: Suured katedraalid" } },
  { categorySetId: "built-in-art-architecture-set-019", batchId: "05-art-architecture", name: { en: "Art & Architecture: Famous Skyscrapers", et: "Kunst ja arhitektuur: Kuulsad pilvelõhkujad" } },
  { categorySetId: "built-in-art-architecture-set-020", batchId: "05-art-architecture", name: { en: "Art & Architecture: Bridges of the World", et: "Kunst ja arhitektuur: Maailma sillad" } },
  { categorySetId: "built-in-art-architecture-set-021", batchId: "05-art-architecture", name: { en: "Art & Architecture: Monuments Everyone Knows", et: "Kunst ja arhitektuur: Kõigile tuntud monumendid" } },
  { categorySetId: "built-in-art-architecture-set-022", batchId: "05-art-architecture", name: { en: "Art & Architecture: Architecture of the Ancient World", et: "Kunst ja arhitektuur: Antiikmaailma arhitektuur" } },
  { categorySetId: "built-in-art-architecture-set-023", batchId: "05-art-architecture", name: { en: "Art & Architecture: Gothic Architecture", et: "Kunst ja arhitektuur: Gooti arhitektuur" } },
  { categorySetId: "built-in-art-architecture-set-024", batchId: "05-art-architecture", name: { en: "Art & Architecture: Art Nouveau", et: "Kunst ja arhitektuur: Juugendstiil" } },
  { categorySetId: "built-in-art-architecture-set-025", batchId: "05-art-architecture", name: { en: "Art & Architecture: Modernist Buildings", et: "Kunst ja arhitektuur: Modernistlikud hooned" } },
  { categorySetId: "built-in-art-architecture-set-026", batchId: "05-art-architecture", name: { en: "Art & Architecture: Nordic Design", et: "Kunst ja arhitektuur: Põhjamaade disain" } },
  { categorySetId: "built-in-art-architecture-set-027", batchId: "05-art-architecture", name: { en: "Art & Architecture: Architecture of the Baltic Region", et: "Kunst ja arhitektuur: Baltimaade arhitektuur" } },
  { categorySetId: "built-in-art-architecture-set-028", batchId: "05-art-architecture", name: { en: "Art & Architecture: Design Objects at Home", et: "Kunst ja arhitektuur: Disainesemed kodus" } },
  { categorySetId: "built-in-art-architecture-set-029", batchId: "05-art-architecture", name: { en: "Art & Architecture: Ceramic Art", et: "Kunst ja arhitektuur: Keraamikakunst" } },
  { categorySetId: "built-in-art-architecture-set-030", batchId: "05-art-architecture", name: { en: "Art & Architecture: Textile Art", et: "Kunst ja arhitektuur: Tekstiilikunst" } },
  { categorySetId: "built-in-art-architecture-set-031", batchId: "05-art-architecture", name: { en: "Art & Architecture: Printmaking", et: "Kunst ja arhitektuur: Graafikakunst" } },
  { categorySetId: "built-in-art-architecture-set-032", batchId: "05-art-architecture", name: { en: "Art & Architecture: Graphic Design", et: "Kunst ja arhitektuur: Graafiline disain" } },
  { categorySetId: "built-in-art-architecture-set-033", batchId: "05-art-architecture", name: { en: "Art & Architecture: Public Statues", et: "Kunst ja arhitektuur: Avalikud skulptuurid" } },
  { categorySetId: "built-in-music-set-001", batchId: "06-music", name: { en: "Music: Global Pop Icons", et: "Muusika: Maailma popikoonid" } },
  { categorySetId: "built-in-music-set-002", batchId: "06-music", name: { en: "Music: Stars of Pop and Rock", et: "Muusika: Popi- ja rokitähed" } },
  { categorySetId: "built-in-music-set-003", batchId: "06-music", name: { en: "Music: Hit Bands from Britain, Ireland, and Sweden", et: "Muusika: Menubändid Britanniast, Iirimaalt ja Rootsist" } },
  { categorySetId: "built-in-music-set-004", batchId: "06-music", name: { en: "Music: Rock and Pop Bands Across Decades", et: "Muusika: Roki- ja popbändid läbi aastakümnete" } },
  { categorySetId: "built-in-music-set-005", batchId: "06-music", name: { en: "Music: Instruments of Bands and Orchestras", et: "Muusika: Ansamblite ja orkestrite pillid" } },
  { categorySetId: "built-in-music-set-006", batchId: "06-music", name: { en: "Music: Instruments Powered by Breath, Bow, and Bellows", et: "Muusika: Hinguse, poogna ja lõõtsaga pillid" } },
  { categorySetId: "built-in-music-set-007", batchId: "06-music", name: { en: "Music: Classical Masters from Baroque to Romanticism", et: "Muusika: Klassikameistrid barokist romantismini" } },
  { categorySetId: "built-in-music-set-008", batchId: "06-music", name: { en: "Music: Opera, Piano, and Estonian Musical Voices", et: "Muusika: Ooper, klaver ja Eesti muusikahääled" } },
  { categorySetId: "built-in-music-set-009", batchId: "06-music", name: { en: "Music: Musical Notes and Symbols", et: "Muusika: Noodid ja muusikasümbolid" } },
  { categorySetId: "built-in-music-set-011", batchId: "06-music", name: { en: "Music: Types of Singing Voice", et: "Muusika: Lauluhääle liigid" } },
  { categorySetId: "built-in-music-set-012", batchId: "06-music", name: { en: "Music: Sections of the Orchestra", et: "Muusika: Orkestri pillirühmad" } },
  { categorySetId: "built-in-music-set-013", batchId: "06-music", name: { en: "Music: Percussion Instruments", et: "Muusika: Löökpillid" } },
  { categorySetId: "built-in-music-set-014", batchId: "06-music", name: { en: "Music: String Instruments", et: "Muusika: Keelpillid" } },
  { categorySetId: "built-in-music-set-015", batchId: "06-music", name: { en: "Music: Woodwind Instruments", et: "Muusika: Puupuhkpillid" } },
  { categorySetId: "built-in-music-set-016", batchId: "06-music", name: { en: "Music: Brass Instruments", et: "Muusika: Vaskpuhkpillid" } },
  { categorySetId: "built-in-music-set-017", batchId: "06-music", name: { en: "Music: Keyboard Instruments", et: "Muusika: Klahvpillid" } },
  { categorySetId: "built-in-music-set-018", batchId: "06-music", name: { en: "Music: The Guitar Family", et: "Muusika: Kitarriperekond" } },
  { categorySetId: "built-in-music-set-019", batchId: "06-music", name: { en: "Music: Folk Instruments", et: "Muusika: Rahvapillid" } },
  { categorySetId: "built-in-music-set-020", batchId: "06-music", name: { en: "Music: Eras of Classical Music", et: "Muusika: Klassikalise muusika ajastud" } },
  { categorySetId: "built-in-music-set-021", batchId: "06-music", name: { en: "Music: The World of Opera", et: "Muusika: Ooperimaailm" } },
  { categorySetId: "built-in-music-set-022", batchId: "06-music", name: { en: "Music: Music for Ballet", et: "Muusika: Balletimuusika" } },
  { categorySetId: "built-in-music-set-023", batchId: "06-music", name: { en: "Music: Jazz", et: "Muusika: Džäss" } },
  { categorySetId: "built-in-music-set-024", batchId: "06-music", name: { en: "Music: The Blues", et: "Muusika: Bluus" } },
  { categorySetId: "built-in-music-set-025", batchId: "06-music", name: { en: "Music: Rock of the 1960s and 1970s", et: "Muusika: 1960. ja 1970. aastate rokk" } },
  { categorySetId: "built-in-music-set-026", batchId: "06-music", name: { en: "Music: Pop of the 1980s", et: "Muusika: 1980. aastate popmuusika" } },
  { categorySetId: "built-in-music-set-027", batchId: "06-music", name: { en: "Music: Pop of the 1990s", et: "Muusika: 1990. aastate popmuusika" } },
  { categorySetId: "built-in-music-set-028", batchId: "06-music", name: { en: "Music: Pop of the 2000s", et: "Muusika: 2000. aastate popmuusika" } },
  { categorySetId: "built-in-music-set-029", batchId: "06-music", name: { en: "Music: Pop of the 2010s", et: "Muusika: 2010. aastate popmuusika" } },
  { categorySetId: "built-in-music-set-030", batchId: "06-music", name: { en: "Music: Eurovision Winners", et: "Muusika: Eurovisiooni võitjad" } },
  { categorySetId: "built-in-music-set-031", batchId: "06-music", name: { en: "Music: Nordic Pop", et: "Muusika: Põhjamaade popmuusika" } },
  { categorySetId: "built-in-music-set-032", batchId: "06-music", name: { en: "Music: Music in the Movies", et: "Muusika: Muusika filmides" } },
  { categorySetId: "built-in-music-set-033", batchId: "06-music", name: { en: "Music: Music in Video Games", et: "Muusika: Muusika videomängudes" } },
  { categorySetId: "built-in-music-set-086", batchId: "06-music", name: { en: "Music: Famous Music Festivals", et: "Muusika: Kuulsad muusikafestivalid" } },
  { categorySetId: "built-in-film-television-set-002", batchId: "07-film-television", name: { en: "Film & Television: Blockbusters of the 1990s", et: "Film ja televisioon: 1990. aastate kassahitid" } },
  { categorySetId: "built-in-film-television-set-003", batchId: "07-film-television", name: { en: "Film & Television: Big-Screen Favourites", et: "Film ja televisioon: Suure ekraani lemmikud" } },
  { categorySetId: "built-in-film-television-set-004", batchId: "07-film-television", name: { en: "Film & Television: Action Heroes, Adventurers, and Villains", et: "Film ja televisioon: Märulikangelased, seiklejad ja kurikaelad" } },
  { categorySetId: "built-in-film-television-set-011", batchId: "07-film-television", name: { en: "Film & Television: Fantasy, Comic, and Adventure Characters", et: "Film ja televisioon: Fantaasia-, koomiksi- ja seiklustegelased" } },
  { categorySetId: "built-in-film-television-set-013", batchId: "07-film-television", name: { en: "Film & Television: Television Ensembles, Families, and Antiheroes", et: "Film ja televisioon: Teleansamblid, perekonnad ja antikangelased" } },
  { categorySetId: "built-in-film-television-set-014", batchId: "07-film-television", name: { en: "Film & Television: Comedy, Drama, and Action Television", et: "Film ja televisioon: Komöödia-, draama- ja märulitelevisioon" } },
  { categorySetId: "built-in-film-television-set-019", batchId: "07-film-television", name: { en: "Film & Television: Hollywood Stars of Drama and Comedy", et: "Film ja televisioon: Hollywoodi draama- ja komöödiatähed" } },
  { categorySetId: "built-in-film-television-set-020", batchId: "07-film-television", name: { en: "Film & Television: Comedy, Fantasy, and Modern Screen Stars", et: "Film ja televisioon: Komöödia-, fantaasia- ja tänapäeva ekraanitähed" } },
  { categorySetId: "built-in-film-television-set-021", batchId: "07-film-television", name: { en: "Film & Television: Animated Classics", et: "Film ja televisioon: Animatsiooniklassika" } },
  { categorySetId: "built-in-film-television-set-025", batchId: "07-film-television", name: { en: "Film & Television: Pixar Favourites", et: "Film ja televisioon: Pixari lemmikud" } },
  { categorySetId: "built-in-film-television-set-027", batchId: "07-film-television", name: { en: "Film & Television: Disney Heroes", et: "Film ja televisioon: Disney kangelased" } },
  { categorySetId: "built-in-film-television-set-029", batchId: "07-film-television", name: { en: "Film & Television: Superhero Films", et: "Film ja televisioon: Superkangelaste filmid" } },
  { categorySetId: "built-in-film-television-set-034", batchId: "07-film-television", name: { en: "Film & Television: Science Fiction Films", et: "Film ja televisioon: Ulmefilmid" } },
  { categorySetId: "built-in-film-television-set-042", batchId: "07-film-television", name: { en: "Film & Television: Fantasy Films", et: "Film ja televisioon: Fantaasiafilmid" } },
  { categorySetId: "built-in-film-television-set-043", batchId: "07-film-television", name: { en: "Film & Television: Action Films", et: "Film ja televisioon: Märulifilmid" } },
  { categorySetId: "built-in-film-television-set-044", batchId: "07-film-television", name: { en: "Film & Television: Film Comedies", et: "Film ja televisioon: Filmikomöödiad" } },
  { categorySetId: "built-in-film-television-set-046", batchId: "07-film-television", name: { en: "Film & Television: Romantic Comedies", et: "Film ja televisioon: Romantilised komöödiad" } },
  { categorySetId: "built-in-film-television-set-049", batchId: "07-film-television", name: { en: "Film & Television: Family Films", et: "Film ja televisioon: Perefilmid" } },
  { categorySetId: "built-in-film-television-set-050", batchId: "07-film-television", name: { en: "Film & Television: 1990s Science-Fiction Blockbusters", et: "Film ja televisioon: 1990. aastate ulmekassahitid" } },
  { categorySetId: "built-in-film-television-set-051", batchId: "07-film-television", name: { en: "Film & Television: Films of the 2000s", et: "Film ja televisioon: 2000. aastate filmid" } },
  { categorySetId: "built-in-film-television-set-054", batchId: "07-film-television", name: { en: "Film & Television: Films of the 2010s", et: "Film ja televisioon: 2010. aastate filmid" } },
  { categorySetId: "built-in-film-television-set-055", batchId: "07-film-television", name: { en: "Film & Television: Television Sitcoms", et: "Film ja televisioon: Telekomöödiasarjad" } },
  { categorySetId: "built-in-film-television-set-058", batchId: "07-film-television", name: { en: "Film & Television: Television Crime Dramas", et: "Film ja televisioon: Telekrimisarjad" } },
  { categorySetId: "built-in-film-television-set-065", batchId: "07-film-television", name: { en: "Film & Television: Fantasy on Television", et: "Film ja televisioon: Fantaasia televisioonis" } },
  { categorySetId: "built-in-film-television-set-067", batchId: "07-film-television", name: { en: "Film & Television: Reality Television Formats", et: "Film ja televisioon: Tõsielutelevisiooni formaadid" } },
  { categorySetId: "built-in-film-television-set-068", batchId: "07-film-television", name: { en: "Film & Television: Television Game Shows", et: "Film ja televisioon: Telemängud" } },
  { categorySetId: "built-in-film-television-set-071", batchId: "07-film-television", name: { en: "Film & Television: Famous Film Directors", et: "Film ja televisioon: Kuulsad filmirežissöörid" } },
  { categorySetId: "built-in-film-television-set-075", batchId: "07-film-television", name: { en: "Film & Television: Memorable Film Music", et: "Film ja televisioon: Meeldejääv filmimuusika" } },
  { categorySetId: "built-in-film-television-set-076", batchId: "07-film-television", name: { en: "Film & Television: Oscar-Winning Actors", et: "Film ja televisioon: Oscari võitnud näitlejad" } },
  { categorySetId: "built-in-film-television-set-077", batchId: "07-film-television", name: { en: "Film & Television: European Cinema", et: "Film ja televisioon: Euroopa filmikunst" } },
  { categorySetId: "built-in-film-television-set-078", batchId: "07-film-television", name: { en: "Film & Television: Nordic Screen Stories", et: "Film ja televisioon: Põhjamaade ekraanilood" } },
  { categorySetId: "built-in-film-television-set-079", batchId: "07-film-television", name: { en: "Film & Television: Famous Film Props", et: "Film ja televisioon: Kuulsad filmirekvisiidid" } },
  { categorySetId: "built-in-film-television-set-089", batchId: "07-film-television", name: { en: "Film & Television: Famous Filming Locations", et: "Film ja televisioon: Kuulsad võttepaigad" } },
  { categorySetId: "built-in-sports-games-set-001", batchId: "08-sports-games", name: { en: "Sports & Games: Popular Team and Racket Sports", et: "Sport ja mängud: Populaarsed meeskonna- ja reketialad" } },
  { categorySetId: "built-in-sports-games-set-002", batchId: "08-sports-games", name: { en: "Sports & Games: Precision, Combat, Motor, Winter, and Track Sports", et: "Sport ja mängud: Täpsus-, võitlus-, moto-, tali- ja staadionialad" } },
  { categorySetId: "built-in-sports-games-set-003", batchId: "08-sports-games", name: { en: "Sports & Games: Global Sports Stars Across Stadiums, Courts, and Tracks", et: "Sport ja mängud: Maailma sporditähed staadionidel, väljakutel ja radadel" } },
  { categorySetId: "built-in-sports-games-set-004", batchId: "08-sports-games", name: { en: "Sports & Games: Champions from Estonia and Beyond", et: "Sport ja mängud: Meistrid Eestist ja mujalt" } },
  { categorySetId: "built-in-sports-games-set-005", batchId: "08-sports-games", name: { en: "Sports & Games: World Championships, Races, and Finals", et: "Sport ja mängud: Maailmameistrivõistlused, võidusõidud ja finaalid" } },
  { categorySetId: "built-in-sports-games-set-006", batchId: "08-sports-games", name: { en: "Sports & Games: Club Competitions and Endurance Races", et: "Sport ja mängud: Klubivõistlused ja kestvusalad" } },
  { categorySetId: "built-in-sports-games-set-007", batchId: "08-sports-games", name: { en: "Sports & Games: Classic Tabletop and Video Games", et: "Sport ja mängud: Klassikalised laua- ja videomängud" } },
  { categorySetId: "built-in-sports-games-set-008", batchId: "08-sports-games", name: { en: "Sports & Games: Games from Cards to Consoles", et: "Sport ja mängud: Mängud kaartidest konsoolideni" } },
  { categorySetId: "built-in-sports-games-set-009", batchId: "08-sports-games", name: { en: "Sports & Games: The Rules of Football", et: "Sport ja mängud: Jalgpalli reeglid" } },
  { categorySetId: "built-in-sports-games-set-010", batchId: "08-sports-games", name: { en: "Sports & Games: Famous Football Stadiums", et: "Sport ja mängud: Kuulsad jalgpallistaadionid" } },
  { categorySetId: "built-in-sports-games-set-011", batchId: "08-sports-games", name: { en: "Sports & Games: Football World Cup Nations", et: "Sport ja mängud: Jalgpalli maailmameistrivõistluste riigid" } },
  { categorySetId: "built-in-sports-games-set-012", batchId: "08-sports-games", name: { en: "Sports & Games: Famous Football Clubs", et: "Sport ja mängud: Kuulsad jalgpalliklubid" } },
  { categorySetId: "built-in-sports-games-set-013", batchId: "08-sports-games", name: { en: "Sports & Games: Basketball Basics", et: "Sport ja mängud: Korvpalli põhitõed" } },
  { categorySetId: "built-in-sports-games-set-014", batchId: "08-sports-games", name: { en: "Sports & Games: Tennis Grand Slams", et: "Sport ja mängud: Tennise suure slämmi turniirid" } },
  { categorySetId: "built-in-sports-games-set-015", batchId: "08-sports-games", name: { en: "Sports & Games: Ice Hockey", et: "Sport ja mängud: Jäähoki" } },
  { categorySetId: "built-in-sports-games-set-016", batchId: "08-sports-games", name: { en: "Sports & Games: The Summer Olympics", et: "Sport ja mängud: Suveolümpiamängud" } },
  { categorySetId: "built-in-sports-games-set-051", batchId: "08-sports-games", name: { en: "Sports & Games: The Winter Olympics", et: "Sport ja mängud: Taliolümpiamängud" } },
  { categorySetId: "built-in-sports-games-set-052", batchId: "08-sports-games", name: { en: "Sports & Games: Track and Field", et: "Sport ja mängud: Kergejõustik" } },
  { categorySetId: "built-in-sports-games-set-053", batchId: "08-sports-games", name: { en: "Sports & Games: Competitive Swimming", et: "Sport ja mängud: Võistlusujumine" } },
  { categorySetId: "built-in-sports-games-set-054", batchId: "08-sports-games", name: { en: "Sports & Games: Road Cycling", et: "Sport ja mängud: Maanteerattasõit" } },
  { categorySetId: "built-in-sports-games-set-055", batchId: "08-sports-games", name: { en: "Sports & Games: Motor Racing", et: "Sport ja mängud: Autovõidusõit" } },
  { categorySetId: "built-in-sports-games-set-056", batchId: "08-sports-games", name: { en: "Sports & Games: Skiing", et: "Sport ja mängud: Suusatamine" } },
  { categorySetId: "built-in-sports-games-set-057", batchId: "08-sports-games", name: { en: "Sports & Games: Skating Sports", et: "Sport ja mängud: Uisualad" } },
  { categorySetId: "built-in-sports-games-set-058", batchId: "08-sports-games", name: { en: "Sports & Games: Combat Sports", et: "Sport ja mängud: Võitlusspordialad" } },
  { categorySetId: "built-in-sports-games-set-059", batchId: "08-sports-games", name: { en: "Sports & Games: Golf", et: "Sport ja mängud: Golf" } },
  { categorySetId: "built-in-sports-games-set-060", batchId: "08-sports-games", name: { en: "Sports & Games: Volleyball", et: "Sport ja mängud: Võrkpall" } },
  { categorySetId: "built-in-sports-games-set-061", batchId: "08-sports-games", name: { en: "Sports & Games: Table Tennis", et: "Sport ja mängud: Lauatennis" } },
  { categorySetId: "built-in-sports-games-set-062", batchId: "08-sports-games", name: { en: "Sports & Games: Chess Basics", et: "Sport ja mängud: Male põhitõed" } },
  { categorySetId: "built-in-sports-games-set-063", batchId: "08-sports-games", name: { en: "Sports & Games: Card Games", et: "Sport ja mängud: Kaardimängud" } },
  { categorySetId: "built-in-sports-games-set-064", batchId: "08-sports-games", name: { en: "Sports & Games: Board Games", et: "Sport ja mängud: Lauamängud" } },
  { categorySetId: "built-in-sports-games-set-065", batchId: "08-sports-games", name: { en: "Sports & Games: Classic Video Games", et: "Sport ja mängud: Klassikalised videomängud" } },
  { categorySetId: "built-in-sports-games-set-066", batchId: "08-sports-games", name: { en: "Sports & Games: Video Games of the 1990s", et: "Sport ja mängud: 1990. aastate videomängud" } },
  { categorySetId: "built-in-sports-games-set-067", batchId: "08-sports-games", name: { en: "Sports & Games: Esports", et: "Sport ja mängud: E-sport" } },
  { categorySetId: "built-in-food-drink-set-001", batchId: "09-food-drink", name: { en: "Food & Drink: Countries Behind Pizza, Sushi, and Tacos", et: "Toit ja jook: Pitsa, sushi ja tako päritoluriigid" } },
  { categorySetId: "built-in-food-drink-set-002", batchId: "09-food-drink", name: { en: "Food & Drink: Countries Behind Fish and Chips, Kimchi, and Burgers", et: "Toit ja jook: Kala ja friikartulite, kimchi ning burgerite päritoluriigid" } },
  { categorySetId: "built-in-food-drink-set-003", batchId: "09-food-drink", name: { en: "Food & Drink: Ingredients in Dips, Pesto, Ferments, and Sweets", et: "Toit ja jook: Dipikastmete, pesto, hapendiste ja maiuste koostisosad" } },
  { categorySetId: "built-in-food-drink-set-004", batchId: "09-food-drink", name: { en: "Food & Drink: Ingredients in Tofu, Popcorn, Omelettes, Mash, and Chocolate", et: "Toit ja jook: Tofu, popkorni, omleti, kartulipudru ja šokolaadi koostisosad" } },
  { categorySetId: "built-in-food-drink-set-005", batchId: "09-food-drink", name: { en: "Food & Drink: Hot Drinks, Juice, and Fruit Blends", et: "Toit ja jook: Kuumad joogid, mahl ja puuviljasegud" } },
  { categorySetId: "built-in-food-drink-set-006", batchId: "09-food-drink", name: { en: "Food & Drink: Café, Dairy, and Mineral Drinks", et: "Toit ja jook: Kohviku-, piima- ja mineraaljoogid" } },
  { categorySetId: "built-in-food-drink-set-007", batchId: "09-food-drink", name: { en: "Food & Drink: Meals and Ways of Eating", et: "Toit ja jook: Söögikorrad ja söömisviisid" } },
  { categorySetId: "built-in-food-drink-set-008", batchId: "09-food-drink", name: { en: "Food & Drink: Everyday Dishes, Desserts, and Dairy Foods", et: "Toit ja jook: Igapäevased road, maiused ja piimatooted" } },
  { categorySetId: "built-in-food-drink-set-009", batchId: "09-food-drink", name: { en: "Food & Drink: Fruits", et: "Toit ja jook: Puuviljad" } },
  { categorySetId: "built-in-food-drink-set-010", batchId: "09-food-drink", name: { en: "Food & Drink: Vegetables", et: "Toit ja jook: Köögiviljad" } },
  { categorySetId: "built-in-food-drink-set-011", batchId: "09-food-drink", name: { en: "Food & Drink: Fresh Herbs", et: "Toit ja jook: Värsked maitsetaimed" } },
  { categorySetId: "built-in-food-drink-set-012", batchId: "09-food-drink", name: { en: "Food & Drink: Spices", et: "Toit ja jook: Vürtsid" } },
  { categorySetId: "built-in-food-drink-set-013", batchId: "09-food-drink", name: { en: "Food & Drink: Breads of the World", et: "Toit ja jook: Maailma leivad" } },
  { categorySetId: "built-in-food-drink-set-014", batchId: "09-food-drink", name: { en: "Food & Drink: Cheeses of the World", et: "Toit ja jook: Maailma juustud" } },
  { categorySetId: "built-in-food-drink-set-015", batchId: "09-food-drink", name: { en: "Food & Drink: Pasta Shapes", et: "Toit ja jook: Pastakujud" } },
  { categorySetId: "built-in-food-drink-set-016", batchId: "09-food-drink", name: { en: "Food & Drink: Rice Dishes", et: "Toit ja jook: Riisiroad" } },
  { categorySetId: "built-in-food-drink-set-017", batchId: "09-food-drink", name: { en: "Food & Drink: Soups", et: "Toit ja jook: Supid" } },
  { categorySetId: "built-in-food-drink-set-018", batchId: "09-food-drink", name: { en: "Food & Drink: Salads", et: "Toit ja jook: Salatid" } },
  { categorySetId: "built-in-food-drink-set-019", batchId: "09-food-drink", name: { en: "Food & Drink: Breakfast Foods", et: "Toit ja jook: Hommikusöögid" } },
  { categorySetId: "built-in-food-drink-set-020", batchId: "09-food-drink", name: { en: "Food & Drink: Desserts", et: "Toit ja jook: Magustoidud" } },
  { categorySetId: "built-in-food-drink-set-021", batchId: "09-food-drink", name: { en: "Food & Drink: Chocolate", et: "Toit ja jook: Šokolaad" } },
  { categorySetId: "built-in-food-drink-set-022", batchId: "09-food-drink", name: { en: "Food & Drink: Ice Cream", et: "Toit ja jook: Jäätis" } },
  { categorySetId: "built-in-food-drink-set-023", batchId: "09-food-drink", name: { en: "Food & Drink: Coffee", et: "Toit ja jook: Kohv" } },
  { categorySetId: "built-in-food-drink-set-024", batchId: "09-food-drink", name: { en: "Food & Drink: Tea", et: "Toit ja jook: Tee" } },
  { categorySetId: "built-in-food-drink-set-025", batchId: "09-food-drink", name: { en: "Food & Drink: Fruit Juices", et: "Toit ja jook: Puuviljamahlad" } },
  { categorySetId: "built-in-food-drink-set-026", batchId: "09-food-drink", name: { en: "Food & Drink: Kitchen Tools", et: "Toit ja jook: Köögiriistad" } },
  { categorySetId: "built-in-food-drink-set-027", batchId: "09-food-drink", name: { en: "Food & Drink: Cooking Methods", et: "Toit ja jook: Toiduvalmistamise viisid" } },
  { categorySetId: "built-in-food-drink-set-028", batchId: "09-food-drink", name: { en: "Food & Drink: Baking Basics", et: "Toit ja jook: Küpsetamise põhitõed" } },
  { categorySetId: "built-in-food-drink-set-029", batchId: "09-food-drink", name: { en: "Food & Drink: Italian Food", et: "Toit ja jook: Itaalia toit" } },
  { categorySetId: "built-in-food-drink-set-030", batchId: "09-food-drink", name: { en: "Food & Drink: Mexican Food", et: "Toit ja jook: Mehhiko toit" } },
  { categorySetId: "built-in-food-drink-set-031", batchId: "09-food-drink", name: { en: "Food & Drink: Japanese Food", et: "Toit ja jook: Jaapani toit" } },
  { categorySetId: "built-in-food-drink-set-032", batchId: "09-food-drink", name: { en: "Food & Drink: Nordic Food", et: "Toit ja jook: Põhjamaade toit" } },
  { categorySetId: "built-in-food-drink-set-033", batchId: "09-food-drink", name: { en: "Food & Drink: Baltic Food", et: "Toit ja jook: Baltimaade toit" } },
  { categorySetId: "built-in-technology-inventions-set-001", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Companies Behind Phones, Software, Games, and E-Readers", et: "Tehnoloogia ja leiutised: Telefonide, tarkvara, mängude ja e-lugerite ettevõtted" } },
  { categorySetId: "built-in-technology-inventions-set-002", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Makers Behind Mobiles, Consoles, and Mini Computers", et: "Tehnoloogia ja leiutised: Mobiilide, konsoolide ja miniarvutite loojad" } },
  { categorySetId: "built-in-technology-inventions-set-003", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Browsing, Messaging, and Wireless Connections", et: "Tehnoloogia ja leiutised: Sirvimine, sõnumside ja juhtmeta ühendused" } },
  { categorySetId: "built-in-technology-inventions-set-004", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Codes, Symbols, Cloud Services, and Account Security", et: "Tehnoloogia ja leiutised: Koodid, sümbolid, pilveteenused ja kontoturve" } },
  { categorySetId: "built-in-technology-inventions-set-005", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Pioneers of Telephones, Print, Light, and Explosives", et: "Tehnoloogia ja leiutised: Telefoni, trüki, valguse ja lõhkeainete teerajajad" } },
  { categorySetId: "built-in-technology-inventions-set-006", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Pioneers of Medicine, Radio, Engines, and Reading", et: "Tehnoloogia ja leiutised: Meditsiini, raadio, mootorite ja lugemise teerajajad" } },
  { categorySetId: "built-in-technology-inventions-set-007", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Navigation, Computer, and Web Initials", et: "Tehnoloogia ja leiutised: Navigatsiooni-, arvuti- ja veebialühendid" } },
  { categorySetId: "built-in-technology-inventions-set-008", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Memory, Messaging, Mobile, and AI Initials", et: "Tehnoloogia ja leiutised: Mälu-, sõnumi-, mobiili- ja tehisarulühendid" } },
  { categorySetId: "built-in-technology-inventions-set-009", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Parts of a Computer", et: "Tehnoloogia ja leiutised: Arvuti osad" } },
  { categorySetId: "built-in-technology-inventions-set-010", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Computer Input Devices", et: "Tehnoloogia ja leiutised: Arvuti sisendseadmed" } },
  { categorySetId: "built-in-technology-inventions-set-011", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Digital Storage", et: "Tehnoloogia ja leiutised: Digitaalne andmesalvestus" } },
  { categorySetId: "built-in-technology-inventions-set-012", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Files and Formats", et: "Tehnoloogia ja leiutised: Failid ja vormingud" } },
  { categorySetId: "built-in-technology-inventions-set-013", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: How the Web Works", et: "Tehnoloogia ja leiutised: Kuidas veeb toimib" } },
  { categorySetId: "built-in-technology-inventions-set-014", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Browsers and Search Engines", et: "Tehnoloogia ja leiutised: Brauserid ja otsingumootorid" } },
  { categorySetId: "built-in-technology-inventions-set-015", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Email and Messaging", et: "Tehnoloogia ja leiutised: E-post ja sõnumside" } },
  { categorySetId: "built-in-technology-inventions-set-016", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Social Media of the 2000s", et: "Tehnoloogia ja leiutised: 2000. aastate sotsiaalmeedia" } },
  { categorySetId: "built-in-technology-inventions-set-017", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Smartphones", et: "Tehnoloogia ja leiutised: Nutitelefonid" } },
  { categorySetId: "built-in-technology-inventions-set-018", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Mobile Applications", et: "Tehnoloogia ja leiutised: Mobiilirakendused" } },
  { categorySetId: "built-in-technology-inventions-set-019", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Digital Photography", et: "Tehnoloogia ja leiutised: Digifotograafia" } },
  { categorySetId: "built-in-technology-inventions-set-020", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Sound Technology", et: "Tehnoloogia ja leiutised: Helitehnoloogia" } },
  { categorySetId: "built-in-technology-inventions-set-021", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Television Technology", et: "Tehnoloogia ja leiutised: Televisioonitehnoloogia" } },
  { categorySetId: "built-in-technology-inventions-set-022", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Radio Technology", et: "Tehnoloogia ja leiutised: Raadiotehnoloogia" } },
  { categorySetId: "built-in-technology-inventions-set-023", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Household Appliances", et: "Tehnoloogia ja leiutised: Kodumasinad" } },
  { categorySetId: "built-in-technology-inventions-set-024", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Transport Inventions", et: "Tehnoloogia ja leiutised: Transpordileiutised" } },
  { categorySetId: "built-in-technology-inventions-set-025", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Medical Inventions", et: "Tehnoloogia ja leiutised: Meditsiinileiutised" } },
  { categorySetId: "built-in-technology-inventions-set-026", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Printing and Publishing", et: "Tehnoloogia ja leiutised: Trükkimine ja kirjastamine" } },
  { categorySetId: "built-in-technology-inventions-set-027", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Pioneers of Communication", et: "Tehnoloogia ja leiutised: Sidepidamise teerajajad" } },
  { categorySetId: "built-in-technology-inventions-set-028", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Programming Basics", et: "Tehnoloogia ja leiutised: Programmeerimise põhitõed" } },
  { categorySetId: "built-in-technology-inventions-set-029", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Cybersecurity Basics", et: "Tehnoloogia ja leiutised: Küberturvalisuse põhitõed" } },
  { categorySetId: "built-in-technology-inventions-set-030", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Internet Safety", et: "Tehnoloogia ja leiutised: Internetiohutus" } },
  { categorySetId: "built-in-technology-inventions-set-031", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Robotics", et: "Tehnoloogia ja leiutised: Robootika" } },
  { categorySetId: "built-in-technology-inventions-set-032", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Space Technology", et: "Tehnoloogia ja leiutised: Kosmosetehnoloogia" } },
  { categorySetId: "built-in-technology-inventions-set-033", batchId: "10-technology-inventions", name: { en: "Technology & Inventions: Green Technology", et: "Tehnoloogia ja leiutised: Rohetehnoloogia" } },
  { categorySetId: "built-in-politics-economics-society-set-001", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Global Cooperation and European Institutions", et: "Poliitika, majandus ja ühiskond: Maailmakoostöö ja Euroopa institutsioonid" } },
  { categorySetId: "built-in-politics-economics-society-set-002", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Major International and Estonian Institutions", et: "Poliitika, majandus ja ühiskond: Suured rahvusvahelised ja Eesti institutsioonid" } },
  { categorySetId: "built-in-politics-economics-society-set-003", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Currencies Around the Atlantic and Baltic", et: "Poliitika, majandus ja ühiskond: Atlandi ja Läänemere ümbruse vääringud" } },
  { categorySetId: "built-in-politics-economics-society-set-004", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Currencies of Europe and Asia", et: "Poliitika, majandus ja ühiskond: Euroopa ja Aasia vääringud" } },
  { categorySetId: "built-in-politics-economics-society-set-005", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Choosing Leaders and Organising Government", et: "Poliitika, majandus ja ühiskond: Juhtide valimine ja riigikorraldus" } },
  { categorySetId: "built-in-politics-economics-society-set-006", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Public Duties, Membership, Politics, and Diplomacy", et: "Poliitika, majandus ja ühiskond: Avalikud kohustused, kuuluvus, poliitika ja diplomaatia" } },
  { categorySetId: "built-in-politics-economics-society-set-007", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Blue, Black, and White Identity and Independence", et: "Poliitika, majandus ja ühiskond: Sinimustvalge identiteet ja iseseisvus" } },
  { categorySetId: "built-in-politics-economics-society-set-008", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Estonian Traditions, Symbols, and Digital Life", et: "Poliitika, majandus ja ühiskond: Eesti traditsioonid, sümbolid ja digielu" } },
  { categorySetId: "built-in-politics-economics-society-set-009", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Democracy Basics", et: "Poliitika, majandus ja ühiskond: Demokraatia põhitõed" } },
  { categorySetId: "built-in-politics-economics-society-set-010", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: How Elections Work", et: "Poliitika, majandus ja ühiskond: Kuidas valimised toimivad" } },
  { categorySetId: "built-in-politics-economics-society-set-011", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Branches of Government", et: "Poliitika, majandus ja ühiskond: Riigivõimu harud" } },
  { categorySetId: "built-in-politics-economics-society-set-012", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Local Government", et: "Poliitika, majandus ja ühiskond: Kohalik omavalitsus" } },
  { categorySetId: "built-in-politics-economics-society-set-013", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Human Rights", et: "Poliitika, majandus ja ühiskond: Inimõigused" } },
  { categorySetId: "built-in-politics-economics-society-set-014", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: The United Nations", et: "Poliitika, majandus ja ühiskond: Ühinenud Rahvaste Organisatsioon" } },
  { categorySetId: "built-in-politics-economics-society-set-015", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: The European Union", et: "Poliitika, majandus ja ühiskond: Euroopa Liit" } },
  { categorySetId: "built-in-politics-economics-society-set-016", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: NATO", et: "Poliitika, majandus ja ühiskond: NATO" } },
  { categorySetId: "built-in-politics-economics-society-set-017", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Charities and Aid Organisations", et: "Poliitika, majandus ja ühiskond: Heategevus- ja abiorganisatsioonid" } },
  { categorySetId: "built-in-politics-economics-society-set-018", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Taxes", et: "Poliitika, majandus ja ühiskond: Maksud" } },
  { categorySetId: "built-in-politics-economics-society-set-019", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Banks and Saving", et: "Poliitika, majandus ja ühiskond: Pangad ja säästmine" } },
  { categorySetId: "built-in-politics-economics-society-set-020", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Currencies of the World", et: "Poliitika, majandus ja ühiskond: Maailma vääringud" } },
  { categorySetId: "built-in-politics-economics-society-set-021", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: International Trade", et: "Poliitika, majandus ja ühiskond: Rahvusvaheline kaubandus" } },
  { categorySetId: "built-in-politics-economics-society-set-022", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Jobs and Professions", et: "Poliitika, majandus ja ühiskond: Ametid ja elukutsed" } },
  { categorySetId: "built-in-politics-economics-society-set-023", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Public Services", et: "Poliitika, majandus ja ühiskond: Avalikud teenused" } },
  { categorySetId: "built-in-politics-economics-society-set-024", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Education Systems", et: "Poliitika, majandus ja ühiskond: Haridussüsteemid" } },
  { categorySetId: "built-in-politics-economics-society-set-025", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Healthcare Systems", et: "Poliitika, majandus ja ühiskond: Tervishoiusüsteemid" } },
  { categorySetId: "built-in-politics-economics-society-set-026", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: News and Media", et: "Poliitika, majandus ja ühiskond: Uudised ja meedia" } },
  { categorySetId: "built-in-politics-economics-society-set-027", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Population and the Census", et: "Poliitika, majandus ja ühiskond: Rahvastik ja rahvaloendus" } },
  { categorySetId: "built-in-politics-economics-society-set-028", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Citizenship", et: "Poliitika, majandus ja ühiskond: Kodakondsus" } },
  { categorySetId: "built-in-politics-economics-society-set-029", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: National Symbols", et: "Poliitika, majandus ja ühiskond: Riiklikud sümbolid" } },
  { categorySetId: "built-in-politics-economics-society-set-030", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: National Holidays", et: "Poliitika, majandus ja ühiskond: Riigipühad" } },
  { categorySetId: "built-in-politics-economics-society-set-031", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Nordic Welfare", et: "Poliitika, majandus ja ühiskond: Põhjamaade heaoluühiskond" } },
  { categorySetId: "built-in-politics-economics-society-set-032", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Baltic Connections", et: "Poliitika, majandus ja ühiskond: Balti riikide ühendused" } },
  { categorySetId: "built-in-politics-economics-society-set-033", batchId: "11-politics-economics-society", name: { en: "Politics, Economics & Society: Digital Society", et: "Poliitika, majandus ja ühiskond: Digiühiskond" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-001", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: The Olympian Gods", et: "Mütoloogia, religioon ja filosoofia: Olümpose jumalad" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-002", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Heroes of Greek Myth", et: "Mütoloogia, religioon ja filosoofia: Kreeka müütide kangelased" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-003", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Creatures of Greek Myth", et: "Mütoloogia, religioon ja filosoofia: Kreeka müütide olendid" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-004", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: The Roman Gods", et: "Mütoloogia, religioon ja filosoofia: Rooma jumalad" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-005", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: The Norse Gods", et: "Mütoloogia, religioon ja filosoofia: Põhjala jumalad" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-006", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Creatures of Norse Myth", et: "Mütoloogia, religioon ja filosoofia: Põhjala müütide olendid" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-007", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: The Gods of Ancient Egypt", et: "Mütoloogia, religioon ja filosoofia: Vana-Egiptuse jumalad" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-008", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Celtic Legends", et: "Mütoloogia, religioon ja filosoofia: Keldi legendid" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-009", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Baltic Mythology", et: "Mütoloogia, religioon ja filosoofia: Balti mütoloogia" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-010", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Estonian Folklore", et: "Mütoloogia, religioon ja filosoofia: Eesti rahvapärimus" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-011", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: The Finnish Kalevala", et: "Mütoloogia, religioon ja filosoofia: Soome Kalevala" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-012", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Creation Myths", et: "Mütoloogia, religioon ja filosoofia: Loomismüüdid" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-013", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Flood Myths", et: "Mütoloogia, religioon ja filosoofia: Veeuputusmüüdid" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-014", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Mythical Tricksters", et: "Mütoloogia, religioon ja filosoofia: Mütoloogilised triksterid" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-015", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Heroic Quests", et: "Mütoloogia, religioon ja filosoofia: Kangelasretked" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-016", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Legendary Objects", et: "Mütoloogia, religioon ja filosoofia: Legendaarsed esemed" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-017", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Dragons in Legend", et: "Mütoloogia, religioon ja filosoofia: Draakonid legendides" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-018", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Giants in Myth", et: "Mütoloogia, religioon ja filosoofia: Hiiglased müütides" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-019", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Mythical Underworlds", et: "Mütoloogia, religioon ja filosoofia: Mütoloogilised allmaailmad" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-020", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Sacred Mountains", et: "Mütoloogia, religioon ja filosoofia: Pühad mäed" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-021", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: The World's Major Religions", et: "Mütoloogia, religioon ja filosoofia: Maailma suuremad religioonid" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-022", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Christianity Basics", et: "Mütoloogia, religioon ja filosoofia: Kristluse põhitõed" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-023", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Judaism Basics", et: "Mütoloogia, religioon ja filosoofia: Judaismi põhitõed" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-024", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Islam Basics", et: "Mütoloogia, religioon ja filosoofia: Islami põhitõed" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-025", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Hinduism Basics", et: "Mütoloogia, religioon ja filosoofia: Hinduismi põhitõed" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-026", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Buddhism Basics", et: "Mütoloogia, religioon ja filosoofia: Budismi põhitõed" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-027", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Sikhism Basics", et: "Mütoloogia, religioon ja filosoofia: Sikhismi põhitõed" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-028", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Religious Festivals", et: "Mütoloogia, religioon ja filosoofia: Usupühad" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-029", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Sacred Texts", et: "Mütoloogia, religioon ja filosoofia: Pühakirjad" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-030", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Places of Worship", et: "Mütoloogia, religioon ja filosoofia: Pühakojad" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-031", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Philosophers of the Ancient World", et: "Mütoloogia, religioon ja filosoofia: Antiikmaailma filosoofid" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-032", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Ideas in Ethics", et: "Mütoloogia, religioon ja filosoofia: Eetika mõisted" } },
  { categorySetId: "built-in-mythology-religion-philosophy-set-033", batchId: "12-mythology-religion-philosophy", name: { en: "Mythology, Religion & Philosophy: Logic and Reasoning", et: "Mütoloogia, religioon ja filosoofia: Loogika ja arutlemine" } },
] as const satisfies readonly CategoryTitle[];
