export type LegacyEasyTarget = Readonly<{ categorySetId: string; batchId: string }>;

export const ACCESSIBLE_EASY_SET_IDS = [
  'built-in-history-set-000',
  'built-in-history-set-003',
  'built-in-history-set-011',
  'built-in-history-set-013',
  'built-in-history-set-017',
  'built-in-history-set-019',
  'built-in-history-set-024',
  'built-in-history-set-026',
  'built-in-geography-set-001',
  'built-in-geography-set-003',
  'built-in-geography-set-010',
  'built-in-geography-set-011',
  'built-in-geography-set-013',
  'built-in-geography-set-018',
  'built-in-geography-set-030',
  'built-in-geography-set-033',
  'built-in-science-nature-set-000',
  'built-in-science-nature-set-001',
  'built-in-science-nature-set-002',
  'built-in-science-nature-set-003',
  'built-in-science-nature-set-004',
  'built-in-science-nature-set-007',
  'built-in-science-nature-set-010',
  'built-in-science-nature-set-011',
  'built-in-literature-language-set-001',
  'built-in-literature-language-set-002',
  'built-in-literature-language-set-003',
  'built-in-literature-language-set-004',
  'built-in-literature-language-set-005',
  'built-in-literature-language-set-006',
  'built-in-literature-language-set-022',
  'built-in-literature-language-set-032',
  'built-in-music-set-001',
  'built-in-music-set-002',
  'built-in-music-set-003',
  'built-in-music-set-004',
  'built-in-music-set-005',
  'built-in-music-set-006',
  'built-in-music-set-007',
  'built-in-music-set-008',
  'built-in-film-television-set-002',
  'built-in-film-television-set-003',
  'built-in-film-television-set-004',
  'built-in-film-television-set-011',
  'built-in-film-television-set-013',
  'built-in-film-television-set-014',
  'built-in-film-television-set-019',
  'built-in-film-television-set-020',
  'built-in-sports-games-set-001',
  'built-in-sports-games-set-002',
  'built-in-sports-games-set-003',
  'built-in-sports-games-set-004',
  'built-in-sports-games-set-005',
  'built-in-sports-games-set-006',
  'built-in-sports-games-set-007',
  'built-in-sports-games-set-008',
  'built-in-food-drink-set-001',
  'built-in-food-drink-set-002',
  'built-in-food-drink-set-003',
  'built-in-food-drink-set-004',
  'built-in-food-drink-set-005',
  'built-in-food-drink-set-006',
  'built-in-food-drink-set-007',
  'built-in-food-drink-set-008',
  'built-in-technology-inventions-set-001',
  'built-in-technology-inventions-set-002',
  'built-in-technology-inventions-set-003',
  'built-in-technology-inventions-set-004',
  'built-in-technology-inventions-set-005',
  'built-in-technology-inventions-set-006',
  'built-in-technology-inventions-set-007',
  'built-in-technology-inventions-set-008',
  'built-in-politics-economics-society-set-001',
  'built-in-politics-economics-society-set-002',
  'built-in-politics-economics-society-set-003',
  'built-in-politics-economics-society-set-004',
  'built-in-politics-economics-society-set-005',
  'built-in-politics-economics-society-set-006',
  'built-in-politics-economics-society-set-007',
  'built-in-politics-economics-society-set-008',
] as const;

export const LEGACY_EASY_TARGETS = [
  { categorySetId: 'built-in-history-set-030', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-033', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-035', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-043', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-050', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-053', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-060', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-070', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-074', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-001', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-010', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-012', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-014', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-018', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-023', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-025', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-029', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-031', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-034', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-039', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-049', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-051', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-052', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-055', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-072', batchId: '01-history' },
  { categorySetId: 'built-in-history-set-092', batchId: '01-history' },
  { categorySetId: 'built-in-geography-set-037', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-055', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-057', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-062', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-064', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-066', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-073', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-082', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-088', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-002', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-004', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-012', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-015', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-024', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-027', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-029', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-032', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-047', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-058', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-065', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-072', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-074', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-077', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-080', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-085', batchId: '02-geography' },
  { categorySetId: 'built-in-geography-set-094', batchId: '02-geography' },
  { categorySetId: 'built-in-science-nature-set-013', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-014', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-015', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-016', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-034', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-039', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-040', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-081', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-084', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-017', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-018', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-019', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-021', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-022', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-023', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-026', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-027', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-028', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-029', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-030', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-032', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-051', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-085', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-090', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-094', batchId: '03-science-nature' },
  { categorySetId: 'built-in-science-nature-set-097', batchId: '03-science-nature' },
  { categorySetId: 'built-in-literature-language-set-035', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-036', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-069', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-072', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-077', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-080', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-090', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-091', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-093', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-011', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-014', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-016', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-021', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-023', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-024', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-026', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-028', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-030', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-054', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-081', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-082', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-092', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-094', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-096', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-098', batchId: '04-literature-language' },
  { categorySetId: 'built-in-literature-language-set-100', batchId: '04-literature-language' },
  { categorySetId: 'built-in-art-architecture-set-001', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-002', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-003', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-004', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-005', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-006', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-007', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-008', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-009', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-010', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-011', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-012', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-013', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-014', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-015', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-016', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-017', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-018', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-019', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-020', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-021', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-022', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-023', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-024', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-025', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-026', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-027', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-028', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-029', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-030', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-031', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-032', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-art-architecture-set-033', batchId: '05-art-architecture' },
  { categorySetId: 'built-in-music-set-009', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-011', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-012', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-013', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-014', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-015', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-016', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-086', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-017', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-018', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-019', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-020', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-021', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-022', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-023', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-024', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-025', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-026', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-027', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-028', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-029', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-030', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-031', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-032', batchId: '06-music' },
  { categorySetId: 'built-in-music-set-033', batchId: '06-music' },
  { categorySetId: 'built-in-film-television-set-021', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-025', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-027', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-029', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-034', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-042', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-043', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-044', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-046', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-049', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-050', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-051', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-054', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-055', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-058', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-065', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-067', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-068', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-071', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-075', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-076', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-077', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-078', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-079', batchId: '07-film-television' },
  { categorySetId: 'built-in-film-television-set-089', batchId: '07-film-television' },
  { categorySetId: 'built-in-sports-games-set-009', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-010', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-011', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-012', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-013', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-014', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-015', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-016', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-051', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-052', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-053', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-054', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-055', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-056', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-057', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-058', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-059', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-060', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-061', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-062', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-063', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-064', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-065', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-066', batchId: '08-sports-games' },
  { categorySetId: 'built-in-sports-games-set-067', batchId: '08-sports-games' },
  { categorySetId: 'built-in-food-drink-set-009', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-010', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-011', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-012', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-013', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-014', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-015', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-016', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-017', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-018', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-019', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-020', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-021', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-022', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-023', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-024', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-025', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-026', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-027', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-028', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-029', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-030', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-031', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-032', batchId: '09-food-drink' },
  { categorySetId: 'built-in-food-drink-set-033', batchId: '09-food-drink' },
  { categorySetId: 'built-in-technology-inventions-set-009', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-010', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-011', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-012', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-013', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-014', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-015', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-016', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-017', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-018', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-019', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-020', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-021', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-022', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-023', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-024', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-025', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-026', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-027', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-028', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-029', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-030', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-031', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-032', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-technology-inventions-set-033', batchId: '10-technology-inventions' },
  { categorySetId: 'built-in-politics-economics-society-set-009', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-010', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-011', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-012', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-013', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-014', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-015', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-016', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-017', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-018', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-019', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-020', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-021', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-022', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-023', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-024', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-025', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-026', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-027', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-028', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-029', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-030', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-031', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-032', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-politics-economics-society-set-033', batchId: '11-politics-economics-society' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-001', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-002', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-003', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-004', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-005', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-006', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-007', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-008', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-009', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-010', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-011', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-012', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-013', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-014', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-015', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-016', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-017', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-018', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-019', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-020', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-021', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-022', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-023', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-024', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-025', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-026', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-027', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-028', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-029', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-030', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-031', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-032', batchId: '12-mythology-religion-philosophy' },
  { categorySetId: 'built-in-mythology-religion-philosophy-set-033', batchId: '12-mythology-religion-philosophy' },
] as const satisfies readonly LegacyEasyTarget[];

export const LEGACY_EASY_TARGET_IDS = [
  'built-in-history-set-030',
  'built-in-history-set-033',
  'built-in-history-set-035',
  'built-in-history-set-043',
  'built-in-history-set-050',
  'built-in-history-set-053',
  'built-in-history-set-060',
  'built-in-history-set-070',
  'built-in-history-set-074',
  'built-in-history-set-001',
  'built-in-history-set-010',
  'built-in-history-set-012',
  'built-in-history-set-014',
  'built-in-history-set-018',
  'built-in-history-set-023',
  'built-in-history-set-025',
  'built-in-history-set-029',
  'built-in-history-set-031',
  'built-in-history-set-034',
  'built-in-history-set-039',
  'built-in-history-set-049',
  'built-in-history-set-051',
  'built-in-history-set-052',
  'built-in-history-set-055',
  'built-in-history-set-072',
  'built-in-history-set-092',
  'built-in-geography-set-037',
  'built-in-geography-set-055',
  'built-in-geography-set-057',
  'built-in-geography-set-062',
  'built-in-geography-set-064',
  'built-in-geography-set-066',
  'built-in-geography-set-073',
  'built-in-geography-set-082',
  'built-in-geography-set-088',
  'built-in-geography-set-002',
  'built-in-geography-set-004',
  'built-in-geography-set-012',
  'built-in-geography-set-015',
  'built-in-geography-set-024',
  'built-in-geography-set-027',
  'built-in-geography-set-029',
  'built-in-geography-set-032',
  'built-in-geography-set-047',
  'built-in-geography-set-058',
  'built-in-geography-set-065',
  'built-in-geography-set-072',
  'built-in-geography-set-074',
  'built-in-geography-set-077',
  'built-in-geography-set-080',
  'built-in-geography-set-085',
  'built-in-geography-set-094',
  'built-in-science-nature-set-013',
  'built-in-science-nature-set-014',
  'built-in-science-nature-set-015',
  'built-in-science-nature-set-016',
  'built-in-science-nature-set-034',
  'built-in-science-nature-set-039',
  'built-in-science-nature-set-040',
  'built-in-science-nature-set-081',
  'built-in-science-nature-set-084',
  'built-in-science-nature-set-017',
  'built-in-science-nature-set-018',
  'built-in-science-nature-set-019',
  'built-in-science-nature-set-021',
  'built-in-science-nature-set-022',
  'built-in-science-nature-set-023',
  'built-in-science-nature-set-026',
  'built-in-science-nature-set-027',
  'built-in-science-nature-set-028',
  'built-in-science-nature-set-029',
  'built-in-science-nature-set-030',
  'built-in-science-nature-set-032',
  'built-in-science-nature-set-051',
  'built-in-science-nature-set-085',
  'built-in-science-nature-set-090',
  'built-in-science-nature-set-094',
  'built-in-science-nature-set-097',
  'built-in-literature-language-set-035',
  'built-in-literature-language-set-036',
  'built-in-literature-language-set-069',
  'built-in-literature-language-set-072',
  'built-in-literature-language-set-077',
  'built-in-literature-language-set-080',
  'built-in-literature-language-set-090',
  'built-in-literature-language-set-091',
  'built-in-literature-language-set-093',
  'built-in-literature-language-set-011',
  'built-in-literature-language-set-014',
  'built-in-literature-language-set-016',
  'built-in-literature-language-set-021',
  'built-in-literature-language-set-023',
  'built-in-literature-language-set-024',
  'built-in-literature-language-set-026',
  'built-in-literature-language-set-028',
  'built-in-literature-language-set-030',
  'built-in-literature-language-set-054',
  'built-in-literature-language-set-081',
  'built-in-literature-language-set-082',
  'built-in-literature-language-set-092',
  'built-in-literature-language-set-094',
  'built-in-literature-language-set-096',
  'built-in-literature-language-set-098',
  'built-in-literature-language-set-100',
  'built-in-art-architecture-set-001',
  'built-in-art-architecture-set-002',
  'built-in-art-architecture-set-003',
  'built-in-art-architecture-set-004',
  'built-in-art-architecture-set-005',
  'built-in-art-architecture-set-006',
  'built-in-art-architecture-set-007',
  'built-in-art-architecture-set-008',
  'built-in-art-architecture-set-009',
  'built-in-art-architecture-set-010',
  'built-in-art-architecture-set-011',
  'built-in-art-architecture-set-012',
  'built-in-art-architecture-set-013',
  'built-in-art-architecture-set-014',
  'built-in-art-architecture-set-015',
  'built-in-art-architecture-set-016',
  'built-in-art-architecture-set-017',
  'built-in-art-architecture-set-018',
  'built-in-art-architecture-set-019',
  'built-in-art-architecture-set-020',
  'built-in-art-architecture-set-021',
  'built-in-art-architecture-set-022',
  'built-in-art-architecture-set-023',
  'built-in-art-architecture-set-024',
  'built-in-art-architecture-set-025',
  'built-in-art-architecture-set-026',
  'built-in-art-architecture-set-027',
  'built-in-art-architecture-set-028',
  'built-in-art-architecture-set-029',
  'built-in-art-architecture-set-030',
  'built-in-art-architecture-set-031',
  'built-in-art-architecture-set-032',
  'built-in-art-architecture-set-033',
  'built-in-music-set-009',
  'built-in-music-set-011',
  'built-in-music-set-012',
  'built-in-music-set-013',
  'built-in-music-set-014',
  'built-in-music-set-015',
  'built-in-music-set-016',
  'built-in-music-set-086',
  'built-in-music-set-017',
  'built-in-music-set-018',
  'built-in-music-set-019',
  'built-in-music-set-020',
  'built-in-music-set-021',
  'built-in-music-set-022',
  'built-in-music-set-023',
  'built-in-music-set-024',
  'built-in-music-set-025',
  'built-in-music-set-026',
  'built-in-music-set-027',
  'built-in-music-set-028',
  'built-in-music-set-029',
  'built-in-music-set-030',
  'built-in-music-set-031',
  'built-in-music-set-032',
  'built-in-music-set-033',
  'built-in-film-television-set-021',
  'built-in-film-television-set-025',
  'built-in-film-television-set-027',
  'built-in-film-television-set-029',
  'built-in-film-television-set-034',
  'built-in-film-television-set-042',
  'built-in-film-television-set-043',
  'built-in-film-television-set-044',
  'built-in-film-television-set-046',
  'built-in-film-television-set-049',
  'built-in-film-television-set-050',
  'built-in-film-television-set-051',
  'built-in-film-television-set-054',
  'built-in-film-television-set-055',
  'built-in-film-television-set-058',
  'built-in-film-television-set-065',
  'built-in-film-television-set-067',
  'built-in-film-television-set-068',
  'built-in-film-television-set-071',
  'built-in-film-television-set-075',
  'built-in-film-television-set-076',
  'built-in-film-television-set-077',
  'built-in-film-television-set-078',
  'built-in-film-television-set-079',
  'built-in-film-television-set-089',
  'built-in-sports-games-set-009',
  'built-in-sports-games-set-010',
  'built-in-sports-games-set-011',
  'built-in-sports-games-set-012',
  'built-in-sports-games-set-013',
  'built-in-sports-games-set-014',
  'built-in-sports-games-set-015',
  'built-in-sports-games-set-016',
  'built-in-sports-games-set-051',
  'built-in-sports-games-set-052',
  'built-in-sports-games-set-053',
  'built-in-sports-games-set-054',
  'built-in-sports-games-set-055',
  'built-in-sports-games-set-056',
  'built-in-sports-games-set-057',
  'built-in-sports-games-set-058',
  'built-in-sports-games-set-059',
  'built-in-sports-games-set-060',
  'built-in-sports-games-set-061',
  'built-in-sports-games-set-062',
  'built-in-sports-games-set-063',
  'built-in-sports-games-set-064',
  'built-in-sports-games-set-065',
  'built-in-sports-games-set-066',
  'built-in-sports-games-set-067',
  'built-in-food-drink-set-009',
  'built-in-food-drink-set-010',
  'built-in-food-drink-set-011',
  'built-in-food-drink-set-012',
  'built-in-food-drink-set-013',
  'built-in-food-drink-set-014',
  'built-in-food-drink-set-015',
  'built-in-food-drink-set-016',
  'built-in-food-drink-set-017',
  'built-in-food-drink-set-018',
  'built-in-food-drink-set-019',
  'built-in-food-drink-set-020',
  'built-in-food-drink-set-021',
  'built-in-food-drink-set-022',
  'built-in-food-drink-set-023',
  'built-in-food-drink-set-024',
  'built-in-food-drink-set-025',
  'built-in-food-drink-set-026',
  'built-in-food-drink-set-027',
  'built-in-food-drink-set-028',
  'built-in-food-drink-set-029',
  'built-in-food-drink-set-030',
  'built-in-food-drink-set-031',
  'built-in-food-drink-set-032',
  'built-in-food-drink-set-033',
  'built-in-technology-inventions-set-009',
  'built-in-technology-inventions-set-010',
  'built-in-technology-inventions-set-011',
  'built-in-technology-inventions-set-012',
  'built-in-technology-inventions-set-013',
  'built-in-technology-inventions-set-014',
  'built-in-technology-inventions-set-015',
  'built-in-technology-inventions-set-016',
  'built-in-technology-inventions-set-017',
  'built-in-technology-inventions-set-018',
  'built-in-technology-inventions-set-019',
  'built-in-technology-inventions-set-020',
  'built-in-technology-inventions-set-021',
  'built-in-technology-inventions-set-022',
  'built-in-technology-inventions-set-023',
  'built-in-technology-inventions-set-024',
  'built-in-technology-inventions-set-025',
  'built-in-technology-inventions-set-026',
  'built-in-technology-inventions-set-027',
  'built-in-technology-inventions-set-028',
  'built-in-technology-inventions-set-029',
  'built-in-technology-inventions-set-030',
  'built-in-technology-inventions-set-031',
  'built-in-technology-inventions-set-032',
  'built-in-technology-inventions-set-033',
  'built-in-politics-economics-society-set-009',
  'built-in-politics-economics-society-set-010',
  'built-in-politics-economics-society-set-011',
  'built-in-politics-economics-society-set-012',
  'built-in-politics-economics-society-set-013',
  'built-in-politics-economics-society-set-014',
  'built-in-politics-economics-society-set-015',
  'built-in-politics-economics-society-set-016',
  'built-in-politics-economics-society-set-017',
  'built-in-politics-economics-society-set-018',
  'built-in-politics-economics-society-set-019',
  'built-in-politics-economics-society-set-020',
  'built-in-politics-economics-society-set-021',
  'built-in-politics-economics-society-set-022',
  'built-in-politics-economics-society-set-023',
  'built-in-politics-economics-society-set-024',
  'built-in-politics-economics-society-set-025',
  'built-in-politics-economics-society-set-026',
  'built-in-politics-economics-society-set-027',
  'built-in-politics-economics-society-set-028',
  'built-in-politics-economics-society-set-029',
  'built-in-politics-economics-society-set-030',
  'built-in-politics-economics-society-set-031',
  'built-in-politics-economics-society-set-032',
  'built-in-politics-economics-society-set-033',
  'built-in-mythology-religion-philosophy-set-001',
  'built-in-mythology-religion-philosophy-set-002',
  'built-in-mythology-religion-philosophy-set-003',
  'built-in-mythology-religion-philosophy-set-004',
  'built-in-mythology-religion-philosophy-set-005',
  'built-in-mythology-religion-philosophy-set-006',
  'built-in-mythology-religion-philosophy-set-007',
  'built-in-mythology-religion-philosophy-set-008',
  'built-in-mythology-religion-philosophy-set-009',
  'built-in-mythology-religion-philosophy-set-010',
  'built-in-mythology-religion-philosophy-set-011',
  'built-in-mythology-religion-philosophy-set-012',
  'built-in-mythology-religion-philosophy-set-013',
  'built-in-mythology-religion-philosophy-set-014',
  'built-in-mythology-religion-philosophy-set-015',
  'built-in-mythology-religion-philosophy-set-016',
  'built-in-mythology-religion-philosophy-set-017',
  'built-in-mythology-religion-philosophy-set-018',
  'built-in-mythology-religion-philosophy-set-019',
  'built-in-mythology-religion-philosophy-set-020',
  'built-in-mythology-religion-philosophy-set-021',
  'built-in-mythology-religion-philosophy-set-022',
  'built-in-mythology-religion-philosophy-set-023',
  'built-in-mythology-religion-philosophy-set-024',
  'built-in-mythology-religion-philosophy-set-025',
  'built-in-mythology-religion-philosophy-set-026',
  'built-in-mythology-religion-philosophy-set-027',
  'built-in-mythology-religion-philosophy-set-028',
  'built-in-mythology-religion-philosophy-set-029',
  'built-in-mythology-religion-philosophy-set-030',
  'built-in-mythology-religion-philosophy-set-031',
  'built-in-mythology-religion-philosophy-set-032',
  'built-in-mythology-religion-philosophy-set-033',
] as const;
