export interface AccessibleEasyQuestion {
  key: string;
  batchId: string;
  difficulty: 'easy';
  subjectKey: string;
  clue: { en: string; et: string };
  response: { en: string; et: string };
  explanation: { en: string; et: string };
  source: { title: string; url: string; license: 'CC-BY-SA-4.0' };
}

export interface OpenTdbInspiration {
  system: 'OpenTDB';
  candidateId: string;
  license: 'CC-BY-SA-4.0';
}

type RelationEntry = readonly [
  slug: string,
  sourceTitle: string,
  promptEn: string,
  promptEt: string,
  answerEn: string,
  answerEt: string,
];

function relationGroup(
  batchId: string,
  group: string,
  entries: readonly RelationEntry[],
  clue: (prompt: string) => string,
  clueEt: (prompt: string) => string,
  explanation: (prompt: string, answer: string) => string,
  explanationEt: (prompt: string, answer: string) => string,
): AccessibleEasyQuestion[] {
  return entries.map(([slug, sourceTitle, promptEn, promptEt, answerEn, answerEt], index) => ({
    key: `${batchId}-${group}-${String(index + 1).padStart(2, '0')}`,
    batchId,
    difficulty: 'easy',
    subjectKey: `accessible-easy:${batchId}:${slug}`,
    clue: { en: clue(promptEn), et: clueEt(promptEt) },
    response: { en: answerEn, et: answerEt },
    explanation: {
      en: explanation(promptEn, answerEn),
      et: explanationEt(promptEt, answerEt),
    },
    source: {
      title: `${sourceTitle} — Wikipedia`,
      url: `https://en.wikipedia.org/wiki/${slug}`,
      license: 'CC-BY-SA-4.0',
    },
  }));
}

const HISTORY = [
  ...relationGroup('01-history', 'years', [
    ['Fall_of_the_Berlin_Wall', 'Fall of the Berlin Wall', 'the Berlin Wall opened', 'Berliini müür avati', '1989', '1989'],
    ['End_of_World_War_II_in_Europe', 'End of World War II in Europe', 'World War II ended in Europe', 'teine maailmasõda Euroopas lõppes', '1945', '1945'],
    ['Estonian_Declaration_of_Independence', 'Estonian Declaration of Independence', 'Estonia first declared independence', 'Eesti kuulutas esimest korda välja iseseisvuse', '1918', '1918'],
    ['French_Revolution', 'French Revolution', 'the French Revolution began', 'Prantsuse revolutsioon algas', '1789', '1789'],
    ['Apollo_11', 'Apollo 11', 'people first landed on the Moon', 'inimesed maandusid esimest korda Kuul', '1969', '1969'],
    ['Sinking_of_the_Titanic', 'Sinking of the Titanic', 'the Titanic sank', 'Titanic uppus', '1912', '1912'],
    ['World_War_I', 'World War I', 'World War I began', 'esimene maailmasõda algas', '1914', '1914'],
    ['Estonian_Restoration_of_Independence', 'Estonian Restoration of Independence', 'Estonia restored its independence', 'Eesti taastas iseseisvuse', '1991', '1991'],
    ['Magna_Carta', 'Magna Carta', 'Magna Carta was sealed', 'Magna Carta pitseeriti', '1215', '1215'],
    ['Voyages_of_Christopher_Columbus', 'Voyages of Christopher Columbus', 'Columbus first reached the Caribbean', 'Kolumbus jõudis esimest korda Kariibi merele', '1492', '1492'],
  ],
  (prompt) => `Which year matches this event: ${prompt}?`,
  (prompt) => `Milline aasta sobib selle sündmusega: ${prompt}?`,
  (prompt, answer) => `The year was ${answer}: ${prompt}.`,
  (prompt, answer) => `Aasta oli ${answer}: ${prompt}.`),
  ...relationGroup('01-history', 'people', [
    ['Napoleon', 'Napoleon', 'the French emperor defeated at Waterloo', 'Waterloo lahingus lüüa saanud Prantsuse keiser', 'Napoleon Bonaparte', 'Napoleon Bonaparte'],
    ['Cleopatra', 'Cleopatra', 'the last active pharaoh of ancient Egypt', 'Vana-Egiptuse viimane valitsev vaarao', 'Cleopatra', 'Kleopatra'],
    ['Julius_Caesar', 'Julius Caesar', 'the Roman leader assassinated on the Ides of March', 'märtsi iididel mõrvatud Rooma riigimees', 'Julius Caesar', 'Julius Caesar'],
    ['Mahatma_Gandhi', 'Mahatma Gandhi', 'the leader associated with nonviolent Indian independence', 'India vägivallatu iseseisvusliikumise juht', 'Mahatma Gandhi', 'Mahatma Gandhi'],
    ['Nelson_Mandela', 'Nelson Mandela', 'the anti-apartheid leader who led South Africa from 1994 to 1999', 'apartheidivastane juht, kes juhtis Lõuna-Aafrikat aastatel 1994–1999', 'Nelson Mandela', 'Nelson Mandela'],
    ['Martin_Luther_King_Jr.', 'Martin Luther King Jr.', 'the American civil-rights leader who delivered “I Have a Dream”', 'Ameerika kodanikuõiguste juht, kes pidas kõne „Mul on üks unistus“', 'Martin Luther King Jr.', 'Martin Luther King Jr.'],
    ['Queen_Victoria', 'Queen Victoria', 'the British queen whose reign gave its name to an era', 'Briti kuninganna, kelle valitsemisaja järgi nimetati terve ajastu', 'Queen Victoria', 'kuninganna Victoria'],
    ['Peter_the_Great', 'Peter the Great', 'the Russian tsar who founded Saint Petersburg', 'Peterburi rajanud Vene tsaar', 'Peter the Great', 'Peeter I'],
    ['Joan_of_Arc', 'Joan of Arc', 'the French heroine also called the Maid of Orléans', 'Prantsuse kangelanna, keda tuntakse Orléansi neitsina', 'Joan of Arc', 'Jeanne d’Arc'],
    ['Winston_Churchill', 'Winston Churchill', 'the British wartime leader from 1940 to 1945 who became famous for defiant speeches', 'aastatel 1940–1945 tegutsenud trotslike kõnede poolest tuntud Briti sõjaaegne juht', 'Winston Churchill', 'Winston Churchill'],
  ],
  (prompt) => `Who was ${prompt}?`,
  (prompt) => `Kes oli ${prompt}?`,
  (prompt, answer) => `${answer} was ${prompt}.`,
  (prompt, answer) => `${answer} oli ${prompt}.`),
  ...relationGroup('01-history', 'places', [
    ['Pompeii', 'Pompeii', 'the Roman city buried by Mount Vesuvius in AD 79', 'Rooma linn, mille Vesuuvi purse mattis 79. aastal', 'Pompeii', 'Pompei'],
    ['Machu_Picchu', 'Machu Picchu', 'the famous Inca citadel high in the Andes', 'kuulus inkade kindluslinn kõrgel Andides', 'Machu Picchu', 'Machu Picchu'],
    ['Stonehenge', 'Stonehenge', 'the prehistoric stone circle in southern England', 'eelajalooline kiviring Lõuna-Inglismaal', 'Stonehenge', 'Stonehenge'],
    ['Colosseum', 'Colosseum', 'the enormous ancient amphitheatre in Rome', 'hiiglaslik antiikne amfiteater Roomas', 'the Colosseum', 'Colosseum'],
    ['Great_Wall_of_China', 'Great Wall of China', 'the long series of fortifications across northern China', 'Põhja-Hiinat läbiv pikk kaitserajatiste süsteem', 'the Great Wall of China', 'Hiina müür'],
    ['Acropolis_of_Athens', 'Acropolis of Athens', 'the hilltop complex containing the Parthenon', 'Parthenoni templiga mäepealne kompleks', 'the Acropolis of Athens', 'Ateena akropol'],
    ['Tower_of_London', 'Tower of London', 'the historic fortress beside the River Thames', 'ajalooline kindlus Thamesi jõe ääres', 'the Tower of London', 'Londoni Tower'],
    ['Auschwitz_concentration_camp', 'Auschwitz concentration camp', 'the Nazi concentration and extermination camp near Oświęcim', 'Oświęcimi lähedal asunud natside koondus- ja hävituslaager', 'Auschwitz', 'Auschwitz'],
    ['Bastille', 'Bastille', 'the Paris fortress-prison stormed in 1789', 'Pariisi kindlusvangla, mis vallutati 1789. aastal', 'the Bastille', 'Bastille'],
    ['Ellis_Island', 'Ellis Island', 'the New York entry point for millions of immigrants', 'New Yorgi saabumiskoht miljonitele sisserändajatele', 'Ellis Island', 'Ellis Island'],
  ],
  (prompt) => `Name ${prompt}.`,
  (prompt) => `Nimeta ${prompt}.`,
  (prompt, answer) => `${answer} is ${prompt}.`,
  (prompt, answer) => `${answer} on ${prompt}.`),
  ...relationGroup('01-history', 'civilizations', [
    ['Ancient_Egypt', 'Ancient Egypt', 'the civilization that built the pyramids at Giza', 'Giza püramiidid rajanud tsivilisatsioon', 'ancient Egypt', 'Vana-Egiptus'],
    ['Roman_Empire', 'Roman Empire', 'the empire whose capital was Rome', 'impeerium, mille pealinn oli Rooma', 'the Roman Empire', 'Rooma impeerium'],
    ['Vikings', 'Vikings', 'the Scandinavian seafarers active during the early Middle Ages', 'varakeskajal tegutsenud Skandinaavia meresõitjad', 'the Vikings', 'viikingid'],
    ['Aztecs', 'Aztecs', 'the Mesoamerican people whose capital was Tenochtitlan', 'Kesk-Ameerika rahvas, kelle pealinn oli Tenochtitlán', 'the Aztecs', 'asteegid'],
    ['Inca_Empire', 'Inca Empire', 'the Andean empire centred in present-day Peru', 'tänapäeva Peruus asunud Andide impeerium', 'the Inca Empire', 'inkade impeerium'],
    ['Ancient_Greece', 'Ancient Greece', 'the civilization associated with Athens, Sparta, and the original Olympic Games', 'Ateena, Sparta ja algsete olümpiamängudega seotud tsivilisatsioon', 'ancient Greece', 'Vana-Kreeka'],
    ['Ottoman_Empire', 'Ottoman Empire', 'the empire ruled by sultans from Constantinople', 'Konstantinoopolist sultanite valitsetud impeerium', 'the Ottoman Empire', 'Osmanite riik'],
    ['Maya_civilization', 'Maya civilization', 'the Mesoamerican civilization known for cities such as Tikal', 'Tikalisuguste linnade poolest tuntud Kesk-Ameerika tsivilisatsioon', 'the Maya civilization', 'maiade tsivilisatsioon'],
    ['Mongol_Empire', 'Mongol Empire', 'the vast empire founded by Genghis Khan', 'Tšingis-khaani rajatud hiiglaslik impeerium', 'the Mongol Empire', 'Mongoli impeerium'],
    ['Soviet_Union', 'Soviet Union', 'the state also abbreviated as the USSR', 'riik, mida lühendati NSVL', 'the Soviet Union', 'Nõukogude Liit'],
  ],
  (prompt) => `Name the civilization, people, empire, or state: ${prompt}.`,
  (prompt) => `Nimeta tsivilisatsioon, rahvas, impeerium või riik: ${prompt}.`,
  (prompt, answer) => `The answer is ${answer}: ${prompt}.`,
  (prompt, answer) => `Vastus on ${answer}: ${prompt}.`),
] as const;

const GEOGRAPHY = [
  ...relationGroup('02-geography', 'capitals', [
    ['Estonia', 'Estonia', 'Estonia', 'Eesti', 'Tallinn', 'Tallinn'],
    ['Finland', 'Finland', 'Finland', 'Soome', 'Helsinki', 'Helsingi'],
    ['Latvia', 'Latvia', 'Latvia', 'Läti', 'Riga', 'Riia'],
    ['Sweden', 'Sweden', 'Sweden', 'Rootsi', 'Stockholm', 'Stockholm'],
    ['Norway', 'Norway', 'Norway', 'Norra', 'Oslo', 'Oslo'],
    ['Denmark', 'Denmark', 'Denmark', 'Taani', 'Copenhagen', 'Kopenhaagen'],
    ['Germany', 'Germany', 'Germany', 'Saksamaa', 'Berlin', 'Berliin'],
    ['France', 'France', 'France', 'Prantsusmaa', 'Paris', 'Pariis'],
    ['Italy', 'Italy', 'Italy', 'Itaalia', 'Rome', 'Rooma'],
    ['Japan', 'Japan', 'Japan', 'Jaapan', 'Tokyo', 'Tokyo'],
  ],
  (prompt) => `What is the capital of ${prompt}?`,
  (prompt) => `Mis on ${prompt} pealinn?`,
  (prompt, answer) => `${answer} is the capital of ${prompt}.`,
  (prompt, answer) => `${answer} on ${prompt} pealinn.`),
  ...relationGroup('02-geography', 'landmarks', [
    ['Eiffel_Tower', 'Eiffel Tower', 'the Eiffel Tower', 'Eiffeli torn', 'France', 'Prantsusmaa'],
    ['Great_Pyramid_of_Giza', 'Great Pyramid of Giza', 'the Great Pyramid of Giza', 'Giza suur püramiid', 'Egypt', 'Egiptus'],
    ['Taj_Mahal', 'Taj Mahal', 'the Taj Mahal', 'Taj Mahal', 'India', 'India'],
    ['Sydney_Opera_House', 'Sydney Opera House', 'the Sydney Opera House', 'Sydney ooperimaja', 'Australia', 'Austraalia'],
    ['Christ_the_Redeemer_(statue)', 'Christ the Redeemer', 'the Christ the Redeemer statue', 'Lunastaja Kristuse kuju', 'Brazil', 'Brasiilia'],
    ['Leaning_Tower_of_Pisa', 'Leaning Tower of Pisa', 'the Leaning Tower of Pisa', 'Pisa viltune torn', 'Italy', 'Itaalia'],
    ['Statue_of_Liberty', 'Statue of Liberty', 'the Statue of Liberty', 'Vabadussammas New Yorgis', 'the United States', 'Ameerika Ühendriigid'],
    ['Sagrada_Família', 'Sagrada Família', 'the Sagrada Família basilica', 'Sagrada Família basiilika', 'Spain', 'Hispaania'],
    ['Burj_Khalifa', 'Burj Khalifa', 'the Burj Khalifa', 'Burj Khalifa', 'the United Arab Emirates', 'Araabia Ühendemiraadid'],
    ['Moai', 'Moai', 'the famous moai statues of Easter Island', 'Lihavõttesaare kuulsad moai-kujud', 'Chile', 'Tšiili'],
  ],
  (prompt) => `In which country is this landmark found: ${prompt}?`,
  (prompt) => `Millises riigis asub see vaatamisväärsus: ${prompt}?`,
  (prompt, answer) => `The country is ${answer}: ${prompt}.`,
  (prompt, answer) => `Riik on ${answer}: ${prompt}.`),
  ...relationGroup('02-geography', 'waters', [
    ['Baltic_Sea', 'Baltic Sea', 'the sea between Estonia and Sweden', 'Eesti ja Rootsi vahele jääv meri', 'the Baltic Sea', 'Läänemeri'],
    ['Mediterranean_Sea', 'Mediterranean Sea', 'the sea between Europe and Africa', 'Euroopa ja Aafrika vahele jääv meri', 'the Mediterranean Sea', 'Vahemeri'],
    ['Atlantic_Ocean', 'Atlantic Ocean', 'the ocean between Europe and North America', 'Euroopa ja Põhja-Ameerika vahele jääv ookean', 'the Atlantic Ocean', 'Atlandi ookean'],
    ['Pacific_Ocean', 'Pacific Ocean', 'the ocean between Asia and Australia in the west and the Americas in the east', 'ookean, mille läände jäävad Aasia ja Austraalia ning itta Ameerikad', 'the Pacific Ocean', 'Vaikne ookean'],
    ['Nile', 'Nile', 'the major river that flows through Egypt', 'Egiptust läbiv suur jõgi', 'the Nile', 'Niilus'],
    ['Amazon_River', 'Amazon River', 'the great river running across northern South America', 'Lõuna-Ameerika põhjaosa läbiv hiigeljõgi', 'the Amazon River', 'Amazonas'],
    ['Danube', 'Danube', 'the river flowing through Vienna, Bratislava, Budapest, and Belgrade', 'Viini, Bratislavat, Budapesti ja Belgradi läbiv jõgi', 'the Danube', 'Doonau'],
    ['Lake_Peipus', 'Lake Peipus', 'the large lake on the Estonia–Russia border', 'suur järv Eesti ja Venemaa piiril', 'Lake Peipus', 'Peipsi järv'],
    ['Dead_Sea', 'Dead Sea', 'the extremely salty lake between Jordan and Israel', 'Jordaania ja Iisraeli vahel asuv ülisoolane järv', 'the Dead Sea', 'Surnumeri'],
    ['Niagara_Falls', 'Niagara Falls', 'the waterfalls on the border of Canada and the United States', 'Kanada ja Ameerika Ühendriikide piiril asuvad joad', 'Niagara Falls', 'Niagara juga'],
  ],
  (prompt) => `Name ${prompt}.`,
  (prompt) => `Nimeta ${prompt}.`,
  (prompt, answer) => `${answer} is ${prompt}.`,
  (prompt, answer) => `${answer} on ${prompt}.`),
  ...relationGroup('02-geography', 'physical', [
    ['Mount_Everest', 'Mount Everest', 'the Himalayan mountain measured at 8,848.86 metres above sea level', 'Himaalaja mägi, mille kõrguseks on mõõdetud 8848,86 meetrit üle merepinna', 'Mount Everest', 'Mount Everest'],
    ['Sahara', 'Sahara', 'the huge hot desert across North Africa', 'Põhja-Aafrikat kattev hiiglaslik kuum kõrb', 'the Sahara', 'Sahara'],
    ['Greenland', 'Greenland', 'the mostly Arctic island that is an autonomous territory of Denmark', 'peamiselt Arktikas asuv Taani autonoomne ala', 'Greenland', 'Gröönimaa'],
    ['Africa', 'Africa', 'the continent containing the Sahara and the Nile', 'Sahara kõrbe ja Niiluse jõega manner', 'Africa', 'Aafrika'],
    ['Equator', 'Equator', 'the imaginary line dividing Earth into northern and southern hemispheres', 'Maad põhja- ja lõunapoolkeraks jagav mõtteline joon', 'the Equator', 'ekvaator'],
    ['North_Pole', 'North Pole', 'the northernmost point on Earth', 'Maa kõige põhjapoolsem punkt', 'the North Pole', 'põhjapoolus'],
    ['Alps', 'Alps', 'the mountain range running through Switzerland and Austria', 'Šveitsi ja Austriat läbiv mäestik', 'the Alps', 'Alpid'],
    ['Grand_Canyon', 'Grand Canyon', 'the vast Arizona canyon carved by the Colorado River', 'Colorado jõe uuristatud hiigelkanjon Arizonas', 'the Grand Canyon', 'Grand Canyon'],
    ['Antarctica', 'Antarctica', 'the icy continent around the South Pole', 'lõunapoolust ümbritsev jäine manner', 'Antarctica', 'Antarktika'],
    ['Hawaii', 'Hawaii', 'the American island state in the central Pacific', 'Ameerika Ühendriikide saar-osariik Vaikse ookeani keskosas', 'Hawaii', 'Hawaii'],
  ],
  (prompt) => `What is ${prompt}?`,
  (prompt) => `Mis on ${prompt}?`,
  (prompt, answer) => `${answer} is ${prompt}.`,
  (prompt, answer) => `${answer} on ${prompt}.`),
] as const;

const SCIENCE = [
  ...relationGroup('03-science-nature', 'space', [
    ['Sun', 'Sun', 'the star at the centre of our Solar System', 'meie Päikesesüsteemi keskmes olev täht', 'the Sun', 'Päike'],
    ['Moon', 'Moon', 'Earth’s natural satellite', 'Maa looduslik kaaslane', 'the Moon', 'Kuu'],
    ['Mars', 'Mars', 'the planet commonly called the Red Planet', 'planeet, mida kutsutakse punaseks planeediks', 'Mars', 'Marss'],
    ['Jupiter', 'Jupiter', 'the fifth planet from the Sun, famous for the Great Red Spot', 'Päikesest viies planeet, mis on tuntud Suure Punase Laigu poolest', 'Jupiter', 'Jupiter'],
    ['Saturn', 'Saturn', 'the planet best known for its bright rings', 'eredate rõngaste poolest tuntud planeet', 'Saturn', 'Saturn'],
    ['Venus', 'Venus', 'the hottest planet in the Solar System', 'Päikesesüsteemi kuumim planeet', 'Venus', 'Veenus'],
    ['Milky_Way', 'Milky Way', 'the galaxy containing our Solar System', 'meie Päikesesüsteemi sisaldav galaktika', 'the Milky Way', 'Linnutee'],
    ['Pluto', 'Pluto', 'the dwarf planet once classified as the ninth planet', 'kääbusplaneet, mida peeti kunagi üheksandaks planeediks', 'Pluto', 'Pluuto'],
    ['International_Space_Station', 'International Space Station', 'the large crewed laboratory orbiting Earth', 'suur mehitatud labor, mis tiirleb ümber Maa', 'the International Space Station', 'Rahvusvaheline Kosmosejaam'],
    ['Comet', 'Comet', 'an icy Solar System body that can grow a visible tail', 'jäine Päikesesüsteemi keha, millel võib tekkida nähtav saba', 'a comet', 'komeet'],
  ],
  (prompt) => `What is ${prompt}?`,
  (prompt) => `Mis on ${prompt}?`,
  (prompt, answer) => `${answer} is ${prompt}.`,
  (prompt, answer) => `${answer} on ${prompt}.`),
  ...relationGroup('03-science-nature', 'body', [
    ['Heart', 'Heart', 'the organ that pumps blood around the body', 'organ, mis pumpab verd läbi keha', 'the heart', 'süda'],
    ['Lung', 'Lung', 'the paired organs used for breathing', 'hingamiseks kasutatavad paariselundid', 'the lungs', 'kopsud'],
    ['Brain', 'Brain', 'the organ at the centre of the nervous system', 'närvisüsteemi keskne organ', 'the brain', 'aju'],
    ['Skeleton', 'Skeleton', 'the framework of bones supporting the body', 'keha toetav luudest raamistik', 'the skeleton', 'luustik'],
    ['Skin', 'Skin', 'the organ that covers the outside of the human body', 'inimkeha välispinda kattev elund', 'the skin', 'nahk'],
    ['Blood', 'Blood', 'the red fluid transported by the circulatory system', 'vereringes liikuv punane vedelik', 'blood', 'veri'],
    ['Stomach', 'Stomach', 'the digestive organ between the oesophagus and small intestine', 'söögitoru ja peensoole vahel asuv seedeelund', 'the stomach', 'magu'],
    ['Eye', 'Eye', 'the organ that detects light and enables sight', 'valgust tajuv ja nägemist võimaldav elund', 'the eye', 'silm'],
    ['DNA', 'DNA', 'the molecule that carries genetic information', 'pärilikku teavet kandev molekul', 'DNA', 'DNA'],
    ['Red_blood_cell', 'Red blood cell', 'the blood cell that carries oxygen using haemoglobin', 'hemoglobiini abil hapnikku kandev vererakk', 'a red blood cell', 'punalible'],
  ],
  (prompt) => `Name the body part, cell, or substance: ${prompt}.`,
  (prompt) => `Nimeta kehaosa, rakk või aine: ${prompt}.`,
  (prompt, answer) => `The answer is ${answer}: ${prompt}.`,
  (prompt, answer) => `Vastus on ${answer}: ${prompt}.`),
  ...relationGroup('03-science-nature', 'basics', [
    ['Water', 'Water', 'the chemical formula H₂O', 'keemiline valem H₂O', 'water', 'vesi'],
    ['Oxygen', 'Oxygen', 'the gas with chemical symbol O that humans need to breathe', 'keemilise tähisega O gaas, mida inimesed hingamiseks vajavad', 'oxygen', 'hapnik'],
    ['Gold', 'Gold', 'the precious metal with chemical symbol Au', 'keemilise tähisega Au väärismetall', 'gold', 'kuld'],
    ['Gravity', 'Gravity', 'the force that pulls objects toward Earth', 'jõud, mis tõmbab esemeid Maa poole', 'gravity', 'gravitatsioon'],
    ['Photosynthesis', 'Photosynthesis', 'the process plants use to turn light into chemical energy', 'protsess, millega taimed muudavad valguse keemiliseks energiaks', 'photosynthesis', 'fotosüntees'],
    ['Freezing', 'Freezing', 'the change from liquid water to solid ice', 'vedela vee muutumine tahkeks jääks', 'freezing', 'külmumine'],
    ['Atom', 'Atom', 'the basic unit of a chemical element', 'keemilise elemendi põhiosake', 'an atom', 'aatom'],
    ['Sound', 'Sound', 'vibrations that travel through a medium and can be heard', 'keskkonnas levivad võnked, mida saab kuulda', 'sound', 'heli'],
    ['Rainbow', 'Rainbow', 'the coloured arc caused by light interacting with water droplets', 'valguse ja veepiiskade koostoimel tekkiv värviline kaar', 'a rainbow', 'vikerkaar'],
    ['Magnet', 'Magnet', 'an object that attracts iron and produces a magnetic field', 'rauda ligi tõmbav ja magnetvälja tekitav ese', 'a magnet', 'magnet'],
  ],
  (prompt) => `What is ${prompt}?`,
  (prompt) => `Mis on ${prompt}?`,
  (prompt, answer) => `${answer[0].toUpperCase()}${answer.slice(1)} is ${prompt}.`,
  (prompt, answer) => `${answer[0].toUpperCase()}${answer.slice(1)} on ${prompt}.`),
  ...relationGroup('03-science-nature', 'animals', [
    ['Blue_whale', 'Blue whale', 'the baleen whale that can grow to around 30 metres long', 'kiusvaal, kes võib kasvada umbes 30 meetri pikkuseks', 'the blue whale', 'sinivaal'],
    ['Cheetah', 'Cheetah', 'the fastest land animal', 'kiireim maismaaloom', 'the cheetah', 'gepard'],
    ['Emperor_penguin', 'Emperor penguin', 'the Antarctic penguin whose male incubates an egg on his feet', 'Antarktika pingviin, kelle isaslind haub muna oma jalgadel', 'the emperor penguin', 'keiserpingviin'],
    ['Giraffe', 'Giraffe', 'the tallest living land animal', 'kõrgeim tänapäeval elav maismaaloom', 'the giraffe', 'kaelkirjak'],
    ['Polar_bear', 'Polar bear', 'the large white bear native to the Arctic', 'Arktikas elav suur valge karu', 'the polar bear', 'jääkaru'],
    ['Kangaroo', 'Kangaroo', 'the Australian marsupial known for hopping', 'hüppamise poolest tuntud Austraalia kukkurloom', 'the kangaroo', 'känguru'],
    ['Honey_bee', 'Honey bee', 'the insect that produces honey and lives in colonies', 'mett valmistav ja kolooniates elav putukas', 'the honey bee', 'meemesilane'],
    ['Octopus', 'Octopus', 'the eight-armed marine mollusc', 'kaheksa kombitsaga mereline limus', 'the octopus', 'kaheksajalg'],
    ['African_elephant', 'African elephant', 'the elephant native to Africa, with larger ears than its Asian relative', 'Aafrikas elav elevant, kelle kõrvad on Aasia sugulase omadest suuremad', 'the African elephant', 'Aafrika elevant'],
    ['Dolphin', 'Dolphin', 'the intelligent marine mammal known for echolocation', 'kajalokatsiooni poolest tuntud intelligentne mereimetaja', 'a dolphin', 'delfiin'],
  ],
  (prompt) => `Which animal is ${prompt}?`,
  (prompt) => `Milline loom on ${prompt}?`,
  (prompt, answer) => `${answer[0].toUpperCase()}${answer.slice(1)} is ${prompt}.`,
  (prompt, answer) => `${answer[0].toUpperCase()}${answer.slice(1)} on ${prompt}.`),
] as const;

const LITERATURE = [
  ...relationGroup('04-literature-language', 'authors', [
    ['Harry_Potter', 'Harry Potter', 'the Harry Potter series', 'Harry Potteri sarja', 'J. K. Rowling', 'J. K. Rowling'],
    ['Romeo_and_Juliet', 'Romeo and Juliet', 'Romeo and Juliet', '„Romeo ja Julia“', 'William Shakespeare', 'William Shakespeare'],
    ['The_Hobbit', 'The Hobbit', 'The Hobbit', '„Kääbiku“', 'J. R. R. Tolkien', 'J. R. R. Tolkien'],
    ['Pride_and_Prejudice', 'Pride and Prejudice', 'Pride and Prejudice', '„Uhkuse ja eelarvamuse“', 'Jane Austen', 'Jane Austen'],
    ['The_Little_Prince', 'The Little Prince', 'The Little Prince', '„Väikese printsi“', 'Antoine de Saint-Exupéry', 'Antoine de Saint-Exupéry'],
    ['Murder_on_the_Orient_Express', 'Murder on the Orient Express', 'Murder on the Orient Express', '„Mõrva Idaekspressis“', 'Agatha Christie', 'Agatha Christie'],
    ['1984_(novel)', 'Nineteen Eighty-Four', 'the novel 1984', 'romaani „1984“', 'George Orwell', 'George Orwell'],
    ['The_Old_Man_and_the_Sea', 'The Old Man and the Sea', 'The Old Man and the Sea', '„Vanamehe ja mere“', 'Ernest Hemingway', 'Ernest Hemingway'],
    ['Truth_and_Justice', 'Truth and Justice', 'the Estonian novel cycle Truth and Justice', 'romaanisarja „Tõde ja õigus“', 'A. H. Tammsaare', 'A. H. Tammsaare'],
    ['Kevade', 'Kevade', 'the Estonian school novel Kevade', 'Eesti kooliromaani „Kevade“', 'Oskar Luts', 'Oskar Luts'],
  ],
  (prompt) => `Who wrote ${prompt}?`,
  (prompt) => `Kes kirjutas ${prompt}?`,
  (prompt, answer) => `${answer} wrote ${prompt}.`,
  (prompt, answer) => `${answer} kirjutas ${prompt}.`),
  ...relationGroup('04-literature-language', 'characters', [
    ['Sherlock_Holmes', 'Sherlock Holmes', 'Sherlock Holmes', 'Sherlock Holmes', 'a detective', 'detektiiv'],
    ['Winnie-the-Pooh', 'Winnie-the-Pooh', 'Winnie-the-Pooh', 'Karupoeg Puhh', 'a bear', 'karu'],
    ['Pippi_Longstocking', 'Pippi Longstocking', 'Pippi Longstocking', 'Pipi Pikksukk', 'Astrid Lindgren', 'Astrid Lindgren'],
    ['Don_Quixote', 'Don Quixote', 'Don Quixote', 'Don Quijote', 'windmills', 'tuuleveskid'],
    ['Alice%27s_Adventures_in_Wonderland', 'Alice’s Adventures in Wonderland', 'Alice', 'Alice', 'Wonderland', 'Imedemaa'],
    ['The_Three_Musketeers', 'The Three Musketeers', 'the musketeers Athos, Porthos, and Aramis', 'musketärid Athos, Porthos ja Aramis', 'The Three Musketeers', '„Kolm musketäri“'],
    ['Moomins', 'Moomins', 'the Moomins', 'muumitrollid', 'Tove Jansson', 'Tove Jansson'],
    ['Kalevipoeg', 'Kalevipoeg', 'Kalevipoeg', 'Kalevipoeg', 'the Estonian national epic', 'Eesti rahvuseepos'],
    ['Robin_Hood', 'Robin Hood', 'Robin Hood', 'Robin Hood', 'Sherwood Forest', 'Sherwoodi mets'],
    ['Dracula', 'Dracula', 'Count Dracula', 'krahv Dracula', 'a vampire', 'vampiir'],
  ],
  (prompt) => `Complete this familiar literary association: ${prompt} — ?`,
  (prompt) => `Täienda tuntud kirjanduslikku seost: ${prompt} — ?`,
  (prompt, answer) => `${prompt} is associated with ${answer}.`,
  (prompt, answer) => `${prompt} seostub mõistega ${answer}.`),
  ...relationGroup('04-literature-language', 'languages', [
    ['Spanish_language', 'Spanish language', 'Spain and much of Latin America', 'Hispaanias ja suures osas Ladina-Ameerikast', 'Spanish', 'hispaania keel'],
    ['French_language', 'French language', 'France and parts of Belgium, Switzerland, and Canada', 'Prantsusmaal ning Belgia, Šveitsi ja Kanada osades', 'French', 'prantsuse keel'],
    ['German_language', 'German language', 'Germany and Austria', 'Saksamaal ja Austrias', 'German', 'saksa keel'],
    ['Italian_language', 'Italian language', 'Italy', 'Itaalias', 'Italian', 'itaalia keel'],
    ['Finnish_language', 'Finnish language', 'Finland', 'Soomes', 'Finnish', 'soome keel'],
    ['Latvian_language', 'Latvian language', 'Latvia', 'Lätis', 'Latvian', 'läti keel'],
    ['Japanese_language', 'Japanese language', 'Japan', 'Jaapanis', 'Japanese', 'jaapani keel'],
    ['Portuguese_language', 'Portuguese language', 'Portugal and Brazil', 'Portugalis ja Brasiilias', 'Portuguese', 'portugali keel'],
    ['Greek_language', 'Greek language', 'Greece', 'Kreekas', 'Greek', 'kreeka keel'],
    ['Icelandic_language', 'Icelandic language', 'Iceland', 'Islandil', 'Icelandic', 'islandi keel'],
  ],
  (prompt) => `Which language is principally spoken in ${prompt}?`,
  (prompt) => `Millist keelt räägitakse peamiselt ${prompt}?`,
  (prompt, answer) => `${answer} is principally spoken in ${prompt}.`,
  (prompt, answer) => `${answer} on peamine keel ${prompt}.`),
  ...relationGroup('04-literature-language', 'terms', [
    ['Synonym', 'Synonym', 'a word with the same or nearly the same meaning as another', 'teise sõnaga sama või peaaegu sama tähendusega sõna', 'a synonym', 'sünonüüm'],
    ['Antonym', 'Antonym', 'a word with the opposite meaning to another', 'teisele sõnale vastupidise tähendusega sõna', 'an antonym', 'antonüüm'],
    ['Palindrome', 'Palindrome', 'a word or phrase that reads the same forwards and backwards', 'mõlemas suunas ühtemoodi loetav sõna või fraas', 'a palindrome', 'palindroom'],
    ['Biography', 'Biography', 'a book about a person’s life written by somebody else', 'kellegi teise kirjutatud raamat inimese elust', 'a biography', 'biograafia'],
    ['Autobiography', 'Autobiography', 'a person’s account of their own life', 'inimese enda kirjutatud elulugu', 'an autobiography', 'autobiograafia'],
    ['Haiku', 'Haiku', 'the short Japanese poetic form traditionally arranged in three lines', 'traditsiooniliselt kolmerealine lühike Jaapani luulevorm', 'a haiku', 'haiku'],
    ['Novel', 'Novel', 'a long work of fictional prose', 'pikk proosavormis ilukirjandusteos', 'a novel', 'romaan'],
    ['Proverb', 'Proverb', 'a short traditional saying expressing common wisdom', 'rahvatarkust väljendav lühike traditsiooniline ütlus', 'a proverb', 'vanasõna'],
    ['Alphabet', 'Alphabet', 'an ordered set of letters used for writing a language', 'keele kirjutamiseks kasutatav järjestatud tähtede kogum', 'an alphabet', 'tähestik'],
    ['Metaphor', 'Metaphor', 'a figure of speech that describes one thing as another', 'kõnekujund, mis kirjeldab üht asja teisena', 'a metaphor', 'metafoor'],
  ],
  (prompt) => `Name the literary or language term: ${prompt}.`,
  (prompt) => `Nimeta kirjandus- või keelemõiste: ${prompt}.`,
  (prompt, answer) => `The term is ${answer}: ${prompt}.`,
  (prompt, answer) => `Mõiste on ${answer}: ${prompt}.`),
] as const;

const MUSIC = [
  ...relationGroup('06-music', 'artists', [
    ['Dancing_Queen', 'Dancing Queen', '“Dancing Queen”', 'laulu „Dancing Queen“', 'ABBA', 'ABBA'],
    ['Bohemian_Rhapsody', 'Bohemian Rhapsody', '“Bohemian Rhapsody”', 'laulu „Bohemian Rhapsody“', 'Queen', 'Queen'],
    ['Like_a_Prayer_(song)', 'Like a Prayer', '“Like a Prayer”', 'laulu „Like a Prayer“', 'Madonna', 'Madonna'],
    ['Billie_Jean', 'Billie Jean', '“Billie Jean”', 'laulu „Billie Jean“', 'Michael Jackson', 'Michael Jackson'],
    ['Rolling_in_the_Deep', 'Rolling in the Deep', '“Rolling in the Deep”', 'laulu „Rolling in the Deep“', 'Adele', 'Adele'],
    ['Shape_of_You', 'Shape of You', '“Shape of You”', 'laulu „Shape of You“', 'Ed Sheeran', 'Ed Sheeran'],
    ['Toxic_(song)', 'Toxic', '“Toxic”', 'laulu „Toxic“', 'Britney Spears', 'Britney Spears'],
    ['Poker_Face_(song)', 'Poker Face', '“Poker Face”', 'laulu „Poker Face“', 'Lady Gaga', 'Lady Gaga'],
    ['Smells_Like_Teen_Spirit', 'Smells Like Teen Spirit', '“Smells Like Teen Spirit”', 'laulu „Smells Like Teen Spirit“', 'Nirvana', 'Nirvana'],
    ['Waterloo_(song)', 'Waterloo', 'the 1974 Eurovision winner “Waterloo”', '1974. aasta Eurovisiooni võidulaulu „Waterloo“', 'ABBA', 'ABBA'],
  ],
  (prompt) => `Which artist recorded ${prompt}?`,
  (prompt) => `Milline artist esitas ${prompt}?`,
  (prompt, answer) => `${answer} recorded ${prompt}.`,
  (prompt, answer) => `${answer} esitas ${prompt}.`),
  ...relationGroup('06-music', 'bands', [
    ['The_Beatles', 'The Beatles', 'John Lennon, Paul McCartney, George Harrison, and Ringo Starr', 'John Lennon, Paul McCartney, George Harrison ja Ringo Starr', 'the Beatles', 'The Beatles'],
    ['Queen_(band)', 'Queen', 'Freddie Mercury, Brian May, Roger Taylor, and John Deacon', 'Freddie Mercury, Brian May, Roger Taylor ja John Deacon', 'Queen', 'Queen'],
    ['ABBA', 'ABBA', 'Agnetha, Björn, Benny, and Anni-Frid', 'Agnetha, Björn, Benny ja Anni-Frid', 'ABBA', 'ABBA'],
    ['Spice_Girls', 'Spice Girls', 'Scary, Sporty, Baby, Ginger, and Posh', 'Scary, Sporty, Baby, Ginger ja Posh', 'the Spice Girls', 'Spice Girls'],
    ['U2', 'U2', 'Bono, the Edge, Adam Clayton, and Larry Mullen Jr.', 'Bono, The Edge, Adam Clayton ja Larry Mullen Jr.', 'U2', 'U2'],
    ['Metallica', 'Metallica', 'the metal band behind “Enter Sandman”', 'metal-bänd, kes esitab laulu „Enter Sandman“', 'Metallica', 'Metallica'],
    ['Coldplay', 'Coldplay', 'the British band behind “Yellow” and “Viva la Vida”', 'Briti bänd, kes esitab laule „Yellow“ ja „Viva la Vida“', 'Coldplay', 'Coldplay'],
    ['Backstreet_Boys', 'Backstreet Boys', 'the boy band behind “I Want It That Way”', 'poistebänd, kes esitab laulu „I Want It That Way“', 'the Backstreet Boys', 'Backstreet Boys'],
    ['The_Rolling_Stones', 'The Rolling Stones', 'the rock band fronted by Mick Jagger', 'Mick Jaggeri juhitud rokkbänd', 'the Rolling Stones', 'The Rolling Stones'],
    ['Rammstein', 'Rammstein', 'the German band behind “Du hast”', 'Saksa bänd, kes esitab laulu „Du hast“', 'Rammstein', 'Rammstein'],
  ],
  (prompt) => `Name the band: ${prompt}.`,
  (prompt) => `Nimeta bänd: ${prompt}.`,
  (prompt, answer) => `The band is ${answer}: ${prompt}.`,
  (prompt, answer) => `Bänd on ${answer}: ${prompt}.`),
  ...relationGroup('06-music', 'instruments', [
    ['Piano', 'Piano', 'the keyboard instrument with black and white keys', 'mustade ja valgete klahvidega klahvpill', 'the piano', 'klaver'],
    ['Guitar', 'Guitar', 'the usually six-stringed instrument common in rock music', 'tavaliselt kuue keelega rokkmuusikas levinud pill', 'the guitar', 'kitarr'],
    ['Violin', 'Violin', 'the small bowed string instrument held under the chin', 'lõua all hoitav väike poogenkeelpill', 'the violin', 'viiul'],
    ['Drum_kit', 'Drum kit', 'the collection of drums and cymbals played by one musician', 'ühe muusiku mängitav trummide ja taldrikute komplekt', 'a drum kit', 'trummikomplekt'],
    ['Saxophone', 'Saxophone', 'the metal woodwind instrument strongly associated with jazz', 'džässiga tugevalt seotud metallist puupuhkpill', 'the saxophone', 'saksofon'],
    ['Trumpet', 'Trumpet', 'the brass instrument played through three valves', 'kolme ventiiliga vaskpuhkpill', 'the trumpet', 'trompet'],
    ['Accordion', 'Accordion', 'the bellows-driven instrument with buttons or piano-style keys', 'lõõtsaga pill, millel on nupud või klaveriklahvid', 'the accordion', 'akordion'],
    ['Flute', 'Flute', 'the high-pitched woodwind held sideways', 'külgsuunas hoitav kõrge kõlaga puupuhkpill', 'the flute', 'flööt'],
    ['Cello', 'Cello', 'the large bowed string instrument played between the knees', 'põlvede vahel mängitav suur poogenkeelpill', 'the cello', 'tšello'],
    ['Bagpipes', 'Bagpipes', 'the air-bag instrument strongly associated with Scotland', 'Šotimaaga tugevalt seotud õhukotiga pill', 'bagpipes', 'torupill'],
  ],
  (prompt) => `Which instrument is ${prompt}?`,
  (prompt) => `Milline pill on ${prompt}?`,
  (prompt, answer) => `${answer[0].toUpperCase()}${answer.slice(1)} is ${prompt}.`,
  (prompt, answer) => `${answer[0].toUpperCase()}${answer.slice(1)} on ${prompt}.`),
  ...relationGroup('06-music', 'classical', [
    ['Ludwig_van_Beethoven', 'Ludwig van Beethoven', 'the Fifth Symphony and the Moonlight Sonata', 'viienda sümfoonia ja „Kuupaistesonaadi“', 'Ludwig van Beethoven', 'Ludwig van Beethoven'],
    ['Wolfgang_Amadeus_Mozart', 'Wolfgang Amadeus Mozart', 'The Magic Flute', 'ooperi „Võluflööt“', 'Wolfgang Amadeus Mozart', 'Wolfgang Amadeus Mozart'],
    ['Antonio_Vivaldi', 'Antonio Vivaldi', 'The Four Seasons', '„Neli aastaaega“', 'Antonio Vivaldi', 'Antonio Vivaldi'],
    ['Pyotr_Ilyich_Tchaikovsky', 'Pyotr Ilyich Tchaikovsky', 'the ballets Swan Lake and The Nutcracker', 'balletid „Luikede järv“ ja „Pähklipureja“', 'Pyotr Ilyich Tchaikovsky', 'Pjotr Tšaikovski'],
    ['Johann_Sebastian_Bach', 'Johann Sebastian Bach', 'the Brandenburg Concertos', 'Brandenburgi kontserdid', 'Johann Sebastian Bach', 'Johann Sebastian Bach'],
    ['Frédéric_Chopin', 'Frédéric Chopin', 'many famous solo piano nocturnes', 'paljud kuulsad klaverinokturnid', 'Frédéric Chopin', 'Frédéric Chopin'],
    ['Giuseppe_Verdi', 'Giuseppe Verdi', 'the opera La traviata', 'ooperi „La traviata“', 'Giuseppe Verdi', 'Giuseppe Verdi'],
    ['Richard_Wagner', 'Richard Wagner', 'the four-opera Ring cycle', 'neljast ooperist koosneva „Nibelungi sõrmuse“', 'Richard Wagner', 'Richard Wagner'],
    ['Arvo_Pärt', 'Arvo Pärt', 'the tintinnabuli style and the work Spiegel im Spiegel', 'tintinnabuli-stiili ja teose „Spiegel im Spiegel“', 'Arvo Pärt', 'Arvo Pärt'],
    ['Georg_Ots', 'Georg Ots', 'the Estonian baritone famous for opera and popular songs', 'Eesti bariton, kes sai tuntuks ooperi ja levilauludega', 'Georg Ots', 'Georg Ots'],
  ],
  (prompt) => `Name the composer or musician: ${prompt}.`,
  (prompt) => `Nimeta helilooja või muusik: ${prompt}.`,
  (prompt, answer) => `The answer is ${answer}: ${prompt}.`,
  (prompt, answer) => `Vastus on ${answer}: ${prompt}.`),
] as const;

const FILM_TELEVISION = [
  ...relationGroup('07-film-television', 'films', [
    ['Titanic_(1997_film)', 'Titanic', 'the 1997 romance set aboard the doomed ocean liner', '1997. aasta armastusfilm hukule määratud ookeanilaeval', 'Titanic', '„Titanic“'],
    ['The_Matrix', 'The Matrix', 'the science-fiction film in which Neo discovers a simulated reality', 'ulmefilm, kus Neo avastab simuleeritud tegelikkuse', 'The Matrix', '„Matrix“'],
    ['Home_Alone', 'Home Alone', 'the Christmas comedy in which Kevin is accidentally left behind', 'jõulukomöödia, kus Kevin kogemata üksi koju jäetakse', 'Home Alone', '„Üksinda kodus“'],
    ['Jurassic_Park_(film)', 'Jurassic Park', 'the Steven Spielberg adventure about a dinosaur theme park', 'Steven Spielbergi seiklusfilm dinosauruste teemapargist', 'Jurassic Park', '„Jurassic Park“'],
    ['The_Lion_King', 'The Lion King', 'the Disney story of Simba, Mufasa, and Scar', 'Disney lugu Simbast, Mufasast ja Scarist', 'The Lion King', '„Lõvikuningas“'],
    ['Shrek', 'Shrek', 'the animated film about a green ogre and a talking donkey', 'animafilm rohelisest sookollist ja rääkivast eeslist', 'Shrek', '„Shrek“'],
    ['Frozen_(2013_film)', 'Frozen', 'the Disney musical featuring sisters Elsa and Anna', 'Disney muusikal õdedest Elsast ja Annast', 'Frozen', '„Lumekuninganna ja igavene talv“'],
    ['Forrest_Gump', 'Forrest Gump', 'the film in which Tom Hanks plays a man who witnesses decades of American history', 'film, kus Tom Hanksi tegelane satub mitme aastakümne Ameerika ajaloo keskele', 'Forrest Gump', '„Forrest Gump“'],
    ['The_Terminator', 'The Terminator', 'the action film featuring the line “I’ll be back”', 'märulifilm kuulsa repliigiga „I’ll be back“', 'The Terminator', '„Terminaator“'],
    ['Avatar_(2009_film)', 'Avatar', 'the James Cameron film set on the moon Pandora', 'James Cameroni film, mille tegevus toimub Pandoral', 'Avatar', '„Avatar“'],
  ],
  (prompt) => `Name ${prompt}.`,
  (prompt) => `Nimeta ${prompt}.`,
  (prompt, answer) => `${answer} is ${prompt}.`,
  (prompt, answer) => `${answer} on ${prompt}.`),
  ...relationGroup('07-film-television', 'characters', [
    ['Darth_Vader', 'Darth Vader', 'the black-armoured Star Wars villain who is Luke Skywalker’s father', 'mustas turvises „Tähesõdade“ kurikael, kes on Luke Skywalkeri isa', 'Darth Vader', 'Darth Vader'],
    ['Indiana_Jones', 'Indiana Jones', 'the archaeologist adventurer played by Harrison Ford', 'Harrison Fordi mängitud arheoloogist seikleja', 'Indiana Jones', 'Indiana Jones'],
    ['James_Bond', 'James Bond', 'the British secret agent known by the code number 007', 'Briti salaagent koodnumbriga 007', 'James Bond', 'James Bond'],
    ['Rocky_Balboa', 'Rocky Balboa', 'the fictional Philadelphia boxer played by Sylvester Stallone', 'Sylvester Stallone’i mängitud väljamõeldud Philadelphia poksija', 'Rocky Balboa', 'Rocky Balboa'],
    ['Terminator_(character)', 'Terminator', 'the cyborg character who says “I’ll be back”', 'küborgtegelane, kes ütleb „I’ll be back“', 'the Terminator', 'Terminaator'],
    ['Jack_Sparrow', 'Jack Sparrow', 'Johnny Depp’s eccentric pirate captain', 'Johnny Deppi ekstsentriline piraadikapten', 'Jack Sparrow', 'Jack Sparrow'],
    ['Harry_Potter_(character)', 'Harry Potter', 'the young wizard with a lightning-shaped scar', 'välgukujulise armiga noor võlur', 'Harry Potter', 'Harry Potter'],
    ['Spider-Man', 'Spider-Man', 'the superhero whose alter ego is Peter Parker', 'superkangelane, kelle tavakodanikunimi on Peter Parker', 'Spider-Man', 'Ämblikmees'],
    ['Wonder_Woman', 'Wonder Woman', 'the Amazon superhero also known as Diana Prince', 'amatsoonist superkangelane, keda tuntakse ka Diana Prince’ina', 'Wonder Woman', 'Wonder Woman'],
    ['E.T._the_Extra-Terrestrial', 'E.T. the Extra-Terrestrial', 'the friendly alien who wants to phone home', 'sõbralik tulnukas, kes tahab koju helistada', 'E.T.', 'E.T.'],
  ],
  (prompt) => `Which screen character is ${prompt}?`,
  (prompt) => `Milline ekraanitegelane on ${prompt}?`,
  (prompt, answer) => `${answer} is ${prompt}.`,
  (prompt, answer) => `${answer} on ${prompt}.`),
  ...relationGroup('07-film-television', 'television', [
    ['Friends', 'Friends', 'features Ross, Rachel, Monica, Chandler, Joey, and Phoebe', 'jälgib Rossi, Racheli, Monica, Chandleri, Joey ja Phoebe elu', 'Friends', '„Sõbrad“'],
    ['The_Simpsons', 'The Simpsons', 'features Homer, Marge, Bart, Lisa, and Maggie', 'räägib Homerist, Marge’ist, Bartist, Lisast ja Maggiest', 'The Simpsons', '„Simpsonid“'],
    ['Game_of_Thrones', 'Game of Thrones', 'features the Iron Throne and Westeros', 'keerleb Raudtrooni ja Westerose ümber', 'Game of Thrones', '„Troonide mäng“'],
    ['Breaking_Bad', 'Breaking Bad', 'follows chemistry teacher Walter White', 'jälgib keemiaõpetaja Walter White’i', 'Breaking Bad', '„Halvale teele“'],
    ['Stranger_Things', 'Stranger Things', 'is set in Hawkins and features the Upside Down', 'toimub Hawkinsi linnas ja sisaldab Teispoolsust', 'Stranger Things', '„Veidrad asjad“'],
    ['The_Office_(American_TV_series)', 'The Office', 'is an American mockumentary set at Dunder Mifflin', 'on Dunder Mifflini kontoris toimuv Ameerika mokumentaalsari', 'The Office', '„Kontor“'],
    ['South_Park', 'South Park', 'is an animated comedy about Stan, Kyle, Cartman, and Kenny', 'on animakomöödia Stanist, Kyle’ist, Cartmanist ja Kennyst', 'South Park', '„South Park“'],
    ['Baywatch', 'Baywatch', 'is a beach-rescue drama starring David Hasselhoff', 'on David Hasselhoffiga rannapäästjate sari', 'Baywatch', '„Rannavalve“'],
    ['Knight_Rider_(1982_TV_series)', 'Knight Rider', 'is a 1980s action series featuring the talking car KITT', 'on 1980. aastate märulisari rääkiva autoga KITT', 'Knight Rider', '„Knight Rider“'],
    ['Õnne_13', 'Õnne 13', 'is a long-running Estonian drama set around Morna', 'on pikaajaline Eesti telesari, mille tegevus toimub Morna ümbruses', 'Õnne 13', '„Õnne 13“'],
  ],
  (prompt) => `Which television series ${prompt}?`,
  (prompt) => `Milline telesari ${prompt}?`,
  (prompt, answer) => `${answer} ${prompt}.`,
  (prompt, answer) => `${answer} ${prompt}.`),
  ...relationGroup('07-film-television', 'people', [
    ['Tom_Hanks', 'Tom Hanks', 'Forrest Gump and Cast Away', 'filmides „Forrest Gump“ ja „Kaldale uhutud“', 'Tom Hanks', 'Tom Hanks'],
    ['Meryl_Streep', 'Meryl Streep', 'The Devil Wears Prada and Mamma Mia!', 'filmides „Saatan kannab Pradat“ ja „Mamma Mia!“', 'Meryl Streep', 'Meryl Streep'],
    ['Leonardo_DiCaprio', 'Leonardo DiCaprio', 'Jack in Titanic and Cobb in Inception', 'Jacki filmis „Titanic“ ja Cobbi filmis „Algus“', 'Leonardo DiCaprio', 'Leonardo DiCaprio'],
    ['Julia_Roberts', 'Julia Roberts', 'Pretty Woman and Erin Brockovich', 'filmides „Kaunis naine“ ja „Erin Brockovich“', 'Julia Roberts', 'Julia Roberts'],
    ['Arnold_Schwarzenegger', 'Arnold Schwarzenegger', 'the Terminator and Conan the Barbarian', 'Terminaatorit ja Conan Barbarit', 'Arnold Schwarzenegger', 'Arnold Schwarzenegger'],
    ['Jim_Carrey', 'Jim Carrey', 'Ace Ventura and The Mask', 'Ace Venturat ja Maski', 'Jim Carrey', 'Jim Carrey'],
    ['Jennifer_Aniston', 'Jennifer Aniston', 'Rachel Green in Friends', 'Rachel Greeni sarjas „Sõbrad“', 'Jennifer Aniston', 'Jennifer Aniston'],
    ['Daniel_Radcliffe', 'Daniel Radcliffe', 'Harry Potter in the film series', 'Harry Potterit filmisarjas', 'Daniel Radcliffe', 'Daniel Radcliffe'],
    ['Margot_Robbie', 'Margot Robbie', 'Barbie in the 2023 film', 'Barbiet 2023. aasta filmis', 'Margot Robbie', 'Margot Robbie'],
    ['Rowan_Atkinson', 'Rowan Atkinson', 'Mr. Bean', 'Mr. Beani', 'Rowan Atkinson', 'Rowan Atkinson'],
  ],
  (prompt) => `Which actor played ${prompt}?`,
  (prompt) => `Milline näitleja mängis ${prompt}?`,
  (prompt, answer) => `${answer} played ${prompt}.`,
  (prompt, answer) => `${answer} mängis ${prompt}.`),
] as const;

const SPORTS_GAMES = [
  ...relationGroup('08-sports-games', 'basics', [
    ['Association_football', 'Association football', 'the sport played at the FIFA World Cup', 'FIFA maailmameistrivõistlustel mängitav spordiala', 'football', 'jalgpall'],
    ['Basketball', 'Basketball', 'the sport in which players shoot a ball through a hoop', 'spordiala, kus pall visatakse läbi korvi', 'basketball', 'korvpall'],
    ['Ice_hockey', 'Ice hockey', 'the ice sport played with sticks and a puck', 'keppide ja litriga mängitav jääspordiala', 'ice hockey', 'jäähoki'],
    ['Tennis', 'Tennis', 'the racket sport played at Wimbledon', 'Wimbledonis mängitav reketiala', 'tennis', 'tennis'],
    ['Volleyball', 'Volleyball', 'the team sport in which a ball is hit over a high net', 'võistkondlik spordiala, kus pall lüüakse üle kõrge võrgu', 'volleyball', 'võrkpall'],
    ['Golf', 'Golf', 'the sport whose aim is to put a ball into a series of holes in as few strokes as possible', 'spordiala, kus pall püütakse võimalikult väheste löökidega aukudesse saada', 'golf', 'golf'],
    ['Boxing', 'Boxing', 'the combat sport fought with padded gloves in a ring', 'polsterdatud kinnastega ringis peetav võitlusspordiala', 'boxing', 'poks'],
    ['Formula_One', 'Formula One', 'the top international class of single-seater motor racing', 'vormelautode rahvusvaheline kõrgeim võistlusklass', 'Formula 1', 'vormel 1'],
    ['Biathlon', 'Biathlon', 'the winter sport combining cross-country skiing and rifle shooting', 'murdmaasuusatamist ja püssilaskmist ühendav talispordiala', 'biathlon', 'laskesuusatamine'],
    ['Athletics', 'Athletics', 'the collection of running, jumping, and throwing events', 'jooksu-, hüppe- ja heitealadest koosnev spordiala', 'athletics', 'kergejõustik'],
  ],
  (prompt) => `Name the sport: ${prompt}.`,
  (prompt) => `Nimeta spordiala: ${prompt}.`,
  (prompt, answer) => `The sport is ${answer}: ${prompt}.`,
  (prompt, answer) => `Spordiala on ${answer}: ${prompt}.`),
  ...relationGroup('08-sports-games', 'stars', [
    ['Cristiano_Ronaldo', 'Cristiano Ronaldo', 'Cristiano Ronaldo', 'Cristiano Ronaldo', 'football', 'jalgpall'],
    ['Michael_Jordan', 'Michael Jordan', 'Michael Jordan', 'Michael Jordan', 'basketball', 'korvpall'],
    ['Serena_Williams', 'Serena Williams', 'Serena Williams', 'Serena Williams', 'tennis', 'tennis'],
    ['Usain_Bolt', 'Usain Bolt', 'Usain Bolt', 'Usain Bolt', 'sprinting', 'sprint'],
    ['Michael_Schumacher', 'Michael Schumacher', 'Michael Schumacher', 'Michael Schumacher', 'Formula 1', 'vormel 1'],
    ['Tiger_Woods', 'Tiger Woods', 'Tiger Woods', 'Tiger Woods', 'golf', 'golf'],
    ['Muhammad_Ali', 'Muhammad Ali', 'Muhammad Ali', 'Muhammad Ali', 'boxing', 'poks'],
    ['Kelly_Sildaru', 'Kelly Sildaru', 'Kelly Sildaru', 'Kelly Sildaru', 'freestyle skiing', 'vigursuusatamine'],
    ['Ott_Tänak', 'Ott Tänak', 'Ott Tänak', 'Ott Tänak', 'rallying', 'autoralli'],
    ['Kristina_Šmigun-Vähi', 'Kristina Šmigun-Vähi', 'Kristina Šmigun-Vähi', 'Kristina Šmigun-Vähi', 'cross-country skiing', 'murdmaasuusatamine'],
  ],
  (prompt) => `In which sport did ${prompt} become famous?`,
  (prompt) => `Millises spordialas sai tuntuks ${prompt}?`,
  (prompt, answer) => `${prompt} became famous in ${answer}.`,
  (prompt, answer) => `${prompt} sai tuntuks spordialal ${answer}.`),
  ...relationGroup('08-sports-games', 'events', [
    ['Olympic_Games', 'Olympic Games', 'the global multi-sport event symbolised by five rings', 'viie rõngaga sümboliseeritud ülemaailmne mitme spordiala võistlus', 'the Olympic Games', 'olümpiamängud'],
    ['FIFA_World_Cup', 'FIFA World Cup', 'the men’s international football tournament held every four years', 'iga nelja aasta tagant toimuv meeste jalgpalli maailmaturniir', 'the FIFA World Cup', 'FIFA maailmameistrivõistlused'],
    ['Tour_de_France', 'Tour de France', 'the famous multi-stage bicycle race around France', 'kuulus mitmeetapiline jalgrattavõistlus Prantsusmaal', 'the Tour de France', 'Tour de France'],
    ['Wimbledon_Championships', 'Wimbledon Championships', 'the grass-court Grand Slam tennis tournament in London', 'Londonis muruväljakutel peetav suure slämmi tenniseturniir', 'Wimbledon', 'Wimbledon'],
    ['Super_Bowl', 'Super Bowl', 'the championship game of the NFL', 'NFL-i meistrivõistluste finaalmäng', 'the Super Bowl', 'Super Bowl'],
    ['UEFA_Champions_League', 'UEFA Champions League', 'Europe’s leading men’s club football competition', 'Euroopa tähtsaim meeste klubijalgpalli võistlus', 'the UEFA Champions League', 'UEFA Meistrite Liiga'],
    ['Boston_Marathon', 'Boston Marathon', 'the famous annual road race in Massachusetts', 'kuulus iga-aastane maanteejooks Massachusettsis', 'the Boston Marathon', 'Bostoni maraton'],
    ['Rally_Estonia', 'Rally Estonia', 'Estonia’s major international rally event', 'Eesti suur rahvusvaheline rallivõistlus', 'Rally Estonia', 'Rally Estonia'],
    ['Vasaloppet', 'Vasaloppet', 'the long-distance cross-country ski race in Sweden', 'Rootsis peetav pikamaamurdmaasuusatamise võistlus', 'Vasaloppet', 'Vasaloppet'],
    ['24_Hours_of_Le_Mans', '24 Hours of Le Mans', 'the day-long endurance motor race in France', 'Prantsusmaal peetav ööpäevane kestvussõit', 'the 24 Hours of Le Mans', 'Le Mansi 24 tunni sõit'],
  ],
  (prompt) => `Name ${prompt}.`,
  (prompt) => `Nimeta ${prompt}.`,
  (prompt, answer) => `${answer} is ${prompt}.`,
  (prompt, answer) => `${answer} on ${prompt}.`),
  ...relationGroup('08-sports-games', 'games', [
    ['Chess', 'Chess', 'the board game featuring kings, queens, rooks, bishops, and knights', 'lauamäng kuningate, lippude, vankrite, odade ja ratsudega', 'chess', 'male'],
    ['Monopoly_(game)', 'Monopoly', 'the property-trading board game with Boardwalk and Park Place', 'kinnisvaraga kauplemise lauamäng Boardwalki ja Park Place’iga', 'Monopoly', 'Monopol'],
    ['Scrabble', 'Scrabble', 'the board game in which letter tiles form words', 'lauamäng, kus täheklotsidest moodustatakse sõnu', 'Scrabble', 'Scrabble'],
    ['Tetris', 'Tetris', 'the video game built around falling geometric blocks', 'langevate geomeetriliste klotsidega videomäng', 'Tetris', 'Tetris'],
    ['Super_Mario', 'Super Mario', 'the video-game series starring an Italian plumber in a red cap', 'punase mütsiga Itaalia torumehest videomängusari', 'Super Mario', 'Super Mario'],
    ['Minecraft', 'Minecraft', 'the block-building sandbox video game', 'klotsidest ehitamise liivakastivideomäng', 'Minecraft', 'Minecraft'],
    ['Pokémon', 'Pokémon', 'the game franchise whose slogan is “Gotta Catch ’Em All”', 'mängusari loosungiga „Gotta Catch ’Em All“', 'Pokémon', 'Pokémon'],
    ['Counter-Strike', 'Counter-Strike', 'the team-based shooter featuring terrorists and counter-terrorists', 'terroristide ja eriüksuslastega meeskondlik tulistamismäng', 'Counter-Strike', 'Counter-Strike'],
    ['Angry_Birds', 'Angry Birds', 'the Finnish game about launching birds at green pigs', 'Soome mäng, kus linde lennutatakse roheliste sigade pihta', 'Angry Birds', 'Angry Birds'],
    ['Uno_(card_game)', 'Uno', 'the card game in which players match colours and numbers', 'kaardimäng, kus sobitatakse värve ja numbreid', 'Uno', 'Uno'],
  ],
  (prompt) => `Name the game: ${prompt}.`,
  (prompt) => `Nimeta mäng: ${prompt}.`,
  (prompt, answer) => `The game is ${answer}: ${prompt}.`,
  (prompt, answer) => `Mäng on ${answer}: ${prompt}.`),
] as const;

const FOOD_DRINK = [
  ...relationGroup('09-food-drink', 'origins', [
    ['Pizza', 'Pizza', 'pizza', 'pitsa', 'Italy', 'Itaalia'],
    ['Sushi', 'Sushi', 'sushi', 'sushi', 'Japan', 'Jaapan'],
    ['Taco', 'Taco', 'tacos', 'takod', 'Mexico', 'Mehhiko'],
    ['Croissant', 'Croissant', 'the croissant', 'sarvesai', 'France', 'Prantsusmaa'],
    ['Paella', 'Paella', 'paella', 'paella', 'Spain', 'Hispaania'],
    ['Fish_and_chips', 'Fish and chips', 'fish and chips', 'fish and chips', 'the United Kingdom', 'Ühendkuningriik'],
    ['Kimchi', 'Kimchi', 'kimchi', 'kimchi', 'Korea', 'Korea'],
    ['Greek_salad', 'Greek salad', 'Greek salad', 'Kreeka salat', 'Greece', 'Kreeka'],
    ['Baguette', 'Baguette', 'the baguette', 'baguette', 'France', 'Prantsusmaa'],
    ['Hamburger', 'Hamburger', 'the hamburger in its modern popular form', 'hamburger selle tänapäevases populaarses vormis', 'the United States', 'Ameerika Ühendriigid'],
  ],
  (prompt) => `Which country is most associated with this food: ${prompt}?`,
  (prompt) => `Millise riigiga seostub kõige rohkem see toit: ${prompt}?`,
  (prompt, answer) => `The country is ${answer}: ${prompt}.`,
  (prompt, answer) => `Riik on ${answer}: ${prompt}.`),
  ...relationGroup('09-food-drink', 'ingredients', [
    ['Guacamole', 'Guacamole', 'guacamole', 'guacamole', 'avocado', 'avokaado'],
    ['Hummus', 'Hummus', 'hummus', 'hummus', 'chickpeas', 'kikerherned'],
    ['Pesto', 'Pesto', 'traditional green pesto', 'traditsiooniline roheline pesto', 'basil', 'basiilik'],
    ['Sauerkraut', 'Sauerkraut', 'sauerkraut', 'hapukapsas', 'cabbage', 'kapsas'],
    ['Marzipan', 'Marzipan', 'marzipan', 'martsipan', 'almonds', 'mandlid'],
    ['Tofu', 'Tofu', 'tofu', 'tofu', 'soybeans', 'sojaoad'],
    ['Popcorn', 'Popcorn', 'popcorn', 'popkorn', 'maize', 'mais'],
    ['Omelette', 'Omelette', 'an omelette', 'omlett', 'eggs', 'munad'],
    ['Mashed_potato', 'Mashed potato', 'mashed potatoes', 'kartulipuder', 'potatoes', 'kartulid'],
    ['Chocolate', 'Chocolate', 'chocolate', 'šokolaad', 'cocoa beans', 'kakaooad'],
  ],
  (prompt) => `What is the key ingredient in this food: ${prompt}?`,
  (prompt) => `Mis on selle toidu peamine koostisosa: ${prompt}?`,
  (prompt, answer) => `The key ingredient is ${answer}: ${prompt}.`,
  (prompt, answer) => `Peamine koostisosa on ${answer}: ${prompt}.`),
  ...relationGroup('09-food-drink', 'drinks', [
    ['Coffee', 'Coffee', 'the caffeinated drink brewed from roasted beans', 'röstitud ubadest valmistatav kofeiiniga jook', 'coffee', 'kohv'],
    ['Tea', 'Tea', 'the drink made by steeping leaves of Camellia sinensis', 'teepõõsa lehtede tõmbamisel saadav jook', 'tea', 'tee'],
    ['Orange_juice', 'Orange juice', 'the breakfast drink squeezed from oranges', 'apelsinidest pressitud hommikusöögijook', 'orange juice', 'apelsinimahl'],
    ['Hot_chocolate', 'Hot chocolate', 'the warm sweet drink made with chocolate or cocoa', 'šokolaadi või kakaoga valmistatav soe magus jook', 'hot chocolate', 'kuum šokolaad'],
    ['Smoothie', 'Smoothie', 'the thick blended drink commonly made from fruit', 'tavaliselt puuviljadest valmistatav paks püreestatud jook', 'a smoothie', 'smuuti'],
    ['Espresso', 'Espresso', 'the small concentrated coffee brewed under pressure', 'surve all valmistatav väike kange kohv', 'espresso', 'espresso'],
    ['Lemonade', 'Lemonade', 'the sweet-and-sour drink flavoured with lemon', 'sidrunimaitseline magushapu jook', 'lemonade', 'limonaad'],
    ['Milkshake', 'Milkshake', 'the cold blended drink made with milk and often ice cream', 'piimast ja sageli jäätisest valmistatav külm vahustatud jook', 'a milkshake', 'piimakokteil'],
    ['Mineral_water', 'Mineral water', 'water from a mineral spring', 'mineraalallikast pärinev vesi', 'mineral water', 'mineraalvesi'],
    ['Kefir', 'Kefir', 'the fermented milk drink made with kefir grains', 'keefiriterade abil kääritatud piimajook', 'kefir', 'keefir'],
  ],
  (prompt) => `Name the drink: ${prompt}.`,
  (prompt) => `Nimeta jook: ${prompt}.`,
  (prompt, answer) => `The drink is ${answer}: ${prompt}.`,
  (prompt, answer) => `Jook on ${answer}: ${prompt}.`),
  ...relationGroup('09-food-drink', 'everyday', [
    ['Breakfast', 'Breakfast', 'the first meal of the day', 'päeva esimene söögikord', 'breakfast', 'hommikusöök'],
    ['Dessert', 'Dessert', 'the sweet course commonly eaten at the end of a meal', 'toidukorra lõpus söödav magus käik', 'dessert', 'magustoit'],
    ['Vegetarianism', 'Vegetarianism', 'a diet that excludes meat', 'toitumisviis, mis välistab liha', 'a vegetarian diet', 'taimetoitlus'],
    ['Barbecue', 'Barbecue', 'cooking food outdoors over fire or hot coals', 'toidu valmistamine õues tule või kuumade süte kohal', 'barbecuing', 'grillimine'],
    ['Sandwich', 'Sandwich', 'a filling placed between slices of bread', 'täidis kahe leivaviilu vahel', 'a sandwich', 'võileib'],
    ['Soup', 'Soup', 'a mainly liquid dish often served hot', 'peamiselt vedel roog, mida serveeritakse sageli kuumalt', 'soup', 'supp'],
    ['Salad', 'Salad', 'a dish of mixed ingredients, often including raw vegetables', 'segatud koostisosadest, sageli toorestest köögiviljadest roog', 'a salad', 'salat'],
    ['Ice_cream', 'Ice cream', 'the frozen sweet dairy dessert', 'külmutatud magus piimatoode', 'ice cream', 'jäätis'],
    ['Pancake', 'Pancake', 'the flat cake cooked from batter in a pan', 'pannil tainast küpsetatud lame kook', 'a pancake', 'pannkook'],
    ['Cheese', 'Cheese', 'the food made by coagulating milk proteins', 'piimavalkude kalgendamisel valmistatav toit', 'cheese', 'juust'],
  ],
  (prompt) => `Name the food, meal, or cooking term: ${prompt}.`,
  (prompt) => `Nimeta toit, söögikord või toiduvalmistamise mõiste: ${prompt}.`,
  (prompt, answer) => `The answer is ${answer}: ${prompt}.`,
  (prompt, answer) => `Vastus on ${answer}: ${prompt}.`),
] as const;

const TECHNOLOGY = [
  ...relationGroup('10-technology-inventions', 'products', [
    ['iPhone', 'iPhone', 'the iPhone', 'iPhone’i', 'Apple', 'Apple'],
    ['Windows_95', 'Windows 95', 'Windows 95', 'Windows 95', 'Microsoft', 'Microsoft'],
    ['PlayStation', 'PlayStation', 'the PlayStation', 'PlayStationi', 'Sony', 'Sony'],
    ['Android_(operating_system)', 'Android', 'the Android operating system', 'Androidi operatsioonisüsteemi', 'Google', 'Google'],
    ['Kindle_Store', 'Kindle', 'the Kindle e-reader family', 'Kindle’i e-lugerite sarja', 'Amazon', 'Amazon'],
    ['Galaxy_S_series', 'Samsung Galaxy S series', 'the Galaxy S smartphone series', 'Galaxy S nutitelefonide sarja', 'Samsung', 'Samsung'],
    ['Xbox', 'Xbox', 'the Xbox console brand', 'Xboxi konsoolibrändi', 'Microsoft', 'Microsoft'],
    ['Nintendo_Switch', 'Nintendo Switch', 'the Switch hybrid game console', 'hübriidkonsooli Switch', 'Nintendo', 'Nintendo'],
    ['Nokia_3310', 'Nokia 3310', 'the famously durable 3310 mobile phone', 'kuulsa vastupidava mobiiltelefoni 3310', 'Nokia', 'Nokia'],
    ['Raspberry_Pi', 'Raspberry Pi', 'the affordable Raspberry Pi single-board computer', 'soodsa üheplaadiarvuti Raspberry Pi', 'the Raspberry Pi Foundation', 'Raspberry Pi Foundation'],
  ],
  (prompt) => `Which company or organisation introduced ${prompt}?`,
  (prompt) => `Milline ettevõte või organisatsioon tõi turule ${prompt}?`,
  (prompt, answer) => `${answer} introduced ${prompt}.`,
  (prompt, answer) => `${answer} tõi turule ${prompt}.`),
  ...relationGroup('10-technology-inventions', 'web', [
    ['World_Wide_Web', 'World Wide Web', 'the system of linked pages accessed through a browser', 'brauseriga avatavate omavahel lingitud lehtede süsteem', 'the World Wide Web', 'veeb'],
    ['Email', 'Email', 'electronic messages sent between digital addresses', 'digitaalsete aadresside vahel saadetavad elektroonilised sõnumid', 'email', 'e-post'],
    ['Wi-Fi', 'Wi-Fi', 'wireless local networking commonly used to connect devices to the internet', 'juhtmeta kohtvõrk, millega seadmed tavaliselt internetti ühendatakse', 'Wi-Fi', 'Wi-Fi'],
    ['Bluetooth', 'Bluetooth', 'the short-range wireless standard named after a Danish king', 'Taani kuninga järgi nimetatud lähiala juhtmevaba standard', 'Bluetooth', 'Bluetooth'],
    ['Search_engine', 'Search engine', 'a service used to find pages and information on the web', 'veebilehtede ja teabe leidmiseks kasutatav teenus', 'a search engine', 'otsingumootor'],
    ['QR_code', 'QR code', 'the square two-dimensional barcode scanned by phone cameras', 'telefonikaameraga loetav ruudukujuline kahemõõtmeline vöötkood', 'a QR code', 'QR-kood'],
    ['Hashtag', 'Hashtag', 'a word or phrase preceded by the # symbol on social media', 'sotsiaalmeedias #-märgiga algav sõna või fraas', 'a hashtag', 'teemaviide'],
    ['Emoji', 'Emoji', 'a small pictogram used in digital messages', 'digisõnumites kasutatav väike piltmärk', 'an emoji', 'emoji'],
    ['Cloud_computing', 'Cloud computing', 'using remote internet servers to store or process data', 'kaugserverite kasutamine andmete hoidmiseks või töötlemiseks', 'cloud computing', 'pilvandmetöötlus'],
    ['Password', 'Password', 'a secret string used to verify access to an account', 'konto kasutusõiguse kontrollimiseks kasutatav salajane märgijada', 'a password', 'parool'],
  ],
  (prompt) => `Name the technology term: ${prompt}.`,
  (prompt) => `Nimeta tehnoloogiamõiste: ${prompt}.`,
  (prompt, answer) => `The term is ${answer}: ${prompt}.`,
  (prompt, answer) => `Mõiste on ${answer}: ${prompt}.`),
  ...relationGroup('10-technology-inventions', 'inventors', [
    ['Telephone', 'Telephone', 'the telephone', 'telefoni', 'Alexander Graham Bell', 'Alexander Graham Bell'],
    ['World_Wide_Web', 'World Wide Web', 'the World Wide Web', 'veebi', 'Tim Berners-Lee', 'Tim Berners-Lee'],
    ['Printing_press', 'Printing press', 'the movable-type printing press in Europe', 'Euroopa trükipressi liikuvate trükitähtedega', 'Johannes Gutenberg', 'Johannes Gutenberg'],
    ['Light_bulb', 'Light bulb', 'a practical long-lasting incandescent light bulb', 'praktilise pikaealise hõõglambi', 'Thomas Edison', 'Thomas Edison'],
    ['Dynamite', 'Dynamite', 'dynamite', 'dünamiidi', 'Alfred Nobel', 'Alfred Nobel'],
    ['Penicillin', 'Penicillin', 'penicillin’s antibacterial effect', 'penitsilliini antibakteriaalse toime', 'Alexander Fleming', 'Alexander Fleming'],
    ['Radio', 'Radio', 'early practical radio communication', 'varajase praktilise raadioside', 'Guglielmo Marconi', 'Guglielmo Marconi'],
    ['Steam_engine', 'Steam engine', 'major improvements to the steam engine', 'aurumasina olulised täiustused', 'James Watt', 'James Watt'],
    ['Braille', 'Braille', 'the raised-dot reading system', 'reljeefsetel punktidel põhineva kirjasüsteemi', 'Louis Braille', 'Louis Braille'],
    ['Diesel_engine', 'Diesel engine', 'the diesel engine', 'diiselmootori', 'Rudolf Diesel', 'Rudolf Diesel'],
  ],
  (prompt) => `Who is commonly associated with inventing or developing ${prompt}?`,
  (prompt) => `Keda seostatakse tavaliselt järgmise leiutamise või arendamisega: ${prompt}?`,
  (prompt, answer) => `${answer} is commonly associated with ${prompt}.`,
  (prompt, answer) => `${answer} seostatakse tavaliselt järgmisega: ${prompt}.`),
  ...relationGroup('10-technology-inventions', 'abbreviations', [
    ['Global_Positioning_System', 'Global Positioning System', 'GPS', 'GPS', 'Global Positioning System', 'globaalne positsioneerimissüsteem'],
    ['Universal_Serial_Bus', 'USB', 'USB', 'USB', 'Universal Serial Bus', 'Universal Serial Bus'],
    ['Hypertext_Transfer_Protocol', 'HTTP', 'HTTP', 'HTTP', 'Hypertext Transfer Protocol', 'hüperteksti edastusprotokoll'],
    ['Portable_Document_Format', 'PDF', 'PDF', 'PDF', 'Portable Document Format', 'porditav dokumendivorming'],
    ['Central_processing_unit', 'Central processing unit', 'CPU', 'CPU', 'central processing unit', 'keskprotsessor'],
    ['Random-access_memory', 'Random-access memory', 'RAM', 'RAM', 'random-access memory', 'muutmälu'],
    ['Short_Message_Service', 'SMS', 'SMS', 'SMS', 'Short Message Service', 'lühisõnumiteenus'],
    ['Subscriber_identity_module', 'SIM card', 'SIM', 'SIM', 'subscriber identity module', 'abonendi identifitseerimismoodul'],
    ['High-definition_television', 'High-definition television', 'HD', 'HD', 'high definition', 'kõrglahutus'],
    ['Artificial_intelligence', 'Artificial intelligence', 'AI', 'AI', 'artificial intelligence', 'tehisintellekt'],
  ],
  (prompt) => `In technology, what does ${prompt} stand for?`,
  (prompt) => `Mida tähendab tehnoloogias lühend ${prompt}?`,
  (prompt, answer) => `${prompt} stands for ${answer}.`,
  (prompt, answer) => `${prompt} tähendab: ${answer}.`),
] as const;

const SOCIETY = [
  ...relationGroup('11-politics-economics-society', 'institutions', [
    ['European_Union', 'European Union', 'the political and economic union abbreviated EU', 'poliitiline ja majanduslik liit lühendiga EL', 'the European Union', 'Euroopa Liit'],
    ['United_Nations', 'United Nations', 'the international organisation abbreviated UN', 'rahvusvaheline organisatsioon lühendiga ÜRO', 'the United Nations', 'Ühinenud Rahvaste Organisatsioon'],
    ['NATO', 'NATO', 'the North Atlantic military alliance', 'Põhja-Atlandi sõjaline liit', 'NATO', 'NATO'],
    ['European_Parliament', 'European Parliament', 'the directly elected legislative body of the European Union', 'Euroopa Liidu otse valitav seadusandlik kogu', 'the European Parliament', 'Euroopa Parlament'],
    ['World_Health_Organization', 'World Health Organization', 'the UN health agency abbreviated WHO', 'ÜRO terviseagentuur lühendiga WHO', 'the World Health Organization', 'Maailma Terviseorganisatsioon'],
    ['International_Red_Cross_and_Red_Crescent_Movement', 'International Red Cross and Red Crescent Movement', 'the humanitarian movement symbolised by a red cross or crescent', 'punase risti või poolkuuga tähistatud humanitaarliikumine', 'the Red Cross and Red Crescent Movement', 'Punase Risti ja Punase Poolkuu liikumine'],
    ['UNESCO', 'UNESCO', 'the UN agency associated with World Heritage Sites', 'maailmapärandi paikadega seotud ÜRO organisatsioon', 'UNESCO', 'UNESCO'],
    ['International_Olympic_Committee', 'International Olympic Committee', 'the organisation that oversees the modern Olympic Games', 'nüüdisaegseid olümpiamänge juhtiv organisatsioon', 'the International Olympic Committee', 'Rahvusvaheline Olümpiakomitee'],
    ['Bank_of_Estonia', 'Bank of Estonia', 'Estonia’s central bank, Eesti Pank', 'Eesti keskpank', 'the Bank of Estonia', 'Eesti Pank'],
    ['Riigikogu', 'Riigikogu', 'Estonia’s national parliament', 'Eesti riigi parlament', 'the Riigikogu', 'Riigikogu'],
  ],
  (prompt) => `Name the organisation: ${prompt}.`,
  (prompt) => `Nimeta organisatsioon: ${prompt}.`,
  (prompt, answer) => `The organisation is ${answer}: ${prompt}.`,
  (prompt, answer) => `Organisatsioon on ${answer}: ${prompt}.`),
  ...relationGroup('11-politics-economics-society', 'currencies', [
    ['Euro', 'Euro', 'Estonia, Finland, Germany, and many other EU countries', 'Eestis, Soomes, Saksamaal ja paljudes teistes EL-i riikides', 'the euro', 'euro'],
    ['Pound_sterling', 'Pound sterling', 'the United Kingdom', 'Ühendkuningriigis', 'the pound sterling', 'naelsterling'],
    ['United_States_dollar', 'United States dollar', 'the United States', 'Ameerika Ühendriikides', 'the US dollar', 'USA dollar'],
    ['Swedish_krona', 'Swedish krona', 'Sweden', 'Rootsis', 'the Swedish krona', 'Rootsi kroon'],
    ['Norwegian_krone', 'Norwegian krone', 'Norway', 'Norras', 'the Norwegian krone', 'Norra kroon'],
    ['Danish_krone', 'Danish krone', 'Denmark', 'Taanis', 'the Danish krone', 'Taani kroon'],
    ['Swiss_franc', 'Swiss franc', 'Switzerland', 'Šveitsis', 'the Swiss franc', 'Šveitsi frank'],
    ['Japanese_yen', 'Japanese yen', 'Japan', 'Jaapanis', 'the yen', 'jeen'],
    ['Polish_złoty', 'Polish złoty', 'Poland', 'Poolas', 'the złoty', 'zlott'],
    ['Renminbi', 'Renminbi', 'China', 'Hiinas', 'the renminbi', 'jüaan'],
  ],
  (prompt) => `Which currency is used in ${prompt}?`,
  (prompt) => `Millist raha kasutatakse ${prompt}?`,
  (prompt, answer) => `${answer[0].toUpperCase()}${answer.slice(1)} is used in ${prompt}.`,
  (prompt, answer) => `${answer[0].toUpperCase()}${answer.slice(1)} kasutatakse ${prompt}.`),
  ...relationGroup('11-politics-economics-society', 'civics', [
    ['Democracy', 'Democracy', 'a system in which citizens choose representatives through elections', 'kord, kus kodanikud valivad esindajad valimistel', 'democracy', 'demokraatia'],
    ['Constitution', 'Constitution', 'the fundamental set of rules by which a state is governed', 'riigi valitsemise aluseks olev põhireeglite kogum', 'a constitution', 'põhiseadus'],
    ['Election', 'Election', 'the process of choosing a person for public office by voting', 'avaliku ameti kandja valimine hääletamise teel', 'an election', 'valimised'],
    ['Separation_of_powers', 'Separation of powers', 'the principle that divides state authority among legislative, executive, and judicial branches', 'põhimõte, mis jagab riigivõimu seadusandliku, täidesaatva ja kohtuvõimu vahel', 'separation of powers', 'võimude lahusus'],
    ['Mayor', 'Mayor', 'the elected or appointed head of a city government', 'linna valitud või määratud juht', 'a mayor', 'linnapea'],
    ['Tax', 'Tax', 'a compulsory payment collected by government', 'riigi kogutav kohustuslik makse', 'a tax', 'maks'],
    ['Referendum', 'Referendum', 'a direct public vote on a specific proposal', 'rahva otsene hääletus kindla küsimuse üle', 'a referendum', 'rahvahääletus'],
    ['Citizenship', 'Citizenship', 'legal membership of a country', 'õiguslik kuulumine riigi kodanike hulka', 'citizenship', 'kodakondsus'],
    ['Political_party', 'Political party', 'an organised group seeking political power through elections', 'valimiste kaudu poliitilist võimu taotlev organiseeritud rühm', 'a political party', 'erakond'],
    ['Embassy', 'Embassy', 'a country’s official diplomatic mission in another country', 'riigi ametlik diplomaatiline esindus teises riigis', 'an embassy', 'saatkond'],
  ],
  (prompt) => `What civic term means ${prompt}?`,
  (prompt) => `Milline ühiskonnaõpetuse mõiste tähendab järgmist: ${prompt}?`,
  (prompt, answer) => `${answer[0].toUpperCase()}${answer.slice(1)} means ${prompt}.`,
  (prompt, answer) => `${answer[0].toUpperCase()}${answer.slice(1)} tähendab järgmist: ${prompt}.`),
  ...relationGroup('11-politics-economics-society', 'estonia', [
    ['Flag_of_Estonia', 'Flag of Estonia', 'blue, black, and white', 'sinine, must ja valge', 'the Estonian flag', 'Eesti lipp'],
    ['Independence_Day_(Estonia)', 'Independence Day (Estonia)', '24 February', '24. veebruar', 'Estonian Independence Day', 'Eesti Vabariigi aastapäev'],
    ['Estonian_language', 'Estonian language', 'Estonia’s official language', 'Eesti riigikeel', 'Estonian', 'eesti keel'],
    ['Eurovision_Song_Contest_2001', 'Eurovision Song Contest 2001', 'the country represented by Tanel Padar, Dave Benton, and 2XL when they won Eurovision 2001', 'riik, mida esindasid 2001. aasta Eurovisiooni võitnud Tanel Padar, Dave Benton ja 2XL', 'Estonia', 'Eesti'],
    ['Singing_Revolution', 'Singing Revolution', 'the peaceful national movement that helped restore Baltic independence', 'Balti riikide iseseisvuse taastamisele kaasa aidanud rahumeelne rahvuslik liikumine', 'the Singing Revolution', 'laulev revolutsioon'],
    ['Estonian_Song_Festival', 'Estonian Song Festival', 'the huge choral festival held in Tallinn roughly every five years', 'Tallinnas umbes iga viie aasta järel peetav hiiglaslik kooripidu', 'the Estonian Song Festival', 'Eesti laulupidu'],
    ['Skype', 'Skype', 'the internet-calling service whose software was developed by Estonian engineers', 'internetikõnede teenus, mille tarkvara arendasid Eesti insenerid', 'Skype', 'Skype'],
    ['E-residency_of_Estonia', 'E-residency of Estonia', 'Estonia’s digital identity programme for non-residents', 'Eesti digitaalne isikutunnistuse programm mitteresidentidele', 'e-Residency', 'e-residentsus'],
    ['Estonian_kroon', 'Estonian kroon', 'Estonia’s currency immediately before the euro', 'Eesti raha vahetult enne eurot', 'the kroon', 'kroon'],
    ['Coat_of_arms_of_Estonia', 'Coat of arms of Estonia', 'the three blue lions on Estonia’s national coat of arms', 'kolm sinist lõvi Eesti riigivapil', 'the coat of arms of Estonia', 'Eesti riigivapp'],
  ],
  (prompt) => `Name the Estonian symbol, event, or idea: ${prompt}.`,
  (prompt) => `Nimeta Eesti sümbol, sündmus või idee: ${prompt}.`,
  (prompt, answer) => `The answer is ${answer}: ${prompt}.`,
  (prompt, answer) => `Vastus on ${answer}: ${prompt}.`),
] as const;

export function buildAccessibleEasyQuestions(): AccessibleEasyQuestion[] {
  return [
    ...HISTORY,
    ...GEOGRAPHY,
    ...SCIENCE,
    ...LITERATURE,
    ...MUSIC,
    ...FILM_TELEVISION,
    ...SPORTS_GAMES,
    ...FOOD_DRINK,
    ...TECHNOLOGY,
    ...SOCIETY,
  ];
}

export function applyAccessibleEasyQuestions(
  rows: readonly Record<string, string>[],
  questions: readonly AccessibleEasyQuestion[],
  openTdbInspirations: readonly OpenTdbInspiration[] = [],
): { rows: Array<Record<string, string>>; evidence: ContentEvidence[]; replacedClueIds: string[] } {
  if (questions.length !== 40) throw new Error(`An accessible-easy batch requires 40 questions; found ${questions.length}`);
  const batchIds = new Set(questions.map((question) => question.batchId));
  if (batchIds.size !== 1) throw new Error('Accessible-easy replacement questions must belong to one batch');

  const categoryRows = new Map<string, Array<Record<string, string>>>();
  for (const row of rows) {
    if (row.content_kind !== 'board' || row.difficulty !== 'easy') continue;
    const set = categoryRows.get(row.category_set_id) ?? [];
    set.push(row);
    categoryRows.set(row.category_set_id, set);
  }
  const slots = [...categoryRows.values()].slice(0, 8);
  if (slots.length !== 8 || slots.some((slot) => slot.length !== 5)) {
    throw new Error('Accessible-easy replacement requires eight complete easy category sets');
  }

  const replacements = new Map<string, Record<string, string>>();
  const evidence: ContentEvidence[] = [];
  const replacedClueIds: string[] = [];
  for (const [setIndex, slot] of slots.entries()) {
    const orderedSlot = [...slot].sort((left, right) => Number(left.tier) - Number(right.tier));
    const questionSet = questions.slice(setIndex * 5, setIndex * 5 + 5);
    for (const [tierIndex, row] of orderedSlot.entries()) {
      const question = questionSet[tierIndex];
      const clueId = `${row.pack_id}-accessible-easy-${String(setIndex * 5 + tierIndex + 1).padStart(3, '0')}`;
      replacedClueIds.push(row.clue_id);
      replacements.set(row.clue_id, {
        ...row,
        clue_id: clueId,
        clue_en: question.clue.en,
        clue_et: question.clue.et,
        response_en: question.response.en,
        response_et: question.response.et,
        accepted_variants_en: '',
        accepted_variants_et: '',
        explanation_en: question.explanation.en,
        explanation_et: question.explanation.et,
        source_title: question.source.title,
        source_url: question.source.url,
        source_license: question.source.license,
        source_retrieved_at: '2026-08-27',
        translation_status: 'reviewed',
        enabled: 'true',
      });
      const inspiration = openTdbInspirations[evidence.length];
      evidence.push({
        version: 1,
        clueId,
        batchId: question.batchId,
        factKey: `accessible-easy:${question.key}`,
        subjectKey: question.subjectKey,
        assertion: `${question.response.en} — ${question.explanation.en}`,
        origin: inspiration === undefined ? 'compatibleOpen' : 'openTdbInspired',
        authoring: {
          author: 'Codex Accessible Trivia Author',
          authoredAt: '2026-08-27T19:00:00.000Z',
        },
        supportingSource: {
          sourceId: question.subjectKey,
          title: question.source.title,
          url: question.source.url,
          license: question.source.license,
          retrievedAt: '2026-08-27',
        },
        inspiration: inspiration ?? null,
        factualReview: {
          reviewer: 'Codex Accessible Trivia Factual Reviewer',
          reviewedAt: '2026-08-27T20:00:00.000Z',
          decision: 'approved',
        },
        editorialReview: {
          reviewer: 'Codex Accessible Trivia Editorial Reviewer',
          reviewedAt: '2026-08-27T20:30:00.000Z',
          decision: 'approved',
        },
        translationReview: {
          reviewer: 'Codex Estonian Semantic Reviewer',
          reviewedAt: '2026-08-27T21:00:00.000Z',
          decision: 'approved',
        },
        adultPolicyReview: null,
      });
    }
  }

  return {
    rows: rows.map((row) => replacements.get(row.clue_id) ?? row),
    evidence,
    replacedClueIds,
  };
}
import type { ContentEvidence } from './evidence';
