export const IPC_CHANNELS = {
  dispatch: 'quiz-stage:dispatch',
  startMatch: 'quiz-stage:start-match',
  contentAvailability: 'quiz-stage:content-availability',
  setupOptions: 'quiz-stage:setup-options',
  hasResumableMatch: 'quiz-stage:has-resumable-match',
  resumeMatch: 'quiz-stage:resume-match',
  listHistory: 'quiz-stage:list-history',
  contentImportPreview: 'quiz-stage:content:import-preview',
  contentImportCommit: 'quiz-stage:content:import-commit',
  contentImportDiscard: 'quiz-stage:content:import-discard',
  contentExport: 'quiz-stage:content:export',
  contentList: 'quiz-stage:content:list',
  contentSaveCategory: 'quiz-stage:content:save-category',
  contentSaveFinal: 'quiz-stage:content:save-final',
  contentCreatePack: 'quiz-stage:content:create-pack',
  contentDeletePack: 'quiz-stage:content:delete-pack',
  contentReportClue: 'quiz-stage:content:report-clue',
  contentResolveReport: 'quiz-stage:content:resolve-report',
  audioSettingsGet: 'quiz-stage:audio-settings:get',
  audioSettingsUpdate: 'quiz-stage:audio-settings:update',
  mediaWarning: 'quiz-stage:media-warning',
  hostState: 'quiz-stage:state:host',
  publicState: 'quiz-stage:state:public',
  hostReady: 'quiz-stage:ready:host',
  publicReady: 'quiz-stage:ready:public',
} as const;
